(mes
 (meta (engine 'ADV) (charset "english") (extraop #t))
 (seg*
  (if (</>
       (//
        (? (= K 1))
        ((cmd 209) 0 5)
        (image-file "gpc¥waku.gpc")
        (image-mem 0 3)
        ((cmd 209) 1 5)
        (nop@)
        (set-var K 0))
       (// (nop@))))
  (branch-reg 54 (</> (/) (/ (mes-jump "mes¥ma_a02.mes"))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b13_01.gpc")
  (image-mem 0 3)
  (proc 3)
  (if (</>
       (//
        (? (= P 5))
        (nop@))
       (//
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))))
  (load-mem "clm¥b13_01.clm" 32768)
  (text-frame 10 312 70 373)
  (text-delay 2)
  (if (</>
       (//
        (? (= 200 #t))
        (if (</>
             (//
              (? (= 53 #t) (= 52 #t))
              (nop@)
              (text "I'm back at my room in the Intelligence Division. It's time  to get down to business......"))
             (//
              (? (= 53 #t) (= 52 #f))
              (nop@)
              (text "I probably shouldn't just wander around aimlessly. Maybe Annahas some useful information......"))
             (//
              (text "I'm back at my room again. The air here is stale...... I'd   rather wander the city than stay in a place like this."))))
        (wait)
        (text-reset))
       (//
        (? (= 200 #f))
        (text "After leaving Anna and Katou behind in the office, I headed" 'br)
        (text "to my room in intelligence headquarters.")
        (wait)
        (text-reset)
        (text "I haven't been back here in nearly 2 months. Thanks to havingAnna's complete support, I was able to choose when to take onnew missions.")
        (wait)
        (text-reset)
        (text "That is, until now......")
        (wait)
        (text-reset)
        ;; comments should NOT make a difference!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        (text "This luxurious room is also a result of being Anna's agent.  Because of it, I didn't get eaten alive by the other         uniformed bastards.")
        (wait)
        (text-reset)
        (text "But now, with Anna's protection no longer certain, I wonder  if my luck will finally run out.")
        (wait)
        (text-reset)
        (text "Either way, I need to talk with Anna alone.")
        (wait)
        (text-reset)
        (nop@)
        (set-reg 200 #t))))
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t))
   (nop@)
   (set-var K 0)
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (if (</>
        (//
         (? (= 202 #t) (= 204 #t) (= 206 #t) (= 208 #t))
         (exec-mem 4768 4 8 12 6 1 0 0 4480 4480 1 0))
        (// (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0))))
   (menu1
    5
    72
    5
    88
    (</>
     (/ (text "   Save   "))
     (/
      (set-reg 202 #t)
      (set-reg 204 #t)
      (set-reg 206 #t)
      (set-reg 208 #t)
      (nop@)
      (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 16 96")
         (exec-mem 4768 5 9 16 12 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          6
          112
          6
          128
          6
          144
          (</>
           (/ (text "    File 1    "))
           (/ (text "    File 2    "))
           (/ (text "    File 3    "))
           (/ (text "    File 4    "))
           (/ (text "    File 5    "))
           (/)))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (nop@)
         (set-var J P)
         (nop@)
         (set-var P 0)
         (if (</>
              (//
               (? (= S 0))
               (nop@)
               (set-var K 1)
               (flag-save 0)
               (nop@)
               (set-var K 0)
               (text "Successfully saved to File 1.")
               (wait)
               (text-reset 14))
              (//
               (? (= S 1))
               (nop@)
               (set-var K 1)
               (flag-save 1)
               (nop@)
               (set-var K 0)
               (text "Successfully saved to File 2.")
               (wait)
               (text-reset 14))
              (//
               (? (= S 2))
               (nop@)
               (set-var K 1)
               (flag-save 2)
               (nop@)
               (set-var K 0)
               (text "Successfully saved to File 3.")
               (wait)
               (text-reset 14))
              (//
               (? (= S 3))
               (nop@)
               (set-var K 1)
               (flag-save 3)
               (nop@)
               (set-var K 0)
               (text "Successfully saved to File 4.")
               (wait)
               (text-reset 14))
              (//
               (? (= S 4))
               (nop@)
               (set-var K 1)
               (flag-save 4)
               (nop@)
               (set-var K 0)
               (text "Successfully saved to File 5.")
               (wait)
               (text-reset 14))
              (// (? (= S 255)))))
         (nop@)
         (set-var P J))
        (//
         (? (= S 1))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 8 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          6
          112
          (</>
           (/ (text "   Anna's Office   "))
           (/ (text "    Anna's Room    "))
           (/ (text "      Outside      "))
           (/)))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (nop@)
               (set-reg 51 #t)
               (mes-jump "mes¥MA_B01.MES"))
              (//
               (? (= S 1))
               (nop@)
               (set-reg 51 #t)
               (mes-jump "mes¥MA_C01.MES"))
              (//
               (? (= S 2))
               (nop@)
               (set-reg 51 #t)
               (mes-jump "mes¥MB_A01.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= S 1) (= 201 #f))
   (proc 0)
   (text "This room has desks and chairs to keep up appearances, but I barely ever use them.")
   (wait)
   (text-reset)
   (text "I never really had a reason to. Desk work doesn't suit me,   and I don't consider it my job.")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 201 #t)
   (proc 1))
 (seg (? (= S 1) (= 202 #f))
   (proc 0)
   (text "It must have been used by another Intelligence agent before Iearned this room. It's an old-looking and scuffed desk.")
   (wait)
   (text-reset)
   (text "It's not worth complaining about, since I rarely use it      anyway.")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 202 #t)
   (proc 1))
 (seg (? (= S 1) (= 202 #t))
   (proc 0)
   (text "It's an old and worn desk. The last person to have this room probably used it a lot.")
   (wait)
   (text-reset)
   (proc 1))
 (seg (? (= S 2) (= 203 #f))
   (proc 0)
   (text "It's filled with an assortment of torture tools, as well as  other items I use to take care of \"problematic\" situations.")
   (wait)
   (text-reset)
   (text "I don't need them now, but it wouldn't hurt to take a quick  inventory...")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 203 #t)
   (proc 1))
 (seg (? (= S 2) (= 204 #f))
   (proc 0)
   (text "The shelves are filled with tools used to torture prisoners. Whips, vibrators, enemas, and even more exotic things...")
   (wait)
   (text-reset)
   (text "All these tools are hand-picked by me. Nobody has been able  to resist crying out when I use them. For now, I don't need  them until I catch the prisoners...")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 204 #t)
   (proc 1))
 (seg (? (= S 2) (= 204 #t))
   (proc 0)
   (text "I don't need to open this until I catch one of the prisoners.")
   (wait)
   (text-reset)
   (proc 1))
 (seg (? (= S 3) (= 205 #f))
   (proc 0)
   (text "My room is on the fifth floor... well, what would be the     fifth floor if we were above ground. The view is alright,    but the VIP spots in this city are even deeper underground.")
   (wait)
   (text-reset)
   (text "If the scaffolding that makes up our sky one day collapsed   and fell down, all these exposed buildings wouldn't          stand a chance.")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 205 #t)
   (proc 1))
 (seg (? (= S 3) (= 206 #f))
   (proc 0)
   (text "Outside the window is a war memorial. The pillar stands at   least three stories tall, covered in the names of soldiers   who've died for our nation.")
   (wait)
   (text-reset)
   (text "The tower has gotten larger and fuller since I last saw it.  It's amazing how much the view has changed after just a      couple months of not using this room.")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 206 #t)
   (proc 1))
 (seg (? (= S 3) (= 206 #t))
   (proc 0)
   (text "Outside the window is a growing memorial to our soldiers     who've died across the globe.")
   (wait)
   (text-reset)
   (proc 1))
 (seg (? (= S 4) (= 52 #t))
   (proc 0)
   (text "I have no choice but to go see the former superior of the twoprisoners that Anna mentioned. Hopefully I can get some      information...")
   (wait)
   (text-reset)
   (proc 1))
 (seg (? (= S 4) (= 207 #f))
   (proc 0)
   (text "I wonder how much better I would feel if I went back to      Anna's office and beat the crap out of Katou.")
   (wait)
   (text-reset)
   (text "I don't know what Anna's true intentions behind this mission are. All I know is that I've been dragged into one hell of   a mess.")
   (wait)
   (text-reset)
   (text "Honestly, I have no idea how I'm supposed to find the        prisoners.")
   (wait)
   (text-reset)
   (text "This city is full of all kinds of criminals and fugitives.   If they were to hide out in Chiba or Chinatown, finding them would be nearly impossible.")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 207 #t)
   (proc 1))
 (seg (? (= S 4) (= 208 #f))
   (proc 0)
   (text "They told me to \"catch the prisoners\". But with almost no    information on them - no histories, no faces - how am I      supposed to find them?!")
   (wait)
   (text-reset)
   (text "This mission is totally unlike anything I've done. I've neverheard of a leak in our intel corps before, nor of this many  prisoners escaping at once.")
   (wait)
   (text-reset)
   (text "Also, there must be a reason why Katou, the \"internal affairsinspector\", is involved in this mission. Is there really a   traitor in our ranks?......")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 208 #t)
   (proc 1))
 (seg (? (= S 4) (= 208 #t))
   (proc 0)
   (text "Anna wanted me to come to her room......" 'br)
   (text "It's somewhere here in intel headquarters, so I guess I      should make my way over.")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 209 #t)
   (proc 1)))