(mes
 (meta (engine 'ADV) (charset "english") (extraop #t))
 (seg*
  (if (</>
       (//
        (? (= K 1))
        ((cmd 209) 0 5)
        (image-file "gpc¥waku.gpc")
        (image-mem 0 3)
        ((cmd 209) 1 5)
        (nop@)
        (set-var K 0))
       (// (nop@))))
  (branch-reg 54 (</> (/) (/ (mes-jump "mes¥ma_a02.mes"))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b13_01.gpc")
  (image-mem 0 3)
  (proc 3)
  (if (</>
       (//
        (? (= P 5))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (load-mem "clm¥b13_01.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 200 #t))
        (if (</>
             (//
              (? (= 53 #t) (= 52 #t))
              (nop@)
              (text "情報部内にある、わたしの自室に戻った。そろそろ本気で仕事にかからなければ‥‥‥"))
             (//
              (? (= 53 #t) (= 52 #f))
              (nop@)
              (text "あてもなくウロついてても意味がないようだ。アンナなら、もっと情報を持っているかも‥‥‥"))
             (//
              (text
               "情報部内にある、わたしの自室に戻った。ここは息が詰まる‥‥‥こんな所に居るくらいなら、さっさと出かけた方がましだ。"))))
        (wait)
        (text-reset))
       (//
        (? (= 200 #f))
        (text "アンナと加藤のいるオフィスを後にしたわたしは、情報部ビルの中に設けられた自室にやって来た。")
        (wait)
        (text-reset)
        (text "この部屋にやって来るのは、ほぼ２ヶ月ぶりだ。わたしはアンナの完璧な庇護の下にある為、仕事を選ぶ事ができたのだ。")
        (wait)
        (text-reset)
        (text "それも、「今までは」だが‥‥‥‥‥‥")
        (wait)
        (text-reset)
        (text "こんな上等の部屋をあてがわれたのも、アンナの部下だから。制服野郎どもの食い物にされる事がなかったのもそうだ。")
        (wait)
        (text-reset)
        (text "しかし、これからは考えなければならないのだろうか。アンナに全面的な信頼を置く事が難しくなってきた。")
        (wait)
        (text-reset)
        (text "どちらにしても、アンナとふたりきりで話さなければ。")
        (wait)
        (text-reset)
        (nop@)
        (set-reg 200 #t))))
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t))
   (nop@)
   (set-var K 0)
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (if (</>
        (//
         (? (= 202 #t) (= 204 #t) (= 206 #t) (= 208 #t))
         (exec-mem 4768 4 8 12 6 1 0 0 4480 4480 1 0))
        (// (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0))))
   (menu1
    5
    72
    5
    88
    (</>
     (/ (text "　セーブ　"))
     (/
      (set-reg 202 #t)
      (set-reg 204 #t)
      (set-reg 206 #t)
      (set-reg 208 #t)
      (nop@)
      (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 16 96")
         (exec-mem 4768 5 9 16 12 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          6
          112
          6
          128
          6
          144
          (</>
           (/ (text "　ファイル１　"))
           (/ (text "　ファイル２　"))
           (/ (text "　ファイル３　"))
           (/ (text "　ファイル４　"))
           (/ (text "　ファイル５　"))
           (/)))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (nop@)
         (set-var J P)
         (nop@)
         (set-var P 0)
         (if (</>
              (//
               (? (= S 0))
               (nop@)
               (set-var K 1)
               (flag-save 0)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (//
               (? (= S 1))
               (nop@)
               (set-var K 1)
               (flag-save 1)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (//
               (? (= S 2))
               (nop@)
               (set-var K 1)
               (flag-save 2)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (//
               (? (= S 3))
               (nop@)
               (set-var K 1)
               (flag-save 3)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (//
               (? (= S 4))
               (nop@)
               (set-var K 1)
               (flag-save 4)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (// (? (= S 255)))))
         (nop@)
         (set-var P J))
        (//
         (? (= S 1))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 8 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          6
          112
          (</>
           (/ (text "　アンナのオフィス　"))
           (/ (text "　　アンナの部屋　　"))
           (/ (text "　　　外に出る　　　"))
           (/)))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (nop@)
               (set-reg 51 #t)
               (mes-jump "mes¥MA_B01.MES"))
              (//
               (? (= S 1))
               (nop@)
               (set-reg 51 #t)
               (mes-jump "mes¥MA_C01.MES"))
              (//
               (? (= S 2))
               (nop@)
               (set-reg 51 #t)
               (mes-jump "mes¥MB_A01.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= S 1) (= 201 #f))
   (proc 0)
   (text "体裁を整える為に机と椅子が置かれてはいるが、わたし自身はほとんど使った事がない。")
   (wait)
   (text-reset)
   (text "わたしにはデスクワークは似合わないし、自分の仕事だとも思っていない。")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 201 #t)
   (proc 1))
 (seg (? (= S 1) (= 202 #f))
   (proc 0)
   (text "わたしがこの部屋を占領する以前にも、情報部の誰かが使っていたんだろう、かなり古びている。")
   (wait)
   (text-reset)
   (text "もっとも、それに文句をつけるつもりは無い。わたし自身はほとんど使う機会はないんだから。")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 202 #t)
   (proc 1))
 (seg (? (= S 1) (= 202 #t))
   (proc 0)
   (text "わたしがこの部屋を占領する以前にも、情報部の誰かが使っていたんだろう、かなり古びている。")
   (wait)
   (text-reset)
   (proc 1))
 (seg (? (= S 2) (= 203 #f))
   (proc 0)
   (text "拷問をする時に使う各種の道具と、それ以外の厄介事を片付ける為のアイテムが入っている棚だ。")
   (wait)
   (text-reset)
   (text "今はまだ必要ないが、点検しておいた方がいいだろうか‥‥‥")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 203 #t)
   (proc 1))
 (seg (? (= S 2) (= 204 #f))
   (proc 0)
   (text "棚の中には、囚人を拷問する為に使う道具が入っている。ムチ、バイブ、浣腸器からもっとマニアックな物まで‥‥‥")
   (wait)
   (text-reset)
   (text
    "どれもわたし自身が選りすぐった物ばかり。これらを使って音を上げなかった者はいない。とりあえず、脱走した囚人を捕まえるまでは必要ないが‥‥‥")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 204 #t)
   (proc 1))
 (seg (? (= S 2) (= 204 #t))
   (proc 0)
   (text "脱走した囚人を捕まえるまでは、戸棚を開ける必要もないだろう。")
   (wait)
   (text-reset)
   (proc 1))
 (seg (? (= S 3) (= 205 #f))
   (proc 0)
   (text
    "このわたしの部屋は地上５階‥‥‥と言っても、街全体が地下百数十メートルにある訳だが‥‥‥にある。眺めは悪くないが、この街での特等席は、さらに地下だ。")
   (wait)
   (text-reset)
   (text "万が一地殻が崩れて頭上から降って来た場合、露出している建物はひとたまりもない。")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 205 #t)
   (proc 1))
 (seg (? (= S 3) (= 206 #f))
   (proc 0)
   (text "窓の外には、戦没者慰霊塔がある。世界各地の戦線で死亡した兵士達の名を連ねた物だ。")
   (wait)
   (text-reset)
   (text "最近では塔は、その数と高さをどんどん増している。ほんの２ヶ月部屋を留守にしていただけで、驚く程景色が変わってしまうのだ。")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 206 #t)
   (proc 1))
 (seg (? (= S 3) (= 206 #t))
   (proc 0)
   (text "窓の外には、戦没者慰霊塔がある。世界各地の戦線で死亡した兵士達の名を連ねた物だ。")
   (wait)
   (text-reset)
   (proc 1))
 (seg (? (= S 4) (= 52 #t))
   (proc 0)
   (text "アンナの言った、ふたりの囚人の元上官に会いに行くしかない。何か情報を得られればいいが‥‥‥")
   (wait)
   (text-reset)
   (proc 1))
 (seg (? (= S 4) (= 207 #f))
   (proc 0)
   (text "すぐにでもアンナのオフィスに戻って、加藤の奴を殴り倒してやったら、どんなに気が晴れるだろう。")
   (wait)
   (text-reset)
   (text "わたしに汚れ仕事を押し付けた、アンナの真意もわからない。とにかく厄介ごとに巻き込まれたのは間違いないな。")
   (wait)
   (text-reset)
   (text "実際、どうやったら囚人達を見つけ出す事が出来るのか、皆目見当もつかない。")
   (wait)
   (text-reset)
   (text "この街には、犯罪者や逃亡者の類がごまんと居る。千葉やチャイナタウンに逃げ込まれたら、見つけるのは不可能に近いだろう。")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 207 #t)
   (proc 1))
 (seg (? (= S 4) (= 208 #f))
   (proc 0)
   (text "囚人を捉えろと言われても、彼女達に関する情報は驚く程少ない。経歴はおろか、顔さえわからずにどうやって捕まえればいい？")
   (wait)
   (text-reset)
   (text "こんな任務は前代未聞だし、情報部から機密が漏れた事も囚人が逃亡したって話も今まで聞いた事がない。")
   (wait)
   (text-reset)
   (text "内務監査官の加藤が今回の任務に絡んでるのも、その辺の理由か。内部に裏切り者が居るって事か‥‥‥")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 208 #t)
   (proc 1))
 (seg (? (= S 4) (= 208 #t))
   (proc 0)
   (text "アンナは部屋に来いって言ってたっけ‥‥‥部屋はこの情報部の中にある、行ってみるしかないか。")
   (wait)
   (text-reset)
   (nop@)
   (set-reg 209 #t)
   (proc 1)))