(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (if (</>
       (//
        (? (= K 1))
        ((cmd 209) 0 5)
        (image-file "gpc¥waku.gpc")
        (image-mem 0 3)
        ((cmd 209) 1 5)
        (nop@)
        (set-var K 0))
       (// (nop@))))
  (branch-reg 56 (</> (/) (/ (mes-jump "mes¥ma_a03.mes"))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b13_01.gpc")
  (image-mem 0 3)
  (proc 3)
  (if (</>
       (//
        (? (= P 5))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (load-mem "clm¥b13_01.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 900 #t))
        (text "情報部内にある、わたしの自室に戻った。ここは息が詰まる‥‥‥こんな所に居るくらいなら、さっさと出かけた方がましだ。")
        (wait)
        (text-reset 14))
       (//
        (? (= 900 #f))
        (text "情報部のわたしの部屋に戻った。市ヶ谷でふたりの逃亡者に関する情報は得たものの、未だひとりの囚人も捕らえる事が出来ない。")
        (wait)
        (text-reset 14)
        (text "だからと言って咎められるいわれはないが、このままではストレスが溜まる一方だ。")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 900 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t))
   (nop@)
   (set-var K 0)
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 6 1 0 0 4480 4480 1 0)
   (menu1 5 72 5 88 (</> (/ (text "　セーブ　")) (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 16 96")
         (exec-mem 4768 5 9 16 12 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          6
          112
          6
          128
          6
          144
          (</>
           (/ (text "　ファイル１　"))
           (/ (text "　ファイル２　"))
           (/ (text "　ファイル３　"))
           (/ (text "　ファイル４　"))
           (/ (text "　ファイル５　"))
           (/)))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (nop@)
         (set-var J P)
         (nop@)
         (set-var P 0)
         (if (</>
              (//
               (? (= S 0))
               (nop@)
               (set-var K 1)
               (flag-save 0)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (//
               (? (= S 1))
               (nop@)
               (set-var K 1)
               (flag-save 1)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (//
               (? (= S 2))
               (nop@)
               (set-var K 1)
               (flag-save 2)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (//
               (? (= S 3))
               (nop@)
               (set-var K 1)
               (flag-save 3)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (//
               (? (= S 4))
               (nop@)
               (set-var K 1)
               (flag-save 4)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (// (? (= S 255)))))
         (nop@)
         (set-var P J))
        (//
         (? (= S 1))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 8 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          6
          112
          (</>
           (/ (text "　アンナのオフィス　"))
           (/ (text "　　アンナの部屋　　"))
           (/ (text "　　　外に出る　　　"))
           (/)))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (branch-reg
                55
                (</>
                 (/ (mes-jump "mes¥MA_B02.MES"))
                 (/ (mes-jump "mes¥MA_B03.MES")))))
              (// (? (= S 1)) (mes-jump "mes¥MA_C02.MES"))
              (//
               (? (= S 2))
               (branch-reg
                55
                (</>
                 (/ (mes-jump "mes¥MB_A01.MES"))
                 (/ (nop@) (set-reg 56 #t) (mes-jump "mes¥MB_A02.MES")))))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= S 1) (= 288 #f))
   (proc 0)
   (text "部屋と同じくらい古びた机と椅子が置かれている。わたし自身はほとんど使う事がないが、体裁を保つ為にあるんだろう。")
   (wait)
   (text-reset 14)
   (text "わたしにはデスクワークは似合わないし、自分の仕事だとも思っていない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 288 #t)
   (proc 1))
 (seg (? (= S 1) (= 289 #f))
   (proc 0)
   (text "わたしの部屋は、情報部における典型的な部員のそれとは多少異なる所がある。")
   (wait)
   (text-reset 14)
   (text "大抵の情報部員にとって必要不可欠な机と椅子は、わたしには場所ふさぎの邪魔者にすぎない。ベッドの方が使用頻度が高いのだ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 289 #t)
   (proc 1))
 (seg (? (= S 1) (= 289 #t))
   (proc 0)
   (text "部屋と同じくらい古びた机と椅子が置かれている。わたし自身はほとんど使う事がないが、体裁を保つ為にあるんだろう。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 290 #f))
   (proc 0)
   (text "棚の中には、ムチ、バイブ、浣腸器などの囚人を拷問する為に使う道具が入っている。")
   (wait)
   (text-reset 14)
   (text "わたしが情報部に籍を置く事を許されるのも、それらの道具を他人より巧く使えるからに他ならない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 290 #t)
   (proc 1))
 (seg (? (= S 2) (= 291 #f))
   (proc 0)
   (text "拷問の時に使う、様々な道具が入っている。どれも囚人に最高の苦痛と屈辱を与える為に、わたし自身が選んだ物ばかりだ。")
   (wait)
   (text-reset 14)
   (text "しかし肝心の囚人がいないからには、それらの道具を使う事も出来ない。お楽しみの時間の前に困難な任務を片付けなければ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 291 #t)
   (proc 1))
 (seg (? (= S 2) (= 291 #t))
   (proc 0)
   (text "脱走した囚人を捕まえるまでは、戸棚を開ける必要もないだろう。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 292 #f))
   (proc 0)
   (text "窓の外は、小さな公園になっている。この情報部オフィスのある一画は本当の都心部。土地の無駄遣いは批判の的になっている。")
   (wait)
   (text-reset 14)
   (text "元々この辺りは軍の駐屯地だったらしい。市ヶ谷に大規模な基地が出来るまでは、帝都の治安を守る任を負っていた。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 292 #t)
   (proc 1))
 (seg (? (= S 3) (= 293 #f))
   (proc 0)
   (text "窓の外には、戦没者慰霊塔がある。世界各地の戦線で死亡した兵士達の名を連ねた物だ。")
   (wait)
   (text-reset 14)
   (text "最近では塔は、その数と高さをどんどん増している。ほんの２ヶ月部屋を留守にしていただけで、驚く程景色が変わってしまう。")
   (wait)
   (text-reset 14)
   (text "この国も長くは持つまいという明白な証拠だ。犯罪が増え、治安が乱れるのも無理はない。誰もが未来に絶望している‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 293 #t)
   (proc 1))
 (seg (? (= S 3) (= 293 #t))
   (proc 0)
   (text "窓の外は、小さな公園になっている。この情報部オフィスのある一画は本当の都心部。土地の無駄遣いは批判の的になっている。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 253 #f) (= 287 #t))
   (proc 0)
   (text "秋葉原のブラックマーケットで会った女、大佐が話したエイプリルの友人だと言ってた。")
   (wait)
   (text-reset 14)
   (text "しかし、あの女がエイプリルでないという保証があるだろうか？　わたしは逃走した囚人の顔さえ知らない。")
   (wait)
   (text-reset 14)
   (text "仮にエイプリルとレイファを発見したとしても、どうする事も出来ないじゃないか‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 253 #t) (= 287 #f))
   (proc 0)
   (text "市ヶ谷ベースのカール大佐に言われたとおり、チャイナタウンを探してみたが、レイファを見つける事は出来なかった‥‥‥")
   (wait)
   (text-reset 14)
   (text "あの一画には身を隠す場所が腐るほどあるし、もし彼女が同じ部屋に居たとしても、わたしより先にむこうに発見される可能性が高い")
   (wait)
   (text-reset 14)
   (text "相手は特殊部隊上がり。わたしよりはるかに強いし、人殺しなどお手の物だろう、レイファに勝つ方法を考えなければ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 253 #t) (= 287 #t))
   (proc 0)
   (text "市ヶ谷ベースのカール大佐に言われた、秋葉原とチャイナタウンでは、ふたりの囚人を見つけられなかった‥‥‥。")
   (wait)
   (text-reset 14)
   (text "いや、仮にふたりがそこに居たとしても、特殊な能力を持った彼女達を捕まえるのは難しい。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 55 #t))
   (proc 0)
   (text "加藤は囚人に刻まれたマークと特殊ゴーグルの事を、故意にわたしに知らせなかったに違いない。")
   (wait)
   (text-reset 14)
   (text "単なる嫌がらせなのか、それとも囚人を見つけられると都合が悪いのか‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 294 #f))
   (proc 0)
   (text "エイプリルとレイファが居そうな場所は見当がついたが、秋葉原やチャイナタウンを探しても、ふたりが見つかるとは限らない‥‥‥")
   (wait)
   (text-reset 14)
   (text "ふたりが誰かの命令で機密を盗み、逃亡したのだとしたら、証拠隠滅の為に今頃は消されているんじゃないだろうか？")
   (wait)
   (text-reset 14)
   (text "でも、たとえそうだとしても、ふたりを探さない訳にはいかない。とにかく、任務を遂行しようと努力したって事をわからせないと。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 294 #t)
   (proc 1))
 (seg (? (= S 4) (= 294 #t))
   (proc 0)
   (text "たとえふたりがすでに生きていないとしても、探さない訳にはいかない。わたしが努力したって事は示しとかないと‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))