(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (if (</>
       (//
        (? (= K 1))
        ((cmd 209) 0 5)
        (image-file "gpc¥waku.gpc")
        (image-mem 0 3)
        ((cmd 209) 1 5)
        (nop@)
        (set-var K 0))
       (// (nop@))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b13_01.gpc")
  (image-mem 0 3)
  (proc 3)
  (if (</>
       (//
        (? (= P 5))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (load-mem "clm¥b13_01.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 904 #f))
        (text "情報部内の、わたしの部屋に戻った。こんな所で途方に暮れている場合じゃない、それはわかっているが‥‥‥")
        (wait)
        (text-reset 14))
       (//
        (? (= 904 #t))
        (text "こんな所で途方に暮れている場合じゃない、それはわかっている。しかし今のわたしは、自分の義務を果すのに熱心じゃない。")
        (wait)
        (text-reset 14)
        (text "いっそ、この隙にアンナが逃げおおせてくれれば。わたしも情報部を去って、千葉で暮らそうか‥‥‥")
        (wait)
        (text-reset 14)
        (text "アンナはまだ情報部内に留まっているのだろうか。何故だ？　逃げようと思えば、もっと早くそうする事も出来たのに‥‥‥")
        (wait)
        (text-reset 14)
        (text "どういう理由で軍と情報部に反旗を翻したか。何故囚人達に協力したのか、そういう事情は全くわからないままだ。")
        (wait)
        (text-reset 14)
        (text "アンナ本人の口から聞かなければならない。それも、囚人達にしたのと同じような方法を使ってだ。")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 904 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 202 #t) (= 204 #t) (= 206 #t) (= 208 #t))
   (nop@)
   (set-var K 0)
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 6 1 0 0 4480 4480 1 0)
   (menu1 5 72 5 88 (</> (/ (text "　セーブ　")) (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 16 96")
         (exec-mem 4768 5 9 16 12 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          6
          112
          6
          128
          6
          144
          (</>
           (/ (text "　ファイル１　"))
           (/ (text "　ファイル２　"))
           (/ (text "　ファイル３　"))
           (/ (text "　ファイル４　"))
           (/ (text "　ファイル５　"))
           (/)))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (nop@)
         (set-var J P)
         (nop@)
         (set-var P 0)
         (if (</>
              (//
               (? (= S 0))
               (nop@)
               (set-var K 1)
               (flag-save 0)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (//
               (? (= S 1))
               (nop@)
               (set-var K 1)
               (flag-save 1)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (//
               (? (= S 2))
               (nop@)
               (set-var K 1)
               (flag-save 2)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (//
               (? (= S 3))
               (nop@)
               (set-var K 1)
               (flag-save 3)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (//
               (? (= S 4))
               (nop@)
               (set-var K 1)
               (flag-save 4)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (// (? (= S 255)))))
         (nop@)
         (set-var P J))
        (//
         (? (= S 1))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 48")
         (exec-mem 4768 5 9 22 6 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          (</> (/ (text "　アンナのオフィス　")) (/ (text "　　アンナの部屋　　"))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MA_B06.MES"))
              (// (? (= S 1)) (mes-jump "mes¥MA_C04.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t))
   (exec-mem 3072 0)
   (nop@)
   (set-var K 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (text "　セーブ　"))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 16 96")
         (exec-mem 4768 5 9 16 12 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          6
          112
          6
          128
          6
          144
          (</>
           (/ (text "　ファイル１　"))
           (/ (text "　ファイル２　"))
           (/ (text "　ファイル３　"))
           (/ (text "　ファイル４　"))
           (/ (text "　ファイル５　"))
           (/)))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (nop@)
         (set-var J P)
         (nop@)
         (set-var P 0)
         (if (</>
              (//
               (? (= S 0))
               (nop@)
               (set-var K 1)
               (flag-save 0)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (//
               (? (= S 1))
               (nop@)
               (set-var K 1)
               (flag-save 1)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (//
               (? (= S 2))
               (nop@)
               (set-var K 1)
               (flag-save 2)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (//
               (? (= S 3))
               (nop@)
               (set-var K 1)
               (flag-save 3)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (//
               (? (= S 4))
               (nop@)
               (set-var K 1)
               (flag-save 4)
               (nop@)
               (set-var K 0)
               (text "セーブしました")
               (wait)
               (text-reset 14))
              (// (? (= S 255)))))
         (nop@)
         (set-var P J))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= S 1) (= 464 #f))
   (proc 0)
   (text "わたしはもう事件のほとんど全てを知っている。他にどんな情報があるにせよ、もはや必要ではないだろう。")
   (wait)
   (text-reset 14)
   (text "机と椅子もまた然り。この任務が済んだら、今度こそ本当に情報部を去ろう。二度とこの部屋に来る事もない‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 464 #t)
   (proc 1))
 (seg (? (= S 1) (= 465 #f))
   (proc 0)
   (text "机の中に入った報告書や調書の類も、データベースの中の情報も出所は軍部だ、役に立ちそうな物は何もない。")
   (wait)
   (text-reset 14)
   (text "機構＝システムはすでに取り戻したし、軍部がこれ以上何かを言ってくる事もないだろう。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 465 #t)
   (proc 1))
 (seg (? (= S 1) (= 465 #t))
   (proc 0)
   (text "この任務が済んだら、今度こそ本当に情報部を去ろう。二度とこの部屋に来る事もないはずだ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 466 #f))
   (proc 0)
   (text "わたしの拷問道具が入った戸棚だ。今のところ、拷問しなければならない囚人はいない。")
   (wait)
   (text-reset 14)
   (text "アンナを除いては。それをするには、まずアンナを捕まえないと。彼女は自分の部屋に居るはずだが‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 466 #t)
   (proc 1))
 (seg (? (= S 2) (= 466 #t))
   (proc 0)
   (text "そろそろ本気でアンナを捕まえに行かなければ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 467 #f))
   (proc 0)
   (text "窓の外の小さな公園に何かに不満を訴えるデモ隊が集まり、情報部のビルに向かって奇声を上げている。")
   (wait)
   (text-reset 14)
   (text "わたしの部屋からはほとんど何も聞こえないし、まさか武力行使に訴えるとも思えない、つまりほとんど何の影響もない訳。")
   (wait)
   (text-reset 14)
   (text "しかし、この種のデモやもっと始末に負えないテロ行為は増える一方。軍の統制力に陰りが見えてきたようだ‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 467 #t)
   (proc 1))
 (seg (? (= S 3) (= 468 #f))
   (proc 0)
   (text "はるか頭上から街を照らしている灯かりは、厚い雲に覆われてほとんどその威力を発揮していない。")
   (wait)
   (text-reset 14)
   (text "ただでさえ常に夜のような街は、さらに暗くなってしまった。こういう時は、悪質な犯罪が急激に増えることだろう。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 468 #t)
   (proc 1))
 (seg (? (= S 3) (= 468 #t))
   (proc 0)
   (text "はるか頭上から街を照らしている灯かりは、厚い雲に覆われてほとんどその威力を発揮していない。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4))
   (proc 0)
   (branch-index
    (</>
     (/
      (text "アンナが軍からシステムを盗み、囚人を脱獄させた張本人とは簡単には信じられない。そんな事をして何の得がある？")
      (wait)
      (text-reset 14)
      (text "彼女達が軍のデータベースから抜き取った機密には、アンナにそんな事をさせる理由となりうる物なのだろうか‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "加藤は目の上の瘤だったアンナが失墜すれば喜ぶだろう。このまま見逃す事は絶対に有り得ない。")
      (wait)
      (text-reset 14)
      (text "すでにアンナは監視されているだろうし、わたしがモタモタしているのも面白くないはずだ。アンナを尋問しなければならない‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "アンナが事件の黒幕だったとしたら、どうして早々に逃げなかったのだろう。それが一番の謎だ。")
      (wait)
      (text-reset 14))
     (/ (text "アンナを捕まえに行かなければ。彼女は情報部内の自分の部屋に居るはずだ。") (wait) (text-reset 14))))
   (proc 1)))