(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b01_01.gpc")
  (image-mem 0 3)
  (image-file "gpc¥b01_01b.gpc")
  (image-mem 1 0)
  (proc 3)
  (if (</>
       (//
        (? (= P 5))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (load-mem "clm¥b01_01b.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 918 #t))
        (text "「Katou」" 'br)
        (text "何をしているのだ、早くアンナ大佐を捕まえろ。")
        (wait)
        (text-reset 14))
       (//
        (? (= 918 #f))
        (text "「Katou」" 'br)
        (text "少佐か‥‥‥どうかしたのかね、怖い顔をして。")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "元々だよ。アンナは何処？")
        (wait)
        (text-reset 14)
        (text "「Katou」" 'br)
        (text "知らぬ。自室に居るのではないのか？")
        (wait)
        (text-reset 14)
        (text "「Katou」" 'br)
        (text "ところで、プリスは尋問したのだろうな。これで貴様の任務も終わりか。随分時間がかかったな。")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "そうでもない‥‥‥もうひとり捕まえなければならなくなった。")
        (wait)
        (text-reset 14)
        (text "「Katou」" 'br)
        (text "それでアンナ大佐か。")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "どうしてそれを‥‥‥あんた、最初から知ってたんだね？")
        (wait)
        (text-reset 14)
        (text "「Katou」" 'br)
        (text "大佐だけではない、プロジェクトに関っていた全員が容疑者だ。あの女が犯人ではないかという疑いは、強かったがな。")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "‥‥‥‥‥‥‥‥‥‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Katou」" 'br)
        (text "何をためらっている。大佐を尋問すればよかろう？　他の囚人共にしたように。")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 918 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 471 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 6 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          (</> (/ (str " 　　自分の部屋　 　")) (/ (text "　　アンナの部屋　　"))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MA_A06.MES"))
              (// (? (= S 1)) (mes-jump "mes¥MA_C04.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 470 #f))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "エイプリルとレイファが隠してた情報は、もう取り戻した。軍の技研が持ってったろう？")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "マイクロチップと刺青の写真か。すでに解析済みだ。中身は新しい集積回路の設計図と、それを使った新型チップの回路図だった。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "回路図か、思った通りだ。刺青の模様が普通じゃなかった。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "あれはポッドモッド用の、頭蓋の中に埋めこむタイプのチップだ。脳に特別な刺激を与える、今までに例がない物だ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥‥‥‥‥‥そんな事を話していいのかい、機密だろ？")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "何の問題も無い。なぜならそれは、機構＝システムの一部に過ぎないからだ。つまり貴様の任務はまだ終わっていないという事だ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "だけど‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "私がまだだと言ったら、まだなのだ！")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "貴様が見つけたそれらはハード、つまりシステムの一部に過ぎぬ。問題はソフトなのだ、そちらの方が重要だ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ソフトね‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "何処にでも隠せそうな物だけど、何かに記憶しておかなきゃならないはずだろう？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "軍のデータベースからデータを抜き取ったのはナナだろうけど、あの子を拷問してもそんな事は自白しなかった。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "本人達も知らないという事もありうる。アンナ大佐が密かに隠したのかも知れぬではないか。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "アンナが？　情報部の中にあるっての？　そんな事は考えられないね。探せばすぐに見つかるだろう。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "ソフトとは、形があるようで何にでも化ける。古典的なフロッピーから、偽装してネットワーク内に放り込んでおく事も。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "見つけだすには、隠した本人に聞く他なかろう。こちらには拷問のプロもついている。任務はほぼ達成されたと言ってよかろう。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "アンナが‥‥‥本当に軍の情報に手を出したと思うの？")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 470 #t)
   (proc 1))
 (seg (? (= S 1) (= 471 #f))
   (proc 0)
   (text "「Katou」" 'br)
   (text "おそらく、アンナ大佐が首謀者だったのだろう。最初にその機密の内容を知ったのは、大佐のはずだからな。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それじゃ、彼女達を事件に巻き込んだのもアンナだと？　エリコや他の囚人達も‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "元々、プロジェクトは軍と、情報部とサカタ・ネオテクの三者で考案されたのだ。エリコを巻き込んだのはそういう事だからだ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そのソフトの隠し場所を、アンナを拷問して吐かせろと？")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "急げよ、貴様も国賊だと思われたくなければな。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "加藤、あんたはアンナがこんな事になったのを喜んでるんだろう。本物の下衆野郎だよ。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "何と言われようと困らん。貴様こそ目を覚ませ。あんな移民の女に利用されていたのだぞ、軍人として恥ずかしいとは思わんのか。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "やってやるよ‥‥‥でも、あんたや軍部の為じゃない。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "どうしてアンナがそんな真似をしたのかが知りたいからだ。わたしを裏切ったのが許せないからだよ！")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "勝手にするがいい。しかし失敗は許さん。尋問してデータを取り戻すのだ。裏切りは許さんからな。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 471 #t)
   (proc 1))
 (seg (? (= S 1) (= 471 #t))
   (proc 0)
   (text "「Katou」" 'br)
   (text "アンナ大佐も大変な事をしたものだ。あの女に未来はない。囚人としての暮らしが待っているだけだ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 472 #f))
   (proc 0)
   (text "加藤は確かに嫌な奴だ。しかし、この男は軍人として最高のキャリアを積んできた人間なのに間違いない、それは一目でわかる。")
   (wait)
   (text-reset 14)
   (text "鍛えられた肉体は、幾多の戦場を潜り抜けて鍛え上げられたものであろうし、冷たい眼は人殺しのそれと何も変らない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 472 #t)
   (proc 1))
 (seg (? (= S 2) (= 473 #f))
   (proc 0)
   (text "長身の加藤が目の前に立つと、想像を絶する威圧感がある。隆起した筋肉は、軍服の上からでもわかる程だ。")
   (wait)
   (text-reset 14)
   (text "しかし、その羨むばかりの体つきとは裏腹に、こいつの頭の中は腐り果てている。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 473 #t)
   (proc 1))
 (seg (? (= S 2) (= 473 #t))
   (proc 0)
   (text "加藤は確かに嫌な奴だ。しかし、この男は軍人として最高のキャリアを積んできた人間なのに間違いない、それは一目でわかる。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3))
   (proc 0)
   (branch-index
    (</>
     (/
      (text "アンナが軍からシステムを盗み、囚人を脱獄させた張本人とは簡単には信じられない。そんな事をして何の得がある？")
      (wait)
      (text-reset 14)
      (text "彼女達が軍のデータベースから抜き取った機密には、アンナにそんな事をさせる理由となりうる物なのだろうか‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "加藤は目の上の瘤だったアンナが失墜すれば喜ぶだろう。このまま見逃す事は絶対に有り得ない。")
      (wait)
      (text-reset 14)
      (text "すでにアンナは監視されているだろうし、わたしがモタモタしているのも面白くないはずだ。アンナを尋問しなければならない‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "アンナが事件の黒幕だったとしたら、どうして早々に逃げなかったのだろう。それが一番の謎だ。")
      (wait)
      (text-reset 14))
     (/ (text "アンナを捕まえに行かなければ。彼女は情報部内の自分の部屋に居るはずだ。") (wait) (text-reset 14))))
   (proc 1))
 (seg*))