(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (if (</> (// (? (= 58 #t) (= 60 #t)) (mes-jump "mes¥ma_b04.mes")) (//)))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b01_01.gpc")
  (image-mem 0 3)
  (image-file "gpc¥b01_01b.gpc")
  (image-mem 1 0)
  (proc 3)
  (if (</>
       (//
        (? (= P 5))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (load-mem "clm¥b01_01b.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 914 #t))
        (text "「Katou」" 'br)
        (text "どうかしたかね、少佐？")
        (wait)
        (text-reset 14))
       (//
        (? (= 914 #f))
        (text "「Katou」" 'br)
        (text "どうかしたかね、少佐？")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "ああ、どうかしたさ。まさか、わたしがあんたに会うのを楽しみにしてるとは思ってないだろう？")
        (wait)
        (text-reset 14)
        (text "「Katou」" 'br)
        (text "それはそれは‥‥‥えらく嫌われたものだ。それも私の仕事のうちだがね。なかなか辛いものだよ。")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "なに善人ぶってる。あんたみたいに下衆な野郎は、今までお目にかかった事がないけどね。")
        (wait)
        (text-reset 14)
        (text "「Katou」" 'br)
        (text "‥‥‥それで、用件は何だね。")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 914 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 6 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          (</> (/ (str " 　　自分の部屋　 　")) (/ (text "　　アンナの部屋　　"))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (branch-reg
                56
                (</>
                 (/ (mes-jump "mes¥MA_A02.MES"))
                 (/ (mes-jump "mes¥ma_a03.mes")))))
              (// (? (= S 1)) (mes-jump "mes¥MA_C02.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 56 #t))
   (proc 0)
   (if (</>
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #f) (= 60 #f))
         (nop@)
         (text "「Kiyomi」" 'br)
         (text "エイプリルを捕まえた。これから尋問にかける。")
         (wait)
         (text-reset 14)
         (text "「Katou」" 'br)
         (text "よくやった。何かわかり次第、私に報告するようにな。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #f) (= 60 #f))
         (nop@)
         (text "「Kiyomi」" 'br)
         (text "エイプリルを拷問したけど、何も吐かなかったよ。")
         (wait)
         (text-reset 14)
         (text "「Katou」" 'br)
         (text "ふむ‥‥‥仕方がないな。もうひとりの元特殊部隊上がりを捕らえる事だ。迅速にな。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #t) (= 60 #f))
         (nop@)
         (text "「Kiyomi」" 'br)
         (text "エイプリルは尋問したし、レイファも捕まえた。これからレイファを尋問するつもり。")
         (wait)
         (text-reset 14)
         (text "「Katou」" 'br)
         (text "これで何も聞き出せなかったとしたら、お前の自慢の特殊技能とやらに疑問を持たざるをえなくなる。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (text "「Kiyomi」" 'br)
         (text "エイプリルとレイファは捕まえたよ、これからふたりを尋問する。何か喋るといいけど。")
         (wait)
         (text-reset 14)
         (text "「Katou」" 'br)
         (text "ちゃんと報告に来るとは、いい心掛けだ。私あるいは軍の助力が必要な時は、いつでも言うがいい。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (text "「Kiyomi」" 'br)
         (text "レイファを捕まえた。やっぱりチャイナタウンに隠れてたよ。")
         (wait)
         (text-reset 14)
         (text "「Katou」" 'br)
         (text "捕まえてくれと言わんばかりだな。怪しいと言わざるをえない、油断は禁物だぞ。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (text "「Kiyomi」" 'br)
         (text "レイファからは、何も聞き出せなかった。わたしの尋問が甘かったとは思えない、何も知らないんじゃないかね。")
         (wait)
         (text-reset 14)
         (text "「Katou」" 'br)
         (text "私はそうは思わんがね。仕方ない、もうひとりの特殊部隊上がりを捕えろ。迅速にな。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (text "「Kiyomi」" 'br)
         (text "レイファからは、何も聞き出せなかった。何も知らないのよ。もしもエイプリルもそうだったら、どうするつもりだい？")
         (wait)
         (text-reset 14)
         (text "「Katou」" 'br)
         (text "貴様とアンナ大佐に責任を取ってもらうさ。そうなりたくないのなら、何とかするのだな。")
         (wait)
         (text-reset 14))
        (//
         (text "「Katou」" 'br)
         (text "手ぶらで戻って来るとは期待外れだ。お前はまだ、自分の義務を果していないぞ。早く囚人を捕まえて来い。")
         (wait)
         (text-reset 14))))
   (proc 1))
 (seg (? (= S 1) (= 314 #f))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "この前の続きだけどね、どうしてわたしにゴーグルと囚人のマークの件を黙ってたのか、その訳が聞きたいね。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "まだそんな事を言っているのか。忘れていたと言っているだろう？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そんな話、信じられないね。それさえわかってりゃ、こんなに苦労する事もなかったんだ！")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "信じるも信じないもお前の勝手。だがな、私を信じなければ仕事がやり辛くなるだけだぞ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そりゃ結構、わたしがビビるとでも？")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "勘違いするな、脅しているのではない。私がこの事件に関して軍から全権を委任されている。だから私を信じろと言っているのだ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "へえ、「だから私を信じろ」だって？　冗談じゃないね。あんたなんか信じられない。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それどころか、わたしはあんたを疑ってるんだよ。わざと捜査を遅らせてるんじゃないかってね。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "何を馬鹿な‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そう？　わたしはそれ程馬鹿げた話じゃないと思っているけど。何なら何処ぞにリークしてやろうか？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "内務監査のあんたが機密漏洩の首謀者だって事になれば、ただでは済まないだろうね。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "勝手にしろ。恥をかくのはお前だぞ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 314 #t)
   (proc 1))
 (seg (? (= S 1) (= 314 #t))
   (proc 0)
   (text "「Katou」" 'br)
   (text "詰まらん戯言をほざいている暇があるなら、早く事件にかたをつけてしまえ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 315 #f))
   (proc 0)
   (text "長身の加藤が目の前に立つと、想像を絶する威圧感がある。隆起した筋肉は、軍服の上からでもわかる程だ。")
   (wait)
   (text-reset 14)
   (text "しかし、その羨むばかりの体つきとは裏腹に、こいつの頭の中は腐り果てている。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 315 #t)
   (proc 1))
 (seg (? (= S 2) (= 316 #f))
   (proc 0)
   (text "加藤は確かに嫌な奴だ。しかし、この男は軍人として最高のキャリアを積んできた人間なのに間違いない、それは一目でわかる。")
   (wait)
   (text-reset 14)
   (text "鍛えられた肉体は、幾多の戦場を潜り抜けて鍛え上げられたものであろうし、冷たい眼は人殺しのそれと何も変らない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 316 #t)
   (proc 1))
 (seg (? (= S 2) (= 316 #t))
   (proc 0)
   (text "長身の加藤が目の前に立つと、想像を絶する威圧感がある。隆起した筋肉は、軍服の上からでもわかる程だ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 56 #t))
   (proc 0)
   (if (</>
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #f) (= 60 #f))
         (nop@)
         (text "まずはエイプリルを尋問してみよう。この事件全体を解く鍵がみつかるかもしれない。")
         (wait)
         (text-reset 14)
         (text "それが無理でも、レイファを逮捕するためのヒントか、第３の囚人を発見する手がかりを得られればいい。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #f) (= 60 #f))
         (nop@)
         (text "エイプリルがわたしの拷問に耐えられたとは思いたくない。彼女は本当に何も知らなかったのか‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #t) (= 60 #f))
         (nop@)
         (text "ふたり目の囚人、レイファを逮捕した。彼女を尋問すれば、何か情報を得られるかもしれない。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (text "ふたりの囚人は逮捕した。彼女達を尋問すれば、機密に関する情報を得られるだろう。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (text "レイファを逮捕した。彼女を尋問すれば、事件全体を解く鍵がみつかるかもしれない。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (text "レイファがわたしの拷問に耐えられたとは思いたくない。彼女は本当に何も知らなかったのか‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (text "レイファは何も喋らなかった。エイプリルを何とかしなければならない。どんな事でもいい、何とかしないと‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (text "まずはエイプリルかレイファを逮捕しなければならない。どちらから先にやるか‥‥‥")
         (wait)
         (text-reset 14))))
   (proc 1))
 (seg (? (= S 3) (= 317 #f))
   (proc 0)
   (text "加藤は全く悪びれた様子もないが、例の囚人につけたマーキングの件をわたしに黙っていた事は、責められても仕方ない失敗だ。")
   (wait)
   (text-reset 14)
   (text "忘れたの一言で済まされる問題じゃない。そもそも、そんな重要な事を忘れるなんて、信じられないじゃないか。")
   (wait)
   (text-reset 14)
   (text "やはり、加藤を信じる事など出来ない。何か裏があるに決まっているんだ‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 317 #t)
   (proc 1))
 (seg (? (= S 3) (= 317 #t))
   (proc 0)
   (text "加藤は全く悪びれた様子もないが、例の囚人につけたマーキングの件をわたしに黙っていた事は、責められても仕方ない失敗だ。")
   (wait)
   (text-reset 14)
   (proc 1)))