(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b01_01.gpc")
  (image-mem 0 3)
  (image-file "gpc¥b01_01b.gpc")
  (image-mem 1 0)
  (proc 3)
  (if (</>
       (//
        (? (= P 5))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (load-mem "clm¥b01_01b.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 912 #t))
        (text "「加藤」" 'br)
        (text "私に何か用かね、少佐。")
        (wait)
        (text-reset 14))
       (//
        (? (= 912 #f))
        (text "「加藤」" 'br)
        (text "どうしたね、少佐？")
        (wait)
        (text-reset 14)
        (text "加藤‥‥‥いつまでここでふんぞり返ってるつもりなんだろう。")
        (wait)
        (text-reset 14)
        (text "「キヨミ」" 'br)
        (text "ここはアンナのオフィスだと記憶していたけど？")
        (wait)
        (text-reset 14)
        (text "「加藤」" 'br)
        (text "しばらくの間、私が使用する事になった。大佐に用なら、私室に行けば逢えるだろう。")
        (wait)
        (text-reset 14)
        (text "「キヨミ」" 'br)
        (text "‥‥‥‥‥‥‥‥‥")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 912 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 211 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 6 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          (</> (/ (str " 　　自分の部屋　 　")) (/ (text "　　アンナの部屋　　"))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MA_A01.MES"))
              (// (? (= S 1)) (mes-jump "mes¥MA_C01.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 210 #f))
   (proc 0)
   (text "「キヨミ」" 'br)
   (text "あんたがわたしの事を良く思ってないのは、情報部の人間なら誰でも知ってる。")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "だのに、どうしてわたしなんかに機密奪還を命じたんだい？　全く信用のおけない人間に。")
   (wait)
   (text-reset 14)
   (text "「加藤」" 'br)
   (text "他に信用出来る部下がいないと言うのは悲しむべき事だが、お前のその判断は誤っている。")
   (wait)
   (text-reset 14)
   (text "「加藤」" 'br)
   (text "私は、相手がプロであるなら、相手が誰でも十分な敬意を払っているつもりだ。任務に私情を挟むつもりもない。")
   (wait)
   (text-reset 14)
   (text "「加藤」" 'br)
   (text "加えて言うなら、私はお前を嫌っているのではなく、極めて特殊な人間であると考えているだけだ。")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "そりゃどうも‥‥‥でも、やっぱりこの任務にわたしを選んだのは賢い選択とは思えないね。")
   (wait)
   (text-reset 14)
   (text "「加藤」" 'br)
   (text "たとえ任務＝ランが失敗に終わったとしても、私の腹は痛まない。違うかね？")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 210 #t)
   (proc 1))
 (seg (? (= S 1) (= 211 #f))
   (proc 0)
   (text "「加藤」" 'br)
   (text "今回の任務は、単に脱走した囚人を捉えるのが目的という訳ではない。我々軍は大いに面子を潰されたのだ。")
   (wait)
   (text-reset 14)
   (text "「加藤」" 'br)
   (text "我々の社会はヤクザのそれと似ている。面子を潰されたままでは、軍の統率力は失われる。それはこの国にとって良くない事だ。")
   (wait)
   (text-reset 14)
   (text "「加藤」" 'br)
   (text "私の言っている意味がわかるな？　私がここまで譲歩している事を考えて、速やかに事を終わらせてもらいたい。")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "はん、わたしが軍の面子を気にしてやる理由があるかい？")
   (wait)
   (text-reset 14)
   (text "「加藤」" 'br)
   (text "‥‥‥正直言って、私はお前をどう扱ってよいのか理解に苦しむ。")
   (wait)
   (text-reset 14)
   (text "「加藤」" 'br)
   (text "出世を望んでいる訳ではなく、金が欲しいのでもない。名を売りたいのなら軍になど居らず、脳に配線してハッカーになるだろう。")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「加藤」" 'br)
   (text "では何が望みなのだ。仮に私あるいは軍がお前に望む物をくれてやると言っても、拒絶するのだろう？")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "そう簡単に理解されちゃたまんないね。わたしみたいな変わり者がいるから世の中面白いんだ。違うかね、ご同輩。")
   (wait)
   (text-reset 14)
   (text "「加藤」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 211 #t)
   (proc 1))
 (seg (? (= S 1) (= 211 #t))
   (proc 0)
   (text "「加藤」" 'br)
   (text "私は当分ここに居る。用があるならいつでも来るがいい。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 212 #f))
   (proc 0)
   (text "加藤は確かに嫌な奴だ。しかし、この男は軍人として最高のキャリアを積んできた人間なのは間違いない、それは一目でわかる。")
   (wait)
   (text-reset 14)
   (text "鍛えられた肉体は、幾多の戦場を潜り抜けて鍛え上げられたものであろうし、冷たい眼は人殺しのそれと何も変らない。")
   (wait)
   (text-reset 14)
   (text
    "こいつが脳に配線しないのは、そんな事をする必要が無いからだ。指一本動かさずに人を殺す事が出来るし、欲しい情報は必ず彼の元に集まって来る。")
   (wait)
   (text-reset 14)
   (text "わざわざ肉体改造＝ポッドモッドする必要は無いって訳。まあ、他にも何か理由があるのかもしれないが。")
   (wait)
   (text-reset 14)
   (text "一部の僧侶や保守的な医師は、肉体改造を快く思っていない。どんな影響があるかわからないからというのがその理由だ。")
   (wait)
   (text-reset 14)
   (text "加藤が世の規範である僧侶に嫌われたくないと思っているか、医師の忠告を真に受けて、万が一を恐れている可能性が無くもない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 212 #t)
   (proc 1))
 (seg (? (= S 2) (= 213 #f))
   (proc 0)
   (text "長身の加藤が目の前に立つと、想像を絶する威圧感がある。隆起した筋肉は、軍服の上からでもわかる程だ。")
   (wait)
   (text-reset 14)
   (text "しかし、その羨むばかりの体つきとは裏腹に、こいつの頭の中は腐り果てている。")
   (wait)
   (text-reset 14)
   (text "純粋な日本人であり、軍人である事を体中で表現したような尊大な態度には反発を抱かずにはいられない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 213 #t)
   (proc 1))
 (seg (? (= S 2) (= 213 #t))
   (proc 0)
   (text "長身の加藤が目の前に立つと、想像を絶する威圧感がある。隆起した筋肉は、軍服の上からでも形がわかる程だ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 214 #f))
   (proc 0)
   (branch-reg
    52
    (</>
     (/
      (text "オフィスの中にアンナの姿はない。「私の部屋に‥‥‥」と言ってたんだ、私室にいるんだろう。")
      (wait)
      (text-reset 14)
      (text "とすれば、こんな所に居てもあまり意味はないな。まだ引き受けた訳ではないにせよ、任務について情報を仕入れておいた方がいい。")
      (wait)
      (text-reset 14)
      (text "それにしても、厄介な事に巻き込まれたもんだ‥‥‥"))
     (/
      (text "オフィスの中にアンナの姿は無い。当然だ、アンナにしたところで加藤と長時間一緒に居たくはないだろう。")
      (wait)
      (text-reset 14)
      (text "わたしを迎えに来た軍服の男が、あれ程わたしを急かしたのもその為だろうか‥‥‥")
      (wait)
      (text-reset 14)
      (text "確かあいつは情報部の人間だった。情報部内で加藤の事を良く思っている者は数えるくらいしかいない。"))))
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 214 #t)
   (proc 1))
 (seg (? (= S 3) (= 215 #f))
   (proc 0)
   (text "どういう裏があるのか知らないが、加藤がこれ以上の情報をくれる事はないだろう。")
   (wait)
   (text-reset 14)
   (text "こいつと話をしていても無駄だ‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 215 #t)
   (proc 1))
 (seg (? (= S 3) (= 215 #t))
   (proc 0)
   (text "加藤が当分の間、アンナのオフィスを占領するつもりだとしたら、今度の任務はそうとうヤバい物に違いない。")
   (wait)
   (text-reset 14)
   (proc 1)))