(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 3072 0)
  (if (</> (// (? (= 64 #t)) (mes-jump "mes¥ma_b05.mes")) (//)))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (if (</>
       (//
        (? (= P 5))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (if (</>
       (//
        (? (= 80 #t))
        (image-file "gpc¥b01_01.gpc")
        (image-mem 0 3)
        (image-file "gpc¥b01_01a.gpc")
        (image-mem 1 0)
        (load-mem "clm¥b01_01a.clm" 32768))
       (//
        (? (= 80 #f))
        (image-file "gpc¥b01_01.gpc")
        (image-mem 0 3)
        (image-file "gpc¥b01_01b.gpc")
        (image-mem 1 0)
        (load-mem "clm¥b01_01b.clm" 32768))))
  (proc 3)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 80 #t) (= 916 #t))
        (text "「Anna」" 'br)
        (text "キヨミ。どうかしたの？")
        (wait)
        (text-reset 14))
       (//
        (? (= 80 #t) (= 916 #f))
        (text "「Katou」" 'br)
        (text "どうかしたのかね‥‥‥大佐？")
        (wait)
        (text-reset 14)
        (text "「Anna」" 'br)
        (text "ええ、事件に関する事なので一緒に聞いてほしかったの。キヨミ、話してちょうだい。")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "‥‥‥‥‥‥‥‥‥‥‥‥話すって、何をどう話したらいい。")
        (wait)
        (text-reset 14)
        (text "「Anna」" 'br)
        (text "洗いざらいよ。多分あなたの力になれると思うの。")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "‥‥‥エイプリルとレイファを尋問して、ナナとミツコが千葉に潜伏してる事がわかった。多分ふたりは一緒にいると思う。")
        (wait)
        (text-reset 14)
        (text "「Katou」" 'br)
        (text "‥‥‥‥‥‥‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "で、千葉に行ったんだけど‥‥‥何しろあそこは犯罪多発地帯だし軍や情報部ってだけじゃ捜査が進まない。")
        (wait)
        (text-reset 14)
        (text "「Anna」" 'br)
        (text "それで？")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "それで、千葉で情報屋みたいのを見つけた。名前はモリイ、千葉の裏世界でもかなりの顔らしい。")
        (wait)
        (text-reset 14)
        (text "「Katou」" 'br)
        (text "モリイ？　聞いた事がない。公安方面に当たりをつけてみるかね？")
        (wait)
        (text-reset 14)
        (text "「Anna」" 'br)
        (text "その必要は無いと思いますわ。裏があるとは思えませんから、私達を引っ掛けて得をする訳ではないでしょう？")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "さっきから気になってたんだけどさ、アンナは知ってるの？　どうしてあんな千葉のいかがわしい情報屋の事を？")
        (wait)
        (text-reset 14)
        (text "「Anna」" 'br)
        (text "まあ、色々とね‥‥‥私だって情報部の将校よ。")
        (wait)
        (text-reset 14)
        (nop@)
        (set-reg 916 #t))
       (//
        (? (= 80 #f) (= 915 #t))
        (text "「Katou」" 'br)
        (text "何か用かね、少佐？")
        (wait)
        (text-reset 14))
       (//
        (? (= 80 #f) (= 915 #f))
        (text "「Katou」" 'br)
        (text "何か用かね、少佐？")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "別に‥‥‥あんたにゃ用はないよ。アンナは何処に居る？")
        (wait)
        (text-reset 14)
        (text "「Katou」" 'br)
        (text "知らんな。大佐の部屋に居るのではないかね。それはそうと、捜査の進展はどうなっておるのだ。")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "ああ、進んでるよ‥‥‥それなりに。")
        (wait)
        (text-reset 14)
        (text "「Katou」" 'br)
        (text "もっと頻繁に連絡をくれてもいいと思うが？　お前は私がこの事件のオブザーバーだという事を忘れている。")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "ああそうかい、別に嫌味をいわれに来た訳じゃないんだけどね。")
        (wait)
        (text-reset 14)
        (nop@)
        (set-reg 915 #t))))
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 80 #t) (= 66 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 6 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          (</> (/ (str " 　　自分の部屋　 　")) (/ (text "　　アンナの部屋　　"))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MA_A04.MES"))
              (// (? (= S 1)) (mes-jump "mes¥MA_C03.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 80 #f))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 6 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          (</> (/ (str " 　　自分の部屋　 　")) (/ (text "　　アンナの部屋　　"))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MA_A04.MES"))
              (// (? (= S 1)) (mes-jump "mes¥MA_C03.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 66 #t))
   (proc 0)
   (if (</>
        (//
         (? (= 63 #t))
         (nop@)
         (text "「Kiyomi」" 'br)
         (text "ミツコを捕まえたよ。無抵抗の人間を背後から撃つのは、あまりいい気持ちじゃなかったけどね‥‥‥")
         (wait)
         (text-reset 14)
         (text "「Anna」" 'br)
         (text "ミツコの尋問が終わったら、報告してちょうだい。")
         (wait)
         (text-reset 14))
        (//
         (? (= 62 #t))
         (nop@)
         (text "「Kiyomi」" 'br)
         (text "ナナを尋問したよ。ミツコとの待ち合わせ場所がわかった。これから行ってみる。")
         (wait)
         (text-reset 14)
         (text "「Anna」" 'br)
         (text "わかったわ、ミツコを逮捕したら知らせて。上層部の方も、捜査の進展を喜ぶでしょうから。")
         (wait)
         (text-reset 14))
        (//
         (? (= 61 #t))
         (nop@)
         (branch-reg
          386
          (</>
           (/
            (text "「Kiyomi」" 'br)
            (text "ナナを捕まえたよ。これから尋問にかける。ミツコを一緒に逮捕できなかったのは痛いけど‥‥‥居所を聞き出せるだろう。")
            (wait)
            (text-reset 14)
            (text "「Anna」" 'br)
            (text "そう。モリイの情報が役に立ったわね‥‥‥")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "ああ。モリイは商売になるネタを提供してもらったって言ってたけど、何をくれてやったの？")
            (wait)
            (text-reset 14)
            (text "「Anna」" 'br)
            (text "軍が開発した、あるポッドモッド技術の一部をリークしたのよ。頭骸の中にアラミド繊維の網を入れて伝達速度を倍にする技術。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "それが‥‥‥モリイにどんな得になるっての。")
            (wait)
            (text-reset 14)
            (text "「Anna」" 'br)
            (text "まだ一般には公開されてない情報よ。モリイのお抱え医師は、これで３年は他のクリニックより優位に立てるわ。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "なるほど‥‥‥そいつは大変な儲けになる。でも、軍がよくそんな情報を提供したね。")
            (wait)
            (text-reset 14)
            (text "「Anna」" 'br)
            (text "別に‥‥‥軍部ではもう一般的になっている技術よ。あとは、いつ民間に流すかってだけ。")
            (wait)
            (text-reset 14)
            (nop@)
            (set-reg 386 #t))
           (/
            (text "「Kiyomi」" 'br)
            (text "ナナを捕まえたよ。これから尋問にかける。ミツコを一緒に逮捕できなかったのは痛いけど、居所を聞き出せると思う。")
            (wait)
            (text-reset 14)
            (text "「Anna」" 'br)
            (text "ナナがどうやってデータベースから自分達のデータを消去出来たのか、技術部の方が知りたがってるわ。その話も聞き出して。")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 67 #t))
         (nop@)
         (branch-reg
          386
          (</>
           (/
            (text "「Anna」" 'br)
            (text "モリイから囚人の情報を聞き出した？")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "ああ。モリイは商売になるネタを提供してもらったって言ってたけど、何をくれてやったの。")
            (wait)
            (text-reset 14)
            (text "「Anna」" 'br)
            (text "軍が開発した、あるポッドモッド技術の一部をリークしたのよ。頭骸の中にアラミド繊維の網を入れて伝達速度を倍にする技術。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "それが‥‥‥モリイにどんな得になるっての。")
            (wait)
            (text-reset 14)
            (text "「Anna」" 'br)
            (text "まだ一般には公開されてない情報よ。モリイのお抱え医師は、これで３年は他のクリニックより優位に立てるわ。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "なるほど‥‥‥そいつは大変な儲けになる。でも、軍がよくそんな情報を提供したね。")
            (wait)
            (text-reset 14)
            (text "「Anna」" 'br)
            (text "別に‥‥‥軍部ではもう一般的になっている技術よ。あとは、いつ民間に流すかってだけ。")
            (wait)
            (text-reset 14)
            (nop@)
            (set-reg 386 #t))
           (/
            (text "「Anna」" 'br)
            (text "貴重な情報を提供したんですからね、絶対に囚人を捕えてもらわなければならないわよ。")
            (wait)
            (text-reset 14)))))
        (//
         (text "「Anna」" 'br)
         (text "モリイの事は私達で何とかするわ。あなたは店に行って情報を受け取ってきなさい。")
         (wait)
         (text-reset 14))))
   (proc 1))
 (seg (? (= 80 #t) (= S 1) (= 377 #f))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "アンナ、わたしよりもモリイの事を知ってそうじゃないか。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "まあね、千葉ではけっこう有名よ。もっとも千葉は有名人だらけだけど。ハッカー、闇医者、サイバネ屋、もっと危ない人もいるわ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "で、モリイはその中のどれなの。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "なんて言ったらいいのかしら。言わばそのどれもね。ハッカー達が仕掛け＝ランの為に使うアイスブレーカーを調達したり‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "ポッドモッドを希望する患者に、闇医者を紹介したり。もっと危険な仕事もしてるはずだけど、それは私の情報網にもかからない。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "そんな得体の知れぬ族と協力関係になるなど、軍では認められん。少佐、そんな奴に頼らねば任務を遂行出来ぬのか？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "まあ無理だね。千葉はわたしにとっても管轄外、住民になりすまして潜入してる部員もいないだろうし。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "情報部などと言って、大した事はないな‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1)
   (nop@)
   (set-reg 377 #t))
 (seg (? (= 80 #t) (= S 1) (= 378 #f))
   (proc 0)
   (text "「Anna」" 'br)
   (text "私はモリイを使う事に何の疑問も感じません。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "彼女は千葉に精通しているのだし、任務の為に外部の協力者を使う事は珍しくありませんから。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "君のようにかね、アンナ大佐？　挙げ句に情報部に居座って優先市民権を得るという訳か。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "いい加減におしよ。元はといえば、あんたら軍人共のミスで情報部にケツを拭かせようってんじゃないか。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥無礼な事を言うな。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "何でも無礼で片付くんなら、苦労はない。機密が洩れたのも無礼、囚人が脱走したのも無礼って？")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "口が過ぎるぞ‥‥‥いや、我々が争っても仕方がない。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "まさにそのとおり。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "キヨミ！　私達には、他に選択の余地はないようです。モリイに囚人の情報を探らせましょう。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "もっとも、すでに有力なネタを入手しているようですけど‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 378 #t)
   (proc 1))
 (seg (? (= S 1) (= 80 #t) (= 378 #t))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "問題は、どうやってモリイにネタを吐かせるかって事か。情報屋ってぐらいだから、金さえ払やいいんだろうけど‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "千葉の相場は高いわよ？　特に相手が情報部だってわかってしまっている以上、ふっかけてくるでしょうね。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "冗談ではないぞ。ただでさえ無能な部員に給料を払っているのだ。これ以上の浪費は認められぬ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "貧乏臭い事言うなよ、軍部は金持ちだろ？　それに、無能な部員てのは誰の事なのか教えてもらおうじゃないか。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "待ちなさい、キヨミ‥‥‥私に考えがあります。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "考えって‥‥‥金も払わずモリイに情報を提供させるつもりなの？まさかわたしに拷問しろってんじゃないだろうね。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "見境なく拷問する訳にはいかないでしょう。大丈夫、私に任せてもらうわ。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "あなたは千葉のモリイの店に行きなさい。あとは私達で話し合いをするから。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥‥‥そりゃ結構。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 66 #t)
   (proc 1))
 (seg (? (= S 2) (= 80 #f) (= 379 #f))
   (proc 0)
   (text "加藤は確かに嫌な奴だ。しかし、この男は軍人として最高のキャリアを積んできた人間なのに間違いない、それは一目でわかる。")
   (wait)
   (text-reset 14)
   (text "鍛えられた肉体は、幾多の戦場を潜り抜けて鍛え上げられたものであろうし、冷たい眼は人殺しのそれと何も変らない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 379 #t)
   (proc 1))
 (seg (? (= S 2) (= 80 #f) (= 365 #f))
   (proc 0)
   (text "長身の加藤が目の前に立つと、想像を絶する威圧感がある。隆起した筋肉は、軍服の上からでもわかる程だ。")
   (wait)
   (text-reset 14)
   (text "しかし、その羨むばかりの体つきとは裏腹に、こいつの頭の中は腐り果てている。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 365 #t)
   (proc 1))
 (seg (? (= S 2) (= 80 #f) (= 365 #t))
   (proc 0)
   (text "長身の加藤が目の前に立つと、想像を絶する威圧感がある。隆起した筋肉は、軍服の上からでもわかる程だ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 80 #f) (= 381 #f))
   (proc 0)
   (text "「Katou」" 'br)
   (text "どうかしたかね、少佐。私はよい報告しか耳にしたくはない。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "よく言うよ。何も言わなきゃ言わないでわたしを非難するくせに。あんたら軍人のやり方は気に入らないね。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "それはお互い様だな。私もかねがね情報部の怠惰なやり方には納得できかねる気でいたからな。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "目の前の的だけ見てりゃいい軍人と一緒にするな。こっちはいつ背後から撃たれるかもしれないし、郵便受けが爆発するかも‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "いつも恐怖と戦ってんだ。潜入工作はもっと辛い。回りが全員敵って感覚、あんたにはわかんないだろうね。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "それはお前とて同じ事だ。潜入捜査や公安の仕事に携わった事など一度もないのだろう？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 381 #t)
   (proc 1))
 (seg (? (= S 1) (= 80 #f) (= 381 #t))
   (proc 0)
   (text "「Katou」" 'br)
   (text "そんなに私が嫌いなら、早く任務を終えることだ。二度とお前と仕事をする事もないだろう。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 80 #t) (= 66 #t))
   (proc 0)
   (if (</>
        (//
         (? (= 63 #t))
         (nop@)
         (text "「Katou」" 'br)
         (text "ミツコの尋問が終わったら、彼女は軍が引き取る。彼女が秘書をしていた高官と同じように軍が処罰を決するのだ。")
         (wait)
         (text-reset 14))
        (//
         (? (= 62 #t))
         (nop@)
         (text "「Kiyomi」" 'br)
         (text "これから、ナナがミツコと待ち合わせた地下鉄に乗る。乗客の目もあるし、あまり派手にやりたくないけどね‥‥‥")
         (wait)
         (text-reset 14)
         (text "「Katou」" 'br)
         (text "ミツコが秘書をしていた軍部高官は、すでに更迭された。彼女にはもっと酷い目にあってもらわねばならん。")
         (wait)
         (text-reset 14))
        (//
         (? (= 61 #t))
         (nop@)
         (text "「Kiyomi」" 'br)
         (text "これからナナを尋問するけど‥‥‥何かある？")
         (wait)
         (text-reset 14)
         (text "「Katou」" 'br)
         (text "尋問が終わり次第、ナナは軍部が引き取る。他のふたりの囚人も同様だ。彼女らは軍法会議にかけられなければならんからな。")
         (wait)
         (text-reset 14))
        (//
         (? (= 67 #t) (= 386 #f))
         (nop@)
         (text "「Katou」" 'br)
         (text "どうかしたかね、少佐。")
         (wait)
         (text-reset 14))
        (//
         (? (= 67 #t) (= 386 #t))
         (nop@)
         (text "「Katou」" 'br)
         (text "わざわざ軍の技術をリークしてやったんだ、どんな事があっても囚人を捕まえて来い。")
         (wait)
         (text-reset 14))
        (//
         (text "「Katou」" 'br)
         (text "貴様が居ては、アンナ大佐と内密な話が出来ん。早く千葉に行ってモリイとやらに会って来い。")
         (wait)
         (text-reset 14))))
   (proc 1))
 (seg (? (= S 2) (= 80 #t) (= 382 #f))
   (proc 0)
   (text "「Katou」" 'br)
   (text "何をモタモタしているのだ？　そのモリイとかいう女を絞めあげて囚人の居所を吐かせればいだろう。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そんな簡単な事じゃないんだよ。相手は千葉の人間だ、こっちがそういう素振りを見せれば、逃げられるのがオチさ。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "馬鹿馬鹿しい。そんな事だから情報部は腑抜けだと言うんだ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "結構、それじゃあんたが何とかしな。わたしは降ろさせてもらう。そうすりゃ、嫌な顔を見なくてすむしね！")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "キヨミ‥‥‥もっと冷静になってちょうだい。解決策が無い訳ではないんだから。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 382 #t)
   (proc 1))
 (seg (? (= S 2) (= 80 #t) (= 382 #t))
   (proc 0)
   (text "「Katou」" 'br)
   (text "何をモタモタしているのだ？　そのモリイとかいう女を絞めあげて囚人の居所を吐かせればいだろう。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 80 #t) (= 384 #f))
   (proc 0)
   (text "わたしの部屋とは反対に面した所にあるアンナのオフィスからは、ごみごみした街を正面に見下ろしている。")
   (wait)
   (text-reset 14)
   (text "さらに上階にある為に展望には恵まれているが、見えるのがこの街並みでは、眺めが良いとは言えない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 384 #t)
   (proc 1))
 (seg (? (= S 3) (= 80 #t) (= 385 #f))
   (proc 0)
   (text "建物の正面に面した広い窓は、眼下の街からも丸見えのはずだ。いつこの窓から銃弾が飛び込んで来るかわからない。")
   (wait)
   (text-reset 14)
   (text "情報部内でも高い地位にあるアンナが、こんな最低の部屋をあてがわれるのは、彼女の出世を面白く思っていない連中がいるからだ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 385 #t)
   (proc 1))
 (seg (? (= S 3) (= 80 #t) (= 385 #t))
   (proc 0)
   (text "建物の正面に面した広い窓は、眼下の街からも丸見えのはずだ。いつこの窓から銃弾が飛び込んで来るかわからない。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 80 #f))
   (proc 0)
   (if (</>
        (//
         (? (= 63 #t))
         (nop@)
         (branch-index
          (</>
           (/
            (text "他の３人の囚人の証言で、軍の機密を盗もうと言い出したのがミツコであるのはわかっている。")
            (wait)
            (text-reset 14)
            (text "ただし、背後で彼女達を操っていた人間がいる事も明らか。ミツコがその人物を知っているはずだ。")
            (wait)
            (text-reset 14)
            (text "やっとこの事件全体を支配する、リズムやカラーを理解しかけた気がする。この分なら、もうじき任務は終了するだろう。")
            (wait)
            (text-reset 14))
           (/
            (text "ミツコを尋問すれば、事件の背後で彼女達を操っていた黒幕の存在がわかるはずだ。")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 62 #t))
         (nop@)
         (text "ナナがミツコと落ち合う約束をしたのは、東京と千葉を結ぶ地下鉄の中。そこに行けば、ミツコを捕らえる事が出来るだろう。")
         (wait)
         (text-reset 14))
        (//
         (? (= 61 #t))
         (nop@)
         (text "ナナはエイプリルやレイファと違って、ただの元兵士。拷問すれば簡単に口を割りそうだ‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 66 #t))
         (nop@)
         (text "アンナはモリイと知り合いだったのか？　モリイの店に行ってみろと言ってたが‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 65 #t))
         (nop@)
         (branch-index
          (</>
           (/
            (text "千葉の怪しげな店で会った女、モリイといった‥‥‥モリイは千葉の裏世界でもかなり知れた顔らしい。")
            (wait)
            (text-reset 14)
            (text "ふたりの事も、何か知っていそうな素振りだった。しかし、軍部や情報部の権威は、千葉では何の効力もない。")
            (wait)
            (text-reset 14)
            (text "力ずくでってのも、あの女が相手ではいい考えとも思えない‥‥‥どうしたらモリイの口を割る事ができる？")
            (wait)
            (text-reset 14))
           (/
            (text
             "モリイはナナとミツコの事を、何か知っているようだ。そうでなくても、千葉で情報を得る事が出来る。何とか味方につけなければ。")
            (wait)
            (text-reset 14)))))
        (//
         (branch-index
          (</>
           (/
            (text "エイプリルとレイファから聞き出した話だと、彼女達をスカウトしたのは、元軍部高官の秘書だったミツコらしい。")
            (wait)
            (text-reset 14)
            (text "そして、ミツコとナナは恋人同士だった。ふたりが一緒に千葉に潜伏しているという話は、まんざら嘘ではなさそうだ。")
            (wait)
            (text-reset 14))
           (/
            (text "次にわたしがすべき事は、ナナとミツコを捕まえる事だ。ふたりは千葉シティに逃げ込んだらしい。しかし‥‥‥")
            (wait)
            (text-reset 14)
            (text
             "千葉は政府や軍にも見捨てられた無法地帯、情報部の威光さえ届かない場所だ。ふたりをみつけるどころか、わたしの命さえ‥‥‥")
            (wait)
            (text-reset 14))
           (/
            (text "次にわたしがすべき事は、ナナとミツコを捕まえる事だ。ふたりは千葉シティに逃げ込んだらしい。しかし‥‥‥")
            (wait)
            (text-reset 14)))))))
   (proc 1))
 (seg (? (= S 4) (= 80 #t))
   (proc 0)
   (if (</>
        (//
         (? (= 63 #t))
         (nop@)
         (branch-index
          (</>
           (/
            (text "他の３人の囚人の証言で、軍の機密を盗もうと言い出したのがミツコであるのはわかっている。")
            (wait)
            (text-reset 14)
            (text "ただし、背後で彼女達を操っていた人間がいる事も明らか。ミツコがその人物を知っているはずだ。")
            (wait)
            (text-reset 14)
            (text "やっとこの事件全体を支配する、リズムやカラーを理解しかけた気がする。この分なら、もうじき任務は終了するだろう。")
            (wait)
            (text-reset 14))
           (/
            (text "ミツコを尋問すれば、事件の背後で彼女達を操っていた黒幕の存在がわかるはずだ。")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 62 #t))
         (nop@)
         (text "ナナがミツコと落ち合う約束をしたのは、東京と千葉を結ぶ地下鉄の中。そこに行けば、ミツコを捕らえる事が出来るだろう。")
         (wait)
         (text-reset 14))
        (//
         (? (= 61 #t))
         (nop@)
         (text "ナナはエイプリルやレイファと違って、ただの元兵士。拷問すれば簡単に口を割りそうだ‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 66 #t))
         (nop@)
         (text "アンナはモリイと知り合いだったのか？　モリイの店に行ってみろと言ってたが‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 65 #t))
         (nop@)
         (branch-index
          (</>
           (/
            (text "千葉の怪しげな店で会った女、モリイといった‥‥‥モリイは千葉の裏世界でもかなり知れた顔らしい。")
            (wait)
            (text-reset 14)
            (text "ふたりの事も、何か知っていそうな素振りだった。しかし、軍部や情報部の権威は、千葉では何の効力もない。")
            (wait)
            (text-reset 14)
            (text "力ずくでってのも、あの女が相手ではいい考えとも思えない‥‥‥どうしたらモリイの口を割る事ができる？")
            (wait)
            (text-reset 14))
           (/
            (text
             "モリイはナナとミツコの事を、何か知っているようだ。そうでなくても、千葉で情報を得る事が出来る。何とか味方につけなければ。")
            (wait)
            (text-reset 14)))))
        (//
         (branch-index
          (</>
           (/
            (text "エイプリルとレイファから聞き出した話だと、彼女達をスカウトしたのは、元軍部高官の秘書だったミツコらしい。")
            (wait)
            (text-reset 14)
            (text "そして、ミツコとナナは恋人同士だった。ふたりが一緒に千葉に潜伏しているという話は、まんざら嘘ではなさそうだ。")
            (wait)
            (text-reset 14))
           (/
            (text "次にわたしがすべき事は、ナナとミツコを捕まえる事だ。ふたりは千葉シティに逃げ込んだらしい。しかし‥‥‥")
            (wait)
            (text-reset 14)
            (text
             "千葉は政府や軍にも見捨てられた無法地帯、情報部の威光さえ届かない場所だ。ふたりをみつけるどころか、わたしの命さえ‥‥‥")
            (wait)
            (text-reset 14))
           (/
            (text "次にわたしがすべき事は、ナナとミツコを捕まえる事だ。ふたりは千葉シティに逃げ込んだらしい。しかし‥‥‥")
            (wait)
            (text-reset 14)))))))
   (proc 1))
 (seg*))