(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (branch-reg 55 (</> (/) (/ (mes-jump "mes¥ma_b03.mes"))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b01_01.gpc")
  (image-mem 0 3)
  (image-file "gpc¥b01_01a.gpc")
  (image-mem 1 0)
  (proc 3)
  (if (</>
       (//
        (? (= P 5))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (load-mem "clm¥b01_01a.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 913 #t))
        (text "「Anna」" 'br)
        (text "キヨミ‥‥‥囚人の手がかりは見つかった？")
        (wait)
        (text-reset 14))
       (//
        (? (= 913 #f))
        (text "「Anna」" 'br)
        (text "キヨミ‥‥‥どうしたの？")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "どうしたもこうしたもない。行き詰まりってやつさ。")
        (wait)
        (text-reset 14)
        (text "「Anna」" 'br)
        (text "市ヶ谷ベースには行ってみた？")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "もちろん。わたしが義務を果していないと思ってるでしょう。")
        (wait)
        (text-reset 14)
        (text "「Katou」" 'br)
        (text "そんな事はない、我々はお前に期待しているのだ。")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "そりゃどうも‥‥‥有り難いけど迷惑だね。")
        (wait)
        (text-reset 14)
        (text "「Katou」" 'br)
        (text "やむをえんだろう、すでに３人のエージェントが殺された話はしただろう？")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "そんな話は聞いてない。わざと黙ってたね‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Anna」" 'br)
        (text "‥‥‥‥‥‥‥‥‥")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 913 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 253 #t) (= 287 #t) (= 55 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 (</> (/ (str " 　　自分の部屋　　 "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (proc 0)
               (branch-reg
                55
                (</>
                 (/
                  (text "「Katou」" 'br)
                  (text "次に来る時は、吉報を携えている事を祈っている。")
                  (wait)
                  (text-reset 14)
                  (text "「Kiyomi」" 'br)
                  (text "‥‥‥‥‥‥‥‥‥‥‥‥"))
                 (/
                  (text "「Katou」" 'br)
                  (text "行くかね？　私の言った事を忘れるな。囚人に付けたマークを確認するんだ、いいな。")
                  (wait)
                  (text-reset 14)
                  (text "「Kiyomi」" 'br)
                  (text "言われなくてもそうする。囚人のマークとゴーグルの事を黙ってた件、絶対に忘れないからな‥‥‥"))))
               (wait)
               (text-reset 14)
               (mes-jump "mes¥MA_A02.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 287 #f))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 (</> (/ (str " 　　自分の部屋　　 "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (proc 0)
               (branch-reg
                55
                (</>
                 (/
                  (text "「Katou」" 'br)
                  (text "次に来る時は、吉報を携えている事を祈っている。")
                  (wait)
                  (text-reset 14)
                  (text "「Kiyomi」" 'br)
                  (text "‥‥‥‥‥‥‥‥‥‥‥‥"))
                 (/
                  (text "「Katou」" 'br)
                  (text "行くかね？　私の言った事を忘れるな。囚人に付けたマークを確認するんだ、いいな。")
                  (wait)
                  (text-reset 14)
                  (text "「Kiyomi」" 'br)
                  (text "言われなくてもそうする。囚人のマークとゴーグルの事を黙ってた件、絶対に忘れないからな‥‥‥"))))
               (wait)
               (text-reset 14)
               (mes-jump "mes¥MA_A02.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 253 #f))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 (</> (/ (str " 　　自分の部屋　　 "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (proc 0)
               (branch-reg
                55
                (</>
                 (/
                  (text "「Katou」" 'br)
                  (text "次に来る時は、吉報を携えている事を祈っている。")
                  (wait)
                  (text-reset 14)
                  (text "「Kiyomi」" 'br)
                  (text "‥‥‥‥‥‥‥‥‥‥‥‥"))
                 (/
                  (text "「Katou」" 'br)
                  (text "行くかね？　私の言った事を忘れるな。囚人に付けたマークを確認するんだ、いいな。")
                  (wait)
                  (text-reset 14)
                  (text "「Kiyomi」" 'br)
                  (text "言われなくてもそうする。囚人のマークとゴーグルの事を黙ってた件、絶対に忘れないからな‥‥‥"))))
               (wait)
               (text-reset 14)
               (mes-jump "mes¥MA_A02.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 55 #t))
   (proc 0)
   (text "「Anna」" 'br)
   (text "キヨミ、くれぐれも気をつけて‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 296 #t))
   (proc 0)
   (text "「Anna」" 'br)
   (text "何としてでも、彼女達を捕えなければ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 253 #t) (= 287 #t))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "このまんまじゃ、一生かかっても無理だね。ふたりを見つける事なんて不可能だよ。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "そう‥‥‥あなたに期待していたんだけど。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そんな眼で見ないでよ、こっちまで切なくなってくる。わたしにも不可能な事はある。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "でもね、私には他に頼れる人がいないのよ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そう言われてもね、このままじゃ方法がない。囚人のプロファイルを消されたのが致命的だったね。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "わかってる‥‥‥それはね。でも、それでもやはり捜索をやめる訳にはいかないわ。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "何としてでも、彼女達を捕えなければ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そう言われてもね‥‥‥不可能な事は不可能だよ。部員を１００人ほど貸してくれりゃ、話は別だけどね。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "それは無理よ。そんなに大勢の人間が関ったら秘密が守れないわ。特に、情報部の中に大穴が開いた今ではね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それじゃ、わたしにどうしろっての？")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 296 #t)
   (proc 1))
 (seg (? (= S 1) (= 295 #f))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "市ヶ谷ベースのカール大佐には会った。エイプリルとレイファの元上官ってやつ。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "それで‥‥‥彼はふたりの居所を知っていたの？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "絶対確実って訳じゃないけどね。エイプリルは除隊前に秋葉原のブラックマーケットに友達が居るって話してたらしい。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "レイファはチャイナタウンだってさ。その話を信用していいのかわからないけど。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "信じるしかないでしょう、他に手がかりがないんですもの。行ってみたの？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "いや、まだだけど‥‥‥わたしの前に３人のエージェントが殺されたって話は本当なの？")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "‥‥‥‥‥‥‥‥‥本当よ。黙っていてごめんなさい。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "まったくだ。もっと早く言ってほしかったね‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "それを話してしまったら、あなたは引き受けてくれたかしら？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 295 #t)
   (proc 1))
 (seg (? (= S 1) (= 296 #f))
   (proc 0)
   (text "「Anna」" 'br)
   (text "大佐に聞いた、秋葉原とチャイナタウンを探してみたら？")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 299 #t))
   (proc 0)
   (text "「Katou」" 'br)
   (text "早く行け。囚人を捕えて来い‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 55 #t))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "どうして囚人にマーキングしてた事を、言わなかった。それを知っていれば、こんなに苦労しなかったのに！")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "忘れたと言ったではないか。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "はん、そんな話は信用できないね。わたしに言わせればね、軍と情報部に開いた大穴ってのは、あんたの事だよ。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "何を言い出す‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "だってそうだろう、わたしが囚人を逮捕するのを遅らせて得する奴は誰だい。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "その間に女を始末するか、証拠を消しちまう事もできる。情報漏洩の黒幕ってのは、あんたの事なんじゃないのかい！")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "キヨミ！　何を言い出すの‥‥‥やめなさい。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "それ以上、無礼な口を聞かない方が身のためだぞ。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "キヨミ、だめよ‥‥‥抑えて。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたを拷問する日が来るかと思うと、楽しみだよ。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "早く行け。囚人を捕えて来い‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 299 #t)
   (proc 1))
 (seg (? (= S 2) (= 298 #t))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "それじゃ、どうすればいいのよ。お教えを賜りたいね。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "私なら、囚人を見分ける事など造作もない。彼女らには特殊フィルターを通さなければ見えないマークが刻まれている。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "なんだって？")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "フィルターは、部員の一部に支給されているゴーグルに含まれているはずだ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "どういう事なの。どうしてわたしにその事を言わなかった！　無駄足を踏まずにすんだのに！")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "言ってなかったか？　それは失礼。お前はいつもゴーグルを身に着けていたのだろう。皮肉なものだな‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "ゴーグルをかけて見さえすれば、囚人の体に刻まれた「卍」のマークが見えたのに。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わざと黙っていたな。どういう事だ、嫌がらせのつもり？")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "忘れていたと言った。誰にでもミスはつきものだからな。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "腹の中まで真っ黒な野郎だね、あんたは‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "そう怒るな、もう一度捜索すれば済む話じゃないか。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "秋葉原とチャイナタウンだったな？　そこに行って、ゴーグルをかけてみればいい。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 55 #t)
   (proc 1))
 (seg (? (= S 2) (= 253 #t) (= 287 #t))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "４人のうち、２人は居所がわかったよ、大体だけどね。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "だったら早く逮捕したらどうだ。このままでは、お前の怠慢と言われても仕方ないんじゃないかね？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ふたりの顔を教えてよ。わたしは何の情報ももらってない。ホロもプロファイルもなしじゃどうにもならない。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "ほう？　なるほど。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "秋葉原とチャイナタウンは探ってみたけどね、無駄足だった。あんた、これ以上わたしに無駄足を踏ませたいの？")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "そんな事はない。情報部に与えた貴重な経費を、部員を無駄に養う為に使うつもりはない。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "これ以上続けても、どうにもならないね。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "私はそうは思わんがね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたがどう思おうと関係ない。わたしが無理だって言うなら、それは無理なんだよ。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "そう、関係ない。顔もプロファイルもな‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "何の話をしてるんだい？")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 298 #t)
   (proc 1))
 (seg (? (= S 2) (= 297 #f))
   (proc 0)
   (text "「Katou」" 'br)
   (text "どうした。もう音をあげて許しを請いに来たのか？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "腹の中まで下衆な野郎だよ、あんたは。そんなにわたしが気に入らなきゃ、自分の部下を使えばいいだろう！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "てめえの部下が役立たずだから、わたしにお鉢が回ってきたんだ。違うかい。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "そう感情的になるな。さっさと責任を果して、楽になろうじゃないかね、お互いに。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしだって、出来る事ならそうしたい。")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "そう。汚物にまみれた道を行く時は、息を止めてさっさと通り過ぎるのが一番だ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Katou」" 'br)
   (text "お前には期待しているのだ、早く囚人を捕えてくれんかね。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 297 #t)
   (proc 1))
 (seg (? (= S 2) (= 297 #t))
   (proc 0)
   (text "「Katou」" 'br)
   (text "お前には期待しているのだ、早く囚人を捕えてくれんかね。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 300 #f))
   (proc 0)
   (text "わたしの部屋とは反対に面した所にあるアンナのオフィスからは、ごみごみした街を正面に見下ろしている。")
   (wait)
   (text-reset 14)
   (text "さらに上階にある為に展望には恵まれているが、見えるのがこの街並みでは、眺めが良いとは言えない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 300 #t)
   (proc 1))
 (seg (? (= S 3) (= 301 #f))
   (proc 0)
   (text "建物の正面に面した広い窓は、眼下の街からも丸見えのはずだ。いつこの窓から銃弾が飛び込んで来るかわからない。")
   (wait)
   (text-reset 14)
   (text "情報部内でも高い地位にあるアンナが、こんな最低の部屋をあてがわれるのは、彼女の出世を面白く思っていない連中がいるからだ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 301 #t)
   (proc 1))
 (seg (? (= S 3) (= 301 #t))
   (proc 0)
   (text "わたしの部屋とは反対に面した所にあるアンナのオフィスからは、ごみごみした街を正面に見下ろしている。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 55 #t))
   (proc 0)
   (text "囚人につけたマーキングと、それをわたしの持っているゴーグルで発見出来るって事‥‥‥")
   (wait)
   (text-reset 14)
   (text "加藤は絶対、故意に黙っていた。何故だろう。ただの嫌がらせか、それとも、もっと深い意味があるのか？")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 253 #t) (= 287 #t))
   (proc 0)
   (text "エイプリルとレイファの居所がわかったとしても、やはり今のままではふたりを見つける事は難しい。")
   (wait)
   (text-reset 14)
   (text "わたしが行き詰まっている事を、アンナと加藤にも伝えておくべきだろう、それはわたしのせいじゃないって事もだ！")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 302 #f))
   (proc 0)
   (text "アンナと加藤は、わたしの訪問をあまり喜んでいないようだ。" 'br)
   (text "わたしが任務半ばで不平を漏らしに来たと悟ったか‥‥‥")
   (wait)
   (text-reset 14)
   (text "確かにわたしだって、そんなみっともない真似はしたくない。でも今回は特別なんだって事をわからせておかないと。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 302 #t)
   (proc 1))
 (seg (? (= S 4) (= 302 #t))
   (proc 0)
   (text "アンナと加藤は、わたしの訪問をあまり喜んでいないようだ。" 'br)
   (text "わたしが任務半ばで不平を漏らしに来たと悟ったか‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))