(mes
 (meta (engine 'ADV) (charset "english") (extraop #t))
 (seg*
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b01_01.gpc")
  (image-mem 0 3)
  (image-file "gpc¥b01_01b.gpc")
  (image-mem 1 0)
  (proc 3)
  (if (</>
       (//
        (? (= P 5))
        (nop@))
       (//
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))))
  (load-mem "clm¥b01_01b.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 912 #t))
        (text-delay 0)
        (text "「Katou」" 'br)
        (text-delay 2)
        (text "Do you need something, Major?")
        (wait)
        (text-reset 14))
       (//
        (? (= 912 #f))
        (text-delay 0)
        (text "「Katou」" 'br)
        (text-delay 2)
        (text "How can I help you, Major?")
        (wait)
        (text-reset 14)
        (text "Katou...... How long is he going to stand around in here?")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Kiyomi」" 'br)
        (text-delay 2)
        (text "I seem to recall this being Anna's office, correct?")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Katou」" 'br)
        (text-delay 2)
        (text "This office has been assigned to me for the time being.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Katou」" 'br)
        (text-delay 2)
        (text "If you need to speak to the Colonel, you can find her in her private quarters.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Kiyomi」" 'br)
        (text-delay 2)
        (text "...............")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 912 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 211 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 6 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          (</> (/ (str "   Kiyomi's Room    ")) (/ (text "    Anna's Room     "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MA_A01.MES"))
              (// (? (= S 1)) (mes-jump "mes¥MA_C01.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 210 #f))
   (proc 0)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Everyone in Intelligence knows you don't like me, Katou.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "So why the hell did you pick me for this highly classified" 'br)
   (text "mission? You don't trust me at all.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "Unfortunately, I had no better options this time. However," 'br)
   (text "your judgement is flawed.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "I respect the badge, not the wearer. This is business. I haveno intention of letting personal feelings get in the way.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "And in addition, I don't dislike you. I just think of you" 'br)
   (text "as a very unique person.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Well, I'm honored... But still, I don't think it was smart tochoose me for this mission.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "Think about it this way: Even if the mission fails," 'br)
   (text "I won't be the one taking the blame for it.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "..................")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 210 #t)
   (proc 1))
 (seg (? (= S 1) (= 211 #f))
   (proc 0)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "This mission isn't just about capturing prisoners. We, the" 'br)
   (text "military, have lost a lot of reputation in certain circles." 'br)
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "Our situation is similar to the Yakuza. If we lose face," 'br)
   (text "we lose power. And that's bad for everyone.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "Do you understand? I've been lenient with you so far, but I" 'br)
   (text "expect this matter to be resolved quickly.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Ha? Why should I care about the military's reputation?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "......I must say, I'm at a loss as to how to handle you.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "You're not looking for a promotion or money, and if you" 'br)
   (text "wanted fame, you would get wired up and become a hacker.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "..................")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "So what do you want? And even if I or the military offered" 'br)
   (text "you what you want, would you refuse it?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "...Don't expect to understand me so easily.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Eccentric people like me are what make the world so" 'br)
   (text "interesting. Isn't that right, comrade?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "............")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 211 #t)
   (proc 1))
 (seg (? (= S 1) (= 211 #t))
   (proc 0)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "I'll be here for a while. If you need me, you can come" 'br)
   (text "by anytime.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 212 #f))
   (proc 0)
   (text "Katou might be an ass, but there's no doubt he's had one of" 'br)
   (text "the best careers in the military. That's obvious just by" 'br)
   (text "looking at him.")
   (wait)
   (text-reset 14)
   (text "His body has been honed by countless battles, and his cold" 'br)
   (text "eyes are no different from those of a killer.")
   (wait)
   (text-reset 14)
   (text "This guy doesn't wire his brain because he doesn't have to." 'br)
   (text "He can kill people without lifting a finger, and the" 'br)
   (text "information he wants will always come to him.")
   (wait)
   (text-reset 14)
   (text "So there's no need for him to go to the trouble of physical" 'br)
   (text "modification (pod-mod). Well, I suppose he could have other" 'br)
   (text "reasons too.")
   (wait)
   (text-reset 14)
   (text "Some monks and conservative doctors don't approve of" 'br)
   (text "cyberware enhancements, because they don't know enough about" 'br)
   (text "the long-term effects.")
   (wait)
   (text-reset 14)
   (text "It's possible Katou looks up to the monks and wants to follow")
   (text "their example, or that he takes the doctor's warnings about" 'br)
   (text "long-term danger seriously.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 212 #t)
   (proc 1))
 (seg (? (= S 2) (= 213 #f))
   (proc 0)
   (text "Katou's massive frame towering in front of me is incredibly" 'br)
   (text "intimidating. Even through his uniform, I can see the" 'br)
   (text "definition of his muscles.")
   (wait)
   (text-reset 14)
   (text "But despite his impressive physique, he's completely rotten" 'br)
   (text "on the inside.")
   (wait)
   (text-reset 14)
   (text "His smug attitude, which seems to proclaim his pride in being")
   (text "a true Japanese patriot and a military man, is something that")
   (text "innately disgusts me.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 213 #t)
   (proc 1))
 (seg (? (= S 2) (= 213 #t))
   (proc 0)
   (text "Katou's massive frame towering in front of me is incredibly" 'br)
   (text "intimidating. Even through his uniform, I can see the" 'br)
   (text "definition of his muscles.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 214 #f))
   (proc 0)
   (branch-reg 52
    (</>
     (/
      (text "There's no sign of Anna in her office. She said \"come see me" 'br)
      (text "in my room......\", so she must be in her private room.")
      (wait)
      (text-reset 14)
      (text "If that's the case, there's no point in staying here. Even" 'br)
      (text "though I haven't accepted the job yet, it'd be smart to" 'br)
      (text "gather as much information as possible.")
      (wait)
      (text-reset 14)
      (text "I've certainly gotten caught up in a nasty situation......"))
     (/
      (text "There's no sign of Anna in her office. Naturally, Anna" 'br)
      (text "wouldn't stay with Katou any longer than she had to.")
      (wait)
      (text-reset 14)
      (text "Is that why the uniformed guy who came to get me rushed me" 'br)
      (text "so much?")
      (wait)
      (text-reset 14)
      (text "I'm pretty sure he was also a member of the Intelligence" 'br)
      (text "Division. Very few people in this division think positively" 'br)
      (text "of Katou."))))
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 214 #t)
   (proc 1))
 (seg (? (= S 3) (= 215 #f))
   (proc 0)
   (text "I don't know what led up to this takeover, but I doubt Katou" 'br)
   (text "would give me any more information.")
   (wait)
   (text-reset 14)
   (text "Talking to this guy is a waste of time......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 215 #t)
   (proc 1))
 (seg (? (= S 3) (= 215 #t))
   (proc 0)
   (text "If Katou has been allowed to take over Anna's office for the" 'br)
   (text "foreseeable future, this mission must be" 'br)
   (text "seriously important.")
   (wait)
   (text-reset 14)
   (proc 1)))