(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b02_02.gpc")
  (image-mem 0 3)
  (if (</>
       (//
        (? (= P 7))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_07.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 7))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_07v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 7)))))
       (// (nop@))))
  (proc 3)
  (text-frame 10 312 70 383)
  (text "「アンナ」" 'br)
  (text "くっ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "アンナとするの、本当に久しぶりだね。それにしても悪い女だね、任務の最中だってのに不謹慎もいいとこ。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "言わないで‥‥‥お願い、明かりを消して！")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "こっちの方がわたしの好みなんだよ、知ってるでしょう？")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "誰かに見られているかもしれないのよ。隠しカメラがあるかもしれないわ。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "見せてやればいいじゃない。今頃、アンナのアソコを見ながらマスかいてるかもよ？")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "嫌な事、言わないで‥‥‥考えただけで気分が悪くなる！")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "あんたは日本人が大っキライだもんね、特に軍属の日本人。今濡れ場をモニターしてるような奴らがさ。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "んっ！　お願い‥‥‥変な事言わないで‥‥‥集中できないわ。")
  (wait)
  (text-reset 14)
  (text "アンナの皮膚は、白人とは思えないほど滑らかだ。部屋の中の温度と変らないくらい冷たい。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "本当に白い肌ね、寒い国の女は色白になるって言うけど‥‥‥")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "嫌よ、見ないで。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "誰に向かって言ってるの。わたし？　それとも、カメラの向こうでマスかいてる奴？")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "敏感な乳首と、脇の下へ舌を這わせる。恥ずかしそうな顔は、苦悶の表情に変わる。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "キヨミ、重いわ‥‥‥潰されてしまいそう。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "そりゃ、アンナよりは重いだろうさ。")
  (wait)
  (text-reset 14)
  (text "乳首を使って、アンナの体中を愛撫してやる。敏感になっているアンナは、そんな少しの刺激でも反応してしまうようだ。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "あッ‥‥‥くすぐったいわ！")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "でも気持ちいい？")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "ん‥‥‥そう、すごく気持ちいい‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "ポッドモッドで限りなく白に近いアンナの体。わたしの愛撫でほんのり上気しても、わずかに赤みが差すだけだ。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "随分感じてるみたいじゃない。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "それは‥‥‥キヨミが来てくれないから‥‥‥")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "アンナが嫌いな訳じゃないんだ、この部屋が嫌なの。情報部のビルもね。それは知ってるはずよ。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "その分、たっぷりサービスしてあげるよ。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "んっ‥‥‥あッ！")
  (wait)
  (text-reset 14)
  (text "アンナの脚の付け根にある、柔らかな花芯を指で押し開く。透明な粘液が溢れて、わたしの指を濡らした‥‥‥")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "感じてる‥‥‥ここ、熱くなってる。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "そう、感じてるわ、すごく‥‥‥ああ、キヨミ！")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "いい香い。アンナの汗の香い‥‥‥")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "ここだけは、ちゃんと色があるのね。奇麗なピンク色‥‥‥")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "キヨミ‥‥‥私を護って、お願い。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "いつだって護ってあげてるじゃない。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "アンナ、どうしてそんな事を言い出すの？")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "‥‥‥‥‥‥いいの、何でもない。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "余計な事を考えられないようにしてあげる。")
  (wait)
  (text-reset 14)
  (text "わたしは、アンナの胸を跡がつくほど強く揉みながら、自分の恥部をアンナに押し付ける。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "あっ、あッ‥‥‥キヨミ、ああッ")
  (wait)
  (text-reset 14)
  (text "湿った襞の擦れる音が、静寂で満たされた部屋に響く。")
  (wait)
  (text-reset 14)
  (text "わたしの恥部の、小さな突出した部分がアンナの突起に触れる。痺れるような甘美な刺激が脳を麻痺させ、快楽の深淵に沈んでいく。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "アンナ、もっと腰を使って。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "んっ‥‥‥キヨミ、あッ‥‥‥お願い、も、もう！")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "一緒に‥‥‥アンナ！")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "ああッ、ああぁぁッ！")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 5)
  (nop@)
  (set-reg 920 #t)
  (sound '|| 2)
  (delay 50)
  (sound '|| 0)
  (nop@)
  (set-var P 0)
  (exec-mem 3072 0)
  (mes-jump "mes¥MA_C01.MES")))