(mes
 (meta (engine 'ADV) (charset "english") (extraop #t))
 (seg*
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Kiyomi")
   (text-delay 15)
   (text "...... ")
   (delay 30)
   (text-delay 5)
   (text "I'm scared.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "What's wrong, Anna? Does Katou have dirt on you" 'br)
   (text "or something?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "If this gets much worse, the military will start looking for" 'br)
   (text "a scapegoat. And immigrants like me are the perfect target.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Don't be ridiculous, Anna. The military can't afford to" 'br)
   (text "ignore such a huge vulnerability in their organization.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "I'll do whatever it takes to find the traitor. It could be" 'br)
   (text "a sleeper agent, sent by some foreign country.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "From a foreign country, like me? That only makes" 'br)
   (text "things worse!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Whoa, Anna, calm down. You're acting crazy.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Easy for you to say...... You're full Japanese, after all.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "..................")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "I'm cold...")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "It's been cold outside, too. I think they're diverting the" 'br)
   (text "power meant for heating the city to somewhere else.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "No, that's not it......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Kiyomi, I need you to hold me tight.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "You're being quite demanding today, Anna. It's no surprise" 'br)
   (text "after you had to deal with Katou for so long.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "He really is a bastard.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Please, just hold me!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "......Ahh, fine. If that's what you really need.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 219 #t)
   (sound '|| 2)
   (delay 50)
   (if (</>
        (//
         (? (= P 6))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_06.uso")
               (sound '|| 3)
               (nop@)
               (set-var P 6))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_06v.uso")
               (sound '|| 3)
               (nop@)
               (set-var P 6)))))
        (// (nop@))))
   (exec-mem 3072 0)
   (mes-jump "mes¥MA_C01A.MES"))
 )