(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (if (</> (// (? (= 58 #t) (= 60 #t)) (mes-jump "mes¥ma_c03.mes")) (//)))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (if (</>
       (// (? (= 55 #f)) (image-file "gpc¥b02_01.gpc") (image-mem 0 3))
       (//
        (image-file "gpc¥b02_01.gpc")
        (image-mem 0 3)
        (image-file "gpc¥b02_01a.gpc")
        (image-mem 0 3)
        (load-mem "clm¥b02_01a.clm" 32768))))
  (proc 3)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= P 5))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (if (</>
       (//
        (? (= 55 #f))
        (text "アンナの姿はない。オフィスの方に居るんだろうか‥‥‥")
        (wait)
        (text-reset 14)
        (mes-jump "mes¥MA_A02.MES"))
       (//
        (? (= 921 #t))
        (text "「アンナ」" 'br)
        (text "キヨミ‥‥‥どうしたの？")
        (wait)
        (text-reset 14))
       (//
        (? (= 921 #f))
        (text "「Kiyomi」" 'br)
        (text "アンナ、ちょっと聞きたいんだけど‥‥‥")
        (wait)
        (text-reset 14)
        (text "「アンナ」" 'br)
        (text "どうしたの？　エイプリルとレイファは見つかった？")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "そんな事どうでもいい。")
        (wait)
        (text-reset 14)
        (text "「アンナ」" 'br)
        (text "どうでもいいって事はないでしょう‥‥‥怒っているの？")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "‥‥‥‥‥‥‥‥‥")
        (wait)
        (text-reset 14)
        (text "「アンナ」" 'br)
        (text "怖いわ、そんな目で見ないで。")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "‥‥‥‥‥‥‥‥‥‥‥‥")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 921 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 52 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 6 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          (</> (/ (str " 　　自分の部屋　 　")) (/ (text "　アンナのオフィス　"))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (branch-reg
                56
                (</>
                 (/ (mes-jump "mes¥MA_A02.MES"))
                 (/ (mes-jump "mes¥MA_A03.MES")))))
              (//
               (? (= S 1))
               (branch-reg
                55
                (</>
                 (/ (mes-jump "mes¥MA_B02.MES"))
                 (/ (mes-jump "mes¥MA_B03.MES")))))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 56 #t))
   (proc 0)
   (if (</>
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #f) (= 60 #f))
         (nop@)
         (branch-reg
          308
          (</>
           (/
            (text "「Kiyomi」" 'br)
            (text "エイプリルは逮捕したわ。")
            (wait)
            (text-reset 14)
            (text "「アンナ」" 'br)
            (text "そう‥‥‥やっぱり秋葉原だったの？")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "軍装屋の店員に化けてた。除隊前から隠れ蓑にしようと準備してたんだ。これから拷問にかけてみる。")
            (wait)
            (text-reset 14)
            (text "「アンナ」" 'br)
            (text "わかったわ。何か喋るといいけど‥‥‥")
            (wait)
            (text-reset 14)
            (nop@)
            (set-reg 308 #t))
           (/
            (text "「アンナ」" 'br)
            (text "エイプリルを尋問してみて‥‥‥何かわかったら、私に報告するのを忘れないでね。")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #f) (= 60 #f))
         (nop@)
         (branch-reg
          309
          (</>
           (/
            (text "「Kiyomi」" 'br)
            (text "エイプリルは大して情報を持ってなかった。")
            (wait)
            (text-reset 14)
            (text "「アンナ」" 'br)
            (text "最後まで拷問に屈しなかったって事は、考えられないの？")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "特殊部隊で苦痛に対する耐性を身につけたようだけど、わたしの拷問を受けて何も喋らなかったとは思えないね。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "エイプリルは、本当に何も知らないんだよ。レイファの方に賭けるしかないね。")
            (wait)
            (text-reset 14)
            (nop@)
            (set-reg 309 #t))
           (/
            (text "「アンナ」" 'br)
            (text "早くレイファを捕まえて。彼女がエイプリルの逮捕に気付いて逃亡する前にね。")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #t) (= 60 #f))
         (nop@)
         (branch-reg
          310
          (</>
           (/
            (text "「Kiyomi」" 'br)
            (text "レイファを捕まえた。予想通りチャイナタウンに居たよ‥‥‥")
            (wait)
            (text-reset 14)
            (text "「アンナ」" 'br)
            (text "そう‥‥‥早速取り調べを始めてちょうだい。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "そうする‥‥‥でも、レイファはどうしてチャイナタウンを隠れ場所に選んだのかね。誰でも考えつきそうな所なのに。")
            (wait)
            (text-reset 14)
            (text "「アンナ」" 'br)
            (text "たとえ危険だとわかっていても、同族の住む場所に居たかったのかしら。それとも、本気で逃げ果せると‥‥‥")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "だとしたら、レイファはよっぽどの自信家か、馬鹿ね。")
            (wait)
            (text-reset 14)
            (set-reg 310 #t))
           (/
            (text "「アンナ」" 'br)
            (text "レイファから何かを聞き出せればいいけど。せめて、第３の囚人の居場所だけでもわからないと‥‥‥")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (branch-reg
          311
          (</>
           (/
            (text "「Kiyomi」" 'br)
            (text "エイプリルとレイファは、ふたりとも逮捕したわ。まだ尋問にはかけてないけどね。")
            (wait)
            (text-reset 14)
            (text "「アンナ」" 'br)
            (text "お楽しみは、後でって訳？　あなた、そんな事が出来る性格じゃなかったと思うけど。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "囚人の心理って知ってるかい？　ふたりの囚人に、もうひとりの同僚を売れば無罪放免、売らなきゃ死刑って言うんだ。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "必ず吐くね。もうひとりの仲間が自分を売るんじゃないかって妄想に取り付かれて、だったら自分が先にってなる訳。")
            (wait)
            (text-reset 14)
            (text "「アンナ」" 'br)
            (text "それを、エイプリルとレイファに仕掛けるの‥‥‥")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "その必要もないかもしれない。少しは楽しませてほしいけど。")
            (wait)
            (text-reset 14)
            (text "「アンナ」" 'br)
            (text "尋問はあなたの専門。どうやろうと自由だけど、油断しないでね。相手は元特殊部隊、あなたと同じプロなんだから。")
            (wait)
            (text-reset 14)
            (nop@)
            (set-reg 311 #t))
           (/
            (text "「アンナ」" 'br)
            (text "尋問はあなたの専門、どうやろうと自由よ。だけど必ず口を割らせてね。")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (branch-reg
          311
          (</>
           (/
            (text "「Kiyomi」" 'br)
            (text "レイファを捕まえた。予想通りチャイナタウンに居たよ‥‥‥")
            (wait)
            (text-reset 14)
            (text "「アンナ」" 'br)
            (text "そう‥‥‥早速取り調べを始めてちょうだい。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "そうする‥‥‥でも、レイファはどうしてチャイナタウンを隠れ場所に選んだのかね。誰でも考えつきそうな所なのに。")
            (wait)
            (text-reset 14)
            (text "「アンナ」" 'br)
            (text "たとえ危険だとわかっていても、同族の住む場所に居たかったのかしら。それとも、本気で逃げ果せると‥‥‥")
            (wait)
            (text-reset 14)
            (text "「アンナ」" 'br)
            (text "先にレイファを尋問するの？　それとも、エイプリルを逮捕するつもりかしら。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "まだ考えてない。楽しみは後にってのもいいけど、レイファからエイプリルの情報を得られるかもしれないしね。")
            (wait)
            (text-reset 14)
            (nop@)
            (set-reg 311 #t))
           (/
            (text "「アンナ」" 'br)
            (text "先にレイファを尋問するの？　それとも、エイプリルを逮捕するつもりかしら。")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (branch-reg
          312
          (</>
           (/
            (text "「Kiyomi」" 'br)
            (text "レイファを尋問した。これ以上は何をやっても無駄だね。")
            (wait)
            (text-reset 14)
            (text "「アンナ」" 'br)
            (text "‥‥‥‥‥‥‥‥‥")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "わたしの感想を言おうか？　レイファは何も情報を持ってないよ。アンナ、あんたの事も信用できなくなってきた。")
            (wait)
            (text-reset 14)
            (text "「アンナ」" 'br)
            (text "どういう意味？")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "例の機密云々の話、全部嘘なんじゃないかって事。レイファは本当に何も知らなかったんだよ。")
            (wait)
            (text-reset 14)
            (text "「アンナ」" 'br)
            (text "それじゃ、彼女は何も知らずに協力したって事なんでしょう。もうひとりの‥‥‥エイプリルを捕まえなさい。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "‥‥‥‥‥‥‥‥‥‥‥‥")
            (wait)
            (text-reset 14)
            (text "「アンナ」" 'br)
            (text "キヨミ。私や加藤を信じないのは勝手だけど、とにかく任務は続けてもらうわ。")
            (wait)
            (text-reset 14)
            (nop@)
            (set-reg 312 #t))
           (/
            (text "「アンナ」" 'br)
            (text "早くエイプリルを捕まえて。彼女がレイファの逮捕に気付いて逃亡する前にね。")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (text "「Kiyomi」" 'br)
         (text "レイファは何も喋らなかった‥‥‥エイプリルを何とかしないと、わたし達はおしまいって訳ね。")
         (wait)
         (text-reset 14)
         (text "「アンナ」" 'br)
         (text "最初からそんな弱気になってどうするの？　尋問はあなたの得意でしょう。愉しみでもある、大丈夫よ‥‥‥きっと大丈夫。")
         (wait)
         (text-reset 14)
         (text "「Kiyomi」" 'br)
         (text "‥‥‥‥‥‥‥‥‥‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (text "「アンナ」" 'br)
         (text "エイプリルでもレイファでもいいわ。とにかく、どちらかを逮捕しないと、話は始まらないじゃない。")
         (wait)
         (text-reset 14))))
   (proc 1))
 (seg (? (= S 1) (= 305 #f))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "アンナ‥‥‥あんたは知ってたの？")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "何の話をしてるの？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "決まってるだろう、囚人に付けたマーキングの事だよ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それがわかってりゃ、今頃ふたりを逮捕できてた。あんたはその事を知ってたのかって聞いてんのさ。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "キヨミ、どうしてそんな事を聞くの。まさか私が‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "いいから。早く答えるんだよ。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "し、知らなかったわ。本当よ、私も初めて聞いたわ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "本当だろうね？")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "私が嘘をついて何になるの。そうでしょう？　キヨミに何の恨みがある訳じゃなし、囚人が捕まって困る訳でもないわ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "アンナもそう思う？　加藤がゴーグルとマークの事を教えなかったのは、囚人を捕まえられちゃ都合が悪いからじゃないかって？")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "‥‥‥‥‥‥そうかもしれないわね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "軍の機密を洩らした奴ってのは、本当は加藤なんじゃ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "声が大きいわ‥‥‥誰かに聞かれてるかもしれないのよ？")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "その話、ここでするのはまずいわ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 305 #t)
   (proc 1))
 (seg (? (= S 1) (= 305 #t))
   (proc 0)
   (text "「アンナ」" 'br)
   (text "とにかく、一刻も早く彼女達を捕まえてちょうだい。そうすれば、全てがわかるはずよ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 306 #f))
   (proc 0)
   (text "触れれば折れてしまいそうな華奢な体、ポッドモッドの為に驚くほど白い皮膚‥‥‥何処から見てもタフな人間には見えない。")
   (wait)
   (text-reset 14)
   (text "アンナが情報部でここまでの地位にまでのし上がるのは、並大抵の苦労ではなかったろう。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 306 #t)
   (proc 1))
 (seg (? (= S 2) (= 307 #f))
   (proc 0)
   (text "今まで聞いた事はないが、アンナは何歳なのだろうか。噂どおり元ＫＧＢだとしたら、わたしよりはるかに年上のはずだ。")
   (wait)
   (text-reset 14)
   (text "移民に限らず、この街にはアンナのような過去の知れない人間が多い。不老不死まであと一歩といったところか。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 307 #t)
   (proc 1))
 (seg (? (= S 2) (= 307 #t))
   (proc 0)
   (text "触れれば折れてしまいそうな華奢な体、ポッドモッドの為に驚くほど白い皮膚‥‥‥何処から見てもタフな人間には見えない。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 303 #f))
   (proc 0)
   (text "人々の体が発する熱やその他の雑事から発せられる湿気が、水蒸気の霧となって窓の外を漂っている。")
   (wait)
   (text-reset 14)
   (text "やがて雨になりそうな気配だ。街を管理する者達は、そうした現象を制御する努力をとっくの昔に止めてしまっている。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 303 #t)
   (proc 1))
 (seg (? (= S 3) (= 304 #f))
   (proc 0)
   (text "アンナの私室はわたしの部屋よりも低い位置にあり、眺めはさほどよくない。")
   (wait)
   (text-reset 14)
   (text "育ちすぎた木々の枝が視界をふさいで、外の様子をうかがい知る事はほとんど出来ないようだ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 304 #t)
   (proc 1))
 (seg (? (= S 3) (= 304 #t))
   (proc 0)
   (text "人々の体が発する熱やその他の雑事から発せられる湿気が、水蒸気の霧となって窓の外を漂っている。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 56 #t))
   (proc 0)
   (if (</>
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #f) (= 60 #f))
         (nop@)
         (text "まずはエイプリルを尋問してみよう。この事件全体を解く鍵がみつかるかもしれない。")
         (wait)
         (text-reset 14)
         (text "それが無理でも、レイファを逮捕するためのヒントか、第３の囚人を発見する手がかりを得られればいい。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #f) (= 60 #f))
         (nop@)
         (text "エイプリルがわたしの拷問に耐えられたとは思いたくない。彼女は本当に何も知らなかったのか‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #t) (= 60 #f))
         (nop@)
         (text "ふたり目の囚人、レイファを逮捕した。彼女を尋問すれば、何か情報が得られるかもしれない。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (text "ふたりの囚人は逮捕した。彼女達を尋問すれば、機密に関する情報を得られるだろう。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (text "レイファを逮捕した。彼女を尋問すれば、事件全体を解く鍵がみつかるかもしれない。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (text "レイファがわたしの拷問に耐えられたとは思いたくない。彼女は本当に何も知らなかったのか‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (text "レイファは何も喋らなかった。エイプリルを何とかしなければならない。どんな事でもいい、何とかしないと‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (text "まずはエイプリルかレイファを逮捕しなければならない。どちらから先にやるか‥‥‥")
         (wait)
         (text-reset 14))))
   (proc 1))
 (seg (? (= S 4) (= 313 #f))
   (proc 0)
   (text "加藤はゴーグルと囚人に付けたマークの事を、どうして黙っていたのだろう。")
   (wait)
   (text-reset 14)
   (text "その事を知っていれば、わたしはもっと早く囚人を逮捕出来たというのに。加藤には何か裏がありそうだ‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 313 #t)
   (proc 1))
 (seg (? (= S 4) (= 313 #t))
   (proc 0)
   (text "加藤はゴーグルと囚人に付けたマークの事を、どうして黙っていたのだろう。加藤には何か裏がありそうだ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))