(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (branch-reg 74 (</> (/) (/ (mes-jump "mes¥ma_c04.mes"))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (if (</>
       (// (? (= 64 #t)) (image-file "gpc¥b02_01.gpc") (image-mem 0 3))
       (// (? (= 66 #t)) (image-file "gpc¥b02_01.gpc") (image-mem 0 3))
       (//
        (? (= 65 #t))
        (image-file "gpc¥b02_01.gpc")
        (image-mem 0 3)
        (image-file "gpc¥b02_01a.gpc")
        (image-mem 0 3)
        (load-mem "clm¥b02_01a.clm" 32768))
       (// (image-file "gpc¥b02_01.gpc") (image-mem 0 3))))
  (proc 3)
  (if (</>
       (//
        (? (= P 5))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 64 #t))
        (text "アンナはオフィスに居るようだ。")
        (wait)
        (text-reset 14)
        (mes-jump "mes¥MA_A05.MES"))
       (//
        (? (= 66 #t))
        (text "部屋にアンナの姿はない。多分、オフィスの方に居るんだろう。")
        (wait)
        (text-reset 14)
        (mes-jump "mes¥MA_A04.MES"))
       (//
        (? (= 65 #t))
        (text "「キヨミ」" 'br)
        (text "アンナ、ここに居たの‥‥‥")
        (wait)
        (text-reset 14)
        (text "「アンナ」" 'br)
        (text "キヨミ‥‥‥どうしたの、浮かない顔ね。")
        (wait)
        (text-reset 14)
        (text "「キヨミ」" 'br)
        (text "そっちもあまり元気じゃなさそうだね。もっとも、加藤と四六時中顔あわせてりゃ、誰でも元気じゃなくなるけど。")
        (wait)
        (text-reset 14)
        (text "「アンナ」" 'br)
        (text "そうじゃないわ‥‥‥‥‥‥")
        (wait)
        (text-reset 14)
        (text "「アンナ」" 'br)
        (text "こういう嫌なお天気の日はね、頭の中のもうひとつの人格が目を覚ますのよ。脳に配線していないキヨミにはわからないかしら？")
        (wait)
        (text-reset 14)
        (text "「キヨミ」" 'br)
        (text "それが、ポッドモッドを受けた人間だけ感じる感覚ならね。単に気が滅入るって事なら想像がつくけど。")
        (wait)
        (text-reset 14)
        (text "「アンナ」" 'br)
        (text "ちょっと違うわね‥‥‥‥‥‥それで、何か用かしら？")
        (wait)
        (text-reset 14))
       (//
        (text "アンナの姿はない。何処に行ってしまったのだろう‥‥‥")
        (wait)
        (text-reset 14)
        (mes-jump "mes¥MA_A04.MES"))))
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 52 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 6 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          (</> (/ (str " 　　自分の部屋　 　")) (/ (text "　アンナのオフィス　"))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MA_A04.MES"))
              (// (? (= S 1)) (mes-jump "mes¥MA_B04.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 387 #f))
   (proc 0)
   (text "「キヨミ」" 'br)
   (text "エイプリルとレイファから得た情報を元に、千葉を捜索してる。残りのふたりの囚人を見つける為にね。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "そう‥‥‥千葉シティにね。任務とはいえ、あなたを千葉に送り出すのは嫌な気持ちね。")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "まあね、確かにお世辞にも素晴らしい街とは思わないけど。アンナは千葉に行った事があるの？")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "わたしが脳の配線をどうしたと思うの？　当時民間人だった私に手術する事が出来たのは、千葉の闇クリニックだけよ。")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "言われてみればそうかな‥‥‥民間人がおおっぴらにサイバネ治療を出来るようになったのは、ここ数年の話だ。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "それでも、私が今脳に配線しろって言われたら、やっぱり千葉に行くでしょうね。")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "それは‥‥‥どうして？")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "最新の技術があるから。まだ一般に公開されていない最新の技術がね。彼らがどうやってそれを手に入れたのかは知らないけど。")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 387 #t)
   (proc 1))
 (seg (? (= S 1) (= 388 #f))
   (proc 0)
   (text "「アンナ」" 'br)
   (text "話が外れたわね。それで‥‥‥千葉でどうしたの？")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "何しろあそこじゃ、情報部の権威は通じない。住民は全員余所者のわたしに猜疑的だし。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "昔ね、私もよく言われたわ。千葉にはカモとカモを待ってる詐欺師の２種類しかいないってね‥‥‥")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "うん、それで‥‥‥どうしようもないって訳。このまんまじゃ一生かかってもふたりを見つけられない。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "それは困ったわね。")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "大して困ってないような、悠長な言い方ね‥‥‥")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "そんな事はないわ。それで、どうするつもりなの？")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "千葉で、ある女に会ったんだ。名前はモリイ。千葉で如何わしい店をやってる。情報屋でもあるみたいだ。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "千葉の‥‥‥モリイね。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 388 #t)
   (proc 1))
 (seg (? (= S 1) (= 388 #t) (= 65 #t))
   (proc 0)
   (text "「キヨミ」" 'br)
   (text "モリイは何か知ってるみたいだった。わたし達の探してる囚人達の事をね。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "そんな事が有り得るかしら、ナナとミツコが目立つ行動をしてるとは思えないけど‥‥‥彼女達が素人だとしてもね。")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "もしまだ何も知らないとしても、モリイならふたりを探せるって。千葉の裏世界では、かなりの顔らしい。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "‥‥‥‥‥‥‥‥‥千葉のモリイ。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "確かに裏世界に精通しているようにも見えたわね。")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "アンナ、あの女の事を知ってるの？")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "そんな事はどうでもいいわ。それじゃ、モリイにふたりの囚人を探させればいいじゃない。")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "それが‥‥‥タダじゃ駄目らしい。軍部は金を払ってくれるかな。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "多分無理ね。それに、モリイは相手が情報部だって事を知っているのでしょう？　大金を要求してくるわ。")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "それじゃ、どうすればいいのさ？")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "そうね‥‥‥私に考えがあるわ。オフィスに行きましょう。")
   (wait)
   (text-reset 14)
   (text "「キヨミ」" 'br)
   (text "え‥‥‥どうするつもりなのさ？")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "加藤と話をしなければならないわね、大丈夫よ。いらっしゃい。")
   (wait)
   (text-reset 14)
   (proc 1)
   (nop@)
   (set-reg 80 #t)
   (exec-mem 3072 0)
   (mes-jump "mes¥MA_B04.MES"))
 (seg (? (= S 2) (= 389 #f))
   (proc 0)
   (text "今まで聞いた事はないが、アンナは何歳なのだろうか。噂どおり元ＫＧＢだとしたら、わたしよりはるかに年上のはずだ。")
   (wait)
   (text-reset 14)
   (text "移民に限らず、この街にはアンナのような過去の知れない人間が多い。不老不死まであと一歩といったところか。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 389 #t)
   (proc 1))
 (seg (? (= S 2) (= 390 #f))
   (proc 0)
   (text "触れれば折れてしまいそうな華奢な体、ポッドモッドの為に驚くほど白い皮膚‥‥‥何処から見てもタフな人間には見えない。")
   (wait)
   (text-reset 14)
   (text "アンナが情報部でここまでの地位にまでのし上がるのは、並大抵の苦労ではなかったろう。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 390 #t)
   (proc 1))
 (seg (? (= S 2) (= 390 #t))
   (proc 0)
   (text "今まで聞いた事はないが、アンナは何歳なのだろうか。噂どおり元ＫＧＢだとしたら、わたしよりはるかに年上のはずだ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 391 #f))
   (proc 0)
   (text "アンナの私室はわたしの部屋よりも低い位置にあり、眺めはさほどよくない。")
   (wait)
   (text-reset 14)
   (text "育ちすぎた木々の枝が視界をふさいで、外の様子をうかがい知る事はほとんど出来ないようだ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 391 #t)
   (proc 1))
 (seg (? (= S 3) (= 392 #f))
   (proc 0)
   (text "人々の体が発する熱やその他の雑事から発せられる湿気が、水蒸気の霧となって窓の外を漂っている。")
   (wait)
   (text-reset 14)
   (text "やがて雨になりそうな気配だ。街を管理する者達は、そうした現象を制御する努力をとっくの昔に止めてしまっている。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 392 #t)
   (proc 1))
 (seg (? (= S 3) (= 392 #t))
   (proc 0)
   (text "アンナの私室はわたしの部屋よりも低い位置にあり、眺めはさほどよくない。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4))
   (proc 0)
   (if (</>
        (//
         (? (= 63 #t))
         (nop@)
         (branch-index
          (</>
           (/
            (text "他の３人の囚人の証言で、軍の機密を盗もうと言い出したのがミツコであるのはわかっている。")
            (wait)
            (text-reset 14)
            (text "ただし、背後で彼女達を操っていた人間がいる事も明らか。ミツコがその人物を知っているはずだ。")
            (wait)
            (text-reset 14)
            (text "やっとこの事件全体を支配する、リズムやカラーを理解しかけた気がする。この分なら、もうじき任務は終了するだろう。")
            (wait)
            (text-reset 14))
           (/
            (text "ミツコを尋問すれば、事件の背後で彼女達を操っていた黒幕の存在がわかるはずだ。")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 62 #t))
         (nop@)
         (text "ナナがミツコと落ち合う約束をしたのは、東京と千葉を結ぶ地下鉄の中。そこに行けば、ミツコを捕らえる事が出来るだろう。")
         (wait)
         (text-reset 14))
        (//
         (? (= 61 #t))
         (nop@)
         (text "ナナはエイプリルやレイファと違って、ただの元兵士。拷問すれば簡単に口を割りそうだ‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 66 #t))
         (nop@)
         (text "アンナはモリイと知り合いだったのか？　モリイの店に行ってみろと言ってたが‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 65 #t))
         (nop@)
         (branch-index
          (</>
           (/
            (text "千葉の怪しげな店で会った女、モリイといった‥‥‥モリイは千葉の裏世界でもかなり知れた顔らしい。")
            (wait)
            (text-reset 14)
            (text "ふたりの事も、何か知っていそうな素振りだった。しかし、軍部や情報部の権威は、千葉では何の効力もない。")
            (wait)
            (text-reset 14)
            (text "力ずくでってのも、あの女が相手ではいい考えとも思えない‥‥‥どうしたらモリイの口を割る事ができる？")
            (wait)
            (text-reset 14))
           (/
            (text
             "モリイはナナとミツコの事を、何か知っているようだ。そうでなくても、千葉で情報を得る事が出来る。何とか味方につけなければ。")
            (wait)
            (text-reset 14)))))
        (//
         (branch-index
          (</>
           (/
            (text "エイプリルとレイファから聞き出した話だと、彼女達をスカウトしたのは、元軍部高官の秘書だったミツコらしい。")
            (wait)
            (text-reset 14)
            (text "そして、ミツコとナナは恋人同士だった。ふたりが一緒に千葉に潜伏しているという話は、まんざら嘘ではなさそうだ。")
            (wait)
            (text-reset 14))
           (/
            (text "次にわたしがすべき事は、ナナとミツコを捕まえる事だ。ふたりは千葉シティに逃げ込んだらしい。しかし‥‥‥")
            (wait)
            (text-reset 14)
            (text
             "千葉は政府や軍にも見捨てられた無法地帯、情報部の威光さえ届かない場所だ。ふたりをみつけるどころか、わたしの命さえ‥‥‥")
            (wait)
            (text-reset 14))
           (/
            (text "次にわたしがすべき事は、ナナとミツコを捕まえる事だ。ふたりは千葉シティに逃げ込んだらしい。しかし‥‥‥")
            (wait)
            (text-reset 14)))))))
   (proc 1))
 (seg*))