(mes
 (meta (engine 'ADV) (charset "english") (extraop #t))
 (seg*
  (branch-reg 54 (</> (/) (/ (mes-jump "mes¥ma_c02.mes"))))
  (if (</>
       (//
        (? (= 920 #t))
        (image-file "gpc¥waku.gpc")
        (image-mem 0 3)
        ((cmd 209) 1 5)
        (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
        (image-file "gpc¥b02_01.gpc")
        (image-mem 0 3)
        (image-file "gpc¥b02_01a.gpc")
        (image-mem 0 3)
        (proc 3)
        (if (</>
             (//
              (? (= P 5))
              (nop@))
             (//
              (if (</>
                   (//
                    (? (= O 0))
                    (sound '|| 0)
                    (sound '|| "uso¥xg_05.uso")
                    (sound '|| 1)
                    (nop@)
                    (set-var P 5))
                   (//
                    (? (= O 1))
                    (sound '|| 0)
                    (sound '|| "uso¥xg_05v.uso")
                    (sound '|| 1)
                    (nop@)
                    (set-var P 5)))))))
        (load-mem "clm¥b02_01a.clm" 32768)
        (text-frame 10 312 70 383)
        (set-reg 219 #t)
        (nop@)
        (text-delay 0)
        (text "「Anna」" 'br)
        (text-delay 2)
        (text "............")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Kiyomi」" 'br)
        (text-delay 2)
        (text "So, are you still cold?")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Anna」" 'br)
        (text-delay 2)
        (text "I'm fine now...... But I can't shake this feeling of guilt. I")
        (text "may have dragged you into something terrible, Kiyomi.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Kiyomi」" 'br)
        (text-delay 2)
        (text "Don't worry, we'll get through this together. Just like we" 'br)
        (text "always have before.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Anna」" 'br)
        (text-delay 5)
        (text "............")
        (text-delay 2)
        (wait)
        (text-reset 14)
        (nop@)
        (set-reg 920 #f))
       (//
        (? (= 919 #t))
        (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
        (image-file "gpc¥b02_01.gpc")
        (image-mem 0 3)
        (image-file "gpc¥b02_01a.gpc")
        (image-mem 0 3)
        (proc 3)
        (load-mem "clm¥b02_01a.clm" 32768)
        (text-frame 10 312 70 383)
        (text-delay 0)
        (text "「Anna」" 'br)
        (text-delay 2)
        (text "Kiyomi...... Have you found any leads?")
        (wait)
        (text-reset 14)
        (set-reg 52 #t)
        (nop@))
       (//
        (? (= 919 #f))
        (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
        (image-file "gpc¥b02_01.gpc")
        (image-mem 0 3)
        (image-file "gpc¥b02_01a.gpc")
        (image-mem 0 3)
        (proc 3)
        (load-mem "clm¥b02_01a.clm" 32768)
        (text-frame 10 312 70 383)
        (text-delay 2)
        (text "「Anna」" 'br)
        (text "Kiyomi......")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Kiyomi」" 'br)
        (text-delay 2)
        (text "I came, just like you asked.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Anna」" 'br)
        (text-delay 2)
        (text "I'm sorry about earlier, I had to act that way in front of" 'br)
        (text "Katou. Making an enemy of him would be stupid.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Kiyomi」" 'br)
        (text-delay 2)
        (text "I get that. But you're going to explain why you got me into" 'br)
        (text "this mess in the first place, right?")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Anna」" 'br)
        (text-delay 2)
        (text "I can't explain it. I had no choice.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Anna」" 'br)
        (text-delay 2)
        (text "There's no one I can rely on but you......")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 919 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 52 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 6 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          (</> (/ (str "   Kiyomi's Room    ")) (/ (text "   Anna's Office    "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MA_A01.MES"))
              (// (? (= S 1)) (mes-jump "mes¥MA_B01.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 219 #t) (= 52 #t))
   (proc 0)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "April and Lei-Fa's former commander is stationed" 'br)
   (text "at Ichigaya Base.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 219 #t) (= 52 #f))
   (proc 0)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "I suppose it was too much to hope that I could ignore this." 'br)
   (text "Alright, Anna, what do you need me to do?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Two of the prisoners...... April and Lei-Fa, their commander" 'br)
   (text "is over at Ichigaya Base.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Ichigaya Base, huh. How long were those two in the military?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Until a year ago. They completed their mandatory 3 years of" 'br)
   (text "service to earn citizenship, and are now in the reserves.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "You did say they were Special Forces. Three years on the" 'br)
   (text "front lines is impressive, especially for immigrants.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Yes, it is. They're no ordinary soldiers.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "These days, you can't throw a rock without hitting a former" 'br)
   (text "*something*. Hackers, hitmen... they're everywhere.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "The world has become a difficult place to live in for us.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "............Be careful out there.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Yeah, I've got to be careful. These women are" 'br)
   (text "real professionals......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 52 #t)
   (proc 1))
 (seg (? (= S 1) (= 218 #t) (= 221 #t) (= 225 #t))
   (proc 0)
   (mes-jump "mes¥MA_C01X.MES"))
 (seg (? (= S 1) (= 217 #f))
   (proc 0)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "I need you to break the situation down for me. How did the" 'br)
   (text "leak happen? And what's the relation between the 4 escapees?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "I can't tell you anything about the classified information." 'br)
   (text "I don't even have clearance to view it myself.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "However, it seems to be about a system being developed in" 'br)
   (text "partnership between the military and a private corporation.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "You're being pretty vague......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "I'm telling you all the details I know.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "So how did the prisoners get their hands" 'br)
   (text "on that information?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "We suspect it was leaked by Mitsuko, who used to be the" 'br)
   (text "secretary of a top military officer.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Of course, by now that officer has been dealt with.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "We don't know how the prisoners are connected. I don't think" 'br)
   (text "they knew each other at all before they were captured.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "It's likely that someone arranged their meeting. And that" 'br)
   (text "\"someone\" is probably in intel or the military.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Otherwise, it would be nearly impossible for four prisoners" 'br)
   (text "to escape at once.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Yes, that's what we think too......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 217 #t)
   (proc 1))
 (seg (? (= S 1) (= 218 #f))
   (proc 0)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Tell me more about the contents of the stolen classified" 'br)
   (text "information. I don't know enough to get the full picture.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "It started with the military and its private business partner")
   (text "working together to build some kind of system.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Someone, somewhere, found out about it and decided to hire" 'br)
   (text "former professionals to steal info about the secret tech...")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Right... The team successfully stole the information and" 'br)
   (text "passed it on to the boss who hired them.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "But you don't know if they delivered the stolen intel or not,")
   (text "right? Since the culprit was caught shortly afterwards.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "It's hard to believe that a \"professional\" would make" 'br)
   (text "such a simple mistake.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "That's true......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "However, the captured team member was broken out and" 'br)
   (text "disappeared before we could interrogate them.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "It appears someone within the military helped them escape." 'br)
   (text "Or at least, someone with serious inside connections.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Yeah, the situation is pretty bad. If this gets out, the" 'br)
   (text "intel director's head will roll.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Even that wouldn't fix things.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 218 #t)
   (proc 1))
 (seg (? (= S 1) (= 218 #t))
   (proc 0)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "There's still a leak in our organization that" 'br)
   (text "hasn't been found.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 220 #f))
   (proc 0)
   (text "Her slender body looks like it would break if you touched it.")
   (text "For a pod-mod, her skin is unusually pale. No matter how I" 'br)
   (text "look at her, she doesn't seem tough at all.")
   (wait)
   (text-reset 14)
   (text "Climbing the ranks to her current position in intel must have")
   (text "been a difficult battle.")
   (wait)
   (text-reset 14)
   (text "I know she has a socket, though it's not visible from this" 'br)
   (text "angle. It was probably essential for her to get this far.")
   (wait)
   (text-reset 14)
   (text "To survive in this world, you either have to be" 'br)
   (text "tough as nails or sharp as a razor.")
   (wait)
   (text-reset 14)
   (text "I doubt anyone would blame her for enhancing her body" 'br)
   (text "to compensate for her weakness.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 220 #t)
   (proc 1))
 (seg (? (= S 2) (= 221 #f))
   (proc 0)
   (branch-reg
    218
    (</>
     (/
      (text "I've never heard anyone mention it before, but I wonder how" 'br)
      (text "old Anna is. If she's ex-KGB like the rumours say, then she'd")
      (text "have to be much older than me.")
      (wait)
      (text-reset 14)
      (text "This city is full of people like Anna with unknown pasts. Not")
      (text "just immigrants, either. It's like they're all" 'br)
      (text "frozen in time."))
     (/
      (text "Anna seems to have lost her usual calm demeanor." 'br)
      (text "Her slender fingers are clasped in front of her, " 'br)
      (text "trembling slightly.")
      (wait)
      (text-reset 14)
      (text "Anna's trendy, intricate, and flamboyant dress is carefully" 'br)
      (text "designed to make her body appear larger than she really is.")
      (wait)
      (text-reset 14)
      (text "But thanks to her anxious look and posture, the tailor's hard")
      (text "work is undone and she looks like a helpless child" 'br)
      (text "in adult's clothes.")
      (wait)
      (text-reset 14)
      (text "What could have Anna so worried?")
      (nop@)
      (set-reg 221 #t))))
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 221 #t))
   (proc 0)
   (text-delay 2)
   (text "Anna's shaking has gotten more intense, her arms wrapped" 'br)
   (text "tightly around her body as though she's freezing.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 222 #f))
   (proc 0)
   (text "Anna's private room is lower than mine, and the view" 'br)
   (text "isn't quite as good.")
   (wait)
   (text-reset 14)
   (text "The view is blocked by overgrown tree branches, and the soundfrom outside is muffled as well.")
   (wait)
   (text-reset 14)
   (text "However, in this city, the higher a room is, the lower it is.")
   (text "The whole building is located more than a hundred" 'br)
   (text "meters underground.")
   (wait)
   (text-reset 14)
   (text "The real important people live further underground in the" 'br)
   (text "city. If a disaster were to happen and the roof caved in, all")
   (text "these exposed buildings would be obliterated.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 222 #t)
   (proc 1))
 (seg (? (= S 3) (= 223 #f))
   (proc 0)
   (text "The heat emitting from people's bodies and the moisture" 'br)
   (text "drifting up from the ground combine to create a thick mist" 'br)
   (text "that lingers outside the window.")
   (wait)
   (text-reset 14)
   (text "Soon, that mist will condense into rain. The city planners" 'br)
   (text "stopped trying to manage the weather long ago.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 223 #t)
   (proc 1))
 (seg (? (= S 3) (= 223 #t))
   (proc 0)
   (text-delay 2)
   (text "Outside the window, it's as dark as night because of the" 'br)
   (text "drifting fog. But day and night look practically the same" 'br)
   (text "here, save for the brightness of the sky-lights.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 224 #f))
   (proc 0)
   (text "Anna's room is full of furniture from her homeland, making itone of the most unique rooms in the division.")
   (wait)
   (text-reset 14)
   (text "Though, if you consider that it's her only home, it seems" 'br)
   (text "very sterile. If Anna wasn't here, I'd think this was" 'br)
   (text "a storage room.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 224 #t)
   (proc 1))
 (seg (? (= S 4) (= 225 #f))
   (proc 0)
   (text "With her high rank, there's no reason Anna should be required")
   (text "to stay in the intelligence building.")
   (wait)
   (text-reset 14)
   (text "The reason she's still here is probably for her own safety." 'br)
   (text "There are people all over the city who are bitter about" 'br)
   (text "people like Anna succeeding.")
   (wait)
   (text-reset 14)
   (text "How can a single woman, especially someone delicate" 'br)
   (text "like Anna, possibly live alone safely?")
   (wait)
   (text-reset 14)
   (text "It's practically impossible for her to move out" 'br)
   (text "of this building.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 225 #t)
   (proc 1))
 (seg (? (= S 4) (= 225 #t))
   (proc 0)
   (text-delay 2)
   (text "This place may be lonely and empty, but it's Anna's only" 'br)
   (text "place to live. Better this than living on the street......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))