(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b12_01.gpc")
  (image-mem 0 3)
  (proc 3)
  (if (</>
       (//
        (? (= P 4))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_04.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 4))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_04v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 4)))))
       (// (nop@))))
  (text-frame 10 312 70 383)
  (text "「Kiyomi」" 'br)
  (text "アンナ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "遅かったわね。私が怪しいって、前から気付いてたんでしょう？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "それじゃ、やっぱり‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "だからあなたがここに居る。そうじゃない？　何をやっているの、早く捕まえなさい。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "弁解しないの？")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "どうでもいいわ、もう何も考えたくないの‥‥‥")
  (wait)
  (text-reset 14)
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b02_01.gpc")
  (image-mem 0 3)
  (image-file "gpc¥b02_01a.gpc")
  (image-mem 0 3)
  (load-mem "clm¥b02_01a.clm" 32768)
  (proc 3)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 476 #t) (= 478 #t))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "データベースから抜き取った情報を出しな。それさえ回収すれば、わざわざ拷問する必要もない。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "持ってないわ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたの為を思って言ってるんだ。わたしに隠し通せると思ってるんなら、考えを改めた方がいい。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "持っていないって言ってるでしょう！")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "あなた達、大っ嫌いよ。どうしてただ日本人なだけで特別なの。移民じゃいけないの？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そんな事は言ってない。いいから、早く出すんだ！")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "お断わりよ、この情報はロシアまで持って帰る。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "まさか‥‥‥自分がスパイだって言ってるの？")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "だったらどうだって言うの。拷問して吐かせたらどう？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "仕方ないね‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "本当にそうするしかないようだよ。アンナにこんな事はしたくないんだけどね‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1)
   (exec-mem 3072 0)
   (mes-jump "mes¥MD_G01.MES"))
 (seg (? (= S 1) (= 475 #f))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "あんたが自分で囚人達を操って、軍から情報を盗んだんなら、どうしてわたしに任務を押し付けたんだい。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしなら途中で任務を投げ出して、自分に危険が及ぶ事が無いとでも考えてたの？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それとも、エイプリルかレイファにでも殺させるつもりだったの？まさかわたしが、あいつらに勝てるとは思わないものね。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "ち、違うわ。そうじゃないのよ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それじゃ、どういう事なのか説明してもらいたいね。釈明ぐらいしたらどうなんだ。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "なんで黙ってるんだい、あんたも他の囚人のように拷問されたい？わたしが出来ないと思ってるのかね。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 475 #t)
   (proc 1))
 (seg (? (= S 1) (= 476 #f))
   (proc 0)
   (text "「Anna」" 'br)
   (text "御託を並べてないで、早く私を拷問したらいいでしょう？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "なんだって‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "早く拷問すればいいって言ってるのよ。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "私は何も喋らないわ、あなたは自分をプロだと思ってるらしいけどとんでもない、自惚れもいいとこよ。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "キヨミ、あなたはただのサディスト。拷問好きのアマチュアにすぎないわ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "自分がプロだと言いたいのかい。どうしてデータベースから情報を消去した。そんな事をしたら、バレるに決まってるじゃない。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "同じ盗むにしても、あんたがプロだってなら消去せずコピーを取るだけにしとく。それが当たり前のやり方だろう？")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そんな事はどうでもいい。もっと他にあるだろう。このままじゃ裁判も受けられない、加藤の思うがままになるんだよ？")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "そんな事はどうでもいいわ。早くやりなさい！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "しかし‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "あなたはそれだけが取り柄でしょう。人が苦しむ姿を見るのが心底好きで仕方ない、本物の異常者！")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "ええそうよ、あなたならエイプリルかレイファに殺されると思ってたわ。絶対に任務に失敗すると信じてたのよ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "いい加減にしな、その口を閉じるんだ。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "モリイに殺させるのも、良かったかもしれないわね！")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "死体は臓器屋が始末して、骨さえ残らないもの。ふたりを千葉に隠れさせたのは、あなたなら恐れて何も出来ないと思ったからよ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 476 #t)
   (proc 1))
 (seg (? (= S 1) (= 476 #t))
   (proc 0)
   (text "「Anna」" 'br)
   (text "御託はもういいわ、同情もして欲しくない。早く私を拷問にかければいいでしょう？")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 477 #f))
   (proc 0)
   (text "ポッドモッドで色の白いアンナの顔は、普段よりも一層青ざめているように見える。")
   (wait)
   (text-reset 14)
   (text "わたしがここにやって来る事は、プリスが尋問された時からわかっていたはずだ。顔色が悪いのもそのせいか‥‥‥")
   (wait)
   (text-reset 14)
   (text "しかし、わかっていたのならどうして逃げなかったのか。身柄を拘束されていた訳ではない、いつでもそう出来たはずなのに。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 477 #t)
   (proc 1))
 (seg (? (= S 2) (= 478 #f))
   (proc 0)
   (text "アンナは努めて平静を装っている。この分では、隠したソフトの在処を白状するとは思えない。")
   (wait)
   (text-reset 14)
   (text "しかし、いかにも華奢で病弱そうなアンナがわたしの尋問に耐えられるだろうか。")
   (wait)
   (text-reset 14)
   (text "わたしが本気で尋問したら、アンナは死んでしまうかもしれない。むしろ、それがアンナの望みなのだろうか？")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 478 #t)
   (proc 1))
 (seg (? (= S 2) (= 478 #t))
   (proc 0)
   (text "華奢で病弱そうなアンナが、わたしの尋問に耐えられるだろうか。悪くすれば、死んでしまうかもしれない‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 479 #f))
   (proc 0)
   (text "窓の外は、いよいよ雨になってしまった。この街に降る雨は、全て街で発生した蒸気や様々な生産活動の老廃物のような物だ。")
   (wait)
   (text-reset 14)
   (text "害は無いと言うが、どれだけ信用出来る？　この雨に打たれるのはぞっとしない。外には出ない事だ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 479 #t)
   (proc 1))
 (seg (? (= S 3) (= 480 #f))
   (proc 0)
   (text "冷気が窓のガラスを通して、室内にも忍び込んで来る。今にも雪になりそうな気配だ。")
   (wait)
   (text-reset 14)
   (text "雪を見るのは何年ぶりだろう、子供の頃以来だ。アンナも故郷の国を捨てて以来のはずだ‥‥‥")
   (wait)
   (text-reset 14)
   (text "今のこの状況を察した何者かが、わざとやっている。その考えがあながち嘘でないと思うわたしは、妄想に取り付かれているのか？")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 480 #t)
   (proc 1))
 (seg (? (= S 3) (= 480 #t))
   (proc 0)
   (text "窓の外は、いよいよ雨になってしまった。この街に降る雨は、全て街で発生した蒸気や様々な生産活動の老廃物のような物だ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4))
   (proc 0)
   (branch-index
    (</>
     (/
      (text "加藤が言っていた、残りの情報。システムのソフトさえ取り戻せばアンナを尋問する必要はない。")
      (wait)
      (text-reset 14)
      (text "アンナはわたしの説得に応じるだろうか。そうでなければ、本当に拷問にかけなければならないが‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "アンナがどうして軍部のデータベースに手を付けたのか。そういう事を一切言おうとしないのは何故なのか‥‥‥")
      (wait)
      (text-reset 14)
      (text "訳も無くアンナがそんな事をする訳はない。その理由を話さないのは、わたしの事を信じていないからだろうか。")
      (wait)
      (text-reset 14))
     (/
      (text "このままでは、本当にアンナを尋問しなければならない。アンナの体では、拷問に耐える事は出来ないだろう。")
      (wait)
      (text-reset 14))))
   (proc 1))
 (seg*))