(mes
 (meta (engine 'ADV) (charset "english") (extraop #t))
 (seg*
  (branch-reg 56 (</> (/) (/ (mes-jump "mes¥mb_a02.mes"))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b15_01.gpc")
  (image-mem 0 3)
  (if (</>
       (//
        (? (= P 3))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_03.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_03v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3)))))
       (// (nop@))))
  (load-mem "clm¥b15_01.clm" 32768)
  (proc 3)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 54 #t))
        (text "I have an idea where April and Lei-Fa are, but......")
        (wait)
        (text-reset 14)
        (text "I don't even know what they look like, so how am I supposed" 'br)
        (text "to recognise them?")
        (wait)
        (text-reset 14))
       (//
        (? (= 922 #t) (= 53 #t))
        (nop@)
        (text "I walk out of the Intelligence Division building.")
        (wait)
        (text-reset 14)
        (branch-reg
         52
         (</>
          (/ (text "Although, I still don't even know where to start......"))
          (/
           (text "I should go meet April and Lei-Fa's old boss. Even if he" 'br)
		   (text "doesn't have much information, it's worth going to Ichigaya" 'br)
		   (text "Base anyway."))))
        (wait)
        (text-reset 14))
       (//
        (? (= 922 #f))
        (text "I exit the intelligence office and step into the streets." 'br)
		(text "This area is well patrolled by the military, so it's" 'br)
		(text "relatively safe.")
        (wait)
        (text-reset 14)
        (text "Intelligence has offices all over the city, usually" 'br)
		(text "disguised as companies that work with the military. This one" 'br)
		(text "doesn't try to hide itself, though.")
        (wait)
        (text-reset 14)
        (text "That means the office is an easy target for would-be" 'br)
		(text "terrorists, which is why there are so many plainclothes" 'br)
		(text "agents walking the streets and keeping this district safe.")
        (wait)
        (text-reset 14)
        (branch-reg
         52
         (</>
          (/
           (text "I doubt any escaped prisoners would be here. They'd be far" 'br)
		   (text "better off hiding in Chinatown or the maze that is" 'br)
		   (text "Chiba City.")
           (wait)
           (text-reset 14)
           (text "There are a lot of criminals and seedy types in those parts." 'br)
		   (text "If I were them, I'd just go to ground and lie low until" 'br)
		   (text "things cool down......"))
          (/
           (text "No escaped prisoner would come to a place like this. If they" 'br)
		   (text "were smart, they wouldn't set foot anywhere in Ichigaya," 'br)
		   (text "either.")
           (wait)
           (text-reset 14)
           (text "Because of that, I really doubt April and Lei-Fa's old CO" 'br)
		   (text "would know where they are.")
           (wait)
           (text-reset 14)
           (text "Well, unless the \"old CO\" is the mastermind behind" 'br)
		   (text "all this......"))))
        (nop@)
        (set-reg 53 #t)
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 922 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 96")
         (set-var X 3)
         (when (</>
                (// (? (= 52 #t)) (nop@) (inc-var X 1))
                (// (? (= 54 #t)) (nop@) (inc-var X 1))))
         (if (</>
              (// (? (= X 3)) (exec-mem 4768 5 9 22 8 1 0 0 4480 4480 1 0))
              (// (? (= X 4)) (exec-mem 4768 5 9 22 10 1 0 0 4480 4480 1 0))
              (// (? (= X 5)) (exec-mem 4768 5 9 22 12 1 0 0 4480 4480 1 0))))
         (menu1
          6
          80
          6
          96
          6
          112
          6
          128
          6
          144
          (</>
           (/ (str "  Intel Dept. Bldg  "))
           (/ (str "     Chinatown      "))
           (/ (str "     Chiba City     "))
           (/ (set-reg 52 #t) (nop@) (text "   Ichigaya Base   "))
           (/ (set-reg 54 #t) (nop@) (str "     Akihabara     "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (if (</>
                    (// (? (= 54 #t)) (nop@) (mes-jump "mes¥MA_A02.MES"))
                    (// (mes-jump "mes¥MA_A01.MES")))))
              (// (? (= S 1)) (mes-jump "mes¥MB_C01.MES"))
              (// (? (= S 2)) (mes-jump "mes¥MB_E01.MES"))
              (// (? (= S 3)) (mes-jump "mes¥MB_B01.MES"))
              (// (? (= S 4)) (mes-jump "mes¥MB_D01.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 226 #f))
   (proc 0)
   (text "This area is safe because of all the military presence" 'br)
   (text "nearby. The housing is relatively nice, and all the best" 'br)
   (text "hotels are here.")
   (wait)
   (text-reset 14)
   (text "しかし、わたしにとってそれらは全く関りのない世界だ。多くの軍関係者もそうだろう。")
   (wait)
   (text-reset 14)
   (text "毎日金持ち日本人の暮らしぶりを見ていれば、嫌らしい小役人のような人間になってしまっても仕方のない事なのか‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 226 #t)
   (proc 1))
 (seg (? (= S 1) (= 227 #f))
   (proc 0)
   (text "巨大なビルがはるか上空まで伸びている。街の至る所に、このビルのように地殻を支える柱の役目を果している建物がある。")
   (wait)
   (text-reset 14)
   (text "この辺りの建物はまだ管理もしっかりしているし、頻繁に手を入れられているが、スラムに行くとこうはいかない。")
   (wait)
   (text-reset 14)
   (text "本当に地殻を支える役を負っているとしたら、背筋が寒くなるような倒壊しそうな建物が多いのだ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 227 #t)
   (proc 1))
 (seg (? (= S 1) (= 227 #t))
   (proc 0)
   (text "巨大なビルがはるか上空まで伸びている。街の至る所に、このビルのように地殻を支える柱の役目を果している建物がある。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 228 #f))
   (proc 0)
   (text "人々の体が発する熱や、その他の雑事から発せられる湿気が、水蒸気の霧となって上空を漂っている。")
   (wait)
   (text-reset 14)
   (text "考えてみれば奇異な光景だが、わたし達にとってはすでに当たり前の光景だ。やがて雨が降りだすだろう。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 228 #t)
   (proc 1))
 (seg (? (= S 2) (= 229 #f))
   (proc 0)
   (text "はるか上空にコンクリートとクロームの地殻が、霧に見え隠れしている。")
   (wait)
   (text-reset 14)
   (text "もう何十年もの間この空を見続けて来たわたしだが、未だに不安感は消えない。")
   (wait)
   (text-reset 14)
   (text "いつかこの空が落ちてくるのかも‥‥‥という懸念は、永遠になくならないだろう。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 229 #t)
   (proc 1))
 (seg (? (= S 2) (= 229 #t))
   (proc 0)
   (text "はるか上空にコンクリートとクロームの地殻が、霧に見え隠れしている。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 230 #f))
   (proc 0)
   (text "この一角は金持ちの日本人が多い。彼らは無防備で街中を歩く危険を犯そうとしないのだろう、歩いている人は少ない。")
   (wait)
   (text-reset 14)
   (text "昼でもなお薄暗いこの街ではいつでも犯罪が起こりうるし、わざわざ部屋から出る必要もない。特に金持ちなら。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 230 #t)
   (proc 1))
 (seg (? (= S 3) (= 231 #f))
   (proc 0)
   (text "情報部へ向かうヘリの中で感じた冷気は、今でも少しも衰えていない。まばらな人並みと相まってひどく寒々しい雰囲気がする。")
   (wait)
   (text-reset 14)
   (text "しかし、あまり季節の移り変わりを感じる事がない街の中で、この寒さだけが冬である事の証明であるなら、それも歓迎すべき事か。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 231 #t)
   (proc 1))
 (seg (? (= S 3) (= 231 #t))
   (proc 0)
   (text "情報部へ向かうヘリの中で感じた冷気は、今でも少しも衰えていない。まばらな人並みと相まってひどく寒々しい雰囲気がする。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 232 #t))
   (proc 0)
   (text "ふたりの囚人が居そうな場所の見当はついた。しかし、ふたりの顔さえ知らないのに、どうやって見つけたらいい？")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 54 #t))
   (proc 0)
   (text "ふたりの囚人が居そうな場所の見当はついた。しかし、ふたりの顔さえ知らないのに、どうやって見つけたらいい？")
   (wait)
   (text-reset 14)
   (text "アンナか加藤に相談してもいいんじゃないだろうか‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 232 #t)
   (proc 1))
 (seg (? (= S 4) (= 52 #t))
   (proc 0)
   (text "とにかく、まずは市ヶ谷ベースに行かなければならない。たとえ、ふたりの元上官が、大した情報を持っていないとしてもだ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4))
   (proc 0)
   (text "少なくとも、この辺りに逃走した囚人がいるとは思えない。何処に行くあてがある訳でもないし、これからどうしたものか‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))