(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b03_01.gpc")
  (image-mem 0 3)
  (if (</> (// (? (= 927 #t)) (image-file "gpc¥b03_01a.gpc") (image-mem 1 0))))
  (proc 3)
  (if (</>
       (//
        (? (= P 5))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (load-mem "clm¥b03_01a.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 927 #t))
        (text "「Karl」" 'br)
        (text "また君か‥‥‥どうだね、何か進展があったかね？")
        (wait)
        (text-reset 14))
       (//
        (? (= 927 #f))
        (text "陸軍の市ヶ谷基地にやって来た。わたしを案内した若い兵士は、相変わらず胡散臭げな顔だ。陸軍と情報部の軋轢は未だ健在らしい。")
        (wait)
        (text-reset 14)
        (text "「Karl」" 'br)
        (text "少佐、何かあったのかね？　もう二度と会う事は無いという話だったと記憶しているが。")
        (wait)
        (text-reset 14)
        (image-file "gpc¥b03_01a.gpc")
        (image-mem 1 0)
        (text "「Kiyomi」" 'br)
        (text "申し訳ないとは思ってる。けど、ちょっと聞きたい事があってね。")
        (wait)
        (text-reset 14)
        (text "「Karl」" 'br)
        (text "‥‥‥‥‥‥‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "そんなに邪険にしなくてもいいだろ？　別に、あんたを捕まえに来た訳じゃない。")
        (wait)
        (text-reset 14)
        (text "「Karl」" 'br)
        (text "当然だな、私が捕まらなければならない理由はない。")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "本当にそう思ってるなら、そんなに脅えなくてもいいさ。")
        (wait)
        (text-reset 14)
        (text "「Karl」" 'br)
        (text "‥‥‥‥‥‥‥‥‥")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 927 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 54 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 (</> (/ (text "　　　情報部前　　　"))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MB_A02.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1))
   (proc 0)
   (if (</>
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #f) (= 60 #f))
         (nop@)
         (branch-reg
          336
          (</>
           (/
            (text "「Kiyomi」" 'br)
            (text "エイプリルを捕まえたよ‥‥‥秋葉原に潜んでた。いや、潜んでなんていない、堂々と店を経営してたよ。")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "すると、秋葉原の友人というのは嘘で、ずっと前から計画して造った隠れ蓑だった訳だな。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "それもあんたの教育かい？　どっちかって言うと、情報部のやりそうな事だけどね。スリーパーの常套手段。")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "そうだな‥‥‥彼女を拷問にかけるのかね？")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "そう。何か問題がある？")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "エイプリルはなかなか口を割らんだろう、彼女は苦痛に対する耐性が、人一倍強かった。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "それじゃ、どうすればいいのさ？")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "何とかして彼女を服従させる事だ。軍人の性でね、何者かに服従する事が習性になってしまっているのさ。")
            (wait)
            (text-reset 14)
            (nop@)
            (set-reg 336 #t))
           (/
            (text "「Karl」" 'br)
            (text "何とかして彼女を服従させる事だ。軍人の性でね、何者かに服従する事が習性になってしまっているのさ。")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #f) (= 60 #f))
         (nop@)
         (text "「Kiyomi」" 'br)
         (text "エイプリルを尋問したけど、何も喋らなかったよ。早いとこもうひとりのレイファを捕まえないとね‥‥‥")
         (wait)
         (text-reset 14)
         (text "「Karl」" 'br)
         (text "しっかりしてくれ、もしも君の捜査がうまくいかなければ、私が真犯人にされる可能性だってあるんだ。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #t) (= 60 #f))
         (nop@)
         (branch-reg
          335
          (</>
           (/
            (text "「Kiyomi」" 'br)
            (text "エイプリルを捕まえて尋問したよ。もうひとりのナナってやつの居所を喋ったよ。")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "さすがだな。君の拷問なら、必ず口を割ると思ったが‥‥‥")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "レイファも捕まえたから、これから尋問してみるつもり。空振りに終わらなきゃいいけど。")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "随分弱気になっているじゃないか。見掛けほど厚顔な人間でないのは知っているが、そんなタイプじゃないだろう。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "余計なお世話よ‥‥‥何かアドバイスはないかしら。このままじゃ失敗しそうだわ。")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "レイファは自尊心が強かったな。誇り高いと言うか、屈辱的な行為を受けるのを何よりも嫌っていた。")
            (wait)
            (text-reset 14))
           (/
            (text "「Karl」" 'br)
            (text "レイファは自尊心が強かったな。誇り高いと言うか、屈辱的な行為を受けるのを何よりも嫌っていた。")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (text "「Kiyomi」" 'br)
         (text "エイプリルとレイファを捕まえたよ、尋問はまだだけどね。")
         (wait)
         (text-reset 14)
         (text "「Karl」" 'br)
         (text "そうか‥‥‥君の健闘に期待する。事件が解決をみなければ真っ先に生贄にされるのは私だからな。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (branch-reg
          334
          (</>
           (/
            (text "「Kiyomi」" 'br)
            (text "レイファを捕まえたよ、やはりチャイナタウンだった。")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "そうだろうな。レイファが隠れるとなればそこしかない。しかし、よく彼女を捕まえる事が出来たものだ。")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "レイファは功夫の達人。いかに君が優秀だとはいえ、彼女に勝てるとは思えないがね。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "運が良かったのさ。それに、レイファは慢心しすぎてた。わたしの事をなめてたんだよ。")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "そう‥‥‥そういう傾向があったな、何度も注意したはずなのに。いや、誤解しないでくれ。昔の話だよ。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "わかってるさ‥‥‥これから彼女を尋問するんだけど、アドバイスはないかしら？")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "レイファは自尊心が強かったな。誇り高いと言うか、屈辱的な行為を受けるのを何よりも嫌っていた。")
            (wait)
            (text-reset 14)
            (nop@)
            (set-reg 334 #t))
           (/
            (text "「Karl」" 'br)
            (text "レイファは自尊心が強かったな。誇り高いと言うか、屈辱的な行為を受けるのを何よりも嫌っていた。")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (text "「Kiyomi」" 'br)
         (text "レイファを尋問したよ。何も喋らなかったけどね‥‥‥")
         (wait)
         (text-reset 14)
         (text "「Karl」" 'br)
         (text "ほう、情報部のキヨミの拷問に耐えるとはやるものだ‥‥‥何も知らなかったのではないかね、レイファは道具だったのだろう。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (branch-reg
          337
          (</>
           (/
            (text "「Kiyomi」" 'br)
            (text "レイファを尋問したよ。何も喋らなかったけどね‥‥‥")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "ほう、情報部のキヨミの拷問に耐えるとはやるものだ‥‥‥何も知らなかったのではないかね、レイファは道具だったのだろう。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "だろうね。わたしの拷問に耐えられたとは思えない。エイプリルが何か喋ってくれるといいけど。")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "エイプリルはなかなか口を割らんだろう、彼女は苦痛に対する耐性が、人一倍強かった。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "それじゃ、どうすればいいのさ？")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "何とかして彼女を服従させる事だ。軍人の性でね、何者かに服従する事が習性になってしまっているのさ。")
            (wait)
            (text-reset 14))
           (/
            (text "「Karl」" 'br)
            (text "何とかして彼女を服従させる事だ。軍人の性でね、何者かに服従する事が習性になってしまっているのさ。")
            (wait)
            (text-reset 14)))))
        (//
         (branch-reg
          333
          (</>
           (/
            (text "「Karl」" 'br)
            (text "彼女達を見つけたかね？　私の助言が役に立ったか気になっていたのだが。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "また見つけてはいない。時間の問題だと思うけどね。")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "ほう、大した自信だ。何を根拠にそう言い切れるのだ。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "自分で助言しといて、それはないんじゃない？　囚人の体には特殊なマーキングがつけてあったんだよ。")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "マーキング？　つまり、何処に隠れてもわかるように、あらかじめしるしを書いておいたという訳かね。")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "まあそんなとこ。そんな簡単な話じゃないけどね。特殊なフィルタを通すと見えるペイントね‥‥‥")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "そんな便利な物があるのなら、もっと早く彼女らを捕まえる事が出来ただろうに。君は、私が思っているより無能なのか？")
            (wait)
            (text-reset 14)
            (text "「Kiyomi」" 'br)
            (text "‥‥‥‥‥‥こっちにも色々と事情があってね。わたしがその話を聞いたのは、つい最近の事なんだよ。")
            (wait)
            (text-reset 14)
            (text "「Karl」" 'br)
            (text "君の苦労は察するよ。その種の問題は何処にでもあるものだ。")
            (wait)
            (text-reset 14)
            (nop@)
            (set-reg 333 #t))
           (/
            (text "「Karl」" 'br)
            (text "君の苦労は察するよ。どこにでも問題はあるものだ。")
            (wait)
            (text-reset 14)))))))
   (proc 1))
 (seg (? (= S 2) (= 329 #f))
   (proc 0)
   (text "軍服を着て産まれてきたと言われても信じられるほど、逞しい体に服が似合っている。")
   (wait)
   (text-reset 14)
   (text "わたしよりも２０は年上だろうか、おそらくこの国に来る前も軍人だったのだろう。")
   (wait)
   (text-reset 14)
   (text "もしかすると、開戦当時引き抜かれてやって来たくちかも。いや、もしそうならもっと優遇されていてもよさそうなものだ‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 329 #t)
   (proc 1))
 (seg (? (= S 2) (= 330 #f))
   (proc 0)
   (text "いかにも歴戦の古強者と言わんばかりの、逞しい体躯をしている。身に着けた服も、着古されて体にしっくり馴染んでいるようだ。")
   (wait)
   (text-reset 14)
   (text "金ぴかの徽章磨きに余念のない、その実戦地に赴いた事など一度もない日本人の将校とは大違いだ。")
   (wait)
   (text-reset 14)
   (text "だからこそ、軍や日本人に恨みを持っているとも考えられるが。この男がふたりの部下を指揮して‥‥‥そう思えなくもない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 330 #t)
   (proc 1))
 (seg (? (= S 2) (= 330 #t))
   (proc 0)
   (text "軍服を着て産まれてきたと言われても信じられるほど、逞しい体に服が似合っている。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3))
   (proc 0)
   (if (</>
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #f) (= 60 #f))
         (nop@)
         (text "まずはエイプリルを尋問してみよう。この事件全体を解く鍵がみつかるかもしれない。")
         (wait)
         (text-reset 14)
         (text "それが無理でも、レイファを逮捕するためのヒントか、第３の囚人を発見する手がかりを得られればいい。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #f) (= 60 #f))
         (nop@)
         (text "エイプリルがわたしの拷問に耐えられたとは思いたくない。彼女は本当に何も知らなかったのか‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #t) (= 60 #f))
         (nop@)
         (text "ふたり目の囚人、レイファを逮捕した。彼女を尋問すれば、何か情報が得られるかもしれない。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (text "ふたりの囚人は逮捕した。彼女達を尋問すれば、機密に関する情報を得られるだろう。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (text "レイファを逮捕した。彼女を尋問すれば、事件全体を解く鍵がみつかるかもしれない。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (text "レイファがわたしの拷問に耐えられたとは思いたくない。彼女は本当に何も知らなかったのか‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (text "レイファは何も喋らなかった。エイプリルを何とかしなければならない。どんな事でもいい、何とかしないと‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (text "まずはエイプリルかレイファを逮捕しなければならない。どちらも元特殊部隊だ。本当ならわたしのかなう相手ではない‥‥‥")
         (wait)
         (text-reset 14)
         (text "わずかに有利な点は、例の囚人に刻まれたマークとゴーグルの性能だけ。相手に気付かれる前に倒さなければならないだろう。")
         (wait)
         (text-reset 14))))
   (proc 1))
 (seg*))