(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (branch-reg 56 (</> (/) (/ (mes-jump "mes¥mb_b02.mes"))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b03_01.gpc")
  (image-mem 0 3)
  (if (</> (// (? (= 926 #t)) (image-file "gpc¥b03_01a.gpc") (image-mem 1 0))))
  (proc 3)
  (if (</>
       (//
        (? (= P 5))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (load-mem "clm¥b03_01a.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 926 #t))
        (text "「Karl」" 'br)
        (text "何か用かね？")
        (wait)
        (text-reset 14))
       (//
        (? (= 926 #f))
        (text "市ヶ谷ベースにやって来たわたしは、わたしを胡散臭い者と判断し猜疑的な視線を送る兵士に案内されて基地内の一室に通された。")
        (wait)
        (text-reset 14)
        (text "部屋は基地の中でもあまり上等とは言えない、クレゾールの臭いがする湿った陰気な場所にある。")
        (wait)
        (text-reset 14)
        (text "部屋の主である将校があまり優遇されていない事が、部屋に案内された瞬間にわかるような所だ。")
        (wait)
        (text-reset 14)
        (text "飾られた隊旗は外人部隊の物で、わたしのような人間にでもその存在を知られる有名なマーク。")
        (wait)
        (text-reset 14)
        (image-file "gpc¥b03_01a.gpc")
        (image-mem 1 0)
        (text "「軍服の男」" 'br)
        (text "お待たせした。")
        (wait)
        (text-reset 14)
        (text "その男は、いかにも歴戦の古強者と言わんばかりの逞しい体躯と、よく響く低い声の持ち主だった。")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "あなたが‥‥‥エイプリルとレイファの元上官？")
        (wait)
        (text-reset 14)
        (text "「軍服の男」" 'br)
        (text "カール大佐である。君の事は聞いている、ふたりの元部下について何かたずねたい事があるとか？")
        (wait)
        (text-reset 14)
        (text "カールか‥‥‥月並みな名前だわ。ヨーロッパ系に見えない事もないが、この手の軍人は大抵国籍不明って事になってる。")
        (wait)
        (text-reset 14)
        (text "「Karl」" 'br)
        (text "話を聞こうじゃないか、あまり君の助けになれるとも思えないが。")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "あなたの部下だった、ふたりの部下の話をして。")
        (wait)
        (text-reset 14)
        (text "「Karl」" 'br)
        (text "その前に言っておくが、私が軍の人間ではない君に情報を提供している事を考慮してもらいたい。")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 926 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 54 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 (</> (/ (text "　　　情報部前　　　"))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (if (</>
                    (//
                     (? (= 55 #t))
                     (nop@)
                     (text "「Kiyomi」" 'br)
                     (text "多分、もうお邪魔する事もないでしょうね‥‥‥")
                     (wait)
                     (text-reset 14)
                     (text "「Karl」" 'br)
                     (text "そう願いたいものだ、それでは失礼する。")
                     (wait)
                     (text-reset 14)
                     (mes-jump "mes¥MB_A02.MES"))
                    (//
                     (? (= 240 #t))
                     (nop@)
                     (text "「Karl」" 'br)
                     (text "あのふたりには用心する事だ。この任務は、君が思ってるよりずっと困難な仕事だぞ。")
                     (wait)
                     (text-reset 14)
                     (mes-jump "mes¥MB_A01.MES"))
                    (//
                     (nop@)
                     (set-reg 240 #t)
                     (text "「Karl」" 'br)
                     (text "もう行くのかね？")
                     (wait)
                     (text-reset 14)
                     (text "「Kiyomi」" 'br)
                     (text "ええ。これ以上あなたが何か知ってるとも思えないし。")
                     (wait)
                     (text-reset 14)
                     (text "「Karl」" 'br)
                     (text
                      "そうか。幸運を祈る‥‥‥とは言えないがね。何しろあのふたりのおかげで私の経歴に傷がつく事になるかもしれんのだから。")
                     (wait)
                     (text-reset 14)
                     (text "「Kiyomi」" 'br)
                     (text "そうね‥‥‥")
                     (wait)
                     (text-reset 14)
                     (text "「Karl」" 'br)
                     (text "せいぜい頑張ってみるといい。忠告しておくが、あのふたりは私の部下の中でもかなり優秀な方だったよ。")
                     (wait)
                     (text-reset 14)
                     (text "「Kiyomi」" 'br)
                     (text "‥‥‥‥‥‥‥‥‥ご協力に感謝します。")
                     (wait)
                     (text-reset 14)
                     (mes-jump "mes¥MB_A01.MES")))))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 54 #t))
   (proc 0)
   (text "「Karl」" 'br)
   (text "情報部では、私の事も疑っているのだろうな。あのふたりを使って私が何か企んでいたのではないかと‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 234 #t))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "他に、彼女達について知っている事は？")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "特にない‥‥‥と思う。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "自信なさそうじゃない、何か隠してんの？")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "私に何かを隠さねばならない理由はない。わかっていると思うが。君には感謝しているよ、私の立場を尊重してくれている。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "なんだか釘をさされたみたいだね。")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "情報部のキヨミという名前は、軍人の間でも知れている。拷問をさせたら、吐かなかった奴はいないと。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そう思うなら‥‥‥わたしをプロと見なしてるんなら、ふたりが隠れてそうな場所を教えてよ。")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "‥‥エイプリルは秋葉原に友人が居るらしい。ブラックマーケットのある所だ。知っているか？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "知ってるわ。その友人の所に居るってのね？　レイファは？")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "彼女は特にあてがあるようではなかったが‥‥‥彼女が中国系の人間である事を考えれば、大体見当はつく。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "チャイナタウンね。わたしもそれは考えたけど、そんなすぐに思いつきそうな所に隠れるかしら？")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "それは彼ら民族の事をよく理解していない。彼らにとっては、同国人と一緒にいるのが一番安全なのだ。")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "誰も仲間を売ろうとはしないからな。自分と同じように、誰かに追われている人間や犯罪者も多いし。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "なるほどね‥‥‥秋葉原もブラックマーケットの辺りなら犯罪者なんかも多い。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ところで、ふたりのホロはないかしら。出来れば詳しいプロファイルも見たいんだけど‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "何もない。データは根こそぎ消えている。情報部だって同じなのだろう？　だから君がここに居る。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "なんてこった‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "ついでに言えば、ふたりのデータが無い以上、軍に彼女達が在籍したという証拠もない。私が覚えているというだけでね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それを情報部が認めるとでも？　ふたりが存在していた事は間違いないのに。")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "わかっている‥‥‥言ってみただけだ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥そんなに脅える事ないでしょう。誰もあなたを疑っているとは言ってないわ。")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "それこそわかっていない。もしも事件が解決をみる事がなかったとしたら、最初に生贄にされるのは他ならぬ私だ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 54 #t)
   (proc 1))
 (seg (? (= S 1) (= 233 #t) (= 236 #t))
   (proc 0)
   (text "「Karl」" 'br)
   (text "あのふたりは本物のプロだった、それは誰でも知ってる事だ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "どんな作戦に参加してたの？")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "アジアのいくつかの戦場と、中東に１年以上。特殊部隊の兵士としてこれ以上の経歴はなかろう。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "でも、彼女達は軍に留まらなかった。何かあてがあったんじゃないかしら。外の世界で生きて行くあてが。")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "‥‥‥そうかもしれん。しかし、彼女らに軍属以上によい職があるとは思えない。特に移民ではな。")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "そもそも特殊部隊の人間は、徴兵義務の為に嫌々軍人になった連中とは違う。彼女らに除隊を告げられた時はショックだったよ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ふたりには家族は？")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "エイプリルにはいない。確か、爆弾テロか何かで家族を失っているはずだ。レイファの家族は健在だと思う。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ふたりは仲がよかったの？")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "よかったとも言えるし、そうでないとも言える。同じ部隊に居たのだから、付き合いはあったろう。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "除隊した時期がほとんど同じというのも、気になるわね。それで全く無関係だなんて、信じられる訳ない。")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ふたりが一緒にいる可能性だって‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 234 #t)
   (proc 1))
 (seg (? (= S 1) (= 233 #f))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "わたしにどうしろと？")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "君がどうして彼女達を追っているのか、あのふたりが何をしたのかを教えてほしい。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "どうしてわたしがそうしなきゃならないの。情報部の上から圧力をかける事も出来るってのに。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたが、どうしても喋らなきゃならないようにも出来るわ。")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "だが、そうするつもりは無いのだろう？　君は私に対して一応の敬意を払っているように見える。")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "外見から感じられるほど、ごり押しタイプの人間ではない。情報部にはそういう族が多いんだがね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そうね‥‥‥でも、わたしだってそれほど詳しく知っている訳じゃないのよ。")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "あのふたりは何をした？　逃亡する前‥‥‥そもそも何の罪を犯したのかさえよくは聞かされていない。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "軍とある企業が、共同で開発していた機構＝システムを奪ったって事しか知らない。")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "奪った？　何をだね、機構＝システム自体を？　それとも、その機構の仕様か、その物のコピーなのかね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "さあ、そこまでは‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Karl」" 'br)
   (text "君は、その話に何の矛盾も感じないのか。私には全く筋の通っていない話に思えるが？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 233 #t)
   (proc 1))
 (seg (? (= S 1) (= 233 #t))
   (proc 0)
   (text "「Karl」" 'br)
   (text "君はこの任務に何の矛盾も感じないのか。私には全く筋の通っていない話に思えるが？")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 235 #f))
   (proc 0)
   (text "いかにも歴戦の古強者と言わんばかりの、逞しい体躯をしている。身に着けた服も、着古されて体にしっくり馴染んでいるようだ。")
   (wait)
   (text-reset 14)
   (text "金ぴかの徽章磨きに余念のない、その実戦地に赴いた事など一度もない日本人の将校とは大違いだ。")
   (wait)
   (text-reset 14)
   (text "だからこそ、軍や日本人に恨みを持っているとも考えられるが。この男がふたりの部下を指揮して‥‥‥そう思えなくもない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 235 #t)
   (proc 1))
 (seg (? (= S 2) (= 236 #f))
   (proc 0)
   (text "わたしよりも２０は年上だろうか、おそらくこの国に来る前も軍人だったのだろう。")
   (wait)
   (text-reset 14)
   (text "もしかすると、開戦当時引き抜かれてやって来たくちかも。いや、もしそうならもっと優遇されていてもよさそうなものだ‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 236 #t)
   (proc 1))
 (seg (? (= S 2) (= 236 #t))
   (proc 0)
   (text "いかにも歴戦の古強者と言わんばかりの、逞しい体躯をしている。身に着けた服も、着古されて体にしっくり馴染んでいるようだ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 54 #t))
   (proc 0)
   (text "秋葉原ブラックマーケットに、チャイナタウンか。わたしの想像したとおりだな。")
   (wait)
   (text-reset 14)
   (text "しかし、依然ふたりの詳しい経歴も顔もわからない。ナナって奴はよほど優秀なハッカーらしいな。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 234 #t))
   (proc 0)
   (text "大佐はふたりの話をしたがらないと思ったけど、意外に友好的だ。自分には後ろ暗い事などないというハッタリだろうか？")
   (wait)
   (text-reset 14)
   (text "しかし、わたしを納得させたところで大した意味はない。そもそも情報が洩れたのは軍部だ、厳しく追求されているだろう。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 233 #t))
   (proc 0)
   (text "確かに大佐の言うように、今回の任務は何処か裏がありそうな気がしてならない。しかし、裏があったからどうだと言うんだ？")
   (wait)
   (text-reset 14)
   (text "わたしは、自分が今どんな状況に置かれてるのかもわかってない。任務を放棄して、シベリアに送られるのもゴメンだ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 239 #f))
   (proc 0)
   (text "軍人が相手じゃ、一筋縄ではいかないと思ってたけど‥‥‥")
   (wait)
   (text-reset 14)
   (text "自分の元部下が何かをやらかして、しかも情報部の人間が軍の基地まで押し掛けて来たとなれば、保身にはしってもやむを得ないか？")
   (wait)
   (text-reset 14)
   (text "どうせわたしの知ってる内容なんて、大した事ないんだ。洩らしたとしても別に影響はないか‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 239 #t)
   (proc 1))
 (seg (? (= S 3) (= 239 #t))
   (proc 0)
   (text "どうせわたしの知ってる内容なんて、大した事ないんだ。洩らしたとしても別に影響はないか‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))