(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (branch-reg
   930
   (</>
    (/
     (image-file "gpc¥b05_02.gpc")
     (image-mem 0 3)
     (branch-reg
      355
      (</> (/ (nop@)) (/ (image-file "gpc¥b05_02a.gpc") (image-mem 1 0)))))
    (/ (image-file "gpc¥b05_02b.gpc") (image-mem 0 3))))
  (proc 3)
  (if (</>
       (//
        (? (= P 6))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_06.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 6))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_06v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 6)))))
       (// (nop@))))
  (load-mem "clm¥b05_02b.clm" 32768)
  (text-frame 10 312 70 383)
  (text "浮浪者の男が言った、レイファの潜んでいるビルの一室に入った。ビルの中でも、崩壊の度合が少なく、快適そうな部屋だ。")
  (wait)
  (text-reset 14)
  (text "室内に人の気配は無いが、レイファが元特殊部隊だという事を思えば、それも納得出来る。わたしに気配を悟られる事は有り得ない。")
  (wait)
  (text-reset 14)
  (text "あとは自慢の強運と、レイファの体に刻まれた卍のマークだけが頼り。彼女が近くに居れば壁越しでもそれと判る仕掛けになってる。")
  (wait)
  (text-reset 14)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 354 #t) (= 930 #f))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 16 48")
   (exec-mem 4768 4 8 16 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " ゴーグル装着 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= 355 #f))
               (text "ゴーグルを装着した。")
               (wait)
               (text-reset 14)
               (image-file "gpc¥b05_02b.gpc")
               (image-mem 0 3)
               (image-file "gpc¥shotwaku.gpc")
               (image-mem 1 0)
               (proc 3)
               (text "視界が緑一色だ。これがフィルタを通して見た視界‥‥‥あれは？あれがレイファなのか？")
               (wait)
               (text-reset 14)
               (text "「Lei-Fa」" 'br)
               (text "お前、何者か。あたしの事を見てるな！")
               (wait)
               (text-reset 14)
               (text "わたしの視線を感じたのだろうか、レイファがこちらを見ている。特殊部隊の特殊感覚か、功夫の技なのか？")
               (wait)
               (text-reset 14)
               (text "「Kiyomi」" 'br)
               (text "動くな！　わたしの銃はお前を照準してるぞ。")
               (wait)
               (text-reset 14)
               (text "「Lei-Fa」" 'br)
               (text "‥‥‥軍人じゃない、匂いが違うね。なのに、どうしてあたしを捕まえに来るか？")
               (wait)
               (text-reset 14)
               (text "「Kiyomi」" 'br)
               (text "動くなって言ってるでしょう？　言うとおりにした方が身の為だとは思わないか。")
               (wait)
               (text-reset 14)
               (text "「Lei-Fa」" 'br)
               (text "お前、日本人ね。こんな所まであたしを探しに来るなんて、バカにも程があると思うよ！")
               (wait)
               (text-reset 14)
               (nop@)
               (set-reg 355 #t)
               (nop@)
               (set-reg 930 #t))
              (//
               (? (= 355 #t))
               (text "ゴーグルを装着した。視界が緑に変わる‥‥‥")
               (wait)
               (text-reset 14)
               (image-file "gpc¥b05_02b.gpc")
               (image-mem 0 3)
               (image-file "gpc¥shotwaku.gpc")
               (image-mem 1 0)
               (proc 3)
               (nop@)
               (set-reg 930 #t)))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 930 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 16 48")
   (exec-mem 4768 4 8 16 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " ゴーグル解除 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "P 1 4 64")
         (text "ゴーグルを外した。")
         (wait)
         (text-reset 14)
         (nop@)
         (set-reg 930 #f)
         (image-file "gpc¥b05_02.gpc")
         (image-mem 0 3)
         (image-file "gpc¥b05_02a.gpc")
         (image-mem 1 0)
         (proc 3))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 346 #f))
   (proc 0)
   (text "想像すると、おそらくこのコードの先に何らかの電気製品が付いていたんじゃないだろうか。")
   (wait)
   (text-reset 14)
   (text "照明器具か、防犯装置の類か、さもなくば通信機器か。いずれにしても、略奪者の眼鏡に適う価値があった事は間違いない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 346 #t)
   (proc 1))
 (seg (? (= S 1) (= 347 #f))
   (proc 0)
   (text "屋根の一部が何処かへいってしまって、本来屋根裏にあるコードが露出している。")
   (wait)
   (text-reset 14)
   (text "色とりどりのコードは、どんな用途に使われていたのかわたしにはわからないが、通電していない事は疑う余地もない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 347 #t)
   (proc 1))
 (seg (? (= S 1) (= 347 #t))
   (proc 0)
   (text "照明器具か、防犯装置の類か、さもなくば通信機器か。いずれにしても、略奪者の眼鏡に適う価値があった事は間違いない。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 348 #f))
   (proc 0)
   (text "洋式のバスタブの中には数年分の雨水が溜まり、表面には苔ともカビともつかない緑色の物体が浮かんでいる。")
   (wait)
   (text-reset 14)
   (text "こうなっては、二度と使う事は出来ないだろう。レイファは潜んでいる間、バスを使う事はなかったんだろうか？")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 348 #t)
   (proc 1))
 (seg (? (= S 2) (= 349 #f))
   (proc 0)
   (text "その昔は扉で仕切られていたと思われる奥の部屋は、バスルームのようだ。ボロボロになったカーテンの残骸が見える。")
   (wait)
   (text-reset 14)
   (text "その予想外の古風な造りには驚かされる。洋式のバスタブに、木を貼った床は、その頃の感覚からしても当世風ではなかったろう。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 349 #t)
   (proc 1))
 (seg (? (= S 2) (= 349 #t))
   (proc 0)
   (text "その昔は扉で仕切られていたと思われる奥の部屋は、バスルームのようだ。ボロボロになったカーテンの残骸が見える。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 350 #f))
   (proc 0)
   (text "昔は壁か屋根の一部か、さもなくば家具だったと思われる残骸が、所々に転がっている。")
   (wait)
   (text-reset 14)
   (text "これもまた略奪者のした事なのか、それとも、後にここを快適な部屋にしようとした何者かの仕業なのか‥‥‥判断は出来ない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 350 #t)
   (proc 1))
 (seg (? (= S 3) (= 351 #f))
   (proc 0)
   (text "半ば土に返りかけたカーペットと、その上に積もった埃が床全体をおおっている。")
   (wait)
   (text-reset 14)
   (text "靴痕のような物は見当たらないが、レイファであれば足跡を残さずに歩き回る事も可能だろう。プロとはそういうものだ‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 351 #t)
   (proc 1))
 (seg (? (= S 3) (= 351 #t))
   (proc 0)
   (text "床には靴痕のような物は見当たらないが、レイファであれば足跡を残さずに歩き回る事も可能だろう。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 352 #f))
   (proc 0)
   (text "壁に走った深い亀裂が、わたしの不安感を煽る。いったいいつまで天井の重みに耐えてくれるのだろうか‥‥‥")
   (wait)
   (text-reset 14)
   (text "しかしそれを言うなら、わたし達地下の住人はいつもその恐怖に脅えているのだ。地殻が崩れれば、死ぬのはみんな同じ事だ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 352 #t)
   (proc 1))
 (seg (? (= S 4) (= 353 #f))
   (proc 0)
   (text "陽光に当たるという事はないので、さして変色はしていないものの無数のひび割れが壁一面に走っていて、新品同様とは言えない。")
   (wait)
   (text-reset 14)
   (text "はがれ落ちた漆喰のような物の下から、本当の壁が覗いているのも部屋をいっそうみすぼらしく見せている。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 353 #t)
   (proc 1))
 (seg (? (= S 4) (= 353 #t))
   (proc 0)
   (text "壁に走った深い亀裂が、わたしの不安感を煽る。いったいいつまで天井の重みに耐えてくれるのだろうか‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 356 #t))
   (proc 0)
   (text "レイファはわたしを始末して、再び逃走するつもりだ。戦いはいよいよ避け難い。")
   (wait)
   (text-reset 14)
   (text "しかし、相手は元特殊部隊だ。わたしに勝ち目があるのだろうか？相手の慢心した隙に付け込むしかないか‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 355 #t))
   (proc 0)
   (text "わたしの存在をレイファに知られる前に何とかしたかったが‥‥‥不可能だとは思うが、説得してみるしかない。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 349 #t) (= 353 #t))
   (proc 0)
   (text "肉眼ではレイファがここに居る事を確認するのは不可能か。そろそろ例のゴーグルの出番かもしれない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 354 #t)
   (proc 1))
 (seg (? (= S 5))
   (proc 0)
   (text "部屋の中にレイファの存在を知らせてくれるような物が見つかるだろうか‥‥‥探してみるべきだろうか？")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 6) (= 356 #f) (= 355 #t))
   (proc 0)
   (text "「Lei-Fa」" 'br)
   (text "あんた何者ね？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "なんで黙ってる。さては‥‥‥お前あたしを捕まえに来たな。軍人には見えないけど、何者か！")
   (wait)
   (text-reset 14)
   (text "レイファに悟られる前に何とかしようと思ってたのに‥‥‥まともに戦って勝ち目はあるだろうか？")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "何にも言わないつもりか？　それでもいいぞ、どっちみちお前ここで死ぬね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしに手を出すのは賢明じゃないよ。わたしは情報部のもんさ、殺せば部員が大挙してあんたを捕まえに来る。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "お前を殺さなければ、今ここで捕まるだけね。あたしに脅しが通用すると思ってるか？")
   (wait)
   (text-reset 14)
   (text "どうする事も出来ない‥‥‥戦うしかないのか？")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 356 #t)
   (proc 1))
 (seg (? (= S 6) (= 356 #t) (= 355 #t))
   (proc 0)
   (text "レイファはもはや何を言っても聞きはしないだろう‥‥‥力ずくで言うことを聞かせるしかないようだ。")
   (wait)
   (text-reset 14)
   (text "だが、わたしに何とか出来るだろうか？　自信は全くない。いかにわたしが強運だとしても‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんた、どうして軍の機密なんかに手を出したんだ？　そんな事をすればどうなるか、わからなかった訳じゃないだろう。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "そんな事、お前に教えるとおもうか？　拷問されても吐かなかったのに？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "チッ‥‥‥それじゃ、どうしようもないね。出来れば穏便にと思ったんだけどね。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "どこからでもかかって来るね。あたしが負ける訳ないよ！")
   (wait)
   (text-reset 14)
   (proc 1)
   (exec-mem 3072 0)
   (branch-reg
    930
    (</>
     (/ (nop@))
     (/
      (exec-mem 9504 "I")
      (exec-mem 9504 "M M128")
      (exec-mem 9504 "L gpc¥b05_02b0.gpc,KEEP")
      (exec-mem 9504 "L gpc¥b05_02b1.gpc,KEEP")
      (exec-mem 9504 "L gpc¥b05_02b2.gpc,KEEP")
      (exec-mem 9504 "L gpc¥b05_02b3.gpc,KEEP")
      (exec-mem 9504 "L gpc¥b05_02b4.gpc,KEEP")
      (exec-mem 9504 "L gpc¥b05_02b5.gpc,KEEP")
      (exec-mem 9504 "L gpc¥b05_02b6.gpc,KEEP")
      (exec-mem 9504 "L gpc¥b05_02b7.gpc,KEEP")
      (exec-mem 9504 "C gpc¥b05_02b0.gpc,GPC")
      (image-mem 1 0)
      (delay 3)
      (exec-mem 9504 "C gpc¥b05_02b1.gpc,GPC")
      (image-mem 1 0)
      (delay 3)
      (exec-mem 9504 "C gpc¥b05_02b2.gpc,GPC")
      (image-mem 1 0)
      (delay 3)
      (exec-mem 9504 "C gpc¥b05_02b3.gpc,GPC")
      (image-mem 1 0)
      (delay 3)
      (exec-mem 9504 "C gpc¥b05_02b4.gpc,GPC")
      (image-mem 1 0)
      (delay 3)
      (exec-mem 9504 "C gpc¥b05_02b5.gpc,GPC")
      (image-mem 1 0)
      (delay 3)
      (exec-mem 9504 "C gpc¥b05_02b6.gpc,GPC")
      (image-mem 1 0)
      (delay 3)
      (exec-mem 9504 "C gpc¥b05_02b7.gpc,GPC")
      (image-mem 1 0)
      (delay 3))))
   (exec-mem 9504 "E")
   (exec-mem 3072 0)
   (mes-jump "mes¥MC_B01.MES")
   (set-var S 6)
   (set-reg 356 #t)
   (set-reg 930 #f)
   (proc 0)
   (text "レイファはわたしを始末して、再び逃走するつもりだ。戦いはいよいよ避け難い。")
   (wait)
   (text-reset 14)
   (text "しかし、相手は元特殊部隊だ。わたしに勝ち目があるのだろうか？相手の慢心した隙に付け込むしかないか‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 6) (= 355 #t) (= 930 #f))
   (proc 0)
   (text "わたしの存在をレイファに知られる前に何とかしたかったが‥‥‥不可能だとは思うが、説得してみるしかない。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 6) (= 349 #t) (= 353 #t) (= 930 #f))
   (proc 0)
   (text "肉眼ではレイファがここに居る事を確認するのは不可能か。そろそろ例のゴーグルの出番かもしれない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 354 #t)
   (proc 1))
 (seg (? (= S 6) (= 930 #f))
   (proc 0)
   (text "部屋の中にレイファの存在を知らせてくれるような物が見つかるだろうか‥‥‥探してみるべきだろうか？")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))