(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b05_01.gpc")
  (image-mem 0 3)
  (proc 3)
  (if (</>
       (//
        (? (= P 3))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_03.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_03v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3)))))
       (// (nop@))))
  (load-mem "clm¥b05_01.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 907 #t))
        (text "チャイナタウンの一画にやって来た。レイファを逮捕する事が出来た今となっては、何の用も無いはずだが‥‥‥")
        (wait)
        (text-reset 14))
       (//
        (? (= 907 #f))
        (text "チャイナタウンだ。辺りは廃屋のようなビルが林立し、昼なお暗い犯罪者の巣窟といった雰囲気。")
        (wait)
        (text-reset 14)
        (text "前回来た時には、レイファがこの辺りに潜んでいるという根拠も信憑性がなかったし、あまりやる気がなかったけど‥‥‥")
        (wait)
        (text-reset 14)
        (text "今度は、そう気楽ではいられない。このビルの何処かにレイファが潜んでいる事は、ほぼ間違いないように思える。")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 907 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 59 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 6 96 (</> (/ (text "　　　情報部前　　　"))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MB_A02.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 59 #f) (= 339 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 6 96 (</> (/ (text "　　ビル内に入る　　"))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MB_C02A.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 59 #t))
   (proc 0)
   (text "レイファが潜んでいた廃屋同然のビルだ。逃亡中とはいえ、いつ崩れるかもしれないのに、よく我慢できたものだ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 339 #t))
   (proc 0)
   (text "今にも崩れ落ちそうなビルは、追われて身を隠そうとする犯罪者が身を潜めるのにうってつけのように思える‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 338 #f))
   (proc 0)
   (text "今にも崩れ落ちそうなビルだ。周囲の建物より低い事から、かつては高級住宅だった事がわかる。")
   (wait)
   (text-reset 14)
   (text "崩れ落ちそうではあるが、入り口は辛うじて人が通れるだけの隙間があり、いかにも何者かが潜んでいそうな雰囲気だけど‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 338 #t)
   (proc 1))
 (seg (? (= S 1) (= 338 #t) (= 345 #f))
   (proc 0)
   (text "あたりの建物より幾分低く、外観からは高級な住宅を思わせる。入り口には、かろうじて人がひとり通れる空間があるようだ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 338 #t) (= 345 #t))
   (proc 0)
   (text "今にも崩れ落ちそうなビルは、追われて身を隠そうとする犯罪者が身を潜めるのにうってつけのように思える‥‥‥")
   (wait)
   (text-reset 14)
   (text "浮浪者の話を聞かなかったとしても、レイファが隠れているとすればまさにこんなビルの中だと思っただろう。")
   (wait)
   (text-reset 14)
   (text
    "任務とはいえ、この中に入るのは勇気が必要だ。これ程切羽詰まっていなければ、わたしのキャリアが賭かっていなければ、敢えてこの中に足を踏み入れようとは思わない。")
   (wait)
   (text-reset 14)
   (text "しかし、今のわたしには選択の余地はないようだ。実はレイファと浮浪者の男が結託して、罠を張っているのでなければいいが。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 339 #t)
   (proc 1))
 (seg (? (= S 2) (= 340 #f))
   (proc 0)
   (text "瓦礫と崩れかかった建物ばかりの街に、ひときわ高いビル群が威圧的におおい被さるように見える。")
   (wait)
   (text-reset 14)
   (text "この辺りの住民は、毎日あれらを見上げながら暮らしている訳だ。なんて屈辱なんだろう。わたしなら３日と耐えられない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 340 #t)
   (proc 1))
 (seg (? (= S 2) (= 341 #f))
   (proc 0)
   (text "彼方には、はるか上空までそびえるビル群がある。地殻を支える柱の役を負った建物達だ。")
   (wait)
   (text-reset 14)
   (text "それよりも手前にあるこの一画の建物は、いつ倒壊してもおかしくないほどボロボロになっている。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 341 #t)
   (proc 1))
 (seg (? (= S 2) (= 341 #t))
   (proc 0)
   (text "瓦礫と崩れかかった建物ばかりの街に、ひときわ高いビル群が威圧的におおい被さるように見える。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 342 #f))
   (proc 0)
   (text "本来なら一杯の車で満ちているはずなのに、ぽっかりと口を開けたビルの窓からは、真っ暗な空間しか見る事が出来ない。")
   (wait)
   (text-reset 14)
   (text "どういう経緯で廃墟になったのかは不明だけど、その後の略奪のせいで、すっかり空っぽにされたんだろう。")
   (wait)
   (text-reset 14)
   (text "こういう光景を目にするのは、何もチャイナタウンだけじゃない。この国が、もう長くないという証拠だろうか？")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 342 #t)
   (proc 1))
 (seg (? (= S 3) (= 343 #f))
   (proc 0)
   (text "巨大な立体駐車場とショッピングモールがくっついた物のようだ。今では見る影もないが、往時の賑わいが容易に想像出来る。")
   (wait)
   (text-reset 14)
   (text "建物には、破壊の痕の他に略奪の痕が見てとれる。もう何年も前の話だろう。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 343 #t)
   (proc 1))
 (seg (? (= S 3) (= 343 #t))
   (proc 0)
   (text "建物には、破壊の痕の他に酷い略奪の痕が見てとれる。もう何年も前の話だろう‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 60 #t))
   (proc 0)
   (text "「Vagrant」" 'br)
   (text "姉さんこの間はありがとうよ。女を抱いたのは５年振りだったよ！しかし、あの女も気の毒な事だなぁ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "お安いご用さ。また何かあったら頼むよ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 59 #t))
   (proc 0)
   (text "「Vagrant」" 'br)
   (text "この前の姉さんじゃねえか。女は見つかったかい？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ああ、おかげさんでね。大丈夫、この前の約束は忘れてないよ。そのうち礼をするから待ってな。")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "楽しみにしてるぜぇ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 344 #f))
   (proc 0)
   (text "こっちの動きを警戒して微動だにしない。わたしの事を恐れてるのか、それとも襲う価値があるか値踏みしているのかもしれない。")
   (wait)
   (text-reset 14)
   (text "どっちにしても、あまり重要には思えない。万が一襲って来たとしても、わたしより強そうには見えないし‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "よう、また会ったね。いつもこの辺りに居るのかい？")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "‥‥‥‥‥‥‥‥‥この前の姉ちゃんか。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしの事を覚えてたみたいだね、ご同輩？")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "誰が仲間なもんか。そっちは暖けぇ部屋ん中でうまい物食ってんのに、俺は凍え死なねえように夜中の間ずっと歩き回ってんだぜ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしもあんたと同じさ。明日のメシの為にゃ、足が棒になるまで歩き回らなきゃならない。嫌な世の中さね。")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "そうは見えねえがなぁ‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そのわたしの苦痛を和らげる為に、ひとつ教えちゃくれないかね。このへんに、女がひとり隠れてるはずなんだよ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "軍に追われて、かなり切羽詰まってるはずなんだ。元特殊部隊だから武器も持ってるだろう。")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥姉さん、あんた何者だね？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ずっとこのへんに居たんなら、わたしが探してる女の事を知っててもよさそうなもんだけど‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "どんな女だ。人種は、顔と身体はどんなだ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "心当たりがあるんだね？")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "追われてるってだけじゃわかんねえな。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "中国人。顔は‥‥‥見た事がないから何とも言えない。軍に居たから、かなり引き締まった筋肉質だと思う。")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "この辺りにゃ、中国人は腐るほど居る。だが、心当たりがない訳でもねぇなぁ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 344 #t)
   (proc 1))
 (seg (? (= S 4) (= 345 #f))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "そいつを見たんだろ、早く教えなよ！")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "そしたら、俺の得になるのか？　姉さんが足を棒にしたところで、俺の腹が空く訳じゃねえ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥‥‥‥‥‥そりゃそうだ、ごもっとも。")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "姉さん、あんた女を見つけたらいくら貰えるんだ？　少し俺に分けてくれるんなら、教えてもいい。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "欲をかくと、いつか痛い目にあうよ。")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "脅しは効かねえよ。どのみちこっちは、いつ死ぬかわからねえって経験を毎日してんだから。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わかった、わかった。わたしは情報部の人間なんだ。あんたが死にそうになった時、情報部のもてなしを受けられるようにする。")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それでどうだい。")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "信用していいんだな？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "いくら零落したって、わたしら同族だろ？　兄妹みたいなもんだ。信用してもらえないなんて悲しすぎるね。")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "いいだろう。そこの低いビルの中に見慣れない女が出入りしてる。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そいつが、わたしの探してる女だって証拠は？")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "中国人だが、この辺りのお仲間と顔見知りってふうでもない。妙に脅えたような態度だし、物腰が普通じゃねえ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "なるほど。なかなか鋭い洞察力じゃない。わかったよ、そのビルを探してみよう。")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "もしも女が姉さんの探してる相手だったら、俺にたっぷりいい目をみさしてくれよな。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 345 #t)
   (proc 1))
 (seg (? (= S 4) (= 345 #t))
   (proc 0)
   (text "「Vagrant」" 'br)
   (text "もしも女が姉さんの探してる相手だったら、俺にたっぷりいい目をみさしてくれよな。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5))
   (proc 0)
   (if (</>
        (//
         (? (= 63 #t))
         (nop@)
         (branch-index
          (</>
           (/
            (text "他の３人の囚人の証言で、軍の機密を盗もうと言い出したのがミツコであるのはわかっている。")
            (wait)
            (text-reset 14)
            (text "ただし、背後で彼女達を操っていた人間がいる事も明らか。ミツコがその人物を知っているはずだ。")
            (wait)
            (text-reset 14)
            (text "やっとこの事件全体を支配する、リズムやカラーを理解しかけた気がする。この分なら、もうじき任務は終了するだろう。")
            (wait)
            (text-reset 14))
           (/
            (text "ミツコを尋問すれば、事件の背後で彼女達を操っていた黒幕の存在がわかるはずだ。")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 62 #t))
         (nop@)
         (text "ナナがミツコと落ち合う約束をしたのは、東京と千葉を結ぶ地下鉄の中。そこに行けば、ミツコを捕らえる事が出来るだろう。")
         (wait)
         (text-reset 14))
        (//
         (? (= 61 #t))
         (nop@)
         (text "ナナはエイプリルやレイファと違って、ただの元兵士。拷問すれば簡単に口を割りそうだ‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 66 #t))
         (nop@)
         (text "アンナはモリイと知り合いだったのか？　モリイの店に行ってみろと言ってたが‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 65 #t))
         (nop@)
         (branch-index
          (</>
           (/
            (text "千葉の怪しげな店で会った女、モリイといった‥‥‥モリイは千葉の裏世界でもかなり知れた顔らしい。")
            (wait)
            (text-reset 14)
            (text "ふたりの事も、何か知っていそうな素振りだった。しかし、軍部や情報部の権威は、千葉では何の効力もない。")
            (wait)
            (text-reset 14)
            (text "力ずくでってのも、あの女が相手ではいい考えとも思えない‥‥‥どうしたらモリイの口を割る事ができる？")
            (wait)
            (text-reset 14))
           (/
            (text
             "モリイはナナとミツコの事を、何か知っているようだ。そうでなくても、千葉で情報を得る事が出来る。何とか味方につけなければ。")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 58 #t) (= 60 #t))
         (branch-index
          (</>
           (/
            (text "エイプリルとレイファから聞き出した話だと、彼女達をスカウトしたのは、元軍部高官の秘書だったミツコらしい。")
            (wait)
            (text-reset 14)
            (text "そして、ミツコとナナは恋人同士だった。ふたりが一緒に千葉に潜伏しているという話は、まんざら嘘ではなさそうだ。")
            (wait)
            (text-reset 14))
           (/
            (text "次にわたしがすべき事は、ナナとミツコを捕まえる事だ。ふたりは千葉シティに逃げ込んだらしい。しかし‥‥‥")
            (wait)
            (text-reset 14)
            (text
             "千葉は政府や軍にも見捨てられた無法地帯、情報部の威光さえ届かない場所だ。ふたりをみつけるどころか、わたしの命さえ‥‥‥")
            (wait)
            (text-reset 14))
           (/
            (text "次にわたしがすべき事は、ナナとミツコを捕まえる事だ。ふたりは千葉シティに逃げ込んだらしい。しかし‥‥‥")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #f) (= 60 #f))
         (nop@)
         (text "まずはエイプリルを尋問してみよう。この事件全体を解く鍵がみつかるかもしれない。")
         (wait)
         (text-reset 14)
         (text "それが無理でも、レイファを逮捕するためのヒントか、第３の囚人を発見する手がかりを得られればいい。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #f) (= 60 #f))
         (nop@)
         (text "エイプリルがわたしの拷問に耐えられたとは思いたくない。彼女は本当に何も知らなかったのか‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #t) (= 60 #f))
         (nop@)
         (text "ふたり目の囚人、レイファを逮捕した。彼女を尋問すれば、何か情報が得られるかもしれない。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (text "ふたりの囚人は逮捕した。彼女達を尋問すれば、機密に関する情報を得られるだろう。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (text "レイファを逮捕した。彼女を尋問すれば、事件全体を解く鍵がみつかるかもしれない。")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (text "レイファがわたしの拷問に耐えられたとは思いたくない。彼女は本当に何も知らなかったのか‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (text "レイファは何も喋らなかった。エイプリルを何とかしなければならない。どんな事でもいい、何とかしないと‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (text "まずはエイプリルかレイファを逮捕しなければ。明らかに自分より強いとわかっている相手と戦うのは、気が重い‥‥‥")
         (wait)
         (text-reset 14))))
   (proc 1)))