(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (branch-reg 55 (</> (/) (/ (mes-jump "mes¥mb_c02.mes"))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b05_01.gpc")
  (image-mem 0 3)
  (if (</>
       (//
        (? (= P 3))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_03.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_03v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3)))))
       (// (nop@))))
  (proc 3)
  (load-mem "clm¥b05_01.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 906 #t))
        (text "ビル内の一室を出て、チャイナタウンの街路に出た。")
        (wait)
        (text-reset 14))
       (//
        (? (= 54 #t))
        (text "チャイナタウンにやって来た。カール大佐の言う事が正しければ、レイファはこの辺りの何処かに潜んでいるのだろう。")
        (wait)
        (text-reset 14)
        (text "しかし、倒壊しかけたビル群を全て回っていたら膨大な時間を浪費する事になるだろう、何とかしなければ‥‥‥")
        (wait)
        (text-reset 14))
       (//
        (? (= 905 #t))
        (text "チャイナタウンの一画にやって来た。辺りは廃屋然としたビルが立ち並び、今にも崩れ落ちそうだ。")
        (wait)
        (text-reset 14))
       (//
        (? (= 905 #f))
        (text "チャイナタウンだ。辺りは廃屋然としたビルが立ち並び、今にも崩れ落ちそうな雰囲気。")
        (wait)
        (text-reset 14)
        (text "この一画は、言わずと知れた中国系移民の居住区だが、彼等の他にも犯罪者が多くたむろっている事もよく知られている。")
        (wait)
        (text-reset 14)
        (text "軍と情報部に追われた逃亡者なら、ここに潜んでいてもおかしくはない。しかし、どうやって見つければいい？")
        (nop@)
        (set-reg 241 #t)
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 905 #t)
  (nop@)
  (set-reg 906 #f)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 54 #f))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (if (</>
              (// (? (= 54 #t)) (exec-mem 4768 5 9 22 6 1 0 0 4480 4480 1 0))
              (// (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0))))
         (menu1
          6
          80
          6
          96
          (</>
           (/ (text "　　　情報部前　　　"))
           (/ (set-reg 54 #t) (nop@) (text "　　ビル内に入る　　"))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MB_A01.MES"))
              (// (? (= S 1)) (mes-jump "mes¥MB_C01A.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 54 #t) (= 253 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (if (</>
              (// (? (= 54 #t)) (exec-mem 4768 5 9 22 6 1 0 0 4480 4480 1 0))
              (// (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0))))
         (menu1
          6
          80
          6
          96
          (</>
           (/ (text "　　　情報部前　　　"))
           (/ (set-reg 54 #t) (nop@) (text "　　ビル内に入る　　"))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MB_A01.MES"))
              (// (? (= S 1)) (mes-jump "mes¥MB_C01A.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 250 #t))
   (proc 0)
   (text "いつ崩れ落ちてもおかしくないが、入り口は確保されている。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 54 #t) (= 243 #t))
   (proc 0)
   (text "ほとんど崩れ落ちそうなほどボロボロだが、入り口部分は人が中に入れるくらいは原形を保っている。")
   (wait)
   (text-reset 14)
   (text "こんなビルの中に入ったら、いつ天井が崩れ落ちてくるか不安で仕方ないだろうな‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "しかし、だからこそ犯罪者が潜んでいそうだとも言える。カールの話を信じるなら、レイファはこの辺りにいるはずだし‥‥‥")
   (wait)
   (text-reset 14)
   (text "無作為に探していても、単なる時間の無駄だけれど、何もしないでは、話しは始まらない。")
   (wait)
   (text-reset 14)
   (text "行ってみようか‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 250 #t)
   (proc 1)
   (exec-mem 3072 0)
   (mes-jump "mes¥MB_C01A.MES"))
 (seg (? (= S 1) (= 242 #f))
   (proc 0)
   (text "まわりの建物に比べてかなり低いこのビルは、かつて何に使われていたのだろうか？")
   (wait)
   (text-reset 14)
   (text "この街では、高い場所に居るほど危ないとされている。そう考えると、かなり高級な住宅だったのかもしれない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 242 #t)
   (proc 1))
 (seg (? (= S 1) (= 243 #f))
   (proc 0)
   (text "人が住まなくなって、どれくらいの時間が経過したのだろうか。ビルの側面には、無数の細かいひび割れが走っている。")
   (wait)
   (text-reset 14)
   (text "この辺りに巣食う犯罪者や浮浪者同然の人々も、このビルに住もうとは思わないのではないだろうか？")
   (wait)
   (text-reset 14)
   (text "こんなひどい有り様では、いつ倒壊してもおかしくない。しかし、だからこそ何者かが潜んでいる可能性はあるかも‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 243 #t)
   (proc 1))
 (seg (? (= S 1) (= 243 #t))
   (proc 0)
   (text "人が住まなくなって、どれくらいの時間が経過したのだろうか。ビルの側面には、無数の細かいひび割れが走っている。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 244 #f))
   (proc 0)
   (text "彼方には、はるか上空までそびえるビル群がある。地殻を支える柱の役を負った建物達だ。")
   (wait)
   (text-reset 14)
   (text "それよりも手前にあるこの一画の建物は、いつ倒壊してもおかしくないほどボロボロになっている。")
   (wait)
   (text-reset 14)
   (text "そもそも、この辺りが廃墟同然になったのは、テロやその種の犯罪行為が多発したせいなのか。建物が壊れているのもその為‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 244 #t)
   (proc 1))
 (seg (? (= S 2) (= 245 #f))
   (proc 0)
   (text "瓦礫と崩れかかった建物ばかりの街に、ひときわ高いビル群が威圧的におおい被さるように見える。")
   (wait)
   (text-reset 14)
   (text "この辺りの住民は、毎日あれらを見上げながら暮らしている訳だ。なんて屈辱なんだろう。わたしなら３日と耐えられない。")
   (wait)
   (text-reset 14)
   (text "しかし、移民達はこの生活を享受しなければいけない。その生活から抜け出す事は、決して出来ない‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 245 #t)
   (proc 1))
 (seg (? (= S 2) (= 245 #t))
   (proc 0)
   (text "そもそも、この辺りが廃墟同然になったのは、テロやその種の犯罪行為が多発したせいか？")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 246 #f))
   (proc 0)
   (text "巨大な立体駐車場とショッピングモールがくっついた物のようだ。今では見る影もないが、往時の賑わいが容易に想像出来る。")
   (wait)
   (text-reset 14)
   (text "建物には、破壊の痕の他に略奪の痕が見てとれる。もう何年も前の話だろう。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 246 #t)
   (proc 1))
 (seg (? (= S 3) (= 247 #f))
   (proc 0)
   (text "本来なら一杯の車で満ちているはずなのに、ぽっかりと口を開けたビルの窓からは、真っ暗な空間しか見る事が出来ない。")
   (wait)
   (text-reset 14)
   (text "どういう経緯で廃墟になったのかは不明だけど、その後の略奪のせいで、すっかり空っぽにされたんだろう。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 247 #t)
   (proc 1))
 (seg (? (= S 3) (= 247 #t))
   (proc 0)
   (text "巨大な立体駐車場とショッピングモールがくっついた物のようだ。今では見る影もないが、往時の賑わいが容易に想像出来る。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 253 #t))
   (proc 0)
   (text "「Vagrant」" 'br)
   (text "何かくれよ、そしたら思い出すかもしんねえ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 252 #t))
   (proc 0)
   (text "「Vagrant」" 'br)
   (text "お前、何者だ‥‥‥この辺の人間じゃないな？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "人を探してるんだよ、わかる？　言葉はわかるんでしょう？")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "馬鹿にすんな‥‥‥それ以上近づくな！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あのねえ、そんな離れてちゃ話しにくいでしょう？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "このあたりにね、わたしの探してる女が逃げ込んだらしいの。あんた、ずっとここいら辺りを寝ぐらにしてんじゃないの？")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "何かくれよ、そしたら思い出すかもしんねえ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "何かって言われてもね。あんたが欲しがるような物、何も持ってないんだよ。")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "それじゃ、何も知らねえ。")
   (wait)
   (text-reset 14)
   (text "きっと何も知らないに違いない。第一、わたしは本当に何も持ってない。こいつに恵んでやれるような物は。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 253 #t)
   (proc 0))
 (seg (? (= S 4) (= 248 #f))
   (proc 0)
   (text "こっちの動きを警戒して微動だにしない。わたしの事を恐れてるのか、それとも襲う価値があるか値踏みしているのかもしれない。")
   (wait)
   (text-reset 14)
   (text "どっちにしても、あまり重要には思えない。万が一襲って来たとしても、わたしより強そうには見えないし。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 248 #t)
   (proc 1))
 (seg (? (= S 4) (= 249 #f))
   (proc 0)
   (text "よく見ると、日本人のように見えるが‥‥‥")
   (wait)
   (text-reset 14)
   (text "これだけ優遇されている世界なのに、それでもなおドロップアウトしてしまうなんて、簡単には信じられない事だ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ちょっとあんた。この辺で怪しい女を見なかった？")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "我ながら馬鹿みたいな質問だった。このあたりで怪しくない奴なんて滅多にいないだろうし、一番怪しいのはこの男に違いない。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "もっとこっちに来なよ、何もしやしないわよ。")
   (wait)
   (text-reset 14)
   (text "「Vagrant」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "近寄って来る様子はない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 249 #t)
   (proc 0))
 (seg (? (= S 4) (= 249 #t))
   (proc 0)
   (text "こっちの動きを警戒して微動だにしない。わたしの事を恐れてるのか、それとも襲う価値があるか値踏みしているのかも。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 252 #t))
   (proc 0)
   (text "わざわざ危険をおかして、倒壊したビルの中に入って調べるだけの必要があるのか‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 54 #t))
   (proc 0)
   (text "カール大佐の話を信じるならば、レイファはここに居る訳だ。となれば、とにかく探してみるしかない。")
   (wait)
   (text-reset 14)
   (text "とは言え、チャイナタウンには無数のビルがある。これを全て探すなんて、とても不可能だし‥‥‥")
   (wait)
   (text-reset 14)
   (text "手近な建物から調べてみるか‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 252 #t)
   (proc 1))
 (seg (? (= S 5) (= 251 #f))
   (proc 0)
   (text "チャイナタウンにはいくつものビルがあって、しかも逃走した囚人がここにいるとは限らない‥‥‥")
   (wait)
   (text-reset 14)
   (text "何のあてもないのに、全ての建物の中を調べるのは時間の浪費だ。しかも、それらのビルの屋根が急に落ちないって保証もない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 251 #t)
   (proc 1))
 (seg (? (= S 5) (= 251 #t))
   (proc 0)
   (text "あたりには目的の逃走した囚人らしい人影はない。わたしの目の前に立った浮浪者の男が目的の人間とも思えないし‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))