(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (load-mem "clm¥b04_01.clm" 32768)
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b04_01.gpc")
  (image-mem 0 3)
  (if (</>
       (//
        (? (= P 6))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_06.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 6))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_06v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 6)))))
       (// (nop@))))
  (if (</>
       (//
        (? (= 57 #t))
        (proc 3)
        (text-frame 10 312 70 383)
        (text "秋葉原のブラックマーケットにある、エイプリルの店だ。主人が逮捕された今となっては、得る事は何もないはずだ‥‥‥")
        (wait)
        (text-reset 14)
        (nop@)
        (set-reg 932 #t)
        (mes-jump "mes¥mb_a02.mes"))
       (//
        (? (= 57 #f))
        (image-file "gpc¥b04_01a.gpc")
        (image-mem 1 0)
        (load-mem "clm¥b04_01.clm" 32768)
        (proc 3)
        (text-frame 10 312 70 383)
        (text "「Woman at the counter」" 'br)
        (text "いらっしゃい‥‥‥また、あなたですか。")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "あら、まだ逃げずに居たとはね。とっくの昔に行方を晦ませてると思ったよ。")
        (wait)
        (text-reset 14)
        (text "「Woman at the counter」" 'br)
        (text "えっ‥‥‥な、何の話をしてるの？")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "あんたの話よ。わたしはね、馬鹿だと思われるのが大嫌いなんだ。そういうふうに振舞われるのは我慢できない。")
        (wait)
        (text-reset 14)
        (text "「Woman at the counter」" 'br)
        (text "‥‥‥‥‥‥‥‥‥‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "それとも何かい、あんた、そんなに自信家なの？")
        (wait)
        (text-reset 14)
        (text "「Woman at the counter」" 'br)
        (text "な、何をおっしゃってるのか、よくわからないんですけど？")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "そうかい、それじゃ嫌でもわかるようにしてやるさ。")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 932 #f)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 57 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 (</> (/ (text "　　　情報部前　　　"))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MB_A02.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 57 #f) (= 368 #t) (= 931 #f))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 16 48")
   (exec-mem 4768 4 8 16 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " ゴーグル装着 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= 369 #f))
               (text "ゴーグルを装着した。")
               (wait)
               (text-reset 14)
               (image-file "gpc¥b04_01b.gpc")
               (image-mem 0 3)
               (image-file "gpc¥shotwaku.gpc")
               (image-mem 1 0)
               (proc 3)
               (text "視界が緑一色だ。これがフィルタを通して見た視界‥‥‥そして、ゴーグルの中に浮かび上がる、卍の印。")
               (wait)
               (text-reset 14)
               (text "「Woman at the counter」" 'br)
               (text "それは‥‥‥そのゴーグル、見た事がある。")
               (wait)
               (text-reset 14)
               (text "「Kiyomi」" 'br)
               (text "そうかい、それじゃ仕方ないね‥‥‥‥‥‥")
               (wait)
               (text-reset 14)
               (text "「Woman at the counter」" 'br)
               (text "まさか、あたしの体に‥‥‥クソッ！")
               (wait)
               (text-reset 14)
               (text "「Kiyomi」" 'br)
               (text "はじめまして、エイプリル。もっとも、わたしはずっと前からあんたの事を疑ってたがね！")
               (wait)
               (text-reset 14)
               (text "「April」" 'br)
               (text "チッ、もっと早く退くべきだった。")
               (wait)
               (text-reset 14)
               (text "「Kiyomi」" 'br)
               (text "もう遅い。あんたは隠れ蓑を大事にしすぎたんだよ。軍装品屋の生活がそんなに楽しかったのかい？")
               (wait)
               (text-reset 14)
               (text "「April」" 'br)
               (text "あなたにはわかんないのさ！　外人部隊で地獄みたいな戦場を生き抜いて、それでも除隊すればただの移民なんだよ？")
               (wait)
               (text-reset 14)
               (text "「April」" 'br)
               (text "あたしが悪いってのかよ‥‥‥")
               (wait)
               (text-reset 14)
               (text "「Kiyomi」" 'br)
               (text "エイプリル、あんたを逮捕する。")
               (wait)
               (text-reset 14)
               (nop@)
               (set-reg 369 #t))
              (//
               (? (= 369 #t))
               (text "ゴーグルを装着した。視界が緑に変わる‥‥‥")
               (wait)
               (text-reset 14)
               (image-file "gpc¥b04_01b.gpc")
               (image-mem 0 3)
               (image-file "gpc¥shotwaku.gpc")
               (image-mem 1 0)
               (proc 3))))
         (nop@)
         (set-reg 931 #t))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 57 #f) (= 368 #f) (= 931 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 57 #f) (= 931 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 16 48")
   (exec-mem 4768 4 8 16 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " ゴーグル解除 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "P 1 4 64")
         (text "ゴーグルを外した。")
         (wait)
         (text-reset 14)
         (image-file "gpc¥b04_01.gpc")
         (image-mem 0 3)
         (image-file "gpc¥b04_01a.gpc")
         (image-mem 1 0)
         (proc 3)
         (nop@)
         (set-reg 931 #f))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 3) (= 361 #f))
   (proc 0)
   (text "ケースの中のほとんどの銃が、かつて軍で使われていた中古品だ。自ら法律を反故にするなんて、軍もよほど困っているらしい。")
   (wait)
   (text-reset 14)
   (text "もっとも、街中に銃が広まってしまった今となっては、銃規制など無意味には違いないが‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 361 #t)
   (proc 1))
 (seg (? (= S 3) (= 362 #f))
   (proc 0)
   (text "ガラスケースの中には、古いタイプの軽機関銃と様々なハンドガンが陳列されている。")
   (wait)
   (text-reset 14)
   (text "銃刀法が事実上無効となってしまった今では、それらの品は街中でよく見られる物だ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 362 #t)
   (proc 1))
 (seg (? (= S 3) (= 362 #t))
   (proc 0)
   (text "ケースの中のほとんどの銃が、かつて軍で使われていた中古品だ。自ら法律を反故にするなんて、軍もよほど困っているらしい。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 363 #f))
   (proc 0)
   (text "どのマスクも中古品らしく古びている。どこかの戦線で使われた物だろうが、いったい誰が買うのだろう？")
   (wait)
   (text-reset 14)
   (text "本当にガスマスクが必要な事態になったとしたら、こんなチャチな中古品で身を守れるとは思わない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 363 #t)
   (proc 1))
 (seg (? (= S 4) (= 363 #t))
   (proc 0)
   (text "どのマスクも中古品らしく古びている。どこかの戦線で使われた物だろうが、いったい誰が買うのだろう？")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 365 #f))
   (proc 0)
   (text "軍用ブーツと背嚢が、山のように積まれている。どちらも実際に軍で使われていた物のようだ。")
   (wait)
   (text-reset 14)
   (text "今でも十分使用に耐えるだろうが、この中の何割が死んだ兵士から接ぎ取った物だろうと考えると、買う気にはなれない‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 365 #t)
   (proc 1))
 (seg (? (= S 5) (= 365 #t))
   (proc 0)
   (text "軍用ブーツと背嚢が、山のように積まれている。どちらも実際に軍で使われていた物のようだ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (>= S 6) (= 57 #t))
   (proc 0)
   (text "ここにはもう、エイプリルの姿はない。彼女が捕まる危険を冒しても守ろうとした店は、近いうちに略奪者の物になるだろう。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 6) (= 368 #t))
   (proc 0)
   (text "エイプリルとの戦いは、避ける事が出来ないだろう。しかし、勝算が無い訳でもない。")
   (wait)
   (text-reset 14)
   (text "彼女は隠れ蓑の生活に浸りすぎて、もはや特殊部隊の頃の鋭敏さや残酷さを持ち合わせていないからだ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 6) (= 359 #t) (= 360 #t))
   (proc 0)
   (text "やはり、この女がエイプリルなのは間違いないだろう。そろそろ自慢のゴーグルの出番だな‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 368 #t)
   (proc 1))
 (seg (? (= S 6))
   (proc 0)
   (branch-reg
    81
    (</>
     (/
      (text "カウンターの女は、落ち着きなくわたしの様子を伺っている。この前あれだけ脅しておいたから、それも無理ないが‥‥‥")
      (wait)
      (text-reset 14)
      (text "もしもこの女がエイプリルだとしたら、この前わたしが来た直後に行方を晦ませるのが普通だろう。")
      (wait)
      (text-reset 14)
      (text "しかしわたしの勘は、まさにこの女がエイプリルだと言っているのだ。それが間違いとも思えない。")
      (wait)
      (text-reset 14))
     (/
      (text "この女がエイプリルである事は、レイファの証言からしても明らかだ。どんなに芝居がうまくても、もはや逃れる事は出来ない。")
      (wait)
      (text-reset 14)
      (text "よもや仲間が捕えられ、自分の素性がばれる事など予想だにしていないようだが‥‥‥")
      (wait)
      (text-reset 14)
      (text "この勝負はどう転んでもエイプリルに勝ち目はない。出来れば面倒を起こさずに、さっさと諦めてほしいもんだ。")
      (wait)
      (text-reset 14))))
   (nop@)
   (set-reg 367 #t)
   (proc 1))
 (seg (? (= S 1) (= 370 #t))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "聞こえなかったのかい？　その手をカウンターの上に置くんだよ！")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "今のあんたにわたしを倒せると思う？　隠れ蓑の生活に慣れきってすっかりナマクラになっちまったあんたに。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "エイプリル、お前はもう特殊部隊のエリートじゃない。悪あがきはしない方が利口ってもんだ。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "そ、そんな事‥‥‥やってみなきゃわかんないでしょ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "仕方がない‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1)
   (exec-mem 3072 0)
   (mes-jump "mes¥MC_A01.MES"))
 (seg (? (= S 1) (= 369 #t))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "あんたに同情しない訳じゃないけどね、軍の情報に手をつけたのは失敗だった。本当に逃げきれると思ってたのかい？")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "誰に唆されたのか知らないけど、そいつにはあんたの身を守る気なんてなかった訳だ。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "違う！　あたしは‥‥‥金や名誉が欲しかったんじゃないんだ。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "あたしなんて所詮は移民さ。この国じゃゴミ屑と大して変らない。でも‥‥‥")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "そんなあたしの事を必要としてくれるって言うんだ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "詳しい話は、情報部で聞く。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥誰があんたなんかに捕まるもんか。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "さあ、その手をカウンターの上に置くんだよ！")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 370 #t)
   (proc 1))
 (seg (? (= S 1) (= 358 #f))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "この前頼んどいたはずだけど、エイプリルが店に現れたって報告はもらってないよ。")
   (wait)
   (text-reset 14)
   (text "「Woman at the counter」" 'br)
   (text "えっ、ええ‥‥‥だってエイプリルは現れなかったんですもの。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そうかい‥‥‥エイプリルはどうしてるんだろうねえ、軍を辞めて仕事もないだろう、食うにも困ってるんじゃないかね。")
   (wait)
   (text-reset 14)
   (text "「Woman at the counter」" 'br)
   (text "‥‥‥‥‥‥‥‥‥そうかもね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんた、心配じゃないのかい？　友人がそんな目にあってるかもしれないってのに。")
   (wait)
   (text-reset 14)
   (text "「Woman at the counter」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしが怖いかい？　そんなに脅えた目で見なさんな。何にもしやしない。あんたがエイプリルでなければね。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 358 #t)
   (proc 1))
 (seg (? (= S 1) (= 359 #f))
   (proc 0)
   (text "「Woman at the counter」" 'br)
   (text "お願い、もう帰ってよ‥‥‥エイプリルが来たら連絡するから！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そう邪険にしなくてもいいだろ、あんたをどうしようって気はないんだから。")
   (wait)
   (text-reset 14)
   (branch-reg
    59
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "ところで、あんた知ってるかい？　エイプリルは軍に捕えられた時尋問を受けてるんだ。")
      (wait)
      (text-reset 14)
      (text "「Woman at the counter」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "その時にね、軍の尋問を担当したクソ野郎はエイプリルの体に印を付けたんだってさ。")
      (wait)
      (text-reset 14)
      (text "「Woman at the counter」" 'br)
      (text "しるしって‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "付けられた本人がわからないのかい？")
      (wait)
      (text-reset 14)
      (text "「Woman at the counter」" 'br)
      (text "だから‥‥‥あたしは知らないって言ってるでしょう！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "観念しなよ、あんたはもう逃げられない‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "「Kiyomi」" 'br)
      (text "そりゃそうと、レイファを逮捕したよ。あんたのお仲間。")
      (wait)
      (text-reset 14)
      (text "「Woman at the counter」" 'br)
      (text "えっ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "やっぱり驚いたね。これでもまだ自分は無関係だって言い張るつもりなの？")
      (wait)
      (text-reset 14)
      (text "「Woman at the counter」" 'br)
      (text "しっ、知らないって言ってるじゃない！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あきらめの悪い女だね。あんたの事はレイファから聞いてるんだ。")
      (wait)
      (text-reset 14)
      (text "「Woman at the counter」" 'br)
      (text "いい加減な事を言わないでよ、そんな訳ないじゃない‥‥‥")
      (wait)
      (text-reset 14))))
   (nop@)
   (set-reg 359 #t)
   (proc 1))
 (seg (? (= S 1) (= 359 #t))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "観念しなよ、あんたはもう逃げられない‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 371 #t))
   (proc 0)
   (text "この女がエイプリルだとしたら、もはや特殊部隊の時の能力を有していないって事になる。銃を見ただけで震えるようでは。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 369 #t))
   (proc 0)
   (text "女の顔はこころなしか青ざめて、わたしの顔を正面で見据える事も出来ない様子。武装した私の姿を見れば無理ないか‥‥‥")
   (wait)
   (text-reset 14)
   (text "この女がエイプリルだとしたら、もはや特殊部隊の時の能力を有していないって事になる。銃を見ただけで震えるようでは。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 371 #t)
   (proc 1))
 (seg (? (= S 2) (= 360 #f))
   (proc 0)
   (text "不審な客を見るような目でわたしを見ている。無邪気な軍装品屋のレジ係を装っているが、落ち着きがない。")
   (wait)
   (text-reset 14)
   (text "右腕をカウンターの下に置き、油断なく辺りの様子を伺うような仕草。見たとおりの人間でない事は間違いないな‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 360 #t)
   (proc 1))
 (seg (? (= S 2) (= 360 #t))
   (proc 0)
   (text "どうやって逃げ出すか、策を練っているのだろうか。落ち着きがなく、店の裏口の方を横目で見ている‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))