(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (branch-reg 64 (</> (/) (/ (mes-jump "mes¥mb_f02.mes"))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b07_01.gpc")
  (image-mem 0 3)
  (proc 3)
  (if (</>
       (//
        (? (= P 6))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_06.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 6))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_06v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 6)))))
       (// (nop@))))
  (load-mem "clm¥b07_01.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (// (? (= 933 #t)) (text "モリイの店に入った。") (wait) (text-reset 14))
       (//
        (? (= 933 #f))
        (text "路地の奥まった所にある、一軒の店の中に入った。店といっても看板の類がある訳ではなく何を商っているのか見当もつかない。")
        (wait)
        (text-reset 14)
        (text "店内にも、特に商品と言えそうな物は見当たらず、ガラクタが雑に積み重ねてあるだけだ。")
        (wait)
        (text-reset 14)
        (text "そして、わたしを出迎えたこの店のオーナーと思われる女。いかにも千葉の住人そのもの、外の世界ではお目にかかれない人間だ。")
        (wait)
        (text-reset 14)
        (text "「ミラーグラスの女」" 'br)
        (text "誰だい、あたしの店に何か用かい？")
        (wait)
        (text-reset 14)
        (text "女は上から下まで黒のレザーを纏い、まるで精悍な猫科の動物のよう。そして、もっとも奇妙なのが、目を覆ったミラーグラスだ。")
        (wait)
        (text-reset 14)
        (text "眼底部分に、サングラスのレンズを埋めこんでしまっているようでフレームは見当たらない。こんなポッドモッドは珍しい。")
        (wait)
        (text-reset 14)
        (text "「ミラーグラスの女」" 'br)
        (text "あんた、千葉の人間じゃないようだね。それにその格好。軍人かさもなきゃ情報部ってとこ？")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "どうでもいい事さ、あんたの知った事じゃない。")
        (wait)
        (text-reset 14)
        (text "「ミラーグラスの女」" 'br)
        (text "なるほど、まあそうだね。それであたしに何か用かい？")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "さあね‥‥‥どうしてここに来たのかも解らないんだから。この店は何を売ってるの？　あんたは何者だい。")
        (wait)
        (text-reset 14)
        (text "「ミラーグラスの女」" 'br)
        (text "あたしはモリイ、この店は‥‥‥そう、客の望む物は何でもある。判るかい？　この店は千葉の全てさ。")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 933 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 66 #f) (= 65 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 (</> (/ (text "　　　外に出る　　　"))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MB_E02.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 66 #t) (= 67 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str " 　移動　 "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 (</> (/ (text "　　　外に出る　　　"))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MB_E02.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 68 #t))
   (proc 0)
   (text "「Mori」" 'br)
   (text "よう、ご同輩。また一緒にランをしようや。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 67 #t))
   (proc 0)
   (text "「Mori」" 'br)
   (text "まずはコフィン宿に行ってみな。女を押さえたら、千葉から送り出す手配をしてやるよ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 419 #t))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "メインストリートをまっすぐね‥‥‥ところで、あんたはどうやってナナを見つけたの、顔も見た事ないのに？")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "ご丁寧にマーキングまでしてあったのに、そりゃないだろう。あの印は、皮膚を張り替えない限り消えないだろうね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "その事をどうして‥‥‥アンナが教えたの？")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "あのマークはね、秘密でも何でもないよ。フィルターを通せば誰にでも見えるんだから。あたしのサングラスは飾りじゃないよ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それにしても、広大な千葉の中で顔さえ知らない女を見つけ出したんだ、大したものさ。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "ハッカーってのはどうしようもない自惚れ屋さ、手前の腕を自慢したくて仕方ない。結局それが命取りだったね。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "おとなしく淫売の真似をしてりゃいいものを、いくつか仕事をしちまったのさ。しっかり足跡が残ってた。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "この仕事、あんたの方がわたしよりずっと向いてるみたいだね。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "千葉の中でだけ通用する魔法さ、そう気を落としなさんな。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "コフィン宿ね‥‥‥わかった、そこに行ってみる。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "ヤツを捕まえたら、千葉から送り出す手配をしてやるよ。横槍が入るのは御免だろう？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "やさしいじゃない、それは別料金？")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "サービスさ、あんた気に入ったよ。ランが済んだら一杯やろうや。あたし達、気が合いそうじゃないか。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "御免だね。あんたの前だと、わたしはただの小娘に見える。そんな気持ちになるのはお断わり。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "人間、たまに謙虚な気持ちになるのもいいもんさ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 67 #t)
   (proc 1))
 (seg (? (= S 1) (= 66 #t))
   (proc 0)
   (text "「Mori」" 'br)
   (text "よう、来たね。例の女の居所は調べがついてるよ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "金の話はついた？　わたしの上司が何とかしてくれるって話だったんだけど。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "ああ、支払いは済んでる。あんたの上司、アンナってんだろ。気前のいい人だね、それにあたしの商売をちゃんとわかってる。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥‥‥アンナは何をしたの？")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "本人から直接聞きなよ。それで、例のナナって女だけど‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "間違いなく千葉に居る。さすがにハッカーをやる程大胆じゃなかったみたいだけどね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それじゃ、千葉で何をやってるの？")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "コフィン宿って知ってるかい？　簡単に言うと売春宿みたいなもんだけどね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "売春宿？　ナナは商売女になってるって訳か‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "ただの売春婦じゃないんだけどね、これは千葉独特のもんさ。脳に配線した女にしか出来ない。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "さっぱり訳がわからないね‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "まあいいさ、自分で確かめりゃいい。ナナはエリーと名乗ってる。いわゆる源氏名ってヤツ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "女のわたしが行っても大丈夫なの？　そんなヤバい所で争い事は遠慮したいね。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "ここが何処だと思ってる。もっと変てこなセックスを好む変態が腐るほど居るんだ、レズくらいどうって事ない。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "それに、争い事にはならないと思うね。まあ安心しなよ、あたしがうまい事やってやるからさ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "とにかく、コフィン宿へ行ってみなって。メインストリートをまっすぐ進んだ路地さ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 419 #t)
   (proc 1))
 (seg (? (= S 1) (= 412 #f))
   (proc 0)
   (text "「Mori」" 'br)
   (text "その格好で千葉の街をうろつくなんて、大した度胸だよ。この千葉で目立っちまうとは。過激な女だ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "大きなお世話。こっちだって好きでやってる訳じゃない。それにしても、この店は何を売ってるのさ、見たとこ何も無いわ。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "言ったろ、何でもあるって。それであんたは何をお望みなんだい？新しい身分か闇のサイバネ医者？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしが逃亡者に見えるっての？　そんなのはお呼びじゃないね。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "ふん、最近はそういう奴が多いんだけどね。何人もの軍人が新しい顔と身分を買いに来た。そろそろ本気でヤバいんだろうね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "どうやら無駄足だったみたいだね、もっとも何かがあるって期待してた訳じゃないんだけど。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "嫌な女だね、あんまり人の事は言えないけどさ‥‥‥あたしは千葉の裏の世界でも顔なんだよ、期待は裏切らないつもりだけどね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "人を探してる。女がふたり、この千葉に逃げ込んだんだ。ちょっと訳ありでね。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "なんだ、そんな事か‥‥‥あんた、一番頼りになる人間に会いに来たね。そいつはあたしの得意分野だ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 412 #t)
   (proc 1))
 (seg (? (= S 1) (= 412 #t) (= 65 #f))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "ふたりは、どっちも元軍人。名前はナナとミツコ。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "なる程。あんたは軍人で、ふたりを捕まえるのが任務な訳か。ふたりのホロはあるかい？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "何もない。ナナは優秀なハッカーだったらしい、軍のデータベースから、自分達のデータを根こそぎ消しちまったのさ。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "軍のデータに手を出せるハッカーなんて、存在しないよ。あたしの知ってる限りじゃね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それじゃ、彼女は奇蹟をやってのけたって訳さ。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "簡単に言うなよ。軍のデータベースをサイバーペースで見てみな、１００キロ四方はある超巨大なマトリクスだよ？")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "それに手を出してみな、あっという間に焼かれちまう。今までに何人のハッカーがフラットラインしちまった事か‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "でも、それが事実さ。ふたりが千葉に潜伏してるのは、彼女達の仲間を尋問して聞き出した。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "顔を知らなくても、同じ場所に居ればそれとわかる仕掛けもある。でもね、千葉じゃわたしは自由に動けない‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "ミツコってのは日本人だろう、千葉じゃ目立ちすぎるから人目につかない所に隠れてるはずだね。見つけるのは難しい。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "もうひとりの方からだね。ハッカーなら、千葉で職にあぶれる事は無いだろうけど、それならあたしの耳に入らない訳はないね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "自信がありそうじゃない、ナナの事を知ってるんだね？")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "ハッカーは大抵ポッドモッドをしてる。闇医者の線からも何かわかるかもね。でも、こっから先は商売さ。あんたいくら出す？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "金を取るってのかい？")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "当たり前、こっちも商売だからね。おっと、あたしを脅そうって気なら止めときな。あんたより強いよ。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "それに、あたしに手を出したら、千葉から生きて帰るのは無理さ。そういう取り決めでね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "いくら欲しいのさ。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "さてね、軍は金持ちだろう？　少しはずんでもらおうか。失望はさせないよ、その女は必ず見つけてやる、千葉に居るならね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "金の話はわたしじゃ決められない。上と相談してみないと。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "それでいい、調べといてやるよ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 65 #t)
   (proc 1))
 (seg (? (= S 1) (= 65 #t))
   (proc 0)
   (text "「Mori」" 'br)
   (text "こっちも商売だからタダって訳にはね。あんたのスポンサーと相談して来なよ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 413 #f))
   (proc 0)
   (text "レザースーツの下は、鍛え上げられた筋肉質の体。ただ者でないのは一目見ただけでもわかる。")
   (wait)
   (text-reset 14)
   (text "千葉という土地柄でもあるし、何度も危険な橋を渡ってきたプロなのだろう。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 413 #t)
   (proc 1))
 (seg (? (= S 2) (= 414 #f))
   (proc 0)
   (text "モリイの姿でもっとも目につくのは、やはり眼底部分に埋め込まれたミラーグラスだろう。")
   (wait)
   (text-reset 14)
   (text "今までにも変わったポッドモッド＝肉体改造を見てきたが、モリイのそれは、とびきり変わっている。")
   (wait)
   (text-reset 14)
   (text "おそらく視神経にも手を入れて、単なる装飾の為以外の機能を持っているに違いない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 414 #t)
   (proc 1))
 (seg (? (= S 2) (= 414 #t))
   (proc 0)
   (text "レザースーツの下は、鍛え上げられた筋肉質の体。ただ者でないのは一目見ただけでもわかる。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 415 #f))
   (proc 0)
   (text "大型のコンプレッサーだろうか、布の下から古びた金属の箱のような物が見える。")
   (wait)
   (text-reset 14)
   (text "これもモリイの商売道具のひとつだとすると、建築関係の仕事でもしているのだろうか‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 415 #t)
   (proc 1))
 (seg (? (= S 3) (= 416 #f))
   (proc 0)
   (text "わたしにはただのガラクタにしか見えないが、モリイにとっては価値ある商品なのだろう‥‥‥")
   (wait)
   (text-reset 14)
   (text "それとも、殺風景な店の装飾品か、偽装の為に置かれた本物のガラクタなのかもしれない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 416 #t)
   (proc 1))
 (seg (? (= S 3) (= 416 #t))
   (proc 0)
   (text "大型のコンプレッサーだろうか、布の下から古びた金属の箱のような物が見える。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 417 #f))
   (proc 0)
   (text "無造作に積まれたダンボールの箱は、中に何が入っているのか見当もつかない。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "そいつをご所望かい？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "この箱の中、何が入ってるんだい。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "アイスブレーカーって、知ってる？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "さあ‥‥‥聞いた事もないけど。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 417 #t)
   (proc 1))
 (seg (? (= S 4) (= 418 #f))
   (proc 0)
   (text "「Mori」" 'br)
   (text "その箱の中身はＲＯＭのソフトだよ。ハッカーがランに使うアイスブレーカーさ。目茶苦茶素性の怪しいヤツ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それは何をする物なの‥‥‥モリイ、あんたもハッカーなのかい？")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "アイスブレーカーってのは、サイバースペースで使う、プロテクト破りの道具。簡単に言うとね‥‥‥ローテクには説明出来ないよ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "悪かったね、わたしは好きでローテクやってんだ。文句を言われる筋合いはないよ。")
   (wait)
   (text-reset 14)
   (text "「Mori」" 'br)
   (text "文句を言ったつもりはないよ。あたしだってローテクに毛が生えたようなもんさ、肉体を酷使するのが好きでね。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 418 #t)
   (proc 1))
 (seg (? (= S 4) (= 418 #t))
   (proc 0)
   (text "箱の中身は、ハッカーの為のソフトらしい。しかし、何処で造られた物なのか想像出来ない。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5))
   (proc 0)
   (if (</>
        (//
         (? (= 63 #t))
         (nop@)
         (branch-index
          (</>
           (/
            (text "他の３人の囚人の証言で、軍の機密を盗もうと言い出したのがミツコであるのはわかっている。")
            (wait)
            (text-reset 14)
            (text "ただし、背後で彼女達を操っていた人間がいる事も明らか。ミツコがその人物を知っているはずだ。")
            (wait)
            (text-reset 14)
            (text "やっとこの事件全体を支配する、リズムやカラーを理解しかけた気がする。この分なら、もうじき任務は終了するだろう。")
            (wait)
            (text-reset 14)
            (text "そうなれば、千葉なんぞに用はない。早くミツコを尋問するべきだろう。この街はただ立っているだけでも危険なのだから。")
            (wait)
            (text-reset 14))
           (/
            (text "ミツコを尋問すれば、事件の背後で彼女達を操っていた黒幕の存在がわかるはずだ。千葉なんぞにはもう用はない。")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 62 #t))
         (nop@)
         (text "ナナがミツコと落ち合う約束をしたのは、東京と千葉を結ぶ地下鉄の中。そこに行けば、ミツコを捕らえる事が出来るだろう。")
         (wait)
         (text-reset 14))
        (//
         (? (= 61 #t))
         (nop@)
         (text "ナナはエイプリルやレイファと違って、ただの元兵士。拷問すれば簡単に口を割りそうだ‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 67 #t))
         (text "コフィン宿か‥‥‥確かにナナが潜伏するには都合がいいだろう。千葉の中でもあまり知られていない場所だ。")
         (wait)
         (text-reset 14))
        (//
         (? (= 66 #t))
         (nop@)
         (text "アンナに言われて、のこのこやって来たけど‥‥‥アンナはモリイに何をしたのだろう？")
         (wait)
         (text-reset 14))
        (//
         (? (= 65 #t))
         (nop@)
         (branch-index
          (</>
           (/
            (text "モリイはナナとミツコの事を知っている‥‥‥しかし、口を割らせるのは難しそうだ。")
            (wait)
            (text-reset 14)
            (text "千葉に、他にアテがある訳ではない、何とかしてモリイからふたりの行方を聞き出さなければならない‥‥‥")
            (wait)
            (text-reset 14))
           (/
            (text "モリイはナナとミツコの事を、何か知っているようだ。そうでなくても、千葉で情報を得る事が出来るだろう‥‥‥")
            (wait)
            (text-reset 14)))))
        (//
         (branch-index
          (</>
           (/
            (text "エイプリルとレイファから聞き出した話だと、彼女達をスカウトしたのは、元軍部高官の秘書だったミツコらしい。")
            (wait)
            (text-reset 14)
            (text "そして、ミツコとナナは恋人同士だった。ふたりが一緒に千葉に潜伏しているという話は、まんざら嘘ではなさそうだ。")
            (wait)
            (text-reset 14)
            (text "次にわたしがすべき事は、ナナとミツコを捕まえる事だ。ふたりはこの街に潜んでいる。")
            (wait)
            (text-reset 14))
           (/
            (text "ナナとミツコがこの街の何処かに居るのは間違いない。問題はどうやってふたりを見つけるかだ。")
            (wait)
            (text-reset 14)
            (text "わたしは、この街では全くの部外者。誰かの協力を得られない限りどうする事も出来ないだろう‥‥‥")
            (wait)
            (text-reset 14)))))))
   (proc 1))
 (seg*))