(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 3072 0)
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b08_02.gpc")
  (image-mem 0 3)
  (proc 3)
  (if (</>
       (//
        (? (= P 3))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_03.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_03v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3)))))
       (// (nop@))))
  (load-mem "clm¥b08_02.clm" 32768)
  (text-frame 10 312 70 383)
  (text "コフィン宿の中は、ハニカム構造のアルミ板のように、小さな壁で仕切られた小部屋が左右に続いている。")
  (wait)
  (text-reset 14)
  (text "まるで蜂の巣の中にいるような錯覚を覚えながら、ひとつの部屋の中に入ると、女が寝ている。")
  (wait)
  (text-reset 14)
  (text "この女がナナに違いない。首の後ろあたりから出た配線が壁につながり、彼女自身の頭の中にトリップしているのがわかる。")
  (wait)
  (text-reset 14)
  (text "つまり、意識が無い訳だ。こんな状態の人間を相手にした事は、未だかつて経験した事がない。")
  (wait)
  (text-reset 14)
  (text "まあ、これなら逃げられる心配は無いが‥‥‥")
  (wait)
  (text-reset 14)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 85 #t) (= 87 #t) (= 89 #t))
   (if (</>
        (//
         (? (= P 7))
         (sound '|| 2)
         (delay 50)
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_07.uso")
               (sound '|| 3)
               (nop@)
               (set-var P 7))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_07v.uso")
               (sound '|| 3)
               (nop@)
               (set-var P 7)))))
        (// (nop@))))
   (proc 0)
   (text "じっとナナの顔を眺めていても、楽しくも何ともない。とはいえ、ソフトウェアの女とファックするのもお断わり。")
   (wait)
   (text-reset 14)
   (text "という事は、やるべき事はひとつしかない。ナナを情報部に連行する前に、少しお楽しみの先払いをもらう事にしよう。")
   (wait)
   (text-reset 14)
   (text "わたしは、ナナの後頭部からモジュールを引き抜いた‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "うっ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "お目覚めかい、お姫様！")
   (wait)
   (text-reset 14)
   (image-file "gpc¥b08_03.gpc")
   (image-mem 0 3)
   (proc 3)
   (text "「Nana」" 'br)
   (text "なっ、何すんだよバカ。こんな事してどうなるかわかってんの！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "はん、淫売がえらそうな口を聞くじゃない。あんたが眠ってる間に薄汚い野郎どもが、あんたのお道具で何をしてたと思ってるの？")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "ちょっと‥‥‥やめなさいよ。誰か‥‥‥誰か来てよ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "生憎だね、誰も来やしないよ。それに、あんたはもうお終いだよ。")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "えっ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "うまく隠れたつもりだろうが、逃げ果せようったって無理な話さ。あんたを逮捕する。")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "そ、それじゃ‥‥‥軍の！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "当たり。あんたを連れてく前にちょっと楽しませてもらうよ。")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "いっ、嫌よ‥‥‥何すんのよっ、薄汚い手で触んないで、あんたなんかに触られたくないわ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ニッキーやブリジッタは、そんな口の聞き方はしないだろう？")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "嫌だって‥‥‥んッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あら、意外と敏感じゃない。下衆野郎どもにやられまくって不感症になっちまったと思ったのに。")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "そ、そこ‥‥‥駄目、触っちゃ駄目ッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "こんな所で働いてるわりにゃ、ここは奇麗なまんまだ。可愛いねぇ貝みたいにパックリ口を開いてる。")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "放して‥‥‥あッ、あんッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そんなに感じてちゃ、わたしを満足させる前にまいっちまうよ。それでよく娼婦が勤まるもんだね。")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "そっ、そんな‥‥‥嫌ぁッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "白い肌だね。この肌にムチの傷が‥‥‥さぞかし奇麗だろうね。後でたっぷり楽しませてもらう。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それに、知ってる事を洗いざらい吐くんだ。軍のデータベースから盗んだ物をどうしたか。誰に頼まれてやったのかをね！")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "うっ、んッ‥‥‥はぁ、はぁ、はぁ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたのお友達は先に天国で待ってるよ。あんたも味わってみたいだろう、至上の悦楽ってやつをさ。")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "嫌ぁ‥‥‥そんなの嫌よ、もう駄目ッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ミツコにされるより気持ちいいかい？")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "しっ、知らないわ‥‥‥そんな女、知らない。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "嘘を言うんじゃないよ。")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "あぁッ！　いっ、痛ッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ミツコにされるより気持ちいいかって聞いてるんだよ。")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "うっ‥‥‥んッ。き、気持ちいいです‥‥‥ああァッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "いい子だ。それじゃ、ご褒美にいかせてあげるよ。")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "んっ、んっ、んっ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "だ、駄目‥‥‥そこ！")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "あッ、ああァァッ！")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "いっ、いい加減に‥‥‥放せッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "おっと、まだ抵抗する力が残ってたの。")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "冗談じゃないわ、あんたにされるぐらいなら死んだ方がマシよッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "嫌われたもんだね、荒事は避けようと思ったけど‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1)
   (nop@)
   (set-reg 68 #t)
   (exec-mem 3072 0)
   (mes-jump "mes¥MC_C01.MES"))
 (seg (? (= S 1) (= 85 #f))
   (proc 0)
   (text "眠っているようにも見えるが、叩いても抓っても目を覚まさないだろう事は間違いない。")
   (wait)
   (text-reset 14)
   (text "首の後ろから出た配線の先、ホストコンピュータにつながり、彼女の脳の中に既製品の情報を送り込んでいる。")
   (wait)
   (text-reset 14)
   (text "意識が無い分、他の売春行為より楽なのだろう。寝てる間にお道具がすり減るだけで、セックスをしている感覚さえ無いのだ。")
   (wait)
   (text-reset 14)
   (text "罪の意識も、嫌悪感もなし。他に稼ぐあてが無いナナにとって、これ以上はない仕事だ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 85 #t)
   (proc 1))
 (seg (? (= S 1) (= 85 #t))
   (proc 0)
   (text "眠っているようにも見えるが、叩いても抓っても目を覚まさないであろう事は間違いない。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 86 #f))
   (proc 0)
   (text "白人らしい肉感的な体。何も身に纏っていないが、それを恥ずかしがる様子はない。")
   (wait)
   (text-reset 14)
   (text "まだ２０代の前半と思われる白い肌には、張りがあり染みのひとつも見つけられない。控え目に言っても美少女の部類に入るだろう。")
   (wait)
   (text-reset 14)
   (text "これだけの容姿ならば、そこいらの街頭に立つ娼婦より金を稼げるのは間違いない。")
   (wait)
   (text-reset 14)
   (text "しかし残念ながらこの電脳セックスでは、女はただのハードウェアにすぎない。容姿はそれほど問題ではないのだ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 86 #t)
   (proc 1))
 (seg (? (= S 2) (= 87 #f))
   (proc 0)
   (text "ナナは裸体を隠そうともせず、狭苦しい部屋に横たわっている。若くまだ少女の面影を残した体は、娼婦にするには惜しい。")
   (wait)
   (text-reset 14)
   (text "本物の女とのセックスに恐れを抱き、ソフトウェアの女とファックするような下衆な野郎が相手では、なおさらだ。")
   (wait)
   (text-reset 14)
   (text "エイプリルとレイファから聞いた話では、ナナはミツコの恋人だ。つまり、レズビアンという訳。")
   (wait)
   (text-reset 14)
   (text "こんな事をさせておくのは、ますます勿体ない。わたしの嗜好にも合致している。ナナの尋問は楽しい事になりそうだ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 87 #t)
   (proc 1))
 (seg (? (= S 2) (= 87 #t))
   (proc 0)
   (text "ナナは裸体を隠そうともせず、狭苦しい部屋に横たわっている。若くまだ少女の面影を残した体は、娼婦にするには惜しい。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 88 #f))
   (proc 0)
   (text "部屋の壁に貼ってある注意書には、『モジュールを抜かない事』と書かれている。")
   (wait)
   (text-reset 14)
   (text "カウンターの男が言っていた事を思い出す。確か、急にモジュールを抜くとまずい事になると言っていたようだ‥‥‥")
   (wait)
   (text-reset 14)
   (text "眠っているというより、仮死状態に近い昏睡にある女が、急に目を覚ますという事だろう。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 88 #t)
   (proc 1))
 (seg (? (= S 3) (= 89 #f))
   (proc 0)
   (text "壁の注意書によれば、急にモジュールを抜くとまずい事になるらしい。モジュールというのは、女の首の後ろから出ている物だろう。")
   (wait)
   (text-reset 14)
   (text "壁に伸びている、ハーネスのようなコードの束だ。女はそのコードでホストコンピュータとつながっているらしいな‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 89 #t)
   (proc 1))
 (seg (? (= S 3) (= 89 #t))
   (proc 0)
   (text "壁の注意書によれば、急にモジュールを抜くとまずい事になるらしい。モジュールというのは、女の首の後ろから出ている物だろう。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4))
   (proc 0)
   (branch-index
    (</>
     (/
      (text "ナナは深い眠りの中にあるようで、逃げ出す事はおろか、わたしに抵抗する事さえ出来ないだろう。")
      (wait)
      (text-reset 14)
      (text "確かに仕事はやりやすいが、無抵抗すぎても興ざめというものだ。抵抗する女を、嬲りながら組み敷くのが楽しいのだから‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "ナナを連れ出した後の事は、全てモリイに任せてある。あの女に任せれば、何の心配もないだろう。")
      (wait)
      (text-reset 14)
      (text "あまりに呆気なくて、退屈な気さえする。わたしにとって任務とはお楽しみの一部なのだから‥‥‥")
      (wait)
      (text-reset 14))
     (/ (text "ナナはあまりにも無抵抗すぎて、ただ捕まえるだけでは退屈このうえない。") (wait) (text-reset 14))))
   (proc 1)))