(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b08_01.gpc")
  (image-mem 0 3)
  (proc 3)
  (if (</>
       (//
        (? (= P 3))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_03.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_03v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3)))))
       (// (nop@))))
  (load-mem "clm¥b08_01.clm" 32768)
  (text-frame 10 312 70 383)
  (text "モリイに聞いたとおり、千葉のメインストリートの先にあるコフィン宿に入った。")
  (wait)
  (text-reset 14)
  (text "コフィン宿とは、外見は旅行客用の安宿の体裁を持っているが、その実ヤクの取り引きや娼婦の為に使われる物のようだ。")
  (wait)
  (text-reset 14)
  (text "カウンターには、いかつい体つきをした外人の男が座っている。どうやら用心棒も兼ねているらしい‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Man at the counter」" 'br)
  (text "らっしゃい。あんた見ねえ顔だけど、初めてかい？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "まあね。思ってたよりまともな所だな。")
  (wait)
  (text-reset 14)
  (text "「Man at the counter」" 'br)
  (text "そりゃどうも。何をお望みで？　部屋かね、それとも‥‥‥")
  (wait)
  (text-reset 14)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 424 #t))
   (proc 0)
   (text "「Man at the counter」" 'br)
   (text "焦らなくても女の子は逃げやしないぜ。どのソフトでジャムるのか選びなよ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 420 #t) (= 423 #t))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "ところで、エリーって子はどの子なの？")
   (wait)
   (text-reset 14)
   (text "「Man at the counter」" 'br)
   (text "エリー？　それは本物の女の名前だぜ。そこに貼ってあるのはホロスターのニッキーにブリジッタ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Man at the counter」" 'br)
   (text "あんた、本当にシステムを理解してるのか？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あ、ああ‥‥‥そうだった。実際にやるのは初めてなんだよ。評判を聞いてね、試してみたかったんだ。")
   (wait)
   (text-reset 14)
   (text "「Man at the counter」" 'br)
   (text "だったら最初から言いなよ。ウチのシステムは、そこのホロからお好みのソフトを選んで、そいつを女の子に転送するから‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Man at the counter」" 'br)
   (text "ソケット付きの女の子とジャムってもらう。その子は完璧にあんたのお好みどおり。ニッキーでもブリジッタでも。")
   (wait)
   (text-reset 14)
   (text "「Man at the counter」" 'br)
   (text "あっちの具合から喘ぎ声まで、完璧なコピーだ。有名なスターとよろしく出来るって訳だな。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ああ、わかってる。思い出したよ。ところでエリーは‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Man at the counter」" 'br)
   (text "エリーがいいって言うなら、エリーを回してやるけどよ、余計な事はしないでくれよな。")
   (wait)
   (text-reset 14)
   (text "「Man at the counter」" 'br)
   (text "システムとリンクしてる時は、女の方は意識がねえ。急にソケットを抜くとマズイんだ。生身の女とヤりたきゃ他に行きなよ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わかってる、早く部屋に案内しなよ。")
   (wait)
   (text-reset 14)
   (text "「Man at the counter」" 'br)
   (text "本当にわかってんのかね‥‥‥どのソフトにするか選びな。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 424 #t)
   (proc 1))
 (seg (? (= S 1) (= 420 #f))
   (proc 0)
   (text "「Man at the counter」" 'br)
   (text "あんたこの辺の人間じゃねえだろう、見ねえ顔だもんな。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "まあね‥‥‥外の人間がここに来るのは珍しい？")
   (wait)
   (text-reset 14)
   (text "「Man at the counter」" 'br)
   (text "そうでもねえけどな、ここじゃ他所じゃねえお愉しみもあるし。ところであんたサツじゃねえだろうな。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "千葉の人間が警察を恐れるなんて、意外だった。")
   (wait)
   (text-reset 14)
   (text "「Man at the counter」" 'br)
   (text "その格好は何でえ、フザけた事すると生きて帰れねえぜ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "安心しなよ、こいつはわたしの趣味でね。あんたに迷惑はかけないからさ。")
   (wait)
   (text-reset 14)
   (text "「Man at the counter」" 'br)
   (text "それならいいがな‥‥‥姉さん、そいつは過激すぎるファッションだぜ。さぞかし腕に覚えがあるんだろうな。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それはそうと、特別なお愉しみってヤツ。わたしもそいつが目当てなんだけどね。")
   (wait)
   (text-reset 14)
   (text "「Man at the counter」" 'br)
   (text "そこのホロで選びな。どれでも好きな子が空いてるぜ‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 420 #t)
   (proc 1))
 (seg (? (= S 1) (= 420 #t))
   (proc 0)
   (text "「Man at the counter」" 'br)
   (text "そこのホロで選びな。どれでも好きな子が空いてるぜ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 421 #f))
   (proc 0)
   (text "男は２メートルを超える長身。横幅もそれに劣らない堂々としたものだ。常軌を逸した筋肉はウエイトトレーニングで得たものか？")
   (wait)
   (text-reset 14)
   (text "とてつもない威圧感だが、実戦向きではない。にしても、上腕部の太さはわたしの頭よりもあるだろう。")
   (wait)
   (text-reset 14)
   (text "負ける気はしないが、あまり敵に回したくない相手だ。それ程好戦的でないのが有難い‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 421 #t)
   (proc 1))
 (seg (? (= S 2) (= 422 #f))
   (proc 0)
   (text "自分の筋肉を誇示するように、ぴったり体に張り付いたシャツを着ている。シャツは今にも破けそうだ。")
   (wait)
   (text-reset 14)
   (text "そのシャツの上に着たオーバーオールといい、薄く化粧した顔といい、かなり奇異に見える‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 422 #t)
   (proc 1))
 (seg (? (= S 2) (= 422 #t))
   (proc 0)
   (text "男は２メートルを超える長身。横幅もそれに劣らない堂々としたものだ。常軌を逸した筋肉はウエイトトレーニングで得たものか？")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 423 #f))
   (proc 0)
   (text "女が裸で悩ましいポーズをとった、ホロが貼ってある。いずれもかなりの美人だが、人工的な匂いが感じられる。")
   (wait)
   (text-reset 14)
   (text "おそらく、ポッドモッドで美しさを得たに違いない。どの顔もみな同じに見える。それに、どこかで見た顔ばかりだ‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 423 #t)
   (proc 1))
 (seg (? (= S 3) (= 423 #t) (= 424 #f))
   (proc 0)
   (text "裸の女のホロだ。しかし、それほど卑猥な感じはしない。むしろ、それぞれの美しさを際立たせるのが目的のホロのようだ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 424 #t))
   (proc 0)
   (text "わたしの知らない間に、セックスも複雑になったもんだ。これは言わば電脳セックスってヤツ。")
   (wait)
   (text-reset 14)
   (text "生身の女をハードウエアにして、ゲームを遊ぶようなものだ。いい悪いは別として、わたし好みでないのは間違いない。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "この、右上のホロは‥‥‥いいね、そそるじゃない。")
   (wait)
   (text-reset 14)
   (text "「Man at the counter」" 'br)
   (text "それはニッキーだ、最新のソフトだぜ。ニッキーは可愛い顔で男を狂わせる。俺も試したけどお薦めだね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それじゃ、これにしとく。金は先払いかい？")
   (wait)
   (text-reset 14)
   (text "「Man at the counter」" 'br)
   (text "後でいい。どうせこの建物からは逃げられねえしな。エリーはと、一番奥の左側の部屋だ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "もうエリーはニッキーになっちまってるの？")
   (wait)
   (text-reset 14)
   (text "「Man at the counter」" 'br)
   (text "あんたが服を脱ぎ終わった頃にな。どっちみち意識はねえ。眠ってるみたいなもんさ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "女にとっては、その方が楽かもしれない。ちょっと眠ってる間に、客が勝手に済ませてくれるんだから。")
   (wait)
   (text-reset 14)
   (text "「Man at the counter」" 'br)
   (text "まあな‥‥‥この仕事は脳に配線してる女の特権だな。ヤッてる最中は夢でも見てるんだろうさ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "なるほどね‥‥‥いろいろとありがとうよ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 425 #t)
   (proc 1)
   (exec-mem 3072 0)
   (mes-jump "mes¥MB_G01A.MES"))
 (seg (? (= S 4) (= 426 #f))
   (proc 0)
   (text "カウンターの奥は、ごく普通の安ホテルと何等変わる所はない。ここが千葉だと感じさせるニューテクとは一切無関係のようだ。")
   (wait)
   (text-reset 14)
   (text "それどころか、わたしの見る限り電子機器だと思えるような物は一切存在しない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 426 #t)
   (proc 1))
 (seg (? (= S 4) (= 427 #f))
   (proc 0)
   (text "異常なほど巨大な男の体に隠れて、店の奥はほとんど見る事が出来ない。一見しただけでは、どんな店なのかもわからない程だ。")
   (wait)
   (text-reset 14)
   (text "そこはかとなく漂う胡散臭さはあるものの、ヤクの取り引きや売春行為を匂わせる様子は感じられない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 427 #t)
   (proc 1))
 (seg (? (= S 4) (= 427 #t))
   (proc 0)
   (text "カウンターの奥は、ごく普通の安ホテルと何等変わる所はない。ここが千葉だと感じさせるニューテクとは一切無関係のようだ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5))
   (proc 0)
   (if (</>
        (//
         (? (= 424 #t))
         (nop@)
         (text "モリイが言った、自分で確かめろという事は、こういう意味だったのか。確かに電脳セックスなど千葉以外ではお目にかかれない。")
         (wait)
         (text-reset 14)
         (text "脳に配線したナナがハッカー以外に自分の能力を生かすには、この仕事をするしかなかったのだろうか‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 422 #t))
         (nop@)
         (text "壁に貼った女のホロは、このコフィン宿が売春宿である証拠なのだろうか。この中にナナの写真が‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 420 #t))
         (text "この男は、見掛けほど悪い男ではないようだ。筋肉のかたまりのような体も相手を威圧する為に鍛えた訳ではないようだし‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (text "ここがモリイに教えられたコフィン宿か。確かに怪しい雰囲気はあるが、一瞥しただけではよくわからない。")
         (wait)
         (text-reset 14)
         (text "ナナを見つけるには、目の前のこの男の助けが必要かも。何とかして店の中まで入り込まなければ。")
         (wait)
         (text-reset 14))))
   (proc 1)))