(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b10_01.gpc")
  (image-mem 0 3)
  (image-file "gpc¥b10_01a.gpc")
  (image-mem 1 0)
  (proc 3)
  (if (</>
       (//
        (? (= P 4))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_04.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 4))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_04v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 4)))))
       (// (nop@))))
  (load-mem "clm¥b10_01.clm" 32768)
  (text-frame 10 312 70 383)
  (text "わたしは、サカタ・ジクムント　ユニバーサル　ネオテクの社長室にやって来た。")
  (wait)
  (text-reset 14)
  (text "ここは、我々の住む地下都市よりさらに地下にある。不思議と圧迫感が無いのは、部屋の堅牢な造りのせいか‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Sakata」" 'br)
  (text "君が情報部から来た少佐かね？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "そうです。お手数をかけてしまって‥‥‥申し訳ありません。")
  (wait)
  (text-reset 14)
  (text "「Sakata」" 'br)
  (text "我が社に敵国のスパイが潜入したという事だが‥‥‥ここ数ヶ月の間に、新しく採用した人間はいない。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Sakata」" 'br)
  (text "さらに過去に遡る事は出来るが、あまり意味が無いだろう。知っての通り、我が社は軍とも取り引きがある。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "存じております。")
  (wait)
  (text-reset 14)
  (text "「Sakata」" 'br)
  (text "社員の採用には、特別に注意を払っているのだが‥‥‥")
  (wait)
  (text-reset 14)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 484 #f) (= 482 #f))
   (proc 0)
   (text "「Sakata」" 'br)
   (text "何かの間違いではないかね。もしもそれが本当ならば、我が社は信用を失う事になりかねない。")
   (wait)
   (text-reset 14)
   (text "坂田は物静かな調子で淡々と話す。とてもザイバツを代表する男とは思えない。もっと尊大な感じかと思ったが。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "情報部の調べでは確かに間違いありませんね、残念ですが。簡単には信じられない事でしょうが‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "信用しない訳ではないが、そういう事実は無いのだ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "そのスパイは何をしたのだね。大体、そんなに簡単に外部の人間が入り込めるものなのかね？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そう、スパイと言うより‥‥‥国賊と言うべきでしょうか。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "国賊とは？　一体何をしたのだ、その者は。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "軍のデータベースに手を加えた者がいます。あるデータが奪われ、機密を盗んだ犯人は逮捕されましたが‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "軍の機密とは、それは一体‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ある機構＝システムに関する情報だと聞いています。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "それは、まさか‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 482 #t)
   (proc 1))
 (seg (? (= S 1) (= 484 #f) (= 483 #f))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "坂田さん、お嬢様がいらっしゃいますね。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "それがどうした！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "実は、わたしは軍の機密を盗んだ犯人を逮捕した当人でして。厳しい尋問をしたところ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "スパイとか何とか口実をつけて、それが目的か。誰の企みか知らんが、サカタ・ネオテクを陥れようという策略だろう！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしはただの公僕です。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "我が社は無関係だ。大体、その機構＝システムを創ったのは、我が社なのだ。盗んで何になると言うのだ。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "娘が何だと言うのだ。混血なのがそんなに悪いのか。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "混血ですって‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "白々しい。確かに娘はドイツ人とのハーフだ。しかし、その妻も死んで久しい。人目を避けて静かに暮らしていたものを！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "なるほど、そういう事か。サカタ社とドイツのジクムント社の合弁の為に、政略結婚したのね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "エリコはその時に産まれた‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "知らなかったのか。それでは、本当に？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしは情報を盗んだ犯人を尋問しただけ。あなたのお嬢さんがその事件に関っていた事を白状したのよ。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "‥‥‥‥‥‥‥‥‥エリコが？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしの上官が、わたしをここに送り込んだ訳がわかったわ。娘があなたの弱みって訳ね。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "困るのだ‥‥‥その件が公になれば、サカタ・ネオテクの信用問題になりかねん。昔の話を蒸し返されるのもだ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それは娘さんに聞いてみないと、何とも言えませんね。ある軍の高官秘書で、ミツコという名前に覚えはありません？")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "確かに聞き覚えのある名前だが‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "どうやら、娘さんと接触を持ったのはその女のようです。何を言ってそそのかしたのか知りませんけど‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "どのみち、娘さんが事件に関っていたのは間違いない。その女を拷問して聞き出したのですから。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "それで、サカタ・ネオテクをどうするつもりだ‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 483 #t)
   (proc 1))
 (seg (? (= S 1) (= 484 #f) (= 483 #t) (= 490 #f))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "わたしはただ、任務を遂行したいだけでね。娘さんを、エリコを引き渡しなさい。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "しかし、本当にエリコが犯人だとしたら、サカタ・ネオテクの名が公にならない訳がない。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "日本の行く末を左右するザイバツがそんな事になったら‥‥‥君はその事をどう思っているのかね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "どうでもいい‥‥‥とは言えないね。わたしの上官からも言われてるし。高度に政治的な問題になりかねないってね。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "だからよく考えてみるべきだと言っている。エリコひとりの為に、サカタ・ネオテクの名前を汚す訳にはいかないのだ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "でも、お嬢さんが事件に関っていた事は間違いないんだ。黙殺する訳にはいかない。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "エリコを情報部に渡したら‥‥‥どうなる？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "軍部も協力者を失いたくはないでしょう。それ以上どうにかなるって事はないと思うけど。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あなたがエリコに命じて、機密を盗ませたのでないならね。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "わかった、娘を引き渡そう‥‥‥エリコを社長室へ。")
   (wait)
   (text-reset 14)
   (text "つまり、エリコはサカタ・ネオテクのために捨て石にされた訳だ。坂田が事件に関っていない事は、間違いないだろうか？")
   (wait)
   (text-reset 14)
   (text "そんな事をしても何のメリットも無い。サカタ・ネオテクなら軍部に引き渡したのと同じ物を、もう一度造る事も可能だろう。")
   (wait)
   (text-reset 14)
   (image-file "gpc¥b10_01b.gpc")
   (image-mem 1 0)
   (text "「Sakata」" 'br)
   (text "娘のエリコだ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "お父さん、この人だれなの？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "はじめまして、お嬢さん。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 490 #t)
   (proc 1))
 (seg (? (= S 1) (= 484 #f) (= 490 #t))
   (proc 0)
   (text "「Sakata」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 490 #t) (= 485 #t) (= 487 #t))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "誰かに頼まれたの？　あんたは彼女達に何をしてやったの。")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "しらないったら、ほんとにしらないもの！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "強情な子だ。本当に痛い目にあいたいの？")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたのした事は立派な犯罪。それも一生刑務所で暮らさなきゃならないくらいの重い罪なんだよ。")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "そ、そんな‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "何でミツコ達に協力した。金に困ってた訳じゃない。父親やそんな奴らに反抗したつもりだったのかい？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ミツコとあんたが顔見知りだってのは、知ってるんだ。ミツコに頼まれて嫌だとは言えなかったか？")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "しらないってば！　ミツコなんてしらない。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そうかい。それじゃ、ちょっと怖い目にあってもらおうか。情報部に連行する。もうお父さんは助けちゃくれないよ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 69 #t)
   (proc 1)
   (exec-mem 3072 0)
   (mes-jump "mes¥MA_A05.MES"))
 (seg (? (= S 2) (= 484 #f) (= 490 #t))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "奇麗なお嬢さんね、こんな所に閉じこめておくのは惜しいくらい。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "だれなの、あなた。どうしてそんな服を着てるの？")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "エリコ！　静かにしなさい。その人はお前に話があるそうだ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "話ね。物は言い様だわ。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "例の件、本当に確実なんだろうな‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "大丈夫でしょう、きっとね。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "それでは困る！　こちらの事情も理解してほしい。そんな事になれば、我が社だけの問題では済まないのだ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしの上官に伝えておくわ、坂田は娘を売った代償に、ザイバツを守ったってね。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "おい！　そんな言い方をするな。我が社は本当にその事件には関与していない。そんな事をしても何の得も無いのだから。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "娘さんとふたりだけで話したいわ。")
   (wait)
   (text-reset 14)
   (text "「Sakata」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (exec-mem 256 "I")
   (exec-mem 256 "A 1")
   (image-file "gpc¥b10_01.gpc")
   (image-mem 0 0)
   (exec-mem 256 "G 0 35 121 10 66")
   (exec-mem 256 "A 0")
   (exec-mem 256 "P 0 35 121")
   (exec-mem 256 "E")
   (text "「Eriko」" 'br)
   (text "お父さん‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "甘ったれるのもいい加減にしな。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたを護ってくれる人はもう誰もいないのよ。酷い事だとは思うけどね、こうなったのも自業自得さ。")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 484 #t)
   (proc 1))
 (seg (? (= S 2) (= 485 #f) (= 490 #t))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "あんたのお友達は、皆捕まったよ。")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "おともだち？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "エイプリル、レイファ、ナナ、ミツコ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "そ、そんなのうそ‥‥‥みんなどうなっちゃったの？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それはもうすぐわかる。あんたも皆と同じ所に行く事になるんだからね。")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "それなら大丈夫だわ。みんながわたしを護ってくれるもの。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そいつはどうかね。ところで、あんたはどうして軍の機密を盗んだりしたんだい？")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "何も言わないつもりかい。そいつは、あんたの為にならないと思うけどね。")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "な、何もしらない！　お父さんはどこなの？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "お父さんはね、あんたを売ったんだよ。自分の会社や家族を護る為に、あんたを好きにしていいってね！")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "そんなのうそよ‥‥‥そんなの信じない。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それじゃ、お父さんを呼んでみな。誰も来やしないよ！")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "そんな‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 485 #t)
   (proc 1))
 (seg (? (= S 2) (= 485 #t) (= 490 #t))
   (proc 0)
   (text "「Eriko」" 'br)
   (text "何もしらないもん、お父さんを呼んで！")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 490 #t) (= 483 #t) (= 486 #f))
   (proc 0)
   (text "エリコの豊かな金髪と白い肌は、死んだ母親ゆずりなのだろう。それが為に、人目を気にして生きる事になるとは‥‥‥")
   (wait)
   (text-reset 14)
   (text "元はと言えば、ザイバツが勢力を拡大する為の政略結婚で産まれた娘だ。世が世なら下にも置かれぬ存在だっただろうに。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 486 #t)
   (proc 1))
 (seg (? (= S 3) (= 490 #t) (= 487 #f))
   (proc 0)
   (text "エリコは見慣れないわたしの姿を見て、不安になっているようだ。やはり後ろ暗いところがあるのだろうか。")
   (wait)
   (text-reset 14)
   (text "それとも、わたしの姿はエリコに恐怖を抱かせるほど奇異な格好なのか‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 487 #t)
   (proc 1))
 (seg (? (= S 3) (= 490 #f) (= 487 #t))
   (proc 0)
   (text "エリコの豊かな金髪と白い肌は、死んだ母親ゆずりなのだろう。それが為に、人目を気にして生きる事になるとは‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 488 #f))
   (proc 0)
   (text "坂田の座った椅子と机は、日本を代表するザイバツの長が使用するに相応しい、今では貴重になった木で出来ている。")
   (wait)
   (text-reset 14)
   (text "地下都市では、良質の家具に使えるような大木は育たないし、外に取りに行く訳にもいかない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 488 #t)
   (proc 1))
 (seg (? (= S 4) (= 488 #t))
   (proc 0)
   (text "坂田の座った椅子と机は、日本を代表するザイバツの長が使用するに相応しい、今では貴重になった木で出来ている。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 489 #f))
   (proc 0)
   (text "わたしには誰が描いた物なのか、どれほどの価値があるのかさえわからない。西洋の絵画なのはわかるが‥‥‥")
   (wait)
   (text-reset 14)
   (text "日本を代表するザイバツの長が選んだ物だ、相応の価値があるのだろう。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 489 #t)
   (proc 1))
 (seg (? (= S 5) (= 489 #t))
   (proc 0)
   (text "わたしには誰が描いた物なのか、どれほどの価値があるのかさえわからない。西洋の絵画なのはわかるが‥‥‥")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 6))
   (proc 0)
   (if (</>
        (//
         (? (= 485 #t) (= 487 #t))
         (nop@)
         (text "このままでは埒があかない、エリコを拷問するしかないようだ。ザイバツの娘だからといって、手心を加えるつもりはない。")
         (wait)
         (text-reset 14)
         (text "むしろ、どんな恥態を見せてくれるか楽しみなくらいだ。エリコの生い立ちを考えると、可哀想だと思わない訳ではないが‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 484 #t))
         (nop@)
         (text "坂田は、自分のザイバツを危険にするぐらいなら、エリコを売る事を選ぶのが当たり前だと言わんばかりだ。")
         (wait)
         (text-reset 14)
         (text "長い伝統を持ったザイバツが自分の代で終わるなど、坂田には考えられない事なのだろう‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 483 #t))
         (nop@)
         (text "血縁を重んじるザイバツの中で、エリコのような混血児が居るのはさぞかし具合が悪かったろう。")
         (wait)
         (text-reset 14)
         (text "エリコは家族の中でも厄介者だったはずだ。人目を避けて育てたのもそのせいだ。")
         (wait)
         (text-reset 14))
        (//
         (text "わたしの拷問を受けて、ミツコが嘘をつける訳はないだろう。エリコがミツコ達に唆されて、彼女達に協力したのは間違いない。")
         (wait)
         (text-reset 14)
         (text "問題は、坂田にその事をどうやって切り出すかだ。アンナと加藤は坂田の娘、エリコに何か問題があるような事を言っていた‥‥‥")
         (wait)
         (text-reset 14))))
   (proc 1))
 (seg (? (= S 1) (= 484 #t))
   (proc 0)
   (if (</>
        (//
         (? (= 485 #t) (= 487 #t))
         (nop@)
         (text "このままでは埒があかない、エリコを拷問するしかないようだ。ザイバツの娘だからといって、手心を加えるつもりはない。")
         (wait)
         (text-reset 14)
         (text "むしろ、どんな恥態を見せてくれるか楽しみなくらいだ。エリコの生い立ちを考えると、可哀想だと思わない訳ではないが‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 484 #t))
         (nop@)
         (text "坂田は、自分のザイバツを危険にするぐらいなら、エリコを売る事を選ぶのが当たり前だと言わんばかりだ。")
         (wait)
         (text-reset 14)
         (text "長い伝統を持ったザイバツが自分の代で終わるなど、坂田には考えられない事なのだろう‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 483 #t))
         (nop@)
         (text "血縁を重んじるザイバツの中で、エリコのような混血児が居るのはさぞかし具合が悪かったろう。")
         (wait)
         (text-reset 14)
         (text "エリコは家族の中でも厄介者だったはずだ。人目を避けて育てたのもそのせいだ。")
         (wait)
         (text-reset 14))
        (//
         (text "わたしの拷問を受けて、ミツコが嘘をつける訳はないだろう。エリコがミツコ達に唆されて、彼女達に協力したのは間違いない。")
         (wait)
         (text-reset 14)
         (text "問題は、坂田にその事をどうやって切り出すかだ。アンナと加藤は坂田の娘、エリコに何か問題があるような事を言っていた‥‥‥")
         (wait)
         (text-reset 14))))
   (proc 1))
 (seg (? (= S 2) (= 489 #f))
   (proc 0)
   (if (</>
        (//
         (? (= 485 #t) (= 487 #t))
         (nop@)
         (text "このままでは埒があかない、エリコを拷問するしかないようだ。ザイバツの娘だからといって、手心を加えるつもりはない。")
         (wait)
         (text-reset 14)
         (text "むしろ、どんな恥態を見せてくれるか楽しみなくらいだ。エリコの生い立ちを考えると、可哀想だと思わない訳ではないが‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 484 #t))
         (nop@)
         (text "坂田は、自分のザイバツを危険にするぐらいなら、エリコを売る事を選ぶのが当たり前だと言わんばかりだ。")
         (wait)
         (text-reset 14)
         (text "長い伝統を持ったザイバツが自分の代で終わるなど、坂田には考えられない事なのだろう‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 483 #t))
         (nop@)
         (text "血縁を重んじるザイバツの中で、エリコのような混血児が居るのはさぞかし具合が悪かったろう。")
         (wait)
         (text-reset 14)
         (text "エリコは家族の中でも厄介者だったはずだ。人目を避けて育てたのもそのせいだ。")
         (wait)
         (text-reset 14))
        (//
         (text "わたしの拷問を受けて、ミツコが嘘をつける訳はないだろう。エリコがミツコ達に唆されて、彼女達に協力したのは間違いない。")
         (wait)
         (text-reset 14)
         (text "問題は、坂田にその事をどうやって切り出すかだ。アンナと加藤は坂田の娘、エリコに何か問題があるような事を言っていた‥‥‥")
         (wait)
         (text-reset 14))))
   (proc 1))
 (seg (? (= S 3) (= 489 #f))
   (proc 0)
   (if (</>
        (//
         (? (= 485 #t) (= 487 #t))
         (nop@)
         (text "このままでは埒があかない、エリコを拷問するしかないようだ。ザイバツの娘だからといって、手心を加えるつもりはない。")
         (wait)
         (text-reset 14)
         (text "むしろ、どんな恥態を見せてくれるか楽しみなくらいだ。エリコの生い立ちを考えると、可哀想だと思わない訳ではないが‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 484 #t))
         (nop@)
         (text "坂田は、自分のザイバツを危険にするぐらいなら、エリコを売る事を選ぶのが当たり前だと言わんばかりだ。")
         (wait)
         (text-reset 14)
         (text "長い伝統を持ったザイバツが自分の代で終わるなど、坂田には考えられない事なのだろう‥‥‥")
         (wait)
         (text-reset 14))
        (//
         (? (= 483 #t))
         (nop@)
         (text "血縁を重んじるザイバツの中で、エリコのような混血児が居るのはさぞかし具合が悪かったろう。")
         (wait)
         (text-reset 14)
         (text "エリコは家族の中でも厄介者だったはずだ。人目を避けて育てたのもそのせいだ。")
         (wait)
         (text-reset 14))
        (//
         (text "わたしの拷問を受けて、ミツコが嘘をつける訳はないだろう。エリコがミツコ達に唆されて、彼女達に協力したのは間違いない。")
         (wait)
         (text-reset 14)
         (text "問題は、坂田にその事をどうやって切り出すかだ。アンナと加藤は坂田の娘、エリコに何か問題があるような事を言っていた‥‥‥")
         (wait)
         (text-reset 14))))
   (proc 1)))