(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b09_01.gpc")
  (image-mem 0 3)
  (proc 3)
  (if (</>
       (//
        (? (= P 6))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_06.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 6))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_06v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 6)))))
       (// (nop@))))
  (load-mem "clm¥b09_01.clm" 32768)
  (text-frame 10 312 70 383)
  (text "わたしは、東京と千葉を結ぶ地下鉄の車内に居た。千葉の駅を出たばかりとあって、客はそれほど多くない。")
  (wait)
  (text-reset 14)
  (text "しかし、乗客のほとんどが素性の知れない怪しげな連中で、それも列車から客を遠ざける理由のようだ。")
  (wait)
  (text-reset 14)
  (text "薄暗い室内は人の汗と排泄物の臭いがし、床のそこここが黒く変色している。普通の人間なら、５分と我慢出来ないだろう。")
  (wait)
  (text-reset 14)
  (text "わたしは、少ない客の中から、ミツコの姿を探そうとあたりを見回した。ミツコは純粋な日本人。見れば一目でわかるだろう。")
  (wait)
  (text-reset 14)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (>= S 1) (= 499 #t))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "あんた、ミツコだろう？")
   (wait)
   (text-reset 14)
   (image-file "gpc¥b09_02b.gpc")
   (image-mem 1 0)
   (text "「Mitsuko」" 'br)
   (text "えっ‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "やっぱりそうだった。わたしの勘も捨てたもんじゃないね。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "あなたは‥‥‥誰ですか。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたのお友達の知り合い。ナナとこの地下鉄で待ち合わせしてたんだろ？　そのお友達から伝言だ。今日は会えないとさ。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "まさかあなた、軍の‥‥‥それじゃ、ナナは！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "おっと、動かない方がいい。可哀想に、そんなにやつれて。あんたはタフじゃないんだよ。逃亡生活なんて似合わないよ。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "薄汚い‥‥‥軍の飼犬のクセに！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そっちもご同様さ、昔はね。あんたの元上司がどうなったか教えてやろうか。軍を免職させられたよ、全部おしまい。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "今じゃ部屋で猫と居眠りしてる、何処にでもいる老人さ。嘘じゃないよ。情報部は彼を監視してるんだ。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "‥‥‥‥‥‥‥あの人は何もしてないわ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "関係ない。良心が痛まないかい？　一人の男の地位もキャリアも、全部奪い取っちまったんだよ、あんたのせいさ。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "そんな話は聞きたくない！　ナナに何をしたの、ここで待ち合わせしているのを知ってるのはあの子だけなのに！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "動くなって言ってるだろう？　情報部でゆっくり聞かせてもらう。あんたがどんな役割をしてて、機密をどうしたのか。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "安心しな、他のお仲間も一緒だよ。全部喋っちまえば痛い目にもあわずに済む。もっとも、前に捕まった時よりは辛いだろうけど。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "何をするつもりなの‥‥‥私を拷問するのね？　聞いた事があるわ情報部にはそれ専門の人がいるって事を。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "たっぷり可愛がってやるよ。あんたの心得さえ良けりゃ、それほど苦痛は無い。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "くっ‥‥‥お、お断わりよ！　情報部になんて行かないわ！")
   (wait)
   (text-reset 14)
   (proc 1)
   (exec-mem 3072 0)
   (mes-jump "mes¥MC_D01.MES"))
 (seg (? (= S 1) (= 492 #f))
   (proc 0)
   (text "こんな物騒な地下鉄の車内で眠る事が出来るというのは、一種の才能と言えるのではないだろうか。")
   (wait)
   (text-reset 14)
   (text "それとも、自分も他の連中と同じくらい怪しくて暴力的な人間だと誇示しているつもりなのだろうか‥‥‥")
   (wait)
   (text-reset 14)
   (text "どちらにしても、こんな車内で眠るなど、わたしには到底出来ない芸当だ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 492 #t)
   (proc 1))
 (seg (? (= S 1) (= 493 #f))
   (proc 0)
   (text "左の女は‥‥‥日本人と言えばそう見えない事はないが、薄汚れた既製品の服は、ミツコが身に着けそうな品ではない。")
   (wait)
   (text-reset 14)
   (text "物騒な車内で堂々と眠りこける大胆さも、わたしが連想するミツコとは異なる。逃亡後にそういう強かさを会得した可能性もあるが。")
   (wait)
   (text-reset 14)
   (text "一応はこの女も候補に入れておこう。ミツコの顔を知らない以上、第一印象で決めてしまう訳にもいかないのだから‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 493 #t)
   (proc 1))
 (seg (? (= S 1) (= 493 #t))
   (proc 0)
   (text "左の女は‥‥‥日本人と言えばそう見えない事はないが、薄汚れた既製品の服は、ミツコが身に着けそうな品ではない。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 494 #f))
   (proc 0)
   (text "うす汚いジーンズと、同じくらい汚れたジャケットを着ている。それほど危険な人間には見えないが、千葉の住人に違いない。")
   (wait)
   (text-reset 14)
   (text "さして力がありそうでもなく、顔にも神経質そうな印象がある。賃仕事で生計を立てているようには見えない‥‥‥")
   (wait)
   (text-reset 14)
   (text "とすると知的労働に従事しているのだろうか。ハッカーか、もっと危険な仕事をする男なのだろうか？")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 494 #t)
   (proc 1))
 (seg (? (= S 2) (= 495 #f))
   (proc 0)
   (text "体は筋肉質でもなく、痩せて上背もあまりない。しかし、ミツコが男装しているようには見えない。")
   (wait)
   (text-reset 14)
   (text "この男は全く無関係な人物だ。しかし、車内で物騒な事に邪魔が入るのは面倒だ。一応、注意を払っておこう。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 495 #t)
   (proc 1))
 (seg (? (= S 2) (= 495 #t))
   (proc 0)
   (text "うす汚いジーンズと、同じくらい汚れたジャケットを着ている。それほど危険な人間には見えないが、千葉の住人に違いない。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 496 #f))
   (proc 0)
   (text "古風なパンクファッションに身を包んだ男は、意外と年を取っているように見える。")
   (wait)
   (text-reset 14)
   (text "マトリクスやサイバースペースの模様を描いた、奇抜な服装を見た事はあるが、パンクは今では落ち目だ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 496 #t)
   (proc 1))
 (seg (? (= S 3) (= 496 #t))
   (proc 0)
   (text "古風なパンクファッションに身を包んだ男は、意外と年を取っているように見える。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 493 #t) (= 495 #t) (= 496 #t) (= 498 #t))
   (proc 0)
   (text "わたしが想像するミツコの姿に当てはまる人間は、車内ではどうやらあの女だけのようだ。")
   (wait)
   (text-reset 14)
   (text "目の前に立っているパンク野郎が目障りだが、そんな事を恐れている場合ではない。")
   (wait)
   (text-reset 14)
   (text "近づいてみるか‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
   (image-file "gpc¥b09_02.gpc")
   (image-mem 0 3)
   (proc 3)
   (text "眠っているのだろうか、女は静かにうつむいて座っている。服装は薄汚れているが、安物ではない。")
   (wait)
   (text-reset 14)
   (text "奇抜な形の帽子からはみ出した髪は、黒檀の色。細く尖った顎も、日本人のそれと言えば、そう見えない事もない。")
   (wait)
   (text-reset 14)
   (text "瞳の色は見えないが‥‥‥‥‥‥その顔は知的で、千葉に通じる地下鉄の車内には不相応だ。")
   (wait)
   (text-reset 14)
   (text "おそらく、この女がミツコに違いない。ひどく疲れ果てた様子で、こけた頬も逃亡生活の辛さを物語っているようだ。")
   (wait)
   (text-reset 14)
   (text "純粋な日本人、軍部高官の秘書。何不自由ない生活をしていたに違いない。自らの変わりように自分でも驚いているはずだ。")
   (wait)
   (text-reset 14)
   (text "むしろ、わたしに捕まる事を望んでいるかも。逃亡生活はどう考えても彼女向きではない‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "ミツコが囚人達を集め、それぞれに仕事を指示したのは他の囚人の自白で明らかだ。")
   (wait)
   (text-reset 14)
   (text "ミツコを尋問すれば、全てがわかるはずだ‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 499 #t))
 (seg (? (= S 4) (= 498 #f))
   (proc 0)
   (text "女は、この地下鉄の車内では比較的まともな服装で、うつむいた格好で座っている。")
   (wait)
   (text-reset 14)
   (text "もしかすると、眠っているのかもしれない。ここからでは詳しくその様子を知る事は出来ない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 498 #t)
   (proc 1))
 (seg (? (= S 4) (= 498 #t))
   (proc 0)
   (text "女は、この地下鉄の車内では比較的まともな服装で、うつむいた格好で座っている。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 497 #f))
   (proc 0)
   (text "窓の外では黒ずんだコンクリートの壁が、尋常でない速度で背後に飛んで行く。")
   (wait)
   (text-reset 14)
   (text "密閉されたパイプの中を走る当世風の鉄道とは違い、この地下鉄は昔ながらのレール上を走るタイプだ、事故の確率は高い。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 497 #t)
   (proc 1))
 (seg (? (= S 5) (= 497 #t))
   (proc 0)
   (text "窓の外では黒ずんだコンクリートの壁が、尋常でない速度で背後に飛んで行く。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 6))
   (proc 0)
   (branch-index
    (</>
     (/
      (text "ナナはこの地下鉄の車内でミツコと待ち合わせていた。この車両の中にミツコが居るのは間違いないが‥‥‥")
      (wait)
      (text-reset 14)
      (text "それらしい人物が居るだろうか、何しろわたしはミツコの顔を知らない。勘に頼るしかないのだ。")
      (wait)
      (text-reset 14))
     (/
      (text "まだ乗客の数はそれ程ではないが、東京に近づくにつれて人の数が増えるはずだ。早く見つけなければ‥‥‥")
      (wait)
      (text-reset 14))
     (/ (text "この中にミツコらしい人物がいるだろうか‥‥‥") (wait) (text-reset 14))))
   (proc 1)))