(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (exec-mem 256 "E")
  (exec-mem 9504 "I")
  (exec-mem 9504 "M M96")
  (exec-mem 9504 "L gpc¥b11_01b1.gpc,KEEP")
  (exec-mem 9504 "L gpc¥b11_01b2.gpc,KEEP")
  (exec-mem 9504 "L gpc¥b11_01b3.gpc,KEEP")
  (exec-mem 9504 "L gpc¥b11_01b4.gpc,KEEP")
  (exec-mem 9504 "L gpc¥b11_01b5.gpc,KEEP")
  (exec-mem 9504 "L gpc¥b11_01c1.gpc,KEEP")
  (exec-mem 9504 "L gpc¥b11_01c2.gpc,KEEP")
  (exec-mem 9504 "L gpc¥b11_01c3.gpc,KEEP")
  (exec-mem 9504 "L gpc¥b11_01c4.gpc,KEEP")
  (exec-mem 9504 "L gpc¥b11_01c5.gpc,KEEP")
  (exec-mem 9504 "L gpc¥b11_01a.gpc,KEEP")
  (exec-mem 9504 "L gpc¥b11_01.gpc,KEEP")
  (exec-mem 9504 "C gpc¥b11_01.gpc,GPC")
  (image-mem 0 3)
  (exec-mem 9504 "C gpc¥b11_01a.gpc,GPC")
  (image-mem 1 0)
  (exec-mem 9504 "L gpc¥shotwaku.gpc,KEEP")
  (proc 3)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= P 6))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_06.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 6))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_06v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 6)))))
       (// (nop@))))
  (load-mem "clm¥b11_01.clm" 32768)
  (text "「プリス」" 'br)
  (text "情報部の人間が公安部にやって来るなんて、珍しいね。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "それは知らなかった。わたしはあんまり雑用はやらないんだ。公安どころか、軍部にさえ行かない。")
  (wait)
  (text-reset 14)
  (text "「プリス」" 'br)
  (text "それで済むのなら結構な事だわ。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "それはそうと、いつもそんな派手な格好で勤務してるの？")
  (wait)
  (text-reset 14)
  (text "「プリス」" 'br)
  (text "まあね。私もあなた同様、あまり雑用はしないから。この場合雑用というのは外回りの事だけど。")
  (wait)
  (text-reset 14)
  (text "「プリス」" 'br)
  (text "納得してもらえたかしら？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "まあね。わたしも他人の好みをどうこう言える人間じゃないし。")
  (wait)
  (text-reset 14)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 508 #t))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "情報部の内通者が誰なのかは後で確かめるとして、その前にあんたを逮捕させてもらう。")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "出来るかしら、あなたにそれが？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "元特殊部隊とだって、渡りあった事があるんだよ。いくら叩き上げの猛者だからって、簡単に勝てるとは思わないでよね。")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "大したものね、尊敬に値するわ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "馬鹿にしやがって‥‥‥")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "そういう訳ではないのだけど‥‥‥そろそろ種明かしをしてあげましょうか。いつまで黙ってるのも意地が悪いし。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "なんだって‥‥‥")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "いいわよ、出て来なさい。")
   (wait)
   (text-reset 14)
   (exec-mem 256 "I")
   (mes-load? "mes¥bnkcpy2.mec" 0)
   (mes-load? 0)
   (exec-mem 256 "A 1")
   (exec-mem 9504 "C gpc¥b11_01b1.gpc,GPC")
   (image-mem 1 0)
   (exec-mem 9504 "C gpc¥b11_01b2.gpc,GPC")
   (image-mem 1 0)
   (exec-mem 9504 "C gpc¥b11_01b3.gpc,GPC")
   (image-mem 1 0)
   (exec-mem 9504 "C gpc¥b11_01b4.gpc,GPC")
   (image-mem 1 0)
   (exec-mem 9504 "C gpc¥b11_01b5.gpc,GPC")
   (image-mem 1 0)
   (exec-mem 9504 "C gpc¥b11_01a.gpc,GPC")
   (image-mem 1 0)
   (exec-mem 256 "G 0 12 16 56 136")
   (exec-mem 256 "A 0")
   (exec-mem 256 "P 0 12 16")
   (exec-mem 256 "F 0")
   (exec-mem 256 "A 1")
   (exec-mem 256 "G 1 12 151 56 136")
   (exec-mem 256 "A 0")
   (exec-mem 256 "P 1 12 151")
   (exec-mem 256 "E")
   (text "「エイプリル」" 'br)
   (text "また会ったね、姉さん‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "この前は油断してたけど、今度はそうはいかないね。")
   (wait)
   (text-reset 14)
   (text "「エリコ」" 'br)
   (text "このひと、恐い‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「エイプリル」" 'br)
   (text "恐がんなくても大丈夫さ、あんたはうしろに隠れてな。")
   (wait)
   (text-reset 14)
   (text "「ナナ」" 'br)
   (text "よくもミツコに酷い事したね、かたきは取らせてもらうから！")
   (wait)
   (text-reset 14)
   (text "「ミツコ」" 'br)
   (text "世の中って、こんなふうになってるのよ。いつでも風向きがいいとは限らないって訳ね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "なるほどね、全員ここに隠れてたって訳。")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "しかもあなたには不都合な事に、このビルの中には私達しか居ないのよ。撃ちあいになっても誰も来ないわ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "完全にはめられたって訳ね‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "私はこれで失礼するわ、あなたの屍体を処理する為にモルグの冷蔵庫を空けておかないと。")
   (wait)
   (text-reset 14)
   (text "「ナナ」" 'br)
   (text "もう一度、軍のデータベースをハッキングしなきゃ。あんたの記録を消去する為にね。")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "それじゃみんな。後は頼んだわよ。")
   (wait)
   (text-reset 14)
   (exec-mem 256 "I")
   (exec-mem 256 "A 1")
   (exec-mem 9504 "C gpc¥b11_01.gpc,GPC")
   (image-mem 0 0)
   (exec-mem 9504 "C gpc¥b11_01b1.gpc,GPC")
   (image-mem 1 0)
   (exec-mem 9504 "C gpc¥b11_01b2.gpc,GPC")
   (image-mem 1 0)
   (exec-mem 9504 "C gpc¥b11_01b3.gpc,GPC")
   (image-mem 1 0)
   (exec-mem 9504 "C gpc¥b11_01b4.gpc,GPC")
   (image-mem 1 0)
   (exec-mem 9504 "C gpc¥b11_01b5.gpc,GPC")
   (image-mem 1 0)
   (exec-mem 256 "G 0 12 16 56 136")
   (exec-mem 256 "A 0")
   (exec-mem 256 "P 0 12 16")
   (exec-mem 256 "F 0")
   (exec-mem 256 "A 1")
   (exec-mem 256 "G 1 12 151 56 136")
   (exec-mem 256 "A 0")
   (exec-mem 256 "P 1 12 151")
   (exec-mem 256 "E")
   (text "「Kiyomi」" 'br)
   (text "ちっ‥‥‥逃がすか！")
   (wait)
   (text-reset 14)
   (proc 1)
   (exec-mem 3072 0)
   (mes-jump "mes¥MC_F01.MES"))
 (seg (? (= S 1) (= 501 #t) (= 503 #t) (= 505 #t))
   (proc 0)
   (text "「プリス」" 'br)
   (text "そろそろ本題に入ったら？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "何の事かしら‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "情報部も落ちたものね、穴だらけよ。私の言ってる意味、わかる？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "さっぱりわからないね。")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "あなたが何しに来たかを、知ってるって言ってるのよ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "あなたが考えてる事を当ててみましょうか。今日あなたがここに来る事を知ってるのは、誰と誰か‥‥‥")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "あなたが今関ってる任務は、極秘だったわよね。何処で何をしているのか、知っている人間はそんなにいないんじゃない？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "どうやってこの場を切り抜けようかって考えてるでしょう？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それは、あんたが事件に関ってたって事を白状してる訳？")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "さあね、どうかしら‥‥‥あなたが死ねば、私の事を知っている人間はあとふたり。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "どっちかは裏切り者だろ、あとひとり。")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "とても魅力的な話ね。私だって苦労して手に入れたこの地位を失いたくはないわ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしを殺すっての？")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "さあね、どうしようかしら‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 508 #t)
   (proc 1))
 (seg (? (= S 1) (= 501 #f))
   (proc 0)
   (text "「Kiyomi」" 'br)
   (text "あんたのお国は何処だい、見たところ暑い地方のようだけど。")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "そう見えるのは、ご先祖にラテン民族の血が混じっているから。私自身は寒い国の出なのよ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それじゃ、その服は単純に趣味のせいか‥‥‥")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "ベリーダンサーにでも見えた？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "まあね、そんなとこ。あんたみたいな移民が、公安部で出世するのは、さぞかし大変だったろうね。")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "そうでもないわ。あなたの上司もそうでしょう？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "アンナの事？　まさか、知り合いだとか‥‥‥そう言えば、寒い国の出身だって言ってたね。")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "ええ、そう。私も白ロシア人なの。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それは‥‥‥‥‥‥奇遇だね。")
   (wait)
   (text-reset 14)
   (text "「プリス」" 'br)
   (text "そうね、偶然って恐ろしいものね。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 501 #t)
   (proc 1))
 (seg (? (= S 1) (= 501 #t))
   (proc 0)
   (text "「プリス」" 'br)
   (text "私もあなたの上司のアンナと同じ、白ロシア人なのよ。偶然って恐ろしいものね。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 502 #f))
   (proc 0)
   (text "大切な部分を隠す、最小限の布しか身に着けていない。露出した肌は白人という程白くはなく、きめも細かい。")
   (wait)
   (text-reset 14)
   (text "丸みを帯びた肉感的な身体は、スパニッシュ等のラテン系によく見られるものだ。")
   (wait)
   (text-reset 14)
   (text "プリスがどうやって秘密警察の幹部にまで登りつめたのか知らないが、獰猛な警察犬のようなタイプでないのは間違いない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 502 #t)
   (proc 1))
 (seg (? (= S 2) (= 503 #f))
   (proc 0)
   (text "自分の豊満な肉体を誇示するように、大切な部分を隠す最小限の布地しか身に着けていない。")
   (wait)
   (text-reset 14)
   (text "こんな格好をした公安部員が存在する事さえ信じられないが、それ以上に謎なのは、彼女が秘密警察の幹部だと言う事だ。")
   (wait)
   (text-reset 14)
   (text "公安部は軍よりずっとくだけていて、多少の事は大目にみるという事だろうか‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 503 #t)
   (proc 1))
 (seg (? (= S 2) (= 503 #t))
   (proc 0)
   (text "自分の豊満な肉体を誇示するように、大切な部分を隠す最小限の布地しか身に着けていない。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 504 #f))
   (proc 0)
   (text "一般の部員達がいる部屋とプリスの部屋を仕切る窓は、分厚い強化プラスティック製のようだ。")
   (wait)
   (text-reset 14)
   (text "おそらく、ただの樹脂性に見える壁も、実は積層構造だろう。鉄板やハードゲルを挟み込んだ防弾効果のある物に違いない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 504 #t)
   (proc 1))
 (seg (? (= S 3) (= 505 #f))
   (proc 0)
   (text "ブラインドで仕切られて、向こうの部屋の様子を知る事は出来ないが、この部屋に入るまで人の姿を見た覚えはない。")
   (wait)
   (text-reset 14)
   (text "週末という訳ではないし、時間もそれ程遅くはない。皆出払っているのだろうか‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 505 #t)
   (proc 1))
 (seg (? (= S 3) (= 505 #t))
   (proc 0)
   (text "一般の部員達がいる部屋と、プリスの部屋を仕切る窓は、分厚い強化プラスティック製のようだ。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 506 #f))
   (proc 0)
   (text "小さなモニターと薄型の端末がある。公安部なら軍のデータベースにも繋がっているはずだ。")
   (wait)
   (text-reset 14)
   (text "プリスがエイプリル達の仲間だとすれば、ナナがこのマシンを使ってハッキングをした可能性もある。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 506 #t)
   (proc 1))
 (seg (? (= S 4) (= 507 #f))
   (proc 0)
   (text "ひどく旧式の端末だ。しかし、ハッカーのナナが何らかの細工をしたとすれば、外見そのままの性能ではないだろう。")
   (wait)
   (text-reset 14)
   (text "ハッカー達は、このテの旧式マシンに高性能なＣＰＵや内蔵機器を使い、最新マシンに匹敵するスペックに改造するのが好きらしい。")
   (wait)
   (text-reset 14)
   (text "この端末が、そんな改造を施されている可能性もある。わたしにはそれを確かめる術もないが‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 507 #t)
   (proc 1))
 (seg (? (= S 4) (= 507 #t))
   (proc 0)
   (text "プリスがエイプリル達の仲間だとすれば、ナナがこのマシンを使ってハッキングをした可能性もある。")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5))
   (proc 0)
   (branch-index
    (</>
     (/
      (text "プリスは移民でありながら公安部の一部門、秘密警察の幹部にまで登りつめてしまった人物だ。")
      (wait)
      (text-reset 14)
      (text "同じ移民で情報部の将校になったアンナとは違い、公安部で幹部になる為には現場での地道な経験がなければならない。")
      (wait)
      (text-reset 14)
      (text "つまり、凶悪な殺人犯やもっと厄介な犯罪者と渡りあうだけの能力を持っているという事だ。")
      (wait)
      (text-reset 14))
     (/
      (text "内部の手引きで脱走したエイプリル達の事も、放っておく訳にはいかない。")
      (wait)
      (text-reset 14)
      (text "プリスを逮捕した後で、残りの５人も捕まえなければ。大変な仕事になりそうだ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "プリスの部屋まで来る間に、誰か人の姿を見たという覚えはない。安心して任務を遂行する事が出来そうだ。")
      (wait)
      (text-reset 14))))
   (proc 1)))