(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (nop@)
   (set-reg 980 #t)
   (set-reg 981 #t)
   (set-reg 982 #f)
   (set-reg 983 #f)
   (set-reg 984 #f)
   (set-reg 985 #f)
   (set-reg 986 #f)
   (set-reg 987 #f)
   (set-reg 988 #f)
   (set-reg 989 #f)
   (set-reg 990 #f)
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_00.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (if (</>
        (//
         (? (= P 8))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_08.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 8))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_08v.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 8)))))
        (// (nop@))))
   (exec-mem 256 "E")
   (load-mem "clm¥A1_00.clm" 32768)
   (load-mem "clm¥icon.clm" 20480)
   (mes-load? "mes¥icon_cl.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥icon_c2.mec" 0)
   (mes-load? 0)
   (text-frame 10 312 70 370)
   (exec-mem 256 "A 0")
   (proc 12)
   (set-var H 0)
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "白状しちまうなら今のうちだよ。わざわざ痛い目にあわなくってもいいだろう。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それともあんた、そういうのが趣味なの？")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "ふ、ふん‥‥‥勝手な事ばっかり言って！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "声が震えてるじゃないの。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "冗談じゃないわ、こっちはプロなんだからね。簡単に口を割るなんて思わないでよねっ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "威勢のいい事だ。それじゃ楽しませてもらおうか‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "何しろわたしは、こういうのが大好きでね。あんたみたいな小生意気な女がヒイヒイ泣き叫ぶ姿を見るのがね！")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "異常者よ‥‥‥あんた狂ってる。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "何とでも言いな、忠告はしてやったんだ。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "こ、こっちに来るな！　あたしに触るなっ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "さて、まずは何でいたぶってやろうか。この鞭は丹念に革をなめして、たっぷり油を染み込ませたんだ。剃刀みたいな切れ味だよ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "こっちのロッドはすごく重い。これで叩かれたら、骨が折れちまうかもしれないね。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "言葉もないって？　それじゃ、そろそろ始めようか‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (exec-mem 256 "P 5 6 0")
   (loop
    (set-var S 0)
    (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
    (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (= Z 1) (= 991 #f))
   (proc 0)
   (exec-mem 256 "P 5 71 0")
   (nop@)
   (set-reg 991 #t)
   (exec-mem 256 "P 8 6 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 71 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 71 40))))
   (load-mem "clm¥icon2.clm" 20480)
   (proc 1))
 (seg (? (= Z 1) (= 991 #t))
   (proc 0)
   (exec-mem 256 "P 5 6 0")
   (nop@)
   (set-reg 991 #f)
   (exec-mem 256 "P 9 71 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 6 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 6 40))))
   (load-mem "clm¥icon.clm" 20480)
   (proc 1))
 (seg (? (= Z 2) (= 991 #f))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #f))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Z 2) (= 991 #t))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #t))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Y 1) (= S 1) (<= H 3))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "さあ、これが最後のチャンスだ。痛い目にあう前に洗いざらい吐いちまいな！")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "だ、誰が‥‥‥仲間を裏切るなんて、死んでも嫌だね！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そうかい、それじゃこのロッドで死ぬほど痛めつけてやるよ！")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "くっ‥‥‥こ、このサディスト！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "最高の誉め言葉だね、ゾクゾクしてくる。")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "狂ってる‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "これからが本当にいいところさ。まさか、もうお終いだなんて言わないよね。あんたはもっと悦ばせてくれるだろう？")
      (wait)
      (text-reset 14))
     (/
      (text "「Kiyomi」" 'br)
      (text "まさかもうお終いだなんて言わないよね。あんたはもっと悦ばせてくれるだろう？")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 6))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "くっくっくっ‥‥‥いい声で鳴くじゃないか。")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "うッ‥‥‥も、もう許して。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "許してほしかったら、全部吐いちまうこった。あんたのお仲間の事とか、盗んだ機密をどうしたかって事をね！")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "知らないんだってば‥‥‥本当に何も知らないのよォ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "殴られるのがそんなに好き？　お望みなら、身体中アザだらけにしてあげるよ。")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "ひっ‥‥‥‥‥‥そ、そんな！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "もうちょっと苛めてやった方がいいわね、同じ仲間を裏切るにしても、ぎりぎりまで耐えた方が罪の意識がないものね。")
      (wait)
      (text-reset 14))
     (/
      (text "「Kiyomi」" 'br)
      (text "もうちょっと苛めてやった方がいいわね、同じ仲間を裏切るにしても、ぎりぎりまで耐えた方が罪の意識がないものね。")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 7))
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "そろそろ喋りたくなってきたかい？")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "ペッ！　お断わりだね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "馬鹿な女だ‥‥‥早く喋っちまえば、それだけ苦痛が少なくてすむのに。もっとも、わたしのお楽しみがなくなって残念だけどね。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたが馬鹿で頑固な女でよかった。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "そ、そんな‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "今さら後悔しても遅い。どうやって嬲ってやろう、考えるだけで楽しくなってくるね！")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "な、何するつもりなのよ。よして、触らないで！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "まずは、その邪魔な服を脱がせないとね。ロッドの効き目が落ちるし第一、その格好は鑑賞に堪えない。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "やっ、やめろ‥‥‥触るなッ！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 18688 3)
   (exec-mem 18688 5 1 0)
   (exec-mem 3072 0)
   (mes-jump "mes¥MD_A02.MES"))
 (seg (? (= Y 1) (= S 2))
   (sound 'se 1)
   (if (</>
        (//
         (? (>= H 5) (= 548 #f))
         (proc 0)
         (image-file "gpc¥a1_00a.gpc")
         (image-mem 1 0)
         (nop@)
         (set-reg 548 #t)
         (image-file "gpc¥a1_00ba.gpc")
         (image-mem 1 0)
         (proc 12))
        (//
         (proc 0)
         (image-file "gpc¥a1_00ba.gpc")
         (image-mem 1 0)
         (proc 12))))
   (proc 10)
   (branch-reg
    541
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (text "「April」" 'br)
      (text "ひッ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "おっと、危なく顔に傷をつけるところだった。")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "お、お願い‥‥‥顔だけは！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "元特殊部隊でも、顔に傷がつくのは堪えられないって？")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "安心しな、顔だけは勘弁してやる。このロッドで顔を叩いたらとても見られたもんじゃないご面相になっちまうからね！")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "あ、あんたキ×ガイよ‥‥‥まともじゃないわ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 541 #t)
      (set-reg 548 #f))
     (/
      (text "「April」" 'br)
      (text "いっ、嫌ッ‥‥‥顔だけは！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 548 #f))))
   (proc 11))
 (seg (? (= Y 1) (= S 3))
   (sound 'se 1)
   (branch-reg
    542
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (if (</>
           (//
            (? (>= H 3) (= 548 #f))
            (proc 0)
            (image-file "gpc¥a1_00bb.gpc")
            (image-mem 1 0)
            (image-file "gpc¥a1_00a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 548 #t)
            (proc 12))
           (//
            (proc 0)
            (image-file "gpc¥a1_00bb.gpc")
            (image-mem 1 0)
            (proc 12))))
      (proc 10)
      (text "「April」" 'br)
      (text "痛ッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ちっ、その服は厚すぎる。これじゃロッドの効果が半減するよ。")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "こ、この変態‥‥‥いい加減にしろッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "かと言って、力を入れりゃ骨が折れちまうしね。わたしとしては、そうなる前に白状した方がいいと忠告しとく。")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 542 #t))
     (/
      (proc 10)
      (text "「Kiyomi」" 'br)
      (text "まだまだこんなもんじゃないよ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 4))
   (sound 'se 1)
   (branch-reg
    543
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (if (</>
           (//
            (? (>= H 3) (= 548 #f))
            (proc 0)
            (image-file "gpc¥a1_00bc.gpc")
            (image-mem 1 0)
            (image-file "gpc¥a1_00a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 548 #t)
            (proc 12))
           (//
            (proc 0)
            (image-file "gpc¥a1_00bc.gpc")
            (image-mem 1 0)
            (proc 12))))
      (proc 10)
      (text "「Kiyomi」" 'br)
      (text "いい音だ。何度聴いてもわくわくする‥‥‥もう降参するかい？")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "誰が‥‥‥あんたなんかに負けるかッ！")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "威勢がよくて結構だ。いつまで続くか試してみようか？")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 543 #t))
     (/
      (proc 10)
      (text "「Kiyomi」" 'br)
      (text "避けられるもんなら、避けてみな！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 5))
   (sound 'se 1)
   (branch-reg
    544
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (if (</>
           (//
            (? (>= H 3) (= 548 #f))
            (proc 0)
            (image-file "gpc¥a1_00a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 548 #t)
            (image-file "gpc¥a1_00bd.gpc")
            (image-mem 1 0)
            (proc 12))
           (//
            (proc 0)
            (image-file "gpc¥a1_00bd.gpc")
            (image-mem 1 0)
            (proc 12))))
      (proc 10)
      (text "「Kiyomi」" 'br)
      (text "あんまり効いてないみたいだね‥‥‥痛いかい？")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "い、痛いに決まってるでしょ‥‥‥うッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "もっと強くしてやろうか、段々気持ちよくなってくるだろう？")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 544 #t))
     (/
      (proc 10)
      (text "「April」" 'br)
      (text "ひッ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 6))
   (sound 'se 1)
   (branch-reg
    545
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (if (</>
           (//
            (? (>= H 3) (= 548 #f))
            (proc 0)
            (image-file "gpc¥a1_00a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 548 #t)
            (image-file "gpc¥a1_00be.gpc")
            (image-mem 1 0)
            (proc 12))
           (//
            (proc 0)
            (image-file "gpc¥a1_00be.gpc")
            (image-mem 1 0)
            (proc 12))))
      (proc 10)
      (text "「April」" 'br)
      (text "うッ‥‥‥ど、どうしてあたしがこんなッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "まだそんな事を言ってるのかい、いい加減にしないとただじゃ済まさないよ！")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "くそッ、この借りは必ず返してやる‥‥‥絶対に！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "残念だけど、そうはならないね。あんたはもうお終いなんだから。")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 545 #t))
     (/
      (proc 10)
      (text "「April」" 'br)
      (text "あうッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 7))
   (sound 'se 1)
   (branch-reg
    546
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (if (</>
           (//
            (? (>= H 3) (= 548 #f))
            (proc 0)
            (image-file "gpc¥a1_00a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 548 #t)
            (image-file "gpc¥a1_00bf.gpc")
            (image-mem 1 0)
            (proc 12))
           (//
            (proc 0)
            (image-file "gpc¥a1_00bf.gpc")
            (image-mem 1 0)
            (proc 12))))
      (proc 10)
      (text "「April」" 'br)
      (text "いっ‥‥‥痛ッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "随分可愛いの着けてるじゃない、全然似合ってないけど。")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "酷い‥‥‥こんなのって、あんまりよ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "こっちも遊んでる訳じゃないからね、あんたの気持ちなんかに構っちゃいられないんだよ。")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 546 #t))
     (/
      (proc 10)
      (text "「April」" 'br)
      (text "あうッ‥‥‥‥‥‥痛っ。")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= S 8) (= Y 1))
   (sound 'se 1)
   (branch-reg
    547
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (if (</>
           (//
            (? (>= H 3) (= 548 #f))
            (proc 0)
            (image-file "gpc¥a1_00a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 548 #t)
            (image-file "gpc¥a1_00bg.gpc")
            (image-mem 1 0)
            (proc 12))
           (//
            (proc 0)
            (image-file "gpc¥a1_00bg.gpc")
            (image-mem 1 0)
            (proc 12))))
      (proc 10)
      (nop@)
      (set-reg 547 #t)
      (text "「April」" 'br)
      (text "あッ‥‥‥ああァッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "なかなかいい鳴き声だ。そうでなくっちゃ楽しくない。")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "ち、血が‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "元特殊部隊が血を見て驚いてちゃ、話しにならないね。それとも、自分の血と他人のとじゃ違うってのかい？")
      (wait)
      (text-reset 14))
     (/
      (proc 10)
      (text "「Kiyomi」" 'br)
      (text "もっと鳴きな、段々楽しくなってきたよ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 3))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "この鞭はね、丹念になめした革に油を染み込ませた物なんだ。剃刀よりも鋭く切れる。")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "そ、それで脅してるつもり？　全然怖くないわよ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "その割には声が震えてるみたいだけど？")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "この程度で音をあげられちゃ困るね、まだまだこれからさ。")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "このサディスト‥‥‥キ×ガイ！")
      (wait)
      (text-reset 14))
     (/
      (text "「Kiyomi」" 'br)
      (text "わくわくするね、あんたを相手にしてるとさ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 6))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「April」" 'br)
      (text "うッ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "まだ終わりにするつもりはないけど、一応聞いといてやる。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "他の仲間は何処に隠れてる、盗んだ機密は何処に隠したんだ。")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "な、何の事だかわからない‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そうこなくっちゃ。まだまだ楽しませてもらうからね。")
      (wait)
      (text-reset 14))
     (/
      (text "「April」" 'br)
      (text "な、何も喋らないよ‥‥‥絶対に！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 7))
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "そろそろ喋りたくなってきたかい？")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "ペッ！　お断わりだね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "馬鹿な女だ‥‥‥早く喋っちまえば、それだけ苦痛が少なくてすむのに。もっとも、わたしのお楽しみがなくなって残念だけどね。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたが馬鹿で頑固な女でよかった。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "そ、そんな‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "まずは、その邪魔な服を脱がせないとね。鞭の効き目が落ちるし、その格好は鑑賞に堪えない。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "くっ‥‥‥どれだけ嬲れば気が済むんだ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "さあね、それもあんた次第さ。こう見えてもわたしは優しい女なんだ。素直な子には何もしないんだけどね‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 18688 3)
   (exec-mem 18688 5 1 0)
   (exec-mem 3072 0)
   (mes-jump "mes¥MD_A02.MES"))
 (seg (? (= S 2) (= Y 2))
   (sound 'se 1)
   (branch-reg
    541
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (if (</>
           (//
            (? (>= H 5) (= 548 #f))
            (proc 0)
            (image-file "gpc¥a1_00a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 548 #t)
            (image-file "gpc¥a1_00ba.gpc")
            (image-mem 1 0)
            (proc 12))
           (//
            (proc 0)
            (image-file "gpc¥a1_00ba.gpc")
            (image-mem 1 0)
            (proc 12))))
      (proc 10)
      (nop@)
      (set-reg 541 #t)
      (set-reg 548 #f)
      (text "「April」" 'br)
      (text "ひッ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "危ないね、顔に当たるとこだった。")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "気をつけなよ。大事な顔に傷を付けたくはないだろう？")
      (wait)
      (text-reset 14))
     (/
      (proc 0)
      (image-file "gpc¥a1_00ba.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「April」" 'br)
      (text "かっ、顔だけは許して‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 548 #f))))
   (proc 11))
 (seg (? (= Y 2) (= S 3))
   (sound 'se 1)
   (branch-reg
    542
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (if (</>
           (//
            (? (>= H 3) (= 548 #f))
            (proc 0)
            (image-file "gpc¥a1_00a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 548 #t)
            (image-file "gpc¥a1_00bb.gpc")
            (image-mem 1 0)
            (proc 12))
           (//
            (proc 0)
            (image-file "gpc¥a1_00bb.gpc")
            (image-mem 1 0)
            (proc 12))))
      (proc 10)
      (text "「April」" 'br)
      (text "くッ！　こ、こんなの全然痛くないよッ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "お望みなら、もっと痛くしてやってもいいんだけど？")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "そ、そんな‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 542 #t))
     (/
      (proc 10)
      (text "「April」" 'br)
      (text "んッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 4))
   (sound 'se 1)
   (branch-reg
    543
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (if (</>
           (//
            (? (>= H 3) (= 548 #f))
            (proc 0)
            (image-file "gpc¥a1_00a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 548 #t)
            (image-file "gpc¥a1_00bc.gpc")
            (image-mem 1 0)
            (proc 12))
           (//
            (proc 0)
            (image-file "gpc¥a1_00bc.gpc")
            (image-mem 1 0)
            (proc 12))))
      (proc 10)
      (text "「April」" 'br)
      (text "くうッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "これでもまだ強がり言ってられるかい！")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "え、遠慮すんなよ。もっとやればいい‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 543 #t))
     (/
      (proc 10)
      (text "「April」" 'br)
      (text "あうッ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= S 5) (= Y 2))
   (sound 'se 1)
   (branch-reg
    544
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (if (</>
           (//
            (? (>= H 3) (= 548 #f))
            (proc 0)
            (image-file "gpc¥a1_00a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 548 #t)
            (image-file "gpc¥a1_00bd.gpc")
            (image-mem 1 0)
            (proc 12))
           (//
            (proc 0)
            (image-file "gpc¥a1_00bd.gpc")
            (image-mem 1 0)
            (proc 12))))
      (proc 10)
      (text "「April」" 'br)
      (text "うッ‥‥‥ぜ、全然効かないよッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "やせ我慢して。いつまでその我慢が続くかしらね。")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "あんたなんかに屈するもんか‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 544 #t))
     (/
      (proc 10)
      (text "「April」" 'br)
      (text "いッ、痛くなんてないわ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= S 6) (= Y 2))
   (sound 'se 1)
   (branch-reg
    545
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (if (</>
           (//
            (? (>= H 3) (= 548 #f))
            (proc 0)
            (image-file "gpc¥a1_00a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 548 #t)
            (image-file "gpc¥a1_00be.gpc")
            (image-mem 1 0)
            (proc 12))
           (//
            (proc 0)
            (image-file "gpc¥a1_00be.gpc")
            (image-mem 1 0)
            (proc 12))))
      (proc 10)
      (nop@)
      (set-reg 545 #t)
      (text "「Kiyomi」" 'br)
      (text "ちッ、服の上からじゃあまり効かないか‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "何をやったって無駄よ、絶対に喋らないわ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "はん、いつまで意地を張ってられるか楽しみだね！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 545 #t))
     (/
      (proc 10)
      (text "「April」" 'br)
      (text "あッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= S 7) (= Y 2))
   (sound 'se 1)
   (branch-reg
    546
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (if (</>
           (//
            (? (>= H 3) (= 548 #f))
            (proc 0)
            (image-file "gpc¥a1_00a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 548 #t)
            (image-file "gpc¥a1_00bf.gpc")
            (image-mem 1 0)
            (proc 12))
           (//
            (proc 0)
            (image-file "gpc¥a1_00bf.gpc")
            (image-mem 1 0)
            (proc 12))))
      (proc 10)
      (text "「April」" 'br)
      (text "きゃッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "可愛い声だこと。とても元特殊部隊とは思えないね。")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "大きなお世話よ‥‥‥わたしはあんたみたいな露出狂じゃないわ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 546 #t))
     (/
      (proc 10)
      (text "「Kiyomi」" 'br)
      (text "いっそ、服を全部引っ剥がしてやろうか！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= S 8) (= Y 2))
   (sound 'se 1)
   (branch-reg
    547
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (if (</>
           (//
            (? (>= H 3) (= 548 #f))
            (proc 0)
            (image-file "gpc¥a1_00bg.gpc")
            (image-mem 1 0)
            (image-file "gpc¥a1_00a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 548 #t)
            (proc 12))
           (//
            (proc 0)
            (image-file "gpc¥a1_00bg.gpc")
            (image-mem 1 0)
            (proc 12))))
      (proc 10)
      (text "「Kiyomi」" 'br)
      (text "いい音だ‥‥‥鞭が肌を裂く音がする！")
      (wait)
      (text-reset 14)
      (text "「April」" 'br)
      (text "く、狂ってるわ‥‥‥こんな事して、何が楽しいのよ。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "もっと鳴くんだ。ほら‥‥‥もっと鳴け！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 547 #t))
     (/
      (proc 10)
      (text "「April」" 'br)
      (text "あッ‥‥‥あうッ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg*))