(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (proc 5)
  (proc 15)
  (proc 10)
  (text "「Kiyomi」" 'br)
  (text "ナナから先払いで金をもらったって言ったけど、それじゃあんたとレイファは金の為に仲間に加わったのかい？")
  (wait)
  (text-reset 14)
  (text "「April」" 'br)
  (text "それは‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "言い難そうだね。わたしに隠し事が出来ると思ってるの？")
  (wait)
  (text-reset 14)
  (text "「April」" 'br)
  (text "そんな事思ってません！　ほ、本当です‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "まあいい、口があるのはお前だけじゃない。他の仲間からも有益な情報を得られるって事もあるだろう。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "それじゃ、盗んだ機密は何処に隠した。ナナはもう処分しちまったんじゃないだろうな？")
  (wait)
  (text-reset 14)
  (text "「April」" 'br)
  (text "わ、わかりません‥‥‥それはナナに聞いてみないと‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "だろうと思った。お前は、言わば肉体労働が担当だったんだろう？金を払って雇われた、ただの道具みたいなものだ。")
  (wait)
  (text-reset 14)
  (text "「April」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "それじゃ、最後に聞くけど‥‥‥")
  (wait)
  (text-reset 14)
  (if (</>
       (//
        (? (= 59 #f))
        (text "「Kiyomi」" 'br)
        (text "レイファは何処に隠れているんだ？")
        (wait)
        (text-reset 14)
        (text "「April」" 'br)
        (text "そ、それは‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "隠しても無駄だ。お前はもう裏切り者、自分の肉体的苦痛を和らげるために仲間を売った最低の屑なんだから。")
        (wait)
        (text-reset 14)
        (text "「April」" 'br)
        (text "チャイナタウンです‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "チャイナタウンはもう探した事がある。他に隠れていそうな場所は知らないの？")
        (wait)
        (text-reset 14)
        (text "「April」" 'br)
        (text "いえ、レイファは絶対にチャイナタウンに居るはずです。あの子は廃ビルの中をねぐらにしてました‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "チャイナタウンか‥‥‥そこまで言うんなら信じてやろう。")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "お前にもう用はない、せいぜい囚人生活を楽しみな。")
        (wait)
        (text-reset 14)
        (proc 11))
       (//
        (? (= 59 #t) (= 60 #f))
        (text "「Kiyomi」" 'br)
        (text "問題のナナは何処に隠れている？　それと、もうひとりの仲間の、ミツコってのは？")
        (wait)
        (text-reset 14)
        (text "「April」" 'br)
        (text "ナナは多分、千葉シティに隠れてると思います‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "千葉だって？　あそこは、か弱い女の子がひとりで生きていけるような所じゃない。")
        (wait)
        (text-reset 14)
        (text "「April」" 'br)
        (text "ナナはハッカーだから、あの街でなら職にあぶれるような事はないと思います。居心地もいいはずだし‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "そうか、千葉はニューテク野郎が集まる所だから、ハッカーの仕事もあるって訳か。それじゃミツコは？")
        (wait)
        (text-reset 14)
        (text "「April」" 'br)
        (text "多分、一緒だと思います‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "千葉シティか‥‥‥これ以上お前に聞く事はないようだな。せいぜい囚人生活を楽しんでな！")
        (wait)
        (text-reset 14))
       (//
        (? (= 59 #t) (= 60 #t))
        (proc 10)
        (text "「Kiyomi」" 'br)
        (text "その、問題のナナは何処に隠れている？　それと、もうひとりの仲間のミツコってのは？")
        (wait)
        (text-reset 14)
        (text "「April」" 'br)
        (text "ナナは多分、千葉シティに隠れてると思います‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "千葉だって？　あそこは、か弱い女の子がひとりで生きていけるような所じゃない。")
        (wait)
        (text-reset 14)
        (text "「April」" 'br)
        (text "ナナはハッカーだから、あの街でなら職にあぶれるような事はないと思います。居心地もいいはずだし‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "そうか、千葉はニューテク野郎が集まる所だから、ハッカーの仕事もあるって訳か。それじゃミツコは？")
        (wait)
        (text-reset 14)
        (text "「April」" 'br)
        (text "多分、一緒だと思います‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "レイファから聞いた話だと、ナナとミツコはレズビアンの恋人同士だったらしいね、それは本当かい。")
        (wait)
        (text-reset 14)
        (text "「April」" 'br)
        (text "はい、間違いなく‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "だとすれば一緒に隠れている可能性が高いな。千葉シティか‥‥‥お前にもう用はない、せいぜい囚人生活を楽しみな。")
        (wait)
        (text-reset 14)
        (proc 11))))
  (exec-mem 18688 3)
  (exec-mem 18688 5 1 0)
  (exec-mem 3072 0)
  (nop@)
  (set-reg 58 #t)
  ((cmd 209) 0 5)
  (image-file "gpc¥waku.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (nop@)
  (set-reg 938 #t)
  (define-proc 7
    (<>
     (exec-mem 3968 103)
     (exec-mem 3072 0)
     (exec-mem 25984 2 0)
     (sound 'se 2)))
  (exec-mem 9504 "E")
  (exec-mem 256 "I")
  (mes-jump "mes¥MA_A03.MES")))