(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_03.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (if (</>
        (//
         (? (= P 9))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_09.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 9))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_09v.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 9)))))
        (// (nop@))))
   (exec-mem 256 "E")
   (load-mem "clm¥A1_03.clm" 32768)
   (text-frame 10 312 70 370)
   (exec-mem 256 "I")
   (exec-mem 256 "A 0")
   (exec-mem 18688 5 1 0)
   (exec-mem 256 "G 0 33 240 21 160")
   (proc 10)
   (text "「April」" 'br)
   (text "なっ、何をするつもり？　こ、怖いわ、嫌よ‥‥‥近寄らないで！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わめくんじゃないよ、牝犬！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "お前はわたしに嘘をついてたね。あれだけ嬲ってやったのに、ものわかりの悪い女だ。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "も、申し訳ありません‥‥‥お、お許し下さい、ご主人様！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "もう聞き飽きたんだよ、お前のそのセリフは。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "お願いです！　もう二度と‥‥‥二度と嘘はつきませんから！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "安心しな、これ以上お前に何かをしようとは思わない。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "お前は牝奴隷にさえなれなかったって事さ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "ああ、そんな‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "軍隊からはドロップアウト、奴隷も失格。それじゃお前は、何の役に立つってんだい。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "もう一度だけ‥‥‥お願いです、もう一度だけ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "駄目だ。わたしはこれ以上失望したくないんでね。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしが欲しいのは、お前がその薄汚い＊＊＊の中に隠した軍部" 'br)
   (text "の機密だけ。それだけは取り返さなきゃならない。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "駄目ッ、これだけは‥‥‥ああ、止めて！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "傑作じゃないか。数十億って金がかかってる機密が、薄汚い淫売女の＊＊＊の中だなんて。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "臭い汁にまみれた機密を、わたしが手を突っ込んで取り出さなきゃならないなんてさ。最高の笑い話だ！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 587 #f))
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "この淫売。プリスにはどんなご褒美をもらったんだい、わたしの鞭よりも気持ちよかったのか？")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "そ、そんな事してません‥‥‥本当です！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "嘘をつくんじゃないよ、牝犬。お前が本当に欲しかったのは金じゃなくて、ご褒美だったんだろう。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "お前は牝犬だ。誰にでも尻尾を振ってお強請りする本当の牝犬よ！塀の中に入っても、愛想振りまいて可愛がってもらうんだね。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 587 #t)
   (proc 11))
 (seg (? (= S 1) (= 587 #t))
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "お前みたいな淫売の牝犬は、顔を見るだけでうんざりだ。")
   (wait)
   (text-reset 14)
   (proc 11))
 (seg (? (= S 2) (= 588 #f))
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "乳首をこんなにおっ立てて、何を期待してるんだい。お前を悦ばせてやる気なんて、全然ないんだよ。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "なっ、何も‥‥‥期待なんてしてないわ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "心にもない事を言うんじゃないよ、この牝犬。乳首を苛めて欲しくて仕方ないんだろう。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "でも駄目だ。二度とそんな事はしてやらない。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "お前は牝奴隷にさえなれなかった、本物のクズだ。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 588 #t)
   (proc 11))
 (seg (? (= S 2) (= 588 #t))
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "お前は牝奴隷にさえなれなかった、本物のクズだ。")
   (wait)
   (text-reset 14)
   (proc 11))
 (seg (? (= S 3) (= 589 #f))
   (proc 10)
   (text "「April」" 'br)
   (text "ひッ‥‥‥つ、冷たい！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしの手が冷たいって？　そうだろうさ、お前等クズの為に寒い街を何時間もうろつく羽目になったんだからね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "余計な手間をかけさせやがって。この借りは、お前のお仲間にたっぷり払ってもらうからね。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "そんな！　やるんならあたしを‥‥‥お願い！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "嫌なこった。お前にはご褒美もお仕置きもなしだ。誰がそんな事をしてやるもんか。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 589 #t)
   (proc 11))
 (seg (? (= S 3) (= 589 #t))
   (proc 10)
   (text "「April」" 'br)
   (text "ひッ‥‥‥つ、冷たい！")
   (wait)
   (text-reset 14)
   (proc 11))
 (seg (? (= S 4) (= 590 #f))
   (proc 0)
   (exec-mem 256 "G 30 33 240 21 160")
   (image-file "gpc¥a1_03a1.gpc")
   (image-mem 1 0)
   (image-file "gpc¥a1_03b.gpc")
   (image-mem 1 0)
   (proc 10)
   (text "「April」" 'br)
   (text "あうッ！　な、何をするつもりなの‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "決まってるだろう、お前が汚らしい＊＊＊の中に隠した軍部の機" 'br)
   (text "密を回収するんだよ！")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "まさか、手を入れて‥‥‥そんなの無理よ、裂けちゃうわ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "どうだかわからないよ、淫売のここは、わたしの手ぐらい簡単に飲み込んじまいそうじゃないか！")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "いッ、嫌ぁぁぁぁ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "嫌だって言ってるわりには、もう濡れてるじゃないか。この淫売！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3072 0)
   (mes-load? "mes¥bnkcpy2.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥md_a4ani.mec" 0)
   (mes-load? 0)
   (proc 10)
   (text "「April」" 'br)
   (text "ひッ！　ひぃぃぃぃッ！")
   (wait)
   (text-reset 14)
   (exec-mem 256 "P 10 8 304")
   (exec-mem 29184 2 1 0 0)
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "ほらみろ、やっぱり何ともない。")
   (wait)
   (text-reset 14)
   (exec-mem 256 "P 10 8 304")
   (exec-mem 29184 2 1 1 0)
   (proc 10)
   (text "「April」" 'br)
   (text "嫌ッ‥‥‥し、死んじゃう‥‥‥あァァァッ！")
   (wait)
   (text-reset 14)
   (exec-mem 256 "P 10 8 304")
   (exec-mem 29184 2 1 0 0)
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "何処に隠してる‥‥‥もっと奥の方なのか？")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 590 #t)
   (exec-mem 256 "P 10 8 304")
   (exec-mem 256 "P 0 33 240")
   (exec-mem 29184 3 1)
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= S 4) (= 590 #t))
   (proc 0)
   (exec-mem 256 "G 30 33 240 21 160")
   (image-file "gpc¥a1_03a1.gpc")
   (image-mem 1 0)
   (image-file "gpc¥a1_03b.gpc")
   (image-mem 1 0)
   (proc 10)
   (text "「April」" 'br)
   (text "んんッ！　お願い‥‥‥もう許してッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そうはいかない、これも任務だからね。")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3072 0)
   (mes-load? "mes¥bnkcpy2.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥md_a4ani.mec" 0)
   (mes-load? 0)
   (proc 10)
   (text "「April」" 'br)
   (text "あうッ！　んッ、んッ‥‥‥んんッ！")
   (wait)
   (text-reset 14)
   (exec-mem 256 "P 10 8 304")
   (exec-mem 29184 2 1 0 0)
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "ちっ、汚い汁を出すんじゃないよ。わたしの手が汚れるだろう！")
   (wait)
   (text-reset 14)
   (exec-mem 256 "P 10 8 304")
   (exec-mem 29184 2 1 1 0)
   (proc 10)
   (text "「April」" 'br)
   (text "ううッ‥‥‥ほ、本当に駄目‥‥‥壊れちゃうわ！")
   (wait)
   (text-reset 14)
   (exec-mem 256 "P 10 8 304")
   (exec-mem 29184 2 1 0 0)
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "ここに‥‥‥何かあるな、この奥に‥‥‥")
   (wait)
   (text-reset 14)
   (exec-mem 256 "P 10 8 304")
   (exec-mem 29184 2 1 1 0)
   (proc 10)
   (text "「April」" 'br)
   (text "あうぅぅッ、そんな奥まで‥‥‥んふっ、んんッ！")
   (wait)
   (text-reset 14)
   (exec-mem 256 "P 10 8 304")
   (exec-mem 29184 2 1 0 0)
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "これ‥‥‥か。ほら、もう済んだ！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3072 0)
   (exec-mem 256 "P 0 33 240")
   (proc 10)
   (text "「April」" 'br)
   (text "はァ、はァ、はァ、はァ、はァ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "何だ、これは。黒いシリコン板の上にエッチングがしてある。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "はァ、はァ‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "何かって聞いてるんだよ！")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "マ、マイクロチップです‥‥‥何に使うのかは知りません。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "知らない？　何だかわからない物を、アソコの中に入れといたって言うのか。")
   (wait)
   (text-reset 14)
   (text "「April」" 'br)
   (text "プリスが‥‥‥そうしろって‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "まあいい、こいつは軍の技研が調べるだろう。お前にはもう用はない。今度こそ本当に用なしだ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "お前は軍人用の収容所に入れられる。あそこは一般刑務所なんか比じゃない辛さだそうだ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "せいぜい、囚人どもに媚を売って可愛がってもらうんだな！")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 75 #t)
   (proc 11)
   (exec-mem 29184 3 1)
   (exec-mem 256 "S 0")
   (exec-mem 18688 3)
   (exec-mem 18688 5 1 0)
   (exec-mem 3072 0)
   ((cmd 209) 0 5)
   (image-file "gpc¥waku.gpc")
   (image-mem 0 3)
   ((cmd 209) 1 5)
   (exec-mem 256 "I")
   (mes-jump "mes¥MA_A05.mes")))