(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (proc 10)
  (text "「April」" 'br)
  (text "もう許して下さい‥‥‥こ、このままじゃ死んじゃうわ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "少しは素直になってきたみたいだね。でも、これでお終いにする気はないよ。")
  (wait)
  (text-reset 14)
  (text "「April」" 'br)
  (text "ひっ‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "わたしはね、拷問のプロなんだ。だからどうするのが一番こたえるのかよく知ってる。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "一晩その格好で反省してるんだね、また明日可愛がってやる。")
  (wait)
  (text-reset 14)
  (text "「April」" 'br)
  (text "そんなの嫌よ、お願い‥‥‥縄を解いて！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "明日までには傷も消えてるだろう。だけど忘れちゃいけないよ、お前はただの卑しい牝奴隷なんだって事をね！")
  (wait)
  (text-reset 14)
  (text "「April」" 'br)
  (text "ま、待って‥‥‥置いて行かないで！")
  (wait)
  (text-reset 14)
  (text "「April」" 'br)
  (text "ああ、お願い‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (proc 11)
  (exec-mem 18688 3)
  (exec-mem 18688 5 1 0)
  (exec-mem 3072 0)
  ((cmd 209) 0 5)
  (text-frame 0 0 79 399)
  (text-reset 14)
  ((cmd 209) 1 0)
  (define-proc 9
    (<>
     (exec-mem 12288 3 0 1 5 0)
     (exec-mem 11680 0)
     (exec-mem 27648 2 2)
     (exec-mem 3072 2)))
  (define-proc 8
    (<>
     (exec-mem 3968 104)
     (exec-mem 25984 2 1)
     (exec-mem 3072 2)
     (exec-mem 3072 1)))
  (mes-jump "mes¥MD_A03.MES")))