(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (loop
   (set-var S 0)
   (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
   (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 4) (= 991 #f) (= 1020 #f) (= Q 4) (= 982 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name3.gpc,GPC")
   (image-mem 1 0 9 64)
   (proc 1)
   (set-var Q 4))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 4) (= 991 #t) (= 1020 #f) (= Q 4) (= 982 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name3.gpc,GPC")
   (image-mem 1 0 52 64)
   (proc 1)
   (set-var Q 4))
 (seg (? (= Z 2) (= Z 3) (= Z 4) (= 991 #f) (= 1020 #f) (>= Q 1) (= 982 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= Z 4) (= 991 #t) (= 1020 #f) (>= Q 1) (= 982 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1) (= 982 #f))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1) (= 982 #f))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= Z 1)) (proc 4) (mes-load? 4096))
 (seg (? (= Z 2)) (proc 4) (mes-load? 4096))
 (seg (? (= Z 3)) (proc 4) (mes-load? 4096))
 (seg (? (= Z 4)) (proc 4) (mes-load? 4096))
 (seg (? (= Y 1) (= S 1) (>= H 11) (= 586 #t))
   (proc 4)
   (mes-jump "mes¥md_a3_r1.mes"))
 (seg (? (= Y 2) (= S 1) (>= H 11) (= 586 #t))
   (proc 4)
   (mes-jump "mes¥md_a3_r2.mes"))
 (seg (? (>= Y 1) (<= Y 2) (= S 1) (>= H 11))
   (proc 4)
   (branch-reg
    585
    (</>
     (/
      (proc 10)
      (branch-index
       (</>
        (/
         (proc 14)
         (text "ううっ‥‥‥‥‥‥")
         (proc 7)
         (proc 13)
         (text "牝奴隷が板についてきたね、あんた元からそのケがあったみたい。それでこそ、調教のし甲斐があるってもんさ。")
         (proc 7)
         (proc 13)
         (text "もっとも、このまま続ければ命を落としかねないけど。あんたにはその方が幸せかもね‥‥‥")
         (proc 7))
        (/
         (proc 13)
         (text "囚人として暮らすよりその方が楽だとは思うけど、このまま続ければ死んじまうかもね。そろそろけりをつけてやろうか。")
         (proc 7))))
      (proc 11))
     (/
      (exec-mem 3072 0)
      (proc 5)
      (proc 15)
      (proc 10)
      (proc 13)
      (text "もういいだろう。あんたの知ってる事を、洗いざらい白状してもらうよ。嘘をついたらどうなるか、わかってるだろうね？")
      (proc 7)
      (proc 14)
      (text "は、はい‥‥‥何でも喋ります。")
      (proc 7)
      (proc 13)
      (text "それじゃ、まずはお前の仲間の事だ。お前と仲間の女はどうして知り合った。")
      (proc 7)
      (proc 14)
      (text "レイファとは部隊が一緒だったので、前から知ってました。ナナは中東でやったある作戦がきっかけで‥‥‥")
      (proc 7)
      (proc 14)
      (text "ナナは特殊部隊じゃないけど、かなり腕の立つハッカーでした。")
      (proc 7)
      (proc 13)
      (text "ハッカーだって？　つまりニューテクだな。それじゃ、ナナって女が軍のデータベースをハッキングして情報を奪ったんだな。")
      (proc 7)
      (proc 14)
      (text "その作戦で、ナナは敵国の防衛網にハッキングして情報撹乱を。あんな凄腕は滅多に居ないって話でした。")
      (proc 7)
      (proc 13)
      (text "それじゃ、軍のデータベースをハックして機密を盗むって作戦は、ナナが考えたんだな？")
      (proc 7)
      (proc 14)
      (text "あ、あたし達を選んだのはナナだと思います。軍のデータベースは固すぎて、ヘタをすれば焼かれてしまうって言ってました。")
      (proc 7)
      (proc 14)
      (text "レイファとあたしが軍の施設に侵入して、送電をストップさせたんです。その隙にナナがデータベースに潜り込む‥‥‥")
      (proc 7)
      (proc 13)
      (text "見事な連携プレーだ。もっとも、わたしには話の大筋程度しか理解出来なかったけど。お前の話を総合するとナナが主犯って事か？")
      (proc 7)
      (proc 14)
      (text "‥‥‥‥‥‥全部ナナが考えたとは思えません。")
      (proc 7)
      (proc 13)
      (text "それはどうして？")
      (proc 7)
      (proc 14)
      (text "あの子はハッカーだから、軍の機密を換金する方法も知ってるはずだけど、あたし達に先払いで金を払える程裕福じゃないから‥‥‥")
      (proc 7)
      (proc 11)
      (exec-mem 3072 0)
      (nop@)
      (set-reg 586 #t)
      (proc 16)
      (proc 6)
      (if (</>
           (//
            (? (= Y 1))
            (exec-mem 9504 "C icon¥tool12.gpc,GPC")
            (branch-reg
             991
             (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16)))))
           (//
            (? (= Y 2))
            (exec-mem 9504 "C icon¥tool13.gpc,GPC")
            (branch-reg
             991
             (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40)))))))
      (exec-mem 256 "G 10 8 304 64 80"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= Y 1) (= S 1) (<= H 5))
   (proc 4)
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 14)
      (text "なっ、何でも話します‥‥‥だから、もうやめて！")
      (proc 7)
      (proc 13)
      (text "犬みたいにキャンキャンとよく鳴く女だね。そんな事を言っても何にもならないのが、まだわからないのかい？")
      (proc 7)
      (proc 14)
      (text "どうしてよ‥‥‥何でも話すって言ってるのに！")
      (proc 7)
      (proc 13)
      (text "それじゃ、わたしの気が済まないんだよ。")
      (proc 7))
     (/ (proc 14) (text "お願い、何でも喋るから‥‥‥もう許して！") (proc 7))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 10))
   (proc 4)
   (branch-index
    (</>
     (/
      (exec-mem 3072 0)
      (proc 5)
      (proc 15)
      (proc 12)
      (proc 10)
      (proc 13)
      (text "くっくっくっ‥‥‥もうたまらないって顔だね。")
      (proc 7)
      (proc 14)
      (text "そ、そんな事‥‥‥‥‥‥‥‥‥")
      (proc 7)
      (proc 13)
      (text "そんな事、どうしたって？　＊＊＊はグチュグチュ、後ろの方も" 'br)
      (text "ヒクヒク痙攣させて、それでも何でもないって言うつもり？")
      (proc 7)
      (proc 14)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (proc 7)
      (proc 13)
      (text "牝犬らしい態度でお願いするんだね、もっと苛めて下さいってさ！")
      (proc 7)
      (proc 14)
      (text "‥‥‥‥‥‥‥‥‥")
      (proc 7)
      (proc 14)
      (text "も、もっと‥‥‥もっと苛めて下さい‥‥‥ご主人様‥‥‥")
      (proc 7)
      (proc 13)
      (text "いい返事だ。望み通り散々な目にあわせてやるよ！")
      (proc 7)
      (proc 11)
      (exec-mem 3072 0)
      (proc 16)
      (proc 6)
      (if (</>
           (//
            (? (= Y 1))
            (exec-mem 9504 "C icon¥tool12.gpc,GPC")
            (branch-reg
             991
             (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16)))))
           (//
            (? (= Y 2))
            (exec-mem 9504 "C icon¥tool13.gpc,GPC")
            (branch-reg
             991
             (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40)))))))
      (exec-mem 3968 104)
      (exec-mem 3072 2)
      (exec-mem 3072 1))
     (/
      (proc 10)
      (proc 14)
      (text "も、もっと‥‥‥もっと苛めて下さい‥‥‥ご主人様‥‥‥")
      (proc 7)
      (proc 11))
     (/
      (proc 10)
      (proc 13)
      (text "床に出来たその汚らしい汁のシミは何だい。もっと苛めて欲しいのなら、牝犬らしくご主人様にお願いしな！")
      (proc 7)
      (proc 11)))))
 (seg (? (= Y 1) (= S 2))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    571
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02ca.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "んっ、くぅッ‥‥‥‥‥‥")
      (proc 7)
      (proc 13)
      (text "どうだ、気持ちいいか！　ご主人様にお礼を言いな！")
      (proc 7)
      (proc 14)
      (text "きっ、気持ちいいです‥‥‥ありがとうございましたっ‥‥‥")
      (proc 7)
      (nop@)
      (set-reg 571 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "んっ、くぅッ‥‥‥‥‥‥") (proc 7))))
   (proc 11))
 (seg (? (= Y 1) (= S 3))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    572
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02cb.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "あぁッ‥‥‥あぁぁんッ！")
      (proc 7)
      (proc 13)
      (text "＊＊＊が疼いて仕方ないようだな、いかにも牝犬らしいが、大切" 'br)
      (text "なロッドが汚らしい汁で汚れてしまう。どうしてくれるんだ？")
      (proc 7)
      (proc 14)
      (text "き、奇麗にさせて頂きます‥‥‥ご主人様が言われる通りに！")
      (proc 7)
      (nop@)
      (set-reg 572 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "はぁンッ‥‥‥も、もっと下を‥‥‥お願いですッ！") (proc 7))))
   (proc 11))
 (seg (? (= Y 1) (= S 4))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    573
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02cc.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "あうッ‥‥‥い、痛ッ！")
      (proc 7)
      (proc 13)
      (text "痛くて気持ちいいか。牝犬のお前らしい！　エイプリル、お前は牝犬だな、そうだろう？")
      (proc 7)
      (proc 14)
      (text "そうです‥‥‥あたしは牝犬です、だからもっと‥‥‥")
      (proc 7)
      (nop@)
      (set-reg 573 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "あうッ！　い、痛くて気持ちいいです‥‥‥もっと打って‥‥‥") (proc 7))))
   (proc 11))
 (seg (? (= Y 1) (= S 5))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    574
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02cd.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "はっ‥‥‥‥‥‥‥‥‥")
      (proc 7)
      (proc 13)
      (text "腹の上にザーメンをぶち撒けたみたいだね。赤い血の色の精液だ。どうだい、ご主人様の精液を浴びた感想は！")
      (proc 7)
      (proc 14)
      (text "は、はい‥‥‥とってもうれしいです、もっとかけて下さい‥‥‥")
      (proc 7)
      (nop@)
      (set-reg 574 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "はっ‥‥‥‥‥‥‥‥‥") (proc 7))))
   (proc 11))
 (seg (? (= Y 1) (= S 6))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    575
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02ce.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "ひッ‥‥‥そっ、そこは‥‥‥そこは許して下さいッ！")
      (proc 7)
      (proc 13)
      (text "ちゃんと＊＊＊は避けてやるさ。もっとも、囚人には無用の物だ" 'br)
      (text "けど。塀の中じゃお楽しみもないだろうからさ！")
      (proc 7)
      (proc 14)
      (text "ああ、そんな‥‥‥‥‥‥")
      (proc 7)
      (nop@)
      (set-reg 575 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ひッ‥‥‥そっ、そこは‥‥‥そこは許して下さいッ！") (proc 7))))
   (proc 11))
 (seg (? (= Y 1) (= S 7))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    576
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02cf.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "あッ、くぅぅッ‥‥‥‥‥‥")
      (proc 7)
      (proc 13)
      (text "お前のその汚らしい＊＊＊を狙ってやったのに、外しちまった。" 'br)
      (text "許してもいないのに体を動かすんじゃない！")
      (proc 7)
      (proc 14)
      (text "は、はい。申し訳ありません‥‥‥‥‥‥")
      (proc 7)
      (nop@)
      (set-reg 576 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "あッ、くぅぅッ‥‥‥‥‥‥") (proc 7))))
   (proc 11))
 (seg (? (= Y 1) (= S 8))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    577
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02cg.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "はんッ‥‥‥も、もっと上を‥‥‥オッパイを苛めて下さいッ！")
      (proc 7)
      (proc 13)
      (text "奴隷のくせに、ご主人様に意見しようっての？")
      (proc 7)
      (proc 14)
      (text "ああ、申し訳ありません‥‥‥決してそんなつもりじゃ‥‥‥")
      (proc 7)
      (nop@)
      (set-reg 577 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "はんッ‥‥‥も、もっと上を‥‥‥オッパイを苛めて下さいッ！") (proc 7))))
   (proc 11))
 (seg (? (= Y 1) (= S 9))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    578
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02ch.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "あぁぁッ！　お、お願い‥‥‥オッパイを‥‥‥")
      (proc 7)
      (proc 13)
      (text "何処をどうするかは、わたしが決めるんだ。お前はただの牝奴隷、ご主人様に意見するなんて、許さないよ！")
      (proc 7)
      (proc 14)
      (text "も、申し訳ありません‥‥‥でも、もう我慢が‥‥‥")
      (proc 7)
      (nop@)
      (set-reg 578 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "あぁぁッ！　お、お願い‥‥‥オッパイを‥‥‥") (proc 7))))
   (proc 11))
 (seg (? (= Y 1) (= S 10))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    579
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02ci.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "はッ、はぁぁぁん！")
      (proc 7)
      (proc 13)
      (text "そんなに気持ちいいかい、オッパイを苛められるのは！")
      (proc 7)
      (proc 14)
      (text "はい‥‥‥気持ちいいです‥‥‥もっと苛めて下さいッ！")
      (proc 7)
      (nop@)
      (set-reg 579 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "はッ、はぁぁぁん！") (proc 7))))
   (proc 11))
 (seg (? (= Y 1) (= S 11))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    580
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02cj.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "ひッ‥‥‥ひぃぃぃッ！")
      (proc 7)
      (proc 13)
      (text "牝犬め、涙を流して悦んでやがる。オッパイを苛められるのがそんなに気持ちいいか。")
      (proc 7)
      (proc 14)
      (text "気持ちいいです！　お願いです、乳首を‥‥‥千切れるくらい！")
      (proc 7)
      (nop@)
      (set-reg 580 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ひッ‥‥‥ひぃぃぃッ！") (proc 7))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 5))
   (proc 4)
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 13)
      (text "お前はだいぶ牝奴隷が板についてきたな、尋問を始める前のお前とは、まるで別人のようだ。")
      (proc 7)
      (proc 14)
      (text "ああ‥‥‥何でも喋ります‥‥‥だからもう苛めないで下さい！")
      (proc 7)
      (proc 13)
      (text "よく言うよ、鞭で打たれるのが大好きなくせに。うれし涙を流してる＊＊＊が何よりの証拠だよ。")
      (proc 7)
      (proc 14)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
      (proc 7)
      (proc 13)
      (text "ただ知っている事を喋らすだけじゃ、わたしの気が済まない。最低の牝奴隷にしてやるつもりさ！")
      (proc 7)
      (proc 14)
      (text "そんな‥‥‥‥‥‥")
      (proc 7))
     (/
      (proc 13)
      (text "自分が最低の牝奴隷だって事に、早く気付くべきだね。そうすりゃ鞭で打たれるのも辛くないだろうさ。")
      (proc 7)
      (proc 13)
      (text "何しろお前は本物のクズなんだから。鞭を食らってヒイヒイよがってても、誰も責めやしないさ。")
      (proc 7))
     (/ (proc 14) (text "何でも喋ります‥‥‥言われた事は何でもしますから‥‥‥") (proc 7))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 10))
   (proc 4)
   (branch-index
    (</>
     (/
      (exec-mem 3072 0)
      (proc 5)
      (proc 15)
      (proc 12)
      (proc 10)
      (proc 13)
      (text "いい顔だ‥‥‥恥辱にまみれて、プライドも羞恥心も全てなくしてしまった、本当の奴隷の顔だ。")
      (proc 7)
      (proc 14)
      (text "何でも言う事をききます‥‥‥ご主人様の言う通りにします。")
      (proc 7)
      (proc 13)
      (text "神妙な態度だね、すっかり牙を抜かれちまってさ。最初からこうなる事はわかってたんだ。")
      (proc 7)
      (proc 14)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (proc 7)
      (proc 13)
      (text "どうして欲しい、言ってみな。")
      (proc 7)
      (proc 14)
      (text "‥‥‥‥‥‥もっと鞭で苛めて下さい、目茶苦茶にして下さい！")
      (proc 7)
      (proc 13)
      (text "よし、望み通りにしてやろう‥‥‥")
      (proc 7)
      (proc 11)
      (exec-mem 3072 0)
      (proc 16)
      (proc 6)
      (if (</>
           (//
            (? (= Y 1))
            (exec-mem 9504 "C icon¥tool12.gpc,GPC")
            (branch-reg
             991
             (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16)))))
           (//
            (? (= Y 2))
            (exec-mem 9504 "C icon¥tool13.gpc,GPC")
            (branch-reg
             991
             (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40)))))))
      (exec-mem 3968 104)
      (exec-mem 3072 2)
      (exec-mem 3072 1))
     (/
      (proc 10)
      (proc 14)
      (text "‥‥‥‥‥‥もっと鞭で苛めて下さい、目茶苦茶にして下さい！")
      (proc 7)
      (proc 11)))))
 (seg (? (= Y 2) (= S 2))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    571
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02ca.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "んんッ、もっと‥‥‥もっと打って！")
      (proc 7)
      (proc 13)
      (text "ご主人様にお礼はどうした、鞭で打ってもらったお礼は？")
      (proc 7)
      (proc 14)
      (text "ご、ご主人様‥‥‥苛めて下さってありがとうございます‥‥‥")
      (proc 7)
      (nop@)
      (set-reg 571 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "んんッ、もっと‥‥‥もっと打って！") (proc 7))))
   (proc 11))
 (seg (? (= Y 2) (= S 3))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    572
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02cb.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "嫌っ、そこじゃないの‥‥‥もっと下の方を！")
      (proc 7)
      (proc 13)
      (text "呆れた牝犬だね、自分から＊＊＊を鞭で打ってくれって言うの？" 'br)
      (text "そんなマゾ女は今までに見た事もないね！")
      (proc 7)
      (proc 14)
      (text "お願い、早く打って‥‥‥あたしの＊＊＊を打って‥‥‥")
      (proc 7)
      (nop@)
      (set-reg 572 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "嫌っ、そこじゃないの‥‥‥もっと下の方を！") (proc 7))))
   (proc 11))
 (seg (? (= Y 2) (= S 4))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    573
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02cc.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "あうぅッ‥‥‥い、痛いッ！")
      (proc 7)
      (proc 13)
      (text "痛くて気持ちがいいんだろう？　お前みたいな変態のマゾは、こうされるのが好きで仕方ないんだ。")
      (proc 7)
      (proc 14)
      (text "はい‥‥‥そうです、あたしは変態のマゾ女ですッ！")
      (proc 7)
      (nop@)
      (set-reg 573 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "あうぅッ‥‥‥い、痛いッ！") (proc 7))))
   (proc 11))
 (seg (? (= Y 2) (= S 5))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    574
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02cd.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "んんッ！　そ、そこは駄目‥‥‥")
      (proc 7)
      (proc 13)
      (text "皮膚が裂けちまいそうだね。何ならお腹の真ん中に特大の＊＊＊" 'br)
      (text "を作ってやろうか？")
      (proc 7)
      (proc 14)
      (text "そ、そんな‥‥‥駄目、許して‥‥‥")
      (proc 7)
      (nop@)
      (set-reg 574 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "んんッ！　そ、そこは駄目‥‥‥") (proc 7))))
   (proc 11))
 (seg (? (= Y 2) (= S 6))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    575
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02ce.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "あうッ‥‥‥‥‥‥‥‥‥")
      (proc 7)
      (proc 13)
      (text "痛くて気持ちいいだろう。気持ちよくして下さったご主人様に牝奴隷らしくお礼を言ってごらん！")
      (proc 7)
      (proc 14)
      (text "ワ、ワン‥‥‥ワン、ワン！")
      (proc 7)
      (nop@)
      (set-reg 575 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "あうッ‥‥‥‥‥‥‥‥‥") (proc 7))))
   (proc 11))
 (seg (? (= Y 2) (= S 7))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    576
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02cf.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "はッ‥‥‥はぁぁんッ！")
      (proc 7)
      (proc 13)
      (text "おっと、＊＊＊にかすっちまった。そう簡単に悦ばせてはやらな" 'br)
      (text "いからね。たっぷり嬲ってからだ。")
      (proc 7)
      (proc 14)
      (text "ああ、そんな‥‥‥早く下さい！")
      (proc 7)
      (nop@)
      (set-reg 576 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "はッ‥‥‥はぁぁんッ！") (proc 7))))
   (proc 11))
 (seg (? (= Y 2) (= S 8))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    577
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02cg.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "んんッ‥‥‥オッパイも打って‥‥‥早くっ！")
      (proc 7)
      (proc 13)
      (text "ふざけるんじゃないよ、ご主人様に命令するつもりかい？")
      (proc 7)
      (proc 14)
      (text "も、申し訳ありません‥‥‥で、でも我慢できないんです‥‥‥")
      (proc 7)
      (nop@)
      (set-reg 577 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "んんッ‥‥‥オッパイも打って‥‥‥早くっ！") (proc 7))))
   (proc 11))
 (seg (? (= Y 2) (= S 9))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    578
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02ch.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "んんッ、も、もう死んじゃいそう‥‥‥")
      (proc 7)
      (proc 13)
      (text "そう簡単に死なれちゃ困る、お前にはまだ喋ってもらわなきゃならないんだからね。")
      (proc 7)
      (proc 14)
      (text "は、はい‥‥‥ご主人様のためなら何でも喋ります。")
      (proc 7)
      (nop@)
      (set-reg 578 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "んんッ、も、もう死んじゃいそう‥‥‥") (proc 7))))
   (proc 11))
 (seg (? (= Y 2) (= S 10))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    579
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02ci.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "ひぃッ‥‥‥き、気持ちいい‥‥‥もっと打って！")
      (proc 7)
      (proc 13)
      (text "いいだろう。望みどおり、目茶苦茶にしてやる。")
      (proc 7)
      (sound 'se 1)
      (proc 14)
      (text "ああァァァッ！")
      (proc 7)
      (nop@)
      (set-reg 579 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ひぃッ‥‥‥き、気持ちいい‥‥‥もっと打って！") (proc 7))))
   (proc 11))
 (seg (? (= Y 2) (= S 11))
   (proc 4)
   (sound 'se 1)
   (branch-reg
    580
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_02cj.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "あうッ、いい‥‥‥気持ちいい‥‥‥そこ、もっと！")
      (proc 7)
      (proc 13)
      (text "もうプライドも何も残っちゃいないね。オッパイを苛められて悦んでる姿を、あんたの仲間にも見せてやりたいもんだ。")
      (proc 7)
      (proc 14)
      (text "もうどうなってもいい‥‥‥だから、もっと‥‥‥")
      (proc 7)
      (nop@)
      (set-reg 580 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "あうッ、いい‥‥‥気持ちいい‥‥‥そこ、もっと！") (proc 7))))
   (proc 11))
 (seg (? (= Y 3) (= 581 #f) (= S 1))
   (proc 4)
   (proc 10)
   (branch-reg
    584
    (</>
     (/
      (proc 14)
      (text "うッ‥‥‥‥‥‥‥‥‥")
      (proc 7)
      (proc 13)
      (text "よく拝んどきな、これからお前を狂わせてくれる物だよ！")
      (proc 7)
      (proc 14)
      (text "い、嫌っ！　それだけは‥‥‥ああ、お願い‥‥‥")
      (proc 7)
      (proc 13)
      (text "お前に何かを決める権利なんてないんだよ、まだわからないのか？わたしがやるって言ったら、やるんだ！")
      (proc 7)
      (proc 14)
      (text "ううっ‥‥‥‥‥‥")
      (proc 7))
     (/
      (proc 14)
      (text "いっ、嫌ぁ‥‥‥どけて！")
      (proc 7)
      (proc 13)
      (text "お前の汚い汁で汚れてしまった。この後、他のお仲間にも使うんだから、奇麗にしておいた方がいいだろう？")
      (proc 7)
      (proc 14)
      (text "‥‥‥‥‥‥‥‥‥")
      (proc 7)
      (proc 13)
      (text "それとも、仲間に自分の汁で汚れた物を使わせるつもりか？")
      (proc 7)
      (proc 14)
      (text "嫌っ、言わないで‥‥‥そんなの嫌よ！")
      (proc 7)
      (proc 13)
      (text "いや、それもいいかもしれないな。仲間の愛液で汚れたバイブを入れられるのは、どんな気持ちだろうね‥‥‥")
      (proc 7)
      (proc 14)
      (text "そ、そんなの嫌ぁ！　お願い、止めて‥‥‥‥‥‥")
      (proc 7))))
   (nop@)
   (set-reg 581 #t)
   (proc 11))
 (seg (? (= Y 3) (= 581 #t) (= S 1))
   (proc 4)
   (proc 10)
   (proc 14)
   (text "んっ、嫌ッ‥‥‥そんな物、近づけないで‥‥‥")
   (proc 7)
   (proc 11))
 (seg (? (= Y 3) (= 582 #f) (>= S 10) (<= S 11))
   (proc 4)
   (proc 10)
   (proc 14)
   (text "つ、冷たい‥‥‥‥‥‥")
   (proc 7)
   (proc 13)
   (text "こいつは、今までに何人もの女に使ってきた物だ。よっぽどいいんだろう、どの女もヒイヒイ言ってたっけ！")
   (proc 7)
   (proc 14)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (proc 7)
   (proc 13)
   (text "そんなに物欲しそうな目でみなくても、たっぷりと味あわせてやるから、心配するな。")
   (proc 7)
   (proc 14)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
   (proc 7)
   (nop@)
   (set-reg 582 #t)
   (proc 11))
 (seg (? (= Y 3) (= 582 #t) (>= S 10) (<= S 11))
   (proc 4)
   (proc 10)
   (proc 13)
   (text "こいつは、今までに何人もの女に使ってきた物だ。よっぽどいいんだろう、どの女もヒイヒイ言ってたっけ！")
   (proc 7)
   (proc 11))
 (seg (? (= Y 3) (= 583 #f) (>= S 5) (<= S 6))
   (proc 4)
   (proc 10)
   (proc 14)
   (text "なっ、何をするの‥‥‥お腹から離して！")
   (proc 7)
   (proc 13)
   (text "ヘソの穴に入れてやろうか。お前みたいな牝犬なら、どこの穴でもすっぽり飲み込んじまいそうだ！")
   (proc 7)
   (proc 14)
   (text "そんな‥‥‥酷いわ、そんな事いわないで、お願いです‥‥‥")
   (proc 7)
   (proc 13)
   (text "よく見るんだ、立派な物じゃないか。本物のペニスよりも気持ちいいはずだ‥‥‥‥‥‥")
   (proc 7)
   (proc 14)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (proc 7)
   (proc 13)
   (text "欲しいだろう、これで思いっきりかき回して欲しいだろう！")
   (proc 7)
   (proc 14)
   (text "は、はい‥‥‥欲しいです‥‥‥")
   (proc 7)
   (proc 13)
   (text "やっぱりお前は、恥知らずで淫乱な牝犬だ。")
   (proc 7)
   (nop@)
   (set-reg 583 #t)
   (proc 11))
 (seg (? (= Y 3) (= 583 #t) (>= S 5) (<= S 6))
   (proc 4)
   (proc 10)
   (proc 14)
   (text "早く‥‥‥それでかき回して‥‥‥早くっ！")
   (proc 7)
   (proc 11))
 (seg (? (= Y 3) (= 584 #f) (= S 12))
   (proc 4)
   (nop@)
   (inc-var H 1)
   (exec-mem 256 "F 10")
   (proc 0)
   (proc 5)
   (exec-mem 256 "F 8")
   (exec-mem 256 "F 9")
   (exec-mem 256 "F 6")
   (exec-mem 256 "F 7")
   (exec-mem 256 "G 21 3 256 50 144")
   (image-file "gpc¥a1_02b1.gpc")
   (image-mem 1 0)
   (exec-mem 256 "G 22 56 0 16 128")
   (image-file "gpc¥a1_02ba.gpc")
   (image-mem 1 0)
   (mes-load? "mes¥bnkcpy2.mec" 0)
   (mes-load? 0)
   (proc 10)
   (proc 14)
   (text "うッ‥‥‥‥‥‥")
   (proc 7)
   (proc 13)
   (text "おやおや‥‥‥いくらでも入っていきそうだ。")
   (proc 7)
   (proc 14)
   (text "あふッ‥‥‥ゴリゴリするッ！")
   (proc 7)
   (proc 14)
   (text "し、死んじゃう！")
   (proc 7)
   (proc 13)
   (text "まだ死ぬのは早いよ、こいつをたっぷり味わってからにしな。")
   (proc 7)
   (proc 11)
   (exec-mem 256 "F 10")
   (exec-mem 3072 0)
   (proc 17)
   (exec-mem 256 "A 0")
   (proc 10)
   (proc 14)
   (text "あぅぅぅッ！　は、入って来る！")
   (proc 7)
   (proc 13)
   (text "グチュグチュになってるくせに、妙に固いね‥‥‥")
   (proc 7)
   (proc 14)
   (text "痛いっ、無理にしないで‥‥‥大きすぎるのよォ！")
   (proc 7)
   (proc 13)
   (text "黙ってな‥‥‥これで‥‥‥どうだ！")
   (proc 7)
   (proc 14)
   (text "ひぃぃッ！")
   (proc 7)
   (proc 13)
   (text "最後まで入ったようだね‥‥‥処女みたいに苦労したよ。")
   (proc 7)
   (proc 14)
   (text "あうぅぅ‥‥‥‥‥‥")
   (proc 7)
   (nop@)
   (set-reg 584 #t)
   (exec-mem 256 "P 10 8 304")
   (proc 18)
   (exec-mem 256 "P 22 56 0")
   (exec-mem 256 "F 21")
   (exec-mem 256 "F 22")
   (proc 12)
   (proc 6)
   (exec-mem 9504 "C icon¥tool14.gpc,GPC")
   (branch-reg 991 (</> (/ (image-mem 1 0 6 64)) (/ (image-mem 1 0 71 64))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= Y 3) (= 585 #f) (= S 12))
   (proc 4)
   (proc 0)
   (proc 5)
   (exec-mem 256 "F 8")
   (exec-mem 256 "F 9")
   (exec-mem 256 "F 6")
   (exec-mem 256 "F 7")
   (exec-mem 256 "G 21 3 256 50 144")
   (image-file "gpc¥a1_02b1.gpc")
   (image-mem 1 0)
   (exec-mem 256 "G 22 56 0 16 128")
   (image-file "gpc¥a1_02ba.gpc")
   (image-mem 1 0)
   (mes-load? "mes¥bnkcpy2.mec" 0)
   (mes-load? 0)
   (proc 10)
   (proc 14)
   (text "あふッ、ああぁぁ‥‥‥‥‥‥‥‥‥")
   (proc 7)
   (proc 13)
   (text "豚みたいな鳴き声を出すな。お前は犬じゃなかったのか？")
   (proc 7)
   (proc 11)
   (exec-mem 256 "F 10")
   (exec-mem 3072 0)
   (proc 17)
   (exec-mem 256 "A 0")
   (proc 10)
   (proc 14)
   (text "はうぅぅん、いッ‥‥‥お、奥に当たるぅっ！")
   (proc 7)
   (proc 13)
   (text "汚らしい＊＊＊の中に、一杯汁を溜めてたみたいだね。いくらで" 'br)
   (text "も溢れてくるじゃないか！")
   (proc 7)
   (proc 14)
   (text "あふッ、あぁッ‥‥‥もっとかき回してッ！")
   (proc 7)
   (proc 13)
   (text "お前はわたしの奴隷だ、可愛い牝犬。ご主人様に忠誠を誓うんだ。")
   (proc 7)
   (proc 14)
   (text "んんッ、ご主人様‥‥‥何でもしますッ‥‥‥っぁぁん！")
   (proc 7)
   (proc 14)
   (text "あ、あたしは‥‥‥ご主人様のペットですッ‥‥‥")
   (proc 7)
   (proc 13)
   (text "いい子だ。それでこそ可愛がり甲斐があるってもんさ。たっぷりかき回してやるから、精一杯いい声で鳴くんだよ。")
   (proc 7)
   (proc 14)
   (text "はッ、はぁぁぁンッ‥‥‥あふっ、あふぅ！")
   (proc 7)
   (proc 14)
   (text "イッ、イクっ‥‥‥イッちゃう、もうダメェ！")
   (proc 7)
   (exec-mem 256 "P 10 8 304")
   (proc 18)
   (exec-mem 256 "P 22 56 0")
   (exec-mem 256 "F 21")
   (exec-mem 256 "F 22")
   (exec-mem 256 "A 0")
   (proc 12)
   (proc 6)
   (exec-mem 9504 "C icon¥tool14.gpc,GPC")
   (branch-reg 991 (</> (/ (image-mem 1 0 6 64)) (/ (image-mem 1 0 71 64))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1)
   (nop@)
   (set-reg 585 #t))
 (seg (? (= Y 3) (= 585 #t) (= S 12))
   (proc 4)
   (proc 0)
   (proc 5)
   (exec-mem 256 "F 8")
   (exec-mem 256 "F 9")
   (exec-mem 256 "F 6")
   (exec-mem 256 "F 7")
   (exec-mem 256 "G 21 3 256 50 144")
   (image-file "gpc¥a1_02b1.gpc")
   (image-mem 1 0)
   (exec-mem 256 "G 22 56 0 16 128")
   (image-file "gpc¥a1_02ba.gpc")
   (image-mem 1 0)
   (mes-load? "mes¥bnkcpy2.mec" 0)
   (mes-load? 0)
   (proc 10)
   (proc 14)
   (text "はッ、はぁぁぁンッ‥‥‥あふっ、あふぅ！")
   (proc 7)
   (proc 11)
   (exec-mem 3072 0)
   (exec-mem 256 "P 10 8 304")
   (exec-mem 256 "F 10")
   (proc 18)
   (exec-mem 256 "P 22 56 0")
   (exec-mem 256 "F 21")
   (exec-mem 256 "F 22")
   (proc 12)
   (proc 6)
   (exec-mem 9504 "C icon¥tool14.gpc,GPC")
   (branch-reg 991 (</> (/ (image-mem 1 0 6 64)) (/ (image-mem 1 0 71 64))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg*))