(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (proc 5)
  (proc 10)
  (proc 14)
  (text "ううぅぅッ！　うう、うぐッ‥‥‥")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "なに、バイブなんか嫌いだって？")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "うう。ううッ、ふぅッ！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "贅沢な子猫ちゃんだね。でも、そう言うだろうと思って、もっといい物を用意してあるんだ。うれしいだろう？")
  (wait)
  (text-reset 14)
  (proc 11)
  (exec-mem 3072 0)
  (image-file "gpc¥a1_11a2.gpc")
  (image-mem 1 0)
  (proc 12)
  (proc 10)
  (proc 14)
  (text "うぅッ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "そんなにがっつくんじゃないよ、いくら可愛いペットだからって、行儀が悪いのは許せないね。")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "うぐッ‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "よしよし、いい子だ。それじゃわたしのプレゼントをあげようか。あんまり焦らしても何だしね。")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "おい、出といで！")
  (wait)
  (text-reset 14)
  (proc 11)
  (exec-mem 3072 0)
  (image-file "gpc¥a1_11a1.gpc")
  (image-mem 1 0)
  (proc 12)
  (proc 10)
  (text "「Homeless Man」" 'br)
  (text "へへへ‥‥‥どうも。")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ううッ、ううぅぅぅッ！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "この間約束した、おいしい目ってのにあわせてやるよ。")
  (wait)
  (text-reset 14)
  (text "「Homeless Man」" 'br)
  (text "そりゃ、ありがてえ。それで何をしてくれるんで？")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "目の前にあるだろう。その子猫ちゃんを好きにしていいって言ってるんだ。")
  (wait)
  (text-reset 14)
  (text "「Homeless Man」" 'br)
  (text "本当ですかい？　そいつぁ、夢みたいだ！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "最後に＊＊＊したのはいつだ？　もうビンビンになっちまってる" 'br)
  (text "じゃないか。")
  (wait)
  (text-reset 14)
  (text "「Homeless Man」" 'br)
  (text "へっへっへっ‥‥‥そりゃもう。あんな姿を見せられちゃ辛抱出来ませんや。")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "それじゃ好きにしな。あんまり焦らしてやるんじゃないよ。見ろ、子猫ちゃんが＊＊＊びちゃびちゃにして待ってるだろ。")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "んんッ！　んん‥‥‥ううぅッ！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "この牝猫に、お前の汚い物を一発ご馳走してやんな！")
  (wait)
  (text-reset 14)
  (proc 11)
  (exec-mem 3072 0)
  (image-file "gpc¥a1_11b.gpc")
  (image-mem 0 3)
  (proc 12)
  (proc 10)
  (proc 14)
  (text "うぐッ、んふッ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Homeless Man」" 'br)
  (text "こ、こいつぁいい＊＊＊だ。すげえ締まりですぜ！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "そうかい、子猫ちゃんもお気に召したみたいだよ。")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ううぅぅ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Homeless Man」" 'br)
  (text "へへへっ‥‥‥お嬢ちゃん、気持ちいいかい？")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "んぐッ、んんッ‥‥‥ううぅぅッ！")
  (wait)
  (text-reset 14)
  (text "「Homeless Man」" 'br)
  (text "おうッ！　そんなに動かねえでくれよ。もう出ちまいそうだ。もっと楽しもうじゃねえか。")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "だらしのない男だね。その子を失望させるんじゃないよ。")
  (wait)
  (text-reset 14)
  (text "「Homeless Man」" 'br)
  (text "わ、わかってまさぁ‥‥‥それにしてもいい持ち物だぜ！")
  (wait)
  (text-reset 14)
  (text "「Homeless Man」" 'br)
  (text "それにこのオッパイ、最高だぜ。こんないい女には今までお目にかかった事がねえ！")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ふぅッ、ふぅぅぅッ‥‥‥")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "おい牝猫。わたしの話を聞いてるか？　わたしに逆らうとどんな目にあうかよくわかったろう。")
  (wait)
  (text-reset 14)
  (text "「Homeless Man」" 'br)
  (text "へへ‥‥‥すげえ締まりだぜ。それに具合もいい。おれのチ○ポはそんなにうまいか？")
  (wait)
  (text-reset 14)
  (text "「Homeless Man」" 'br)
  (text "ヌルヌルの襞が絡み付くぜ。姉さん、この女よっぽど飢えてたみてえだな！")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "んふっ、んッ‥‥‥んんッ、ふぅぅぅッ！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "なんて姿だ。薄汚い下衆野郎のチ○ポを咥えて、ヒイヒイ言ってる自分をよく見てみろ。")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "もしもこれ以上わたしに逆らうなら、もっと酷い目にあわせるぞ。最低の淫売にしてやってもいいんだ。聞いてるか？")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ううっ‥‥‥うう、んんんッ！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "臭いチ○ポに貫かれて、＊＊＊から汚い汁をたれ流す。そんな辛" 'br)
  (text "い目には、もう遭いたくないだろう？")
  (wait)
  (text-reset 14)
  (text "「Homeless Man」" 'br)
  (text "おうっ、おうッ‥‥‥チ○ポを万力で絞められてるみてえだ！")
  (wait)
  (text-reset 14)
  (text "「Homeless Man」" 'br)
  (text "ああ、一発だけじゃ物足りねえなぁ。こんな＊＊＊なら一晩中で" 'br)
  (text "もやり続けたいぜ‥‥‥")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "んふっ、ううッ‥‥‥ふぅぅぅン！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "お前さえいい子でいるなら、すぐに楽にしてやるんだ。")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ふぅぅんッ、ふぅぅッ‥‥‥ふぅぅぅッ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Homeless Man」" 'br)
  (text "おうっ！　おおっ‥‥‥で、出ちまうぜ！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "レイファ、牝猫。約束だぞ。この悪夢から覚めたら、お前は従順なペットになるんだ。わたしの可愛い牝猫になるんだ！")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ふッ、ふぅぅぅぅぅぅン！")
  (wait)
  (text-reset 14)
  (exec-mem 3072 0)
  ((cmd 209) 0 5)
  (text-frame 0 0 79 399)
  (text-reset 14)
  ((cmd 209) 1 0)
  (text-frame 10 312 70 380)
  (proc 12)
  (proc 10)
  (text "「Homeless Man」" 'br)
  (text "へへへ‥‥‥姉さん、確かにいい目にあわせてもらったぜ。")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "もうお前に用はないよ。さっさと帰りな。")
  (wait)
  (text-reset 14)
  (text "「Homeless Man」" 'br)
  (text "それにしても、あの＊＊＊は最高だったなァ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "こんな事は二度とない。さっさと帰ってマスでもかいてな。")
  (wait)
  (text-reset 14)
  (text "「Homeless Man」" 'br)
  (text "そんなに邪険にしねえでくれよこんな褒美をもらえるんなら、姉さんのために何でもするぜ。")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "お前に用がある時はこちらから連絡する。さあ、帰れ！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "レイファ、目が覚めたら全部吐いてもらうよ。その時までに牝猫らしい態度を身につけときな。")
  (wait)
  (text-reset 14)
  (proc 11)
  (exec-mem 18688 3)
  (exec-mem 18688 5 1 0)
  (exec-mem 3072 0)
  (mes-jump "mes¥MD_B03.MES")))