(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (nop@)
   (set-reg 980 #t)
   (set-reg 981 #t)
   (set-reg 982 #f)
   (set-reg 983 #f)
   (set-reg 984 #f)
   (set-reg 985 #f)
   (set-reg 986 #f)
   (set-reg 987 #f)
   (set-reg 988 #f)
   (set-reg 989 #f)
   (set-reg 990 #f)
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_13.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (if (</>
        (//
         (? (= P 8))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_08.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 8))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_08v.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 8)))))
        (// (nop@))))
   (exec-mem 256 "E")
   (load-mem "clm¥A1_13.clm" 32768)
   (load-mem "clm¥icon.clm" 20480)
   (mes-load? "mes¥icon_cl.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥icon_c2.mec" 0)
   (mes-load? 0)
   (text-frame 10 312 70 370)
   (exec-mem 256 "A 0")
   (proc 12)
   (define-proc 19
     (<>
      (if (</>
           (//
            (? (>= H 8) (= 985 #f))
            (nop@)
            (set-reg 985 #t)
            (mes-load? "mes¥icon_cl.mec" 0)
            (mes-load? 0)
            (mes-load? "mes¥icon_c2.mec" 0)
            (mes-load? 0))
           (// (nop@))))))
   (define-proc 13 (<> (text "「Kiyomi」" 'br)))
   (define-proc 14 (<> (text "「Lei-Fa」" 'br)))
   (set-var H 0)
   (proc 10)
   (proc 13)
   (text "どうだい子猫ちゃん、調子の方は？")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "あ、あなた酷い人ね‥‥‥わたし、もう堪えられないね！")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "あなた？　それは誰に向かって言っているんだ。まだわかってないようだな、自分がただのペットの牝猫だって事を！")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "ご、ごめんなさい、許してほしいね！")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "ペットがご主人様に話しかける事自体、許される行為じゃないが、どうしてもって時は、丁寧な敬語でご主人様と言うんだ。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "わかったのか？　返事もまともに出来ないようじゃ、まだお仕置きが足りないって事だね。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "そ、そんな事ないね。ちゃんとわかった、ご主人様！")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "ふん、まあいいだろう。お前には全部話してもらう。どうして軍部の機密を盗んだのか‥‥‥")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "お前の仲間の事、盗んだ機密を何処に隠したのか。ここまできて嫌だとは言わないだろうね？")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "は、はい‥‥‥全部話すね、ご主人様に言われた通りにするね！")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "よし、いい子だ。だがそれを聞く前に、お前を完全な牝猫に調教してやる必要がある。二度とわたしにたてつけないようにな。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "そ、そんな！　話が違うね、何でも話すから")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "何もしないで欲しいね！")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "駄目だ。お前はまだ従順なペットとは言えない。")
   (wait)
   (text-reset 14)
   (proc 11)
   (proc 0)
   (image-file "gpc¥a1_13a.gpc")
   (image-mem 1 0)
   (proc 12)
   (proc 10)
   (proc 14)
   (text "ああ、優しくしてほしいね‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (exec-mem 256 "P 5 6 0")
   (mes-jump "mes¥md_b3_ms.mes")))