(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (text-frame 10 312 70 370)
  (image-file "gpc¥a1_14be.gpc")
  (image-mem 0 3)
  (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
  (proc 10)
  (proc 13)
  (text "エイプリルに仕事の話を持ち掛けられて、軍のデータベースから情報を盗む作戦に荷担した、そこまではわかった。")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "他のメンバー、ナナとミツコに関しては何か知っているか？")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ナナは、前に軍の作戦で一緒になった事があったね。確か中東の何処かだったはずね。ミツコは‥‥‥")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "ミツコはどうした？")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "それまで会った事はなかったね。軍のデータベースに仕掛＝ランをした時も、わたし達とはあまり話さなかった。")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "相手は軍部だぞ、お前はその仕掛＝ランの事を疑問に思わなかったのか。何の問題がないと？")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "わたしやエイプリルは下っ端ね。作戦を考えたのは、多分ミツコだと思うんだけど‥‥‥")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ひょっとしたら、わたし達はミツコにはめられたね‥‥‥")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "悪いのは全部ミツコのせいか。お前は仲間を売るつもりか？　見下げ果てた女だ。")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "悪いのは全てミツコ。自分はエイプリルに誘われただけ。この国は腐ってる。本当に腐ってるのは、お前の頭の中さ！")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ほ、本当ね、わたしは嘘なんてつかないね！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "お前を完全に信用する訳にはいかない、もしかしたらわたしをはめようとしているのかもしれないだろう？")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "そんな事ない、わたしはご主人様のペットね‥‥‥")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "ふん。ミツコについて知っている事を話せ。")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ミツコは軍の高官の秘書ね、だから機密の事を知ってた。でもその高官と関係があった訳ではないね、彼女はレズビアン。")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ナナと恋人同士だったらしいね、わたし達の前でそんな態度を取った事はないけど、感じでわかった。")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "お前達が盗んだ機密の内容は？　それは何処に隠してある？")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "機密の内容はよく知らないね。わたしはお金をもらって、言われた通りにしただけ、本当ね！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "これ以上お前と話しててもラチがあかない。もういい、お前は一生地下室で鎖につながれていろ！")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ああ、そんな！　話が違うね、ご主人様‥‥‥")
  (wait)
  (text-reset 14)
  (nop@)
  (set-reg 60 #t)
  (nop@)
  (set-reg 938 #t)
  (proc 11)
  (exec-mem 18688 3)
  (exec-mem 18688 5 1 0)
  (exec-mem 3072 0)
  ((cmd 209) 0 5)
  (image-file "gpc¥waku.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (exec-mem 9504 "E")
  (exec-mem 256 "I")
  (mes-jump "mes¥MA_A03.MES")))