(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_14.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (if (</>
        (//
         (? (= P 9))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_09.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 9))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_09v.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 9)))))
        (// (nop@))))
   (exec-mem 256 "E")
   (load-mem "clm¥A1_03.clm" 32768)
   (text-frame 10 312 70 370)
   (exec-mem 256 "I")
   (exec-mem 256 "A 0")
   (exec-mem 18688 5 1 0)
   (proc 10)
   (text "「Lei-Fa」" 'br)
   (text "は、放せぇ‥‥‥何するね！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "レイファ、お前はわたしに嘘をついたな。あれだけ可愛がってやったのに、わたしを裏切ったんだ。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "そ、そんな事ないよ。わたしは裏切ったりしてないね！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "嘘をつけ。ではこの刺青の事をわたしに話さなかったのは何故だ。お前は自分の背中に機密を隠していたんだぞ！")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "そ、それは‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "この刺青には、どんな意味がある？")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "知らないね！　これは、プリスに無理矢理彫らされたもので‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "前はミツコとエイプリル、今度はプリスのせいか。お前は見下げ果てた女だ。一生ドブさらいの仕事をくれてやる！")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "あ、あの時はミツコ達が捕まる訳ないとおもってたね。でも、今度は違う。本当の事を言っているのに‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "だとしても、プリスの事をわたしに黙っていた罪は消えない。お前はわたしに恥をかかせようとしたんだ。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "違うんだってば、そうじゃなくてぇ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "言い訳は聞きたくない。もう二度とお前を可愛がってやらない。お前は牝奴隷以下の、ただの囚人だ。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "ああ、そんな‥‥‥こんな事やめて、もっとわたしを可愛がってほしいね。ご主人様ぁ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "甘えた声を出しても無駄だ、お前に同情する気なんて、わたしにはこれっぽっちも無いんだから。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "ああ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "勝手に泣きわめいていろ。それにしても、機密を隠す為に仲間の身体に刺青を彫るなんて、プリスもいかれた女だ。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "わ、わたしは嫌がったね‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "こいつを傷つけずに済んだのは、全く幸運だったよ。わたしにもまだツキが残ってたって事か。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "わ、わたしはどうなるか？　軍は機密を回収したがるけど、この刺青は背中に張り付いたままね。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "連中はわたしなんか問題にならないほど、冷酷で情け容赦がない。お前の背中の皮を剥いてでも、持ってくだろうさ。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "そんなの嫌ね！　どうしてわたしがそんな目にあわなきゃならないの、わたしが何をしたの？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それはお前が一番よく知っている、そうだろう？")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "そんなの酷すぎるね‥‥‥ご主人様、助けて！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "残念だね。わたしにはもう、そんな気は起こらないんだよ。自分の物にならないんなら、死んでしまっても同じこと。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "ああ、もう二度と逆らわないから‥‥‥いいペットになるね！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "この刺青には、どんな意味がある？　大昔のインカやアステカで見る抽象的な絵のような雰囲気もするが‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "それを知ってるのは、プリスだけね‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "見ようによっては、マトリクスかサイバースペースを表しているような気もする。こんなＴシャツを着た若いのを見た事がある。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "た、多分そうね。軍の機密はサイバネに関する事だって聞いたような気がするね！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "お前はそれを知っていて、わたしに黙っていたな？")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "ああ、ごめんなさい‥‥‥本当に忘れてたんですぅ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "どのみちこれを解析出来るのは、プリスか軍部の連中だけだろう。わたしには、ただの模様以上の意味はない‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "ああ、そんなァ‥‥‥わたしはどうなるね‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "この、一番てっぺんに描いてある、太陽のような印は何だ？")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "わ、わからないね‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "太陽に通じる細い線は何だ、大昔の道か、水路か。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ふん、これ以上お前と話していても埒があかないな。こいつは軍の技研にでも送った方がよさそうだ。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "か、皮を剥がれるのは嫌ね！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "安心しろ、もしそんな事をするとしても、それは技研の連中がやるべき事でわたしの仕事じゃない。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "ああぁぁ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それにしてもこの刺青はよく描けている。汚らしいお前の身体の中で唯一美しい部分と言えない事もないな！")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "ご、ご主人様ぁ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "お前の＊＊＊やオッパイには、誰も興味を示さないだろう。そん" 'br)
   (text "な汚らしい物、欲しくはないからね！")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "うう‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "どれ、ひとつ写真を撮ってやる。技研の連中に刺青を見せるんだ。＊＊＊もはっきり映るようにしてやるから喜べ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ほら、もっと脚を広げて‥‥‥身体を倒すんだ！")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "そ、そんなの嫌ね‥‥‥恥ずかしい！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "淫売の牝猫が、今さら何を恥ずかしがるってんだ。そこでじっとしてな！")
   (wait)
   (text-reset 14)
   (exec-mem 11680 0)
   (exec-mem 27648 2 2)
   (exec-mem 27648 2 2)
   (text "「Kiyomi」" 'br)
   (text "これでいいだろう。お前はもう、本当に用なしだ。二度と会う事もないだろう。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "ああ、ご主人様ぁ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 76 #t)
   (nop@)
   (set-reg 938 #t)
   (proc 11)
   (exec-mem 18688 3)
   (exec-mem 18688 5 1 0)
   (exec-mem 3072 0)
   (exec-mem 9504 "E")
   (exec-mem 256 "I")
   ((cmd 209) 0 5)
   (image-file "gpc¥waku.gpc")
   (image-mem 0 3)
   ((cmd 209) 1 5)
   (mes-jump "mes¥MA_A05.mes")))