(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (mes-load? "mes¥md_b3pl1.mec" 4096)
  (loop
   (set-var S 0)
   (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
   (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 7) (= 991 #f) (= 1020 #f) (= Q 7) (= 985 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name6.gpc,GPC")
   (image-mem 1 0 9 136)
   (proc 1)
   (set-var Q 7))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 7) (= 991 #t) (= 1020 #f) (= Q 7) (= 985 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name6.gpc,GPC")
   (image-mem 1 0 52 136)
   (proc 1)
   (set-var Q 7))
 (seg (? (= Z 2) (= Z 3) (= Z 7) (= 991 #f) (= 1020 #f) (>= Q 1) (= 985 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= Z 7) (= 991 #t) (= 1020 #f) (>= Q 1) (= 985 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1) (= 985 #f))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1) (= 985 #f))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (= Z 1)) (mes-load? 4096))
 (seg (? (= Z 2)) (mes-load? 4096))
 (seg (? (= Z 3)) (mes-load? 4096))
 (seg (? (= Z 7)) (mes-load? 4096))
 (seg (? (= Y 1) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 14)
      (text "も、もう許してほしいね、ご主人様の言う通りにするからっ！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "さて、どうしたもんか‥‥‥")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "ほ、ほんとうよ、ご主人様がやれって言うならどんな恥ずかしい事でもするね！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "その言葉が本当かどうかは、後でゆっくり確かめる。その前に牝猫の礼儀ってものを教えてやらなければな。")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "あうぅぅ‥‥‥酷いね、わたしを信じてほしいね‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (proc 14)
      (text "も、もう許してほしいね、ご主人様の言う通りにするからっ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 11))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 14)
      (text "はっ、はっ、はっ‥‥‥もう死んじゃいそうね！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "まったく困った牝猫だ。嬲られてるってのに＊＊＊から汚い汁を" 'br)
      (text "滴らせてやがる。")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "ごめんなさい、全部わたしが悪いね、許して‥‥‥")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "許す気はない。牝猫に礼儀を教える時は、身体に教えるにかぎる。たっぷり教育してやらないとな！")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "ああぁぁ‥‥‥わたし、本当の変態になってしまうね‥‥‥")
      (wait)
      (text-reset 14))
     (/ (proc 14) (text "はっ、はっ、はっ‥‥‥もう死んじゃいそうね！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 12) (= 623 #f))
   (proc 10)
   (proc 13)
   (text "そろそろ聞こうか、お前の仲間と事件の事を。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "な、何でも話します、全部ご主人様の言われた通りに‥‥‥")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "まず聞こう、お前はどうして軍部の機密を盗もうと思った？")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "わ、わたしはエイプリルに誘われたね。いい仕事があるから一緒にやろうって。")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "いい仕事か、一体いくらもらえばそんな危険な仕事を引き受ける気になるってんだ。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "軍を辞めても、わたしには全然仕事がないね。エイプリルは秋葉原に店を持ってて安泰だけど、わたしには何もない‥‥‥")
   (wait)
   (text-reset 14)
   (branch-reg
    57
    (</>
     (/
      (proc 13)
      (text "やっぱり、店に居たのはエイプリル本人だったのか。話が出来過ぎてると思った。")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "そうとわかれば、後は秋葉原のあの店の女を締め上げるだけだな。わたしをコケにしたらどうなるか、思い知らしてやる。")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "わたしが言ったって事は、言わないでほしいね。ご主人様、お願いです、それだけは許してほしいね！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "どうでもいい事だ。それより先を話せ。")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 81 #t))
     (/ (nop@))))
   (proc 14)
   (text "外人部隊で生き残るのは難しいね、いつか必ず死ぬ。でも軍を辞めても生きてはいけない。わたしはどうすればいいか？")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "それはわたしの知った事じゃない。クソ溜めの底でもさらってればいいだろう！")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "この国は酷すぎるね。わたしは軍を辞めて堅気で生活したかった。その為にはお金が必要、それを元手に何かしたかったね。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "そんな訳で、エイプリルから仕事を持ち掛けられた時、断る事は出来なかったね‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 623 #t)
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 12) (= 623 #t))
   (exec-mem 3072 0)
   (mes-jump "mes¥md_b3_r1.mes"))
 (seg (? (= Y 1) (= S 2))
   (sound 'se 1)
   (branch-reg
    610
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13ca.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "はうぅぅッ！　い、痛いね‥‥‥")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "ご主人様にお礼を言いな。嬲って頂いたお礼をね！")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "は、はいっ‥‥‥ご主人様、ありがとうございますっ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 610 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "はうぅぅッ！　い、痛いね‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 3))
   (sound 'se 1)
   (branch-reg
    611
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13cb.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "くぅぅぅ〜んッ！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "おやおや、いつのまにか牝猫が牝犬になっちまった。自分が猫なのを忘れちまうほど感じてるのかい！")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "ううっ、もう助けて欲しいね‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 611 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "くぅぅぅ〜んッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 4))
   (sound 'se 1)
   (branch-reg
    612
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13cc.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "あうッ！　そ、そこは‥‥‥ああッ！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "お前は、オッパイを苛められるのが大好きだったね。もっと苛めて下さいって、ご主人様にお願いするんだよ。")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "ご、ご主人様、もっと苛めて欲しいね、嫌らしいオッパイを苛めて下さい‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 612 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 14)
      (text "あうッ！　そ、そこは‥‥‥ああッ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 5))
   (sound 'se 1)
   (branch-reg
    613
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13cd.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "い、痛ッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "そこには脂肪も筋肉も付いちゃいないからね。わたしは何処をどう叩けばいいのか、よくわかってるのさ！")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "お願い、もう痛くしないで‥‥‥何でも言う事をききますから。")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 613 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "い、痛ッ‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 6))
   (sound 'se 1)
   (branch-reg
    614
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13ce.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "あふぅ‥‥‥そ、そこ！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "でかい尻だ、何処を叩いても尻に当たっちまうじゃないか。まったく叩き甲斐のある尻だよ！")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "ううっ、そんな事言わないで‥‥‥おかしくなってくるね‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 614 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "あふぅ‥‥‥そ、そこ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 7))
   (sound 'se 1)
   (branch-reg
    615
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13cf.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "んっ、くぅッ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "アソコが痺れてきたろう、お前は苛められて感じる変態の牝猫だからね。正直に気持ちいいって白状しな！")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "あふっ‥‥‥き、気持ちいいです‥‥‥わたしは変態ね‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 615 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "んっ、くぅッ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 8))
   (sound 'se 1)
   (branch-reg
    616
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13cg.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "あッ‥‥‥そ、そこ‥‥‥すごくいいね‥‥‥")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "とうとう白状したか、牝猫！　尻を苛められて気持ちいいなんて、お前は自分がどれだけ淫乱な女なのか、わかってるのか？")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "もう駄目ね、わたしは変態になっちゃったよ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 616 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 14)
      (text "あッ‥‥‥そ、そこ‥‥‥すごくいいね‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 9))
   (sound 'se 1)
   (branch-reg
    617
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13ch.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "ひぃっ！　痛いね、そこは痛いッ！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "当たり前だ、お前を悦ばせるためにやってる訳じゃないんだよ！")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "も、もう許してほしいね、わたし本当に死んじゃうね‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 617 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ひぃっ！　痛いね、そこは痛いッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 10))
   (sound 'se 1)
   (branch-reg
    618
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13ci.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "うッ！　そこは駄目ね、痛いっ！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "誰が避けていいって言った！　お前はご主人様が苛めて下さるのを甘んじて受ける事が出来ないって言うの？")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "ごめんなさい‥‥‥ごめんなさいっ、叩いて下さい！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 618 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "うッ！　そこは駄目ね、痛いっ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 11))
   (sound 'se 1)
   (branch-reg
    619
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13cj.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "くぅぅん‥‥‥な、何だかおかしくなってくるね‥‥‥")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "淫乱で恥知らずな牝猫！　＊＊＊からヨダレが滴れてるじゃない" 'br)
      (text "か。")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "は、はい‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 619 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 14)
      (text "くぅぅん‥‥‥な、何だかおかしくなってくるね‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 12))
   (sound 'se 1)
   (branch-reg
    620
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13ck.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "あッ、あふぅぅン！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "くっくっくっ‥‥‥感じてるのか？　＊＊＊にはほんの少しも触" 'br)
      (text "れてないってのに。本物の変態だね。")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "か、身体がおかしいね‥‥‥こんなの初めて‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 620 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "あッ、あふぅぅン！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 14)
      (text "ひどいね、わたしは何でもご主人様の言いなりなのに‥‥‥")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "お前があまりに呆気なく、わたしの言う通りにするのが信用できないのさ。")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "そ、そんな‥‥‥それじゃわたしはどうすればいいね！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "そいつは自分で考えな。早く答えを見つければ、それだけ鞭を食らわずに済むってもんさ。")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "お願いね‥‥‥ご主人様に生意気な口を聞いたのは、わたしの間違いだった、ごめんなさい。だからもう許してほしいね！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "それだけじゃまだ足りない。謝るだけじゃ足りないんだよ。")
      (wait)
      (text-reset 14))
     (/
      (proc 14)
      (text "ひどいね、わたしは何でもご主人様の言いなりなのに‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 11))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 14)
      (text "あうぅぅ‥‥‥ご主人様、わたしこのままじゃ死んでしまうね！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "勝手に死ぬのは許さない。お前にはもう、自分の好きに死ぬ権利さえないんだよ！")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "そんな、もうどうすればいいかわからないね‥‥‥ご主人様の命令ならどんな恥ずかしい事だって出来るのに！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "それが本心かどうか、ゆっくり調べてやる。鞭で嬲られて＊＊＊" 'br)
      (text "を濡らすような女が何を恥と思うのか、楽しみだね。")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "あぁぁ‥‥‥もう何でもするね、だからもう許して下さい。")
      (wait)
      (text-reset 14))
     (/
      (proc 14)
      (text "あうぅぅ‥‥‥ご主人様、わたしこのままじゃ死んでしまうね！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 12) (= 623 #f))
   (proc 10)
   (proc 13)
   (text "そろそろ聞こうか、お前の仲間と事件の事を。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "な、何でも話します、全部ご主人様の言われた通りに‥‥‥")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "まず聞こう、お前はどうして軍部の機密を盗もうと思った？")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "わ、わたしはエイプリルに誘われたね。いい仕事があるから一緒にやろうって。")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "いい仕事か、一体いくらもらえばそんな危険な仕事を引き受ける気になるってんだ。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "軍を辞めても、わたしには全然仕事がないね。エイプリルは秋葉原に店を持ってて安泰だけど、わたしには何もない‥‥‥")
   (wait)
   (text-reset 14)
   (branch-reg
    57
    (</>
     (/
      (proc 13)
      (text "やっぱり、店に居たのはエイプリル本人だったのか。話が出来過ぎてると思った。")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "そうとわかれば、後は秋葉原のあの店の女を締め上げるだけだな。わたしをコケにしたらどうなるか、思い知らしてやる。")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "わたしが言ったって事は、言わないでほしいね。ご主人様、お願いです、それだけは許してほしいね！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "どうでもいい事だ。それより先を話せ。")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 81 #t))
     (/ (nop@))))
   (proc 14)
   (text "外人部隊で生き残るのは難しいね、いつか必ず死ぬ。でも軍を辞めても生きてはいけない。わたしはどうすればいいか？")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "それはわたしの知った事じゃない。クソ溜めの底でもさらってればいいだろう！")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "この国は酷すぎるね。わたしは軍を辞めて堅気で生活したかった。その為にはお金が必要、それを元手に何かしたかったね。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "そんな訳で、エイプリルから仕事を持ち掛けられた時、断る事は出来なかったね‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 623 #t)
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 12) (= 623 #t))
   (exec-mem 3072 0)
   (mes-jump "mes¥md_b3_r2.mes"))
 (seg (? (= Y 2) (= S 2))
   (sound 'se 1)
   (branch-reg
    610
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13ca.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "ひッ‥‥‥お、お願いです、顔は許して下さいッ！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "そんなつもりはなかったけど、顔に生涯消えない烙印を刻んでやるのも面白いかもね。")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "そ、そんなァ‥‥‥ご主人様、本当にそれだけはッ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 610 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 14)
      (text "ひッ‥‥‥お、お願いです、顔は許して下さいッ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 3))
   (sound 'se 1)
   (branch-reg
    611
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13cb.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "あうッ！　痛い‥‥‥もう死んじゃうよ！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "死んでしまいそうなくらい、気持ちいいか。まったくなんてクソったれな牝猫なんだ。そんなにわたしをうんざりさせたいか！")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "ご、ごめんなさいっ‥‥‥わたしが悪かったです。もっと鞭で苛めて欲しいね‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 611 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 14)
      (text "あうッ！　痛い‥‥‥もう死んじゃうよ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 4))
   (sound 'se 1)
   (branch-reg
    612
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13cc.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "あふぅ‥‥‥き、気持ちいい‥‥‥もっとオッパイを苛めて！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "わたしに命令するつもり？　そんな事をしたら、どんな罰が待ってるかって事をまだ理解してないのか。")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "ご、ごめんなさい‥‥‥ご主人様、もっと鞭で苛めて欲しいです！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 612 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 14)
      (text "あふぅ‥‥‥き、気持ちいい‥‥‥もっとオッパイを苛めて！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 5))
   (sound 'se 1)
   (branch-reg
    613
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13cd.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "ううッ、わたしは従順なペットの牝猫ね‥‥‥")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "段々わかってきたじゃないか。そういう振る舞いをすれば、主人のわたしに可愛がってもらえるんだ。")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "もっとお行儀良くなるね、だからもっと鞭で苛めて！　オッパイが気持ちいいよぉ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 613 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 14)
      (text "ううッ、わたしは従順なペットの牝猫ね‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 6))
   (sound 'se 1)
   (branch-reg
    614
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13ce.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "はうッ！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "尻を鞭で打たれる気分はどうだ？　気持ちいいなら、ご主人様にお礼を言え。もっと他を苛めて欲しいなら、お願いするんだよ！")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "お、お尻が気持ちいいです。ご主人様、ありがとうございます！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 614 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "はうッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 7))
   (sound 'se 1)
   (branch-reg
    615
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13cf.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "ふ、ふぅぅん！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "なんて嫌らしい声を出すんだ。牝猫なら牝猫らしく、さかりのついた鳴き声で鳴いてみな！")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "ニャァァァ‥‥‥ニャ、ニャァァァン！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 615 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ふ、ふぅぅん！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 8))
   (sound 'se 1)
   (branch-reg
    616
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13cg.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "はうん！　そ、そこがいい、すごく感じるね‥‥‥")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "くっくっくっ‥‥‥お前はつくづく調教のし甲斐がある娘だ。苛めれば苛めるだけ牝奴隷そのものになっていく。")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "め、牝奴隷でもいい‥‥‥だから、もっと苛めて欲しいね！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 616 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 14)
      (text "はうん！　そ、そこがいい、すごく感じるね‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 9))
   (sound 'se 1)
   (branch-reg
    617
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13ch.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "んんッ！　痛い‥‥‥痛いけど、身体がおかしくなるね‥‥‥")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "それは全然悪い事じゃない。どんどんおかしくなるがいいさ。どのみち、お前はもう引き返せない所まで来ちまってるんだ！")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "うう‥‥‥わたし、どうなってしまうの‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 617 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 14)
      (text "んんッ！　痛い‥‥‥痛いけど、身体がおかしくなるね‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 10))
   (sound 'se 1)
   (branch-reg
    618
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13ci.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "ひぃぃぃン！　ご、ご主人様、もっと違う所を打って欲しいよ！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "何処を苛めて欲しいって言うんだ？　試しにお願いしてみな。もしかすると、お前の希望を叶えてやるかもしれないぞ。")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "そ、それは‥‥‥言います‥‥‥＊＊＊です、わたしのソコを苛" 'br)
      (text "めて欲しいね！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 618 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 14)
      (text "ひぃぃぃン！　ご、ご主人様、もっと違う所を打って欲しいよ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 11))
   (sound 'se 1)
   (branch-reg
    619
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13cj.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "くッ‥‥‥そ、そこじゃない、違うよ！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "いつでもお前の望みが叶うと思ったら、大間違いだ。ご主人様はどちらかって事を、もっとみっちり教えこんでやる！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 619 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 14)
      (text "くッ‥‥‥そ、そこじゃない、違うよ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 12))
   (sound 'se 1)
   (branch-reg
    620
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_13ck.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 14)
      (text "はぁぁぁん！　わ、わたしもう駄目ね、おかしくなっちゃうよ！")
      (wait)
      (text-reset 14)
      (proc 13)
      (text "おかしくなるだって？　違うね。お前は元々どうしようもない牝猫だったんだ。今に始まった事じゃないのさ。")
      (wait)
      (text-reset 14)
      (proc 14)
      (text "ああ、そんなぁ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 620 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "はぁぁぁん！　") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 6) (= S 1) (= 621 #f))
   (proc 10)
   (proc 13)
   (text "牝猫、これが何だか知っているか？")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "わ、わからないです‥‥‥ご主人様。")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "これはね、尿道カテーテルって言う物さ。こいつをお前の汚らしい穴に突っ込むんだ。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "すると‥‥‥どうなる？")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "お前は小便を垂れ流し続けるって寸法さ！　お前は牝猫だ、わたしのペットさ。どんな恥ずかしい事をされても文句はないよな。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "ああ、そんな‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 621 #t)
   (proc 11))
 (seg (? (= Y 6) (= S 1) (= 621 #t))
   (proc 10)
   (proc 13)
   (text "これはね、尿道カテーテルって言う物さ。こいつをお前の汚らしい穴に突っ込むんだ。")
   (wait)
   (text-reset 14)
   (proc 11))
 (seg (? (= Y 6) (= S 4) (= 622 #f))
   (proc 10)
   (proc 13)
   (text "まったく、この尿道カテーテルってのはよく出来てる。最高の屈辱を与える事が出来るんだ。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "元は医療用だってのが、信じられないくらいさ。こいつを突っ込まれて小便を垂れ流すのがどんなに恥ずかしいか想像がつくかい？")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "そ、それだけは許して下さい‥‥‥ご主人様ぁ！")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "甘えた声を出したって無駄さ、お前は何より恥をかかされるのがこたえるんだ。そいつはもうわかってる。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "うう‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 622 #t)
   (proc 11))
 (seg (? (= Y 6) (= S 13) (= 622 #f))
   (proc 10)
   (proc 13)
   (text "まったく、この尿道カテーテルってのはよく出来てる。最高の屈辱を与える事が出来るんだ。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "元は医療用だってのが、信じられないくらいさ。こいつを突っ込まれて小便を垂れ流すのがどんなに恥ずかしいか想像がつくかい？")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "そ、それだけは許して下さい‥‥‥ご主人様ぁ！")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "甘えた声を出したって無駄さ、お前は何より恥をかかされるのがこたえるんだ。そいつはもうわかってる。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "うう‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 622 #t)
   (proc 11))
 (seg (? (= Y 6) (= S 4) (= 622 #t))
   (proc 10)
   (proc 13)
   (text "まったく、この尿道カテーテルってのはよく出来てる。最高の屈辱を与える事が出来るんだ。")
   (wait)
   (text-reset 14)
   (proc 11))
 (seg (? (= Y 6) (= S 13) (= 622 #t))
   (proc 10)
   (proc 13)
   (text "まったく、この尿道カテーテルってのはよく出来てる。最高の屈辱を与える事が出来るんだ。")
   (wait)
   (text-reset 14)
   (proc 11))
 (seg (? (= Y 6) (= S 14) (= 624 #f))
   (proc 0)
   (exec-mem 256 "G 34 28 110 34 289")
   (exec-mem 256 "G 35 18 304 12 96")
   (image-file "gpc¥a1_13b.gpc")
   (image-mem 1 0)
   (proc 12)
   (wait)
   (proc 10)
   (proc 14)
   (text "うぐッ‥‥‥い、痛い！　やめて、痛いよォ！")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "そりゃ痛いだろうさ、尿道にこいつを突っ込まれるのは、多分考えられる限り最低の事さ。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "ううッ、あふッ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 13)
   (text "お前の＊＊＊から出てるヌルヌルのお陰で、随分やり難い‥‥‥" 'br)
   (text "よし、これでいいだろう。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "あうっ、ああ、あぁぁぁぁ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11)
   (proc 0)
   (exec-mem 256 "A 1")
   (image-file "gpc¥a1_13b1.gpc")
   (image-mem 1 0)
   (exec-mem 28672 18 304 30 399)
   (wait)
   (proc 12)
   (proc 10)
   (proc 13)
   (text "くっくっくっ、どんどん溢れ出して来るじゃないか！")
   (wait)
   (text-reset 14)
   (proc 11)
   (proc 0)
   (exec-mem 256 "A 1")
   (image-file "gpc¥a1_13b2.gpc")
   (image-mem 1 0)
   (exec-mem 28672 18 304 30 399)
   (wait)
   (proc 12)
   (proc 10)
   (proc 14)
   (text "ううっ、うっ、うっ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11)
   (proc 0)
   (exec-mem 256 "A 1")
   (image-file "gpc¥a1_13b3.gpc")
   (image-mem 1 0)
   (exec-mem 28672 18 304 30 399)
   (wait)
   (proc 12)
   (proc 10)
   (proc 13)
   (text "ははは！　なんて愉快な眺めなんだろうね！")
   (wait)
   (text-reset 14)
   (proc 11)
   (proc 0)
   (exec-mem 256 "A 1")
   (image-file "gpc¥a1_13b4.gpc")
   (image-mem 1 0)
   (exec-mem 28672 18 304 30 399)
   (wait)
   (proc 12)
   (proc 10)
   (proc 14)
   (text "はぁ、はぁ、はぁ、はっ、あぁぁぁぁ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11)
   (proc 0)
   (exec-mem 256 "A 1")
   (image-file "gpc¥a1_13b5.gpc")
   (image-mem 1 0)
   (exec-mem 28672 18 304 30 399)
   (wait)
   (proc 12)
   (proc 10)
   (proc 13)
   (text "ほらほら、動くんじゃないよ！　わたしのブーツにその臭い小便をかけてごらん、舐めて奇麗にさせるからね。")
   (wait)
   (text-reset 14)
   (proc 11)
   (proc 0)
   (exec-mem 256 "A 1")
   (image-file "gpc¥a1_13b6.gpc")
   (image-mem 1 0)
   (exec-mem 28672 18 304 30 399)
   (wait)
   (proc 12)
   (proc 10)
   (proc 14)
   (text "うぅぅッ‥‥‥")
   (wait)
   (text-reset 14)
   (exec-mem 256 "P 10 8 304")
   (exec-mem 256 "A 1")
   (image-file "gpc¥a1_13b.gpc")
   (image-mem 1 0)
   (exec-mem 28672 18 304 30 399)
   (wait)
   (proc 12)
   (proc 10)
   (proc 13)
   (text "もうお終いかい？　遠慮なく最後まで出しちまっていいんだよ。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "も、もう出ないです‥‥‥ああ、早く抜いて！")
   (wait)
   (text-reset 14)
   (exec-mem 256 "P 10 8 304")
   (mes-load? "mes¥bnkcpy2.mec" 0)
   (mes-load? 0)
   (exec-mem 256 "A 1")
   (exec-mem 256 "P 34 28 110")
   (exec-mem 256 "P 35 18 304")
   (exec-mem 28672 28 110 62 399)
   (exec-mem 28672 18 304 30 399)
   (proc 12)
   (proc 10)
   (proc 13)
   (text "さあ、もうこんなもんでいいだろう。")
   (wait)
   (text-reset 14)
   (proc 14)
   (text "あうッ！")
   (wait)
   (text-reset 14)
   (proc 11)
   (nop@)
   (inc-var H 2)
   (nop@)
   (set-reg 624 #t))
 (seg (? (= Y 6) (= S 14) (= 624 #t))
   (proc 0)
   (exec-mem 256 "G 34 28 110 34 289")
   (proc 10)
   (proc 14)
   (text "あふッ‥‥‥もう嫌ァ！")
   (wait)
   (text-reset 14)
   (exec-mem 256 "P 10 8 304")
   (proc 0)
   (image-file "gpc¥a1_13b.gpc")
   (image-mem 1 0)
   (wait)
   (proc 12)
   (proc 10)
   (proc 13)
   (text "ちっ、もう出ないみたいだな。")
   (wait)
   (text-reset 14)
   (exec-mem 256 "P 10 8 304")
   (exec-mem 256 "P 34 28 110")
   (exec-mem 256 "G 10 8 304 64 80")
   (proc 12)
   (proc 11)))