(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (nop@)
   (set-reg 980 #t)
   (set-reg 981 #t)
   (set-reg 982 #f)
   (set-reg 983 #f)
   (set-reg 984 #f)
   (set-reg 985 #f)
   (set-reg 986 #f)
   (set-reg 987 #f)
   (set-reg 988 #f)
   (set-reg 989 #f)
   (set-reg 990 #f)
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_10_a.gpc")
   (image-mem 0 3)
   (image-file "gpc¥a1_10_b.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (if (</>
        (//
         (? (= P 8))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_08.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 8))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_08v.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 8)))))
        (// (nop@))))
   (exec-mem 256 "E")
   (load-mem "clm¥A1_10a.clm" 32768)
   (load-mem "clm¥icon.clm" 20480)
   (mes-load? "mes¥icon_cl.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥icon_c2.mec" 0)
   (mes-load? 0)
   (text-frame 10 312 70 370)
   (exec-mem 256 "A 0")
   (proc 12)
   (set-var H 0)
   (proc 12)
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "よう、かわい子ちゃん。気分はどうだい？")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "なるほど、ダンマリって訳か。結構、大変結構だよ。無抵抗の女を嬲ってもちっとも面白くないからね！")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "ペッ！　あたしが何か喋ると思ってるか？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そのセリフは今までに何万回と聞いてる、もう耳タコだよ。ちなみに、そいつらのうちで最後までダンマリを通せた奴はいない。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "まあ、そういう事。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "さて、世間話はこれくらいにして、そろそろ仕事にかかろうか。慌ただしくて申し訳ないが、こっちも商売なんでね。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "な、何をするつもりか‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "その服はちと邪魔になる、脱いでもらおうか。いや、ロープを外すのは面倒だからね。ちょいとはだけてくれりゃ十分だ。")
   (wait)
   (text-reset 14)
   (proc 11)
   (proc 0)
   (image-file "gpc¥a1_10a.gpc")
   (image-mem 0 3)
   (proc 12)
   (proc 10)
   (text "「Lei-Fa」" 'br)
   (text "くッ‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "きめの細かい肌だ。わたしは白人女にはうんざりなんだ、やっぱり東洋人が一番嬲り甲斐があるね。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "何をされても喋らないね、痛いのは平気よ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "痛いのは平気よ‥‥‥か。その言葉がどこまで本当か、試してあげるよ。たっぷりとね。")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (exec-mem 256 "P 5 6 0")
   (loop
    (set-var S 0)
    (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
    (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (= Z 1) (= 991 #f))
   (proc 0)
   (exec-mem 256 "P 5 71 0")
   (nop@)
   (set-reg 991 #t)
   (exec-mem 256 "P 8 6 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 71 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 71 40))))
   (load-mem "clm¥icon2.clm" 20480)
   (proc 1))
 (seg (? (= Z 1) (= 991 #t))
   (proc 0)
   (exec-mem 256 "P 5 6 0")
   (nop@)
   (set-reg 991 #f)
   (exec-mem 256 "P 9 71 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 6 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 6 40))))
   (load-mem "clm¥icon.clm" 20480)
   (proc 1))
 (seg (? (= Z 2) (= 991 #f))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #f))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Z 2) (= 991 #t))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #t))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Y 1) (= S 1) (= H 0))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "さて、何処から苛めてやろうか‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "や、やるんなら、さっさとやるね！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そう焦りなさんな、お望み通りたっぷり苛めてやるよ。")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "お前、頭がおかしいね‥‥‥こんな事して、楽しいのか？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ああ、その通り。わたしは頭がおかしいんだ。何処からやって欲しい？　＊＊＊か、それともオッパイがいいかね。")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "か、勝手にするね！")
      (wait)
      (text-reset 14))
     (/ (text "「Lei-Fa」" 'br) (text "や、やるんなら、さっさとやるね！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 3))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "どうだい、少しは素直な気持ちになってきたかい？")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "ペッ、全然効かないね。あたしは痛いのには慣れてるからね！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "物分かりの悪い女だね、早く音を上げちまえばそれだけ辛い思いをしなくて済むってのがわからないかね。")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "お前、所詮アマチュアね。あたしがお前の拷問をする番になったら竹串を一本ずつ大切な所に刺してってやるね！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "口の減らない娘だ。そういう生意気な態度をとると、どういう事になるかたっぷり教えてやるよ！")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "やってみろ、全然何ともないね！")
      (wait)
      (text-reset 14))
     (/
      (text "「Lei-Fa」" 'br)
      (text "ペッ、全然効かないね。あたしは痛いのには慣れてるからね！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (= H 4))
   (proc 10)
   (text "「Lei-Fa」" 'br)
   (text "どうした、もっとやるね。あたしは全然平気だから！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "誰もお前の意見なんか、聞いちゃいないんだよ。止めだ、お前にはこんなもんじゃ生ぬるいようだからね。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "何をやっても同じ事ね！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "せいぜい強がってな、今に悲鳴をあげさせてみせる。さあ、立って服を脱ぐんだよ！")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "時間の無駄ね‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それ以上減らず口をたたいてみろ、素っ裸にしてビルの屋上から吊るしてやるからな！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 18688 3)
   (exec-mem 18688 5 1 0)
   (exec-mem 3072 0)
   (mes-jump "mes¥MD_B02.MES"))
 (seg (? (= Y 1) (= S 2))
   (sound 'se 1)
   (branch-reg
    592
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_10ba.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Lei-Fa」" 'br)
      (text "あッ‥‥‥くッ、何するね！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "可愛らしい＊＊＊丸見えにして、何強がってんだい。その大事な" 'br)
      (text "お道具が二度と使い物にならないようにしてやろうか？")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "か、勝手にするね‥‥‥別にどうでもいいね！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 592 #t))
     (/
      (proc 10)
      (text "「Lei-Fa」" 'br)
      (text "くッ、何するね‥‥‥そんなとこ見るな！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 3))
   (sound 'se 1)
   (branch-reg
    593
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_10bb.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Lei-Fa」" 'br)
      (text "何処を狙ってるね、そんなとこ叩かれても痛くないよ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "顔に似合わずいいオッパイじゃないの。ガキみたいにぺったんこかと思ったよ。")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "そんな挑発には乗らない。別に恥ずかしくも何ともないね。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ああそうかい、それじゃもっと恥ずかしい思いをさせてやるさ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 593 #t))
     (/
      (proc 10)
      (text "「Lei-Fa」" 'br)
      (text "何処を狙ってるね、そんなとこ叩かれても痛くないよ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 4))
   (sound 'se 1)
   (branch-reg
    594
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_10bc.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 1)
      (proc 10)
      (text "「Lei-Fa」" 'br)
      (text "あうッ！　い、痛ッ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あんまりわたしをなめるんじゃないよ。取り返しのつかない事になる前に、さっさと白状しちまいな！")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "‥‥‥‥‥‥")
      (nop@)
      (set-reg 594 #t))
     (/
      (proc 10)
      (text "「Lei-Fa」" 'br)
      (text "あうッ！　い、痛ッ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 5))
   (sound 'se 1)
   (branch-reg
    595
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_10bd.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Lei-Fa」" 'br)
      (text "くッ‥‥‥そ、そんな打ち方じゃあたしは殺せないね！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "死んでもらっちゃ困るんだよ、あんたにはその方が都合がいいだろうがね。")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "あんた、頭おかしいよ、医者に診てもらった方がいいね。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そうさ、わたしは頭がおかしいんだ。だから、早く何とかしないと何をしでかすかわからないよ。")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 595 #t))
     (/
      (proc 10)
      (text "「Lei-Fa」" 'br)
      (text "くッ‥‥‥そ、そんな打ち方じゃあたしは殺せないね！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (= H 0))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "この鞭をよく見ろ。これは革をなめして、たっぷり油を染み込ませた特別製さ。")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "今まで、これを食らって音を上げなかった奴はいない。お前だって例外じゃないさ。")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "そんな物見せられても、全然怖くないね！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "いつまでその強がりが続くか楽しみだ。囚人の血が染み付いた鞭でじっくり試してやるよ。")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "くッ‥‥‥人の顔に汚い物押し付けないねっ！")
      (wait)
      (text-reset 14))
     (/ (text "「Lei-Fa」" 'br) (text "人の顔に汚い物押し付けないねっ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 3))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Lei-Fa」" 'br)
      (text "ふぁ〜っ、眠くなってきたね！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ムカつく小娘だ。強がりもそこまでいけば立派だよ。")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "全然強がってないね、鞭なんかじゃ痛くもかゆくもないよ。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そうかい、それじゃ望み通り痛くしてやるから待ってな。舐められっぱなしじゃ済まさないからな！")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "やるだけ無駄ね、疲れるから止めといた方がいいね。")
      (wait)
      (text-reset 14))
     (/
      (text "「Lei-Fa」" 'br)
      (text "何をしても無駄ね、疲れるから止めといた方がいいね。")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (= H 4))
   (proc 10)
   (text "「Lei-Fa」" 'br)
   (text "どうした、もっとやるね。あたしは全然平気だから！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "誰もお前の意見なんか、聞いちゃいないんだよ。止めだ、お前にはこんなもんじゃ生ぬるいようだからね。")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "何をやっても同じ事ね！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "せいぜい強がってな、今に悲鳴をあげさせてみせる。さあ、立って服を脱ぐんだよ！")
   (wait)
   (text-reset 14)
   (text "「Lei-Fa」" 'br)
   (text "時間の無駄ね‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それ以上減らず口をたたいてみろ、素っ裸にしてビルの屋上から吊るしてやるからな！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 18688 3)
   (exec-mem 18688 5 1 0)
   (exec-mem 3072 0)
   (mes-jump "mes¥MD_B02.MES"))
 (seg (? (= Y 2) (= S 2))
   (sound 'se 1)
   (branch-reg
    592
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_10ba.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Lei-Fa」" 'br)
      (text "あうッ‥‥‥な、何をする、そこはダメね！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あんたでも恥ずかしいって感情があるとは、意外だった。＊＊＊" 'br)
      (text "丸出しは嫌かい、何とかして隠さないと丸見えだよ！")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "べ、別に恥ずかしくなんてないね‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 592 #t))
     (/
      (proc 10)
      (text "「Lei-Fa」" 'br)
      (text "あうッ‥‥‥な、何をする、そこはダメね！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 3))
   (sound 'se 1)
   (branch-reg
    593
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_10bb.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Lei-Fa」" 'br)
      (text "ど、何処狙ってるか。全然効かないね‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あら、なかなかいいオッパイしてるじゃない。尖った乳首がとても魅力的だわ。")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "見たいなら見ればいいね！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "見るだけじゃ物足りない。乳首が千切れるくらい強く叩いてやりたいね。あんたが泣き叫ぶまで！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 593 #t))
     (/
      (proc 10)
      (text "「Lei-Fa」" 'br)
      (text "ど、何処狙ってるか。全然効かないね‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 4))
   (sound 'se 1)
   (branch-reg
    594
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_10bc.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Lei-Fa」" 'br)
      (text "うッ‥‥‥そ、それが自慢の鞭か。大した事ないね！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "わかった。お前は鈍感な不感症女だね、だから痛みを感じないんだろう。アソコを舐められても何も感じないんじゃない？")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "そ、そんなわけないね、お前馬鹿、やってられないね！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "うろたえるところをみると、外れちゃいないらしいな。可哀想に、わたしが鞭で感じさせてやるよ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 594 #t))
     (/
      (proc 10)
      (text "「Lei-Fa」" 'br)
      (text "うッ‥‥‥そ、それが自慢の鞭か。大した事ないね！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 5))
   (sound 'se 1)
   (branch-reg
    595
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_10bd.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Lei-Fa」" 'br)
      (text "つッ‥‥‥ヘタクソ、外したね！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "外しちゃいない。あんたのその可愛い乳首が見たかったのさ。ツンと尖って可愛らしいじゃないか、色もピンクで奇麗だ。")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "お、お前に見せるためにあるんじゃないね！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あんたみたいな女でも、恥ずかしがる事があるなんて意外ね。これからもっと恥ずかしがらせてやるよ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 595 #t))
     (/
      (proc 10)
      (text "「Lei-Fa」" 'br)
      (text "つッ‥‥‥ヘタクソ、外したね！")
      (wait)
      (text-reset 14))))
   (proc 11)))