(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (proc 10)
  (text "「Kiyomi」" 'br)
  (text "お前が軍のデータベースから盗んだ情報の内容は？")
  (wait)
  (text-reset 14)
  (text "「Nana」" 'br)
  (text "ポッドモッド技術の一種でした。特殊な命令を書き込んだチップを頭骸の中に埋めこんで、能力を超人的に引き上げる‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "そんなのはよくある技術じゃないか、別に珍しくない。")
  (wait)
  (text-reset 14)
  (text "「Nana」" 'br)
  (text "あたしも詳しくは‥‥‥ただ、普通のチップ埋めこみとは、チップの容量も埋めこむ場所もちょっと違うみたいで‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "他には何を盗んだ？")
  (wait)
  (text-reset 14)
  (text "「Nana」" 'br)
  (text "ある医学データを。ポッドモッド関係って言うより、完全な医療関係の内容でした、だからあたしにはよくわからなくて‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "なんでそんな物を？　それも軍部の開発してる機構＝システムに関係があるってのか。")
  (wait)
  (text-reset 14)
  (text "「Nana」" 'br)
  (text "あたしにもわからないけど、ミツコがそれも盗めって‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "それからどうした‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Nana」" 'br)
  (text "データベースから、あたし達が盗んだ物を消去しました‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "そんな事をすれば、絶対に足がつく。優秀なハッカーだったお前がどうしてそんな馬鹿な事をした？")
  (wait)
  (text-reset 14)
  (text "「Nana」" 'br)
  (text "ミツコがそうしろって言ったから‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "またミツコか。これは是が非でもミツコを捕まえなければな。他のふたりから聞いた話もあわせて考えると‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "ミツコが事件の首謀者に間違いない。お前の恋人は何処に隠れているんだ、知らないとは言わせないぞ。")
  (wait)
  (text-reset 14)
  (text "「Nana」" 'br)
  (text "ミツコは、一緒に隠れているのは危険だからって言って‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "連絡を取りあってた訳だ、ミツコと連絡する方法は？")
  (wait)
  (text-reset 14)
  (text "「Nana」" 'br)
  (text "週に一度、東京・千葉ラインの車内で会う約束でした。あの地下鉄のです‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "ああ、知ってる。最高に治安が悪くて、まともな人間なら絶対に使わない地下鉄だな。")
  (wait)
  (text-reset 14)
  (text "「Nana」" 'br)
  (text "その地下鉄の、一番最後の車両です‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "わかった。ミツコを捕まえに行くとしよう。お前はもう用済みだ。次はミツコの番って訳。")
  (wait)
  (text-reset 14)
  (text "「Nana」" 'br)
  (text "お、お願いです‥‥‥ミツコに酷い事しないで！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "うるさい。お前はただのペットだ。ご主人様に意見する権利なんてないんだよ！")
  (wait)
  (text-reset 14)
  (text "「Nana」" 'br)
  (text "ああ、そんな！　お願いです‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "あばよ、他のお仲間とよろしくやってな！")
  (wait)
  (text-reset 14)
  (nop@)
  (set-reg 62 #t)
  (nop@)
  (set-reg 938 #t)
  (proc 11)
  (exec-mem 18688 3)
  (exec-mem 18688 5 1 0)
  (exec-mem 3072 0)
  ((cmd 209) 0 5)
  (image-file "gpc¥waku.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (exec-mem 9504 "E")
  (exec-mem 256 "I")
  (mes-jump "mes¥MA_A04.MES")))