(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (nop@)
   (set-reg 980 #t)
   (set-reg 981 #t)
   (set-reg 982 #f)
   (set-reg 983 #f)
   (set-reg 984 #f)
   (set-reg 985 #f)
   (set-reg 986 #f)
   (set-reg 987 #f)
   (set-reg 988 #f)
   (set-reg 989 #f)
   (set-reg 990 #f)
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_21.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (if (</>
        (//
         (? (= P 9))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_09.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 9))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_09v.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 9)))))
        (// (nop@))))
   (exec-mem 256 "E")
   (load-mem "clm¥A1_21.clm" 32768)
   (load-mem "clm¥icon.clm" 20480)
   (mes-load? "mes¥icon_cl.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥icon_c2.mec" 0)
   (mes-load? 0)
   (text-frame 10 312 70 370)
   (exec-mem 256 "A 0")
   (proc 12)
   (define-proc 17
     (<>
      (proc 12)
      (if (</>
           (//
            (? (>= H 5) (= 647 #f))
            (proc 0)
            (proc 5)
            (image-file "gpc¥a1_21ca.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 647 #t)
            (proc 12)
            (proc 6)
            (proc 18))
           (// (proc 12))))))
   (define-proc 18 (<> (mes-load? "mes¥md_c2pl1.mec" 4096) (exec-mem 4096)))
   (define-proc 15 (<> (text "「Kiyomi」" 'br)))
   (define-proc 16 (<> (text "「Nana」" 'br)))
   (define-proc 81
     (<>
      (if (</>
           (//
            (? (>= H 7) (= 982 #f))
            (nop@)
            (set-reg 982 #t)
            (mes-load? "mes¥icon_cl.mec" 0)
            (mes-load? 0)
            (mes-load? "mes¥icon_c2.mec" 0)
            (mes-load? 0))
           (// (nop@))))))
   (set-var H 0)
   (proc 12)
   (proc 10)
   (proc 15)
   (text "くっくっくっ、いい格好だね。なんてみっともない姿なんだ！")
   (wait)
   (text-reset 14)
   (proc 16)
   (text "ううっ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 15)
   (text "＊＊＊どころか、尻の穴まで丸見えじゃないか！　あんたの恋人のミツコにも見せてやりたいもんだね。")
   (wait)
   (text-reset 14)
   (proc 15)
   (text "あんたのその恥ずかしい姿を見たら、ミツコはどうすると思うね？目を逸らすか、それとも欲情して覆いかぶさるかもよ。")
   (wait)
   (text-reset 14)
   (proc 16)
   (text "なんでこんな目にあわなきゃならないの‥‥‥こんなの酷すぎる！")
   (wait)
   (text-reset 14)
   (proc 15)
   (text "わたしに逆らうお前が悪いんだよ。これからたっぷり時間をかけて牝豚に調教してやるのさ。")
   (wait)
   (text-reset 14)
   (proc 16)
   (text "はっ、放して‥‥‥こんなとこには居たくないわッ！")
   (wait)
   (text-reset 14)
   (proc 16)
   (text "もう嫌ぁ、こんなの嫌よォ！")
   (wait)
   (text-reset 14)
   (proc 15)
   (text "ぎゃぁぎゃぁわめくな。本当に辛いのはこれからさ！　その大きくて真っ白な尻に、鞭とロッドで奴隷の烙印を押してやる。")
   (wait)
   (text-reset 14)
   (proc 16)
   (text "ううっ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (exec-mem 256 "P 5 6 0")
   (loop
    (set-var S 0)
    (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
    (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 4) (= 991 #f) (= 1020 #f) (= Q 4) (= 982 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name3.gpc,GPC")
   (image-mem 1 0 9 64)
   (proc 1)
   (set-var Q 4))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 4) (= 991 #t) (= 1020 #f) (= Q 4) (= 982 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name3.gpc,GPC")
   (image-mem 1 0 52 64)
   (proc 1)
   (set-var Q 4))
 (seg (? (= Z 2) (= Z 3) (= Z 4) (= 991 #f) (= 1020 #f) (>= Q 1) (= 982 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= Z 4) (= 991 #t) (= 1020 #f) (>= Q 1) (= 982 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1) (= 982 #f))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1) (= 982 #f))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (= Z 1) (= 991 #f))
   (proc 0)
   (exec-mem 256 "P 5 71 0")
   (nop@)
   (set-reg 991 #t)
   (exec-mem 256 "P 8 6 0")
   (nop@)
   (set-var Y 1)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 71 163))
 (seg (? (= 1 #f))
   (exec-mem 3104 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 71 40))
 (seg*
  (set-reg 929 #f)
  (if (</>
       (//
        (? (= 982 #t))
        (exec-mem 9504 "C icon¥tool14.gpc,GPC")
        (image-mem 1 0 71 64))
       (//
        (? (= 982 #f))
        (exec-mem 9504 "C icon¥tool03.gpc,GPC")
        (image-mem 1 0 71 64))))
  (load-mem "clm¥icon2.clm" 20480)
  (proc 1))
 (seg (? (= Z 1) (= 991 #t))
   (proc 0)
   (exec-mem 256 "P 5 6 0")
   (nop@)
   (set-reg 991 #f)
   (exec-mem 256 "P 9 71 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 6 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 6 40))
        (//
         (? (= Y 3))
         (if (</>
              (//
               (? (= 982 #t))
               (exec-mem 9504 "C icon¥tool14.gpc,GPC")
               (image-mem 1 0 6 64))
              (//
               (? (= 982 #f))
               (exec-mem 9504 "C icon¥tool03.gpc,GPC")
               (image-mem 1 0 6 64)))))))
   (load-mem "clm¥icon.clm" 20480)
   (proc 1))
 (seg (? (= Z 2) (= 991 #f))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 6 40)
   (if (</>
        (//
         (? (= 982 #t))
         (exec-mem 9504 "C icon¥tool25.gpc,GPC")
         (image-mem 1 0 6 64))
        (// (nop@))))
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #f))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 6 16)
   (if (</>
        (//
         (? (= 982 #t))
         (exec-mem 9504 "C icon¥tool25.gpc,GPC")
         (image-mem 1 0 6 64))
        (// (nop@))))
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Z 2) (= 991 #t))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 71 40)
   (if (</>
        (//
         (? (= 982 #t))
         (exec-mem 9504 "C icon¥tool25.gpc,GPC")
         (image-mem 1 0 71 64))
        (// (nop@))))
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #t))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 71 16)
   (if (</>
        (//
         (? (= 982 #t))
         (exec-mem 9504 "C icon¥tool25.gpc,GPC")
         (image-mem 1 0 71 64))
        (// (nop@))))
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Z 4) (= 991 #f) (= 982 #t))
   (nop@)
   (set-var Y 3)
   (proc 0)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 9504 "C icon¥tool14.gpc,GPC")
   (image-mem 1 0 6 64)
   (exec-mem 18688 5 5 1)
   (proc 1)
   (exec-mem 18688 2 4))
 (seg (? (= Z 4) (= 991 #t) (= 982 #t))
   (nop@)
   (set-var Y 3)
   (proc 0)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 9504 "C icon¥tool14.gpc,GPC")
   (image-mem 1 0 71 64)
   (exec-mem 18688 5 5 1)
   (proc 1)
   (exec-mem 18688 2 4))
 (seg (? (= Y 1) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 15)
      (text "くっくっくっ‥‥‥なんて格好だい。＊＊＊どころか尻の穴まで丸見えだ。恥ずかしいったらありゃしないね！")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "な、何よあんたがやったんでしょう！")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "まだまだこんなもんじゃないからね。わたしのロッドで、＊＊＊からうれし涙を流させてやるよ。")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "あんたなんかの言いなりになんて、ならないんだから。何があっても絶対に！")
      (wait)
      (text-reset 14))
     (/
      (proc 16)
      (text "あんたなんかの言いなりになんて、ならないんだから。何があっても絶対に！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 8))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 16)
      (text "うッ、ううぅぅ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "だいぶ参っちまってるようだね。わたしの手にかかれば他愛ないもんさ。そろそろ終わりにしてやろうか？")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "ど、どうせ止めてくれないんでしょう‥‥‥わかってるのよ。あたしが苦しんでるのを見るのが、楽しくて仕方ないのよ！")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "その通り！　お前だけは許すつもりはない、わたしはお前を気に入っているからね。完全な牝奴隷に調教してやるのさ。")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "どうしてこんな事になっちゃったの、あたしはただのハッカーなのに。自分の仕事をしただけなのよ‥‥‥")
      (wait)
      (text-reset 14))
     (/ (proc 16) (text "うッ、ううぅぅ‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 11))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 16)
      (text "はぁ、はぁ、はぁ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "もうたまらないって顔をしてるよ。＊＊＊からはお汁が垂れて、乳首も固くなってる。")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "こんなの変だわ。こんな感じ、初めてなの‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "お前は生まれついての牝豚さ。苛められて感じるマゾの牝豚だよ！自分が牝豚なのを認めて、もっと激しく苛めてってお願いしな。")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "ううっ‥‥‥も、もっと‥‥‥もっと激しく苛めて下さいッ！")
      (wait)
      (text-reset 14))
     (/ (proc 16) (text "はぁ、はぁ、はぁ‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 12)) (mes-jump "mes¥md_c2_r1.mes"))
 (seg (? (= Y 1) (= S 2))
   (sound 'se 1)
   (branch-reg
    633
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21cb.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "あうッ、痛い‥‥‥嫌ァ！")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "牝豚に何か教える時は、身体に教えてやらないとね。誰が主人なのかしっかり覚えるんだよッ。")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "ああ、助けてぇ‥‥‥ミツコ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 633 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "あうッ、痛い‥‥‥嫌ァ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 3))
   (sound 'se 1)
   (branch-reg
    634
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21cc.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "くぅっ、そこ‥‥‥駄目、オッパイは駄目なのッ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "駄目じゃないんだよ、気持ちいいなら素直にそう言いな！")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "だ、誰が‥‥‥そんな事ないもん！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 634 #t)
      (proc 81))
     (/
      (proc 10)
      (proc 16)
      (text "くぅっ、そこ‥‥‥駄目、オッパイは駄目なのッ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 4))
   (sound 'se 1)
   (branch-reg
    635
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21cd.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "はッ、はうぅぅんッ！")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "どうやらオッパイを苛められるのが好きみたいね。ロッドで叩かれて感じるなんて、やっぱりお前は変態のマゾ女だよ！")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "そ、そんな‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 635 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "はッ、はうぅぅんッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 5))
   (sound 'se 1)
   (branch-reg
    636
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21ce.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "くッ！　い、痛いッ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "もっと別な場所がお望みかい？　だったらそう言ってみな。お前の希望を叶えてやるかもしれないよ！")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "き、希望なんてないわ‥‥‥殺してほしいだけよ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 636 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "くッ！　い、痛いッ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 6))
   (sound 'se 1)
   (branch-reg
    637
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21cf.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "あッ、あうッ！")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "さあ、どんどんいくよ！　休ませてなんかやるもんか。死ぬまで叩き続けてやる。")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "ああ、もう死んじゃう‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 637 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "あッ、あうッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 7))
   (sound 'se 1)
   (branch-reg
    638
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21cg.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "ひッ、ひぃぃぃッ！")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "＊＊＊から何か溢れてきたみたいだ。そいつは何だ、白状しな！" 'br)
      (text "その小便みたいなのは何だって聞いてるんだよ。")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "な、何でもないです‥‥‥見ないでッ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 638 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "ひッ、ひぃぃぃッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 8))
   (sound 'se 1)
   (branch-reg
    639
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21ch.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "くふぅッ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "牝豚が鳴き声をあげてやがる。それに酷い臭いだ、この臭いは何処から匂ってくるんだい！")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "そ、それはぁ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 639 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "くふぅッ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 9))
   (sound 'se 1)
   (branch-reg
    640
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21ci.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "んふッ‥‥‥そ、そこは駄目ッ！")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "この変態の牝豚、気分が悪くなってくるよ。＊＊＊を苛められて" 'br)
      (text "感じるなんてとんでもない奴だよ！")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "ああ、何だか変よッ‥‥‥こんなの！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 640 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "んふッ‥‥‥そ、そこは駄目ッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 10))
   (sound 'se 1)
   (branch-reg
    641
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21cj.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "あううッ、そこは駄目ぇ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "もう＊＊＊が洪水になってる。さすがは牝豚だね、調教のし甲斐" 'br)
      (text "がある女だよ。本当にお前は！")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "こ、こんなはずじゃなかったのにぃ‥‥‥")
      (nop@)
      (set-reg 641 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "あううッ、そこは駄目ぇ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 11))
   (sound 'se 1)
   (branch-reg
    642
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21ck.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "うっ、ううッ！")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "ほらほら、段々＊＊＊に近づいてるよ！　大事なお道具を嬲られ" 'br)
      (text "て失神しないように気をつけな。")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "もう嫌、こんなの堪えられない‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 642 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "うっ、ううッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 12))
   (sound 'se 1)
   (branch-reg
    643
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21cl.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "あぐぅ‥‥‥あぁぁッ！")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "牝豚らしい声になってきたじゃないか。お前の可愛らしい口から、そんな鳴き声を聞けるとは思わなかったよ！")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "はぁ、はぁ、はぁ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 643 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "あぐぅ‥‥‥あぁぁッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 16)
      (text "一体何なのよこれは‥‥‥吐き気がしてきたわ！")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "自分の今してる格好を、よく見てから言いなよ。全然説得力がないんじゃないの？")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "くッ‥‥‥なんであたしがこんな格好しなきゃいけないのよッ！")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "ゆっくりと調教してやるから、感謝しな。もう少しすればお前は別の人間になってる。完全な牝奴隷になるのさ。")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "誰が‥‥‥あんたなんかの言いなりになるもんか‥‥‥")
      (wait)
      (text-reset 14))
     (/ (proc 16) (text "一体何なのよこれは‥‥‥吐き気がしてきたわ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 8))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 16)
      (text "ううぅぅッ、もう駄目‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "何が駄目だって言うんだい、自分の好きなようにすりゃいい。もうたまらないんだろう、素直に白状しちまいな。")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "じ、冗談じゃないわ、どうしてあたしがッ！")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "忘れちまいな、てめえの過去を。安っぽいプライドも、ミツコも！そんなのは詰まらない事さ。")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "堕ちちまえばいいんだ。行くとこまで行っちまえばいいのさ‥‥‥")
      (wait)
      (text-reset 14))
     (/ (proc 16) (text "ううぅぅッ、もう駄目‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 11))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 16)
      (text "ああ、死んじゃう‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "死んじまう程いいか。今さら嘘をついても無駄な事さ、お前の身体を見ればわかる。")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "そんな‥‥‥そんな事、ないわ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "それじゃ、その汚い汁を滴らせてる＊＊＊は何なんだ。感じてる" 'br)
      (text "んじゃないのかい。尻の穴をヒクヒクさせやがって！")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "い、嫌ァ‥‥‥言わないでッ！")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "この牝豚め！　お前は奴隷以下の家畜だ、一人前の口をきくんじゃないよ。家畜らしい態度を教えこんでやるからな！")
      (wait)
      (text-reset 14))
     (/ (proc 16) (text "ああ、死んじゃう‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 12)) (mes-jump "mes¥md_c2_r2.mes"))
 (seg (? (= Y 2) (= S 2))
   (sound 'se 1)
   (branch-reg
    633
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21cb.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "んっくッ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "皮が擦り切れて血が滲んできた。いい色だ、たまんないね！")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "こ、殺さないでっ、お願い‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 633 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "んっくッ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 3))
   (sound 'se 1)
   (branch-reg
    634
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21cc.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "はうッ、あたし‥‥‥もう駄目ぇ！")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "駄目だったらどうするってんだい。家畜に鞭を使うのは当たり前の事さ。牝豚を躾るには鞭が必要だ、そうだろう？")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "は、はいッ‥‥‥そうです‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 634 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "はうッ、あたし‥‥‥もう駄目ぇ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 4))
   (sound 'se 1)
   (branch-reg
    635
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21cd.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "ううッ、そこは駄目ぇ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "早く何とかしないと、オッパイが無くなっちまうよ。わたしはそうしてやってもいいんだ。")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "や、止めて‥‥‥それだけは、お願いですぅ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 635 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "ううッ、そこは駄目ぇ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 5))
   (sound 'se 1)
   (branch-reg
    636
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21ce.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "んくッ、痛い、嫌ァ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "もっともっと痛くしてやる、お前はそれを望んでいるんだ！")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "ああ、もう死んだ方がましよ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 636 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "んくッ、痛い、嫌ァ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 6))
   (sound 'se 1)
   (branch-reg
    637
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21cf.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "ひッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "いい音だ、太股がはち切れそうだ。お前が従順なペットにならないのなら、鞭を剃刀みたいに扱う事だって出来るんだぞ。")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 637 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "ひッ‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 7))
   (sound 'se 1)
   (branch-reg
    638
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21cg.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "はァァン！　お、お尻は許してぇ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "でかい尻だね、目をつぶってても当たりそうだ！　当分は椅子に座るだけで辛いだろうね。")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "死んじゃう‥‥‥もう死んじゃう！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 638 #t)
      (proc 81))
     (/
      (proc 10)
      (proc 16)
      (text "はァァン！　お、お尻は許してぇ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 8))
   (sound 'se 1)
   (branch-reg
    639
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21ch.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "ひっ、ひぃぃぃッ！")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "可哀想に＊＊＊の端が切れちまったね。でも、血よりネバネバし" 'br)
      (text "た汁が溢れてるのは何故だい？")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "ああ、そんな‥‥‥変だわ、身体が‥‥‥身体が熱いッ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 639 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "ひっ、ひぃぃぃッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 9))
   (sound 'se 1)
   (branch-reg
    640
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21ci.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "くふっ！　そ、そこはァ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "その臭い汁を何とかしな！　ご主人様の目の前に＊＊＊を向けて" 'br)
      (text "るんだ、ちょっと考えたらどうだい。臭くってたまんないよ！")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "止めて、そんなの酷いわ‥‥‥もう嫌ァ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 640 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "くふっ！　そ、そこはァ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 10))
   (sound 'se 1)
   (branch-reg
    641
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21cj.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "ひぃぃぃッ！")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "おっと、お尻の穴に傷を付けちまった！　それじゃトイレにも行けないねぇ。")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "うっ、うっ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 641 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "ひぃぃぃッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 11))
   (sound 'se 1)
   (branch-reg
    642
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21ck.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "くぅッ‥‥‥そ、そこッ！")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "何処だって？　お前は＊＊＊を鞭で嬲られるのがいいってのか？" 'br)
      (text "＊＊＊を鞭で打って欲しいんだね！")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "は、はい‥‥‥そうです‥‥‥＊＊＊が‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 642 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "くぅッ‥‥‥そ、そこッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 12))
   (sound 'se 1)
   (branch-reg
    643
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_21cl.gpc")
      (image-mem 1 0)
      (proc 17)
      (proc 10)
      (proc 16)
      (text "ううッ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 15)
      (text "ほんとに可愛いお尻だこと。目の前にあると鞭で苛めずにはいられないお尻だよ。牝豚には過ぎた持ち物だね！")
      (wait)
      (text-reset 14)
      (proc 16)
      (text "い、痛い‥‥‥痛いの‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 643 #t)
      (proc 81))
     (/ (proc 10) (proc 16) (text "ううッ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 3) (= S 1) (= 644 #f) (>= H 1))
   (proc 10)
   (proc 15)
   (text "これが何だかわかるだろう、見た事もないとは言わせないぞ。")
   (wait)
   (text-reset 14)
   (proc 16)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 15)
   (text "こいつを＊＊＊に突っ込んで欲しいんだろう？　正直にお願いす" 'br)
   (text "れば、たっぷりやってやるぞ。")
   (wait)
   (text-reset 14)
   (proc 16)
   (text "そ、そんな物‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 15)
   (text "我慢すると身体に悪いぞ。お前のそこからは、ヌルヌルの汁が溢れ出しているじゃないか！")
   (wait)
   (text-reset 14)
   (proc 16)
   (text "お、お願いです‥‥‥それを入れて！")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 644 #t)
   (proc 11))
 (seg (? (= Y 3) (= S 1) (= 644 #t))
   (proc 10)
   (proc 16)
   (text "お、お願いです‥‥‥それを入れて！")
   (wait)
   (text-reset 14)
   (proc 11))
 (seg (? (= Y 3) (>= S 3) (<= S 4) (= 645 #f))
   (proc 10)
   (proc 16)
   (text "あうっ！　嫌っ、それをどけてぇ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 15)
   (text "乳首を固くおっ立てて、何をお高くとまってんだよ！　こいつが欲しくてたまんないんだろう。")
   (wait)
   (text-reset 14)
   (proc 15)
   (text "ミツコとする時も、こんなのを使ってたのか？")
   (wait)
   (text-reset 14)
   (proc 16)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 15)
   (text "答えるんだ！　ミツコとよろしくやる時も、バイブを使っていたのかって聞いてるんだよ。")
   (wait)
   (text-reset 14)
   (proc 16)
   (text "つ、使ってました‥‥‥お願い、意地悪しないで‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 645 #t)
   (proc 11))
 (seg (? (= Y 3) (>= S 3) (<= S 4) (= 645 #t))
   (proc 10)
   (proc 16)
   (text "あうっ！　嫌っ、それをどけてぇ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11))
 (seg (? (= Y 3) (= S 13) (= 646 #f))
   (proc 10)
   (inc-var H 1)
   (proc 15)
   (text "グチュグチュの＊＊＊に、こいつを突っ込んでやる！")
   (wait)
   (text-reset 14)
   (proc 16)
   (text "はっ、早く‥‥‥ああ、意地悪しないで‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11)
   (proc 0)
   (proc 5)
   (exec-mem 256 "G 30 3 112 17 184")
   (exec-mem 256 "G 31 49 120 20 93")
   (image-file "gpc¥a1_21b.gpc")
   (image-mem 1 0)
   ((cmd 193) 0 "gpa¥a1_21.gpa")
   ((cmd 194) 0 "ｲ....ｳ....ｴ....ｱ....")
   ((cmd 195) 0 65535)
   (proc 10)
   (proc 16)
   (text "はうぅぅッ‥‥‥")
   (wait)
   (text-reset 14)
   ((cmd 195) 0 65535)
   (proc 15)
   (text "あっと言う間に" '|34898|)
   (text "み込んじまった。お前の＊＊＊はバイブが大好" 'br)
   (text "きなんだな！")
   (wait)
   (text-reset 14)
   ((cmd 195) 0 65535)
   (proc 16)
   (text "はっ、はっ、はっ‥‥‥んっ、んんんッ！")
   (wait)
   (text-reset 14)
   (proc 15)
   ((cmd 195) 0 65535)
   (text "＊＊＊がパックリ口を開いて‥‥‥わたしの指まで" '|34898|)
   (text "み込んでし" 'br)
   (text "まいそうだ。よっぽどこれが欲しかったんだな。")
   (wait)
   (text-reset 14)
   ((cmd 195) 0 65535)
   (proc 16)
   (text "ああ、いい‥‥‥死んじゃいそう‥‥‥")
   (wait)
   (text-reset 14)
   (proc 15)
   ((cmd 195) 0 65535)
   (text "貪欲な牝豚、まさにそんな感じだ。")
   (wait)
   (text-reset 14)
   (proc 16)
   ((cmd 195) 0 65535)
   (text "ううッ、うッ‥‥‥そ、そうです、あたしは牝豚ですッ！")
   (wait)
   (text-reset 14)
   (proc 16)
   ((cmd 195) 0 65535)
   (text "だから、もっと奥まで‥‥‥ああ、かき回して！")
   (wait)
   (text-reset 14)
   (proc 15)
   ((cmd 195) 0 65535)
   (text "くっくっくっ、また一匹ペットが手に入った訳だ。たまんないね。だからこの仕事は辞められないんだよ。")
   (wait)
   (text-reset 14)
   (proc 11)
   ((cmd 195) 0 0)
   (exec-mem 3072 0)
   (exec-mem 256 "P 30 3 112")
   (exec-mem 256 "P 31 49 120")
   (proc 12)
   (proc 6)
   (branch-reg
    991
    (</>
     (/ (exec-mem 9504 "C icon¥tool14.gpc,GPC") (image-mem 1 0 6 64))
     (/ (exec-mem 9504 "C icon¥tool14.gpc,GPC") (image-mem 1 0 71 64))))
   (proc 10)
   (proc 16)
   (text "アッ、嫌ぁ‥‥‥抜いちゃ駄目ぇ！")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 646 #t)
   (proc 11))
 (seg (? (= Y 3) (= S 13) (= 646 #t))
   (proc 0)
   (proc 5)
   (exec-mem 256 "G 30 3 112 17 184")
   (exec-mem 256 "G 31 49 120 20 93")
   (image-file "gpc¥a1_21b.gpc")
   (image-mem 1 0)
   ((cmd 195) 0 65535)
   (proc 10)
   (proc 16)
   ((cmd 195) 0 65535)
   (text "あふッ、ふぅぅん！")
   (wait)
   (text-reset 14)
   (proc 15)
   ((cmd 195) 0 65535)
   (text "まるで電気仕掛けの人形だね。バイブのスイッチを入れれば途端に尻を振って踊りだす。")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3072 0)
   (exec-mem 256 "P 30 3 112")
   (exec-mem 256 "P 31 49 120")
   (proc 12)
   (proc 6)
   (branch-reg
    991
    (</>
     (/ (exec-mem 9504 "C icon¥tool14.gpc,GPC") (image-mem 1 0 6 64))
     (/ (exec-mem 9504 "C icon¥tool14.gpc,GPC") (image-mem 1 0 71 64))))
   ((cmd 195) 0 0)
   (proc 10)
   (proc 16)
   (text "アッ、嫌ぁ‥‥‥抜いちゃ駄目ぇ！")
   (wait)
   (text-reset 14)
   (proc 11))
 (seg*))