(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (nop@)
   (set-reg 980 #t)
   (set-reg 981 #t)
   (set-reg 982 #f)
   (set-reg 983 #f)
   (set-reg 984 #f)
   (set-reg 985 #f)
   (set-reg 986 #f)
   (set-reg 987 #f)
   (set-reg 988 #f)
   (set-reg 989 #f)
   (set-reg 990 #f)
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_22.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (if (</>
        (//
         (? (= P 9))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_09.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 9))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_09v.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 9)))))
        (// (nop@))))
   (exec-mem 256 "E")
   (load-mem "clm¥A1_22.clm" 32768)
   (load-mem "clm¥icon.clm" 20480)
   (mes-load? "mes¥icon_cl.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥icon_c2.mec" 0)
   (mes-load? 0)
   (text-frame 10 312 70 370)
   (exec-mem 256 "A 0")
   (proc 12)
   (define-proc 19
     (<>
      (if (</>
           (//
            (? (>= H 9) (= 986 #f))
            (nop@)
            (set-reg 986 #t)
            (mes-load? "mes¥icon_cl.mec" 0)
            (mes-load? 0)
            (mes-load? "mes¥icon_c2.mec" 0)
            (mes-load? 0))
           (// (nop@))))))
   (define-proc 15
     (<>
      (proc 12)
      (if (</>
           (//
            (? (>= H 8) (= 665 #f))
            (proc 0)
            (proc 16)
            (proc 12)
            (nop@)
            (set-reg 665 #t))
           (//
            (? (>= H 4) (= 659 #f))
            (proc 0)
            (image-file "gpc¥a1_22a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 659 #t)
            (proc 12))
           (// (nop@))))))
   (define-proc 14
     (<>
      (exec-mem 256 "G 44 31 186 6 71")
      (exec-mem 256 "G 45 28 330 10 349")
      (mes-load? "mes¥bnkcpy2.mec" 0)
      (mes-load? 0)))
   (define-proc 16
     (<>
      (proc 14)
      (mes-load? "mes¥md_c3ani.mec" 0)
      (mes-load? 0)
      (exec-mem 256 "P 44 31 186")
      (exec-mem 256 "P 45 28 330")
      (proc 12)))
   (define-proc 17 (<> (text "「Kiyomi」" 'br)))
   (define-proc 18 (<> (text "「Nana」" 'br)))
   (define-proc 13 (<> (wait) (text-reset 14)))
   (set-var H 0)
   (proc 12)
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "体を洗ってやって、ようやく臭いが消えたようだね。まったく鼻が曲がっちまいそうな臭さだったよ！")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "はぁ、はぁ、はぁ‥‥‥お願い、早く！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "がっつくんじゃないよ牝豚。みっともないったらありゃしない。そんな事じゃわたしの気に入るペットにはなれないよ。")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "だって、もう我慢が‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "全くの別人みたいだ、お前はそんな女じゃなかったはずだ。勘違いするなよ、わたしはお前を悦ばせるためにやってるんじゃない。")
   (wait)
   (text-reset 14)
   (text "「Nana」" 'br)
   (text "何でもいいから‥‥‥早くッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ちっ、しょうがない女だね。本物の牝豚だよ！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (exec-mem 256 "P 5 6 0")
   (mes-load? "mes¥md_c3pl2.mec" 4096)
   (mes-jump "mes¥md_c3_ms.mes")))