(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (loop
   (set-var S 0)
   (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
   (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 8) (= 991 #f) (= 1020 #f) (= Q 8) (= 986 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name7.gpc,GPC")
   (image-mem 1 0 9 160)
   (proc 1)
   (set-var Q 8))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 8) (= 991 #t) (= 1020 #f) (= Q 8) (= 986 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name7.gpc,GPC")
   (image-mem 1 0 52 160)
   (proc 1)
   (set-var Q 8))
 (seg (? (= Z 2) (= Z 3) (= Z 8) (= 991 #f) (= 1020 #f) (>= Q 1) (= 986 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= Z 8) (= 991 #t) (= 1020 #f) (>= Q 1) (= 986 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1) (= 986 #f))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1) (= 986 #f))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (= Z 1)) (mes-load? 4096))
 (seg (? (= Z 2)) (mes-load? 4096))
 (seg (? (= Z 3)) (mes-load? 4096))
 (seg (? (= Z 8)) (mes-load? 4096))
 (seg (? (= Y 1) (= S 1) (<= H 4))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 18)
      (text "ううッ‥‥‥もう我慢できないッ！")
      (proc 13)
      (proc 17)
      (text "お前の座ってるその椅子は安くないんだよ。そいつを汚したらただじゃ済まさないから、そのつもりでな！")
      (proc 13)
      (proc 18)
      (text "は、はい‥‥‥ご主人様の言われた通りにしますッ！")
      (proc 13)
      (proc 17)
      (text "よしよし、いい子だ。ペットは主人の言いつけを守らなきゃいけないんだ。もしも破ったらどうなるか、わかってるだろうね？")
      (proc 13)
      (proc 18)
      (text "何でも言うことをききます、だからッ！")
      (proc 13))
     (/
      (proc 17)
      (text "お前の座ってるその椅子は安くないんだよ。そいつを汚したらただじゃ済まさないから、そのつもりでな！")
      (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 8))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 18)
      (text "はっ、早くぅ‥‥‥もっとやって！")
      (proc 13)
      (proc 17)
      (text "ちっ、なんて女だ。こんな牝豚は初めて見たよ。こんなマゾ女には滅多にお目にかかれないだろうね。")
      (proc 13)
      (proc 18)
      (text "なんでも喋るわ、だからお願いよォ‥‥‥")
      (proc 13)
      (proc 17)
      (text "がっつくんじゃないよ。今望み通りにしてやる。何処を苛めて欲しいかお願いしな！")
      (proc 13)
      (proc 18)
      (text "＊＊＊‥‥‥＊＊＊を苛めて欲しいのォ‥‥‥")
      (proc 13))
     (/ (proc 18) (text "はっ、早くぅ‥‥‥もっとやって！") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 12))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 18)
      (text "んッ‥‥‥はぁ、はぁ、はぁ、んんッ！")
      (proc 13)
      (proc 17)
      (text "そろそろいいかい、満足した？")
      (proc 13)
      (proc 18)
      (text "まだ駄目、もう少しなの‥‥‥")
      (proc 13)
      (proc 17)
      (text "おやおや、何て貧欲な娘なんだろうね。これだけ嬲ってやったのにまだ足りないってのかい？")
      (proc 13)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥")
      (proc 13)
      (proc 17)
      (text "仕方ないね、もう少し苛めてやろう。そのかわり、後でちゃんと質問に答えるんだぞ。")
      (proc 13))
     (/ (proc 18) (text "んッ‥‥‥はぁ、はぁ、はぁ、んんッ！") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 13) (= 644 #f))
   (proc 10)
   (proc 17)
   (text "さあ、遊びはもう終わりだ。わたしの質問に答えてもらうよ。まさか今さら嫌だとは言わないだろうね？")
   (proc 13)
   (proc 18)
   (text "は、はい‥‥‥何でも喋ります‥‥‥")
   (proc 13)
   (proc 17)
   (text "まずは、お前がどうやって軍のデータベースをハッキングしたかを聞こうか。それはかなり無謀な事だったんだろう？")
   (proc 13)
   (proc 18)
   (text "サイバースペースで見ると、軍のデータベースは数キロ四方の巨大なマトリクスです‥‥‥")
   (proc 13)
   (proc 18)
   (text "大抵のハッカーは、それを見ただけで臆してしまう‥‥‥")
   (proc 13)
   (proc 17)
   (text "なのに、どうしてお前はそれに手を出した。")
   (proc 13)
   (proc 18)
   (text "エイプリルとレイファが仲間だったから‥‥‥あの子達は自由に軍の施設に出入り出来ました‥‥‥")
   (proc 13)
   (proc 18)
   (text "基地への送電設備を破壊させて、マトリクスを麻痺させました。普通のハッカーにはそんな事は出来ません。超荒業ですから‥‥‥")
   (proc 13)
   (proc 17)
   (text "すると、どうなるってんだ？　プロテクトが外れる訳じゃないだろう。わたしはローテクだからわかんないけど。")
   (proc 13)
   (proc 18)
   (text "送電が止まると、補助電源に変わるんだけど‥‥‥マトリクスは外部からの侵入を防ぐ為に、一瞬で収縮するんです。")
   (proc 13)
   (proc 17)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (proc 13)
   (proc 18)
   (text "あたしは、その瞬間を待って数時間前からマトリクスの外側に張り付いてた。巧妙に偽装して、その一部に化けるの‥‥‥")
   (proc 13)
   (proc 17)
   (text "なるほど、さっぱりわからない。とにかくデータベースの中に入り込んで、軍が開発中のシステムの情報だけを盗んだ。")
   (proc 13)
   (proc 18)
   (text "それの所在はわかってました‥‥‥ミツコが何処からか情報を持って来て、データベースのどの辺りに隠されてるかも知ってた。")
   (proc 13)
   (proc 17)
   (text "するってえと、軍の開発したシステムのネタはミツコが持って来たのか。ミツコはそのネタをどうやって手に入れた？")
   (proc 13)
   (proc 18)
   (text "そ、それは知りません‥‥‥ミツコに聞かないと‥‥‥")
   (proc 13)
   (nop@)
   (set-reg 644 #t)
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 13) (= 644 #t)) (mes-jump "mes¥md_c3_r1.mes"))
 (seg (? (= Y 1) (= S 6))
   (sound 'se 1)
   (branch-reg
    649
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_22ca.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "あっくッ！　い、痛ぁい‥‥‥")
      (proc 13)
      (proc 17)
      (text "痛くて気持ちいいんだろう？　それとも、＊＊＊を直接苛められ" 'br)
      (text "た方が好みなのか。")
      (proc 13)
      (proc 18)
      (text "きっ、気持ちいいです、すごく‥‥‥‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 649 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あっくッ！　い、痛ぁい‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 7))
   (sound 'se 1)
   (branch-reg
    650
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_22cb.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "くふっ、そこじゃないの‥‥‥")
      (proc 13)
      (proc 17)
      (text "何処だろうと同じ事さ、お前みたいな牝豚は、何処を苛められてもヨダレ滴らして悦んじまうのさ！")
      (proc 13)
      (proc 18)
      (text "うう‥‥‥お願いです、もっと気持ちよくしてぇ！")
      (proc 13)
      (nop@)
      (set-reg 650 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "くふっ、そこじゃないの‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 8))
   (sound 'se 1)
   (branch-reg
    651
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_22cc.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "はんッ！　お、お腹はぁ‥‥‥")
      (proc 13)
      (proc 17)
      (text "腹だけじゃない、身体中を傷だらけにしてやるよ！　牝豚にはそっちのが似合いだろう。")
      (proc 13)
      (proc 18)
      (text "ど、どうしてこんなに‥‥‥こんなに気持ちいいの‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 651 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "はんッ！　お、お腹はぁ‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 9))
   (sound 'se 1)
   (branch-reg
    652
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_22cd.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "ああぁぁっ‥‥‥そこじゃないの、もっと下を！")
      (proc 13)
      (proc 17)
      (text "そうはいかないよ。＊＊＊は駄目さ、そこ以外でも感じられるよ" 'br)
      (text "うにしてやるんだ、本物のＭ女にね！")
      (proc 13)
      (proc 18)
      (text "もう駄目‥‥‥アソコが熱いの‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 652 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ああぁぁっ‥‥‥そこじゃないの、もっと下を！") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 10))
   (sound 'se 1)
   (branch-reg
    653
    (</>
     (/
      (nop@)
      (set-reg 653 #t)
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_22ce.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "んんっ‥‥‥")
      (proc 13)
      (proc 17)
      (text "気持ちいいかい、ええ牝豚！　苛めて下さったご主人様にお礼はどうした？")
      (proc 13)
      (proc 18)
      (text "は、はい‥‥‥ご主人様‥‥‥ありがとうございましたッ！")
      (proc 13)
      (nop@)
      (set-reg 653 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "んんっ‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 11))
   (sound 'se 1)
   (branch-reg
    654
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_22cf.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "はうぅぅッ‥‥‥そ、そこっ、気持ちいいのッ！")
      (proc 13)
      (proc 17)
      (text "うるさいんだよ牝豚、ピィピィわめくんじゃない！　それ以上一言でも喋ってみろ、二度と口がきけないようにしてやる。")
      (proc 13)
      (proc 18)
      (text "ああ、そんな‥‥‥そんなの無理ですぅ‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 654 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "はうぅぅッ‥‥‥そ、そこっ、気持ちいいのッ！") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 12))
   (sound 'se 1)
   (branch-reg
    655
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_22cg.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "んくッ、もう死んじゃいそう‥‥‥")
      (proc 13)
      (proc 17)
      (text "勝手に死ぬんじゃないよ、お前はわたしのペットだ。好きな時に死ぬ権利さえないんだ！")
      (proc 13)
      (proc 18)
      (text "は、はいッ！　ご主人様の命令通りにします‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 655 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "んくッ、もう死んじゃいそう‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 13))
   (sound 'se 1)
   (branch-reg
    656
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_22ch.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "ひッ、ひぃぃぃッ！")
      (proc 13)
      (proc 17)
      (text "オッパイを苛められるのが、そんなに気持ちいいのかい？")
      (proc 13)
      (proc 18)
      (text "はいッ、気持ちいいです‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 656 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ひッ、ひぃぃぃッ！") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 14))
   (sound 'se 1)
   (branch-reg
    657
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_22ci.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "くっ、くぅぅんッ！")
      (proc 13)
      (proc 17)
      (text "お前は何処を苛められても感じる、根っからの牝豚だ。ペット以下の家畜だ！")
      (proc 13)
      (proc 18)
      (text "はぁ、はぁ、はぁ‥‥‥‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 657 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "くっ、くぅぅんッ！") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 4))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 17)
      (text "いいか、牝豚。お前の座ってる椅子に染みひとつでも付けてみろ。ただじゃおかないからな。")
      (proc 13)
      (proc 18)
      (text "そ、そんな事言われても‥‥‥無理ですッ！")
      (proc 13)
      (proc 17)
      (text "汚い＊＊＊からヨダレを滴らすんじゃないよ。そんな物で" 'br)
      (text "汚されたら、二度と使う事が出来ないじゃないか。")
      (proc 13)
      (proc 18)
      (text "ごめんなさい‥‥‥でも、溢れてきちゃうんですぅ！")
      (proc 13)
      (proc 17)
      (text "牝豚なんかペットにするんじゃなかったよ。")
      (proc 13))
     (/
      (proc 17)
      (text "いいか、牝豚。お前の座ってる椅子に染みひとつでも付けてみろ。ただじゃおかないからな。")
      (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 8))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 18)
      (text "はうぅぅ‥‥‥もっと、もっとォ！")
      (proc 13)
      (proc 17)
      (text "いつまでやってもきりがない。お前みたいなマゾ女は今まで見た事がない。多分、二度とお目にかかれないだろうな。")
      (proc 13)
      (proc 18)
      (text "そ、そんなァ‥‥‥")
      (proc 13)
      (proc 17)
      (text "お前は生まれついての牝豚だ。ミツコを愛してるような事言って、わたしにちょっと苛められればこの様か。")
      (proc 13)
      (proc 18)
      (text "ああ、お願い‥‥‥ミツコの事は言わないで‥‥‥")
      (proc 13))
     (/ (proc 18) (text "はうぅぅ‥‥‥もっと、もっとォ！") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 12))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 18)
      (text "お、お願いです‥‥‥焦らさないで下さいッ！")
      (proc 13)
      (proc 17)
      (text "ご主人様のやり方に、文句をつけようってのかい？　お前は黙ってよがってりゃいんだよ！")
      (proc 13)
      (proc 18)
      (text "そ、そんな‥‥‥苛めないで‥‥‥")
      (proc 13)
      (proc 17)
      (text "苛めて欲しいくせに、心にもない事を言いやがって。淫売の牝豚。千葉でも最低の淫売女、それがお前だ。")
      (proc 13)
      (proc 18)
      (text "ううっ‥‥‥")
      (proc 13)
      (proc 17)
      (text "いいだろう、望み通り身体中をムチで傷だらけにしてやる。途中で音をあげてみろ、もっと酷いお仕置きだからね！")
      (proc 13))
     (/ (proc 18) (text "お、お願いです‥‥‥焦らさないで下さいッ！") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 13) (= 644 #f))
   (proc 10)
   (proc 17)
   (text "さあ、遊びはもう終わりだ。わたしの質問に答えてもらうよ。まさか今さら嫌だとは言わないだろうね？")
   (proc 13)
   (proc 18)
   (text "は、はい‥‥‥何でも喋ります‥‥‥")
   (proc 13)
   (proc 17)
   (text "まずは、お前がどうやって軍のデータベースをハッキングしたかを聞こうか。それはかなり無謀な事だったんだろう？")
   (proc 13)
   (proc 18)
   (text "サイバースペースで見ると、軍のデータベースは数キロ四方の巨大なマトリクスです‥‥‥")
   (proc 13)
   (proc 18)
   (text "大抵のハッカーは、それを見ただけで臆してしまう‥‥‥")
   (proc 13)
   (proc 17)
   (text "なのに、どうしてお前はそれに手を出した。")
   (proc 13)
   (proc 18)
   (text "エイプリルとレイファが仲間だったから‥‥‥あの子達は自由に軍の施設に出入り出来ました‥‥‥")
   (proc 13)
   (proc 18)
   (text "基地への送電設備を破壊させて、マトリクスを麻痺させました。普通のハッカーにはそんな事は出来ません。超荒業ですから‥‥‥")
   (proc 13)
   (proc 17)
   (text "すると、どうなるってんだ？　プロテクトが外れる訳じゃないだろう。わたしはローテクだからわかんないけど。")
   (proc 13)
   (proc 18)
   (text "送電が止まると、補助電源に変わるんだけど‥‥‥マトリクスは外部からの侵入を防ぐ為に、一瞬で収縮するんです。")
   (proc 13)
   (proc 17)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (proc 13)
   (proc 18)
   (text "あたしは、その瞬間を待って数時間前からマトリクスの外側に張り付いてた。巧妙に偽装して、その一部に化けるの‥‥‥")
   (proc 13)
   (proc 17)
   (text "なるほど、さっぱりわからない。とにかくデータベースの中に入り込んで、軍が開発中のシステムの情報だけを盗んだ。")
   (proc 13)
   (proc 18)
   (text "それの所在はわかってました‥‥‥ミツコが何処からか情報を持って来て、データベースのどの辺りに隠されてるかも知ってた。")
   (proc 13)
   (proc 17)
   (text "するってえと、軍の開発したシステムのネタはミツコが持って来たのか。ミツコはそのネタをどうやって手に入れた？")
   (proc 13)
   (proc 18)
   (text "そ、それは知りません‥‥‥ミツコに聞かないと‥‥‥")
   (proc 13)
   (nop@)
   (set-reg 644 #t)
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 13) (= 644 #t)) (mes-jump "mes¥md_c3_r2.mes"))
 (seg (? (= Y 2) (= S 6))
   (sound 'se 1)
   (branch-reg
    649
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_22ca.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 18)
      (text "はうッ‥‥‥‥‥‥")
      (proc 13)
      (proc 17)
      (text "牝豚を嬲るのは楽しいねぇ。やればやる程、従順な牝奴隷になっていくじゃないか。")
      (proc 13)
      (proc 18)
      (text "ああ‥‥‥もう奴隷でもいいの‥‥‥もっと気持ちよくしてぇ！")
      (proc 13)
      (nop@)
      (set-reg 649 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "はうッ‥‥‥‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 7))
   (sound 'se 1)
   (branch-reg
    650
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_22cb.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 18)
      (text "はっ、はァンッ‥‥‥")
      (proc 13)
      (proc 17)
      (text "さあ、お望み通り身体中を鞭で嬲ってやる。うれしいだろう！")
      (proc 13)
      (proc 18)
      (text "は、はいッ、うれしいです！")
      (proc 13)
      (nop@)
      (set-reg 650 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "はっ、はァンッ‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 8))
   (sound 'se 1)
   (branch-reg
    651
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_22cc.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 18)
      (text "あうッ！　そ、そこじゃないの‥‥‥")
      (proc 13)
      (proc 17)
      (text "＊＊＊からヨダレを垂れ流しながら、何を言ってるんだい！")
      (proc 13)
      (proc 18)
      (text "ああ、身体が‥‥‥変なの、おかしくなりそう！")
      (proc 13)
      (nop@)
      (set-reg 651 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あうッ！　そ、そこじゃないの‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 9))
   (sound 'se 1)
   (branch-reg
    652
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_22cd.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 18)
      (text "はうんッ‥‥‥＊＊＊も叩いて‥‥‥鞭で苛めてぇ！")
      (proc 13)
      (proc 17)
      (text "＊＊＊はもっと楽しい事に使うのさ。じゃないと、二度と" 'br)
      (text "ジャムれなくなっちまうからね。")
      (proc 13)
      (proc 18)
      (text "何でもいいから‥‥‥もっと目茶苦茶にして‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 652 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "はうんッ‥‥‥＊＊＊も叩いて‥‥‥鞭で苛めてぇ！") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 10))
   (sound 'se 1)
   (branch-reg
    653
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (nop@)
      (set-reg 653 #t)
      (proc 0)
      (image-file "gpc¥a1_22ce.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 18)
      (text "あっ、ああぁぁぁ‥‥‥")
      (proc 13)
      (proc 17)
      (text "何だい、そのがっかりしたような声は。＊＊＊を鞭打ってもらえ" 'br)
      (text "なくて失望してるのか？")
      (proc 13)
      (proc 18)
      (text "そ、そんな事ありません、ご主人様に苛めてもらえるなら‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 653 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あっ、ああぁぁぁ‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 11))
   (sound 'se 1)
   (branch-reg
    654
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_22cf.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 18)
      (text "んッ‥‥‥んふぅ！")
      (proc 13)
      (proc 17)
      (text "相変わらずオッパイを嬲られるのが一番みたいね。仕方のない牝豚だよ、どうしようもないね。")
      (proc 13)
      (proc 18)
      (text "ハァ、ハァ、ハァ‥‥‥‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 654 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "んッ‥‥‥んふぅ！") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 12))
   (sound 'se 1)
   (branch-reg
    655
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_22cg.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 18)
      (text "あううっ！　か、顔は許して下さい‥‥‥")
      (proc 13)
      (proc 17)
      (text "うるさい。お前はもうわたしの物なんだよッ、その身体も顔もね！何処をどうしようが勝手さ。")
      (proc 13)
      (proc 18)
      (text "ああ、そんなの酷いわ‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 655 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あううっ！　か、顔は許して下さい‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 13))
   (sound 'se 1)
   (branch-reg
    656
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_22ch.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 18)
      (text "はンッ！　オッパイが気持ちいいの‥‥‥")
      (proc 13)
      (proc 17)
      (text "気持ちいいのかい牝豚。可愛いオッパイが千切れるくらい、強く叩いてやってもいいんだよ！")
      (proc 13)
      (proc 18)
      (text "た、叩いて下さい‥‥‥千切れるくらい強く！")
      (proc 13)
      (nop@)
      (set-reg 656 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "はンッ！　オッパイが気持ちいいの‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 14))
   (sound 'se 1)
   (branch-reg
    657
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_22ci.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 18)
      (text "んふっ‥‥‥‥‥‥")
      (proc 13)
      (proc 17)
      (text "何だいその鳴き声は！　まるでわたしを非難してるみたいじゃないか。文句があるなら言ってみな。")
      (proc 13)
      (proc 18)
      (text "も、文句なんかありません‥‥‥で、でも‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 657 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "んふっ‥‥‥‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 7) (= S 2) (= 660 #f))
   (proc 5)
   (proc 10)
   (proc 18)
   (text "あッ、嫌ァ！　な、何をするのっ‥‥‥")
   (proc 13)
   (proc 17)
   (text "お前の望み通り、嬲ってやろうって言ってるのさ！")
   (proc 13)
   (proc 18)
   (text "んッ！　んんッ‥‥‥‥‥‥‥‥‥")
   (proc 13)
   (proc 11)
   (exec-mem 3072 0)
   (exec-mem 256 "G 16 61 0 16 143")
   (proc 0)
   (image-file "gpc¥a1_22ba.gpc")
   (image-mem 1 0)
   (proc 12)
   (proc 10)
   (proc 17)
   (text "ハッ！　なんて姿なんだ、お前は本当に笑わせてくれるよ！")
   (proc 13)
   (proc 18)
   (text "んん、んんん‥‥‥")
   (proc 13)
   (proc 17)
   (text "目に涙を溜めて。そんなに痛いかい！")
   (proc 13)
   (proc 18)
   (text "んッ‥‥‥‥‥‥")
   (proc 13)
   (proc 17)
   (text "ヨダレを流して悦んでやがる。そうだな、うれしんだろう？")
   (proc 13)
   (proc 18)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (proc 13)
   (proc 11)
   (exec-mem 3072 0)
   (exec-mem 256 "P 16 61 0")
   (proc 12)
   (proc 10)
   (proc 18)
   (text "あうぅぅっ！")
   (proc 13)
   (proc 17)
   (text "そのままじゃ口も利けないからね。惜しいけど外してやるよ。どうだ、気持ちよかったろう！")
   (proc 13)
   (proc 18)
   (text "は、はい‥‥‥‥‥‥")
   (proc 13)
   (nop@)
   (inc-var H 1)
   (nop@)
   (set-reg 660 #t)
   (proc 6)
   (exec-mem 9504 "C icon¥tool18.gpc,GPC")
   (branch-reg 991 (</> (/ (image-mem 1 0 6 160)) (/ (image-mem 1 0 71 160))))
   (proc 11))
 (seg (? (= Y 7) (= S 2) (= 660 #t))
   (proc 10)
   (proc 18)
   (text "あッ、嫌ぁぁぁぁ‥‥‥‥‥‥")
   (proc 13)
   (proc 17)
   (text "舌を挟んじゃ口も利けないからね、惜しいけど止めてやる。")
   (proc 13)
   (proc 11))
 (seg (? (= Y 7) (= S 3) (= 661 #f))
   (proc 0)
   (image-file "gpc¥a1_22bb.gpc")
   (image-mem 1 0)
   (proc 12)
   (proc 10)
   (proc 18)
   (text "あくッ、ひぃぃぃっ！")
   (proc 13)
   (proc 17)
   (text "刺が乳首にざっくり食い込んでる。針で刺されるより痛いはずさ！")
   (proc 13)
   (proc 18)
   (text "はぁ、はぁ、はぁ‥‥‥ああァァァァ！")
   (proc 13)
   (proc 17)
   (text "こんな事をされても、まだ感じるかいこの牝豚は。そうだな、気持ちいいんだろう！")
   (proc 13)
   (proc 18)
   (text "は、はいっ‥‥‥気持ちいいです！")
   (proc 13)
   (proc 18)
   (text "こんなの‥‥‥こんなの初めて！")
   (proc 13)
   (nop@)
   (inc-var H 1)
   (nop@)
   (set-reg 661 #t)
   (proc 11))
 (seg (? (= Y 7) (= S 3) (= 661 #t))
   (proc 10)
   (proc 18)
   (text "あうッッ！　い、痛ッ‥‥‥触っちゃ駄目ぇ！")
   (proc 13)
   (proc 11))
 (seg (? (= Y 7) (= S 4) (= 662 #f))
   (proc 0)
   (image-file "gpc¥a1_22bc.gpc")
   (image-mem 1 0)
   (proc 12)
   (proc 10)
   (proc 18)
   (text "うぅぅンッ！")
   (proc 13)
   (proc 17)
   (text "おやおや、乳首が千切れそうになってるってのに、それでもここをグチュグチュにしてるよ！")
   (proc 13)
   (proc 18)
   (text "はうッ、何なのこの感じ‥‥‥アッ、アアァァ！")
   (proc 13)
   (proc 17)
   (text "牝豚にはとびきりの苦痛でも、快感になっちまう。これじゃどうしようもないね。")
   (proc 13)
   (proc 18)
   (text "くぅぅンッ‥‥‥‥‥‥")
   (proc 13)
   (nop@)
   (inc-var H 1)
   (nop@)
   (set-reg 662 #t)
   (proc 11))
 (seg (? (= Y 7) (= S 4) (= 662 #t))
   (proc 10)
   (proc 18)
   (text "アァァッ、痛い‥‥‥ひ、引っ張っちゃ駄目ぇ！")
   (proc 13)
   (proc 11))
 (seg (? (= Y 7) (= S 5) (= 663 #f))
   (proc 10)
   (proc 17)
   (text "わたしの言いつけを破って、椅子を汚してくれたね。それも牝豚の汚らしい小便で！")
   (proc 13)
   (proc 18)
   (text "ごめんなさい、謝ります‥‥‥自分で奇麗にしますからァ‥‥‥")
   (proc 13)
   (proc 17)
   (text "駄目だね。これはキツイお仕置きをしないと！")
   (proc 13)
   (proc 18)
   (text "な、何をするの‥‥‥それだけは‥‥‥駄目ぇ！")
   (proc 13)
   (proc 11)
   (proc 0)
   (image-file "gpc¥a1_22bd.gpc")
   (image-mem 1 0)
   (proc 12)
   (proc 10)
   (proc 18)
   (text "ひィィィィィン！")
   (proc 13)
   (proc 17)
   (text "ちっちゃいクリトリスだね、刺が貫通しちまった。")
   (proc 13)
   (proc 18)
   (text "あはッ、はァァッ‥‥‥あァァァッ！")
   (proc 13)
   (proc 17)
   (text "このために＊＊＊を取っといたんだ。最高に気持ちいいだろう！")
   (proc 13)
   (proc 18)
   (text "はいッ‥‥‥き、気持ちいい‥‥‥もう死んじゃう！")
   (proc 13)
   (nop@)
   (inc-var H 1)
   (nop@)
   (set-reg 663 #t)
   (proc 11))
 (seg (? (= Y 7) (= S 5) (= 663 #t))
   (proc 10)
   (proc 18)
   (text "さ、触っちゃ駄目ッ‥‥‥ま、またおしっこが出ちゃう！")
   (proc 13)
   (proc 11))
 (seg*))