(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 3072 0)
  (proc 5)
  (image-file "gpc¥a1_21a.gpc")
  (image-mem 1 0)
  (proc 12)
  (proc 10)
  (text "「Kiyomi」" 'br)
  (text "身体中が牝豚の汁だらけだよ。牝豚は臭くて仕方ないね！")
  (wait)
  (text-reset 14)
  (text "「Nana」" 'br)
  (text "ああ、そんな‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "もっと苛めて欲しいのかい、牝豚。苛めて欲しいんなら、ちゃんとご主人様にお願いしてみな！")
  (wait)
  (text-reset 14)
  (text "「Nana」" 'br)
  (text "苛めて下さい‥‥‥もっと激しく苛めてください‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "いいだろう、望み通りにしてやる。その前に約束するんだ。わたしはご主人様のペットです、言われた通りにしますってね！")
  (wait)
  (text-reset 14)
  (text "「Nana」" 'br)
  (text "は、はいッ。あたしはご主人様のペットです。何でもご主人様の言われた通りにしますッ。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "たっぷり苛めた後で、知ってる事を全部話してもらう。お前の大好きなミツコの事もだ。わたしよりミツコが大切な訳はないな？")
  (wait)
  (text-reset 14)
  (text "「Nana」" 'br)
  (text "知っている事は全部話します‥‥‥ミツコの事も話しますからァ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "よしよし、よく言ったな。可愛い子豚ちゃんにご褒美をあげよう。とびきりのご褒美をね！")
  (wait)
  (text-reset 14)
  (proc 11)
  (exec-mem 18688 3)
  (exec-mem 18688 5 1 0)
  (exec-mem 3072 0)
  (mes-jump "mes¥MD_C03.MES")))