(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (nop@)
   (set-reg 980 #t)
   (set-reg 981 #t)
   (set-reg 982 #f)
   (set-reg 983 #f)
   (set-reg 984 #f)
   (set-reg 985 #f)
   (set-reg 986 #f)
   (set-reg 987 #f)
   (set-reg 988 #f)
   (set-reg 989 #f)
   (set-reg 990 #f)
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_30.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (if (</>
        (//
         (? (= P 9))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_09.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 9))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_09v.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 9)))))
        (// (nop@))))
   (exec-mem 256 "E")
   (load-mem "clm¥A1_30.clm" 32768)
   (load-mem "clm¥icon.clm" 20480)
   (mes-load? "mes¥icon_cl.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥icon_c2.mec" 0)
   (mes-load? 0)
   (text-frame 10 312 70 370)
   (exec-mem 256 "A 0")
   (proc 12)
   (proc 10)
   (define-proc 15
     (<>
      (if (</>
           (//
            (? (>= H 3) (= 637 #f))
            (image-file "gpc¥a1_30a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 637 #t)
            (proc 12))
           (// (proc 12))))))
   (text "「Kiyomi」" 'br)
   (text "さて、可愛い日本産の子猫ちゃんの登場だ。それも血統書付きの、とびきりの奴のね。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "おやおや。血統書付きともなると気位が高くて、わたしなんかとは口もきけないって？")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "こ、ここは何処なのよ‥‥‥他の仲間に会わせて！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そうはいかない。口にさえすれば何でも願いが叶ったのは、遠い昔の話。あんたにはもう、魔法を使う事は出来ないのさ。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "わざと私の神経を逆撫でするような言い方は止めて！　私をどうするつもりなの‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "丁重におもてなしするのさ、わたし流のやり方でね。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "何の事を言っているのか、さっぱりわからないわ。私にわかるように説明して頂戴！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたがいつまでその鼻持ちならないお上品な態度を取ってられるか、じっくり確かめてやろうじゃないの。")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (exec-mem 256 "P 5 6 0")
   (loop
    (set-var S 0)
    (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
    (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (= Z 1) (= 991 #f))
   (proc 0)
   (exec-mem 256 "P 5 71 0")
   (nop@)
   (set-reg 991 #t)
   (exec-mem 256 "P 8 6 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 71 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 71 40))))
   (load-mem "clm¥icon2.clm" 20480)
   (proc 1))
 (seg (? (= Z 1) (= 991 #t))
   (proc 0)
   (exec-mem 256 "P 5 6 0")
   (nop@)
   (set-reg 991 #f)
   (exec-mem 256 "P 9 71 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 6 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 6 40))))
   (load-mem "clm¥icon.clm" 20480)
   (proc 1))
 (seg (? (= Z 2) (= 991 #f))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #f))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Z 2) (= 991 #t))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #t))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Y 1) (= S 1) (= H 0))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "あんたがお仲間のボスだった事は、もうわかってんだよ。他の連中から聞いたからね。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "こんな所には一分だって堪えられないわ。暗くてじめじめしていてまるでなめくじになった気分よ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "お気に召さないようだね‥‥‥当たり前だ。誰がこんな所を気に入るってんだい。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "お望みなら、一生この部屋に鎖でつないでやるよ。それが嫌なら、知ってる事を吐いちまいな！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "「Mitsuko」" 'br)
      (text "こんな所には一分だって堪えられないわ。暗くてじめじめしていてまるでなめくじになった気分よ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 3))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Mitsuko」" 'br)
      (text "ううッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "どうだい、子猫ちゃん？　そろそろ決心はついたかね。盗んだ情報の事を話せば、これで終いにしてやらないでもない。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "何よ、その奥歯に物が挟まったような言い方‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "うかうかしてると、その奇麗なお洋服を全部剥ぎ取っちまうよ！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "知らないわ、何も知らないわよ‥‥‥")
      (wait)
      (text-reset 14))
     (/ (text "「Mitsuko」" 'br) (text "ううッ‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Mitsuko」" 'br)
      (text "さっ、触らないで‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "思ったより頑固な女だねぇ、そんなに痛い目にあいたいのかい！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "ひッ‥‥‥も、もう止めて。何の権利があってこんな事をするの！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "物わかりの悪い、馬鹿な女だね。まだわからないのかい、お前には何の権利も有りはしないんだ。殺されても文句は言えないんだよ。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "ああ‥‥‥どうしてこんな事に‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "しかも、わたしに捕まったのが運のつきってやつ。わたしはあんたみたいな日本人だってだけで威張ってる女が大嫌いなんだ。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "何を言ってるの‥‥‥あなただって日本人じゃない！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そうさ、だからこんなクソ仕事をしてる。わたしの他に誰もやりたがらないクソ仕事さ！")
      (wait)
      (text-reset 14))
     (/ (text "「Mitsuko」" 'br) (text "さっ、触らないで‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 6))
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "どうするんだいミツコ。もっと痛い目にあうか？")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それとも、このへんで覚悟を決めて知ってる事を白状するか。どちらにするのか、決めてもらおうじゃない？")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "どっか行きなさいよ！　あなたの顔なんて見たくないわ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "たとえ私が罪人だったとしても、こんな屈辱を受ける理由にはならないわ。しかも私は‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ああ、そう。そういう態度を取るんなら、わたしにも考えがある。今まで手加減してやってたけど、それも終わりね。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "ど、どうするつもりなの？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "喋りたくても、喋れないようにするのさ。しばらくはお前の悲鳴しか聞きたくないよ！")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "いっ、嫌ァ！　触らないで‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "うるさいんだよ！　その口に栓をしてやる！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 18688 3)
   (exec-mem 18688 5 1 0)
   (exec-mem 3072 0)
   (mes-jump "mes¥MD_D02.MES"))
 (seg (? (= Y 1) (= S 2))
   (sound 'se 1)
   (branch-reg
    667
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_30ba.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "うッ！　うぅぅぅぅッ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ロッドで苛められるのはどんな気分だ。こんな経験は今までにないだろ。それとも、同じようにヒヒ爺に可愛がってもらってたか？")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "くッ、最低の気分よ‥‥‥こんな事をしても、何にもならないわ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 667 #t))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "うッ！　うぅぅぅぅッ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 3))
   (sound 'se 1)
   (branch-reg
    668
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_30bb.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "キャァァッ‥‥‥何するのよ、危ないじゃない！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ギャァギャァとうるさい女だね。これしきの事で音をあげてるようじゃ、わたしの拷問には堪えられないよ！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "あ、頭がおかしいわ。こんな事をして楽しいの？")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 668 #t))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "キャァッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 4))
   (sound 'se 1)
   (branch-reg
    669
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_30bc.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "痛ッ！　や、止めてよ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ふざけんな、誰がお前の命令なんてきくと思ってんだ？　お前はもうただの囚人。わたしの意思でどうにでも出来る奴隷なんだよ。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "冗談じゃないわ。大昔じゃあるまいし、奴隷なんて存在しないわ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 669 #t))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "痛ッ！　や、止めてよ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 5))
   (sound 'se 1)
   (branch-reg
    670
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_30bd.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "はんっ、こんなの嫌よ‥‥‥堪えられない‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "その手を退けな！　自慢のオッパイを拝ませてもらおうじゃない。スケベ爺どもを狂わせた、最高のヤツをさぁ！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "わざと下卑た言い方をしないで、頭が痛くなってくるわ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 670 #t))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "はんっ、こんなの嫌よ‥‥‥堪えられない‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 6))
   (sound 'se 1)
   (branch-reg
    671
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_30be.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "あッ‥‥‥い、痛いッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "自慢の太股に、大きな傷が付いちまった！　でも、その方があんたには似合いだよ。塀の中じゃ、誰も見てくれないからね。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "抗議するわ。いくら私が罪人だからって、どうしてこんなに酷い扱いを受けなければならないの！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 671 #t))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "あッ‥‥‥い、痛いッ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 7))
   (sound 'se 1)
   (branch-reg
    672
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_30bf.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "あッ‥‥‥い、嫌ァ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "血統書付き日本猫の＊＊＊だ、いい眺めだねぇ。胸を庇う暇があ" 'br)
      (text "るんなら、自慢のお道具を隠したらどうだい！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "こ、こんなの何ともないわ‥‥‥何ともないのよ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 672 #t))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "あッ‥‥‥い、嫌ァ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (= H 0))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "今まではどうだったか知らないけどね、誰もあんたを助けちゃくれないし、ちやほやしてももらえない。もう二度とね。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "私がそうしてくれって頼んだ訳じゃないわ‥‥‥もう止めましょうよ、こんな事に意味があるとは思えない。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ところが大ありなんだよ、あんたが連中のボスだったのはわかってるんだ。機密を盗んだ張本人だよ。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "「Mitsuko」" 'br)
      (text "もう止めましょうよ、こんな事に意味があるとは思えないわ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 3))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "あんたを見てると、嫌ったらしいおやじ達を思い出す。脂ぎった顔の、支配者階級に胡座をかいて座ってる奴らさ！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "そ、それはあなたの偏見だわ‥‥‥私は一度だって権力を振り回して人を蔑ろにした事なんてないんだから。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そいつはどうかね！　だってあんたは、あいつらに尻尾を振って、それで相応の地位を得たんだろう？")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "ち、違うわ‥‥‥そんな事ない！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "まあいい、どっちみちその地位もキャリアも全部台無しになっちまったんだからね。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あんたはもう、ただの囚人。そとの世界には一生出られないんだ。ざまあないね。")
      (wait)
      (text-reset 14))
     (/
      (text "「Mitsuko」" 'br)
      (text "あなたと何を話しても無駄よ、私をここから出して！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Mitsuko」" 'br)
      (text "うっ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "奇麗なお洋服が台無しになっちまった。うかうかしてると、着てる物を全部切り裂かれちまうよ！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "ひ、人でなし！　どうしてこんな酷い事が出来るの‥‥‥あなたは人間じゃないわ。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あんたにそんな事を言われたくないね。エイプリルやナナはあんたにそそのかされて、機密を盗む片棒を担がされた。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あんたが彼女達を誘わなきゃ、捕まって拷問を受ける事もなかったんじゃないか。あんたの元上官も仕事を奪われずに済んだ。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "都合が悪くなると、すぐ口を閉じる。それで済まされると思ったら大間違いさ。わたしは絶対に諦めない。")
      (wait)
      (text-reset 14))
     (/ (text "「Mitsuko」" 'br) (text "‥‥‥‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 6))
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "どうするんだいミツコ。もっと痛い目にあうか？")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それとも、このへんで覚悟を決めて知ってる事を白状するか。どちらにするのか、決めてもらおうじゃない？")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "どっか行きなさいよ！　あなたの顔なんて見たくないわ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "たとえ私が罪人だったとしても、こんな屈辱を受ける理由にはならないわ。しかも私は‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ああ、そう。そういう態度を取るんなら、わたしにも考えがある。今まで手加減してやってたけど、それも終わりね。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "ど、どうするつもりなの？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "喋りたくても、喋れないようにするのさ。しばらくはお前の悲鳴しか聞きたくないよ！")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "いっ、嫌ァ！　触らないで‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "うるさいんだよ！　その口に栓をしてやる！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 18688 3)
   (exec-mem 18688 5 1 0)
   (exec-mem 3072 0)
   (mes-jump "mes¥MD_D02.MES"))
 (seg (? (= Y 2) (= S 2))
   (sound 'se 1)
   (branch-reg
    667
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_30ba.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "んんッ、もう止めて‥‥‥嫌よォ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "その、胸を庇ってる腕を退けな。じゃないと白魚みたいな指を切り飛ばしてしまうよ！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "や、やれるものなら‥‥‥やってみなさい！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 667 #t))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "んんッ、もう止めて‥‥‥嫌よォ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 3))
   (sound 'se 1)
   (branch-reg
    668
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_30bb.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ひッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "避けるんじゃないよ、手元が狂って顔に傷を付けちまう。もっともその美貌も、こうなっちゃ何の役にも立たないけどね！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "誰か助けて！　このキ×ガイを私に近づけないで！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 668 #t))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ひッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 4))
   (sound 'se 1)
   (branch-reg
    669
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_30bc.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ううッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そのピッタリ肌に張り付いた服は、いともあっさり破れちまうね。気をつけないと皮膚までスッパリ切っちまいそうだよ。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "お、脅しても無駄よ。あなたに屈する事なんて有り得ないわ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そのわりに、声が震えてるみたいだけど？")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 669 #t))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ううッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 5))
   (sound 'se 1)
   (branch-reg
    670
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_30bd.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "はんッ！　い、嫌ァ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "その腕を退けろって言ってるんだよ。ご自慢のオッパイを拝んでやろうって言ってんだ！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "嫌よ、そんなの嫌ァ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 670 #t))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "はんッ！　い、嫌ァ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 6))
   (sound 'se 1)
   (branch-reg
    671
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_30be.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "い、痛ぁッ‥‥‥な、何ともないわ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "お尻もなかなかいいじゃない、そそるねぇ。ナナはもっと子供っぽい身体だったけど。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "ナナにもこんな事をしたのね、あなたは本物のサディストだわ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 671 #t))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "い、痛ぁッ‥‥‥な、何ともないわ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 7))
   (sound 'se 1)
   (branch-reg
    672
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_30bf.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "くぅッ！　み、見ないで‥‥‥見ちゃ駄目ッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "なかなか結構な持ち物じゃない。立派な＊＊＊だ！　お上品ぶっ" 'br)
      (text "てても、そこはただの女さ。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 672 #t))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "くぅッ！　み、見ないで‥‥‥見ちゃ駄目ッ！")
      (wait)
      (text-reset 14))))
   (proc 11)))