(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (nop@)
   (set-reg 980 #t)
   (set-reg 981 #t)
   (set-reg 982 #f)
   (set-reg 983 #f)
   (set-reg 984 #f)
   (set-reg 985 #f)
   (set-reg 986 #f)
   (set-reg 987 #f)
   (set-reg 988 #f)
   (set-reg 989 #f)
   (set-reg 990 #f)
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_31.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (if (</>
        (//
         (? (= P 9))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_09.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 9))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_09v.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 9)))))
        (// (nop@))))
   (exec-mem 256 "E")
   (load-mem "clm¥A1_31.clm" 32768)
   (load-mem "clm¥icon.clm" 20480)
   (mes-load? "mes¥icon_cl.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥icon_c2.mec" 0)
   (mes-load? 0)
   (text-frame 10 312 70 370)
   (exec-mem 256 "A 0")
   (proc 12)
   (define-proc 19
     (<>
      (if (</>
           (//
            (? (>= H 7) (= 983 #f))
            (nop@)
            (set-reg 983 #t)
            (mes-load? "mes¥icon_cl.mec" 0)
            (mes-load? 0)
            (mes-load? "mes¥icon_c2.mec" 0)
            (mes-load? 0))
           (// (nop@))))))
   (proc 10)
   (set-var H 0)
   (text "「Mitsuko」" 'br)
   (text "うぐぅ‥‥‥ううッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "くっくっくっ‥‥‥これで余計な御託を聞かなくて済む。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "うぅぅ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それにしても、いい格好だね。お上品さのカケラもない。＊＊＊" 'br)
   (text "丸出し、男泣かせのオッパイも丸見えときた！")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "その姿を、無理に退役させられた、お前の元上官ってのに見せてやりたいね。少しは気もおさまるだろうよ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "家柄もいい、教養もある。秘書をやってたのだって、婿さんを探すまでの腰掛けだろ？　親も相当の投資をしてたはずだ。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "ううぅぅ、うっんッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "全部ご破算になっちまった訳だ、いい気味だね。ついでに牝奴隷に調教してやる。本物のクズになっちまうがいいさ！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (exec-mem 256 "P 5 6 0")
   (loop
    (set-var S 0)
    (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
    (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 5) (= 991 #f) (= 1020 #f) (= Q 5) (= 983 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name4.gpc,GPC")
   (image-mem 1 0 9 88)
   (proc 1)
   (set-var Q 5))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 5) (= 991 #t) (= 1020 #f) (= Q 5) (= 983 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name4.gpc,GPC")
   (image-mem 1 0 52 88)
   (proc 1)
   (set-var Q 5))
 (seg (? (= Z 2) (= Z 3) (= Z 5) (= 991 #f) (= 1020 #f) (>= Q 1) (= 983 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= Z 5) (= 991 #t) (= 1020 #f) (>= Q 1) (= 983 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1) (= 983 #f))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1) (= 983 #f))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (= Z 1) (= 991 #f))
   (proc 0)
   (exec-mem 256 "P 5 71 0")
   (nop@)
   (set-reg 991 #t)
   (exec-mem 256 "P 8 6 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 71 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 71 40))
        (//
         (? (= Y 4))
         (if (</>
              (//
               (? (= 983 #t))
               (exec-mem 9504 "C icon¥tool15.gpc,GPC")
               (image-mem 1 0 71 88))
              (//
               (? (= 983 #f))
               (exec-mem 9504 "C icon¥tool04.gpc,GPC")
               (image-mem 1 0 71 88)))))))
   (load-mem "clm¥icon2.clm" 20480)
   (proc 1))
 (seg (? (= Z 1) (= 991 #t))
   (proc 0)
   (exec-mem 256 "P 5 6 0")
   (nop@)
   (set-reg 991 #f)
   (exec-mem 256 "P 9 71 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 6 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 6 40))
        (//
         (? (= Y 4))
         (if (</>
              (//
               (? (= 983 #t))
               (exec-mem 9504 "C icon¥tool15.gpc,GPC")
               (image-mem 1 0 6 88))
              (//
               (? (= 983 #f))
               (exec-mem 9504 "C icon¥tool04.gpc,GPC")
               (image-mem 1 0 6 88)))))))
   (load-mem "clm¥icon.clm" 20480)
   (proc 1))
 (seg (? (= Z 2) (= 991 #f))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 6 40)
   (if (</>
        (//
         (? (= 983 #t))
         (exec-mem 9504 "C icon¥tool26.gpc,GPC")
         (image-mem 1 0 6 88))
        (// (nop@))))
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #f))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 6 16)
   (if (</>
        (//
         (? (= 983 #t))
         (exec-mem 9504 "C icon¥tool26.gpc,GPC")
         (image-mem 1 0 6 88))
        (// (nop@))))
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Z 2) (= 991 #t))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 71 40)
   (if (</>
        (//
         (? (= 983 #t))
         (exec-mem 9504 "C icon¥tool26.gpc,GPC")
         (image-mem 1 0 71 88))
        (// (nop@))))
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #t))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 71 16)
   (if (</>
        (//
         (? (= 983 #t))
         (exec-mem 9504 "C icon¥tool26.gpc,GPC")
         (image-mem 1 0 71 88))
        (// (nop@))))
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Z 5) (= 991 #f) (= 983 #t))
   (nop@)
   (set-var Y 4)
   (proc 0)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 9504 "C icon¥tool15.gpc,GPC")
   (image-mem 1 0 6 88)
   (exec-mem 18688 5 7 1)
   (proc 1)
   (exec-mem 18688 2 5))
 (seg (? (= Z 5) (= 991 #t) (= 983 #t))
   (nop@)
   (set-var Y 4)
   (proc 0)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 9504 "C icon¥tool15.gpc,GPC")
   (image-mem 1 0 71 88)
   (exec-mem 18688 5 7 1)
   (proc 1)
   (exec-mem 18688 2 5))
 (seg (? (= Y 1) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Mitsuko」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そんな悲しそうな顔をしなくてもいい。牝奴隷も悪くないさ。羞恥心なんてこれっぽっちも持ってない。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "他人の目も気にせず、自分の欲望を満たせばいい。何も考えずただご主人様の言いなりになってりゃいいんだよ。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "んっ、んん‥‥‥うぅッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "嫌だろうが、あんたに拒否する事は出来ないんだよ。もうすぐさ。目に浮かぶよ。嬲られてヒイヒイよがってるあんたの姿が！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "自分がどれだけ淫乱な女かって事がわかったら、あんたはきっと驚くだろうね。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/ (text "「Mitsuko」" 'br) (text "んっ、んん‥‥‥うぅッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 8))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "おやおや、＊＊＊からうれし涙を流してるじゃないか。お上品な" 'br)
      (text "令嬢がそんなはしたない事じゃいけないねぇ。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "んん〜っ、ふんッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "お前は、それを隠す事さえ出来ない。でもね、牝奴隷になっちまえば別に恥ずかしくも思わないだろうさ。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "人前で堂々と＊＊＊を濡らす事が出来る。最高だろう？")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "うう〜ッ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "口では嫌がってても、身体はそうは言ってない。＊＊＊をイジッ" 'br)
      (text "て、早く気持ちよくなりたい。お前の＊＊＊はそう言ってる！")
      (wait)
      (text-reset 14))
     (/ (text "「Mitsuko」" 'br) (text "んん〜っ、ふんッ‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 10))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "だいぶ牝奴隷らしくなってきたね、ロッドを避けようともしない。嬲られるのが好きになってきたか？")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "ふぅン‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "まだ否定するつもりだろうが、身体は正直さ。乳首もクリトリスも固くなってるじゃないか。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "うぅぅぅぅ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "恥ずかしがる事はない。自分がどれだけ淫乱な女かって事を認めちまえばいいのさ。わたしはいくらでも嬲ってやるぞ。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "うっ、うっ‥‥‥ううっ‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "「Kiyomi」" 'br)
      (text "だいぶ牝奴隷らしくなってきたね、ロッドを避けようともしない。嬲られるのが好きになってきたか？")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 11)) (mes-jump "mes¥md_d2_r1.mes"))
 (seg (? (= Y 1) (= S 2))
   (sound 'se 1)
   (branch-reg
    675
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31ca.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ふッ！　ふぐぅぅッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ギャグを付けてちゃ、悲鳴もあげられまい。いい様だよ、全くね。そんな格好を見せられたら、わたしもつい本気になっちまう。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "うっ、うっ‥‥‥うう〜ッ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 675 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ふッ！　ふぐぅぅッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 3))
   (sound 'se 1)
   (branch-reg
    676
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31cb.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "んぐぅぅッ‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "血統書付きのお上品な牝猫には、ちょっと刺激が強すぎるかね？" 'br)
      (text "もう普通の刺激じゃ感じられなくなっちまうかもね。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "ふぅんッ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 676 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "んぐぅぅッ‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 4))
   (sound 'se 1)
   (branch-reg
    677
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31cc.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ふぅぅッ！　うぐッ、うぅぅぅ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "くっくっ、なんて声を出すんだい。それに、＊＊＊が濡れ始めて" 'br)
      (text "るんじゃない。お汁が滴ってるみたいだけど？")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "うっ、うっ‥‥‥んんッ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 677 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ふぅぅッ！　うぐッ、うぅぅぅ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 5))
   (sound 'se 1)
   (branch-reg
    678
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31cd.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "んぐッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "真っ白なお腹に傷が付いちまった。でも毛並みの良すぎるお前には" 'br)
      (text "ちょっと傷があった方がいいかもね。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 678 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "んぐッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 6))
   (sound 'se 1)
   (branch-reg
    679
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31ce.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ううっ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そのうち、痛みさえ感じなくなる。痛めつけられてるのに、身体が痺れたような感覚だけ。じきにそうなるさ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "うぅっ、うう‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 679 #t)
      (proc 19))
     (/ (proc 10) (text "「Mitsuko」" 'br) (text "ううっ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 7))
   (sound 'se 1)
   (branch-reg
    680
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31cf.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ふっ、ふぅぅぅン！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "切なそうな声を出すなよ。ちょっとオッパイをかすっただけじゃないか。それとも、そんなに敏感なのか？")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 680 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ふっ、ふぅぅぅン！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 8))
   (sound 'se 1)
   (branch-reg
    681
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31cg.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "んぐっ、んんッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "怒ってるのか？　その顔を台無しにされかかったから。お前はまだそんな事を言っている。牝奴隷の心得ってのがわかってないね。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "んくぅ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 681 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "んぐっ、んんッ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 9))
   (sound 'se 1)
   (branch-reg
    682
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31ch.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "んぐぅぅぅッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "＊＊＊さえ付いてないって感じの清楚な顔してて、オッパイを" 'br)
      (text "苛められただけで、その有り様か！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "ふぅぅン、くぅぅッ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 682 #t)
      (proc 19))
     (/ (proc 10) (text "「Mitsuko」" 'br) (text "んぐぅぅぅッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 10))
   (sound 'se 1)
   (branch-reg
    683
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31ci.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "んぐッ、ううっ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "不満そうじゃない、もっと別の所を叩いて欲しいってか？　とんでもない淫乱だね。＊＊＊やオッパイを苛められたいんだろう。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "ううぅぅ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 683 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "んぐッ、ううっ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 11))
   (sound 'se 1)
   (branch-reg
    684
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31cj.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ふっ、ふぅン！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "細い腕だね。あっと言う間に折れてしまいそうだ。わたしはいつでもそうする事が出来るんだ。それを忘れない事だね！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "うっ、うう‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 684 #t)
      (proc 19))
     (/ (proc 10) (text "「Mitsuko」" 'br) (text "ふっ、ふぅン！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Mitsuko」" 'br)
      (text "んんッ！　んん〜っ、んぐッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あんたはギャグを付けてた方が魅力的だ。お上品ぶった御託が聞けなくなって、奴隷らしくなったよ！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "その不安そうな目が、そそるじゃないか。猫よりもむしろ小犬みたいだね。つい苛めたくなっちまう。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "下のお口の方も、上のと同じくらいギュッと閉じてるけど、そのうちパックリと開いてくれるだろうさ。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "「Kiyomi」" 'br)
      (text "あんたはギャグを付けてた方が魅力的だ。お上品ぶった御託が聞けなくなって、奴隷らしくなったよ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 8))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "わたしの言った通りだろう。どんなお嬢さんだって、わたしの手にかかれば、淫乱な牝奴隷になっちまうのさ。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "＊＊＊がうれし涙を流して、もっと鞭打ってくれって言ってる。" 'br)
      (text "そうして欲しいんだろう？")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "うぅぅ‥‥‥うう、ううんッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "まだ素直になってないねぇ。グチュグチュになってる＊＊＊を鏡" 'br)
      (text "で見せてやろうか。どんな具合になってるかさぁ！！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "くっくっ、充血してぷっくり膨らんでる。ピンク色だった襞が欲情して真っ赤になっちまって‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "ううッ！　んん、ふぅぅッ！")
      (wait)
      (text-reset 14))
     (/
      (text "「Kiyomi」" 'br)
      (text "＊＊＊がうれし涙を流して、もっと鞭打ってくれって言ってる。" 'br)
      (text "そうして欲しいんだろう？")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 10))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Mitsuko」" 'br)
      (text "ふぅぅン、ンンンンンン‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "良家のお嬢さんも、こうなっちまったら関係ないね。熱くなった身体を静める事が出来ない。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "自分の身体をよく見てみな。乳首は固くなってるし、＊＊＊から" 'br)
      (text "は襞がはみ出してる。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "ん‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "上品ぶったって駄目さ。お前はもうただの牝奴隷さ。指を使って、＊＊＊の疼きを何とかしたいと思ってる。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "こんな時お前が牝奴隷なら、思う存分オナニー出来るんだ。人目なんて関係ない。思う存分＊＊＊を弄る事が出来るんだよ！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "うっ、うっ‥‥‥ふぅぅン！")
      (wait)
      (text-reset 14))
     (/ (text "「Mitsuko」" 'br) (text "ふぅぅン、ンンンンンン‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 11)) (mes-jump "mes¥md_d2_r2.mes"))
 (seg (? (= Y 2) (= S 2))
   (sound 'se 1)
   (branch-reg
    675
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31ca.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "うぐぅ！　うっ、うくッ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "お前は避ける事さえ出来ない、その格好じゃあね。鞭で打たれるがままになるしかない。それが牝奴隷の悲しい所だねぇ。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "うっ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 675 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "うぐぅ！　うっ、うくッ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 3))
   (sound 'se 1)
   (branch-reg
    676
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31cb.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "くふッ‥‥‥うぐぅぅ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "＊＊＊には、傷ひとつ付けてないはずだよ。なのに、その喘ぎ声" 'br)
      (text "はどういう事だ。卑しい牝奴隷は身体中が＊＊＊なのか！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "うっ、ううっ‥‥‥ううッ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 676 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "くふッ‥‥‥うぐぅぅ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 4))
   (sound 'se 1)
   (branch-reg
    677
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31cc.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ふッ、ふゥゥッ！　んふッ、んふぅ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "今のはちょっと近かったね。あやうく大切な鞭を牝奴隷のお汁で汚してしまうとこだった！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "うっく、うう、ううン！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 677 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ふッ、ふゥゥッ！　んふッ、んふぅ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 5))
   (sound 'se 1)
   (branch-reg
    678
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31cd.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ふッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "よく締まった腰だ、さぞかし官能的な動きをするんだろうね。わたしが直に調べてやる。後でゆっくりね。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "うっ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 678 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ふッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 6))
   (sound 'se 1)
   (branch-reg
    679
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31ce.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "んぐッ、くぅぅン‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "どんな女でも、オッパイを鞭で嬲られると感じてしまう。痛みよりも微妙な身体の疼きを感じるだろう？")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "ううっ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 679 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "んぐッ、くぅぅン‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 7))
   (sound 'se 1)
   (branch-reg
    680
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31cf.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ふッ、ふぅぅぅン‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "不思議なもんだ、オッパイを苛められてるのに、＊＊＊からうれ" 'br)
      (text "し涙が流れ出す。＊＊＊に触られた訳じゃないのにねぇ。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 680 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ふッ、ふぅぅぅン‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 8))
   (sound 'se 1)
   (branch-reg
    681
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31cg.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ふっ、ふぅ〜ッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そんなに恐がらなくてもいいだろう？　わたしがお前の美しい顔を目茶苦茶にすると思ってるのか？")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "ううっ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 681 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ふっ、ふぅ〜ッ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 9))
   (sound 'se 1)
   (branch-reg
    682
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31ch.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "んふぅ‥‥‥ふ、ふぅぅぅン！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "小ぶりだけど可愛いオッパイだこと。固くて誰にも揉まれた事がないように見える。本当はそんな事ないはずだけど。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "う、うう〜ッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 682 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "んふぅ‥‥‥ふ、ふぅぅぅン！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 10))
   (sound 'se 1)
   (branch-reg
    683
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31ci.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "んぐぅ‥‥‥ん、んッ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ブーツを履いてる足より、腕の方が鞭の利きがいいな。もっと敏感な部分もあるが、そこを嬲られるとむしろ悦んでいるようだし。")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "うっ、うっ、ううぅぅン！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 683 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "んぐぅ‥‥‥ん、んッ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 11))
   (sound 'se 1)
   (branch-reg
    684
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_31cj.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (text "「Mitsuko」" 'br)
      (text "ンンッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "どうだ痛いか？　止めて欲しいって顔して、身体の方はもっと違う所を苛めてくれって言ってるぞ！")
      (wait)
      (text-reset 14)
      (text "「Mitsuko」" 'br)
      (text "ううぅぅ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 684 #t)
      (proc 19))
     (/ (proc 10) (text "「Mitsuko」" 'br) (text "ンンッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 4) (= S 1) (= 685 #f))
   (proc 10)
   (text "「Mitsuko」" 'br)
   (text "うッ‥‥‥ううッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "こいつは、お前の恥ずかしい＊＊＊の中まで見れる機械さ。見た" 'br)
   (text "事があるかい、自分のアソコの中をさ。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "お上品な、良家のお嬢様の＊＊＊の中身がどうなってるか、気に" 'br)
   (text "なるじゃないか。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "うっ、ううッ！")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 685 #t)
   (proc 11))
 (seg (? (= Y 4) (= S 1) (= 685 #t))
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "こいつは、お前の恥ずかしい＊＊＊の中まで見れる機械さ。見た" 'br)
   (text "事があるかい、自分のアソコの中をさ。")
   (wait)
   (text-reset 14)
   (proc 11))
 (seg (? (= Y 4) (>= S 6) (<= S 9) (= S 7) (= S 8) (= 686 #f))
   (proc 10)
   (text "「Mitsuko」" 'br)
   (text "ふぅッ、んんんんッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "冷たいか？　その肌触りがまた堪らないんだ。ナイフみたいに鋭くて、光を放ってる。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "たまらないねぇ、最初にこいつを調教の道具にしようと思った奴は最低の下衆野郎だ。しかもとびきり冷酷なサディスト！")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "ふぅっ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "被験者にとって、自分の＊＊＊の奥まで覗き見られる事が、どれ" 'br)
   (text "だけの屈辱かって事を、よくわかっていたのさ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "お前はもう、わたしの物だ。顔もオッパイも、＊＊＊の奥まで全" 'br)
   (text "部わたしの物なんだよ！")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 686 #t)
   (proc 11))
 (seg (? (= Y 4) (>= S 6) (<= S 9) (= S 7) (= S 8) (= 686 #t))
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "たまらないねぇ、最初にこいつを調教の道具にしようと思った奴は最低の下衆野郎だ。しかもとびきり冷酷なサディスト！")
   (wait)
   (text-reset 14)
   (proc 11))
 (seg (? (= Y 4) (= S 12) (= 687 #f))
   (proc 10)
   (text "「Mitsuko」" 'br)
   (text "うう〜ッ、ううぅぅ！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3072 0)
   (image-file "gpc¥a1_31b.gpc")
   (image-mem 1 0)
   (proc 12)
   (wait)
   (proc 10)
   (text "「Mitsuko」" 'br)
   (text "ふッ、ふぐぅぅぅッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "冷たい異物が中に入ってくのがわかるか？　こいつはすごく鋭いからね、何の抵抗もない。これだけ濡れてりゃ当然だけど。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "ふぅぅっ‥‥‥うっ、うっ、うう‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "くっくっ、＊＊＊の奥までよく見える。ピンク色の襞まで丸見え" 'br)
   (text "になってるんだよ。")
   (wait)
   (text-reset 14)
   (text "「Mitsuko」" 'br)
   (text "ううぅぅ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "奇麗な色だ。これは内臓の色‥‥‥本来なら人目に晒される事なんてありえない、見ちゃいけない物なのさ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "＊＊＊の中は襞で一杯だ、誰が良家のお嬢様だって？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "こいつは、男のチ○ポを咥えこむ為の物だろう、ええ！　なんて嫌らしいんだ。淫乱のお前にはぴったりの持ち物だよ。")
   (wait)
   (text-reset 14)
   (nop@)
   (inc-var H 1)
   (nop@)
   (set-reg 687 #t)
   (proc 11))
 (seg (? (= Y 4) (= S 12) (= 687 #f))
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "くっくっくっ、＊＊＊の奥まで丸見えになってるぞ。なんて恥ず" 'br)
   (text "かしい姿だ。こんな恥辱は他にないだろうね！")
   (wait)
   (text-reset 14)
   (proc 11)))