(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (nop@)
   (set-reg 980 #t)
   (set-reg 981 #t)
   (set-reg 982 #f)
   (set-reg 983 #f)
   (set-reg 984 #f)
   (set-reg 985 #f)
   (set-reg 986 #f)
   (set-reg 987 #f)
   (set-reg 988 #f)
   (set-reg 989 #f)
   (set-reg 990 #f)
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_32.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (if (</>
        (//
         (? (= P 9))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_09.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 9))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_09v.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 9)))))
        (// (nop@))))
   (load-mem "clm¥A1_32.clm" 32768)
   (load-mem "clm¥icon.clm" 20480)
   (mes-load? "mes¥icon_cl.mec" 0)
   (mes-load? 0)
   (exec-mem 256 "A 0")
   (exec-mem 256 "G 11 7 242 15 125")
   (exec-mem 256 "A 1")
   (mes-load? "mes¥icon_c2.mec" 0)
   (mes-load? 0)
   (text-frame 10 312 70 370)
   (exec-mem 256 "A 0")
   (proc 12)
   (define-proc 19
     (<>
      (if (</>
           (//
            (? (>= H 7) (= 987 #f))
            (nop@)
            (set-reg 987 #t)
            (mes-load? "mes¥icon_cl.mec" 0)
            (mes-load? 0)
            (mes-load? "mes¥icon_c2.mec" 0)
            (mes-load? 0))
           (// (nop@))))))
   (define-proc 15)
   (set-reg 161 #f)
   (if (</>
        (//
         (? (= 516 #t) (= 703 #f))
         (image-file "gpc¥a1_32a.gpc")
         (image-mem 1 0)
         (nop@)
         (set-reg 703 #t)
         (exec-mem 256 "P 11 7 242"))
        (// (nop@))))
   (proc 12))
 (seg (? (= R B)) (text "「Kiyomi」" 'br))
 (seg (? (>= R 1)) (text "「Mitsuko」" 'br))
 (seg (? (= 417 #t)) (wait) (text-reset 14))
 (seg (? (= 185 #f))
   (nop@)
   (proc 18)
   (text "うぅっ、うう‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "気持ちここに在らずって感じだな、その顔がまた劣情をそそる。存分に可愛がってやるからな。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "わたしの事が嫌いか？")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "うう、ん、んんッ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "その口では喋る事が出来ないか。まあいい、お前の身体は、もうわたし無しではいられないんだから。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "かつてのお前のペット、ナナも同じ。わたしじゃなきゃ満足出来ない身体になっちまったのさ。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "うぅぅ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "くっくっくっ、お前はもう心の中まで牝奴隷だ。何を言われても痛みも感じない。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "わたしはお前を失望させない、きっと満足させてやるさ。その後でお前の知っている事を、全部吐いてもらう。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "わたしの言っている事がわかるな？")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (exec-mem 256 "P 5 6 0")
   (mes-load? "mes¥md_d3pl1.mec" 4096)
   (mes-jump "mes¥md_d3_ms.mes")))