(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 3072 0)
  ((cmd 209) 0 5)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (text-frame 10 312 70 370)
  (image-file "gpc¥a1_31d.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (proc 10)
  (proc 18)
  (text "私がスパイに見えますか？　ナナにデータベースをハックする方法を教えたのも、機密の所在とアクセスコードを教えたのも私です。")
  (wait)
  (text-reset 14)
  (proc 17)
  (text "何でそんな事を知ってたんだ！")
  (wait)
  (text-reset 14)
  (proc 18)
  (text "知っている人間に聞いたから。誰に聞いたか教えてもいいですけどあなたにはどうする事も出来ません。")
  (wait)
  (text-reset 14)
  (proc 17)
  (text "お前の御託は聞きたくない。それは誰だ！")
  (wait)
  (text-reset 14)
  (proc 18)
  (text "サカタ・ジクムント　ユニバーサル　ネオテクの社長令嬢エリコ。坂田ザイバツのトップに立つ男の娘‥‥‥")
  (wait)
  (text-reset 14)
  (proc 17)
  (text "サカタ・ネオテク？　あのサカタ・ネオテクか！")
  (wait)
  (text-reset 14)
  (proc 18)
  (text "失望を味わったでしょう？　サカタ・ネオテクは事実上日本を支配している、超大企業ですものね。手出しは出来ないわ。")
  (wait)
  (text-reset 14)
  (proc 17)
  (text "そのサカタ・ネオテクの社長の娘が、お前に情報を洩らしたって言うのか。それじゃ、本当の黒幕はそのエリコって娘？")
  (wait)
  (text-reset 14)
  (proc 18)
  (text "いいえ黒幕は私よ。私は軍の電脳移植計画を良くないと思い、勝手にそれを妨害しようとした。エリコはその私に協力しただけ。")
  (wait)
  (text-reset 14)
  (proc 17)
  (text "どうしても自分を犯人にしたいようだな！")
  (wait)
  (text-reset 14)
  (proc 18)
  (text "エリコに手出し出来ない以上、もう調べようがないわ。あなたにはどうする事も出来ない、何をやってもね。")
  (wait)
  (text-reset 14)
  (proc 18)
  (text "これで事件はお終いね。私達を犯人に仕立てあげて、何もなかった事にしてしまう以外、手はないわ！")
  (wait)
  (text-reset 14)
  (proc 17)
  (text "くっ‥‥‥お前らが盗んだ機密は何処に隠した？")
  (wait)
  (text-reset 14)
  (proc 18)
  (text "知りません。エリコが何処かに捨ててしまったんでしょう。私も、他の３人も何の情報も持ってません。")
  (wait)
  (text-reset 14)
  (proc 17)
  (text "まんまと機密を葬り去ったって訳だな。大事なところは全部エリコに任せて、それ以上追求出来ないようにしたんだ！")
  (wait)
  (text-reset 14)
  (proc 17)
  (text "ばれるとわかっていながら、わざわざデータベース内の情報を消去したのもそのためか！")
  (wait)
  (text-reset 14)
  (proc 18)
  (text "当たり前です、私達は馬鹿じゃないわ。もっとも、他の３人はただの道具に等しいから、悪い事をしたと思いますけど。")
  (wait)
  (text-reset 14)
  (proc 17)
  (text "くっ‥‥‥それが本当だと、どうして信じられる。自分を犠牲にしても軍の愚行を止めようとしたって？　お前は何様なんだよ！")
  (wait)
  (text-reset 14)
  (proc 18)
  (text "これ以上は何も知りません、拷問しても無駄よ。")
  (wait)
  (text-reset 14)
  (proc 17)
  (text "そいつはどうかな。お楽しみは抜きで、死人でも口を割るようなきついのを試してやろうか！")
  (wait)
  (text-reset 14)
  (proc 18)
  (text "それでも何も喋らないわ。あなたはもうどうする事も出来ないの。エリコを捕まえて、拷問にかけない限りね。")
  (wait)
  (text-reset 14)
  (proc 17)
  (text "‥‥‥‥‥‥お前の顔を見ていると反吐が出る。")
  (wait)
  (text-reset 14)
  (proc 18)
  (text "さようなら、ご主人様‥‥‥")
  (wait)
  (text-reset 14)
  (proc 11)
  (nop@)
  (set-reg 64 #t)
  (nop@)
  (set-reg 938 #t)
  (exec-mem 18688 3)
  (exec-mem 18688 5 1 0)
  (exec-mem 3072 0)
  ((cmd 209) 0 5)
  (image-file "gpc¥waku.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (exec-mem 9504 "E")
  (exec-mem 256 "I")
  (mes-jump "mes¥MA_A05.MES")))