(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (proc 0)
  (image-file "gpc¥a1_31a.gpc")
  (image-mem 1 0)
  (exec-mem 256 "G 8 6 0 3 279")
  (exec-mem 256 "G 9 71 0 3 279")
  (proc 12)
  (proc 6)
  (branch-reg
   991
   (</>
    (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 6 16))
    (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 71 16))))
  (proc 10)
  (text "「Mitsuko」" 'br)
  (text "ううン、ううぅぅ〜ッ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "よしよし、可愛い牝奴隷になってきたな。つい先刻までのお前とはまるで別人みたいだ。")
  (wait)
  (text-reset 14)
  (text "「Mitsuko」" 'br)
  (text "ううっ‥‥‥うっ、うっ‥‥‥ううっ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "ギャグを外したら全部話してくれそうだ。")
  (wait)
  (text-reset 14)
  (text "「Mitsuko」" 'br)
  (text "んん！　んん、ふぅぅッ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "だけど、まだ外してやらない。二度と社会復帰出来なくなるまでもう少しだからね。")
  (wait)
  (text-reset 14)
  (text "「Mitsuko」" 'br)
  (text "んん‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "そう、従順な牝奴隷らしくなった褒美に、わたしの聖水をやろう。女王様のおいしい飲み物だ。どうだ欲しいか？")
  (wait)
  (text-reset 14)
  (text "「Mitsuko」" 'br)
  (text "うう！　ううッ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "よしよし。一滴もこぼすんじゃないよ！")
  (wait)
  (text-reset 14)
  (proc 11)
  (exec-mem 3072 0)
  (proc 5)
  (exec-mem 256 "A 1")
  (text-frame 0 0 79 399)
  (text-reset 14)
  (text-frame 10 312 70 370)
  (image-file "gpc¥a1_31a1.gpc")
  (image-mem 1 0)
  (exec-mem 29184 0 1 "gpa¥a1_31.dpb" 0)
  (exec-mem
   29184
   1
   1
   "A............A............A............A............A............A............A............A............A............")
  (exec-mem 29184 2 1 0 0)
  (exec-mem 29184 3 1)
  (exec-mem 256 "S 0")
  (proc 6)
  (branch-reg
   991
   (</>
    (/
     (if (</>
          (//
           (? (= Y 1))
           (exec-mem 9504 "C icon¥tool12.gpc,GPC")
           (image-mem 1 0 6 16))
          (//
           (? (= Y 2))
           (exec-mem 9504 "C icon¥tool13.gpc,GPC")
           (image-mem 1 0 6 40)))))
    (/
     (if (</>
          (//
           (? (= Y 1))
           (exec-mem 9504 "C icon¥tool12.gpc,GPC")
           (image-mem 1 0 71 16))
          (//
           (? (= Y 2))
           (exec-mem 9504 "C icon¥tool13.gpc,GPC")
           (image-mem 1 0 71 40)))))))
  (proc 10)
  (text "「Kiyomi」" 'br)
  (text "くっくっくっ、おいしいだろう。口を開けてもっとお飲み！")
  (wait)
  (text-reset 14)
  (text "「Mitsuko」" 'br)
  (text "うぐッ、うぐッ、ゴフッ！")
  (wait)
  (text-reset 14)
  (text "「Mitsuko」" 'br)
  (text "うっ、うっ、うっ‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (proc 11)
  (proc 10)
  (text "「Kiyomi」" 'br)
  (text "これでお前は洗礼を受けて、本物の牝奴隷になったって訳さ！")
  (wait)
  (text-reset 14)
  (text "「Mitsuko」" 'br)
  (text "ううぅぅぅぅぅぅ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "よし、最後の調教だ。")
  (wait)
  (text-reset 14)
  (exec-mem 18688 3)
  (exec-mem 18688 5 1 0)
  (exec-mem 3072 0)
  (mes-jump "mes¥MD_D03.MES")))