(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (loop
   (set-var S 0)
   (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
   (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 9) (= 991 #f) (= 1020 #f) (= Q 9) (= 987 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name8.gpc,GPC")
   (image-mem 1 0 9 184)
   (proc 1)
   (set-var Q 9))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 9) (= 991 #t) (= 1020 #f) (= Q 9) (= 987 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name8.gpc,GPC")
   (image-mem 1 0 52 184)
   (proc 1)
   (set-var Q 9))
 (seg (? (= Z 2) (= Z 3) (= Z 9) (= 991 #f) (= 1020 #f) (>= Q 1) (= 987 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= Z 9) (= 991 #t) (= 1020 #f) (>= Q 1) (= 987 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1) (= 987 #f))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1) (= 987 #f))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (>= Z 1)) (mes-load? 4096))
 (seg (? (= Y 1) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 18)
      (text "うっ、うう‥‥‥‥‥‥")
      (proc 13)
      (proc 17)
      (text "お前はわたしの牝奴隷だ。わたしに可愛がってもらえて、うれしいだろう？")
      (proc 13)
      (proc 18)
      (text "うう‥‥‥‥‥‥")
      (proc 13)
      (proc 17)
      (text "目茶苦茶にしてやる、身体も心もだ。整ったその顔も、オッパイも＊＊＊も壊れるまで可愛がってやる。")
      (proc 13)
      (proc 17)
      (text "エイプリルやレイファよりも‥‥‥ナナよりも念入りにだ。お前は特別な牝奴隷だからね。")
      (proc 13)
      (proc 18)
      (text "ンッ、ンン‥‥‥んぐゥ！")
      (proc 13))
     (/
      (proc 17)
      (text "さて、どうやって目茶苦茶にしてやろうかね。わたしの事を一生忘れられなくなる、そんなやり方がいいね。")
      (proc 13)
      (proc 17)
      (text "考えるだけで、こっちも欲情してくるね‥‥‥‥‥‥")
      (proc 13))
     (/ (proc 18) (text "うっ、うう‥‥‥‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 10))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 17)
      (text "わたしは力の加減が出来なくなってきたよ。ついロッドを持つ手に力が入って、お前を叩き潰してしまいそうだ‥‥‥")
      (proc 13)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥")
      (proc 13)
      (proc 17)
      (text "いっその事、殴り殺して剥製にでもしてしまおうか？")
      (proc 13)
      (proc 18)
      (text "うう！　う、んんッ‥‥‥")
      (proc 13)
      (proc 17)
      (text "いくら牝奴隷でも、それは嫌か。しかし、全てはお前が悪いんだ。わたしを本気にさせてしまったのは、お前なんだから。")
      (proc 13)
      (proc 17)
      (text "このまま続けたら、確実にお前を殺してしまうな。そろそろ終わりにするべきかもしれない‥‥‥")
      (proc 13))
     (/
      (proc 17)
      (text "わたしは力の加減が出来なくなってきたよ。ついロッドを持つ手に力が入って、お前を叩き潰してしまいそうだ‥‥‥")
      (proc 13))))
   (proc 11))
 (seg (? (>= Y 1) (<= Y 2) (= S 1) (>= H 11) (= 702 #f))
   (proc 10)
   (proc 18)
   (text "うぐッ‥‥‥‥‥‥")
   (proc 13)
   (proc 11)
   (proc 0)
   (proc 5)
   (exec-mem 256 "P 11 7 242")
   (image-file "gpc¥a1_32d.gpc")
   (image-mem 1 0)
   (proc 12)
   (proc 6)
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (branch-reg
          991
          (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16)))))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (branch-reg
          991
          (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40)))))))
   (proc 10)
   (proc 18)
   (text "はぁ、はぁ、はぁ、はぁ‥‥‥‥‥‥")
   (proc 13)
   (proc 17)
   (text "苦しかったか？　それにしても、わたしは幸運だった‥‥‥")
   (proc 13)
   (proc 17)
   (text "お前に牝奴隷の洗礼を施しただけでなく、純潔まで頂戴してしまったんだからね！")
   (proc 13)
   (proc 18)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (proc 13)
   (proc 17)
   (text "喋ってもらおうか、知っている事を全て。機密を盗むために、他の３人を集めたのはお前だな？　")
   (proc 13)
   (proc 18)
   (text "そうです‥‥‥他の２人はナナの知り合いだったので、彼女達を私に薦めたのはナナですけど‥‥‥")
   (proc 13)
   (proc 17)
   (text "お前は、軍部が機構＝システムを開発している事をどうして知っていたんだ？")
   (proc 13)
   (proc 18)
   (text "私が秘書をしていた高官が‥‥‥その開発に携わっていたので。")
   (proc 13)
   (proc 17)
   (text "捕まればただでは済まないって事は、わかってたはずだ。それに、優秀なハッカーを抱えてた割に計画がずさんすぎる。")
   (proc 13)
   (proc 18)
   (text "計画がずさんだったとしたら、それは私が素人だったからよ。それに、私が機密を盗んだのは、お金のためじゃないわ。")
   (proc 13)
   (proc 18)
   (text "私が機密を盗んだのは、それがよくない物だからです‥‥‥")
   (proc 13)
   (proc 17)
   (text "よくない？　何の話をしてるんだ。ナナはお前達が盗んだ機密の内容が、ポッドモッド技術に関する物だったと言っていた。")
   (proc 13)
   (proc 18)
   (text "それがよくない物なんです‥‥‥私自身、電脳移植を受けているけれど、それは望んでした事。")
   (proc 13)
   (proc 18)
   (text "軍は、兵士全員‥‥‥いいえ、全ての人間にポッドモッドを受けさせようとしていたんです！")
   (proc 13)
   (proc 17)
   (text "それはお前自身の主義、主張だろう。たとえそれが人の権利、移植を望まない人間の権利を奪う事になったとしても‥‥‥")
   (proc 13)
   (proc 17)
   (text "お前がそれを止める権利もない。結局、お前だって軍部と同じただのエゴイストなのさ。")
   (proc 13)
   (proc 18)
   (text "違う‥‥‥そうじゃないわ‥‥‥")
   (proc 13)
   (proc 17)
   (text "黙れ。お前はナナに軍のデータベースの何処に情報があるか知っててどれを盗むか指示したそうだな。何故そんな事を知っていた？")
   (proc 13)
   (proc 17)
   (text "いくら秘書だからって、そんな重要機密に触れられる訳はない。例の高官をたぶらかしたってのも、説得力はないね。")
   (proc 13)
   (proc 17)
   (text "お前は処女だった。体を使って情報を得た訳じゃない。そうだったとしても、そんな事をする理由がない、お前はスパイか？")
   (proc 13)
   (nop@)
   (set-reg 702 #t)
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 11) (= 702 #t)) (mes-jump "mes¥md_d3_r1.mes"))
 (seg (? (= Y 1) (= S 2))
   (sound 'se 1)
   (branch-reg
    689
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_32da.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 6)
      (branch-reg
       991
       (</>
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 6 16))
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "うっ、ふぅぅっ‥‥‥")
      (proc 13)
      (proc 17)
      (text "お前はもう、どこを苛められても感じてしまう、卑しい牝奴隷だ。わたしの為なら何でもする、そうだな？")
      (proc 13)
      (proc 18)
      (text "うう、ううっ！")
      (proc 13)
      (nop@)
      (set-reg 689 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "うっ、ふぅぅっ‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 3))
   (sound 'se 1)
   (branch-reg
    690
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_32db.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 6)
      (branch-reg
       991
       (</>
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 6 16))
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "ンン‥‥‥ンぐッ！")
      (proc 13)
      (proc 17)
      (text "乳首を固くして、ロッドで打たれるのを待ってる。気持ちいいか？待っただけの甲斐はあったろう？")
      (proc 13)
      (proc 18)
      (text "ふぐぅ‥‥‥‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 690 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ンン‥‥‥ンぐッ！") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 4))
   (sound 'se 1)
   (branch-reg
    691
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_32dc.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 10)
      (proc 18)
      (text "うッ、うぅぅぅぅ〜っ！")
      (proc 13)
      (proc 17)
      (text "痛いだろう。お前のオッパイは、まだ熟れていない果実みたいだけど熟れる前にわたしのロッドで弾けちまうかもね！")
      (proc 13)
      (proc 18)
      (text "ンン、ンンン〜ッ！")
      (proc 13)
      (nop@)
      (set-reg 691 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "うッ、うぅぅぅぅ〜っ！") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 5))
   (sound 'se 1)
   (branch-reg
    692
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_32dd.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 10)
      (proc 18)
      (text "ンンッ！　ふぅぅン‥‥‥")
      (proc 13)
      (proc 17)
      (text "いいぞ、その調子だ。牝奴隷は誰をはばかる事なく、人前でも感じてしまうものなのさ。さあ、もっと喘ぎ声をあげな！")
      (proc 13)
      (proc 18)
      (text "ングッ、ンン！")
      (proc 13)
      (nop@)
      (set-reg 692 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ンンッ！　ふぅぅン‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 6))
   (sound 'se 1)
   (branch-reg
    693
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_32de.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 6)
      (branch-reg
       991
       (</>
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 6 16))
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "ふぅッ‥‥‥う、うぅぅン！")
      (proc 13)
      (proc 17)
      (text "あんまり感じすぎて、オシッコ漏らすんじゃないよ。これ以上お前の臭いが染み付いたらたまんないからね。")
      (proc 13)
      (proc 18)
      (text "うっ、うっ、ううッ‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 693 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ふぅっ‥‥‥う、うぅぅン！") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 7))
   (sound 'se 1)
   (branch-reg
    694
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_32df.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 10)
      (proc 18)
      (text "ングッ‥‥‥")
      (proc 13)
      (proc 17)
      (text "まったく何て牝奴隷なんだろうねぇ、＊＊＊がグチュグチュだ！" 'br)
      (text "小便漏らしたみたいにびしょ濡れになってるよ！")
      (proc 13)
      (proc 18)
      (text "うッ‥‥‥‥‥‥‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 694 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ングッ‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 8))
   (sound 'se 1)
   (branch-reg
    695
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_32dg.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 6)
      (branch-reg
       991
       (</>
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 6 16))
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "ふっ、ふぅッ！")
      (proc 13)
      (proc 17)
      (text "真っ白なお腹だ。まさに血統書付きに相応しい、いい毛並みだよ！ただ、整い過ぎなのが鼻につく。傷があって丁度いいよ！")
      (proc 13)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 695 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ふっ、ふぅッ！") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 9))
   (sound 'se 1)
   (branch-reg
    696
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_32dh.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 6)
      (branch-reg
       991
       (</>
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 6 16))
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "うッ、うぐぅぅぅッ！")
      (proc 13)
      (proc 17)
      (text "＊＊＊叩かれて気持ちいいか？　正確には＊＊＊にゃ触れて" 'br)
      (text "もいないけど、敏感になってるお前には、そう感じるはずだ。")
      (proc 13)
      (proc 18)
      (text "うう〜ッ、ん‥‥‥んふゥ！")
      (proc 13)
      (nop@)
      (set-reg 696 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "うッ、うぐぅぅぅッ！") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 10))
   (sound 'se 1)
   (branch-reg
    697
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_32di.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 6)
      (branch-reg
       991
       (</>
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 6 16))
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "ふぅぅぅン！")
      (proc 13)
      (proc 17)
      (text "ここを苛められると、気持ちいいだろう？　＊＊＊その物を嬲ら" 'br)
      (text "れるよりいいかも。わたしは女の身体の事を熟知してるのさ。")
      (proc 13)
      (proc 18)
      (text "うっ、うう‥‥‥‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 697 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ふぅぅぅン！") (proc 13))))
   (proc 11))
 (seg (? (= Y 1) (= S 11))
   (sound 'se 1)
   (branch-reg
    698
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_32dj.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "あぐッ！　んふ、ふぅン！")
      (proc 13)
      (proc 17)
      (text "ちっ、汚い汁で自慢のロッドが汚れちまったじゃないか。盛大に溢れさせやがって。どういうつもりだ？")
      (proc 13)
      (proc 18)
      (text "ふぅん、ん、んん〜ッ‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 698 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あぐッ！　んふ、ふぅン！") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 18)
      (text "ンン、ふぅぅぅン‥‥‥")
      (proc 13)
      (proc 17)
      (text "随分素直になったな、いい子だ。鞭に頬擦りする程これが好きか？お前の血と、愛液で汚れたこの鞭が。")
      (proc 13)
      (proc 17)
      (text "くっくっくっ‥‥‥お前は可愛い牝奴隷だよ、全く。その顔もオッパイも、＊＊＊も全てが素晴らしい。")
      (proc 13)
      (proc 18)
      (text "うぐぅ‥‥‥‥‥‥")
      (proc 13)
      (proc 17)
      (text "さすがに血統書が付いていると、他とは違うって事か。お前を色々な人間に披露してやりたいねぇ。皆羨ましがるだろうよ！")
      (proc 13)
      (proc 17)
      (text "元良家の令嬢が完璧な牝奴隷になって、公衆の面前で＊＊＊を弄" 'br)
      (text "るんだ。人目もはばからずにね。")
      (proc 13))
     (/ (proc 18) (text "ンン、ふぅぅぅン‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 10))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 17)
      (text "いくら何でも、もう観念したろう。元々お前みたいな繊細な女に、わたしの拷問が堪えられる訳がない。")
      (proc 13)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥")
      (proc 13)
      (proc 17)
      (text "無理に我慢してくれたお陰で、わたしはいい思いをさせてもらったけどね。可愛い牝奴隷も手に入れたし。")
      (proc 13)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (proc 13)
      (proc 17)
      (text "もう少ししたら、ギャグを外してやる。そうしたら、知ってる事を全部喋るんだ。いいな？")
      (proc 13))
     (/
      (proc 17)
      (text "もう少ししたら、ギャグを外してやる。そうしたら、知ってる事を全部喋るんだ。いいな？")
      (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 11) (= 702 #t)) (mes-jump "mes¥md_d3_r2.mes"))
 (seg (? (= Y 2) (= S 2))
   (sound 'se 1)
   (branch-reg
    689
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_32da.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 6)
      (branch-reg
       991
       (</>
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 6 16))
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "ぐぅッ‥‥‥‥‥‥")
      (proc 13)
      (proc 17)
      (text "ああ、ぞくぞくするね。美しい女が、顔も身体もズタズタに引き裂かれてくのを見るのは‥‥‥わたしは異常だと思うか？")
      (proc 13)
      (proc 18)
      (text "うう‥‥‥ううッ！")
      (proc 13)
      (nop@)
      (set-reg 689 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ぐぅッ‥‥‥‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 3))
   (sound 'se 1)
   (branch-reg
    690
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_32db.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 6)
      (branch-reg
       991
       (</>
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 6 16))
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "ふぐぅぅぅッ‥‥‥‥‥‥")
      (proc 13)
      (proc 17)
      (text "乳首をかすめたね。もう少しで可愛いサクランボを切り落としてしまうとこだった。まあ、それも牝奴隷の烙印としちゃ上等だが。")
      (proc 13)
      (proc 18)
      (text "うぐっ、ううッ、うう〜ッ！")
      (proc 13)
      (nop@)
      (set-reg 690 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ふぐぅぅぅッ‥‥‥‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 4))
   (sound 'se 1)
   (branch-reg
    691
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_32dc.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 10)
      (proc 18)
      (text "んふッ、ふぐッ‥‥‥")
      (proc 13)
      (proc 17)
      (text "感じてる？　＊＊＊が大洪水になってる。いいや、それだけじゃ" 'br)
      (text "ない。身体が紅潮して産まれたての赤ん坊みたいだよ！")
      (proc 13)
      (proc 18)
      (text "ぐぅッ‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 691 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "んふッ、ふぐッ‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 5))
   (sound 'se 1)
   (branch-reg
    692
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_32dd.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 10)
      (proc 18)
      (text "んっ、んんッ‥‥‥ふぐぅ！")
      (proc 13)
      (proc 17)
      (text "もっと打ってくれって？　人使いが荒いね、ちょっとぐらい待ってくれてもいいだろう。")
      (proc 13)
      (proc 18)
      (text "うぅ〜っ、んんッ‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 692 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "んっ、んんッ‥‥‥ふぐぅ！") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 6))
   (sound 'se 1)
   (branch-reg
    693
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_32de.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 6)
      (branch-reg
       991
       (</>
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 6 16))
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "ンン、アフゥゥッ‥‥‥")
      (proc 13)
      (proc 17)
      (text "＊＊＊までもう少し、お前はそう思ってる。焦らされるくらいな" 'br)
      (text "ら、早くそこを苛めて欲しいってな！")
      (proc 13)
      (proc 18)
      (text "うう‥‥‥‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 693 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ンン、アフゥゥッ‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 7))
   (sound 'se 1)
   (branch-reg
    694
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_32df.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 10)
      (proc 18)
      (text "ンン〜ッ‥‥‥")
      (proc 13)
      (proc 17)
      (text "牝奴隷を調教するコツはね、焦らして焦らし抜いて、嫌でもご主人様の言いなりにさせる事さ。簡単にご褒美をあげちゃ駄目だ。")
      (proc 13)
      (proc 18)
      (text "ンッ、ンッ、ンン〜ッ！")
      (proc 13)
      (nop@)
      (set-reg 694 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ンン〜ッ‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 8))
   (sound 'se 1)
   (branch-reg
    695
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_32dg.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 6)
      (branch-reg
       991
       (</>
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 6 16))
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "ん、んん〜ッ！")
      (proc 13)
      (proc 17)
      (text "お前の身体は完璧だ、腹にも脂肪ひとつない。牝奴隷にするには勿体ないって気さえしてきたよ‥‥‥")
      (proc 13)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 695 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ん、んん〜ッ！") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 9))
   (sound 'se 1)
   (branch-reg
    696
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_32dh.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 6)
      (branch-reg
       991
       (</>
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 6 16))
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "ふぐッ、うぁぁぁッ！")
      (proc 13)
      (proc 17)
      (text "ここは痛いだろう。＊＊＊のまわりは肌が敏感に出来てるのさ。" 'br)
      (text "可哀想に血が出てる。それでも気持ちいいか？")
      (proc 13)
      (nop@)
      (set-reg 696 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ふぐッ、うぁぁぁッ！") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 10))
   (sound 'se 1)
   (branch-reg
    697
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_32di.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 6)
      (branch-reg
       991
       (</>
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 6 16))
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 71 16))))
      (proc 15)
      (proc 10)
      (proc 18)
      (text "ン、ンン〜ッ！　ンふッ、ンふぅぅン！")
      (proc 13)
      (proc 17)
      (text "おやおや、ひときわ大きな声を出して。まさかイッちまったんじゃないだろうねぇ。鞭で打たれて？　まさかね！")
      (proc 13)
      (nop@)
      (set-reg 697 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ン、ンン〜ッ！　ンふッ、ンふぅぅン！") (proc 13))))
   (proc 11))
 (seg (? (= Y 2) (= S 11))
   (sound 'se 1)
   (branch-reg
    698
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_32dj.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 12)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 18)
      (text "あぐぅ‥‥‥")
      (proc 13)
      (proc 17)
      (text "太股の肉が削げるくらい、強く打ってやる。身体中に牝奴隷の印を刻んでやるんだ！")
      (proc 13)
      (proc 18)
      (text "ふっ、ふっ、ふうっ‥‥‥")
      (proc 13)
      (nop@)
      (set-reg 698 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あぐぅ‥‥‥") (proc 13))))
   (proc 11))
 (seg (? (= Y 8) (= S 1) (= 699 #f))
   (proc 10)
   (branch-reg
    701
    (</>
     (/
      (proc 18)
      (text "ふぅぅ‥‥‥‥‥‥")
      (proc 13)
      (proc 17)
      (text "こいつを知ってるな、レズビアンがふたりで楽しむためのバイブ。ナナとする時もこいつを使って楽しんでたか？")
      (proc 13)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥")
      (proc 13)
      (proc 17)
      (text "こいつでお前を貫いてやるんだ。片方はわたしの物、もう片方がお前の中に入るんだよ。")
      (proc 13)
      (proc 18)
      (text "うっ、ううッ！")
      (proc 13)
      (proc 17)
      (text "そうか、そんなに嬉しいか。待ちきれないって？")
      (proc 13))
     (/
      (proc 18)
      (text "うぅぅぅ‥‥‥‥‥‥")
      (proc 13)
      (proc 17)
      (text "顔を背ける事はないだろう。先刻までお前の中に入ってた物だぞ？血と愛液で汚れてはいるが、全部お前の＊＊＊から出た物だ。")
      (proc 13)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥")
      (proc 13)
      (proc 17)
      (text "後で奇麗に掃除させてやる。お前の舌で奇麗にするんだよ！")
      (proc 13))))
   (nop@)
   (set-reg 699 #t)
   (proc 11))
 (seg (? (= Y 8) (= S 1) (= 699 #t))
   (proc 10)
   (proc 18)
   (text "ふぅぅ‥‥‥‥‥‥")
   (proc 13)
   (proc 11))
 (seg (? (= Y 8) (>= S 3) (<= S 4) (= 700 #f))
   (proc 10)
   (proc 17)
   (text "くっくっ、これもパイズリって言うのかねぇ‥‥‥")
   (proc 13)
   (proc 18)
   (text "ふぐぅ、うう！　んん‥‥‥")
   (proc 13)
   (proc 17)
   (text "しっかり可愛がってくれ、ちゃんとおっ立ってないと役に立たないじゃないか！")
   (proc 13)
   (proc 18)
   (text "う、ううッ‥‥‥ううッ！")
   (proc 13)
   (proc 17)
   (text "バイブが擦れるたびに、わたしのアソコも熱くなってくる‥‥‥")
   (proc 13)
   (proc 17)
   (text "まるで男になった気分だ。わたしのチ○ポはどうだい、感想は？　並の男のフニャチンとは出来が違うだろう！")
   (proc 13)
   (nop@)
   (set-reg 700 #t)
   (proc 11))
 (seg (? (= Y 8) (>= S 3) (<= S 4) (= 700 #t))
   (proc 10)
   (proc 18)
   (text "ふぐぅ、うう！　んん‥‥‥")
   (proc 13)
   (proc 11))
 (seg (? (= Y 8) (= S 12) (= 701 #f))
   (nop@)
   (inc-var H 1)
   (proc 0)
   (proc 5)
   (exec-mem 256 "G 0 7 265 9 100")
   (exec-mem 256 "G 30 29 0 12 136")
   (exec-mem 256 "G 31 58 0 19 320")
   (exec-mem 256 "P 11 7 242")
   (image-file "gpc¥a1_32b.gpc")
   (image-mem 1 0)
   (proc 12)
   (proc 6)
   (branch-reg
    991
    (</>
     (/ (exec-mem 9504 "C icon¥tool19.gpc,GPC") (image-mem 1 0 6 184))
     (/ (exec-mem 9504 "C icon¥tool19.gpc,GPC") (image-mem 1 0 71 184))))
   (proc 10)
   (proc 18)
   (text "うぐぅぅぅぅッ！")
   (proc 13)
   (proc 17)
   (text "暴れるんじゃないよ。＊＊＊はぱっくり口を開けて、こいつを欲" 'br)
   (text "しがってるじゃないか。")
   (proc 13)
   (proc 17)
   (text "なかなか固いね‥‥‥くくっ、先刻の膣鏡とは太さが違うから。")
   (proc 13)
   (proc 18)
   (text "うッ、ふぅぅぅン！")
   (proc 13)
   (proc 17)
   (text "根元まで入ったよ‥‥‥お前、処女だったのか？")
   (proc 13)
   (proc 18)
   (text "うっ、うっ‥‥‥ううッ！")
   (proc 13)
   (proc 17)
   (text "それは悪い事をした。でももう遅い。お前の初物は頂いちまった。後はせいぜい楽しむこったね。")
   (proc 13)
   (proc 18)
   (text "ふんっ‥‥‥ふっ、ふっ、ふっ‥‥‥")
   (proc 13)
   (proc 17)
   (text "初めての割には、いい具合になってるようじゃないか。")
   (proc 13)
   (proc 18)
   (text "んっ、んっ、んっ、んっ！")
   (proc 13)
   (proc 17)
   (text "ほらもっと腰を使って。そんな事じゃ、わたしはいかないよ！")
   (proc 13)
   (proc 18)
   (text "んっ、んっ、んっ、んっ‥‥‥‥‥‥")
   (proc 13)
   (proc 17)
   (text "ああ‥‥‥身体が痺れるみたいだ。お前の＊＊＊が疼くたびに、" 'br)
   (text "わたしの方にもそれが伝わってくる。")
   (proc 13)
   (proc 18)
   (text "ンン、ンン‥‥‥ンンンン！")
   (proc 13)
   (proc 17)
   (text "こんな太いのを飲み込んでしまうとは、つくづく大した牝奴隷だ。とても初めてとは思えないね！")
   (proc 13)
   (proc 18)
   (text "ンフッ‥‥‥")
   (proc 13)
   (proc 17)
   (text "そうそう、その調子‥‥‥クッ、わたしまで疼いてきた‥‥‥")
   (proc 13)
   (proc 18)
   (text "ふぅぅン、ふぅぅぅぅン！")
   (proc 13)
   (proc 17)
   (text "ハァ、ハァ、ハァ‥‥‥なんだ、もうイッちまったのか！")
   (proc 13)
   (proc 17)
   (text "ご主人様がイッてないのに、自分だけ満足しやがって。")
   (proc 13)
   (proc 11)
   (proc 0)
   (proc 5)
   (exec-mem 256 "P 0 7 265")
   (exec-mem 256 "P 30 29 0")
   (exec-mem 256 "P 31 58 0")
   (image-file "gpc¥a1_32c.gpc")
   (image-mem 1 0)
   (proc 12)
   (proc 6)
   (branch-reg
    991
    (</>
     (/ (exec-mem 9504 "C icon¥tool19.gpc,GPC") (image-mem 1 0 6 184))
     (/ (exec-mem 9504 "C icon¥tool19.gpc,GPC") (image-mem 1 0 71 184))))
   (proc 10)
   (proc 18)
   (text "ううぅぅぅぅ〜ッ！")
   (proc 13)
   (nop@)
   (set-reg 701 #t)
   (proc 11))
 (seg (? (= Y 8) (= S 12) (= 701 #t))
   (proc 10)
   (proc 17)
   (text "ご主人様を差し置いて、自分だけイッちまうような牝奴隷にご褒美はあげられないね。")
   (proc 13)
   (proc 11))
 (seg*))