(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (proc 10)
  (text "「Kiyomi」" 'br)
  (text "盗んだ機密を何処に隠した？　ミツコは捨てちまったとか言ってたが、そんな訳はないよな。")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "全部はしらない。わたしはちょっとだけしか持ってなかったもん。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "残りはプリスって女が持ってるんだな？　それで、お前が持ってた分はどうしたんだ。")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "プリスが、エイプリルとレイファに持たせようって。あのふたりなら、つかまりそうにないからって。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "エイプリルとレイファは、その事を知っていたのか？")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "しらない。ふたりには教えないほうがいいって‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "だろうな。あのふたりが、わたしの拷問に耐えられたとは思わないから、知っていたならゲロしちまったはずさ。")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "それで、どうやってふたりに機密を隠したんだ？")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "エイプリルは、ちつの中にマイクロチップをいれてるの。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "ちつ？　つまり、アソコの中って事だな。レイファは？")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "いれずみをしらべればわかるって。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "刺青だって？　記憶にないな‥‥‥まあいい、調べればわかる事だからな。お前の知っている事はそれだけか？")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "と、おもうけど‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "よし、エイプリルとレイファをもう一度絞めあげてやる。それと、プリスって女だ。秘密警察だって知った事かい。")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "ねぇ〜ぜんぶ言ったから、もういいでしょう‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "甘ったるい声を出すんじゃないよ、どうして欲しいってんだ！")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "もっといたくしてぇ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "ふざけるな。そんなのはお断わりだね。")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "そ、そんなぁ‥‥‥")
  (wait)
  (text-reset 14)
  (nop@)
  (set-reg 70 #t)
  (proc 11)
  (exec-mem 18688 3)
  (exec-mem 18688 5 1 0)
  (exec-mem 3072 0)
  ((cmd 209) 0 5)
  (image-file "gpc¥waku.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (exec-mem 9504 "E")
  (exec-mem 256 "I")
  (mes-jump "mes¥MA_B05.MES")))