(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (nop@)
   (set-reg 980 #t)
   (set-reg 981 #t)
   (set-reg 982 #f)
   (set-reg 983 #f)
   (set-reg 984 #f)
   (set-reg 985 #f)
   (set-reg 986 #f)
   (set-reg 987 #f)
   (set-reg 988 #f)
   (set-reg 989 #f)
   (set-reg 990 #f)
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_40_a.gpc")
   (image-mem 0 3)
   (image-file "gpc¥a1_40_b.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (if (</>
        (//
         (? (= P 10))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_10.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 10))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_10v.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 10)))))
        (// (nop@))))
   (exec-mem 256 "E")
   (load-mem "clm¥A1_40.clm" 32768)
   (load-mem "clm¥icon.clm" 20480)
   (mes-load? "mes¥icon_cl.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥icon_c2.mec" 0)
   (mes-load? 0)
   (text-frame 10 312 70 370)
   (exec-mem 256 "A 0")
   (proc 12)
   (define-proc 15
     (<>
      (if (</>
           (//
            (? (>= H 3) (= 749 #f))
            (image-file "gpc¥a1_40a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 749 #t)
            (proc 12))
           (// (proc 12))))))
   (set-var H 0)
   (proc 10)
   (text "「Eriko」" 'br)
   (text "うぅ〜ッ、なにこれぇ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "何じゃないんだよ、この馬鹿女が。お前はこれから拷問にかけられるんだ。うんとキツイ奴にね！")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "ごうもん‥‥‥なにをするのォ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "馬鹿でも脅える事はあるらしいね。お前は親父の威光の傘の下で安泰な暮らしをしてきた、でもこれからはそうはいかないよ！")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしはね、お前みたいな女が大嫌いなのさ。混血だとか、一族に疎まれてるとか、手前の不幸を売りもんにして‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "他人に同情してもらおうって、その根性が気に入らない。世の中そんなに甘くないって事を身体に教えてやるよ！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (exec-mem 256 "P 5 6 0")
   (loop
    (set-var S 0)
    (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
    (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (= Z 1) (= 991 #f))
   (proc 0)
   (exec-mem 256 "P 5 71 0")
   (nop@)
   (set-reg 991 #t)
   (exec-mem 256 "P 8 6 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 71 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 71 40))))
   (load-mem "clm¥icon2.clm" 20480)
   (proc 1))
 (seg (? (= Z 1) (= 991 #t))
   (proc 0)
   (exec-mem 256 "P 5 6 0")
   (nop@)
   (set-reg 991 #f)
   (exec-mem 256 "P 9 71 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 6 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 6 40))))
   (load-mem "clm¥icon.clm" 20480)
   (proc 1))
 (seg (? (= Z 2) (= 991 #f))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #f))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Z 2) (= 991 #t))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #t))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Y 1) (= S 1) (<= H 3))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Eriko」" 'br)
      (text "ここ、暗くってキライ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "何を悠長な事を言ってんだよ。あんたが好きだろうが嫌いだろうがそんなのは知った事じゃないんだ。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "いいか、お前は囚人だ。今までみたいになに不自由ない生活が出来るなんて思うんじゃないよ。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "よ、よくわかんない‥‥‥あなたこわいわ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "つくづく馬鹿な娘だねっ！　坂田はあんたにどんな教育を施したんだい。不思議になってくるよ。")
      (wait)
      (text-reset 14))
     (/ (text "「Eriko」" 'br) (text "ここ、暗くってキライ‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 6))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Eriko」" 'br)
      (text "うう〜っ、お洋服がボロボロよォ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "全くこたえていないようだね。これだけ痛い目にあわせてやったってのに。お前はマゾヒストか？")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "いたいのは平気なの‥‥‥だけど、お洋服がァ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そうかい、平気ね。それじゃもっと酷い事をしてやるよ。あんたみたいな女にピッタリの方法でね！")
      (wait)
      (text-reset 14))
     (/
      (text "「Eriko」" 'br)
      (text "うう〜っ、お洋服がボロボロよォ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 7))
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "さあ、そのボロを脱いで裸になるんだよ！")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "そ、そんなのイヤァ‥‥‥お父様におこられちゃうもン‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "いちいち癇にさわる娘だね。お父様が何だってんだ、何なら一緒に嬲ってやってもいいんだ！")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "こ、こわいわ、そんな目でみないで‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしのロッドの責めで口を割らなかった奴は、今までに誰もいない、なのにお前は脅えるばかりで音をあげようとはしない。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そんな女にはね、特別の責苦を与えなきゃいけないんだよ。Ｍ女用の特別な奴を！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "さあ、服を脱ぐんだ！")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "いっ、イヤァ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 18688 3)
   (exec-mem 18688 5 1 0)
   (exec-mem 3072 0)
   (mes-jump "mes¥MD_E02.MES"))
 (seg (? (= Y 1) (= S 2))
   (sound 'se 1)
   (branch-reg
    742
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_40ba.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あッ、あぁぁン‥‥‥いたァい！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "痛いって言ってる割に、平気そうな顔してるじゃないか。わたしを騙そうったって、そうはいかないよ。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "ひどいわよォ、どうしてこんなことするの？")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 742 #t))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あッ、あぁぁン‥‥‥いたァい！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 3))
   (sound 'se 1)
   (branch-reg
    743
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_40bb.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "きゃァァァッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "可愛らしいパンティが丸見えだ。お望みなら、素っ裸になるまで続けてもいいんだよ？")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "イヤッ、そんなのイヤよォ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 743 #t))
     (/ (proc 10) (text "「Eriko」" 'br) (text "きゃァァァッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 4))
   (sound 'se 1)
   (branch-reg
    744
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_40bc.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あぁぁン、お洋服がやぶけちゃったわ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そりゃ残念なこった。その服一着買う金で、何人が飢え死にしないで済んだかって考えると、全く残念な事だね。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "そんなのしらないもん‥‥‥わたしのせいじゃないもん！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 744 #t))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あぁぁン、お洋服がやぶけちゃったわ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 5))
   (sound 'se 1)
   (branch-reg
    745
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_40bd.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "イヤァァァ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "何が嫌なもんか、全然痛そうな顔してないじゃないか。奇麗な太股だ、一度も走った事のない人間の太股ってのはそんなかね。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "どうしてこんなことするの、あなた何がたのしいのよォ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 745 #t))
     (/ (proc 10) (text "「Eriko」" 'br) (text "イヤァァァ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 6))
   (sound 'se 1)
   (branch-reg
    746
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_40be.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "ンッ、ンン〜ッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "その声は嫌がってる人間のでも、苦痛に苛まれてる人間の声でもないね。むしろ歓喜の声に聞こえるよ！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "な、なにを言ってるのか、わかんないわよォ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 746 #t))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "ンッ、ンン〜ッ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 7))
   (sound 'se 1)
   (branch-reg
    747
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_40bf.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あ、あぁぁン‥‥‥お父様にも見せたことないのにィ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "知った事じゃないね。白状しないんなら、素っ裸に剥いて身体中に醜い傷を付けてやるよ！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "な、何もしらないもん‥‥‥ほんとうだもの‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 747 #t))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あ、あぁぁン‥‥‥お父様にも見せたことないのにィ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 8))
   (sound 'se 1)
   (branch-reg
    748
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_40bg.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "な、何するのよォ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "こんなのまだ序の口さ！　あんたはこれから、死んだ方がマシって目にあわされるんだから。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "そんなのイヤよォ、なんでわたしがぁ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 748 #t))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "な、何するのよォ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 3))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Eriko」" 'br)
      (text "こ、ここはどこなの？　あなた、だれ？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "おや、もうお忘れかい。サカタ・ネオテクの社長室で説明したはずだけどね。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "お前は、ミツコやその仲間達と軍の機密を盗み出した。お前の父親は、自分の会社の名前が公になるのが嫌で、お前を売ったんだ。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "よくわかんない‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "つまりね、誰もお前を助けに来ちゃくれないって事。そして、わたしに酷い事をされるんだ、これからね！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "イヤァ、あなたこわい、こっちにこないで！")
      (wait)
      (text-reset 14))
     (/
      (text "「Eriko」" 'br)
      (text "イヤァ、あなたこわい、こっちにこないで！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 6))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Eriko」" 'br)
      (text "うっ、くぅッ‥‥‥どうして‥‥‥こんなひどいことするの？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "これ以上苦痛を受けるのが嫌なら、さっさと知ってる事を吐いちまうんだよ。じゃないと、もっと酷い目にあうんだから。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "さあ、どうするんだ。早く決めな！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "そ、そんなこと言われてもォ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "本当は、お前はマゾ女なんだろう。叩かれ、嬲られるのが大好きなんじゃないのか？")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "よ、よくわかんない‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ああそうかい。それじゃ、よくわかるまで嬲り続けてやる！")
      (wait)
      (text-reset 14))
     (/
      (text "「Eriko」" 'br)
      (text "うっ、くぅッ‥‥‥どうして‥‥‥こんなひどいことするの？")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 7))
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "さあ、そのボロを脱いで裸になるんだよ！")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "そ、そんなのイヤァ‥‥‥お父様におこられちゃうもン‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "いちいち癇にさわる娘だね。お父様が何だってんだ、何なら一緒に嬲ってやってもいいんだ！")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "こ、こわいわ、そんな目でみないで‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしのロッドの責めで口を割らなかった奴は、今までに誰もいない、なのにお前は脅えるばかりで音をあげようとはしない。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そんな女にはね、特別の責苦を与えなきゃいけないんだよ。Ｍ女用の特別な奴を！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "さあ、服を脱ぐんだ！")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "いっ、イヤァ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 18688 3)
   (exec-mem 18688 5 1 0)
   (exec-mem 3072 0)
   (mes-jump "mes¥MD_E02.MES"))
 (seg (? (= Y 2) (= S 2))
   (sound 'se 1)
   (branch-reg
    742
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_40ba.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "ンッ、くぅッ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "何で避けようとしないんだ？　苦痛を味わいたくないんなら、鞭をかわせばいい。本当は鞭で打たれたいんじゃないのかい！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "そ、そんなことないもん！　わたしわるくないもん‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 742 #t))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "ンッ、くぅッ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 3))
   (sound 'se 1)
   (branch-reg
    743
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_40bb.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "み、見ちゃダメぇ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "可愛いパンティはいてるじゃない。待ってな、そのパンティもすぐに脱がせてやるから！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "ぬ、ぬがないもん、そんなのイヤだもの！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 743 #t))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "み、見ちゃダメぇ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 4))
   (sound 'se 1)
   (branch-reg
    744
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_40bc.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あふッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "何だいその声は。本当は鞭を食らって悦んでるんじゃないのかい？嘘をついてもすぐにばれるんだよ。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 744 #t))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あふッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 5))
   (sound 'se 1)
   (branch-reg
    745
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_40bd.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あ、あぁぁ〜ン‥‥‥見えちゃうぅ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そんな事ぐらいで恥ずかしがってどうする。お前はこれから全部見られちまうんだ。オッパイも＊＊＊も全部ね！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "もうやめてよォ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 745 #t))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あ、あぁぁ〜ン‥‥‥見えちゃうぅ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 6))
   (sound 'se 1)
   (branch-reg
    746
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_40be.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "んくッ！　そ、そこはダメなのォ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "どうして駄目なんだ。オッパイを鞭で打たれると気持ちいいからなのか？")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "しらない‥‥‥そんなのしらないもン‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 746 #t))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "んくッ！　そ、そこはダメなのォ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 7))
   (sound 'se 1)
   (branch-reg
    747
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_40bf.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あ、あぁぁン‥‥‥何するのよォ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "わたしが何をしようが、それを止める事は出来ないんだよっ！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "そんなァ、どうしてなの‥‥‥あなたキライよッ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 747 #t))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あ、あぁぁン‥‥‥何するのよォ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 8))
   (sound 'se 1)
   (branch-reg
    748
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_40bg.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あッ、あぶない‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あんたみたいな馬鹿女でも、何が危ないかの分別はあるらしいな！可愛い顔を台無しにされると思ったか？")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "キライよォ、どっかいってよッ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 748 #t))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あッ、あぶない‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11)))