(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (mes-load? "mes¥md_e3pl1.mec" 4096)
  (loop
   (set-var S 0)
   (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
   (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 10) (= 991 #f) (= 1020 #f) (= Q 10) (= 988 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name9.gpc,GPC")
   (image-mem 1 0 9 208)
   (proc 1)
   (set-var Q 10))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 10) (= 991 #t) (= 1020 #f) (= Q 10) (= 988 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name9.gpc,GPC")
   (image-mem 1 0 52 208)
   (proc 1)
   (set-var Q 10))
 (seg (? (= Z 2) (= Z 3) (= Z 10) (= 991 #f) (= 1020 #f) (>= Q 1) (= 988 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= Z 10) (= 991 #t) (= 1020 #f) (>= Q 1) (= 988 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1) (= 988 #f))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1) (= 988 #f))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (>= Z 1)) (mes-load? 4096))
 (seg (? (= Y 1) (= S 1) (<= H 10))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 18)
      (text "い、いたいの好き‥‥‥もっといたくしてぇ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "なんて女だ、これじゃ拷問する意味がないね。もう止めちまうか。これじゃわたしが馬鹿みたいだし。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "あ、あぁ〜ン、ダメぇ！　そんなのイヤなのォ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "いたくしてくれたら、なんでも言うからァ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "本当だな？　わたしがお前を苛めてやったら、知っている事を全部話すんだな！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "は、はなしますぅ、はなしますからァ‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (proc 18)
      (text "いたくしてくれたら、なんでも言うからァ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "本当だな？　わたしがお前を苛めてやったら、知っている事を全部話すんだな！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "はなしますぅ、何でもはなしますぅ！")
      (wait)
      (text-reset 14))
     (/ (proc 18) (text "い、いたいの好き‥‥‥もっといたくしてぇ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 16))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 18)
      (text "くふぅ、くふぅっ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "もう満足したろう。これ以上続けたら死んじまうぞ。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "まだっ、まだなのッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "とんでもない我がまま娘だな。そんなに死にたいのかい！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "ふぅ〜ん、しんじゃってもいいのォ‥‥‥")
      (wait)
      (text-reset 14))
     (/ (proc 18) (text "くふぅ、くふぅっ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 17) (= 739 #f))
   (proc 10)
   (proc 18)
   (text "くふぅ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "さあ、知ってる事を言うんだ。お前はどうしてミツコの仲間になったんだ？")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "ミツコちゃんと、プリスにやれって言われたの‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "ミツコとお前が友達なのは、知ってたが。プリスってのは何処の誰なんだ。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "プリスは、ミツコちゃんのともだち。こうあんぶっていうとこでお仕事してるの‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "公安部だって？　プリスってのは公安の人間なのか！")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "こ、こわいよォ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "ちっ、面倒くさい女だね‥‥‥恐がる事ないだろう、お前はわたしの知ってる限り、一番苦痛に耐える女なんだよ？")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "プリスはぁ、秘密警察っていうトコのえらい人。ミツコちゃんのともだちで、ふたりに言われたからデータベースにアクセスしたの。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "しかし、お前みたいな馬鹿がよくハッキングなんて高度な事を出来るもんだね。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "ばかじゃないもん！　アクセスコードはお父さまのをつかったの。どこに何があるかは、さいしょからしってたから。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "何でお前がそんな事を。軍部とサカタ・ネオテクのトップ数人しか知らない機密だったのに！")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "わたし、コンピュータは詳しいんだから。マトリクスの女王って言われてるんだから！")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "マトリクスの女王？　ある意味でお前にピッタリとも言えるかも。ハッカーなんて、何処か頭のおかしい奴らだからな。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 739 #t)
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 17) (= 739 #t)) (mes-jump "mes¥md_e3_r1.mes"))
 (seg (? (= Y 1) (= S 2))
   (sound 'se 1)
   (branch-reg
    722
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42ga.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "ひッ‥‥‥そっ、そこはぁ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "ダメダメ、＊＊＊はおあずけだ。もっともこのお楽しみが終わっ" 'br)
      (text "たら二度とこんないい事は出来ないだろうけど！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "ああ、そんなぁ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 722 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ひッ‥‥‥そっ、そこはぁ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 3))
   (sound 'se 1)
   (branch-reg
    723
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gb.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "あッ、くぅぅッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "その格好で足を責められるのは、辛いだろう。わたしの許しなしに腰を床に降ろしたら、キツイお仕置きだよ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "はう〜ン、はやくおしおきしてぇ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 723 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あッ、くぅぅッ‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 4))
   (sound 'se 1)
   (branch-reg
    724
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gc.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "ふッ、ふぅ〜ン！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "痛いだろう？　柔らかいお尻の肉を叩かれるのは。足が震えているじゃないか。そんなに気持ちいいか？")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "きっ、きもちいいのォ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 724 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ふッ、ふぅ〜ン！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 5))
   (sound 'se 1)
   (branch-reg
    725
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gd.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "あっ、くッ‥‥‥くぅぅッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "さあ、どんどん＊＊＊に近づいてきたよ。どうする、＊＊＊" 'br)
      (text "を目茶苦茶にしてやろうか？")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "してぇ〜っ、＊＊＊めちゃくちゃにしてぇ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 725 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あっ、くッ‥‥‥くぅぅッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 6))
   (sound 'se 1)
   (branch-reg
    726
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42ge.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "ふぅぅぅぅン！　き、きもちいい、そこがいいのォ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "牝奴隷め。＊＊＊を苛められると、途端にいい声で鳴き始める。" 'br)
      (text "こんな玩具がひとつあってもいいもんだね。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "もっとォ、もっとオモチャにしてぇ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 726 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 18)
      (text "ふぅぅぅぅン！　き、きもちいい、そこがいいのォ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 7))
   (sound 'se 1)
   (branch-reg
    727
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gf.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "ふんッ、ふぅぅン‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "お前には筋肉って物がないのかねぇ。何処をやっても肉を叩く音しかしないじゃないか。よっぽど大切に育てられたとみえる。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "う、うう〜っ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 727 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ふんッ、ふぅぅン‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 8))
   (sound 'se 1)
   (branch-reg
    728
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gg.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "ひぃぃぃン‥‥‥そこ、いたいのォ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "白いお腹に赤い傷が付いてしまった。血がにじんでるみたいだね！なのに、お前は＊＊＊から汁を流してる。どういう事だい。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "い、いたいの好きなの‥‥‥きもちいいのォ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 728 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 18)
      (text "ひぃぃぃン‥‥‥そこ、いたいのォ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 9))
   (sound 'se 1)
   (branch-reg
    729
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gh.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "ングゥゥッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "今のは＊＊＊に近かったみたいだね。お前の大好きな＊＊＊" 'br)
      (text "とお尻の穴は苛めてやらないからな！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "そ、そんなァ‥‥‥おねがい、なんとかしてぇ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 729 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ングゥゥッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 10))
   (sound 'se 1)
   (branch-reg
    730
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gi.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "んくッ！　そ、そこじゃないのにィ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "お前みたいな馬鹿な牝奴隷には、お仕置きが必要なのさ。お前は、普通のお仕置きをしてもこたえないからね！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "そ、そんなァ‥‥‥おねがァい、はやくぅ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 730 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 18)
      (text "んくッ！　そ、そこじゃないのにィ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 11))
   (sound 'se 1)
   (branch-reg
    731
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gj.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "くうぅぅン、いやァ‥‥‥おなかはきもちよくないのォ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "良家のお嬢さんが、腰を振っておねだりするのか。その格好もなかなか魅力的じゃないか。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "はやくぅ〜ッ、おねがァい‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 731 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 18)
      (text "くうぅぅン、いやァ‥‥‥おなかはきもちよくないのォ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 12))
   (sound 'se 1)
   (branch-reg
    732
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gk.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "ひっ、いたい‥‥‥いたいのォ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "痛いってのに嬉しがってやがる。とんでもないマゾ女だね！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "あついよォ、からだがあついのっ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 732 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 18)
      (text "ひっ、いたい‥‥‥いたいのォ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 13))
   (sound 'se 1)
   (branch-reg
    733
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (nop@)
      (set-reg 733 #t)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gl.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "あくぅッ！　オッパイがきもちいいのォ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "ああそうかい、オッパイが気持ちいいのかい。それじゃオッパイが千切れるくらい強烈なのをお見舞いしてやるよっ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "お、おねがい、うんと強いのを！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 733 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 18)
      (text "あくぅッ！　オッパイがきもちいいのォ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 10))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 17)
      (text "少しは満足したか、マゾ女！　自分の小便をうまそうに飲んで、鞭打たれてヒイヒイ言ってるお前は、本物のマゾ女だよ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "うっ、うう〜ッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "死ぬほど苛めてやる。止めてくれって言っても、止めてやらないから覚悟するんだね！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "はっ、はやくぅ〜ッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "ちっ、苛めてやるって言ってるのに、悦んでるのか。どうしようもない奴だね。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "おねがい‥‥‥じらさないでぇ‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (proc 17)
      (text "少しは満足したか、マゾ女！　自分の小便をうまそうに飲んで、鞭打たれてヒイヒイ言ってるお前は、本物のマゾ女だよ！")
      (wait)
      (text-reset 14))
     (/ (proc 18) (text "ふぅ〜ン、もっといたくしてぇ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 16))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 18)
      (text "い、いたいの好き‥‥‥もっといたくしてぇ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "なんて女だ、これじゃ拷問する意味がないね。もう止めちまうか。これじゃわたしが馬鹿みたいだし。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "あ、あぁ〜ン、ダメぇ！　そんなのイヤなのォ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "いたくしてくれたら、なんでも言うからァ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "本当だな？　わたしがお前を苛めてやったら、知っている事を全部話すんだな！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "は、はなしますぅ、はなしますからァ‥‥‥")
      (wait)
      (text-reset 14))
     (/ (proc 18) (text "い、いたいの好き‥‥‥もっといたくしてぇ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 17) (= 739 #f))
   (proc 10)
   (proc 18)
   (text "くふぅ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "さあ、知ってる事を言うんだ。お前はどうしてミツコの仲間になったんだ？")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "ミツコちゃんと、プリスにやれって言われたの‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "ミツコとお前が友達なのは、知ってたが。プリスってのは何処の誰なんだ。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "プリスは、ミツコちゃんのともだち。こうあんぶっていうとこでお仕事してるの‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "公安部だって？　プリスってのは公安の人間なのか！")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "こ、こわいよォ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "ちっ、面倒くさい女だね‥‥‥恐がる事ないだろう、お前はわたしの知ってる限り、一番苦痛に耐える女なんだよ？")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "プリスはぁ、秘密警察っていうトコのえらい人。ミツコちゃんのともだちで、ふたりに言われたからデータベースにアクセスしたの。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "しかし、お前みたいな馬鹿がよくハッキングなんて高度な事を出来るもんだね。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "ばかじゃないもん！　アクセスコードはお父さまのをつかったの。どこに何があるかは、さいしょからしってたから。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "何でお前がそんな事を。軍部とサカタ・ネオテクのトップ数人しか知らない機密だったのに！")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "わたし、コンピュータは詳しいんだから。マトリクスの女王って言われてるんだから！")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "マトリクスの女王？　ある意味でお前にピッタリとも言えるかも。ハッカーなんて、何処か頭のおかしい奴らだからな。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 739 #t)
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 17) (= 739 #t)) (mes-jump "mes¥md_e3_r2.mes"))
 (seg (? (= Y 2) (= S 2))
   (sound 'se 1)
   (branch-reg
    722
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42ga.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "イヤッ、そこじゃないのにィ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "呆れた牝犬だね、自分から＊＊＊を鞭で打ってくれって言うの？" 'br)
      (text "そんなマゾ女は今までに見た事もないね！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "おねがぁい、＊＊＊いたくしてぇ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 722 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "イヤッ、そこじゃないのにィ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 3))
   (sound 'se 1)
   (branch-reg
    723
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gb.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "あうぅッ‥‥‥い、いたいッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "痛くて気持ちがいいんだろう？　お前みたいな変態のマゾは、こうされるのが好きで仕方ないんだ。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "は、はい‥‥‥そうです、わたしはマゾ女ですぅ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 723 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あうぅッ‥‥‥い、いたいッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 4))
   (sound 'se 1)
   (branch-reg
    724
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gc.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "あぁぁぁン、もっと右のほうなのッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "お前には何処だろうと同じ事だ。＊＊＊がベトベトじゃないか！" 'br)
      (text "幼女みたいな＊＊＊のくせに、一人前に感じるなんてね。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "んふっ、こんなの初めてぇ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 724 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 18)
      (text "あぁぁぁン、もっと右のほうなのッ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 5))
   (sound 'se 1)
   (branch-reg
    725
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gd.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "んくぅ、んんんッ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "なんて姿だ。汚辱まみれになって、理性も羞恥心もありゃしない。これが日本を代表するザイバツの娘だなんて、誰が信じる？")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "わ、わかんない‥‥‥なに言ってるのかわかんないよォ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 725 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "んくぅ、んんんッ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 6))
   (sound 'se 1)
   (branch-reg
    726
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42ge.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "はッ、はァァァァン‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "こいつ、イッちまったね？　ご主人様の許可もなく気を遣るなんて許されると思ってるのか。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "ハァ、ハァ、ハァ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 726 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "はッ、はァァァァン‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 7))
   (sound 'se 1)
   (branch-reg
    727
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gf.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "くぅぅンッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "何処を打っても同じように感じやがる。お前は変態のマゾ奴隷だ。そうだな？　自分の口で言ってみろ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "は、はァい‥‥‥わたしは‥‥‥ンッ、へんたいのマゾですぅ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 727 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "くぅぅンッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 8))
   (sound 'se 1)
   (branch-reg
    728
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gg.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "ふ、ふぅぅン‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "馬鹿みたいな格好で、腰を動かしてやがる！　お嬢さんがそんな卑猥な姿をしてていいのかね？")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "だ、だって‥‥‥からだが勝手にィ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 728 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ふ、ふぅぅン‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 9))
   (sound 'se 1)
   (branch-reg
    729
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gh.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "んんッ！　そ、そこはダメぇ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "可愛い靴まで、汚い汁がベッタリじゃないか。お前の＊＊＊は、" 'br)
      (text "どれだけ汁を溜めてるんだい！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "も、もうベトベトなの‥‥‥こんなのはじめてなのォ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 729 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 18)
      (text "も、もうベトベトなの‥‥‥こんなのはじめてなのォ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 10))
   (sound 'se 1)
   (branch-reg
    730
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gi.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "あうッ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "痛くて気持ちいいだろう。気持ちよくして下さったご主人様に牝奴隷らしくお礼を言ってごらん！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "あ、ありがとう‥‥‥ございまッ、ンンッ‥‥‥ございますっ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 730 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あうッ‥‥‥‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 11))
   (sound 'se 1)
   (branch-reg
    731
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gj.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "イヤァ‥‥‥おなかはイヤァァァ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "嫌じゃないんだよ！　処女のくせに腰振って悦んでやがるくせに！お前みたいな馬鹿な牝奴隷は、焦らしぬいてやるからな。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "もうしんじゃうぅ、はやくいじめてほしいのにィ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 731 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "イヤァ‥‥‥おなかはイヤァァァ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 12))
   (sound 'se 1)
   (branch-reg
    732
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gk.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "あふッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "足がガクガクしてるじゃないか。ご主人様の命令なしに床に腰を降ろしたら、もう苛めてやらないからな。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "ああ、そんなァ！　おねがいよォ、はやくゥ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 732 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あふッ‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 13))
   (sound 'se 1)
   (branch-reg
    733
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (nop@)
      (set-reg 733 #t)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_42gl.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "くふぅ‥‥‥き、きもちいい！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "お前はザイバツの令嬢より、最低の淫売の方が性にあってるみたいだねぇ。こんなマゾ奴隷は滅多にいないよ。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "あふっ、あふぅ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 733 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "くふぅ‥‥‥き、きもちいい！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 9) (= S 2))
   (branch-reg
    734
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_42ba.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 18)
      (text "いッ、いたァァい！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "痛いに決まってんだろう、乳首に穴をあけたんだからね！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "あふぅ〜ッ‥‥‥き、きもちいいのォ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "くっくっくっ、いくらマゾ女でもこれはキツイだろうね。")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 734 #t))
     (/
      (proc 10)
      (proc 18)
      (text "いッ、いたァァい！　さわっちゃダメェ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 9) (= S 3))
   (branch-reg
    735
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_42bb.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 18)
      (text "アッ！　く、くぅぅぅッ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "ヘソのピアスは牝奴隷の証しだ。ご主人様に忠誠をつくすって誓いの証明なんだよ。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "は、はぁぁぁっ！　何でもしますぅ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "こんなのはまだまださ。いつかお前のその肌に、奴隷の焼き印を押してやるからね。")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 735 #t))
     (/ (proc 10) (proc 18) (text "アッ！　く、くぅぅぅッ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 9) (= S 4))
   (branch-reg
    736
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_42bc.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 18)
      (text "はっ、はうぅぅぅ〜ッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "動くんじゃないよ、針が折れて取りかえしのつかない事になっちまうかもしれないからね。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "ち、注射はキライよォ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "これは注射じゃない、お前を嬲ってるのさ。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "オ、オシッコが‥‥‥もれちゃいそうっ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 736 #t))
     (/ (proc 10) (proc 18) (text "ち、注射はキライよォ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 9) (= S 5))
   (branch-reg
    737
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (branch-reg
       738
       (</>
        (/ (image-file "gpc¥a1_42bd.gpc") (image-mem 1 0))
        (/ (image-file "gpc¥a1_42bf.gpc") (image-mem 1 0))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "んぐッ！　くぅぅぅぅ〜ン！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "くくッ、＊＊＊に輪っかをはめた女なんて、そうはいない。本物" 'br)
      (text "の牝奴隷くらいのもんさ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "あ、あついよォ‥‥‥＊＊＊があついのォ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "陰唇から血がダラダラ出てる。麻酔もかけてないんだ、そりゃ熱いだろうさ。焼けるように痛いだろう。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "く、くるっちゃうゥ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 737 #t))
     (/
      (proc 10)
      (proc 18)
      (text "さ、さわっちゃダメなのォ！　切れちゃうよォ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 9) (= S 6))
   (branch-reg
    738
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (branch-reg
       737
       (</>
        (/ (image-file "gpc¥a1_42be.gpc") (image-mem 1 0))
        (/ (image-file "gpc¥a1_42bf.gpc") (image-mem 1 0))))
      (proc 12)
      (proc 10)
      (proc 18)
      (text "ヒッ、ヒィィィッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "この輪っかは、ご主人様の命令があるまで外すんじゃないよ。鍵をかけてオナニーさえ出来なくしてやるんだから。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "い、いたッ‥‥‥＊＊＊がァ‥‥‥しんじゃうぅぅッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "いつかこの＊＊＊を目茶苦茶にしてやる。クリトリスの皮を切り" 'br)
      (text "取って、入り口も糸で縫い付けて‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "処女でありながら、ニンフォマニアになるんだ。気が狂いそうになるだろうね。そんなのも面白いよ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 738 #t))
     (/ (proc 10) (proc 18) (text "はッ、ふぅぅッ‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg*))