(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (nop@)
   (set-reg 980 #t)
   (set-reg 981 #t)
   (set-reg 982 #f)
   (set-reg 983 #f)
   (set-reg 984 #f)
   (set-reg 985 #f)
   (set-reg 986 #f)
   (set-reg 987 #f)
   (set-reg 988 #f)
   (set-reg 989 #f)
   (set-reg 990 #f)
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_41c.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (if (</>
        (//
         (? (= P 10))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_10.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 10))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_10v.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 10)))))
        (// (nop@))))
   (exec-mem 256 "E")
   (load-mem "clm¥A1_41.clm" 32768)
   (load-mem "clm¥icon.clm" 20480)
   (mes-load? "mes¥icon_cl.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥icon_c2.mec" 0)
   (mes-load? 0)
   (text-frame 10 312 70 370)
   (exec-mem 256 "A 0")
   (proc 12)
   (define-proc 19
     (<>
      (if (</>
           (//
            (? (>= H 7) (= 983 #f))
            (nop@)
            (set-reg 983 #t)
            (mes-load? "mes¥icon_cl.mec" 0)
            (mes-load? 0)
            (mes-load? "mes¥icon_c2.mec" 0)
            (mes-load? 0))
           (// (nop@))))))
   (define-proc 15
     (<>
      (if (</>
           (//
            (? (>= H 8) (= 717 #f))
            (image-file "gpc¥a1_41dl.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 717 #t))
           (// (nop@))))
      (proc 12)))
   (proc 10)
   (set-var H 0)
   (text "「Eriko」" 'br)
   (text "うっ、うぅ〜ッ！")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "なによ‥‥‥なによォ、これぇ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "縄が食い込んで痛いだろう？　いくら痛いのが好きなお前でもかなり辛いだろう。")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "あ、足が取れちゃいそうっ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "さあ、楽しい拷問の時間だ。")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "痛い、痛ぁ〜いッ！　おろしてぇ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "真性Ｍ女のあんたでも音をあげる、とびきりキツイ奴をやってやるからね！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (exec-mem 256 "P 5 6 0")
   (loop
    (set-var S 0)
    (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
    (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 5) (= 991 #f) (= 1020 #f) (= Q 5) (= 983 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name4.gpc,GPC")
   (image-mem 1 0 9 88)
   (proc 1)
   (set-var Q 5))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 5) (= 991 #t) (= 1020 #f) (= Q 5) (= 983 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name4.gpc,GPC")
   (image-mem 1 0 52 88)
   (proc 1)
   (set-var Q 5))
 (seg (? (= Z 2) (= Z 3) (= Z 5) (= 991 #f) (= 1020 #f) (>= Q 1) (= 983 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= Z 5) (= 991 #t) (= 1020 #f) (>= Q 1) (= 983 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1) (= 983 #f))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1) (= 983 #f))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (= Z 1) (= 991 #f))
   (proc 0)
   (exec-mem 256 "P 5 71 0")
   (nop@)
   (set-reg 991 #t)
   (exec-mem 256 "P 8 6 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 71 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 71 40))
        (//
         (? (= Y 4))
         (if (</>
              (//
               (? (= 983 #t))
               (exec-mem 9504 "C icon¥tool15.gpc,GPC")
               (image-mem 1 0 71 88))
              (//
               (? (= 983 #f))
               (exec-mem 9504 "C icon¥tool04.gpc,GPC")
               (image-mem 1 0 71 88)))))))
   (load-mem "clm¥icon2.clm" 20480)
   (proc 1))
 (seg (? (= Z 1) (= 991 #t))
   (proc 0)
   (exec-mem 256 "P 5 6 0")
   (nop@)
   (set-reg 991 #f)
   (exec-mem 256 "P 9 71 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 6 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 6 40))
        (//
         (? (= Y 4))
         (if (</>
              (//
               (? (= 983 #t))
               (exec-mem 9504 "C icon¥tool15.gpc,GPC")
               (image-mem 1 0 6 88))
              (//
               (? (= 983 #f))
               (exec-mem 9504 "C icon¥tool04.gpc,GPC")
               (image-mem 1 0 6 88)))))))
   (load-mem "clm¥icon.clm" 20480)
   (proc 1))
 (seg (? (= Z 2) (= 991 #f))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 6 40)
   (if (</>
        (//
         (? (= 983 #t))
         (exec-mem 9504 "C icon¥tool26.gpc,GPC")
         (image-mem 1 0 6 88))
        (// (nop@))))
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #f))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 6 16)
   (if (</>
        (//
         (? (= 983 #t))
         (exec-mem 9504 "C icon¥tool26.gpc,GPC")
         (image-mem 1 0 6 88))
        (// (nop@))))
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Z 2) (= 991 #t))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 71 40)
   (if (</>
        (//
         (? (= 983 #t))
         (exec-mem 9504 "C icon¥tool26.gpc,GPC")
         (image-mem 1 0 71 88))
        (// (nop@))))
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #t))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 71 16)
   (if (</>
        (//
         (? (= 983 #t))
         (exec-mem 9504 "C icon¥tool26.gpc,GPC")
         (image-mem 1 0 71 88))
        (// (nop@))))
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Z 5) (= 991 #f) (= 983 #t))
   (nop@)
   (set-var Y 4)
   (proc 0)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 9504 "C icon¥tool15.gpc,GPC")
   (image-mem 1 0 6 88)
   (exec-mem 18688 5 7 1)
   (proc 1)
   (exec-mem 18688 2 5))
 (seg (? (= Z 5) (= 991 #t) (= 983 #t))
   (nop@)
   (set-var Y 4)
   (proc 0)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 9504 "C icon¥tool15.gpc,GPC")
   (image-mem 1 0 71 88)
   (exec-mem 18688 5 7 1)
   (proc 1)
   (exec-mem 18688 2 5))
 (seg (? (= Y 1) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Eriko」" 'br)
      (text "んふう、なんだか熱いのォ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "何て女なんだろうねぇ、サカタ・ネオテクの社長令嬢がマゾ女だったとは。思いもよらなかった。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "マ、マゾって‥‥‥なぁに？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あんたみたいな変態女の事だよ！　苛められて＊＊＊を熱くして" 'br)
      (text "る女の事さ。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "わたし、マゾ女なのかなぁ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/ (text "「Eriko」" 'br) (text "んふう、なんだか熱いのォ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 8))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Eriko」" 'br)
      (text "なんだか気持ちいいのぉ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そりゃよかった。気持ちよくしてくれたわたしに、お礼をするつもりはないのか？")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "な、なにをすればいいのォ？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "何故あんたが、軍の機密を盗む仲間になったのか教えろ。いくら友達の頼みでも簡単に犯罪に荷担する訳はない。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ミツコ達に協力する事を決めた理由は何だ？")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "そ、それはぁ〜っ。言えない！　みんなにおこられるもん！")
      (wait)
      (text-reset 14))
     (/ (text "「Eriko」" 'br) (text "なんだか気持ちいいのぉ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 11))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Eriko」" 'br)
      (text "うっ、うぅ〜ン‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "可愛い顔して、＊＊＊の感度は一人前とは。しかも、真性のＭ女" 'br)
      (text "ときたもんだ！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "あぁん、やめちゃだめぇ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ふざけるんじゃないよ。お前を悦ばせる為にやってる訳じゃない！わたしはお前のご主人様だ。これからはご主人様って呼ぶんだよ。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "は、はぁ‥‥‥ご、ご主人様ぁ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "お前は本物のＭ女だからね、苦痛に負けて口を割る事はないだろ？そのかわり、本物の快感を味あわせてやる。")
      (wait)
      (text-reset 14))
     (/ (text "「Eriko」" 'br) (text "あぁん、やめちゃだめぇ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 12)) (mes-jump "mes¥md_e2_r1.mes"))
 (seg (? (= Y 1) (= S 2))
   (sound 'se 1)
   (branch-reg
    705
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41da.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あん！　そ、そこは痛いの‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "張りのある肌だ。混血なのがいいのかねぇ、白人女とも違うし東洋人のとも違う。なかなか奇麗な肌じゃないか。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "熱いッ！　そこ、熱いのォ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 705 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あん！　そ、そこは痛いの‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 3))
   (sound 'se 1)
   (branch-reg
    706
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41db.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "ひぃぃぃン！　お、お尻がァ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "くくくっ、お尻の穴が台無しになっちまうって？　わたしの目の前で汚いクソをぶち撒けるんじゃないよ！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "イヤぁ、そんなこと‥‥‥そんなこと、しないもン！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 706 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "ひぃぃぃン！　お、お尻がァ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 4))
   (sound 'se 1)
   (branch-reg
    707
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41dc.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "ふっ、ふぅぅぅん！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "何処を苛めても悦ぶ。これじゃ苛めようがないねぇ、ここまで完璧なＭ女は初めてだ。親父にでも調教されたか？")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "はぁ、はぁ、はぁ、はぁ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 707 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "ふっ、ふぅぅぅん！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 5))
   (sound 'se 1)
   (branch-reg
    708
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41dd.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "そっ、そこォ！　すごく気持ちいいのォ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "＊＊＊を苛められて気持ちいいのか！　マゾもそこまでいけば立" 'br)
      (text "派だよ、すごいね。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "＊＊＊気持ちいいの、もっとやってぇ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 708 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "そっ、そこォ！　すごく気持ちいいのォ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 6))
   (sound 'se 1)
   (branch-reg
    709
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41de.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "いっ、痛ぁい‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "痛くされたくないんなら、早く知ってる事を吐いてしまいな。お前が何をしたかは知ってるんだよ！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "い、痛いのがいいの、もっと痛くしてぇ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 709 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "いっ、痛ぁい‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 7))
   (sound 'se 1)
   (branch-reg
    710
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41df.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "くっ、くふぅ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "もうちょっと力を入れれば、内臓破裂だ。死んじまうんだよ！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "それでもいいのォ、もっと痛くしてぇ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 710 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "くっ、くふぅ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 8))
   (sound 'se 1)
   (branch-reg
    711
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41dg.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あッ、くぅぅッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "盗んだ軍の情報を、何処に隠した！　はやく白状しないと、お前を殺してしまうぞ！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "死んじゃってもいいの、こんなのはじめてなのォ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 711 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あッ、くぅぅッ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 9))
   (sound 'se 1)
   (branch-reg
    712
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41dh.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "ひぃぃッ！　オッパイがじんじんするぅ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "本当の事を言わないと、オッパイを潰してしまうぞ！　お前はどうしてミツコと一緒に軍の機密を盗んだ。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "し、しらないのォ〜もっとやってぇ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 712 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "ひぃぃッ！　オッパイがじんじんするぅ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 10))
   (sound 'se 1)
   (branch-reg
    713
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41di.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "ヒィィィィン！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "オッパイ苛められて気持ちいいか？　気持ちよくして下さったご主人様にお礼を言いなっ！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "ありがとうございますぅ〜もっとやってくださいっ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 713 #t)
      (proc 19))
     (/ (proc 10) (text "「Eriko」" 'br) (text "ヒィィィィン！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 11))
   (sound 'se 1)
   (branch-reg
    714
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41dj.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あくぅ‥‥‥も、もっとべつのとこもやってぇ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "全然こたえてないみたいだな、さすがＭ女だ。セックスさえした事ないくせに、これじゃ普通の女にはなれないね！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "うっ、うう‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 714 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あくぅ‥‥‥も、もっとべつのとこもやってぇ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 12))
   (sound 'se 1)
   (branch-reg
    715
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_41dk.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (branch-reg
       991
       (</>
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 6 16))
        (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 71 16))))
      (proc 10)
      (text "「Eriko」" 'br)
      (text "くふッ！　も、もっとォ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "盗んだ軍の機密を、何処に隠した！　白状しな！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "そ、そんなのどうでもいいの、もっとやってぇ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 715 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "くふッ！　も、もっとォ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Eriko」" 'br)
      (text "なんだか気持ちいいのぉ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そりゃよかった。気持ちよくしてくれたわたしに、お礼をするつもりはないのか？")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "な、なにをすればいいのォ？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "何故あんたが、軍の機密を盗む仲間になったのか教えろ。いくら友達の頼みでも簡単に犯罪に荷担する訳はない。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ミツコ達に協力する事を決めた理由は何だ？")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "そ、それはぁ〜っ。言えない！　みんなにおこられるもん！")
      (wait)
      (text-reset 14))
     (/ (text "「Eriko」" 'br) (text "なんだか気持ちいいのぉ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 8))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "お前は本当に淫乱な娘だね。なんだい、その＊＊＊の濡れ方は！" 'br)
      (text "まるで小便を漏らしたみたいにビチャビチャじゃないか。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "こ、こんなの‥‥‥はじめてなのぉ、なんかヘンなのっ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "自分でオナニーするより気持ちいいか？　それとも、見かけによらず、セックスの経験アリかな？")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "なにそれ‥‥‥しらないわ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そりゃいい。初めてでこれだけ感じるなんて、お前には素質があるみたいだね！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "うう〜っ！　は、はやくっ、もっとやってぇ！")
      (wait)
      (text-reset 14))
     (/
      (text "「Eriko」" 'br)
      (text "こ、こんなの‥‥‥はじめてなのぉ、なんかヘンなのっ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 11))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Eriko」" 'br)
      (text "うっ、うぅ〜ン‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "可愛い顔して、＊＊＊の感度は一人前とは。しかも、真性のＭ女" 'br)
      (text "ときたもんだ！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "あぁん、やめちゃだめぇ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ふざけるんじゃないよ。お前を悦ばせる為にやってる訳じゃない！わたしはお前のご主人様だ。これからはご主人様って呼ぶんだよ。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "は、はぁ‥‥‥ご、ご主人様ぁ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "お前は本物のＭ女だからね、苦痛に負けて口を割る事はないだろ？そのかわり、本物の快感を味あわせてやる。")
      (wait)
      (text-reset 14))
     (/ (text "「Eriko」" 'br) (text "あぁん、やめちゃだめぇ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 12)) (mes-jump "mes¥md_e2_r2.mes"))
 (seg (? (= Y 2) (= S 2))
   (sound 'se 1)
   (branch-reg
    705
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41da.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あふ、あふぅ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "お前こそ、本当の牝豚だね。ブウブウ鼻を鳴らして、鞭のご馳走をもらおうと躍起になってる！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "しんじゃいそうなのォ、こんなの‥‥‥すごいの！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 705 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あふ、あふぅ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 3))
   (sound 'se 1)
   (branch-reg
    706
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41db.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "はうッ！　ちょっと左の‥‥‥＊＊＊にやってぇ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "処女のくせに、＊＊＊が何だって？　馬鹿のくせにそんな事だけ" 'br)
      (text "は詳しいんだね！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "ばかじゃないもん‥‥‥違うもんっ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 706 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "はうッ！　ちょっと左の‥‥‥＊＊＊にやってぇ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 4))
   (sound 'se 1)
   (branch-reg
    707
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41dc.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あふッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "お前はどうして軍の機密を盗んだ。サカタ・ネオテクの社長の娘がどうしてそんな事をしなきゃならなかったんだ！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "そ、それを言ったらやめちゃうもん‥‥‥だから言わないのッ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 707 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あふッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 5))
   (sound 'se 1)
   (branch-reg
    708
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41dd.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "はっ、はうッッ！　＊＊＊がいいのォ！！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "とんだ淫乱娘だ。そんな事だから、親父に愛想をつかされるんだ。そりゃそうさ、Ｍ女の娘なんて欲しくないからね！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "い、いやァ‥‥‥そんなこと言わないで‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 708 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "はっ、はうッッ！　＊＊＊がいいのォ！！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 6))
   (sound 'se 1)
   (branch-reg
    709
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41de.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "はうぅ〜ン！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "この淫売女！　お尻の穴を苛められて喘ぎ声をあげるのか。あきれた変態だね。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "へんたいでいいのぉ‥‥‥もっといじめてぇ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 709 #t)
      (proc 19))
     (/ (proc 10) (text "「Eriko」" 'br) (text "はうぅ〜ン！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 7))
   (sound 'se 1)
   (branch-reg
    710
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41df.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "くぅぅぅッ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "盗んだ軍の情報を、何処に隠した！　はやく白状しないと、お前を殺してしまうぞ！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "し、しらない‥‥‥なにもしらないのォ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 710 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "くぅぅぅッ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 8))
   (sound 'se 1)
   (branch-reg
    711
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41dg.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あふっ、あふぅ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ここは気持ちよくないか？　何処がいいのか言ってみな！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "＊＊＊‥‥‥とお尻がきもちいいの‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 711 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あふっ、あふぅ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 9))
   (sound 'se 1)
   (branch-reg
    712
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41dh.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "んくッ！　オッパイがぁ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "死ぬほど痛いだろう。そんなに固くて小さなオッパイじゃね！")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "しんじゃうぅ‥‥‥わたし、しんじゃうぅ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 712 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "んくッ！　オッパイがぁ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 10))
   (sound 'se 1)
   (branch-reg
    713
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41di.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "くぅぅぅン‥‥‥ふぅぅぅン！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "本当の事を言わないと、オッパイを潰してしまうぞ！　お前はどうしてミツコと一緒に軍の機密を盗んだ。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "し、しらないのォ〜もっとやってぇ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 713 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "くぅぅぅン‥‥‥ふぅぅぅン！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 11))
   (sound 'se 1)
   (branch-reg
    714
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_41dj.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Eriko」" 'br)
      (text "はンッ！　ご、ご主人様ァ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "うるさい！　なつくんじゃないよ。お前みたいな真性Ｍ女なんか、病院に入れて一生外に出られないようにしてやる。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "ああ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 714 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "はンッ！　ご、ご主人様ァ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 12))
   (sound 'se 1)
   (branch-reg
    715
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_41dk.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (branch-reg
       991
       (</>
        (/ (exec-mem 9504 "C icon¥tool13.gpc,GPC") (image-mem 1 0 6 40))
        (/ (exec-mem 9504 "C icon¥tool13.gpc,GPC") (image-mem 1 0 71 40))))
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あふッ、そこじゃないのォ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "欲求不満で気が狂いそうか、さすがマゾは違うねぇ。")
      (wait)
      (text-reset 14)
      (text "「Eriko」" 'br)
      (text "し、しんじゃうぅ〜ッ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 715 #t)
      (proc 19))
     (/
      (proc 10)
      (text "「Eriko」" 'br)
      (text "あふッ、そこじゃないのォ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 4) (= S 1) (= 718 #f))
   (proc 10)
   (text "「Eriko」" 'br)
   (text "うぅ〜ッ、いやぁ‥‥‥お医者さんみたい！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そうさ、わたしは医者だ。お前の体を診察してやるのさ。")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "お医者さん、キライ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "暴れるんじゃない！　そんな事をしても無駄さ、お前はわたしから逃れる事は出来ない。")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 718 #t)
   (proc 11))
 (seg (? (= Y 4) (= S 1) (= 718 #t))
   (proc 10)
   (text "「Eriko」" 'br)
   (text "うぅ〜ッ、いやぁ‥‥‥お医者さんみたい！")
   (wait)
   (text-reset 14)
   (proc 11))
 (seg (? (= Y 4) (>= S 9) (<= S 10) (= 719 #f))
   (proc 10)
   (text "「Eriko」" 'br)
   (text "つ、つめたいッ‥‥‥それイヤ、怖いのッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "お前は怖い時に乳首を固くするのか？　これがどんな効果をもたらしてくれるのか、楽しみで仕方ないんだろう！")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "むずかしくて、よくわかんない‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "これは怖い物じゃないって言いたいのさ。それどころか、どうやったらお前が気持ちよくなるか、調べる便利な機械なのさ。")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 719 #t)
   (proc 11))
 (seg (? (= Y 4) (>= S 9) (<= S 10) (= 719 #t))
   (proc 10)
   (text "「Eriko」" 'br)
   (text "つ、つめたいッ‥‥‥それイヤ、怖いのッ！")
   (wait)
   (text-reset 14)
   (proc 11))
 (seg (? (= Y 4) (= S 13) (= 720 #f))
   (proc 10)
   (text "「Eriko」" 'br)
   (text "アッ‥‥‥ンッ！")
   (wait)
   (text-reset 14)
   (proc 11)
   (proc 0)
   (image-file "gpc¥a1_41ca.gpc")
   (image-mem 1 0)
   (proc 12)
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "こいつは鋭いから、処女の＊＊＊でも傷つけずに入る。本当に奥" 'br)
   (text "の方までね。")
   (wait)
   (text-reset 14)
   (text "「Eriko」" 'br)
   (text "いっ、いやぁ‥‥‥つめたいのッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "中の奥まで、外と同じピンク色だ。こいつを何とかしてしまうのは勿体ないくらいさ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "わたしは、＊＊＊に指一本触れず、お前をいかせる事も出来る。" 'br)
   (text "お前には特別なやり方をしてやろう‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (inc-var H 1)
   (nop@)
   (set-reg 720 #t)
   (proc 11))
 (seg (? (= Y 4) (= S 13) (= 720 #t))
   (proc 10)
   (text "「Eriko」" 'br)
   (text "アッ‥‥‥ンッ！")
   (wait)
   (text-reset 14)
   (proc 11)))