(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (proc 10)
  (text "「Eriko」" 'br)
  (text "はぁ、はぁ、はぁ、はぁ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "どうだ、気持ちいいか？")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "は、はいぃぃっ、気持ちいいですぅ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "よし、次は屈辱を教えてやろう。Ｍ女のお前には、それもまた心地いいはずだ。")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "な、なにを‥‥‥するんですか‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "縄を解いてやる。そして、その次は‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (proc 11)
  (proc 0)
  (exec-mem 256 "A 1")
  (text-frame 0 0 79 399)
  (text-reset 14)
  (text-frame 10 312 70 370)
  ((cmd 209) 0 5)
  (image-file "gpc¥a1_41_a.gpc")
  (image-mem 0 3)
  (image-file "gpc¥a1_41_b.gpc")
  (image-mem 0 3)
  (mes-load? "mes¥bnkcpy3.mec" 0)
  (mes-load? 0)
  ((cmd 209) 1 5)
  (exec-mem 256 "A 0")
  (exec-mem 256 "G 8 6 0 3 279")
  (exec-mem 256 "G 9 71 0 3 279")
  (proc 12)
  (proc 10)
  (text "「Kiyomi」" 'br)
  (text "その洗面器に小便するんだ。考えただけでぞくぞくするだろう？")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "オシッコ？　そんなのイヤァ‥‥‥人が見てるのにぃ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "黙れ！　ご主人様の言う事がきけないってのか。")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "だ、だってぇ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "さあ、早くやるんだよ。早く！")
  (wait)
  (text-reset 14)
  (proc 11)
  (exec-mem 3072 0)
  (proc 5)
  (image-file "gpc¥a1_41a.gpc")
  (image-mem 1 0)
  (mes-load? "mes¥bnkcpy2.mec" 4096)
  (mes-load? 4096)
  (exec-mem 29184 0 1 "gpa¥a1_41.dpb" 0)
  (exec-mem
   29184
   1
   1
   "A......A......A......A......A......A......A......A......A......A......A......A......A......A......A......A......A......A......A......A......A......A......A......A......")
  (exec-mem 256 "A 1")
  (image-file "gpc¥a1_41_0.gpc")
  (image-mem 1 0)
  (exec-mem 256 "A 0")
  (image-file "gpc¥a1_41_1.gpc")
  (image-mem 1 0)
  (exec-mem 29184 2 1 0 0)
  (exec-mem 29184 3 1)
  (exec-mem 256 "S 1")
  (exec-mem 256 "A 0")
  (proc 0)
  (image-file "gpc¥a1_41_a.gpc")
  (image-mem 0 3)
  (image-file "gpc¥a1_41_b.gpc")
  (image-mem 0 3)
  (proc 12)
  (exec-mem 256 "S 0")
  (proc 10)
  (text "「Eriko」" 'br)
  (text "うっ、うっ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "嫌がってた割に、随分たくさん出たじゃないか！　＊＊＊から小" 'br)
  (text "便が流れ出てるのを見たら、お前の親父はどうするかね。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "サカタ・ネオテクの社長だからって、冷静じゃいられないはずさ！娘の＊＊＊に口をつけて、ゴクゴク飲んじまうかもよ。")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "もういやぁ〜っ、こんなの気持ちよくないもんっ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "よし、次は自分が垂れ流した小便を飲むんだ。")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "そ、そんなのイヤァ！　きたないもん！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "そうかい、自分じゃ出来ないってぇならわたしが手を貸してやる。")
  (wait)
  (text-reset 14)
  (proc 11)
  (proc 0)
  (exec-mem 256 "A 1")
  (text-frame 0 0 79 399)
  (text-reset 14)
  (text-frame 10 312 70 370)
  ((cmd 209) 0 5)
  (image-file "gpc¥a1_41b_a.gpc")
  (image-mem 0 3)
  (image-file "gpc¥a1_41b_b.gpc")
  (image-mem 0 3)
  (mes-load? "mes¥bnkcpy3.mec" 0)
  (mes-load? 0)
  ((cmd 209) 1 5)
  (exec-mem 256 "A 0")
  (proc 12)
  (proc 10)
  (text "「Eriko」" 'br)
  (text "うっ、うう〜っ！　いやぁ、やめて‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "さっさと飲むんだよ。猫がミルクを舐めるみたいに、ぴちゃぴちゃ音を立ててやんな！")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "うぅッ‥‥‥ピチャッ、ピチャッ、ピチャッ、ピチャッ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "うまいか？　うまい訳ないよな、自分の小便だもんな！")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "ピチャッ、ピチャッ‥‥‥ごほッ、もう飲めないよォ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "遠慮せずどんどん飲りな。")
  (wait)
  (text-reset 14)
  (text "「Eriko」" 'br)
  (text "ご主人様ぁ、もうゆるしてください‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "ちっ、仕方のない女だね。それじゃもっと可愛がってやるか。")
  (wait)
  (text-reset 14)
  (proc 11)
  (exec-mem 18688 3)
  (exec-mem 18688 5 1 0)
  (exec-mem 3072 0)
  (mes-jump "mes¥MD_E03.MES")))