(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (nop@)
   (set-reg 980 #t)
   (set-reg 981 #t)
   (set-reg 982 #f)
   (set-reg 983 #f)
   (set-reg 984 #f)
   (set-reg 985 #f)
   (set-reg 986 #f)
   (set-reg 987 #f)
   (set-reg 988 #f)
   (set-reg 989 #f)
   (set-reg 990 #f)
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_52.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (if (</>
        (//
         (? (= P 10))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_10.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 10))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_10v.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 10)))))
        (// (nop@))))
   (exec-mem 256 "E")
   (load-mem "clm¥A1_52.clm" 32768)
   (load-mem "clm¥icon.clm" 20480)
   (mes-load? "mes¥icon_cl.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥icon_c2.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥md_f3pl1.mec" 4096)
   (text-frame 10 312 70 370)
   (exec-mem 256 "A 0")
   (proc 12)
   (define-proc 19
     (<>
      (if (</>
           (//
            (? (>= H 7) (= 989 #f))
            (nop@)
            (set-reg 989 #t)
            (mes-load? "mes¥icon_cl.mec" 0)
            (mes-load? 0)
            (mes-load? "mes¥icon_c2.mec" 0)
            (mes-load? 0))
           (// (nop@))))))
   (define-proc 15 (<> (text "「Kiyomi」" 'br)))
   (define-proc 16 (<> (text "「Priss」" 'br)))
   (define-proc 17 (<> (wait) (text-reset 14)))
   (proc 10)
   (set-var H 0)
   (proc 15)
   (text "どうだい、移民のお姫さま。そのポーズはお気に召したか？")
   (wait)
   (text-reset 14)
   (proc 16)
   (text "う、うぐぅっ！　")
   (wait)
   (text-reset 14)
   (proc 15)
   (text "＊＊＊どころか、尻の穴まで丸見えだ。それ以上恥ずかしい姿も" 'br)
   (text "なかなかないだろうよ。")
   (wait)
   (text-reset 14)
   (proc 15)
   (text "お前が、＊＊＊からうれし涙を流して、尻の穴をヒクつかせてる" 'br)
   (text "様子をじっくり観察してやるからね。")
   (wait)
   (text-reset 14)
   (proc 16)
   (text "うっ、ううッ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 15)
   (text "嫌がってるふりをしても駄目さ、お前が言葉で責められて感じるって事を、わたしはよく知ってるんだから。")
   (wait)
   (text-reset 14)
   (proc 15)
   (text "観念して、牝奴隷まで堕ちてしまう事だね。それも早い方がいい。そうすれば、心から楽しむ事が出来るんだから！")
   (wait)
   (text-reset 14)
   (proc 16)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (exec-mem 256 "P 5 6 0")
   (mes-jump "mes¥md_f3_ms.mes")))