(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (proc 10)
  (text "「Kiyomi」" 'br)
  (text "いくら何でも、もう観念したろう？　これ以上続けても無駄なのはわかってるんだ。それとも、ここで止められるのは嫌か？")
  (wait)
  (text-reset 14)
  (text "「Priss」" 'br)
  (text "うう、ううぅぅ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "すっかり牙を抜かれて、従順なペットみたいになっちまった。恥ずかしがる事はないよ、誰でもそうさ。")
  (wait)
  (text-reset 14)
  (text "「Priss」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "いいだろうもう少し嬲ってやる、ギャグは着けたままでね。その方が都合がいいだろう？")
  (wait)
  (text-reset 14)
  (text "「Priss」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "いい子だね。楽しませてやるよ、わたしは素直な子は大好きだよ。最初からそうしてれば苦しまずに済んだんだ。")
  (wait)
  (text-reset 14)
  (text "「Priss」" 'br)
  (text "うっ、ううッ‥‥‥ううぅぅッ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "よしよし、それじゃお前の身体を傷だらけにしてやるよ！")
  (wait)
  (text-reset 14)
  (proc 11)
  (exec-mem 18688 3)
  (exec-mem 18688 5 1 0)
  (exec-mem 3072 0)
  (mes-jump "mes¥MD_F03.MES")))