(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (loop
   (set-var S 0)
   (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
   (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 11) (= 991 #f) (= 1020 #f) (= Q 11) (= 989 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name10.gpc,GPC")
   (image-mem 1 0 9 232)
   (proc 1)
   (set-var Q 11))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 11) (= 991 #t) (= 1020 #f) (= Q 11) (= 989 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name10.gpc,GPC")
   (image-mem 1 0 52 232)
   (proc 1)
   (set-var Q 11))
 (seg (? (= Z 2) (= Z 3) (= Z 11) (= 991 #f) (= 1020 #f) (>= Q 1) (= 989 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= Z 11) (= 991 #t) (= 1020 #f) (>= Q 1) (= 989 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1) (= 989 #f))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1) (= 989 #f))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (= Z 1)) (mes-load? 4096))
 (seg (? (= Z 2)) (mes-load? 4096))
 (seg (? (= Z 3)) (mes-load? 4096))
 (seg (? (= Z 11)) (mes-load? 4096))
 (seg (? (= Y 1) (= S 1) (<= H 6))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 16)
      (text "うぐッ、うぐぅぅ‥‥‥")
      (proc 17)
      (proc 15)
      (text "そんなに焦るんじゃないよ。急がなくても、たっぷり可愛がってあげるからさ。")
      (proc 17)
      (proc 16)
      (text "うぅぅ‥‥‥‥‥‥")
      (proc 17)
      (proc 15)
      (text "心の底から卑しい牝奴隷になるのさ。嬉しいだろう？　お前はもう半分くらい、そうなりつつある‥‥‥")
      (proc 17)
      (proc 15)
      (text "もう少しさ。他人の見てる前で、平気で疼く＊＊＊を弄れるよう" 'br)
      (text "になるまでね。")
      (proc 17)
      (proc 16)
      (text "ふっ、ふぅぅぅッ！")
      (proc 17))
     (/ (proc 16) (text "うぐッ、うぐぅぅ‥‥‥") (proc 17))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 1) (= S 1) (<= H 11))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 16)
      (text "ふっ、ふっ、ふっ、ふっ‥‥‥")
      (proc 17)
      (proc 15)
      (text "まるで、さかりのついた牝猫だね。わたしに苛められながら、何回イッちまったんだ、言ってみな。")
      (proc 17)
      (proc 16)
      (text "‥‥‥‥‥‥‥‥‥")
      (proc 17)
      (proc 15)
      (text "まだ羞恥心なんて物が残ってたのか。恥ずかしくてたまらないだろう、苛められながら気を遣るのはさ！")
      (proc 17)
      (proc 15)
      (text "その姿を他の５人に見せてやりたいね。あのプリスが＊＊＊から" 'br)
      (text "汁を垂れ流して狂ってる様子を！")
      (proc 17)
      (proc 16)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (proc 17)
      (proc 15)
      (text "どうでもいいって顔してるじゃない、お前はもう完全に牝奴隷さ。二度と社会復帰なんて出来やしないね。")
      (proc 17))
     (/
      (proc 15)
      (text "お前はまるで、さかりのついた牝猫みたいだ。わたしに苛められながら、何回イッちまったんだ、言ってみな！")
      (proc 17))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (>= Y 1) (<= Y 2) (= S 1) (>= H 12) (= 789 #f))
   (proc 0)
   (proc 5)
   (exec-mem 256 "F 6")
   (exec-mem 256 "F 7")
   (exec-mem 256 "F 8")
   (exec-mem 256 "F 9")
   (mes-load? "mes¥bnkcpy2.mec" 0)
   (mes-load? 0)
   (exec-mem 256 "G 31 3 0 73 197")
   (exec-mem 256 "G 32 3 198 73 199")
   (exec-mem 256 "A 1")
   (image-file "gpc¥a1_52b1.gpc")
   (image-mem 1 0)
   (exec-mem 28672 3 3 76 399)
   (mes-load? 0)
   (exec-mem 256 "A 1")
   (exec-mem 256 "P 31 3 0")
   (exec-mem 256 "P 32 3 198")
   (exec-mem 256 "F 31")
   (exec-mem 256 "F 32")
   (image-file "gpc¥a1_52b2.gpc")
   (image-mem 1 0)
   (exec-mem 28672 3 3 76 399)
   (proc 12)
   (proc 6)
   (if (</>
        (//
         (? (= Y 1))
         (branch-reg
          991
          (</>
           (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 6 16))
           (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 71 16)))))
        (//
         (? (= Y 2))
         (branch-reg
          991
          (</>
           (/ (exec-mem 9504 "C icon¥tool13.gpc,GPC") (image-mem 1 0 6 40))
           (/
            (exec-mem 9504 "C icon¥tool13.gpc,GPC")
            (image-mem 1 0 71 40)))))))
   (proc 12)
   (proc 10)
   (proc 16)
   (text "うッ‥‥‥ハァ、ハァ、ハァ、ハァ、ハァ‥‥‥")
   (proc 17)
   (proc 15)
   (text "辛そうじゃない。何でそんな顔をしてる？")
   (proc 17)
   (proc 16)
   (text "おっ、お願い‥‥‥おトイレに行かせて下さい！")
   (proc 17)
   (proc 15)
   (text "嫌なこった。何でお前にそんな事をしてやらなきゃならない？")
   (proc 17)
   (proc 16)
   (text "そんなッ！　も、漏れちゃう‥‥‥")
   (proc 17)
   (proc 15)
   (text "トイレに行きたいなら、知ってる事を喋るんだ。軍のデータベースから盗んだ情報を何処に隠した？")
   (proc 17)
   (proc 15)
   (text "エイプリルとレイファの身体に隠した以外の奴だ。エリコはお前が持ってるって言ってたぞ。")
   (proc 17)
   (proc 16)
   (text "そんなの後でいいでしょ！　はやく‥‥‥トイレに！")
   (proc 17)
   (proc 15)
   (text "トイレ、トイレってうるさいね。そんなにトイレが好きなら、これから一生公衆便所がわりに使ってやるよ！")
   (proc 17)
   (proc 16)
   (text "わ、私は持ってないわ‥‥‥本当なのよッ！")
   (proc 17)
   (proc 15)
   (text "お前が持ってなくて、誰が持ってるんだよ。他の５人を使って機密を盗ませた張本人はお前だろうが。")
   (proc 17)
   (proc 15)
   (text "ミツコは軍の開発してる機構＝システムが悪い物だったからだとか戯言をほざいてるが、そんな事じゃわたしは納得しない。")
   (proc 17)
   (proc 15)
   (text "事件の黒幕であるお前が、その理由も知ってるはずだ。だがそれを聞く前に、まず機密の所在だ。早く言うんだよ！")
   (proc 17)
   (proc 16)
   (text "ああ、本当なのよ‥‥‥私は盗んだだけ、隠してはいないの！")
   (proc 17)
   (proc 15)
   (text "それじゃ、誰が隠したって言うんだ。まだ他に仲間が居るって言いたいのか？")
   (proc 17)
   (proc 16)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (proc 17)
   (proc 15)
   (text "早く言わないと、わたしの目の前で脱糞する羽目になるよ。そんな恥ずかしい事になってもいいのか？")
   (proc 17)
   (proc 16)
   (text "い、言うわ‥‥‥言うわよ‥‥‥アンナよ！")
   (proc 17)
   (proc 15)
   (text "アンナ？　何ふざけた事を言ってるんだ。")
   (proc 17)
   (proc 16)
   (text "嘘じゃないわ、私達が軍の機密を盗んだのは、アンナからシステムの話を聞いたからなのよ！")
   (proc 17)
   (proc 15)
   (text "何でそんな‥‥‥お前は白ロシア人だったな。まさか、アンナとは昔からの知り合い？")
   (proc 17)
   (proc 16)
   (text "そ、そうよ。この街に来るずっと以前からね‥‥‥")
   (proc 17)
   (nop@)
   (set-reg 789 #t)
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 1) (= S 1) (>= H 12) (= 789 #t)) (mes-jump "mes¥md_f3_r1.mes"))
 (seg (? (= Y 1) (= S 2))
   (sound 'se 1)
   (branch-reg
    775
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52ca.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "ンンッ‥‥‥")
      (proc 17)
      (proc 15)
      (text "動くんじゃないよ。さもないと、その顔に傷を付ける事になるかもしれない。")
      (proc 17)
      (proc 16)
      (text "ふぐぅ‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 775 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "ンンッ‥‥‥") (proc 17))
        (/ (proc 16) (text "うッ、うァァァッ‥‥‥") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 1) (= S 3))
   (sound 'se 1)
   (branch-reg
    776
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52cb.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "ンッ、ンン〜ッ！")
      (proc 17)
      (proc 15)
      (text "ギャクをそんなに強く噛むんじゃないよ。壊れてしまうじゃない。今まで何人もの人間の唾液を吸ってきた大切な物なんだから！")
      (proc 17)
      (proc 16)
      (text "うう〜ッ‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 776 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "ンッ、ンン〜ッ！") (proc 17))
        (/ (proc 16) (text "いっ、痛ッ‥‥‥‥‥‥") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 1) (= S 4))
   (sound 'se 1)
   (branch-reg
    777
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52cc.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "ふぅぅぅン！")
      (proc 17)
      (proc 15)
      (text "ちょっとオッパイを苛められただけで、そのざまか。イッちゃいそうになったら、ちゃんとわたしに言うんだよ！")
      (proc 17)
      (proc 16)
      (text "ふッ、ふッ、ふッ‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 777 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "ふぅぅぅン！") (proc 17))
        (/ (proc 16) (text "だ、駄目！　そんな事したら‥‥‥おかしくなっちゃうわ！") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 1) (= S 5))
   (sound 'se 1)
   (branch-reg
    778
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52cd.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "ふッ‥‥‥ふンッ！")
      (proc 17)
      (proc 15)
      (text "まだまだだよ！　これくらいで感じてたら、何回イッちまうかわからないからね。")
      (proc 17)
      (proc 16)
      (text "うぅぅッ‥‥‥‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 778 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "ふッ‥‥‥ふンッ！") (proc 17))
        (/ (proc 16) (text "はンッ！　そ、それ以上は‥‥‥") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 1) (= S 6))
   (sound 'se 1)
   (branch-reg
    779
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52ce.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "ンくっ！")
      (proc 17)
      (proc 15)
      (text "足が震えてるじゃないか。背中のロープを外したら、床に倒れてしまいそうだね。でも、そうはいかないよ！")
      (proc 17)
      (proc 16)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 779 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "ンくっ！") (proc 17))
        (/ (proc 16) (text "痛いッ、そこは痛いわ‥‥‥") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 1) (= S 7))
   (sound 'se 1)
   (branch-reg
    780
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52cf.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "ンッ、ンン〜ッ！")
      (proc 17)
      (proc 15)
      (text "どうして尻の穴をヒクヒクさせてるんだ？　面白い女だな、尻を叩かれると、機械仕掛けみたいに動きだすんだな。")
      (proc 17)
      (proc 16)
      (text "ンン‥‥‥‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 780 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "ンッ、ンン〜ッ！") (proc 17))
        (/ (proc 16) (text "だ、駄目ぇ〜ッ！　そこは‥‥‥漏れちゃう！") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 1) (= S 8))
   (sound 'se 1)
   (branch-reg
    781
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52cg.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "ふンッ、ふっ‥‥‥ふぅぅン！")
      (proc 17)
      (proc 15)
      (text "不満そうじゃないか。ダンナに可愛がってもらえない若妻って雰囲気だよ。＊＊＊を苛めてもらえないのがそんなに不満なのか！")
      (proc 17)
      (proc 16)
      (text "ふぅ〜ン、ふぅぅン‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 781 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "ふンッ、ふっ‥‥‥ふぅぅン！") (proc 17))
        (/ (proc 16) (text "はうッ！　も、もう駄目‥‥‥‥‥‥‥‥‥") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 1) (= S 9))
   (sound 'se 1)
   (branch-reg
    782
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52ch.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "ふぅッ‥‥‥")
      (proc 17)
      (proc 15)
      (text "打たれるのに慣れてきたようだね。悲鳴が悲鳴でなくなってきた。わたしには、喘ぎ声に聞こえるよ！")
      (proc 17)
      (proc 16)
      (text "ふっ、ふっ、ふっ、ふっ‥‥‥‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 782 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "ふぅッ‥‥‥") (proc 17))
        (/ (proc 16) (text "あぅぅッ‥‥‥何でも話すから、もう許して！") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 1) (= S 10))
   (sound 'se 1)
   (branch-reg
    783
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52ci.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "んぐぅぅ‥‥‥んん〜ッ！")
      (proc 17)
      (proc 15)
      (text "お尻を苛めてやったぞ、お前は大好きだろう？　お尻を苛められるのがさ。皮が剥けて血が出るまで叩いてやろうか！")
      (proc 17)
      (proc 16)
      (text "うぐっ、う、ううう‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 783 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "んぐぅぅ‥‥‥んん〜ッ！") (proc 17))
        (/ (proc 16) (text "アッ！　で、出ちゃう‥‥‥漏れちゃうわ！") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 1) (= S 11))
   (sound 'se 1)
   (branch-reg
    784
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52cj.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "くぅぅぅぅン！")
      (proc 17)
      (proc 15)
      (text "その、ぱっくり口を開いた汚らしい＊＊＊を何とかしたらどうな" 'br)
      (text "んだ。見るに耐えないね。")
      (proc 17)
      (proc 16)
      (text "うっ、うう‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 784 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "くぅぅぅぅン！") (proc 17))
        (/ (proc 16) (text "はぅぅン‥‥‥もう我慢が‥‥‥ど、どうなっても知らないから！") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 1) (= S 12))
   (sound 'se 1)
   (branch-reg
    785
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52ck.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "ぐッ‥‥‥くゥゥゥン！")
      (proc 17)
      (proc 15)
      (text "そのひときわ大きな喘ぎ声は‥‥‥まさか、イッちまったんじゃないだろうね。わたしが見てる前で気を遣ったのか？")
      (proc 17)
      (proc 16)
      (text "うっ、ううッ‥‥‥ンンンン‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 785 #t))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "ぐッ‥‥‥くゥゥゥン！") (proc 17))
        (/ (proc 16) (text "はンッ！　あ、で、出ちゃう‥‥‥そんな事されると‥‥‥") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 2) (= S 1) (<= H 6))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 15)
      (text "あんたの大好きな鞭をくれてやるよ、楽しみにしてな！")
      (proc 17)
      (proc 16)
      (text "んぐぅ、んんん〜ッ！")
      (proc 17)
      (proc 15)
      (text "そんなに悦ばれると、わたしもやり甲斐があるってもんだ。身体中傷だらけにしてやるから、覚悟するんだね！")
      (proc 17)
      (proc 16)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (proc 17)
      (proc 15)
      (text "鞭だけじゃない。ロッドも、もっといい物も用意してあるんだ。最高に効く奴をね‥‥‥")
      (proc 17)
      (proc 15)
      (text "待ってな、もうすぐプレゼントしてやるから。")
      (proc 17))
     (/ (proc 15) (text "あんたの大好きな鞭をくれてやるよ、楽しみにしてな！") (proc 17))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 2) (= S 1) (<= H 11))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 16)
      (text "んぐゥ‥‥‥‥‥‥")
      (proc 17)
      (proc 15)
      (text "どうしたって言うんだい、身体中に脂汗をかいて。わたしの拷問がそんなに不愉快だって言いたいのか？")
      (proc 17)
      (proc 16)
      (text "ンンンン‥‥‥‥‥‥‥‥‥")
      (proc 17)
      (proc 15)
      (text "ああそうかい。お前がそういう態度を取るんなら、このままお前を放っといて、わたしは部屋で休ませてもらうよ！")
      (proc 17)
      (proc 16)
      (text "うぅ〜ッ！　うう、ううぅぅ〜ン！")
      (proc 17)
      (proc 15)
      (text "わたしに行かないで欲しいって？　可愛い事を言うじゃない。最初からそういう風にしてればよかったんだよ。")
      (proc 17)
      (proc 15)
      (text "お前は不細工でわたしの好みじゃないが、そこまで言うんなら可愛がってやらない事もないんだ。")
      (proc 17)
      (proc 16)
      (text "うぅ‥‥‥‥‥‥")
      (proc 17))
     (/
      (proc 15)
      (text "どうしたって言うんだい、身体中に脂汗をかいて。わたしの拷問がそんなに不愉快だって言いたいのか？")
      (proc 17))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 2) (= S 1) (>= H 12) (= 789 #t)) (mes-jump "mes¥md_f3_r2.mes"))
 (seg (? (= Y 2) (= S 2))
   (sound 'se 1)
   (branch-reg
    775
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52ca.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "ふぁっ‥‥‥ふぅぅ〜ッ！")
      (proc 17)
      (proc 15)
      (text "ちょっと驚いたかい？　そんな顔でも、傷が付けば台無しになってしまうって？")
      (proc 17)
      (proc 16)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 775 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "ふぁっ‥‥‥ふぅぅ〜ッ！") (proc 17))
        (/ (proc 16) (text "やっ、止めて！　私は嘘は言ってないのに！") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 2) (= S 3))
   (sound 'se 1)
   (branch-reg
    776
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52cb.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "うぐぅぅッ‥‥‥")
      (proc 17)
      (proc 15)
      (text "どんな気分だ、鞭で皮膚が裂けるほど強く叩かれるのは？　今のお前には、とっても心地いいんじゃないのか？")
      (proc 17)
      (proc 16)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (nop@)
      (set-reg 776 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "うぐぅぅッ‥‥‥") (proc 17))
        (/ (proc 16) (text "あんッ、どうして叩くの‥‥‥知ってる事は話してるのに！") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 2) (= S 4))
   (sound 'se 1)
   (branch-reg
    777
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52cc.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "ンッ、ンン〜ッ‥‥‥‥‥‥")
      (proc 17)
      (proc 15)
      (text "オッパイを苛められるのが気持ちいいか？　自分の＊＊＊がどれ" 'br)
      (text "だけグチュグチュになってるのか、自分でもわかるだろう。")
      (proc 17)
      (proc 16)
      (text "んっ、んっ、んんッ！")
      (proc 17)
      (nop@)
      (set-reg 777 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "ンッ、ンン〜ッ‥‥‥‥‥‥") (proc 17))
        (/ (proc 16) (text "あくぅッ！　オッパイは止めて‥‥‥おかしくなっちゃうわ！") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 2) (= S 5))
   (sound 'se 1)
   (branch-reg
    778
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52cd.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "ンッ！　ンッ！　ンッ！　ンン〜ッ！")
      (proc 17)
      (proc 15)
      (text "お前は何処でもいいのかい、何処を打たれても感じるんだろう！　生まれついてのの牝奴隷だね、信じられないよ。")
      (proc 17)
      (proc 16)
      (text "ンン‥‥‥‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 778 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "ンッ！　ンッ！　ンッ！　ンン〜ッ！") (proc 17))
        (/ (proc 16) (text "はうン！　な、何でも話すって言ってるじゃない！") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 2) (= S 6))
   (sound 'se 1)
   (branch-reg
    779
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52ce.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "んッ、くッ‥‥‥")
      (proc 17)
      (proc 15)
      (text "乳首は硬くなってる、＊＊＊もグチョグチョだ。これでもまだ、" 'br)
      (text "お上品な女のつもりでいるのか！")
      (proc 17)
      (proc 16)
      (text "‥‥‥‥‥‥‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 779 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "んッ、くッ‥‥‥") (proc 17))
        (/ (proc 16) (text "あくぅ！　お、お願い‥‥‥何でも喋るから！") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 2) (= S 7))
   (sound 'se 1)
   (branch-reg
    780
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52cf.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "ンン〜ッ、ンッ！")
      (proc 17)
      (proc 15)
      (text "何てでかい尻なんだろうね。これじゃわたしの腕を見せる機会がないじゃないか。目をつぶってても当たるよ！")
      (proc 17)
      (proc 16)
      (text "ぐぅぅ‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 780 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "ンン〜ッ、ンッ！") (proc 17))
        (/ (proc 16) (text "ううッ、そ、そこ‥‥‥駄目ッ！") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 2) (= S 8))
   (sound 'se 1)
   (branch-reg
    781
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52cg.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "ふぅぅッ‥‥‥ふぅぅン！")
      (proc 17)
      (proc 15)
      (text "おやおや、はしたない声を出すじゃないか。自分が牝奴隷だって事を認めて、素直に感じるようになったね。")
      (proc 17)
      (proc 16)
      (text "うう‥‥‥ふぅぅン‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 781 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "ふぅぅッ‥‥‥ふぅぅン！") (proc 17))
        (/ (proc 16) (text "あァァァ‥‥‥そ、そんな事‥‥‥駄目、もう駄目ぇ！") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 2) (= S 9))
   (sound 'se 1)
   (branch-reg
    782
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52ch.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "ンッ、ンン〜ッ！")
      (proc 17)
      (proc 15)
      (text "気持ちがいいか？　徐々に牝奴隷の礼儀も教えてやる。気持ちよくしてもらったら、ご主人様にお礼を言うんだ！")
      (proc 17)
      (proc 16)
      (text "う、うぅぅっ‥‥‥ううッ！")
      (proc 17)
      (nop@)
      (set-reg 782 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "ンッ、ンン〜ッ！") (proc 17))
        (/ (proc 16) (text "はッ、はぁン‥‥‥お願い、おトイレに行かせて‥‥‥") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 2) (= S 10))
   (sound 'se 1)
   (branch-reg
    783
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52ci.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "くぅぅぅ〜ン！")
      (proc 17)
      (proc 15)
      (text "やっぱりお尻を叩かれるのが一番みたいね。何回でもイッちまいそうな勢いじゃない？")
      (proc 17)
      (proc 16)
      (text "ふッ、ふッ、ふッ、ふッ‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 783 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "くぅぅぅ〜ン！") (proc 17))
        (/ (proc 16) (text "し、死んじゃうぅ‥‥‥このままじゃ‥‥‥ああァァ！") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 2) (= S 11))
   (sound 'se 1)
   (branch-reg
    784
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52cj.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "うぐッ、ふッ‥‥‥ふぅぅッ‥‥‥")
      (proc 17)
      (proc 15)
      (text "ここじゃ満足出来ないって？　グチュグチュになってる＊＊＊を" 'br)
      (text "苛めて欲しいって言ってるのか、ハッキリ言いなよ。")
      (proc 17)
      (proc 16)
      (text "うう、ううぅぅッ！")
      (proc 17)
      (nop@)
      (set-reg 784 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "うぐッ、ふッ‥‥‥ふぅぅッ‥‥‥") (proc 17))
        (/ (proc 16) (text "あくぅッ、ほ、本当に漏れちゃう‥‥‥‥‥‥") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 2) (= S 12))
   (sound 'se 1)
   (branch-reg
    785
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_52ck.gpc")
      (image-mem 1 0)
      (proc 12)
      (proc 10)
      (proc 16)
      (text "ンンッ‥‥‥")
      (proc 17)
      (proc 15)
      (text "卑しい牝豚！　汚い尻を振って、何をしたいってんだ。＊＊＊に" 'br)
      (text "チ○ポを入れて欲しいとでも言うのかい！")
      (proc 17)
      (proc 16)
      (text "うう‥‥‥‥‥‥")
      (proc 17)
      (nop@)
      (set-reg 785 #t)
      (proc 19))
     (/
      (proc 10)
      (branch-reg
       789
       (</>
        (/ (proc 16) (text "ンンッ‥‥‥") (proc 17))
        (/ (proc 16) (text "はぁぁン、お願いよ‥‥‥おトイレに行かせて、何でも言うわ！") (proc 17)))))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 10) (= S 1) (= 786 #f))
   (proc 10)
   (branch-reg
    789
    (</>
     (/
      (proc 16)
      (text "ンッ！　ンン〜ッ‥‥‥")
      (proc 17)
      (proc 15)
      (text "こいつの中に入ってるのは、よく冷やしたグリセリンさ。お前の尻の中にたっぷり流し込んでやる。")
      (proc 17)
      (proc 16)
      (text "ンンンンンン！")
      (proc 17)
      (proc 15)
      (text "すると、どうなる？　言わなくてもわかるだろう。あたり一面に、汚物をぶち撒ける事になるのさ！")
      (proc 17)
      (proc 15)
      (text "そうなりたくなかったら、早く口を割ってしまう事だね！")
      (proc 17))
     (/
      (proc 16)
      (text "い、嫌ァ‥‥‥近づけないで！")
      (proc 17)
      (proc 15)
      (text "臭くって仕方ないって？　自分の尻の穴に差し込まれてた物だよ。汚いもくそもないだろう。")
      (proc 17)
      (proc 16)
      (text "あうぅぅ‥‥‥く、苦しい！")
      (proc 17)
      (proc 15)
      (text "お中がグルグル音を立ててる、あとどれくらい辛抱出来るかな？")
      (proc 17)
      (proc 16)
      (text "お、お願い‥‥‥早くっ‥‥‥トイレに！")
      (proc 17))))
   (nop@)
   (set-reg 786 #t)
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 10) (= S 1) (= 786 #t)) (mes-load? 4096))
 (seg (? (= Y 10) (= S 4) (= 787 #f))
   (proc 10)
   (branch-reg
    789
    (</>
     (/
      (proc 16)
      (text "ふ、ふンッ‥‥‥‥‥‥")
      (proc 17)
      (proc 15)
      (text "よく冷えてるだろう？　中身は冷たいグリセリンだからね。お前の為に、冷蔵庫で保管しといたのさ。")
      (proc 17)
      (proc 15)
      (text "お前の尻からぶち込んでやるからね。" 'br)
      (text "楽しみだろう、わくわくするね！")
      (proc 17)
      (proc 16)
      (text "ンン〜ッ！　ン、ンンッ！")
      (proc 17)
      (proc 15)
      (text "嫌でも逃げられないよ。最低の恥辱を味あわせてやる！")
      (proc 17))
     (/
      (proc 16)
      (text "なッ、何するのよ‥‥‥それを退けて！")
      (proc 17)
      (proc 15)
      (text "そんな悠長な事を言ってる場合じゃないだろう？　あとどれくらい辛抱できるか、自分でわかってるのか？")
      (proc 17)
      (proc 15)
      (text "もうすぐお前は、部屋中に汚物をぶち撒ける事になるのさ。わたしの見てる目の前でね！")
      (proc 17)
      (proc 16)
      (text "な、何でも話すわ‥‥‥だから、お願い！")
      (proc 17))))
   (nop@)
   (set-reg 787 #t)
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 10) (= S 4) (= 787 #t))
   (proc 10)
   (branch-reg
    789
    (</>
     (/ (proc 16) (text "ふ、ふンッ‥‥‥‥‥‥") (proc 17))
     (/ (proc 16) (text "なッ、何するのよ‥‥‥それを退けて！") (proc 17))))
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 10) (= S 13) (= 788 #f))
   (nop@)
   (inc-var H 1)
   (proc 0)
   (proc 5)
   (exec-mem 256 "G 0 8 144 4 40")
   (exec-mem 256 "G 1 49 0 28 149")
   (image-file "gpc¥a1_52a1.gpc")
   (image-mem 1 0)
   (proc 12)
   (proc 10)
   (proc 16)
   (text "うッ‥‥‥うぅぅ〜ッ！")
   (proc 17)
   (proc 15)
   (text "動くんじゃないよ！　こいつはガラスで出来てるからね、ヘタをすると、尻の穴が使い物にならなくなってしまうよ！")
   (proc 17)
   (proc 16)
   (text "うぅ〜っ！")
   (proc 17)
   (proc 15)
   (text "さあ、たっぷり流し込んでやるよ。浣腸器一杯のグリセリンだからね。さぞかし面白い事になるだろうね！")
   (proc 17)
   (proc 16)
   (text "んぐぅぅぅ！")
   (proc 17)
   (proc 11)
   (exec-mem 256 "F 10")
   (exec-mem 3072 0)
   (mes-load? "mes¥bnkcpy2.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥md_f3ani.mec" 0)
   (mes-load? 0)
   (proc 10)
   (proc 16)
   (text "ンッ、ンッ、ンッ、ンン〜ッ！")
   (proc 17)
   (proc 15)
   (text "もうお腹がグルグル言いだした。すごい効果だね、どういう事になるのか、じっと見ていてやろうか‥‥‥")
   (proc 17)
   (proc 16)
   (text "ふぅぅ‥‥‥‥‥‥")
   (proc 17)
   (proc 15)
   (text "ちゃんと尻の穴を締めて、汚い物が漏れないようにするんだよ。わたしにかけてみろ、ただじゃ済まさないからな！")
   (proc 17)
   (proc 11)
   (exec-mem 256 "F 10")
   (exec-mem 3072 0)
   (mes-load? "mes¥bnkcpy2.mec" 0)
   (mes-load? 0)
   (exec-mem 256 "A 1")
   (exec-mem 256 "P 0 8 144")
   (exec-mem 256 "P 1 49 0")
   (exec-mem 256 "F 0")
   (exec-mem 28672 64 144 95 183)
   (exec-mem 28672 392 0 615 207)
   (exec-mem 256 "P 1 49 0")
   (exec-mem 256 "F 1")
   (proc 12)
   (proc 6)
   (branch-reg
    991
    (</>
     (/ (exec-mem 9504 "C icon¥tool21.gpc,GPC") (image-mem 1 0 6 232))
     (/ (exec-mem 9504 "C icon¥tool21.gpc,GPC") (image-mem 1 0 71 232))))
   (proc 10)
   (proc 15)
   (text "これでよし。さあ、さっさと喋らないと、部屋中にお前の汚物がぶち撒けられる事になっちまう。")
   (proc 17)
   (proc 15)
   (text "それでもいいって言うなら、放っといてやるけど。人前でクソを垂れるのが恥ずかしくないってえならね。")
   (proc 17)
   (nop@)
   (set-reg 788 #t)
   (proc 11)
   (exec-mem 256 "F 10"))
 (seg (? (= Y 10) (= S 13) (= 788 #t))
   (proc 10)
   (branch-reg
    789
    (</>
     (/ (proc 15) (text "これ以上は入らないみたいだな、腸の中はクソとグリセリンで一杯になっちまってる。") (proc 17))
     (/ (proc 16) (text "アアッ、駄目ェ！　も、漏れる‥‥‥アアァァァッ！") (proc 17))))
   (proc 11)
   (exec-mem 256 "F 10")))