(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (proc 10)
  (proc 16)
  (text "ああ、もういいでしょ‥‥‥漏れる！")
  (wait)
  (text-reset 14)
  (proc 15)
  (text "黙れ！　静かにしないと、その尻の穴に栓をしてしまうぞ！")
  (wait)
  (text-reset 14)
  (proc 16)
  (text "言ったでしょ、私が喋れば困るのはあなた達だって‥‥‥")
  (wait)
  (text-reset 14)
  (proc 15)
  (text "どうしてアンナは機密を盗もうなんて考えたんだ。お前達はどうしてそれに手を貸した。")
  (wait)
  (text-reset 14)
  (proc 16)
  (text "‥‥‥‥‥‥あれは、機構＝システムなんて代物じゃないわ。")
  (wait)
  (text-reset 14)
  (proc 16)
  (text "ただのポッドモッドじゃないの！　感情をコントロールするのよ。恐怖も怒りも喜びも、全て思いのままに制御出来るのよ！")
  (wait)
  (text-reset 14)
  (proc 15)
  (text "だから‥‥‥何だって言うんだ。")
  (wait)
  (text-reset 14)
  (proc 16)
  (text "救いがたい鈍さね。それを使えば、人間を思いのままに操れるじゃないの。恐怖を感じない兵士は死を恐れず戦うわ。")
  (wait)
  (text-reset 14)
  (proc 16)
  (text "痛みも感じなければ、傷を負っても死ぬまで戦い続ける‥‥‥")
  (wait)
  (text-reset 14)
  (proc 15)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (proc 16)
  (text "もう限界よ‥‥‥お願い、トイレに行かせてぇ！")
  (wait)
  (text-reset 14)
  (proc 15)
  (text "つまり軍部は兵士にそのチップを埋め込んで、超人的な兵士を造ろうとしてるって事なのか？")
  (wait)
  (text-reset 14)
  (proc 16)
  (text "兵士だけじゃないわ‥‥‥そのうち皆やられるわよ‥‥‥")
  (wait)
  (text-reset 14)
  (proc 15)
  (text "今の話が本当だとしても、アンナがそれをしなきゃならない理由は何処にもないね。まさか英雄になりたかった訳じゃないだろう。")
  (wait)
  (text-reset 14)
  (proc 16)
  (text "は、早く‥‥‥も、もう漏れる！")
  (wait)
  (text-reset 14)
  (proc 15)
  (text "それに、自分が機密を盗んだ犯人だってのに、どうして部下のわたしに捜査をさせたのか‥‥‥")
  (wait)
  (text-reset 14)
  (proc 16)
  (text "そ、そんな事はアンナ本人から聞けばいいでしょう！")
  (wait)
  (text-reset 14)
  (proc 16)
  (text "あうッ‥‥‥もう駄目‥‥‥")
  (wait)
  (text-reset 14)
  (proc 15)
  (text "勝手に漏らしてろ。わたしはアンナに会いに行く、今の話が本当なのか、確かめなければならないからな。")
  (wait)
  (text-reset 14)
  (proc 16)
  (text "ま、待って‥‥‥お願い！")
  (wait)
  (text-reset 14)
  (nop@)
  (set-reg 74 #t)
  (proc 11)
  (exec-mem 18688 3)
  (exec-mem 18688 5 1 0)
  (exec-mem 3072 0)
  ((cmd 209) 0 5)
  (image-file "gpc¥waku.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (exec-mem 9504 "E")
  (exec-mem 256 "I")
  (mes-jump "mes¥MA_B06.MES")))