(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (nop@)
   (set-reg 980 #t)
   (set-reg 981 #t)
   (set-reg 982 #f)
   (set-reg 983 #f)
   (set-reg 984 #f)
   (set-reg 985 #f)
   (set-reg 986 #f)
   (set-reg 987 #f)
   (set-reg 988 #f)
   (set-reg 989 #f)
   (set-reg 990 #f)
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_50.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (if (</>
        (//
         (? (= P 10))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_10.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 10))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_10v.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 10)))))
        (// (nop@))))
   (exec-mem 256 "E")
   (load-mem "clm¥A1_50.clm" 32768)
   (load-mem "clm¥icon.clm" 20480)
   (mes-load? "mes¥icon_cl.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥icon_c2.mec" 0)
   (mes-load? 0)
   (text-frame 10 312 70 370)
   (exec-mem 256 "A 0")
   (proc 12)
   (define-proc 15
     (<>
      (if (</>
           (//
            (? (>= H 5) (= 758 #f))
            (image-file "gpc¥a1_50a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 758 #t))
           (// (nop@))))
      (proc 12)))
   (set-var H 0)
   (proc 10)
   (text "「Priss」" 'br)
   (text "これが情報部の自慢の、尋問室という訳ね。案外安っぽいものね。もっと仰々しい設備が整ってるのかと思ったわ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "余計な事は言わなくていい。それにこの部屋には金じゃ買えない物がゴマンと詰まってるんだよ。")
   (wait)
   (text-reset 14)
   (text "「Priss」" 'br)
   (text "今のこの世で、お金で買えない物なんて皆無だわ。地位も、名声も権力も。全てが売買の対象だもの。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そうでもない。囚人の流した血と汗と、恐怖の匂い。これは金じゃ買えない物さ！")
   (wait)
   (text-reset 14)
   (text "「Priss」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたは頭がいい、他のどの囚人よりも。だから言うんだよ、早く知ってる事を喋っちまった方が利口だと思わないか？")
   (wait)
   (text-reset 14)
   (text "「Priss」" 'br)
   (text "私が喋ったら‥‥‥困るのはあなたの方なんじゃないかしら？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "馬鹿な事を。脅しのつもりか？　そっちがそういう態度を取るのなら、こっちも相応のお返しをしなきゃならない。")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (exec-mem 256 "P 5 6 0")
   (loop
    (set-var S 0)
    (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
    (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (= Z 1) (= 991 #f))
   (proc 0)
   (exec-mem 256 "P 5 71 0")
   (nop@)
   (set-reg 991 #t)
   (exec-mem 256 "P 8 6 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 71 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 71 40))))
   (load-mem "clm¥icon2.clm" 20480)
   (proc 1))
 (seg (? (= Z 1) (= 991 #t))
   (proc 0)
   (exec-mem 256 "P 5 6 0")
   (nop@)
   (set-reg 991 #f)
   (exec-mem 256 "P 9 71 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 6 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 6 40))))
   (load-mem "clm¥icon.clm" 20480)
   (proc 1))
 (seg (? (= Z 2) (= 991 #f))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #f))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Z 2) (= 991 #t))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #t))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Y 1) (= S 1) (<= H 4))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Priss」" 'br)
      (text "これでも私は、忙しい身体なの。まだ何か用があるならまた今度って事にしてもらえないかしら？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ふざけた事を言うじゃない、まだまだこれからが本番だよ！")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "やっぱりね‥‥‥言ってみただけなの、気にしないで。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "早くも音をあげそうだって事かい？　少しはわたしにも楽しませてほしいね。")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/ (text "「Priss」" 'br) (text "‥‥‥‥‥‥‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 7))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Priss」" 'br)
      (text "くッ‥‥‥あ、あなた、いつもこんな事してるの？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "もう降参かい？　案外弱かったねぇ。それじゃ吐いてもらおうか。どうして軍の機密を盗んだのかをさ！")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "残念だけど‥‥‥言う訳にはいかないわ。私はまだ全てを失った訳ではないのだから。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そいつはどうかな。公安部での地位も、財産も全てお終いだと思うけどね。")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "あなた、言ったでしょ。お金や地位では買えない物があるの。私はそれを失いたくないのよ‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "「Priss」" 'br)
      (text "あなた、言ったでしょ。お金や地位では買えない物があるの。私はそれを失いたくないのよ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 8))
   (proc 10)
   (text "「Priss」" 'br)
   (text "うッ‥‥‥くッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "おっと、それ以上口を聞くんじゃないよ。わたしのお楽しみが台無しになっちまうだろうが。")
   (wait)
   (text-reset 14)
   (text "「Priss」" 'br)
   (text "まだやるつもりなの‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "冗談じゃない。まだまだこれからさ！")
   (wait)
   (text-reset 14)
   (text "「Priss」" 'br)
   (text "あなたおかしいわ。どうして人間を相手に、こんな酷い事が出来るのよ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたら囚人は人間じゃない、家畜以下の牝奴隷だ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたもすぐに、苛められてヒイヒイ言って悦ぶようになるのさ！")
   (wait)
   (text-reset 14)
   (text "「Priss」" 'br)
   (text "そんなの御免だわ、嫌よ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そうはいかないんだよ！　まずはその口を塞がせてもらうからね！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 18688 3)
   (exec-mem 18688 5 1 0)
   (exec-mem 3072 0)
   (mes-jump "mes¥MD_F02.MES"))
 (seg (? (= Y 1) (= S 2))
   (sound 'se 1)
   (branch-reg
    750
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_50ba.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (text "「Priss」" 'br)
      (text "んくッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "こんな程度で悲鳴をあげるようじゃ、わたしの拷問には耐えられないよ。素直に吐いちまいな！")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "なんて野蛮な！　こんな事が許される訳ないわ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 750 #t))
     (/
      (proc 10)
      (text "「Priss」" 'br)
      (text "んくッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 3))
   (sound 'se 1)
   (branch-reg
    751
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_50bb.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Priss」" 'br)
      (text "きっ、きゃァッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "これでも手加減してるんだ。わたしが本気になったら、こんなもんじゃ済まないよ！")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "こんなの耐えられないわ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 751 #t))
     (/
      (proc 10)
      (text "「Priss」" 'br)
      (text "きっ、きゃァッ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 4))
   (sound 'se 1)
   (branch-reg
    752
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_50bc.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Priss」" 'br)
      (text "ううッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "だらしのない女だね、エリコだってこんな程度で悲鳴をあげるような事はしなかったよ！")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "冗談じゃないわ、私は他のがさつな人間とは違うのよ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 752 #t))
     (/
      (proc 10)
      (text "「Priss」" 'br)
      (text "ううッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 5))
   (sound 'se 1)
   (branch-reg
    753
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_50bd.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Priss」" 'br)
      (text "はッ‥‥‥んんッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ほらほら、早く降参しちまわないと、どんどん大事な所に近づいてくって事がわからないのかい！")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "や、やるなら一思いにやったらどうなの‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 753 #t))
     (/
      (proc 10)
      (text "「Priss」" 'br)
      (text "はッ‥‥‥んんッ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 6))
   (sound 'se 1)
   (branch-reg
    754
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_50be.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Priss」" 'br)
      (text "アッ‥‥‥そ、そこはッ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "わたしがその気になれば、そのセクシーな下着を剥ぎとってしまう事も出来るんだ。そうなる前に覚悟を決めた方がよかないか？")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "なんて下品な言い方なの、あなた本当に日本人なの？")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 754 #t))
     (/
      (proc 10)
      (text "「Priss」" 'br)
      (text "アッ‥‥‥そ、そこはッ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 7))
   (sound 'se 1)
   (branch-reg
    755
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_50bf.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Priss」" 'br)
      (text "ンッ、もう‥‥‥それ以上はッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あんたはわたしを殺そうとしたんだよ？　これくらいの事が何だ。死んだほうがマシって目にあわせてやるよ。")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "あ、あれは仕方がなかったのよ‥‥‥私のせいではないわ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 755 #t))
     (/
      (proc 10)
      (text "「Priss」" 'br)
      (text "ンッ、もう‥‥‥それ以上はッ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 8))
   (sound 'se 1)
   (branch-reg
    756
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_50bg.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Priss」" 'br)
      (text "そっ、そこは駄目ッ‥‥‥そこは許して！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "許して下さい、はいそうですかって訳にゃいかないんだよ。あんた何か勘違いしてないか、これは遊びじゃないんだよ！")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "軍の機密が何だって言うの、そんな大層な物じゃないわ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 756 #t))
     (/
      (proc 10)
      (text "「Priss」" 'br)
      (text "そっ、そこは駄目って言ってるじゃないの！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 9))
   (sound 'se 1)
   (branch-reg
    757
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_50bh.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Priss」" 'br)
      (text "いッ、痛いわ！　そんな事しないで！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "当たり前だろ、痛くしてるんだからさ。それが嫌だって言うなら、いつまでも意地張ってないで、さっさと吐いちまうんだね！")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "それだけは‥‥‥それだけは出来ないわ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 757 #t))
     (/
      (proc 10)
      (text "「Priss」" 'br)
      (text "いッ、痛いわ！　そんな事しないで！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 4))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "あんただって元公安部だ、拷問の１回ぐらいやった事があるだろ？わたしを怨むのは止めてほしいね。")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "私は拷問なんてした事ないわ。言ったでしょう、雑用はやらないって。こんな仕事は他の誰かの物よ。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そりゃ残念だね。こんな楽しい仕事を、わざわざ部下に回してやるなんてさ！")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "あなたは何処かおかしいわ。まともな神経なら、人間を嬲って楽しむなんて、出来ないはずよ。")
      (wait)
      (text-reset 14))
     (/
      (text "「Priss」" 'br)
      (text "あなたは何処かおかしいわ。まともな神経なら、人間を嬲って楽しむなんて、出来ないはずよ。")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 7))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Priss」" 'br)
      (text "も、もう止めて‥‥‥もう十分だわ。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "馬鹿な事を言うんじゃないよ。まだこれからさ！")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "冗談じゃないわ、死んでしまうわよ。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "それじゃ仕方がないね。あんたの知ってる事を喋ってもらおうか。どうして軍の機密を盗もうとしたのか、とかね‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "それは‥‥‥言えないわ。")
      (wait)
      (text-reset 14))
     (/ (text "「Priss」" 'br) (text "も、もう止めて‥‥‥もう十分だわ。") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 8))
   (proc 10)
   (text "「Priss」" 'br)
   (text "うッ‥‥‥くッ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "おっと、それ以上口を聞くんじゃないよ。わたしのお楽しみが台無しになっちまうだろうが。")
   (wait)
   (text-reset 14)
   (text "「Priss」" 'br)
   (text "まだやるつもりなの‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "冗談じゃない。まだまだこれからさ！")
   (wait)
   (text-reset 14)
   (text "「Priss」" 'br)
   (text "あなたおかしいわ。どうして人間を相手に、こんな酷い事が出来るのよ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたら囚人は人間じゃない、家畜以下の牝奴隷だ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたもすぐに、苛められてヒイヒイ言って悦ぶようになるのさ！")
   (wait)
   (text-reset 14)
   (text "「Priss」" 'br)
   (text "そんなの御免だわ、嫌よ！")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "そうはいかないんだよ！　まずはその口を塞がせてもらうからね！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 18688 3)
   (exec-mem 18688 5 1 0)
   (exec-mem 3072 0)
   (mes-jump "mes¥MD_F02.MES"))
 (seg (? (= Y 2) (= S 2))
   (sound 'se 1)
   (branch-reg
    750
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_50ba.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (text "「Priss」" 'br)
      (text "くッ！　こ、こんな事をして後悔するのはあなたよ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "まだそんな事言ってるのか。あんたにはね、もう何の力もないんだよ。その事に早く気付いた方が身のためだと思うけどね！")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "信じ難いほどの間抜けね‥‥‥そんな事を言ってるんじゃないわ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 750 #t))
     (/
      (proc 10)
      (text "「Priss」" 'br)
      (text "くッ！　こ、こんな事をして後悔するのはあなたよ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 3))
   (sound 'se 1)
   (branch-reg
    751
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_50bb.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Priss」" 'br)
      (text "キャッ‥‥‥あ、危ないわ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "脚を少しかすめただけじゃないか。大体ね、あんたが死んだって誰も文句を言いやしないんだよ？")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "でも‥‥‥私が死んだら、永遠に機密の所在はわからないわ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "こんな程度で死ぬもんか。もっとも、これから死んだ方がマシって目にあってもらうんだけどね！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 751 #t))
     (/
      (proc 10)
      (text "「Priss」" 'br)
      (text "キャッ‥‥‥あ、危ないわ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 4))
   (sound 'se 1)
   (branch-reg
    752
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_50bc.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Priss」" 'br)
      (text "くぅっ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あんたは人一倍苦痛に弱いみたいだね。エイプリルやレイファは、これくらいで悲鳴をあげたりはしなかったよ。")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "い、一緒にしないで‥‥‥私はあの子達より繊細なのよ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 752 #t))
     (/
      (proc 10)
      (text "「Priss」" 'br)
      (text "くぅっ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 5))
   (sound 'se 1)
   (branch-reg
    753
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_50bd.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Priss」" 'br)
      (text "うッ、ううっ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "まだまだこれからだ。身体中の服を鞭で剥ぎとってやるんだから！")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "か、勝手にすればいいわ。")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 753 #t))
     (/
      (proc 10)
      (text "「Priss」" 'br)
      (text "うッ、ううっ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 6))
   (sound 'se 1)
   (branch-reg
    754
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_50be.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Priss」" 'br)
      (text "はッ‥‥‥うんッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "何だい今のその声は。まさか、鞭で嬲られて感じてるんじゃないだろうね！")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "そ、そんな訳がないでしょう‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 754 #t))
     (/
      (proc 10)
      (text "「Priss」" 'br)
      (text "はッ‥‥‥うんッ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 7))
   (sound 'se 1)
   (branch-reg
    755
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_50bf.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Priss」" 'br)
      (text "アッ、い、痛ッ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ラテンの血が入っているって言ってたね。その浅黒い肌はそのせいか。なかなか魅力的だよ、他の女とは違ってね！")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "あなたに誉められても嬉しくないわ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 755 #t))
     (/
      (proc 10)
      (text "「Priss」" 'br)
      (text "アッ、い、痛ッ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 8))
   (sound 'se 1)
   (branch-reg
    756
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_50bg.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Priss」" 'br)
      (text "はンッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "今のは歓喜の声と受け取っていいのかね？　何とも色っぽい声を出すじゃないか！")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "そ、そんな事‥‥‥ないわ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 756 #t))
     (/ (proc 10) (text "「Priss」" 'br) (text "はンッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 9))
   (sound 'se 1)
   (branch-reg
    757
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_50bh.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (text "「Priss」" 'br)
      (text "はうッ！　い、痛いッ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "痛いだろうねぇ、肉も何もない所を叩いたんだから！　わたしは、何処を苛めるのが一番効果的かって事を、よく知ってるんだ。")
      (wait)
      (text-reset 14)
      (text "「Priss」" 'br)
      (text "拷問専門の将校って言われる意味が、よくわかったわ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 757 #t))
     (/
      (proc 10)
      (text "「Priss」" 'br)
      (text "はうッ！　い、痛いッ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11)))