(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (nop@)
   (set-reg 980 #t)
   (set-reg 981 #t)
   (set-reg 982 #f)
   (set-reg 983 #f)
   (set-reg 984 #f)
   (set-reg 985 #f)
   (set-reg 986 #f)
   (set-reg 987 #f)
   (set-reg 988 #f)
   (set-reg 989 #f)
   (set-reg 990 #f)
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_51.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (if (</>
        (//
         (? (= P 10))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_10.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 10))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_10v.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 10)))))
        (// (nop@))))
   (exec-mem 256 "E")
   (load-mem "clm¥A1_51.clm" 32768)
   (load-mem "clm¥icon.clm" 20480)
   (mes-load? "mes¥icon_cl.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥icon_c2.mec" 0)
   (mes-load? 0)
   (text-frame 10 312 70 370)
   (exec-mem 256 "A 0")
   (proc 12)
   (define-proc 19
     (<>
      (if (</>
           (//
            (? (>= H 7) (= 983 #f))
            (nop@)
            (set-reg 983 #t)
            (mes-load? "mes¥icon_cl.mec" 0)
            (mes-load? 0)
            (mes-load? "mes¥icon_c2.mec" 0)
            (mes-load? 0))
           (// (nop@))))))
   (define-proc 15
     (<>
      (if (</>
           (//
            (? (>= H 7) (= 770 #f))
            (image-file "gpc¥a1_51e.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 770 #t))
           (// (nop@))))
      (proc 12)))
   (define-proc 13 (<> (text "「Kiyomi」" 'br)))
   (define-proc 14 (<> (text "「Priss」" 'br)))
   (define-proc 16 (<> (wait) (text-reset 14)))
   (proc 10)
   (set-var H 0)
   (text "「Priss」" 'br)
   (text "ううっ、ううぅぅッ！")
   (proc 16)
   (proc 13)
   (text "これでもう、口は利けないだろう。特製の舌を苛めるクリップをプレゼントしてやろうと思ったんだけど‥‥‥")
   (proc 16)
   (proc 13)
   (text "生憎と手元になくってね、ギャグで我慢してもらうよ。他のお仲間レイファやミツコに使った奴でね！")
   (proc 16)
   (proc 14)
   (text "ふゥッ‥‥‥ふぅぅぅッ‥‥‥")
   (proc 16)
   (proc 13)
   (text "そんなに嫌そうな顔するな、他のふたりが気を悪くするじゃない。あの子達の唾液と歯形がついた特別のギャグなんだよ？")
   (proc 16)
   (proc 14)
   (text "‥‥‥‥‥‥‥‥‥")
   (proc 16)
   (proc 13)
   (text "何で歯形がついたと思う？　あまりに苦しくて‥‥‥痛みに耐えかねて、プラスティックのギャグに形が残るほど強く噛締めるのさ。")
   (proc 16)
   (proc 14)
   (text "うぐッ‥‥‥")
   (proc 16)
   (proc 13)
   (text "そんな目にあいたい？　どうしてもって言うなら、そうしてやらない事もないけど、お上品なあんたのお口には合わないかもね。")
   (proc 16)
   (proc 14)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (proc 16)
   (proc 13)
   (text "だんまりか、それじゃ仕方がない。そろそろ始めようかね。")
   (proc 16)
   (proc 13)
   (text "たっぷり可愛がってやるよ！")
   (proc 16)
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (exec-mem 256 "P 5 6 0")
   (loop
    (set-var S 0)
    (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
    (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 5) (= 991 #f) (= 1020 #f) (= Q 5) (= 983 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name4.gpc,GPC")
   (image-mem 1 0 9 88)
   (proc 1)
   (set-var Q 5))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 5) (= 991 #t) (= 1020 #f) (= Q 5) (= 983 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name4.gpc,GPC")
   (image-mem 1 0 52 88)
   (proc 1)
   (set-var Q 5))
 (seg (? (= Z 2) (= Z 3) (= Z 5) (= 991 #f) (= 1020 #f) (>= Q 1) (= 983 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= Z 5) (= 991 #t) (= 1020 #f) (>= Q 1) (= 983 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1) (= 983 #f))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1) (= 983 #f))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (= Z 1) (= 991 #f))
   (proc 0)
   (exec-mem 256 "P 5 71 0")
   (nop@)
   (set-reg 991 #t)
   (exec-mem 256 "P 8 6 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 71 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 71 40))
        (//
         (? (= Y 4))
         (if (</>
              (//
               (? (= 983 #t))
               (exec-mem 9504 "C icon¥tool15.gpc,GPC")
               (image-mem 1 0 71 88))
              (//
               (? (= 983 #f))
               (exec-mem 9504 "C icon¥tool04.gpc,GPC")
               (image-mem 1 0 71 88)))))))
   (load-mem "clm¥icon2.clm" 20480)
   (proc 1))
 (seg (? (= Z 1) (= 991 #t))
   (proc 0)
   (exec-mem 256 "P 5 6 0")
   (nop@)
   (set-reg 991 #f)
   (exec-mem 256 "P 9 71 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 6 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 6 40))
        (//
         (? (= Y 4))
         (if (</>
              (//
               (? (= 983 #t))
               (exec-mem 9504 "C icon¥tool15.gpc,GPC")
               (image-mem 1 0 6 88))
              (//
               (? (= 983 #f))
               (exec-mem 9504 "C icon¥tool04.gpc,GPC")
               (image-mem 1 0 6 88)))))))
   (load-mem "clm¥icon.clm" 20480)
   (proc 1))
 (seg (? (= Z 2) (= 991 #f))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 6 40)
   (if (</>
        (//
         (? (= 983 #t))
         (exec-mem 9504 "C icon¥tool26.gpc,GPC")
         (image-mem 1 0 6 88))
        (// (nop@))))
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #f))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 6 16)
   (if (</>
        (//
         (? (= 983 #t))
         (exec-mem 9504 "C icon¥tool26.gpc,GPC")
         (image-mem 1 0 6 88))
        (// (nop@))))
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Z 2) (= 991 #t))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 71 40)
   (if (</>
        (//
         (? (= 983 #t))
         (exec-mem 9504 "C icon¥tool26.gpc,GPC")
         (image-mem 1 0 71 88))
        (// (nop@))))
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #t))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 71 16)
   (if (</>
        (//
         (? (= 983 #t))
         (exec-mem 9504 "C icon¥tool26.gpc,GPC")
         (image-mem 1 0 71 88))
        (// (nop@))))
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Z 5) (= 991 #f) (= 983 #t))
   (nop@)
   (set-var Y 4)
   (proc 0)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 9504 "C icon¥tool15.gpc,GPC")
   (image-mem 1 0 6 88)
   (exec-mem 18688 5 7 1)
   (proc 1)
   (exec-mem 18688 2 5))
 (seg (? (= Z 5) (= 991 #t) (= 983 #t))
   (nop@)
   (set-var Y 4)
   (proc 0)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 9504 "C icon¥tool15.gpc,GPC")
   (image-mem 1 0 71 88)
   (exec-mem 18688 5 7 1)
   (proc 1)
   (exec-mem 18688 2 5))
 (seg (? (= Y 1) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 13)
      (text "そんなに脅えなくてもいい、わたしは殺したりしないよ。もっとも軍部の、度を越えた変態野郎は何するかわかんないけどね！")
      (proc 16)
      (proc 14)
      (text "‥‥‥‥‥‥‥‥‥")
      (proc 16)
      (proc 13)
      (text "事件が解決して機密を取り戻した後、あいつらはお前達をどうするんだろうね。どのみちただで済むとは思えないねぇ。")
      (proc 16)
      (proc 13)
      (text "嬲りものにされた上に反逆罪で死刑か。さもなきゃ、一生塀の中で公衆便所がわりか‥‥‥わたしの言ってる意味、わかる？")
      (proc 16)
      (proc 14)
      (text "う、ううぅぅ‥‥‥‥‥‥")
      (proc 16)
      (proc 13)
      (text "今さら後悔しても後のまつりさ。")
      (proc 16))
     (/ (proc 14) (text "う、ううぅぅ‥‥‥‥‥‥") (proc 16))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 10))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 13)
      (text "くっくっくっ‥‥‥段々いい顔になってきたじゃない。")
      (proc 16)
      (proc 14)
      (text "んぐッ、ふぐぅぅぅぅ‥‥‥")
      (proc 16)
      (proc 13)
      (text "わたしの拷問がお気に召した？　そうじゃないとは言わせないよ。お前が感じてるのは、わかってるんだから。")
      (proc 16)
      (proc 14)
      (text "‥‥‥‥‥‥‥‥‥")
      (proc 16)
      (proc 13)
      (text "まただんまりか。ギャグを着けてる間はそれでも許すけど、それを外した後は、嫌でも喋ってもらうからね。")
      (proc 16)
      (proc 13)
      (text "覚悟しとくんだね、お前の知ってる事は全部話してもらうよ！")
      (proc 16))
     (/ (proc 13) (text "くっくっくっ‥‥‥段々いい顔になってきたじゃない。") (proc 16))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 11)) (mes-jump "mes¥md_f2_r1.mes"))
 (seg (? (= Y 1) (= S 2))
   (sound 'se 1)
   (branch-reg
    760
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51da.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 14)
      (text "んぐッ‥‥‥んん〜ッ！")
      (proc 16)
      (proc 13)
      (text "オッパイを苛められるのが、そんなに気持ちいいか？　偉そうな口をたたいてもただの女さ。他の女と何も違わないよ。")
      (proc 16)
      (proc 14)
      (text "んっ‥‥‥‥‥‥")
      (proc 16)
      (nop@)
      (set-reg 760 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "んぐッ‥‥‥んん〜ッ！") (proc 16))))
   (proc 11))
 (seg (? (= Y 1) (= S 3))
   (sound 'se 1)
   (branch-reg
    761
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51db.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 14)
      (text "ンッ‥‥‥ンン〜ッ！")
      (proc 16)
      (proc 13)
      (text "ラテンの血が混ざってるってだけあって、いいオッパイしてるね。それに、見かけよりずっと感度がいいみたい。")
      (proc 16)
      (proc 14)
      (text "‥‥‥‥‥‥‥‥‥")
      (proc 16)
      (nop@)
      (set-reg 761 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ンッ‥‥‥ンン〜ッ！") (proc 16))))
   (proc 11))
 (seg (? (= Y 1) (= S 4))
   (sound 'se 1)
   (branch-reg
    762
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51dc.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 14)
      (text "ふぐッ‥‥‥‥‥‥")
      (proc 16)
      (proc 13)
      (text "なんだ全然鍛えてないね。よくもそれで公安部の将校が勤まったもんだ。あんた楽をしすぎてたんじゃないの？")
      (proc 16)
      (proc 14)
      (text "うッ、うう‥‥‥‥‥‥‥‥‥")
      (proc 16)
      (nop@)
      (set-reg 762 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ふぐッ‥‥‥‥‥‥") (proc 16))))
   (proc 11))
 (seg (? (= Y 1) (= S 5))
   (sound 'se 1)
   (branch-reg
    763
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51dd.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 14)
      (text "ングッ、ンン〜ッ！")
      (proc 16)
      (proc 13)
      (text "可哀想に、脂汗をかいて苦しんでるじゃないか。それとも、その汗はあまりに気持ちいいから流してるのかい？")
      (proc 16)
      (proc 14)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (proc 16)
      (nop@)
      (set-reg 763 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ングッ、ンン〜ッ！") (proc 16))))
   (proc 11))
 (seg (? (= Y 1) (= S 6))
   (sound 'se 1)
   (branch-reg
    764
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51de.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 14)
      (text "ふっ‥‥‥ふぅッ！")
      (proc 16)
      (proc 13)
      (text "筋肉のかけらもない足だね。肉感的だとも言えるけど、悪く言えば太り過ぎの脂肪だらけって事になる。")
      (proc 16)
      (proc 14)
      (text "う、うう！　んん〜ッ‥‥‥")
      (proc 16)
      (nop@)
      (set-reg 764 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ふっ‥‥‥ふぅッ！") (proc 16))))
   (proc 11))
 (seg (? (= Y 1) (= S 7))
   (sound 'se 1)
   (branch-reg
    765
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51df.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 14)
      (text "ンン！　ンッ、ンッ‥‥‥")
      (proc 16)
      (proc 13)
      (text "昨日までは公安部の高級将校、でも今はただの牝奴隷だ。嬲られて歓喜の嗚咽を漏らす、薄汚い豚みたいな女さ！")
      (proc 16)
      (proc 14)
      (text "うぐっ、う、うう‥‥‥‥‥‥")
      (proc 16)
      (nop@)
      (set-reg 765 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ンン！　ンッ、ンッ‥‥‥") (proc 16))))
   (proc 11))
 (seg (? (= Y 1) (= S 8))
   (sound 'se 1)
   (branch-reg
    766
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51dg.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 14)
      (text "ふッ‥‥‥ふぐぅぅぅッ！")
      (proc 16)
      (proc 13)
      (text "おやおや‥‥‥ちょっと＊＊＊を叩かれただけでこの有り様だ。" 'br)
      (text "まさか、イッちまったんじゃあるまいね？")
      (proc 16)
      (proc 14)
      (text "ふっ、ふっ、ふっ、ふっ‥‥‥")
      (proc 16)
      (nop@)
      (set-reg 766 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ふッ‥‥‥ふぐぅぅぅッ！") (proc 16))))
   (proc 11))
 (seg (? (= Y 1) (= S 9))
   (sound 'se 1)
   (branch-reg
    767
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51dh.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 14)
      (text "うッ、うぅぅ〜ッ！")
      (proc 16)
      (proc 13)
      (text "普段から鍛えておかないから、余計痛い思いをする事になるのさ！もっとも、自分が拷問されるなんて考える訳ないか。")
      (proc 16)
      (proc 14)
      (text "うっ、うっ、ううッ‥‥‥")
      (proc 16)
      (nop@)
      (set-reg 767 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "うッ、うぅぅ〜ッ！") (proc 16))))
   (proc 11))
 (seg (? (= Y 1) (= S 10))
   (sound 'se 1)
   (branch-reg
    768
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51di.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 14)
      (text "ふぐぅぅ〜ッ！")
      (proc 16)
      (proc 13)
      (text "今のは痛かったね。何しろこのロッドは、最大限の苦痛を与えるように作った特別製だから。しかも骨までは衝撃を与えない。")
      (proc 16)
      (proc 14)
      (text "うっ、ううっ、うう‥‥‥")
      (proc 16)
      (nop@)
      (set-reg 768 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ふぐぅぅ〜ッ！") (proc 16))))
   (proc 11))
 (seg (? (= Y 1) (= S 11))
   (sound 'se 1)
   (branch-reg
    769
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51dj.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 14)
      (text "ンくっ‥‥‥‥‥‥")
      (proc 16)
      (proc 13)
      (text "おや、段々痛みに慣れてきちまったみたいだね。痛くないからって安心しない事だ。牝奴隷に一歩近づいたって事なんだから。")
      (proc 16)
      (proc 14)
      (text "‥‥‥‥‥‥‥‥‥")
      (proc 16)
      (nop@)
      (set-reg 769 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ンくっ‥‥‥‥‥‥") (proc 16))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 13)
      (text "公安部の偉いさんも、こうなっちゃかたなしだね。＊＊＊丸出し" 'br)
      (text "で身体をよじってる。あんたの部下にも見せてやりたいよ！")
      (proc 16)
      (proc 14)
      (text "‥‥‥‥‥‥‥‥‥")
      (proc 16)
      (proc 13)
      (text "プライドも何もあったもんじゃない。一皮剥いたら、ただの女だったって訳ね。もっと見せてごらんよあんたの女の部分をさ！")
      (proc 16)
      (proc 14)
      (text "う、ううぅぅ‥‥‥")
      (proc 16)
      (proc 13)
      (text "ただの移民に過ぎないあんたが、今の地位に登り詰めるには、そのお道具も随分役に立ったんだろうね。")
      (proc 16)
      (proc 13)
      (text "何人の男を咥え込んで、悦ばせてやったんだ！")
      (proc 16)
      (proc 14)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (proc 16))
     (/ (proc 14) (text "う、ううぅぅ‥‥‥") (proc 16))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 10))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 13)
      (text "もういい感じかい？　身体が麻痺して、痛みが快感に変わってきた頃だろう。")
      (proc 16)
      (proc 14)
      (text "うっ‥‥‥‥‥‥")
      (proc 16)
      (proc 13)
      (text "否定しても駄目さ。お前の＊＊＊はうれし涙を流し始めてるじゃ" 'br)
      (text "ないか。身体は正直だからね。")
      (proc 16)
      (proc 14)
      (text "‥‥‥‥‥‥‥‥‥")
      (proc 16)
      (proc 13)
      (text "辛いか？　自分が牝奴隷に変わってくのを感じるのはさ。だけど、その方が幸せなのかもしれないぜ。")
      (proc 16)
      (proc 13)
      (text "他のお前のお仲間を見てると、そう思うね。どいつもこいつも嬲られるのが悦びになっちまってるのさ。")
      (proc 16))
     (/ (proc 13) (text "もういい感じかい？　身体が麻痺して、痛みが快感に変わってきた頃だろう。") (proc 16))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 11)) (mes-jump "mes¥md_f2_r2.mes"))
 (seg (? (= Y 2) (= S 2))
   (sound 'se 1)
   (branch-reg
    760
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51da.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 14)
      (text "ンぐっ！　ん、んん〜ッ！")
      (proc 16)
      (proc 13)
      (text "あんたも思ったほど大した女じゃないね。オッパイを苛められて、声を出すなんてね。他の牝奴隷と同じじゃないか！")
      (proc 16)
      (proc 14)
      (text "うッ、ふぅぅ‥‥‥")
      (proc 16)
      (nop@)
      (set-reg 760 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ンぐっ！　ん、んん〜ッ！") (proc 16))))
   (proc 11))
 (seg (? (= Y 2) (= S 3))
   (sound 'se 1)
   (branch-reg
    761
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51db.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 14)
      (text "ふぅン！　んふッ、んんんッ！")
      (proc 16)
      (proc 13)
      (text "誰が感じていいって言ったんだ、わたしはお前を拷問してるんだ！嬲られて感じるなんて、あんた変態なんじゃない？")
      (proc 16)
      (proc 14)
      (text "く、くぅっ‥‥‥")
      (proc 16)
      (nop@)
      (set-reg 761 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ふぅン！　んふッ、んんんッ！") (proc 16))))
   (proc 11))
 (seg (? (= Y 2) (= S 4))
   (sound 'se 1)
   (branch-reg
    762
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51dc.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 14)
      (text "ふぅぅっ‥‥‥")
      (proc 16)
      (proc 13)
      (text "口からヨダレを垂らして、アソコからはお汁を流してる、自分の姿をよく見てみな。それがお上品な人間のする事なのか？")
      (proc 16)
      (proc 14)
      (text "んぐぅ、んッ！")
      (proc 16)
      (nop@)
      (set-reg 762 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ふぅぅっ‥‥‥") (proc 16))))
   (proc 11))
 (seg (? (= Y 2) (= S 5))
   (sound 'se 1)
   (branch-reg
    763
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51dd.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 14)
      (text "ふぐうッ‥‥‥")
      (proc 16)
      (proc 13)
      (text "どうだい、お腹に鞭を受ける感想は？　人一倍苦痛に弱いお前の事だ。とっくに痛いを通り越して身体が痺れてるんじゃないのか？")
      (proc 16)
      (proc 14)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (proc 16)
      (nop@)
      (set-reg 763 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ふぐうッ‥‥‥") (proc 16))))
   (proc 11))
 (seg (? (= Y 2) (= S 6))
   (sound 'se 1)
   (branch-reg
    764
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51de.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 14)
      (text "ふっ、ふぅぅ〜ッ！")
      (proc 16)
      (proc 13)
      (text "段々＊＊＊に近づいてきたよ、さあどうするんだい？　もっと叩" 'br)
      (text "いて欲しいのか、もう止めにするか。あんたが決めていいんだ。")
      (proc 16)
      (proc 14)
      (text "うっ、うう‥‥‥‥‥‥‥‥‥")
      (proc 16)
      (nop@)
      (set-reg 764 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ふっ、ふぅぅ〜ッ！") (proc 16))))
   (proc 11))
 (seg (? (= Y 2) (= S 7))
   (sound 'se 1)
   (branch-reg
    765
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51df.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 14)
      (text "ン〜ッ！　ンン‥‥‥ンン〜ッ！")
      (proc 16)
      (proc 13)
      (text "それは何だ？　もっと打ってくれって言ってるのか、それとも別の場所を、＊＊＊を苛めて欲しいって合図なの？")
      (proc 16)
      (proc 14)
      (text "ン、ン、ンン〜ッ！")
      (proc 16)
      (nop@)
      (set-reg 765 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ン〜ッ！　ンン‥‥‥ンン〜ッ！") (proc 16))))
   (proc 11))
 (seg (? (= Y 2) (= S 8))
   (sound 'se 1)
   (branch-reg
    766
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51dg.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 14)
      (text "ふッ！　ふァァ‥‥‥ンッ！")
      (proc 16)
      (proc 13)
      (text "ちょっと＊＊＊を嬲られただけで、このざまだ。何が繊細なもん" 'br)
      (text "か。お前はただの淫乱な牝奴隷だよ！")
      (proc 16)
      (proc 14)
      (text "ンッ、ふぅぅぅン‥‥‥")
      (proc 16)
      (nop@)
      (set-reg 766 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "ふッ！　ふァァ‥‥‥ンッ！") (proc 16))))
   (proc 11))
 (seg (? (= Y 2) (= S 9))
   (sound 'se 1)
   (branch-reg
    767
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51dh.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 14)
      (text "んっ、ふ、ん〜ッ！")
      (proc 16)
      (proc 13)
      (text "何て声を出すんだ‥‥‥＊＊＊だけじゃない、お前は何処を苛め" 'br)
      (text "られても感じてしまう、卑しい奴隷じゃないか。")
      (proc 16)
      (proc 14)
      (text "うっ、うっ‥‥‥ううッ！")
      (proc 16)
      (nop@)
      (set-reg 767 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "んっ、ふ、ん〜ッ！") (proc 16))))
   (proc 11))
 (seg (? (= Y 2) (= S 10))
   (sound 'se 1)
   (branch-reg
    768
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51di.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 14)
      (text "うくッ‥‥‥‥‥‥")
      (proc 16)
      (proc 13)
      (text "ここは気持ちよくないのか？　今は痛いだけでも、そのうち気持ちよくなる。お仲間のエリコは、鞭の一発だけでイッてたっけ。")
      (proc 16)
      (proc 14)
      (text "うう‥‥‥‥‥‥")
      (proc 16)
      (nop@)
      (set-reg 768 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "うくッ‥‥‥‥‥‥") (proc 16))))
   (proc 11))
 (seg (? (= Y 2) (= S 11))
   (sound 'se 1)
   (branch-reg
    769
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_51dj.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 14)
      (text "んふッ、ンンッ‥‥‥")
      (proc 16)
      (proc 13)
      (text "あんたの肌は浅黒くて、傷が奇麗に映えないな。面白みが半減するじゃないか。わたしの好みとは程遠いね。")
      (proc 16)
      (proc 14)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (proc 16)
      (nop@)
      (set-reg 769 #t)
      (proc 19))
     (/ (proc 10) (proc 14) (text "んふッ、ンンッ‥‥‥") (proc 16))))
   (proc 11))
 (seg (? (= Y 4) (= S 1) (= 770 #f))
   (proc 10)
   (proc 14)
   (text "うぅ！　うっ、うっ‥‥‥")
   (proc 16)
   (proc 13)
   (text "こいつが何だか知ってるようだね。どこの変態野郎に教わったの？お楽しみの最中に、こいつを使ってたんだろう？")
   (proc 16)
   (proc 14)
   (text "‥‥‥‥‥‥‥‥‥")
   (proc 16)
   (proc 13)
   (text "答えなくてもいいよ、わたしはもうその事を知ってちまったんだ。お前が本当はただの変態女だって事をね！")
   (proc 16)
   (nop@)
   (set-reg 770 #t)
   (proc 11))
 (seg (? (= Y 4) (= S 1) (= 770 #t))
   (proc 10)
   (proc 14)
   (text "うぅ！　うっ、うっ‥‥‥")
   (proc 16)
   (proc 11))
 (seg (? (= Y 4) (>= S 2) (<= S 3) (= 771 #f))
   (proc 10)
   (proc 13)
   (text "さんざ嬲られて火照った身体には、冷たくて気持ちいいだろう？")
   (proc 16)
   (proc 14)
   (text "‥‥‥‥‥‥‥‥‥")
   (proc 16)
   (proc 13)
   (text "否定しないね。それは気持ちいいって事なのかい？")
   (proc 16)
   (proc 14)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (proc 16)
   (nop@)
   (set-reg 771 #t)
   (proc 11))
 (seg (? (= Y 4) (>= S 2) (<= S 3) (= 771 #t))
   (proc 10)
   (proc 14)
   (text "うっ、うう‥‥‥‥‥‥‥‥‥")
   (proc 16)
   (proc 11))
 (seg (? (= Y 4) (= S 12) (= 772 #f))
   (proc 10)
   (nop@)
   (inc-var H 1)
   (proc 13)
   (text "こいつでお前の＊＊＊を検査してやるよ。一体どれくらいの数の" 'br)
   (text "チ○ポを咥え込んだのか、調べてやる！")
   (proc 16)
   (proc 14)
   (text "うっ、うう〜ッ！")
   (proc 16)
   (proc 11)
   (proc 0)
   (exec-mem 256 "G 0 41 269 13 102")
   (image-file "gpc¥a1_51b.gpc")
   (image-mem 1 0)
   (proc 12)
   (proc 10)
   (proc 14)
   (text "うぐッ‥‥‥ううッ！")
   (proc 16)
   (proc 13)
   (text "くっくっくっ、＊＊＊の奥までよく見えるよ‥‥‥")
   (proc 16)
   (proc 13)
   (text "こいつは最高の屈辱だろう？　裸を見られるより、何倍も恥ずかしいだろう。")
   (proc 16)
   (proc 14)
   (text "うっ、うっ‥‥‥ううッ‥‥‥")
   (proc 16)
   (proc 13)
   (text "なるほどね、こりゃ使い込まれてる。ヒダがすり減って何も残ってないみたいだね！")
   (proc 16)
   (proc 14)
   (text "ううッ！　う、んッ、ううッ！")
   (proc 16)
   (proc 13)
   (text "ごちゃごちゃ言うんじゃないよ。いい年して、処女だなんて言いやしないだろう？")
   (proc 16)
   (proc 13)
   (text "お前の＊＊＊は、男を咥えすぎてもう使い物にもならないのさ！")
   (proc 16)
   (proc 14)
   (text "う、うぐぅッ！")
   (proc 16)
   (proc 11)
   (proc 0)
   (proc 5)
   (exec-mem 256 "P 0 41 269")
   (exec-mem 256 "F 0")
   (exec-mem 256 "A 1")
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_51.gpc")
   (image-mem 0 0)
   (branch-reg
    760
    (</> (/) (/ (image-file "gpc¥a1_51da.gpc") (image-mem 1 0))))
   (branch-reg
    761
    (</> (/) (/ (image-file "gpc¥a1_51db.gpc") (image-mem 1 0))))
   (branch-reg
    762
    (</> (/) (/ (image-file "gpc¥a1_51dc.gpc") (image-mem 1 0))))
   (branch-reg
    763
    (</> (/) (/ (image-file "gpc¥a1_51dd.gpc") (image-mem 1 0))))
   (branch-reg
    764
    (</> (/) (/ (image-file "gpc¥a1_51de.gpc") (image-mem 1 0))))
   (branch-reg
    765
    (</> (/) (/ (image-file "gpc¥a1_51df.gpc") (image-mem 1 0))))
   (branch-reg
    766
    (</> (/) (/ (image-file "gpc¥a1_51dg.gpc") (image-mem 1 0))))
   (branch-reg
    767
    (</> (/) (/ (image-file "gpc¥a1_51dh.gpc") (image-mem 1 0))))
   (branch-reg
    768
    (</> (/) (/ (image-file "gpc¥a1_51di.gpc") (image-mem 1 0))))
   (branch-reg
    769
    (</> (/) (/ (image-file "gpc¥a1_51dj.gpc") (image-mem 1 0))))
   (exec-mem 256 "G 0 3 0 38 235")
   (exec-mem 256 "G 1 38 0 30 354")
   (image-file "gpc¥a1_51c.gpc")
   (image-mem 1 0)
   (mes-load? "mes¥bnkcpy3.mec" 0)
   (mes-load? 0)
   (exec-mem 256 "A 0")
   (text-frame 10 312 70 370)
   (proc 12)
   (proc 10)
   (proc 13)
   (text "ほらみろ、ブーツぐらいひと飲みだ。大した＊＊＊だよ！")
   (proc 16)
   (proc 14)
   (text "ふぅッ‥‥‥‥‥‥")
   (proc 16)
   (proc 13)
   (text "汚い汁を出すんじゃないよ！　わたしのブーツが汚れてしまった。全部お前のせいだ、後で舌で掃除するんだよ！")
   (proc 16)
   (proc 14)
   (text "うう‥‥‥‥‥‥")
   (proc 16)
   (proc 13)
   (text "それは承知したって意味なのか？")
   (proc 16)
   (proc 14)
   (text "うっ‥‥‥ううッ！")
   (proc 16)
   (proc 11)
   (proc 0)
   (image-file "gpc¥a1_51e.gpc")
   (exec-mem 256 "P 0 3 0")
   (exec-mem 256 "P 1 38 0")
   (image-mem 1 0)
   (proc 12)
   (proc 6)
   (exec-mem 9504 "C icon¥tool15.gpc,GPC")
   (branch-reg 991 (</> (/ (image-mem 1 0 6 88)) (/ (image-mem 1 0 71 88))))
   (proc 10)
   (proc 13)
   (text "よし、＊＊＊の検査はこれで終りだ。お前がどんな女なのかは、" 'br)
   (text "よくわかったからね。")
   (proc 16)
   (proc 13)
   (text "わたしの検査では、お前は男狂いの色魔だね。")
   (proc 16)
   (proc 14)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (proc 16)
   (nop@)
   (set-reg 772 #t)
   (proc 11))
 (seg (? (= Y 4) (= S 12) (= 772 #t))
   (proc 10)
   (proc 13)
   (text "これ以上ブーツを汚い汁で汚されるのは御免だね。")
   (proc 16)
   (proc 14)
   (text "‥‥‥‥‥‥‥‥‥")
   (proc 16)
   (proc 11))
 (seg*))