(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (proc 5)
  (proc 10)
  (text "「Anna」" 'br)
  (text "これ以上何を喋る必要があるの、もう十分じゃない。キヨミ、私達を手伝って！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "まだ聞くことは、残ってるさ。")
  (wait)
  (text-reset 14)
  (proc 11)
  (proc 0)
  (image-file "gpc¥a1_61a.gpc")
  (image-mem 1 0)
  (proc 12)
  (proc 10)
  (text "「Anna」" 'br)
  (text "くッ！　だ、駄目‥‥‥そこはッ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "拷問のお影で、ここがすっかり潤んでる。こんなになるまで我慢する必要があったのかねぇ？")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "さあ、喋ってもらうよ。残りの機密を、エイプリルとレイファに隠した以外の情報を何処に隠した？")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "それを聞いてどうするの！　私達の仲間にはなってくれないの？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "さあね、そいつは話を全部聞いた後で考えるよ。")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "ああ、そんな！　あなた、軍がやろうとしている事を許すつもり？そんな事が出来る訳がないわ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "黙れ、決めるのはわたしだ。さあ、残りの機密の所在を言うんだ！")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "‥‥‥‥‥‥‥‥‥私達の頭の中よ。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "どういう意味だ、頭の中ってのは、つまり記憶しているって訳か？だったら、他の６人が拷問で白状しない訳がない。")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "違うわ。私達は全員電脳移植を受けているでしょう？　機密はそのチップの中に入ってるのよ。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "加藤がそんな事を言っていたな‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "取り出す方法は、私しか知らないわ。しかもそんな事をしたら私達７人は廃人になってしまう。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "‥‥‥‥‥‥‥‥‥無茶な事をする。")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "命を賭けても軍のやる事を、阻止しなければならなかったのよ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "そのために、自分以外の他の女を犠牲にしても？　狂ってるのは軍じゃなくてアンナ、あんただよ。")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "その事を加藤が知ったら、迷わずあんた達の頭を開いて、チップを取り出すだろうね。後は軍の技研が何とかするだろう。")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "キヨミ！　早くこの無意味な拷問を止めて‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (proc 11)
  ((cmd 203) 5 0)
  (exec-mem 3072 0)
  (exec-mem 18688 3)
  (exec-mem 18688 5 1 0)
  (exec-mem 3968 103)
  (exec-mem 256 "A 0 S 0")
  (exec-mem 256 "G 1 0 0 18 48")
  (exec-mem 4768 0 0 18 6 1 0 0 4480 4480 1 0)
  (menu1 1 8 1 24 (</> (/ (text "　拷問を止める　")) (/ (text "　拷問を続ける　"))))
  (exec-mem 256 "P 1 0 0")
  ((cmd 203) 5 8)
  (if (</>
       (//
        (? (= S 0))
        (proc 10)
        (text "「Kiyomi」" 'br)
        (text "ああ、わかったよ。わたしだってあんな奴等の言いなりになって、可哀想な犠牲者のひとりにされるのは、御免だからね。")
        (wait)
        (text-reset 14)
        (text "「Anna」" 'br)
        (text "キヨミ‥‥‥‥‥‥‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "しかし、これからどうするってんだい？　他の仲間を助けたその後の事は。わたし達はお尋ね者になっちまう。")
        (wait)
        (text-reset 14)
        (text "「Anna」" 'br)
        (text "‥‥‥‥‥‥‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "何も考えてない、なんて言わないでよね。")
        (wait)
        (text-reset 14)
        (text "「Anna」" 'br)
        (text "それは、この縄を解いてくれた後に言うわ‥‥‥‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "わたしの事が信用出来ないっての？　まあ、無理もない。")
        (wait)
        (text-reset 14)
        (text "「Anna」" 'br)
        (text "‥‥‥‥‥‥‥‥‥‥‥‥")
        (wait)
        (text-reset 14)
        (nop@)
        (set-reg 78 #t)
        (proc 11)
        (exec-mem 3072 0)
        (mes-jump "mes¥ME_01.MES"))
       (//
        (? (= S 1))
        (proc 0)
        ((cmd 209) 0 5)
        (image-file "gpc¥a1_62c.gpc")
        (image-mem 0 3)
        ((cmd 209) 1 5)
        (proc 12)
        (proc 10)
        (text "「Kiyomi」" 'br)
        (text "嫌なこった。忘れたの？　あんたはわたしを裏切って、恥をかかせてくれたんだよ。")
        (wait)
        (text-reset 14)
        (text "「Anna」" 'br)
        (text "キヨミ！　そんな事を言っている時じゃないのよ！")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "黙れ、お前は今じゃただの囚人なんだよ。わたしに向かって偉そうな口を聞くんじゃないよ！")
        (wait)
        (text-reset 14)
        (text "「Anna」" 'br)
        (text "ああ‥‥‥‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "今の話を加藤にする前に、わたしからのプレゼントを受け取ってもらうよ。")
        (wait)
        (text-reset 14)
        (text "「Anna」" 'br)
        (text "もうお終いだわ‥‥‥‥‥‥")
        (wait)
        (text-reset 14)
        (text "「Kiyomi」" 'br)
        (text "廃人になる前に、最後のお楽しみって訳さ。わたしのせめてもの慰めだよ。有り難く思うんだね！")
        (wait)
        (text-reset 14)
        (proc 11)
        (exec-mem 3072 0)
        (mes-jump "mes¥md_g03.mes"))))))