(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (nop@)
   (set-reg 980 #t)
   (set-reg 981 #t)
   (set-reg 982 #f)
   (set-reg 983 #f)
   (set-reg 984 #f)
   (set-reg 985 #f)
   (set-reg 986 #f)
   (set-reg 987 #f)
   (set-reg 988 #f)
   (set-reg 989 #f)
   (set-reg 990 #f)
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_61_a.gpc")
   (image-mem 0 3)
   (image-file "gpc¥a1_61_b.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (if (</>
        (//
         (? (= P 13))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_13.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 13))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_13v.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 13)))))
        (// (nop@))))
   (exec-mem 256 "E")
   (load-mem "clm¥A1_61.clm" 32768)
   (load-mem "clm¥icon.clm" 20480)
   (mes-load? "mes¥icon_cl.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥icon_c2.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥md_g2pl1.mec" 4096)
   (text-frame 10 312 70 370)
   (exec-mem 256 "A 0")
   (proc 12)
   (define-proc 19
     (<>
      (if (</>
           (//
            (? (>= H 7) (= 983 #f))
            (nop@)
            (set-reg 983 #t)
            (mes-load? "mes¥icon_cl.mec" 0)
            (mes-load? 0)
            (mes-load? "mes¥icon_c2.mec" 0)
            (mes-load? 0))
           (// (nop@))))))
   (define-proc 15
     (<>
      (if (</>
           (//
            (? (>= H 7) (= 113 #f))
            (image-file "gpc¥a1_61cl.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 113 #t))
           (// (nop@))))
      (proc 12)))
   (define-proc 17 (<> (text "「Kiyomi」" 'br)))
   (define-proc 18 (<> (text "「Anna」" 'br)))
   (proc 10)
   (set-var H 0)
   (sound 'se 1)
   (text "「Anna」" 'br)
   (text "んッ、くッ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3072 0)
   (proc 5)
   (mes-load? "mes¥bnkcpy2.mec" 0)
   (mes-load? 0)
   (exec-mem 29184 0 1 "gpa¥a1_61.dpb" 0)
   (exec-mem
    29184
    1
    1
    "A..........A..........A..........A..........A..........A..........A..........A..........")
   (exec-mem 256 "A 1")
   (image-file "gpc¥a1_61_1.gpc")
   (image-mem 1 0)
   (exec-mem 256 "G 30 59 76 10 68")
   (exec-mem 256 "A 0")
   (exec-mem 256 "P 30 59 76")
   (exec-mem 256 "F 30")
   (exec-mem 29184 2 1 0 0)
   (exec-mem 256 "S 0")
   (exec-mem 256 "A 0")
   (exec-mem 29184 3 1)
   (image-file "gpc¥a1_61_a.gpc")
   (image-mem 0 3)
   (image-file "gpc¥a1_61_b.gpc")
   (image-mem 0 3)
   (proc 12)
   (proc 6)
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "辛いか？　恥ずかしいか！　あんたがわたしにした事に比べれば、これくらい何でもないはずさ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "だからあんたには、最高の屈辱を与えてやる。轡もはめない、縄もそんなにきつくは締めてないはずだよ。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "ど、どういう意味なの‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "喋りたきゃ、勝手に喋れ。床に倒れ込みたいなら勝手にそうしろ。わたしは止めない。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "キヨミ‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "どのみちあんたは、わたしに屈する事になるんだ。でも、それは全てあんた自身の問題、そういう事さ！")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "そんなに‥‥‥そんなに私の事が嫌いになってしまったの？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "当たり前だ。でもね、これだけは感謝してる。わたしはもう、紫岩に溺れる事はないだろう。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたのしてくれた下衆な裏切りのお影で、とびきり冷酷な人間となって生きて行けるだろうからね。")
   (wait)
   (text-reset 14)
   (text "「Anna」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (exec-mem 256 "P 5 6 0")
   (mes-jump "mes¥md_g2_ms.mes")))