(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (proc 10)
  (text "「Kiyomi」" 'br)
  (text "遊びはもうお終いだ、汚物の臭いで鼻が曲がりそうだよ。")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "‥‥‥‥‥‥‥‥‥もう一度、考えてくれないかしら？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "くどいよ！　わたしはあんた達に手を貸すなんて、まっぴら。どうせ情報部に真面目に勤めても、先は知れたもんさ。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "せいぜい大佐どまりがいいとこ、わたしみたいに家柄も後ろ盾もないただの日本人じゃね。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "だけど、もう違う。わたしは支配者階級の仲間入りをするんだよ！悪いけどあんた達には、そのための踏み台になってもらうよ。")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "何も言わないのか？")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "あなたにはがっかりよ、そんな人間だとは思わなかった。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "それじゃ、どんな人間だと思ったって言うんだい！　わたしはこんな人間さ。昔っからね。")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "さあ、一緒に加藤の所に行くんだよ。あん畜生との取り引きに負けたくない、あんたは大切なわたしの切り札だからね！")
  (wait)
  (text-reset 14)
  (text "「Priss」" 'br)
  (text "そうはいかないわ！")
  (wait)
  (text-reset 14)
  (nop@)
  (set-reg 77 #t)
  (proc 11)
  (exec-mem 18688 3)
  (exec-mem 18688 5 1 0)
  (exec-mem 3072 0)
  (exec-mem 9504 "E")
  (exec-mem 256 "I")
  (mes-jump "mes¥ME_01.MES")))