(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (loop
   (set-var S 0)
   (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
   (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 5) (= 991 #f) (= 1020 #f) (= Q 5) (= 983 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name4.gpc,GPC")
   (image-mem 1 0 9 88)
   (proc 1)
   (set-var Q 5))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 5) (= 991 #t) (= 1020 #f) (= Q 5) (= 983 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name4.gpc,GPC")
   (image-mem 1 0 52 88)
   (proc 1)
   (set-var Q 5))
 (seg (? (= Z 2) (= Z 3) (= Z 5) (= 991 #f) (= 1020 #f) (>= Q 1) (= 983 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= Z 5) (= 991 #t) (= 1020 #f) (>= Q 1) (= 983 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1) (= 983 #f))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1) (= 983 #f))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (= Z 1)) (mes-load? 4096))
 (seg (? (= Z 2)) (mes-load? 4096))
 (seg (? (= Z 3)) (mes-load? 4096))
 (seg (? (= Z 5)) (mes-load? 4096))
 (seg (? (= Y 1) (= S 1) (<= H 6))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 17)
      (text "わたしは今、すごく空しい気分さ。自分の愛人をとびきりキツイ拷問にかけるとなりゃ、もっと興奮するかと思ったがね。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "だから、ここから先は遊びとは別の物。わたしが持っているテクを駆使して、あんたを苛め抜いてやる。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "ああ、キヨミ‥‥‥お願い！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "今さら何を言っても無駄だよ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "それは‥‥‥違うわ、誤解なのよ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "先に始めたのはあんたの方、そいつを忘れてもらっちゃ困る。だからね、このクソ仕事を終わらせる協力をしてもらうよ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (proc 17)
      (text "わたしは今、すごく空しい気分さ。自分の愛人をとびきりキツイ拷問にかけるとなりゃ、もっと興奮するかと思ったがね。")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 11))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 18)
      (text "ハァ、ハァ、ハァ、ハァ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "少しはこたえたかい。何もかも喋っちまう気になったか？")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "おっと、わたしは口出ししない約束だっけ。あんたが喋りたくなったんなら、喋ればいい。嫌ならもっと苦しんでもらう。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "まだ足りないって訳ね、わたしは何時間でも付き合ってあげるよ。そのうち、口も滑らかになろうってもんさ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "そんな目で見ても無駄だよ！　わたしはあんたに同情なんかしてやらない、絶対にしてやるもんか。")
      (wait)
      (text-reset 14))
     (/
      (proc 17)
      (text "そんな目で見ても無駄だよ！　わたしはあんたに同情なんかしてやらない、絶対にしてやるもんか。")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 12) (= 117 #f))
   (proc 10)
   (proc 18)
   (text "も、もう十分だわ、お願い‥‥‥もう止めて！")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "それじゃ、喋る気になったんだな？　なら、勝手にどうぞ。わたしはここで聞いてる。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "なるほど、自分からは言いにくいって訳？　何を喋ればいいのか、よくわからないと。それじゃわたしが聞いてやる。")
   (wait)
   (text-reset 14)
   (proc 11)
   (proc 0)
   (if (</> (// (? (= 116 #t)) (exec-mem 256 "P 19 24 175")) (// (nop@))))
   (proc 5)
   (mes-load? "mes¥bnkcpy2.mec" 0)
   (mes-load? 0)
   (exec-mem 256 "A 0")
   (exec-mem 256 "G 0 24 175 9 87")
   (image-file "gpc¥a1_61a.gpc")
   (image-mem 1 0)
   (proc 10)
   (proc 18)
   (text "アッ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "あんたはどうして軍のデータベースをハッキングした？")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "何が不満なのか知らないけど、あんたはこの街で手に入れられる、大抵の物を持ってたはずだ。この上なにが欲しかったのさ。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "何も‥‥‥むしろ私は、この街の人間全員を救ったのよ。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "またその話か。ミツコも同じような事を言ってたね。それにプリスもだ。軍部が市民全員をポッドモッドしようとしてたって事？")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "軍は今では瀕死の状態よ、暴走を始めてるわ。彼等は戦争に負ける訳にいかない。機構＝システムはその為の物なのよ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "まず手始めに兵士に電脳移植をして、無敵の超人兵を造ろうとしているわ。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "いけ好かない野郎どもでも、味方が勝つのは悪くない。兵士達には気の毒だけど。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "‥‥‥‥‥‥次は一般市民よ。軍とサカタ・ネオテクが創ったシステムでは、怒りや不満の感情が抑えられるわ。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "つまり、街の人間全員が、軍の言いなりになるって訳ね。確かにあんな下衆野郎共の言いなりになるのは面白くないけど‥‥‥")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "そんな簡単な問題じゃないわ。次に軍がやろうとしてる事は、兵士の製造よ。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "製造だって？　アンドロイドでも作ろうってのかい。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "これは作り話じゃないのよ‥‥‥軍部の考えは、遺伝子操作による超兵士の製作と、人工的な妊娠・育児プログラムなのよ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "つまり、私達は軍が創った人工受精卵を移植させられ、超兵士製造の工場になるって訳なのよ！")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "私達ってのは、わたしの事も含めて？")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "もちろんよ、彼等には勝つために手段を選んでいる余裕はないわ。妊娠可能な年齢に達した、全ての女性が対象よ。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "はん、何処の誰のとも知れないガキを孕むなんて、ゾッとしない話だね。嫌なこった。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "私達は、そんな計画を許す事なんて出来なかったのよ。女性を物のように扱うなんて、許せないわ！")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 117 #t)
   (proc 11)
   (exec-mem 3072 0)
   (proc 0)
   (mes-load? "mes¥bnkcpy3.mec" 0)
   (mes-load? 0)
   (exec-mem 256 "A 0")
   (proc 12)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (proc 6)
   (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
   (exec-mem 3072 1))
 (seg (? (= Y 1) (= S 1) (>= H 12) (= 117 #t)) (mes-jump "mes¥md_g2_r1.mes"))
 (seg (? (= Y 1) (= S 2))
   (sound 'se 1)
   (branch-reg
    102
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61ca.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "あッ！　くっ、くぅぅぅッ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "痛いか？　これ以上痛い目をみる前に白状するのも自由なら、無駄な努力をするのもあんたの勝手、好きにするがいいさ。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 102 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あッ！　くっ、くぅぅぅッ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 3))
   (sound 'se 1)
   (branch-reg
    103
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (branch-reg
       116
       (</>
        (/ (nop@) (image-file "gpc¥a1_61cb.gpc") (image-mem 1 0))
        (/
         (exec-mem 256 "P 19 24 175")
         (image-file "gpc¥a1_61cb.gpc")
         (image-mem 1 0)
         (image-file "gpc¥a1_61b.gpc")
         (image-mem 1 0))))
      (proc 15)
      (proc 10)
      (proc 18)
      (text "あうッ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "ほら！　ぼんやりしてると、どんどん＊＊＊に近くなってくよ！" 'br)
      (text "大切なアソコを傷つけたくないなら、早く決めちまいな。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "キヨミ‥‥‥もう止めてぇ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 103 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あうッ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 4))
   (sound 'se 1)
   (branch-reg
    104
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61cc.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "はッ、はぅぅぅン！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "太股の内側を叩かれるのは、そんなに気持ちいいのかい、＊＊＊" 'br)
      (text "の近くを苛められるのはさ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "つ、強すぎるわ‥‥‥どうしてこんな事をするの‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 104 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "はッ、はぅぅぅン！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 5))
   (sound 'se 1)
   (branch-reg
    105
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61cd.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "アッ、いっ‥‥‥痛いわッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "だったら、我慢せずに床に倒れちまいな。わたしの靴でも舐めてるんだね。そう出来るように縛ってやったはずだよ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "だ、誰がそんな事を‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 105 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "アッ、いっ‥‥‥痛いわッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 6))
   (sound 'se 1)
   (branch-reg
    106
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61ce.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "あふッ‥‥‥も、もう止めて！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "それはどういう意味？　意地を張るのを止めて、何でも知ってる事を話すって事なんだろうね。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "ち、違うわ‥‥‥絶対に違うわ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 106 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あふッ‥‥‥も、もう止めて！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 7))
   (sound 'se 1)
   (branch-reg
    107
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61cf.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "くぅぅぅッ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "自慢の足に傷が付いちまった。それじゃ、もう短いスカートは履けないね。もっとも、そんな機会は二度とないだろうけどさ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "くっ、くぅッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 107 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "くぅぅぅッ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 8))
   (sound 'se 1)
   (branch-reg
    108
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61cg.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "アッ、痛ァァッ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "他の６人は、あんたよりずっと酷いめにあってるんだ。これしきの事がなんだってんだい。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "も、もう耐えられない、死んでしまうわ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 108 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "アッ、痛ァァッ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 9))
   (sound 'se 1)
   (branch-reg
    109
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61ch.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "ひッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "狙いが外れちまった。あんまり小さなオッパイなんでね。白人女の割に、貧相なオッパイしてるからさ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 109 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ひッ‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 10))
   (sound 'se 1)
   (branch-reg
    110
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61ci.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "はッ、はァァァァン！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "オッパイ叩かれて、いい気持ちになったのか。まさかイッちまった訳じゃないだろうね！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "う、ううっ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 110 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "はッ、はァァァァン！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 11))
   (sound 'se 1)
   (branch-reg
    111
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61cj.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "はうン！　そ、そこは駄目‥‥‥オッパイは許して！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "お尻の穴と＊＊＊以外にも、感じる所があったとはね。ご希望な" 'br)
      (text "ら、いくらでも激しくやってやるよ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "そんなの嫌‥‥‥嫌よ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 111 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 18)
      (text "はうン！　そ、そこは駄目‥‥‥オッパイは許して！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 12))
   (sound 'se 1)
   (branch-reg
    112
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61ck.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "ひぃッ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "こいつは遊びじゃないんだ、必要とあらばその奇麗な顔を二目と見られないご面相にしちまうかもよ。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 112 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ひぃッ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 6))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 17)
      (text "加藤がその姿を見たら、何と思うかね。情報部内の目の上のコブ、出世を阻む、数少ない障害のひとつだったあんたをさ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "い、言わないで‥‥‥あの男の話は聞きたくないわ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "向こうはわたしの報告を聞きたがるだろうよ。あんたがどんな無様な姿で、わたしの拷問にヒイヒイ悲鳴を上げたかってね。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "汚いわ、そんなやり方は酷すぎる‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "だったら何とか仕返しをしてごらんよ。何も出来やしないんだよ、あんたにはもう、どんな力も有りはしないんだから。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (proc 17)
      (text "加藤がその姿を見たら、何と思うかね。情報部内の目の上のコブ、出世を阻む、数少ない障害のひとつだったあんたをさ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 11))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 17)
      (text "わたしは、あんた達を見てて不思議で仕方ない。どうせいつかは白状する事になるのに、何を我慢する必要がある？")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "仲間の事を思ってか？　あんたの仲間は、雁首そろえて牢の中だ。とっくの昔に仲間を売って、楽になっちまったよ。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "白状するも私の勝手って言ったじゃない、余計な事は言わないで！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "いいけどね、どうせもう限界だろう？")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/ (proc 18) (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 12) (= 117 #f))
   (proc 10)
   (proc 18)
   (text "も、もう十分だわ、お願い‥‥‥もう止めて！")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "それじゃ、喋る気になったんだな？　なら、勝手にどうぞ。わたしはここで聞いてる。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "なるほど、自分からは言いにくいって訳？　何を喋ればいいのか、よくわからないと。それじゃわたしが聞いてやる。")
   (wait)
   (text-reset 14)
   (proc 11)
   (proc 0)
   (if (</> (// (? (= 116 #t)) (exec-mem 256 "P 19 24 175")) (// (nop@))))
   (proc 5)
   (mes-load? "mes¥bnkcpy2.mec" 0)
   (mes-load? 0)
   (exec-mem 256 "A 0")
   (exec-mem 256 "G 0 24 175 9 87")
   (image-file "gpc¥a1_61a.gpc")
   (image-mem 1 0)
   (proc 10)
   (proc 18)
   (text "アッ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "あんたはどうして軍のデータベースをハッキングした？")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "何が不満なのか知らないけど、あんたはこの街で手に入れられる、大抵の物を持ってたはずだ。この上なにが欲しかったのさ。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "何も‥‥‥むしろ私は、この街の人間全員を救ったのよ。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "またその話か。ミツコも同じような事を言ってたね。それにプリスもだ。軍部が市民全員をポッドモッドしようとしてたって事？")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "軍は今では瀕死の状態よ、暴走を始めてるわ。彼等は戦争に負ける訳にいかない。機構＝システムはその為の物なのよ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "まず手始めに兵士に電脳移植をして、無敵の超人兵を造ろうとしているわ。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "いけ好かない野郎どもでも、味方が勝つのは悪くない。兵士達には気の毒だけど。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "‥‥‥‥‥‥次は一般市民よ。軍とサカタ・ネオテクが創ったシステムでは、怒りや不満の感情が抑えられるわ。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "つまり、街の人間全員が、軍の言いなりになるって訳ね。確かにあんな下衆野郎共の言いなりになるのは、面白くないけど‥‥‥")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "そんな簡単な問題じゃないわ。次に軍がやろうとしてる事は、兵士の製造よ。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "製造だって？　アンドロイドでも作ろうってのかい。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "これは作り話じゃないのよ‥‥‥軍部の考えは、遺伝子操作による超兵士の製造と、人工的な妊娠・育児プログラムなのよ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "つまり、私達は軍が創った人工受精卵を移植させられ、超兵士製造の工場になるという訳なのよ！")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "私達ってのは、わたしの事も含めて？")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "もちろんよ、彼等には勝つために手段を選んでいる余裕はないわ。妊娠可能な年齢に達した、全ての女性が対象よ。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "はん、何処の誰のとも知れないガキを孕むなんて、ゾッとしない話だね。嫌なこった。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "私達は、そんな計画を許す事なんて出来なかったのよ。女性を物のように扱うなんて、許せないわ！")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 117 #t)
   (proc 11)
   (exec-mem 3072 0)
   (proc 0)
   (mes-load? "mes¥bnkcpy3.mec" 0)
   (mes-load? 0)
   (exec-mem 256 "A 0")
   (proc 12)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (proc 6)
   (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
   (exec-mem 3072 1))
 (seg (? (= Y 2) (= S 1) (>= H 12) (= 117 #t)) (mes-jump "mes¥md_g2_r2.mes"))
 (seg (? (= Y 2) (= S 2))
   (sound 'se 1)
   (branch-reg
    102
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61ca.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "はうッ！　あ、熱い‥‥‥熱いわ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "鞭が熱い訳じゃない、熱いのはあんたの身体さ。鞭で嬲られてるうちに、感じてしまったんだよ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "ああ、そんな事が‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 102 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 18)
      (text "はうッ！　あ、熱い‥‥‥熱いわ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 3))
   (sound 'se 1)
   (branch-reg
    103
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (branch-reg
       116
       (</>
        (/ (nop@) (image-file "gpc¥a1_61cb.gpc") (image-mem 1 0))
        (/
         (exec-mem 256 "P 19 24 175")
         (image-file "gpc¥a1_61cb.gpc")
         (image-mem 1 0)
         (image-file "gpc¥a1_61b.gpc")
         (image-mem 1 0))))
      (proc 15)
      (proc 10)
      (proc 18)
      (text "くぅぅぅッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "死んじまいそうな声出して、まだ意地を張るつもりかい。あんたが頑張っても、何にもいい事ないのにさ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 103 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "くぅぅぅッ‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 4))
   (sound 'se 1)
   (branch-reg
    104
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61cc.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "あふッ！　ひぃっ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "＊＊＊が潤んでるじゃないか、あんたがそんなに夢中になる姿を" 'br)
      (text "見るのは久しぶりだ。そんなに鞭の味が気に入ったの？")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "だ、誰がっ！　そんな事‥‥‥ある訳がないわ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 104 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あふッ！　ひぃっ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 5))
   (sound 'se 1)
   (branch-reg
    105
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61cd.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "あっ、あうぅぅ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "まるでＭ女だね、鞭を食らって悦ぶなんてさ。そんなに好きなら、ずっと打ち続けてやるよ。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 105 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あっ、あうぅぅ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 6))
   (sound 'se 1)
   (branch-reg
    106
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61ce.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "くぅっ‥‥‥い、痛ッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "あとどれくらい我慢してられるかね‥‥‥楽しみだよ。わたしを裏切った女には、たっぷり苦痛を味わってほしいからね！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "そ、そんな‥‥‥ああ、キヨミ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 106 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "くぅっ‥‥‥い、痛ッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 7))
   (sound 'se 1)
   (branch-reg
    107
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61cf.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "は、はンッ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "先刻までの手加減してた鞭とは、全然ちがうだろう！　痛いはずさ本気でやってるんだからね。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "酷いわ、こんな事をしなくてもいいじゃない‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 107 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "は、はンッ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 8))
   (sound 'se 1)
   (branch-reg
    108
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61cg.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "んぐッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "ほお、頑張るじゃない。座ってるだけで死にそうになってるあんたがそこまで我慢するとはね‥‥‥")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "ぜ、絶対に何も喋らないわ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 108 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "んぐッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 9))
   (sound 'se 1)
   (branch-reg
    109
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61ch.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "アッ‥‥‥だ、駄目ッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "じっとしてないと、オッパイを切り落としちまうよ。わたしにそれくらいの事が出来ないなんて、思ってないだろうね？")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 109 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "アッ‥‥‥だ、駄目ッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 10))
   (sound 'se 1)
   (branch-reg
    110
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61ci.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "はッ、はぅぅ〜ン！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "もう時間の問題だね、あんたが口を割るのもさ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "そ、そんな事ない、そんな事ないわよ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 110 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "はッ、はぅぅ〜ン！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 11))
   (sound 'se 1)
   (branch-reg
    111
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61cj.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "ひィィィッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "動くから手元が狂っちまったじゃない。乳首を削ぎ落としてやろうと思ってたのにさ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "そ、そんな‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 111 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ひィィィッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 12))
   (sound 'se 1)
   (branch-reg
    112
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_61ck.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "いっ、嫌ッ！　顔は嫌よ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "さてね、果たしていつまでその美貌を守れるかな。わたしがその気になれば、目茶苦茶にする事だって出来るんだから。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 112 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "いっ、嫌ッ！　顔は嫌よ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 4) (= S 1) (= 114 #f))
   (proc 10)
   (proc 18)
   (text "ンッ‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "そんな嫌そうな顔をしなさんな。こいつであんたのお仲間の身体を調べてやったんだ、奥の方までね‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "あの子達、若くて中の方までピンク色だったっけ。よっぽど恥ずかしかったんだろうね、死んじまいそうな顔してたよ！")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "ど‥‥‥どうしてそんな事が出来るの‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "忘れるんじゃないよ、全部あんたの命令でやったのさ。今までに何人の人間を拷問したと思う？")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 114 #t)
   (proc 11))
 (seg (? (= Y 4) (= S 1) (= 114 #t))
   (proc 10)
   (proc 18)
   (text "ンッ‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11))
 (seg (? (= Y 4) (>= S 10) (<= S 11) (= 115 #f))
   (proc 10)
   (proc 18)
   (text "あッ‥‥‥つ、冷たい‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "これで乳首を苛めてやろうか、結構いい感じかもしれない。クランプで締付けるみたいなものさ。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "嫌よ、そんなのはお断りだわ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "それは残念、なかなか楽しそうだったんだけど。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 115 #t)
   (proc 11))
 (seg (? (= Y 4) (>= S 10) (<= S 11) (= 115 #t))
   (proc 10)
   (proc 18)
   (text "あッ‥‥‥つ、冷たい‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11))
 (seg (? (= Y 4) (= S 13) (= 116 #f))
   (nop@)
   (inc-var H 1)
   (proc 0)
   (exec-mem 256 "G 19 24 175 9 87")
   (image-file "gpc¥a1_61b.gpc")
   (image-mem 1 0)
   (proc 12)
   (wait)
   (proc 10)
   (proc 18)
   (text "アッ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "さすがに他の小便臭い小娘とは違って、あっさり根元まで飲み込んでしまうね。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "嫌ァ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "わたしにペニスがあれば、この＊＊＊をたっぷり味わえたのに。" 'br)
   (text "もう何年も使っちゃいないんだろう？")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "ポッドモッドでも、ここはピンク色してる訳だ。ロシアに居た頃もそれ程遊んでた訳じゃないみたい。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "も、もう嫌ッ‥‥‥早く抜いて！")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "ずっと入れっぱなしにしといてやる。ひょっとしたら、加藤が部屋に入って来るかもね。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "ずっと目の上のコブだった、あんたの＊＊＊を見たら、あいつは" 'br)
   (text "何て言うだろうね！")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "嫌よ‥‥‥もう許して‥‥‥")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 116 #t)
   (proc 11))
 (seg (? (= Y 4) (= S 13) (= 116 #t))
   (proc 10)
   (branch-reg
    117
    (</>
     (/
      (proc 17)
      (text "こいつは刺したままにしといてやる。いつでもあんたのピンク色の＊＊＊がよく見えるようにね！")
      (wait)
      (text-reset 14))
     (/
      (proc 17)
      (text "これだけグチョグチョになってちゃ、こんな物じゃ細すぎて物足りないだろう、わたしの指の方がましってものさ。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "もう許して‥‥‥話すわ、何でも話すから‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11)))