(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (nop@)
   (set-reg 980 #t)
   (set-reg 981 #t)
   (set-reg 982 #f)
   (set-reg 983 #f)
   (set-reg 984 #f)
   (set-reg 985 #f)
   (set-reg 986 #f)
   (set-reg 987 #f)
   (set-reg 988 #f)
   (set-reg 989 #f)
   (set-reg 990 #f)
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_62.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (exec-mem 256 "E")
   (load-mem "clm¥A1_62.clm" 32768)
   (load-mem "clm¥icon.clm" 20480)
   (mes-load? "mes¥icon_cl.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥icon_c2.mec" 0)
   (mes-load? 0)
   (text-frame 10 312 70 370)
   (exec-mem 256 "A 0")
   (proc 12)
   (define-proc 19
     (<>
      (if (</>
           (//
            (? (>= H 8) (= 990 #f))
            (nop@)
            (set-reg 990 #t)
            (mes-load? "mes¥icon_cl.mec" 0)
            (mes-load? 0)
            (mes-load? "mes¥icon_c2.mec" 0)
            (mes-load? 0))
           (// (nop@))))))
   (define-proc 17 (<> (text "「Kiyomi」" 'br)))
   (define-proc 18 (<> (text "「Anna」" 'br)))
   (define-proc 15
     (<>
      (if (</>
           (//
            (? (>= H 7) (= 119 #f))
            (image-file "gpc¥a1_62ba.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 119 #t))
           (// (nop@))))
      (proc 12)))
   (proc 10)
   (set-var H 0)
   (proc 18)
   (text "ふッ、ふぅぅぅ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "くっくっ、なんて恥ずかしい格好なんだ！　＊＊＊どころか、尻" 'br)
   (text "の穴まで丸見えじゃないか。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "いっ、嫌ァ！　見ないで‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "見るなって言われても、こう目の前にあるとね。嫌でも目に入ってしまうよ、仕方ないだろう？")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "これから、あんたの大好きなお尻を苛めてやるからね。たっぷりと恥ずかしい思いを味あわせてやる。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "キヨミ‥‥‥お願い、考え直して！")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "嫌なこった。誰があんた達なんかに協力するもんか。もう引き返せないんだ、何を言ってもね。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "キヨミ‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (exec-mem 256 "P 5 6 0")
   (loop
    (set-var S 0)
    (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
    (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 12) (= 991 #f) (= 1020 #f) (= Q 12) (= 990 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name11.gpc,GPC")
   (image-mem 1 0 9 256)
   (proc 1)
   (set-var Q 12))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 12) (= 991 #t) (= 1020 #f) (= Q 12) (= 990 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name11.gpc,GPC")
   (image-mem 1 0 52 256)
   (proc 1)
   (set-var Q 12))
 (seg (? (= Z 2) (= Z 3) (= Z 12) (= 991 #f) (= 1020 #f) (>= Q 1) (= 990 #t))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= Z 12) (= 991 #t) (= 1020 #f) (>= Q 1) (= 990 #t))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1) (= 990 #f))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1) (= 990 #f))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (= Z 1) (= 991 #f))
   (proc 0)
   (exec-mem 256 "P 5 71 0")
   (nop@)
   (set-reg 991 #t)
   (exec-mem 256 "P 8 6 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 71 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 71 40))
        (//
         (? (= Y 11))
         (if (</>
              (//
               (? (= 990 #t))
               (exec-mem 9504 "C icon¥tool22.gpc,GPC")
               (image-mem 1 0 71 256))
              (//
               (? (= 990 #f))
               (exec-mem 9504 "C icon¥tool11.gpc,GPC")
               (image-mem 1 0 71 256)))))))
   (load-mem "clm¥icon2.clm" 20480)
   (proc 1))
 (seg (? (= Z 1) (= 991 #t))
   (proc 0)
   (exec-mem 256 "P 5 6 0")
   (nop@)
   (set-reg 991 #f)
   (exec-mem 256 "P 9 71 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 6 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 6 40))
        (//
         (? (= Y 11))
         (if (</>
              (//
               (? (= 990 #t))
               (exec-mem 9504 "C icon¥tool22.gpc,GPC")
               (image-mem 1 0 6 256))
              (//
               (? (= 990 #f))
               (exec-mem 9504 "C icon¥tool11.gpc,GPC")
               (image-mem 1 0 6 256)))))))
   (load-mem "clm¥icon.clm" 20480)
   (proc 1))
 (seg (? (= Z 2) (= 991 #f))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 6 40)
   (if (</>
        (//
         (? (= 990 #t))
         (exec-mem 9504 "C icon¥tool33.gpc,GPC")
         (image-mem 1 0 6 256))
        (// (nop@))))
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #f))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 6 16)
   (if (</>
        (//
         (? (= 990 #t))
         (exec-mem 9504 "C icon¥tool33.gpc,GPC")
         (image-mem 1 0 6 256))
        (// (nop@))))
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Z 2) (= 991 #t))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 71 40)
   (if (</>
        (//
         (? (= 990 #t))
         (exec-mem 9504 "C icon¥tool33.gpc,GPC")
         (image-mem 1 0 71 256))
        (// (nop@))))
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #t))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 71 16)
   (if (</>
        (//
         (? (= 990 #t))
         (exec-mem 9504 "C icon¥tool33.gpc,GPC")
         (image-mem 1 0 71 256))
        (// (nop@))))
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Z 12) (= 991 #f) (= 990 #t))
   (nop@)
   (set-var Y 11)
   (proc 0)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 9504 "C icon¥tool22.gpc,GPC")
   (image-mem 1 0 6 256)
   (exec-mem 18688 5 21 1)
   (proc 1)
   (exec-mem 18688 2 12))
 (seg (? (= Z 12) (= 991 #t) (= 990 #t))
   (nop@)
   (set-var Y 11)
   (proc 0)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 9504 "C icon¥tool22.gpc,GPC")
   (image-mem 1 0 71 256)
   (exec-mem 18688 5 21 1)
   (proc 1)
   (exec-mem 18688 2 12))
 (seg (? (= Y 1) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 18)
      (text "お、お願いよ‥‥‥考え直して頂戴！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "駄目だね、絶対に。この国を見捨ててどうするんだよ。わたしには他に行くあてがある訳じゃないんだ。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "こうなりゃ、加藤と心中だね。あんた達から機密を取り返せば、奴の軍部での株も上がる。")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "奴に取り入って、わたしも日本を支配する少数の特権階級のひとりになるさ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "キヨミ、あなた馬鹿よ。そんな事が出来る訳ないじゃない！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "黙れ！　あんたと他の６人は、頭の中をかき回されて廃人になっちまえばいいのさ。わたしを謀った罰だ！")
      (wait)
      (text-reset 14))
     (/ (proc 18) (text "お、お願いよ‥‥‥考え直して頂戴！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 10))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 17)
      (text "何だその有様は。＊＊＊をグチュグチュにして、腰を振ってやが" 'br)
      (text "るじゃないか！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "善人ぶって、軍の計画が云々なんてぬかしといて、結局のところ、あんたもただの牝豚だよ。")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "まったく‥‥‥笑わせてくれるよ。自分のその情けない姿をよく見てみなってんだ。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "どうして自棄になってるの？　あなたこそ、自分の姿をよく見てみなさい‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "うるさい！　お前はただの牝豚だ。わたしに意見するなんて、絶対に許さないよ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (proc 17)
      (text "善人ぶって、軍の計画が云々なんてぬかしといて、結局のところ、あんたもただの牝豚だよ。")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 11)) (mes-jump "mes¥md_g3_r1.mes"))
 (seg (? (= Y 1) (= S 2))
   (sound 'se 1)
   (branch-reg
    120
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_62bb.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (proc 18)
      (text "アッ‥‥‥アアァァン！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "ちょっと強くやり過ぎたかね、かなり痛そうな声だったねぇ‥‥‥まあ、痛みを感じられるのも少しの間だ、よく味わいな！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "くぅっ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 120 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "アッ‥‥‥アアァァン！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 3))
   (sound 'se 1)
   (branch-reg
    121
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62bc.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "ンッ、くぅぅ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "もう手加減はなしだ、身体中に奴隷の烙印を押してやる。一生消えない印をね。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "キヨミ‥‥‥お願い、考え直して‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 121 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ンッ、くぅぅ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 4))
   (sound 'se 1)
   (branch-reg
    122
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62bd.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "ハッ、ハァァァン！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "なんて声だ‥‥‥うかうかしてると、尻の穴と＊＊＊が潰されち" 'br)
      (text "まうよ。それでもいいのかい！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "す、好きにすればいいわ！　どうせ私は‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 122 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ハッ、ハァァァン！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 5))
   (sound 'se 1)
   (branch-reg
    123
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62be.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "ヒィィィィッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "その声が聞きたかったんだよ。いつもお高くとまりやがって、指先ひとつでわたしを好きに動かしてた、あんたのその声が！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "も、もう死んでしまうわ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 123 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ヒィィィィッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 6))
   (sound 'se 1)
   (branch-reg
    124
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62bf.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "あふッ！　も、もう許して‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "誰が許すもんか。裏切りの代償ってのは安かないんだよ。殺されないだけマシって思うんだね！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "し、死んだ方がましだわ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 124 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あふッ！　も、もう許して‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 7))
   (sound 'se 1)
   (branch-reg
    125
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62bg.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "アウッ！　ヒィィィィン！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "もっと鳴くんだ！　大きな声でね！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "ハァ、ハァ、ハァ、ハァ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 125 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "アウッ！　ヒィィィィン！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 8))
   (sound 'se 1)
   (branch-reg
    126
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62bh.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "アッ、アァァァ〜ン！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "＊＊＊は加藤のために残しといてやろう。あんたの大好きなあの" 'br)
      (text "男のためにね！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "そ、そんなッ！　そんなの嫌ァ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 126 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "アッ、アァァァ〜ン！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 9))
   (sound 'se 1)
   (branch-reg
    127
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62bi.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "ううッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "くっくっ、もっと苦しみな。死んだ方がマシだって思ってるだろ？ところがそう簡単には殺してやらないんだ。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "酷いわ、あなたは鬼よ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 127 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ううッ‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 10))
   (sound 'se 1)
   (branch-reg
    128
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62bj.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "くぅンッ！　も、もう止めて‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "はい、そうですかって止められる訳ゃないだろ！　あんたはわたしをはめて殺そうとしたんだよ、こんなもんで済ます訳にいくか。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "そ、そんなァ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 128 #t)
      (proc 19))
     (/
      (proc 10)
      (proc 18)
      (text "くぅンッ！　も、もう止めて‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 11))
   (sound 'se 1)
   (branch-reg
    129
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62bk.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "あくぅ！　あ、足は‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "せいぜい痛みを楽しんどくんだね。もうじきあんたは、痛みさえ感じられなくなっちまうんだからさ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 129 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あくぅ！　あ、足は‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 17)
      (text "軍部に逆らうなんて、馬鹿な事をしたもんだよ。アマチュアのあんた達に何とか出来るなんて思ってたのか？")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "一体何様のつもりなんだ？　英雄にでもなりたかったってのかい。そんな馬鹿な人間には見えなかったけどね。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "だから日本人て嫌い。徹底的な事なかれ主義で、権力にはからきし弱いんだから。")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "何とでも言いな、どうせすぐに廃人同様にされちまうんだからさ。せめてもの慰めに、精一杯楽しむんだね！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "どちらが正しかったのか、そのうちわかるわ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "そん時にゃ、もうあんたは居ない。少なくとも、今のままって事は有り得ないんだろ？")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (proc 17)
      (text "アンナ、軍部に逆らうなんて‥‥‥馬鹿な事をしたもんだよ。")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 10))
   (proc 10)
   (branch-index
    (</>
     (/
      (proc 18)
      (text "お、お願いよ‥‥‥考え直して頂戴！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "駄目だね、絶対に。この国を見捨ててどうするんだよ。わたしには他に行くあてがある訳じゃないんだ。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "こうなりゃ、加藤と心中だね。あんた達から機密を取り返せば、奴の軍部での株も上がる。")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "奴に取り入って、わたしも日本を支配する少数の特権階級のひとりになるさ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "キヨミ、あなた馬鹿よ。そんな事が出来る訳ないじゃない！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "黙れ！　あんたと他の６人は、頭の中をかき回されて廃人になっちまえばいいのさ。わたしを謀った罰だ！")
      (wait)
      (text-reset 14))
     (/ (proc 18) (text "お、お願いよ‥‥‥考え直して頂戴！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 11)) (mes-jump "mes¥md_g3_r2.mes"))
 (seg (? (= Y 2) (= S 2))
   (sound 'se 1)
   (branch-reg
    120
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_62bb.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (proc 18)
      (text "あうッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "もう痛みに鈍くなってきたね、そいつは一生元に戻らないよ。牝奴隷には必要な事だからね！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "うぅぅ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 120 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あうッ‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 3))
   (sound 'se 1)
   (branch-reg
    121
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62bc.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "ひッ‥‥‥ひぃッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "まだ身体に傷が付くのを、恐がってる訳のかい。甘すぎるね、そんな人間がよくも自分を犠牲にしようなんて思ったもんだ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "キヨミ‥‥‥まだ間に合うわ、よく考えて‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 121 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ひッ‥‥‥ひぃッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 4))
   (sound 'se 1)
   (branch-reg
    122
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62bd.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "あくッ‥‥‥い、痛ぁいッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "でも、悪くないだろう？　＊＊＊がうれし涙を流してるじゃない" 'br)
      (text "か。あんたはお尻を苛められるのが大好きだったものね！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "そ、そんな事ないわ‥‥‥そんな事！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 122 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あくッ‥‥‥い、痛ぁいッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 5))
   (sound 'se 1)
   (branch-reg
    123
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62be.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "あうぅぅ‥‥‥お、お尻はッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "お尻は何だって？　気持ちよくて仕方ないか！　お上品ぶっててもわたしにはちゃんとわかってるんだ。あんたが牝豚だって事がね！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 123 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "あうぅぅ‥‥‥お、お尻はッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 6))
   (sound 'se 1)
   (branch-reg
    124
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62bf.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "く、くぅぅぅン！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "豚みたいに鳴く女だね。本当はただの牝豚なんだろう？　鞭打たれてよがってる、ただの牝豚さ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "そ、そんな‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 124 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "く、くぅぅぅン！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 7))
   (sound 'se 1)
   (branch-reg
    125
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62bg.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "ハッ、ハァァァァ〜ン！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "今、イッちまったね？　拷問されてイッちゃうなんて、すごいね。感心しちまうよ。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "そ、そんな事言わないで‥‥‥お願い‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 125 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ハッ、ハァァァァ〜ン！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 8))
   (sound 'se 1)
   (branch-reg
    126
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62bh.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "ハンッ！　そこは堪忍して‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "＊＊＊が疼いて仕方ないだろう？　それだけグチュグチュになっ" 'br)
      (text "てれば、無理もない。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "嫌ッ、それ以上は言わないで‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 126 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "ハンッ！　そこは堪忍して‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 9))
   (sound 'se 1)
   (branch-reg
    127
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62bi.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "んくッ！　い、痛いの‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "嫌だって言っても、止めてはやらない。早くその痛みに慣れてしまう事だね。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 127 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "んくッ！　い、痛いの‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 10))
   (sound 'se 1)
   (branch-reg
    128
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62bj.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "んふッ、んッ、んん〜ッ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "身体が痺れるみたいだろう？　じわじわ効いてくる。尻を振って早く何とかしてくれって言わんばかりだね！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "そ、そんな事は‥‥‥ああ、何とかして‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 128 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "んふッ、んッ、んん〜ッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 11))
   (sound 'se 1)
   (branch-reg
    129
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_62bk.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 10)
      (proc 18)
      (text "はうぅぅ〜ン！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "奴隷の烙印を押されるのが、そんなにうれしいのかい。＊＊＊が" 'br)
      (text "もっとやってくれって言ってるよ！")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 129 #t)
      (proc 19))
     (/ (proc 10) (proc 18) (text "はうぅぅ〜ン！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 11) (= S 1) (= 130 #f))
   (proc 10)
   (branch-reg
    131
    (</>
     (/
      (proc 18)
      (text "そ、それは‥‥‥アナルポンプね‥‥‥")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "あんたの大好きなオモチャさ。お尻の穴で遊ぶのが大好きな変態用のオモチャ。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "何をするの‥‥‥お願い、それは許して！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "くっくっ‥‥‥これで尻の穴が使い物にならないようにしてやる。こいつはね、お腹の中で何倍もの大きさになるんだ。")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "しかも、アナルに栓をしながらグリセリンを流し込める特別製さ。栓をしてる間はいいけど、こいつを抜いたら‥‥‥")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "そ、それだけは！　お願い、ああ‥‥‥キヨミ！")
      (wait)
      (text-reset 14))
     (/
      (proc 18)
      (text "うッ‥‥‥嫌ァ！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "自分の尻の穴に入ってた物だろうが！　汚いなんて言わせないよ。よく臭いを嗅いでみな。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "嫌ァァ！　お願いよ、それを近づけないで！")
      (wait)
      (text-reset 14)
      (proc 17)
      (text "くくっ、こいつを口の中に押し込んでやろうか！　そりゃ中々面白そうだねぇ。")
      (wait)
      (text-reset 14)
      (proc 18)
      (text "嫌ァァァァァァ！")
      (wait)
      (text-reset 14))))
   (nop@)
   (set-reg 130 #t)
   (proc 11))
 (seg (? (= Y 11) (= S 1) (= 130 #t))
   (proc 10)
   (branch-reg
    131
    (</>
     (/ (proc 18) (text "そ、それは‥‥‥‥‥‥") (wait) (text-reset 14))
     (/ (proc 18) (text "いっ、嫌ァ！　近づけないで、汚いわ‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 11) (= S 12) (= 131 #f))
   (proc 10)
   (nop@)
   (inc-var H 1)
   (proc 18)
   (text "嫌ッ、何するの‥‥‥それは駄目よ！")
   (wait)
   (text-reset 14)
   (proc 11)
   (proc 0)
   (proc 5)
   (exec-mem 256 "F 8")
   (exec-mem 256 "F 9")
   (exec-mem 256 "A 1")
   (text-frame 0 0 79 399)
   (text-reset 14)
   (text-frame 10 312 70 370)
   (exec-mem 256 "A 0")
   (mes-load? "mes¥bnkcpy2.mec" 0)
   (mes-load? 0)
   (exec-mem 256 "A 0")
   (image-file "gpc¥a1_62a.gpc")
   (image-mem 1 0)
   (proc 10)
   (proc 17)
   (text "じたばたするんじゃないよ。こいつはね、アナルに栓をしたままでグリセリンを流し込める特別製さ。")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "お腹の中にたっぷり注いでやるからね、せいぜい苦しむがいいさ！何しろ出したくっても出せないんだ。その苦しみは並じゃない。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "や、止めて‥‥‥キヨミ‥‥‥お願い！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3072 0)
   (exec-mem 256 "A 1")
   (text-frame 10 312 70 370)
   (image-file "gpc¥a1_62a3.gpc")
   (image-mem 1 0)
   (image-file "gpc¥a1_62a2.gpc")
   (image-mem 1 0)
   (repeat
    3
    (<> (exec-mem 256 "S 1") (delay 10) (exec-mem 256 "S 0") (delay 10)))
   (exec-mem 256 "A 0")
   (proc 10)
   (proc 17)
   (text "くっくっくっ‥‥‥ほら、どんどん入ってく‥‥‥")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "ンンッ！　ンン‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "あんたみたいに散々お尻で遊んでる女なら、軽く２リットルは入りそうだね。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "ひィィィィィ！")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "もうお腹がグルグル音を立ててるよ‥‥‥苦しいかい？")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "ンッ！　うぐぅぅぅ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "ハァ、ハァ、ハァ、ハァ‥‥‥お、お願い‥‥‥助けて！")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "助けて欲しい？　助けてやろうか、栓を抜いてやろうか？")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "そ、それはッ‥‥‥駄目、抜いちゃ駄目ぇ！")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "でも、そんなに苦しそうにしてちゃね。可哀想で見てられないよ。")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3072 0)
   (proc 10)
   (proc 18)
   (text "アアッ‥‥‥嫌ァァァァ！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3072 0)
   (exec-mem 29184 0 1 "gpa¥a1_62.dpb" 0)
   (exec-mem
    29184
    1
    1
    "A.............A.............A.............A.............A.............A.............")
   (exec-mem 256 "A 1")
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_62.gpc")
   (image-mem 0 3)
   (branch-reg
    119
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62ba.gpc") (image-mem 1 0))))
   (branch-reg
    120
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bb.gpc") (image-mem 1 0))))
   (branch-reg
    121
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bc.gpc") (image-mem 1 0))))
   (branch-reg
    122
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bd.gpc") (image-mem 1 0))))
   (branch-reg
    123
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62be.gpc") (image-mem 1 0))))
   (branch-reg
    124
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bf.gpc") (image-mem 1 0))))
   (branch-reg
    125
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bg.gpc") (image-mem 1 0))))
   (branch-reg
    126
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bh.gpc") (image-mem 1 0))))
   (branch-reg
    127
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bi.gpc") (image-mem 1 0))))
   (branch-reg
    128
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bj.gpc") (image-mem 1 0))))
   (branch-reg
    129
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bk.gpc") (image-mem 1 0))))
   (mes-load? "mes¥bnkcpy3.mec" 0)
   (mes-load? 0)
   (exec-mem 256 "A 1")
   (image-file "gpc¥a1_62_1.gpc")
   (image-mem 1 0)
   (exec-mem 256 "A 0")
   (image-file "gpc¥a1_62_0.gpc")
   (image-mem 1 0)
   (exec-mem 29184 2 1 1 0)
   (exec-mem 29184 3 1)
   (exec-mem 256 "S 0")
   (text-frame 10 312 70 370)
   (proc 10)
   (proc 17)
   (text "はっ、はははははッ！")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "こりゃ臭いや、鼻がもげちまいそうだよ。")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "うッ、うッ、ううっ‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "どうだ、気持ちよかっただろう？")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "あれだけ我慢してたんだもん。目一杯ウンチが出来て、気持ちよくない訳がないよね！")
   (wait)
   (text-reset 14)
   (proc 18)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 17)
   (text "何とか言いなよ、クソ漏らし！")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3072 0)
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (image-file "gpc¥a1_62.gpc")
   (image-mem 0 3)
   (branch-reg
    119
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62ba.gpc") (image-mem 1 0))))
   (branch-reg
    120
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bb.gpc") (image-mem 1 0))))
   (branch-reg
    121
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bc.gpc") (image-mem 1 0))))
   (branch-reg
    122
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bd.gpc") (image-mem 1 0))))
   (branch-reg
    123
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62be.gpc") (image-mem 1 0))))
   (branch-reg
    124
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bf.gpc") (image-mem 1 0))))
   (branch-reg
    125
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bg.gpc") (image-mem 1 0))))
   (branch-reg
    126
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bh.gpc") (image-mem 1 0))))
   (branch-reg
    127
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bi.gpc") (image-mem 1 0))))
   (branch-reg
    128
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bj.gpc") (image-mem 1 0))))
   (branch-reg
    129
    (</> (/ (nop@)) (/ (image-file "gpc¥a1_62bk.gpc") (image-mem 1 0))))
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (nop@)
   (set-reg 131 #t)
   (proc 6)
   (branch-reg
    991
    (</>
     (/ (exec-mem 9504 "C icon¥tool22.gpc,GPC") (image-mem 1 0 6 256))
     (/ (exec-mem 9504 "C icon¥tool22.gpc,GPC") (image-mem 1 0 71 256))))
   (proc 12))
 (seg (? (= Y 11) (= S 12) (= 131 #t))
   (proc 10)
   (proc 18)
   (text "も、もう嫌ァ‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (proc 11))
 (seg*))