(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
   (exec-mem 3072 0)
   (nop@)
   (set-reg 980 #t)
   (set-reg 981 #t)
   (set-reg 982 #f)
   (set-reg 983 #f)
   (set-reg 984 #f)
   (set-reg 985 #f)
   (set-reg 986 #f)
   (set-reg 987 #f)
   (set-reg 988 #f)
   (set-reg 989 #f)
   (set-reg 990 #f)
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_60.gpc")
   (image-mem 0 3)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (if (</>
        (//
         (? (= P 13))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_13.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 13))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_13v.uso")
               (sound '|| 1)
               (nop@)
               (set-var P 13)))))
        (// (nop@))))
   (exec-mem 256 "E")
   (load-mem "clm¥A1_60.clm" 32768)
   (load-mem "clm¥icon.clm" 20480)
   (mes-load? "mes¥icon_cl.mec" 0)
   (mes-load? 0)
   (mes-load? "mes¥icon_c2.mec" 0)
   (mes-load? 0)
   (text-frame 10 312 70 370)
   (exec-mem 256 "A 0")
   (proc 12)
   (set-var H 0)
   (define-proc 15
     (<>
      (if (</>
           (//
            (? (>= H 5) (= 100 #f))
            (image-file "gpc¥a1_60a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 100 #t))
           (// (nop@))))
      (proc 12)))
   (proc 10)
   (text "「アンナ」" 'br)
   (text "くっ‥‥‥苦しいわ、何なのこれは。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "あんたに普通の拷問が通じないのは、わかってるからね。最初から厳しくいかないと。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "何をしても無駄よ、それを言うのならね‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "かといって、やらない訳にもいかないんだよ！　これがわたしの仕事だし、裏切られたって気もある。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "なあ、馬鹿な事は終りにしようよ。わたしの拷問に耐えられるなんてのが不可能なのは、よくわかってるじゃないか。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "ああ、そうかい！　そういうつもりなら仕方ない。本気でやるからそのつもりでね。")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (exec-mem 256 "P 5 6 0")
   (loop
    (set-var S 0)
    (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
    (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 9 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 9 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (= Q 2))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name1.gpc,GPC")
   (image-mem 1 0 52 16)
   (proc 1)
   (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (= Q 3))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (exec-mem 9504 "C icon¥name2.gpc,GPC")
   (image-mem 1 0 52 40)
   (proc 1)
   (set-var Q 3))
 (seg (? (= Z 2) (= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1))
   (proc 0)
   (exec-mem 256 "P 6 9 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= Z 2) (= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1))
   (proc 0)
   (exec-mem 256 "P 7 52 16")
   (proc 1)
   (nop@)
   (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (= Z 1) (= 991 #f))
   (proc 0)
   (exec-mem 256 "P 5 71 0")
   (nop@)
   (set-reg 991 #t)
   (exec-mem 256 "P 8 6 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 71 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 71 40))))
   (load-mem "clm¥icon2.clm" 20480)
   (proc 1))
 (seg (? (= Z 1) (= 991 #t))
   (proc 0)
   (exec-mem 256 "P 5 6 0")
   (nop@)
   (set-reg 991 #f)
   (exec-mem 256 "P 9 71 0")
   (if (</>
        (//
         (? (= Y 1))
         (exec-mem 9504 "C icon¥tool12.gpc,GPC")
         (image-mem 1 0 6 16))
        (//
         (? (= Y 2))
         (exec-mem 9504 "C icon¥tool13.gpc,GPC")
         (image-mem 1 0 6 40))))
   (load-mem "clm¥icon.clm" 20480)
   (proc 1))
 (seg (? (= Z 2) (= 991 #f))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #f))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 6 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 6 16)
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Z 2) (= 991 #t))
   (nop@)
   (set-var Y 1)
   (proc 0)
   (exec-mem 9504 "C icon¥tool12.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 9504 "C icon¥tool24.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 18688 5 1 1)
   (proc 1)
   (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #t))
   (nop@)
   (set-var Y 2)
   (proc 0)
   (exec-mem 9504 "C icon¥tool13.gpc,GPC")
   (image-mem 1 0 71 40)
   (exec-mem 9504 "C icon¥tool23.gpc,GPC")
   (image-mem 1 0 71 16)
   (exec-mem 18688 5 3 1)
   (proc 1)
   (exec-mem 18688 2 3))
 (seg (? (= Y 1) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「アンナ」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "全然こたえたような顔じゃないね。もっとも、そう簡単に事が済むとは、思っちゃいないけど。")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "無駄よ、キヨミ。いくらあなたでも、私に言うことをきかせるのはムリだわ。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "言ってくれるじゃない！　あんたの為を思って手加減してやってるんだよ。これからが本番さ。")
      (wait)
      (text-reset 14))
     (/ (text "「アンナ」" 'br) (text "‥‥‥‥‥‥‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 9))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "さあ言うんだよ！　軍のデータベースから盗んだ機密を、何処に隠したんだ。プリスはあんたがそれを隠したって言ったんだよ。")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "それに、あんたが機密を盗んだ理由だ。プリスの言った事が本当だとすれば、軍の機構＝システムが酷く剣呑な物だから‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "だから機密を盗み、なおかつデータベースからそれを削除したって事になるけど、あんたが英雄志願だなんて信じられないね！")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "他の連中だってそう。ゴロツキか思想なんてのとは無縁のお嬢さんばかりじゃないか！")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "そんな言い方は失礼だわ‥‥‥私を挑発しようと言うなら、無駄な事よ。その手には乗らないわ。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "どうしても言わないってのかい。いい度胸だよ、まったく。仕方がないね、もっと拷問して無理矢理吐かせるしかないようだね。")
      (wait)
      (text-reset 14))
     (/
      (text "「Kiyomi」" 'br)
      (text "さあ言うんだよ！　軍のデータベースから盗んだ機密を、何処に隠したんだ。プリスはあんたがそれを隠したって言ったんだよ。")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 10))
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "まだ何も喋る気にはならない？")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "なんて強情な女だ。あの国の人間は、みんなそうなのかい。あんたの生まれた国ではさ。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "アンナ、わたし達はずっとうまくやって来たじゃない。もう何年もだよ。それなのに、急にお終いだって言うのかい？")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "うまくやって来たんなら、どうしてあなたは紫岩に浸っていたの？ここ数年のあなたは、ひどく自虐的だったわ。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "あんな生活を続ければ、死んでしまう事は明白なのに。それでもうまく行ってたって言うの？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "今度はあなたが黙る番だって訳？　もうたくさんだわ、私は国に帰りたい、こんな所には居たくないのよ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それも、今となっては不可能な話だ。あんたは一生塀の外には出られないし、どれくらい生き長らえる事が出来るかも疑問だ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "軍のデータベースを破壊したあんた達は、反逆者だからね。殺されても文句は言えない。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "まあ、それもこれも機密を取り返してからの話さ。何がなんでも吐いてもらうよ。")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 18688 3)
   (exec-mem 18688 5 1 0)
   (exec-mem 3072 0)
   (mes-jump "mes¥MD_G02.MES"))
 (seg (? (= Y 1) (= S 2))
   (sound 'se 1)
   (branch-reg
    90
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_60ba.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "ンッ‥‥‥ンンッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ストッキングの破れが美しいね。フェティッシュの人間にはたまらない光景だわ。このまま脱がさないで嬲ってやるからね。")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "あなたは本当に、この仕事を楽しんでいるのね‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 90 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "ンッ‥‥‥ンンッ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 3))
   (sound 'se 1)
   (branch-reg
    91
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_60bb.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "アッ！　痛いわ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "いつもわたしとジャムる時は、これくらいじゃ済まなかったと思うけどね？")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "これは恋人とのジャムじゃないわ、あなたには悪意を感じるもの！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 91 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "アッ！　痛いわ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 4))
   (sound 'se 1)
   (branch-reg
    92
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_60bc.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "くッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "肌が白いと、本当に傷がよく映える。拷問のやり甲斐があるってものさ。たとえ相手があんたでもね！")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "脅したって無駄よ、そんな物には屈しないわ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 92 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "くッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 5))
   (sound 'se 1)
   (branch-reg
    93
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_60bd.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "ハンッ！　そ、そこはッ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "氷の女って言われてるアンナでも、＊＊＊を嬲られるのはこたえ" 'br)
      (text "るって訳？")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "痛いわ‥‥‥死んでしまいそうよ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 93 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "ハンッ！　そ、そこはッ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 6))
   (sound 'se 1)
   (branch-reg
    94
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_60be.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "うぐっ‥‥‥つ、強すぎるわ‥‥‥痛いの！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "当たり前だろう、わたしはあんたを悦ばせるためにやってる訳じゃないんだ。気に入らないなら、こんな事は早く終わらせるんだね。")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "い、言わないわ、絶対に‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 94 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "うぐっ‥‥‥つ、強すぎるわ‥‥‥痛いの！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 7))
   (sound 'se 1)
   (branch-reg
    95
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_60bf.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "アッ‥‥‥ううッ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "お腹のあたりに、ちょっと肉がついたんじゃない？　あんたは巧妙に歳を偽ってるけど、本当はいくつなのさ。")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "そ、そんな事はどうでもいいでしょう、関係ないわ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 95 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "アッ‥‥‥ううッ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 8))
   (sound 'se 1)
   (branch-reg
    96
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_60bg.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "あァァン‥‥‥やめてッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "止めてだって？　他のお仲間にはもっと酷い事もしたんだぜ。しかもあんたの命令でさ。")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 96 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "あァァン‥‥‥やめてッ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 9))
   (sound 'se 1)
   (branch-reg
    97
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_60bh.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "くッ！　くぅぅぅッ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "やっぱりストッキングの上から叩くより、効くようだね。太股の裏側なんて筋肉もついてないし。")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "本物のサドね‥‥‥とんでもない人を巻き込んでしまったわ。")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 97 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "くッ！　くぅぅぅッ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 10))
   (sound 'se 1)
   (branch-reg
    98
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_60bi.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "はッ‥‥‥くぅぅぅッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "随分景気よく破けるじゃない。流行のデザイナーズ物だろ、ちゃちな生地を使ってるね。")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "これ一着のお金で、普通の市民が３ヶ月は楽に暮らせるのよ。勿体ないとは感じないの？")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 98 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "はッ‥‥‥くぅぅぅッ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 1) (= S 11))
   (sound 'se 1)
   (branch-reg
    99
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_60bj.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 16)) (/ (image-mem 1 0 71 16))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "きゃッ！　あ、危ないわ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あんたでもそんな可愛い悲鳴を上げるんだね。元ＫＧＢの古強者、寒い国で鍛えられたあんたでも！")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "‥‥‥‥‥‥この国では心が鈍ってしまうのよ、それだけだわ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 99 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "きゃッ！　あ、危ないわ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 5))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "さあ言うんだよ！　軍のデータベースから盗んだ機密を、何処に隠したんだ。プリスはあんたがそれを隠したって言ったんだよ。")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "それに、あんたが機密を盗んだ理由だ。プリスの言った事が本当だとすれば、軍の機構＝システムが酷く剣呑な物だから‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "だから機密を盗み、なおかつデータベースからそれを削除したって事になるけど、あんたが英雄志願だなんて信じられないね！")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "他の連中だってそう。ゴロツキか思想なんてのとは無縁のお嬢さんばかりじゃないか！")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "そんな言い方は失礼だわ‥‥‥私を挑発しようと言うなら、無駄な事よ。その手には乗らないわ。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "どうしても言わないってのかい。いい度胸だよ、まったく。仕方がないね、もっと拷問して無理矢理吐かせるしかないようだね。")
      (wait)
      (text-reset 14))
     (/
      (text "「Kiyomi」" 'br)
      (text "さあ言うんだよ！　軍のデータベースから盗んだ機密を、何処に隠したんだ。プリスはあんたがそれを隠したって言ったんだよ。")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 9))
   (proc 10)
   (branch-index
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "気持ちいいかい、ええ？　あんたは嬲られるのは嫌いじゃなかったもんね。確か、お尻の方も‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "だ、黙りなさい！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "残念だけど、あんたはもう私の上官でも恋人でも何でもない。わたしに命令する事なんて出来ないんだよ。")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "なあ、あんたが軍の機密を何処かに隠したってのはわかってんだ。まさかこれ以上仲間が沸いて出るって事はないだろう？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "わたしに隠しとおすなんて、無理なんだよ。それはふたりともよくわかってる。それじゃ無駄な事は止めにしようじゃないか？")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ああ、そうかい。わたしの話なんか、聞く耳持たないって訳か。")
      (wait)
      (text-reset 14))
     (/
      (text "「Kiyomi」" 'br)
      (text "気持ちいいかい、ええ？　あんたは嬲られるのは嫌いじゃなかったもんね。確か、お尻の方も‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 10))
   (proc 10)
   (text "「Kiyomi」" 'br)
   (text "まだ何も喋る気にはならない？")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "なんて強情な女だ。あの国の人間は、みんなそうなのかい。あんたの生まれた国ではさ。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "アンナ、わたし達はずっとうまくやって来たじゃない。もう何年もだよ。それなのに、急にお終いだって言うのかい？")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "うまくやって来たんなら、どうしてあなたは紫岩に浸っていたの？ここ数年のあなたは、ひどく自虐的だったわ。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "あんな生活を続ければ、死んでしまう事は明白なのに。それでもうまく行ってたって言うの？")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "今度はあなたが黙る番だって訳？　もうたくさんだわ、私は国に帰りたい、こんな所には居たくないのよ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "それも、今となっては不可能な話だ。あんたは一生塀の外には出られないし、どれくらい生き長らえる事が出来るかも疑問だ。")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "軍のデータベースを破壊したあんた達は、反逆者だからね。殺されても文句は言えない。")
   (wait)
   (text-reset 14)
   (text "「アンナ」" 'br)
   (text "‥‥‥‥‥‥‥‥‥‥‥‥")
   (wait)
   (text-reset 14)
   (text "「Kiyomi」" 'br)
   (text "まあ、それもこれも機密を取り返してからの話さ。何がなんでも吐いてもらうよ。")
   (wait)
   (text-reset 14)
   (proc 11)
   (exec-mem 18688 3)
   (exec-mem 18688 5 1 0)
   (exec-mem 3072 0)
   (mes-jump "mes¥MD_G02.MES"))
 (seg (? (= Y 2) (= S 2))
   (sound 'se 1)
   (branch-reg
    90
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (proc 5)
      (image-file "gpc¥a1_60ba.gpc")
      (image-mem 1 0)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "ふっ、ふぅぅッ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "くっくっくっ、いい声で鳴くじゃないか。とても全身ポッドモッドで固めたロボットみたいな女の出す声だとは思えないね！")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "キヨミ、私をそんな風に思ってたのね‥‥‥ええ、確かに私は生身の人間じゃないわ。それを後悔しても、どうにもならないのよ。")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 90 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "ふっ、ふぅぅッ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 3))
   (sound 'se 1)
   (branch-reg
    91
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_60bb.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "ンッ‥‥‥こ、これくらい、何でもないわ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "馬鹿な女だね。そんな恥ずかしい格好して、虚勢を張って何になるんだよ。そんな事も理解できないのか！")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "何を言っても無駄よ‥‥‥言葉責めなんて、何の効果もないわ。")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 91 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "ンッ‥‥‥こ、これくらい、何でもないわ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 4))
   (sound 'se 1)
   (branch-reg
    92
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_60bc.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "あうッ！　そ、そこは‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あんた、足を上から下まで丹念に愛撫されるのが好きだったよね。今度は舌のかわりに鞭で愛撫してやるよ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "そ、それは嫌よ、そんな事したら！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 92 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "あうッ！　そ、そこは‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 5))
   (sound 'se 1)
   (branch-reg
    93
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_60bd.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "ハンッ！　そ、そこはッ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "氷の女って言われてるアンナでも、＊＊＊を嬲られるのはこたえ" 'br)
      (text "るって訳？")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "痛いわ‥‥‥死んでしまいそうよ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 93 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "ハンッ！　そ、そこはッ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 6))
   (sound 'se 1)
   (branch-reg
    94
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_60be.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "ひッ‥‥‥ひぃぃッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "今のは苦痛に耐えかねた悲鳴なのか、それとも歓喜の声なのかい？わたしには、どちらとも判断出来なかったけど。")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 94 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "ひッ‥‥‥ひぃぃッ！")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 7))
   (sound 'se 1)
   (branch-reg
    95
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_60bf.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "はッ、はンッ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "白いお腹に傷が付いてしまったね。もっとも、あんたならその傷もお得意のポッドモッドで何とかしちまうんだろうけどさ！")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "私を何だと思ってるの‥‥‥私だって人間なのよ‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 95 #t))
     (/ (proc 10) (text "「アンナ」" 'br) (text "はッ、はンッ！") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 8))
   (sound 'se 1)
   (branch-reg
    96
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_60bg.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "あうぅッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "でかい口を叩く割りに、他愛ないじゃないの。わたしが他の６人にした拷問は、こんなもんじゃないよ。")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "だったら、私にも早くその拷問というのをやったらどうなの‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 96 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "あうぅッ‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 9))
   (sound 'se 1)
   (branch-reg
    97
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_60bh.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "くッ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ほう、よく我慢したじゃない。その調子でわたしの拷問を耐えきってみるかい？")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "私には出来ないと思ってるんでしょうけど、耐えてみせるわ！")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 97 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "くッ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 10))
   (sound 'se 1)
   (branch-reg
    98
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_60bi.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "ひッ！　わ、私を殺すつもりなの‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "殺すつもりはないけどね、他の６人は死んだほうがマシだって言ってたみたいだけど？")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 98 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "ひッ！　わ、私を殺すつもりなの‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= Y 2) (= S 11))
   (sound 'se 1)
   (branch-reg
    99
    (</>
     (/
      (nop@)
      (inc-var H 1)
      (proc 0)
      (image-file "gpc¥a1_60bj.gpc")
      (image-mem 1 0)
      (proc 5)
      (proc 15)
      (proc 6)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (branch-reg 991 (</> (/ (image-mem 1 0 6 40)) (/ (image-mem 1 0 71 40))))
      (proc 10)
      (text "「アンナ」" 'br)
      (text "くッ、顔は止めて‥‥‥お願い！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "わたしはあんたの顔が醜くなったとしても、見捨てたりしないよ。むしろ、その冷たい人工的な美しさよりマシってもんさ。")
      (wait)
      (text-reset 14)
      (text "「アンナ」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (nop@)
      (set-reg 99 #t))
     (/
      (proc 10)
      (text "「アンナ」" 'br)
      (text "くッ、顔は止めて‥‥‥お願い！")
      (wait)
      (text-reset 14))))
   (proc 11)))