(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  ((cmd 209) 0 5)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (image-file "gpc¥e1_01.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (text-frame 10 312 70 370)
  (if (</>
       (//
        (? (= O 0))
        (sound '|| 2)
        (delay 50)
        (sound '|| 0)
        (sound '|| "uso¥xg_12.uso")
        (sound '|| 1)
        (nop@)
        (set-var P 12))
       (//
        (? (= O 1))
        (sound '|| 2)
        (delay 50)
        (sound '|| 0)
        (sound '|| "uso¥xg_12v.uso")
        (sound '|| 1)
        (nop@)
        (set-var P 12))))
  (text "「Kiyomi」" 'br)
  (text "アッ‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "キヨミ、もっと楽にして。私達に身体を委ねるのよ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「プリス」" 'br)
  (text "さあみんな、もっと彼女を楽しませてあげるのよ。")
  (wait)
  (text-reset 14)
  (text "「エイプリル」" 'br)
  (text "ナナ、もっと脇に退いてよ。ソコに舌が届かないじゃない。")
  (wait)
  (text-reset 14)
  (text "「ナナ」" 'br)
  (text "駄目よ、一番酷い目にあったのはあたしなんだから！　ココは絶対に渡さないわよ。")
  (wait)
  (text-reset 14)
  (text "「ミツコ」" 'br)
  (text "だいぶ身体の力が抜けてきたわね、可愛い顔‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "ンッ‥‥‥は、恥ずかしい事言わないでよ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "キヨミ、あなたは他人に心を開かなきゃいけないわ。そうすれば、もう荒んだ生活に逆戻りする事もないのよ。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "はッ、ううぅぅ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「ナナ」" 'br)
  (text "すごく濡れてるわよ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「エイプリル」" 'br)
  (text "ピチャピチャ音がするもんね。")
  (wait)
  (text-reset 14)
  (text "「エリコ」" 'br)
  (text "わたしもするのォ、みてるだけじゃイヤァ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「プリス」" 'br)
  (text "頭でも撫でてあげなさいよ、それで十分よ。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "暖かいわ‥‥‥こんなに暖かいなんて‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "本当に寒かったのは私ではなくてキヨミ、あなただったのよ。")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "自分がどれだけ凍えているかさえ、気づかなかったなんて。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "ンッ、ンッ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「プリス」" 'br)
  (text "それじゃ、最後はアンナと‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥e1_02.gpc")
  (image-mem 0 3)
  (proc 3)
  (text "「Anna」" 'br)
  (text "はうン‥‥‥くっ、くぅぅぅッ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "もっと‥‥‥もっと腰を動かして‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "はぁ、はぁ、はぁ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "気持ちいい？　アンナ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "いいわ、とても‥‥‥キヨミは？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "いいよ‥‥‥こんなの初めて‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "アッ！　はッ、はァァン！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "わたしは加藤を殺るよ‥‥‥わたしにしか出来ない仕事だ。")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "ン、ンンンッ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "あんた達は、他の仕事に回ってくれ。やるべき事はわかってるね？サカタ・ネオテクの坂田だ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "そのふたりを殺れば、軍の計画は頓挫する。そしてその後は‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "止めて、今は‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "アッ、アアッ！　もっと‥‥‥もっと強く！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "アンナ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "キヨミ‥‥‥もう駄目、もう‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "アッ！　アァァァァァァッ！")
  (wait)
  (text-reset 14)
  (sound '|| 2)
  (delay 50)
  (sound '|| 0)
  (if (</>
       (//
        (? (= O 0))
        (sound '|| 0)
        (sound '|| "uso¥xg_11.uso")
        (sound '|| 1)
        (nop@)
        (set-var P 11))
       (//
        (? (= O 1))
        (sound '|| 0)
        (sound '|| "uso¥xg_11v.uso")
        (sound '|| 1)
        (nop@)
        (set-var P 11))))
  ((cmd 209) 0 5)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (image-file "gpc¥b01_01.gpc")
  (image-mem 0 3)
  (image-file "gpc¥b01_01b.gpc")
  (image-mem 1 0)
  ((cmd 209) 1 10)
  (text-frame 10 312 70 370)
  (text "「加藤」" 'br)
  (text "少佐ではないか‥‥‥どうかしたか？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "もちろん、どうかしたさ。じゃなきゃわたしがこんな所に来る訳がないだろう。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "まさにその通りだな。それで、アンナ大佐の尋問は首尾よく進んでいるのだろうな？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "さあ、その事さ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "ほう、話を聞こうか。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "急で悪いが、あんたら軍部に協力するのは止めにさせてもらうよ。どうもあんた達のやってる事が気に入らないんでね！")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "少佐、それはどういう意味かな？　私にはよくわからなかったが。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "お前らケツの穴野郎は、クソ食らって死んじまえって言ってんだ！")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "くっくっくっ‥‥‥貴様は天に唾するという言葉を知っているか？吐いた唾が自分にかからんように、気をつけるんだな。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "わたしがそんな事を考えて唾を吐くと思ってんの？　手前の靴の所在を心配しながら唾を吐くなんて、くだらないね。")
  (wait)
  (text-reset 14)
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥e1_03.gpc")
  (image-mem 0 3)
  (proc 3)
  (text "「加藤」" 'br)
  (text "馬鹿が。それでは貴様もあ奴等と同じようにとどめを刺してやる！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "ちッ、こりゃ強すぎだ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "どうした！　そんな事では私には勝てんぞ！")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "いや、そもそも貴様などが私に歯向かう事が間違いなのだ。所詮貴様など薄汚い移民共と何も変わらんのだから！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "クッ‥‥‥薄汚いのは、お前ら軍人だろうが。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "死ぬ前に、せいぜい戯言をほざいていろ！")
  (wait)
  (text-reset 14)
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b10_01.gpc")
  (image-mem 0 3)
  (image-file "gpc¥b10_01a.gpc")
  (image-mem 1 0)
  (proc 3)
  (text "「エリコ」" 'br)
  (text "‥‥‥‥‥‥‥‥‥お父さん。")
  (wait)
  (text-reset 14)
  (text "「坂田」" 'br)
  (text "誰だ！　誰も入れるなと言ってあったろう！")
  (wait)
  (text-reset 14)
  (text "「エリコ」" 'br)
  (text "お父さん、わたしよ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「坂田」" 'br)
  (text "エリコ？　どうしてお前がここに居るんだ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「坂田」" 'br)
  (text "お前、どうやってこの部屋に入って来た！")
  (wait)
  (text-reset 14)
  (text "「エリコ」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「坂田」" 'br)
  (text "その‥‥‥後ろに居るのは誰だ！")
  (wait)
  (text-reset 14)
  (text "「エリコ」" 'br)
  (text "お父さんはエリコのことが、ずっときらいだったの？")
  (wait)
  (text-reset 14)
  (text "「坂田」" 'br)
  (text "誰だと言っているんだ、姿を見せろ！")
  (wait)
  (text-reset 14)
  (text "「エリコ」" 'br)
  (text "こたえて！　エリコのことがきらいだったの？")
  (wait)
  (text-reset 14)
  (text "「坂田」" 'br)
  (text "お前、何を持ってるんだ‥‥‥そんな物は置きなさい。お前のような子供が持つ物じゃない！")
  (wait)
  (text-reset 14)
  (text "「エリコ」" 'br)
  (text "やっぱりエリコのことが、きらいだったんだ‥‥‥")
  (wait)
  (text-reset 14)
  (sound 'se 2)
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥e1_04.gpc")
  (image-mem 0 3)
  (proc 3)
  (text "「エリコ」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「エイプリル」" 'br)
  (text "これでよかったのさ。ザイバツの為に娘を売るような男には、似合いの結末だよ！")
  (wait)
  (text-reset 14)
  (text "「エリコ」" 'br)
  (text "お父さん、エリコはお父さんのこと、きらいじゃなかったよ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「ナナ」" 'br)
  (text "もう少し娘に優しく接してれば、殺される事もなかったかもよ。混血ってだけで邪険にされたら、娘だってキレるわ。")
  (wait)
  (text-reset 14)
  (text "「Lei-Fa」" 'br)
  (text "所詮こいつは下衆野郎ね。いずれ誰かに殺されてたに決まってる。")
  (wait)
  (text-reset 14)
  (text "「ナナ」" 'br)
  (text "のんびりしちゃいられないわよ、あたしはログオンしてサカタ・ネオテクのマトリクスに入り込むから‥‥‥")
  (wait)
  (text-reset 14)
  (text "「エイプリル」" 'br)
  (text "こっちはレイファとここの設備を使って、回線を開く。何処かの国の軍事施設が電波を拾ってくれりゃいいけど。")
  (wait)
  (text-reset 14)
  (text "「Lei-Fa」" 'br)
  (text "後はアンナ達が情報部から、情報を送信してくれるね。マル特級の軍事機密を敵軍に垂れ流すね！")
  (wait)
  (text-reset 14)
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥e1_03.gpc")
  (image-mem 0 3)
  (proc 3)
  (text "「加藤」" 'br)
  (text "くっくっくっ‥‥‥逃げるばかりでは勝負にならんぞ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "くそッ、手が痺れてきた‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "貴様に考え直す機会を与えてやる。アンナ大佐と囚人共を私の前に連れて来い！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "絶対にお断りだね‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "考えてみろ！　私は一介の将校ごときで終わる男ではない。この計画がうまく行けば、軍とて私の思うがままなのだぞ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "誇大妄想も甚だしい‥‥‥所詮、あんたもただの公僕さ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "さあ、アンナ大佐を連れて来い！　そうすれば、この場での事は忘れてやる。私の情婦ぐらいにはしてやるぞ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "誰が手前のイロなんかになるもんかよ‥‥‥‥‥‥誰がお前のケツの穴なんか、舐めてやるか！")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "それでは仕方ない、ここで死ぬのだな！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "やっぱり素手では勝ち目がないようだね‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (sound 'se 2)
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥e1_05.gpc")
  (image-mem 0 3)
  (proc 3)
  (text "「加藤」" 'br)
  (text "馬鹿な‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "わたしはあんたみたいなお偉い人間じゃないんでね、プライドなんて、どうでもいいんだよ。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "要は勝ちゃいいのさ！")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "こんな事をして日本はどうなる‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "なるようになるんだよ、馬鹿はお前さ。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "言っとくけど、この銃に入ってるのは麻酔弾じゃない、実弾だよ。あんたの命もここまでって訳さ。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "あばよ、やっぱりお前はケツの穴野郎だよ‥‥‥")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 5)
  (image-file "gpc¥e1_06.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (text-delay 1)
  (text "坂田ザイバツのトップ、坂田が殺されてから数日後。")
  (wait)
  (text-reset 14)
  (text "世界の各地に戦線を広げ過ぎた軍部は、あまりにも呆気なく敵軍の本土急襲を許し、我が国は戦いに敗れた。")
  (wait)
  (text-reset 14)
  (text "他国にはほとんど知られる事のなかった日本の内情を敵軍に暴露したのは、数人の内通者‥‥‥つまりわたし達の仕業だ。")
  (wait)
  (text-reset 14)
  (text "日本は、たった数人の内通者の為に敗北する事になったのだ。しかし、それを悲しむ者はごく少数しか居なかった。")
  (wait)
  (text-reset 14)
  (text "日本を支配するザイバツの象徴、サカタ・ネオテクのビルは、進攻してきた連合軍の手により爆破された。")
  (wait)
  (text-reset 14)
  (text "坂田ザイバツは消滅したのだ‥‥‥")
  (wait)
  (text-reset 14)
  (text "連合軍は非常に進んだ日本のサイバネ技術を高く評価し、千葉を独立した自治区、あるいは企業集合体とする事を決めた。")
  (wait)
  (text-reset 14)
  (text "そして、千葉に住む多くの移民達に市民権を与え、特にニューテク技術者に便宜を図る旨を発表した。")
  (wait)
  (text-reset 14)
  (text "それ以外の日本は占領軍の支配下にあり、ごく少数の日本人を頂点とする身分制度は廃止された‥‥‥")
  (wait)
  (text-reset 14)
  (text "ほとんどの軍人は占領軍の手により拘留され、軍事裁判にかけられるのを待っている。")
  (wait)
  (text-reset 14)
  (text "軍部とサカタ・ネオテクが開発していた機構＝システムの事を知る者は誰もいなくなった。わたし達を除いては。")
  (wait)
  (text-reset 14)
  (text "そして‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (delay 150 0)
  (image-file "gpc¥e1_07.gpc")
  (image-mem 0 3)
  (proc 3)
  (if (</>
       (//
        (? (= O 0))
        (sound '|| 2)
        (delay 50)
        (sound '|| 0)
        (sound '|| "uso¥xg_14.uso")
        (sound '|| 1)
        (nop@)
        (set-var P 14))
       (//
        (? (= O 1))
        (sound '|| 2)
        (delay 50)
        (sound '|| 0)
        (sound '|| "uso¥xg_14v.uso")
        (sound '|| 1)
        (nop@)
        (set-var P 14))))
  (text "「Lei-Fa」" 'br)
  (text "あいや〜っ、自由ね！")
  (wait)
  (text-reset 14)
  (text "外の世界は、暮れかけようとする太陽の光で、紅く染まっている。全てが美しい。まるで全身が洗われるようだ。")
  (wait)
  (text-reset 14)
  (text "「エリコ」" 'br)
  (text "まぶしぃッ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「ナナ」" 'br)
  (text "すごく奇麗ね、夕焼けって初めて見た！")
  (wait)
  (text-reset 14)
  (text "「ミツコ」" 'br)
  (text "外に出れるなんて十何年ぶりかしら、子供の頃以来だわ。")
  (wait)
  (text-reset 14)
  (text "やがて、太陽はビルの影に身を潜め、夜がやって来るだろう。でもその闇は今までの地下世界のそれとは違う、明らかに‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "意外と荒廃していないのね。軍の流していた情報がどれだけいい加減な物だったか、やっとわかったわ。")
  (wait)
  (text-reset 14)
  (text "「プリス」" 'br)
  (text "何が荒廃してない‥‥‥よ！　こんなローテクの極みみたいな所で生活出来るのかしら。")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "しばらくは、地下とこっちを行ったり来たりなんじゃないかしら。少なくとも地上がもう少し整備されるまではね。")
  (wait)
  (text-reset 14)
  (text "「プリス」" 'br)
  (text "占領軍の問題も片付いてはいないし、これからが大変だわ。")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "そう、あなた達はこれからね‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「プリス」" 'br)
  (text "やっぱり行ってしまうの‥‥‥あなた達ふたりは？")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "私達はここには居られないわ。戦犯として裁かれるのは嫌だもの。軍関係者は根こそぎやられるわよ。")
  (wait)
  (text-reset 14)
  (text "「プリス」" 'br)
  (text "まあね、私は何とか罪を免れたけど。")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "せっかく地上に出られたのに刑務所の中なんて、絶対に嫌だわ。それについては、ふたりとも同じ意見なの。")
  (wait)
  (text-reset 14)
  (text "「プリス」" 'br)
  (text "そう‥‥‥気をつけてね。")
  (wait)
  (text-reset 14)
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥e1_08.gpc")
  (image-mem 0 3)
  (proc 3)
  (text "「Anna」" 'br)
  (text "心残りなのではなくて？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "今さら言っても仕方ない、こうなる運命だったと思って諦めるしかないね。")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "アンナ、これから行く所は寒いかい？")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "そうね‥‥‥ここよりはずっとね。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "カムチャッカ経由で５時間か、寝ていればあっと言う間だ。")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "何をそんなに恐れているの？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "寒いのは好きじゃないんだ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "大丈夫よ、寒かったらふたりで温めあえばいいでしょう？")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "前にそうしたようにね。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "そうしよう。そうすれば、きっと耐えられるだろうさ‥‥‥")
  (wait)
  (text-reset 14)
  (exec-mem 3072 0)
  (flag-load 9 1)
  (nop@)
  (set-reg 999 #t)
  (flag-save 9)
  (exec-mem 256 "E")
  (exec-mem 9504 "E")
  ((cmd 203) 0 1)
  (exec-mem 25984 1)
  (exec-mem 25984 3 582)
  (load-mem "tcm¥roll.tcm" 7936)
  (load-mem "tcm¥rooldat.txt" 34048)
  (exec-mem 7936 0 34048 3 0 0 24 7)
  (exec-mem 25984 3)
  ((cmd 209) 0 5 0)
  (image-file "gpc¥b12_01.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5 0)
  (exec-mem 25984 3)
  ((cmd 209) 0 5 0)
  (image-file "gpc¥b11_01.gpc")
  (image-mem 0 3)
  (image-file "gpc¥b11_01a.gpc")
  (image-mem 1 0)
  ((cmd 209) 1 5 0)
  (exec-mem 25984 3)
  ((cmd 209) 0 5 0)
  (image-file "gpc¥b10_01.gpc")
  (image-mem 0 3)
  (image-file "gpc¥b10_01b.gpc")
  (image-mem 1 0)
  ((cmd 209) 1 5 0)
  (exec-mem 25984 3)
  ((cmd 209) 0 5 0)
  (image-file "gpc¥b09_01.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5 0)
  (exec-mem 25984 3)
  ((cmd 209) 0 5 0)
  (image-file "gpc¥b09_02.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5 0)
  (exec-mem 25984 3)
  ((cmd 209) 0 5 0)
  (image-file "gpc¥b08_01.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5 0)
  (exec-mem 25984 3)
  ((cmd 209) 0 5 0)
  (image-file "gpc¥b08_02.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5 0)
  (exec-mem 25984 3)
  ((cmd 209) 0 5 0)
  (image-file "gpc¥b07_01.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5 0)
  (exec-mem 25984 3)
  ((cmd 209) 0 5 0)
  (image-file "gpc¥b06_01.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5 0)
  (exec-mem 25984 3)
  ((cmd 209) 0 5 0)
  (image-file "gpc¥b05_02.gpc")
  (image-mem 0 3)
  (image-file "gpc¥b05_02a.gpc")
  (image-mem 1 0)
  ((cmd 209) 1 5 0)
  (exec-mem 25984 3)
  ((cmd 209) 0 5 0)
  (image-file "gpc¥b04_01.gpc")
  (image-mem 0 3)
  (image-file "gpc¥b04_01a.gpc")
  (image-mem 1 0)
  ((cmd 209) 1 5 0)
  (exec-mem 25984 3)
  ((cmd 209) 0 5 0)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (sound '|| 2)
  (delay 100 0)
  ((cmd 209) 0 5 0)
  (image-file "gpc¥ides96.gpc")
  (image-mem 0 3)
  (sound '|| 0)
  ((cmd 209) 1 5 0)
  (wait 200)
  ((cmd 209) 0 5 0)
  (image-file "gpc¥cm1_a.gpc")
  (image-mem 0 3)
  (image-file "gpc¥cm1_b.gpc")
  (image-mem 0 0)
  ((cmd 209) 1 5 0)
  (wait 400)
  ((cmd 209) 0 5 0)
  (exec-mem 7936 1)
  (exec-mem 25984 0)
  ((cmd 203) 0 0)
  (text-frame 0 0 79 399)
  (text-reset 1)
  ((cmd 209) 1 5)
  (text-frame 10 312 70 370)
  (text "　　　　　ゲームを終了して、ＤＯＳに戻ります。" 'br)
  (text "　　　　　クリックして下さい。")
  (wait)
  ((cmd 212)))
 (seg*))