(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  ((cmd 209) 0 5)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (image-file "gpc¥e2_01.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (text-frame 10 312 70 383)
  (text "「Kiyomi」" 'br)
  (text "よくも今まで、人をあごでこき使ってくれたね。たかが移民のくせしてさ！")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "ううっ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "痛いか、苦しいか？　もうちょっとの辛抱だ、もうすぐ何も感じなくなっちまうんだからさ！")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "お、お願い‥‥‥キヨミ、よく考えて‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "まだ言ってやがる。そんな手には乗らないんだよ！　誰がお前の命令なんかきくもんか。")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "ああ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "くっくっくっ‥‥‥はっ、ざまないね！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "待ってな。加藤との取り引きに成功したら、お前を加藤に差し出してやる。頭ん中を弄られる前に、可愛がってもらいなよ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "あんたと＊＊＊出来るとなったら、あいつも泣いて悦ぶだろう！" 'br)
  (text "今まで散々見下されてきた相手なんだからさ！")
  (wait)
  (text-reset 14)
  (text "「Anna」" 'br)
  (text "キヨミ‥‥‥あなた、狂ってるわ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "狂ってなんかいるもんか！　わたしは権力を手に入れるんだ。それもとびきりデカイ奴を！")
  (wait)
  (text-reset 14)
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥e2_02.gpc")
  (image-mem 0 3)
  (proc 3)
  (text "「Lei-Fa」" 'br)
  (text "あァァァァン！")
  (wait)
  (text-reset 14)
  (text "「エイプリル」" 'br)
  (text "し、死んじゃう‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "もっと苦しみな、デカイ声で鳴くんだよ！")
  (wait)
  (text-reset 14)
  (text "「ミツコ」" 'br)
  (text "こ、こんな事になるなんて‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「ナナ」" 'br)
  (text "い、痛ッ‥‥‥もう止めてよォ！")
  (wait)
  (text-reset 14)
  (text "「エイプリル」" 'br)
  (text "し、喋るんじゃない‥‥‥こいつの思うつぼだよ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "うるさいよ！")
  (wait)
  (text-reset 14)
  (text "「エイプリル」" 'br)
  (text "あうぅぅッ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「プリス」" 'br)
  (text "はッ、あァァァッ！")
  (wait)
  (text-reset 14)
  (text "「エリコ」" 'br)
  (text "いたいのイヤァ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「プリス」" 'br)
  (text "耐えるのよ、どうせこの女もいつか同じ目にあうんだから！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "くっくっくっ、そんな事がある訳ない。わたしはお前らとは違うんだからね！")
  (wait)
  (text-reset 14)
  (text "「Lei-Fa」" 'br)
  (text "はぁぁぁぁぁン！")
  (wait)
  (text-reset 14)
  (text "「エイプリル」" 'br)
  (text "ひぃぃぃッ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「ナナ」" 'br)
  (text "んっ、痛いッ！")
  (wait)
  (text-reset 14)
  (text "「ミツコ」" 'br)
  (text "うぅぅっ‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「エリコ」" 'br)
  (text "こ、こんなのイヤァ！")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 5)
  (image-file "gpc¥e2_03.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (text "「加藤」" 'br)
  (text "どうした、少佐。何か用かな？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "もちろんさ、わたしが用もなしにこんな所に来る訳がない。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "そうだな。ところで、アンナ大佐の尋問は進んでいるのだろうな？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "さあ、その話さ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "ほう、話を聞こうではないか。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "わたしは知っちまったんだ。あんたら軍部が何をやらかそうとしてるのかをさ。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "全国民のマインドコントロール、超兵士の製造。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "ポッドモッドで国民の感情を殺して、この国の支配をより強固にしようって計画をさ。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "だから‥‥‥どうした。それを貴様に知られたところで、我々が困るとでも思っているのか？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "そう尖がらなくてもいいだろう、話はこれからさ。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "アンナが残りの機密を何処に隠したか、知ってるのはわたしだけ。そこで取り引きしようじゃないか。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "機密の所在を教えるから、わたしをあんたの部下にしてよ。他人にあごで使われるのは、もうまっぴらよ。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "貴様を私の部下にだと？　どういう風の吹き回しだ。貴様は私の事が大嫌いだったのではないのか？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "風向きが変われば、わたしも考えを改めない訳にはいかない。それに、わたしを部下にしてくれれば、お楽しみも増えるよ。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "ほう‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "悪い話じゃないだろう？")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "そのお楽しみとやらを、少し味見させてもらおうか。私の気に入れば、考えてやらないでもない。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "スケベな男だね‥‥‥いいよ、たっぷり味わいな。")
  (wait)
  (text-reset 14)
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥e2_04.gpc")
  (image-mem 0 3)
  (proc 3)
  (text "「Kiyomi」" 'br)
  (text "くッ‥‥‥はぁッ！")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "まさか、私の事を一番嫌っていた貴様が、私とまぐわう事になるとはな。思ってもみなかった事だ。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "よ、余計な事は言わないで‥‥‥もっと強く！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "は、はァァン‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "私の持ち物の具合はどうだ？　貴様は私の事をオカマ野郎とか呼んでいたのではなかったか。私はオカマ野郎か？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "ち、違うわ‥‥‥ンンッ！　す、すごくいい‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "凄腕の女情報部員も、こうなってはかたなしだな。ただの女と何も変わらんではないか！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "んっ、んんッ！　ど、どうなの、わたしの味は‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "悪くない、いい締まりだ。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "アッ‥‥‥アアッ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "お願いよ、わたしをあんたの部下に！")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "よかろう。一生私の情婦として、側に置いてやる‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "ああ、うれしいわ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "もっと腰を振れ！　私を満足させる事が出来なければ、私の部下にしてやる訳にはいかんからな！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "んっ、んっ、んん〜ッ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "も、もう誰かに命令されるのは嫌‥‥‥わたしは誰かを支配する側に回りたいのよ！")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "してやる。この作戦が成功すれば、私は軍の中で下にも置かれぬ存在になるはずだ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "そうなった時は、貴様に‥‥‥‥‥‥アンナ大佐は盗んだ機密を何処に隠したのだ？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "アンナは盗んだ機密を、自分達の頭の中のチップに隠してる‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "なるほどな‥‥‥思ったとおりだ。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "んんッ！　んッ‥‥‥も、もう駄目！")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "イッてしまっていいのだぞ。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "い、一緒に‥‥‥わたしの中に注ぎ込んで！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "アッ！　アァァァッ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 5)
  (image-file "gpc¥e2_05.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (text "「加藤」" 'br)
  (text "くっくっくっ‥‥‥馬鹿者共が。我々の計画を阻止するなど、本当に出来ると思っていたのか。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "まったくだ、馬鹿な奴らさ。その上このわたしを仲間にしようとまで考えたんだからね。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "哀れなもんだね‥‥‥もうすぐ頭の中を弄り回されて、何にも感じなくなっちまう。自分で招いた事とはいえ、少し可哀想だよ。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "貴様は迷わなかったのか？　アンナは貴様の愛人だったのだろう？その女に誘われても全く意志が揺るがなかったと？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "もちろんさ。移民の女なんかにそそのかされて、はいそうですかって訳にはいかないからね。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "損得勘定で、アンナよりも私についた方がよいと思ったのだな？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "当たり前だろ？　人間なんてそんなもんさ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "ある意味で、非常に誠実と言えない事もない。ただし、自分に対してだがな。自分の欲望に誠実であったと言えるだろう。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "ふふっ‥‥‥結局、それが一番正しいやり方なのさ。でも、少し惜しいと思わない？　これだけの数の女を台無しにしちまうのは。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "貴様が居れば十分だろう？　欲を張ると、ろくな事にはならん。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "うれしい事を言ってくれるじゃない。まあ、わたしがこいつらより劣るとは思わないけどね。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "そうだ、貴様にあれを見せてやろう‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "あれ‥‥‥ってのは何なの？")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "いいから付いて来い‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥e2_06.gpc")
  (image-mem 0 3)
  (proc 3)
  (exec-mem 11680 0)
  (repeat 10 (<> (exec-mem 7072 0 14 13 15 1) (exec-mem 7072 0 13 12 15 1)))
  (exec-mem 7936 0)
  (text "「Kiyomi」" 'br)
  (text "これは‥‥‥子供？")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "遺伝子操作で産まれた、新しい人類だ。我々よりはるかに優れた運動能力を持ち、苦痛も恐怖も感じない。まさに最強の兵士。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "彼等の成長速度は、通常の１０倍以上。もうすぐガラス管から母親の子宮に移される。数週間後には出産だ。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "本当に生きてる‥‥‥見ようによっては、可愛くないとも言えないかもね。わたしには、グロテスクな物としか感じないけど‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "彼等は出産後すぐに電脳移植を受け、我々の命令に完全に従う超兵士の誕生となる。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "もっとも、これは試作段階だからな、実際にこのような行程で実行される事はないだろう。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "と、言うと‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "民衆のマインドコントロールが成功すれば、最初から母体の中で彼等を育てる事が出来る、誰も文句は言わぬのだからな。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "工場みたいな所に、胎内に化け物を宿した女達が横たわってるの？ひどくシュールな光景だろうね。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "一度に数百単位の超兵士を生産するには、やむを得ぬ。国をあげての大事業になるだろうな。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "首のとこに電極が入ってる‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "定期的に電気的刺激を与える事で、脳の発育をコントロールする事が出来る。彼等には不必要な部分も有るからな。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "こいつら、夢は見るのかい？")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "何だって？")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "何でもない‥‥‥それで、こいつらの母親になるのは？")
  (wait)
  (text-reset 14)
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥e2_07.gpc")
  (image-mem 0 3)
  (proc 3)
  (text "「加藤」" 'br)
  (text "彼等の母親になるのは‥‥‥お前だ！")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "なッ‥‥‥何をするのよ！")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "お前はもう用済みという訳だ。貴様は私の部下には出来ぬ。あまりに野心的過ぎるからな。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "なんだって‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "いつ自分の寝首をかくかも知れぬ女など、必要ないのだよ。私にもこの日本にも、だ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "放せッ！　話が違うじゃないか！")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "私の話を信じていたのか？　馬鹿な女だ。私としては、こんなありきたりの結末など、望んではいなかったのだが‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "わたしをどうするつもりさ！　わたしは実験台になるなんて、死んでもお断りだよッ！")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "貴様には残りの女共と一緒に、実験に協力してもらう。我々が創ったこの子らの母親になるのだ。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "冗談じゃないわ‥‥‥そんなの嫌よ！")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "すぐに何も考えられなくなる、あの女達と同じようにな。超兵士の製造工場になるのだ。")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text "ああ、そんな‥‥‥")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 5)
  (image-file "gpc¥e2_08.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (text "「坂田」" 'br)
  (text "ほう、この８人が新しい被験者ですな？")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "左様、何れも軍部に謀反を働こうとした犯罪者だからな、何をしても文句を言う者は居らんはず。")
  (wait)
  (text-reset 14)
  (text "「坂田」" 'br)
  (text "あそこに座っている女は‥‥‥以前に見た事がございますな。確か情報部の将校だったのでは？")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "それを言うなら、部屋の隅に座っているのは貴様の娘だ。")
  (wait)
  (text-reset 14)
  (text "「坂田」" 'br)
  (text "さて‥‥‥私にあんな大きな娘が居りましたかな？　記憶にありませんが。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "結構‥‥‥実に結構。それでは近日中に実験を再開してもらおう。彼女らもそれを望んでいるだろうからな！")
  (wait)
  (text-reset 14)
  (text "「坂田」" 'br)
  (text "は、必ず‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "くっくっくっ‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 10)
  (delay 150 0)
  (flag-load 9 1)
  (nop@)
  (set-reg 1001 #t)
  (flag-save 9)
  (exec-mem 3072 0)
  (mes-jump "mes¥endstaff.mes")))