(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= Y 0) (= 991 #f))
   (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
   (text-frame 0 0 79 399)
   (text-reset 14)
   (image-file "gpc¥a1_63.gpc")
   (image-mem 0 3)
   (image-file "gpc¥a1_63a.gpc")
   (image-mem 1 0)
   (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
   (exec-mem 256 "E")
   (load-mem "clm¥A1_63.clm" 32768)
   (text-frame 10 312 70 370)
   (exec-mem 256 "I")
   (exec-mem 256 "A 0")
   (exec-mem 18688 5 1 0)
   (exec-mem 256 "G 0 33 240 21 160")
   (proc 10)
   (branch-reg
    77
    (</>
     (/
      (text "「Anna」" 'br)
      (text "あなた達‥‥‥どうやって牢を抜け出して来たの？")
      (wait)
      (text-reset 14)
      (text "「エリコ」" 'br)
      (text "アンナ、だいじょうぶ？")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "酷い事を‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "許さないね、今度こそ負けないよ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Anna」" 'br)
      (text "待って！　キヨミは敵じゃないわ、私達の仲間になったの！")
      (wait)
      (text-reset 14)
      (text "「エイプリル」" 'br)
      (text "こいつが仲間に？　そんなの信じられないわよ！")
      (wait)
      (text-reset 14)
      (text "「ミツコ」" 'br)
      (text "そうよ、この女にどんな酷い事をされたと思っているの？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "なんだ、やるってのかい！　あれだけ酷い目にあったのに、まだ懲りてないのかい。")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "ほら、ごらんなさい。アンナは騙されてるのよ、この女は根っからの下衆野郎なんだから。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "「Kiyomi」" 'br)
      (text "お前ら、どうやって牢を抜け出した？")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "そんな事はどうでもいいでしょう！　あなた、アンナから全部聞いたんでしょう、拷問なんて止めて私達と‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "黙んな！　お前らの戯言は、もう聞き飽きたんだよ。アンナから離れるんだ。さもないと、もっと酷い拷問にかけるよ！")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "みんな何をしているの。早くアンナを助けて、ここを脱出するの！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "その女は、助けるに値しないよ。そいつがあんた達に何をしたのか知ってるのかい！")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "どういう意味なの？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "アンナはね、あんた達の頭の中のチップに機密を隠したんだ。その事を知ってるのか？")
      (wait)
      (text-reset 14)
      (text "「エリコ」" 'br)
      (text "どういうこと？　アンナ、わたしたちに何したの？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あんた達の頭骸に入ってるチップから情報を取り出すには、脳の中を弄り回すしかないんだ、あんたら廃人になっちまうのさ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "アンナはその事を知ってて、そうしたんだ。あんたらの命を犠牲にしても屁とも思ってない、傲慢な女なんだよ。そいつは！")
      (wait)
      (text-reset 14)
      (text "「Anna」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11)
   (exec-mem 3968 102 500 360)
   (exec-mem 3072 1)
   (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (?
       (= S 1)
       (= 133 #t)
       (= 135 #t)
       (= 136 #t)
       (= 137 #t)
       (= 138 #t)
       (= 139 #t))
   (proc 10)
   (sound '|| 2)
   (delay 50)
   (sound '|| 0)
   (branch-reg
    77
    (</>
     (/
      (text "「Kiyomi」" 'br)
      (text "わかったよ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あんた達の気の済むようにすりゃいいさ。縄で吊るして、鞭打ちでもすりゃいいだろ！")
      (wait)
      (text-reset 14)
      (text "「Anna」" 'br)
      (text "キヨミ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「エイプリル」" 'br)
      (text "ふん、いい度胸してるじゃない。７人がかりで拷問されたら、どんな事になるかわからない訳じゃないでしょう。")
      (wait)
      (text-reset 14)
      (text "「ナナ」" 'br)
      (text "やっちゃえ！　目茶苦茶にしてやればいいんだ！")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "そういうのは趣味じゃないけど、みんな納得しないからね‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Anna」" 'br)
      (text "待って、わかったわ。皆の気の済むようにするから！")
      (wait)
      (text-reset 14)
      (text "「Anna」" 'br)
      (text "そのかわり、私とキヨミだけでやるわ。他の皆は黙って見てて。")
      (wait)
      (text-reset 14)
      (text "「ナナ」" 'br)
      (text "それじゃ、何の解決にもならないじゃない。アンナはそいつと恋人同士だったんでしょ？")
      (wait)
      (text-reset 14)
      (text "「ミツコ」" 'br)
      (text "アンナに拷問なんて出来るの？")
      (wait)
      (text-reset 14)
      (text "「Anna」" 'br)
      (text "出来ないわ‥‥‥だから、私とキヨミが交わるところを見て頂戴。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "アンナ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "あなたにとっては、かなりの苦痛だと思うけど‥‥‥人前で恥態を晒すなんてね。でも、彼女にとってはどうなの？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "それじゃ、拷問はなしにしてあげるわ。そのかわり、私達も一緒にするってのはどう？")
      (wait)
      (text-reset 14)
      (text "「Anna」" 'br)
      (text "キヨミさえよければ‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "言ったろ、あんた達の好きなようにすればいいって‥‥‥")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "それじゃ決まりね、みんなも異存はないでしょう？")
      (wait)
      (text-reset 14)
      (text "「ミツコ」" 'br)
      (text "構わないけど‥‥‥")
      (wait)
      (text-reset 14)
      (text "「ナナ」" 'br)
      (text "そんなの優しすぎるよ！")
      (wait)
      (text-reset 14)
      (text "「エイプリル」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "私達は、軍や坂田みたいな人でなしとは違うわ。人を愛する事が出来る、信じる事もね。")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "こいつがアンナを愛してるなら、裏切ったりしないね。")
      (wait)
      (text-reset 14)
      (text "「Anna」" 'br)
      (text "ありがとう‥‥‥")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "さあ、始めるよ‥‥‥")
      (wait)
      (text-reset 14)
      (proc 11)
      (exec-mem 3072 0)
      (mes-jump "mes¥ME_02.MES"))
     (/
      (if (</>
           (//
            (? (= O 0))
            (sound '|| 2)
            (delay 50)
            (sound '|| 0)
            (sound '|| "uso¥xg_02.uso")
            (sound '|| 1)
            (nop@)
            (set-var P 2))
           (//
            (? (= O 1))
            (sound '|| 2)
            (delay 50)
            (sound '|| 0)
            (sound '|| "uso¥xg_02v.uso")
            (sound '|| 1)
            (nop@)
            (set-var P 2))))
      (text "「ナナ」" 'br)
      (text "あんた、救いようのないバカよ！　軍の言いなりになったら、どうなっちゃうかわからないの？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "何とでも言いな‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "アンナ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Anna」" 'br)
      (text "御免なさい、こんな事になってしまって‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Anna」" 'br)
      (text "あなた達を巻き込んでしまった事を、申し訳なく思ってるわ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「ミツコ」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「エイプリル」" 'br)
      (text "この国には希望なんて、これっぽっちもないんだ。所詮、移民は移民、いつまで経ってもそれ以上にはなれないのよ！")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "それでも、戦場でのたれ死ぬよりはマシかもね‥‥‥")
      (wait)
      (text-reset 14)
      (text "「エリコ」" 'br)
      (text "みんな、どうしてそんなに悲しそうなの？　これからどうなるの？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "皆で涙に暮れてる所に水を差して悪いけど、そろそろお終いにしてもらおうかね！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "わたしは湿っぽいのは嫌いでね！")
      (wait)
      (text-reset 14)
      (text "「Anna」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "これから‥‥‥どうするつもりなの‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "さあ、それだ！　わたしとしては、あんた達をこのまま軍部に引き渡すのもあんまり気が進まないんでね。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "わたしからのせめてもの贐ってやつ、最後にもう一度可愛がってやるってのはどうだ？")
      (wait)
      (text-reset 14)
      (text "「Anna」" 'br)
      (text "キヨミ！")
      (wait)
      (text-reset 14)
      (text "「ナナ」" 'br)
      (text "そっ、そんなの嫌よ！")
      (wait)
      (text-reset 14)
      (text "「ミツコ」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "じたばたしても無駄さ、どうせあんた達はもうすぐ何も感じられなくなっちまうんだ。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "最後に苦痛をよく味わっとくのも、悪くないだろうさ！")
      (wait)
      (text-reset 14)
      (text "「Anna」" 'br)
      (text "ああ、キヨミ‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "それじゃ、せいぜい楽しんでくれよな！")
      (wait)
      (text-reset 14)
      (proc 11)
      (exec-mem 3072 0)
      (mes-jump "mes¥ME_03.MES")))))
 (seg (? (= S 1) (= 133 #f))
   (proc 10)
   (branch-reg
    77
    (</>
     (/
      (text "「Anna」" 'br)
      (text "皆聞いて、キヨミがあなた達に酷い事をしたのは、私の命令に従っただけなのよ。だから、悪いのは私なのよ！")
      (wait)
      (text-reset 14)
      (text "「ナナ」" 'br)
      (text "とてもそうは見えなかったけど？　この人、拷問するのが好きでたまらないのよ。")
      (wait)
      (text-reset 14)
      (text "「Anna」" 'br)
      (text "たとえそうだとしても、軍の行為が許せなくて私達と一緒に戦うと言うのなら、私達の仲間に違いないわ！")
      (wait)
      (text-reset 14)
      (text "「エイプリル」" 'br)
      (text "そんな単純なもんかね‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "言わせてもらえば、この女が私達にした事と同じぐらいの苦痛を受けてくれなければみんなの恨みは晴れないと思うわよ。")
      (wait)
      (text-reset 14)
      (text "「ミツコ」" 'br)
      (text "そうよ！　あんな恥ずかしい思いをさせられて‥‥‥")
      (wait)
      (text-reset 14)
      (text "「ナナ」" 'br)
      (text "このバカにも同じ事をしてやるのよ、みんなでね！")
      (wait)
      (text-reset 14)
      (text "「Anna」" 'br)
      (text "そんな‥‥‥それでは何の解決にもならないわ。軍とやってる事が同じじゃないの。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "「Anna」" 'br)
      (text "何を言っても、あなたの気持ちは変わらないでしょうね‥‥‥")
      (wait)
      (text-reset 14)
      (text "「エイプリル」" 'br)
      (text "何を言ってるの、この女を殺してここを出ましょう！　私達全員の力を合わせればこんな女ひとり、簡単に殺せるわよ。")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "そうかな‥‥‥私達は、拷問で弱ってる。それに‥‥‥")
      (wait)
      (text-reset 14)
      (text "「ミツコ」" 'br)
      (text "追っ手をかわすのは難しいわ。何ヶ月か身を隠す事は出来ても、それだけの話よ。いずれ狩られるわ、今回のように。")
      (wait)
      (text-reset 14)
      (text "「エイプリル」" 'br)
      (text "あんたまでそんな事を。それじゃ、全部無駄だったって言うの？")
      (wait)
      (text-reset 14)
      (text "「Anna」" 'br)
      (text "どうやらこれまでみたい。私達、随分頑張ったけれど、所詮は素人の集まりだったのよ、本物のテロリストにはなれないわ‥‥‥")
      (wait)
      (text-reset 14)
      (text "「エイプリル」" 'br)
      (text "そんな簡単に諦めていいのかよ、奴等の思いどおりにさせて！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "相談はまとまったか？　それじゃ、そろそろ観念してもらおうか。")
      (wait)
      (text-reset 14))))
   (nop@)
   (set-reg 133 #t)
   (proc 11))
 (seg (? (= S 1) (= 133 #t))
   (proc 10)
   (branch-reg
    77
    (</>
     (/
      (text "「Anna」" 'br)
      (text "キヨミ‥‥‥皆に謝って、あなたが私達の味方だって証明するの！私達が団結しなければ、軍の計画を阻むのは不可能よ。")
      (wait)
      (text-reset 14))
     (/
      (text "「Anna」" 'br)
      (text "どうやらこれまでみたい。私達、随分頑張ったけれど、所詮は素人の集まりだったのよ、本物のテロリストにはなれないわ‥‥‥")
      (wait)
      (text-reset 14))))
   (proc 11))
 (seg (? (= S 2) (= 135 #f))
   (proc 10)
   (branch-reg
    77
    (</>
     (/
      (text "「Lei-Fa」" 'br)
      (text "確かに任務に忠実なのは、軍人として悪い事じゃないね。でもお前には、それ以外の理由があるね。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "お前は、あたしを嬲る事が、楽しくて仕方ないって感じだったね！もしも仲間になりたいなら、それなりの罰を受けるべきね。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "罰ってのは、何なのさ。")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "お前があたしにしたのと、同じ事をするね。鞭で打って、あたし達の前でオシッコさせるね！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "「Kiyomi」" 'br)
      (text "お前らは、もうすぐ軍部の下衆野郎に頭の中をかき回されて、何もわからなくなっちまうんだ。")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "でも、その方が幸せかもしれないな。どうせ機密を取り出された後は飢えた軍の変態野郎どもに慰み者にされるんだ。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "何にも感じない方がマシだろう？")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "そんな事はさせないね‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ああ、そうかい。それじゃどうするってんだ？　わたしを倒して、この建物から逃げ果せる事が可能だとでも思ってるのか？")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (nop@)
   (set-reg 135 #t)
   (proc 11))
 (seg (? (= S 2) (= 135 #t))
   (proc 10)
   (branch-reg
    77
    (</>
     (/
      (text "「Lei-Fa」" 'br)
      (text "お前は、あたしを嬲る事が、楽しくて仕方ないって感じだったね！もしも仲間になりたいなら、それなりの罰を受けるべきね。")
      (wait)
      (text-reset 14))
     (/ (text "「Lei-Fa」" 'br) (text "‥‥‥‥‥‥‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= S 3) (= 136 #f))
   (proc 10)
   (branch-reg
    77
    (</>
     (/
      (text "「ナナ」" 'br)
      (text "まさか、自分が何をしたか忘れたなんて言わないでしょうね！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ああ、覚えてるさ。確かあんたは、恋人のミツコよりもわたしの方がずっと好きだって言ってた。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ヒイヒイよがりながら、わたしの言うことなら何でもするって言ってたよねぇ。")
      (wait)
      (text-reset 14)
      (text "「ナナ」" 'br)
      (text "うるさいわね、余計な事は言わないでいいの！　そんな人間をどうして信じられるのよ。")
      (wait)
      (text-reset 14)
      (text "「ナナ」" 'br)
      (text "人を拷問して、無理矢理言うことを聞かせるような人間を仲間にするなんて、無茶よ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "「Kiyomi」" 'br)
      (text "あんたの事は、特別目をかけてやったんだ。それを忘れちゃいないだろうね？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "特に念入りに可愛がってやったろう？　それも、お前がわたし好みのペットだったからさ。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "それは今でも変わってない。お前だけは、いつまでも可愛い牝猫として、わたしの側に置いといてやる。")
      (wait)
      (text-reset 14)
      (text "「ナナ」" 'br)
      (text "そ、そんなのお断りよ、バカ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ただ、残念なのはお前にそれを理解するだけの判断力が残されていないって事だな。まあ、それもまた一興ではあるけど。")
      (wait)
      (text-reset 14)
      (text "「ナナ」" 'br)
      (text "いっ、嫌よ‥‥‥誰か何とかしてよ、エイプリル‥‥‥レイファ！")
      (wait)
      (text-reset 14)
      (text "「エイプリル」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Lei-Fa」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (nop@)
   (set-reg 136 #t)
   (proc 11))
 (seg (? (= S 3) (= 136 #t))
   (proc 10)
   (branch-reg
    77
    (</>
     (/
      (text "「ナナ」" 'br)
      (text "まさか、自分が何をしたか忘れたなんて言わないでしょうね！")
      (wait)
      (text-reset 14))
     (/ (text "「ナナ」" 'br) (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= S 4) (= 137 #f))
   (proc 10)
   (branch-reg
    77
    (</>
     (/
      (text "「ミツコ」" 'br)
      (text "私は、あなたの事をそれ程嫌いじゃないわ、そりゃひどい事もされたけど。あなたは他の日本人とは違う。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「ミツコ」" 'br)
      (text "この街は腐ってるわ。それも全部軍部のせいよ、それと一部の金持ち達のせい。このままではいけないと思わない？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "あんただって、その金持ちのひとりだろう？")
      (wait)
      (text-reset 14)
      (text "「ミツコ」" 'br)
      (text "でも、私はこの人達と一緒にやる決心をしたわ。あなたもそうならいいんだけど‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "人の本心なんて、わかりっこないさ。何を言ってもね、口で言うだけじゃ何にもならない。")
      (wait)
      (text-reset 14)
      (text "「ミツコ」" 'br)
      (text "それがわかってるなら、私達に証明して。私達の仲間だって事を。出来ないなら、あなたを信じる事は無理だわ。")
      (wait)
      (text-reset 14))
     (/
      (text "「Kiyomi」" 'br)
      (text "この中で一番酷い目にあいそうなのは、お前だね。同胞を裏切るのは、特に罪が重い。")
      (wait)
      (text-reset 14)
      (text "「ミツコ」" 'br)
      (text "この街は腐ってるわ。それも全部軍部のせいよ、それと一部の金持ち達のせい。このままではいけないと思わない？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "そうは思わないね。虐げられるのが嫌なら、支配する側に回ればいいのさ。どんな事をしてもね！")
      (wait)
      (text-reset 14)
      (text "「ミツコ」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "せいぜい愛想よくするんだね。わたしにじゃない、軍の連中にだ。そうすりゃ、少しは苦痛を減らしてくれるだろうさ。")
      (wait)
      (text-reset 14)
      (text "「ミツコ」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (nop@)
   (set-reg 137 #t)
   (proc 11))
 (seg (? (= S 4) (= 137 #t))
   (proc 10)
   (branch-reg
    77
    (</>
     (/
      (text "「ミツコ」" 'br)
      (text "私達に証明して、私達の仲間だって事を。それが出来ないならあなたを信じるのは無理だわ。")
      (wait)
      (text-reset 14))
     (/ (text "「ミツコ」" 'br) (text "‥‥‥‥‥‥‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= S 5) (= 138 #f))
   (proc 10)
   (branch-reg
    77
    (</>
     (/
      (text "「エリコ」" 'br)
      (text "‥‥‥‥‥‥またいたくする？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "しないよ、絶対にね‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「エリコ」" 'br)
      (text "本当に、いたくしないのね？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "ああ。それどころか、保身のためにお前を売った、お前の親父を懲らしめてやるよ。タダじゃ済まさない。")
      (wait)
      (text-reset 14)
      (text "「エリコ」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "お前の親父は悪人だよ、放っておく事は出来ない。まだ親父さんが好きな訳じゃないだろう？")
      (wait)
      (text-reset 14)
      (text "「エリコ」" 'br)
      (text "お父さま、キライよ‥‥‥だいっキライ！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "だろうね‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "「Kiyomi」" 'br)
      (text "あんたの頭の中にも機密が入ってるってのは、残念だね。うまくすれば、あんただけは助かったかもしれないのに。")
      (wait)
      (text-reset 14)
      (text "「エリコ」" 'br)
      (text "‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "どういう意味かわからないか？　軍部はサカタ・ネオテクより優位に立つために、あんたを利用出来たって事さ。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "坂田の娘が機密を洩らしたってだけでも、サカタ・ネオテクは弱みを握られたって事になる。それでも十分に有効だけど‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "さらに、軍の手の内にあんたが居ればもっと都合がいい。まったく残念だけどね、仕方がない。")
      (wait)
      (text-reset 14)
      (text "「エリコ」" 'br)
      (text "これから‥‥‥どうなっちゃうの？")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "散々話したろう？　まだわからないのかい。お前はね、その少し足りない頭の中を弄り回されて、もっと馬鹿にされちまうんだよ。")
      (wait)
      (text-reset 14))))
   (nop@)
   (set-reg 138 #t)
   (proc 11))
 (seg (? (= S 5) (= 138 #t))
   (proc 10)
   (branch-reg
    77
    (</>
     (/ (text "「エリコ」" 'br) (text "‥‥‥‥‥‥またいたくする？") (wait) (text-reset 14))
     (/ (text "「エリコ」" 'br) (text "‥‥‥‥‥‥‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= S 6) (= 139 #f))
   (proc 10)
   (branch-reg
    77
    (</>
     (/
      (text "「プリス」" 'br)
      (text "アンナがあなたに惹かれた事は、わからなくもないわ。アンナとでは全く正反対だから。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "驚くほどタフで、世間に逆らっても反論を覆してしまうような、力強さがある。それに、何より健康だわ。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "だからって‥‥‥わたしとアンナがそういう関係だからって、あんたはわたしを信じはしないだろう？")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "でも、私達にあなたのようなプロの助けが必要なのも、確かだわ。今のままでは、これ以上事態が好転するとも思えないし。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "問題は、他の５人が納得するかって事ね‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "「Kiyomi」" 'br)
      (text "あんたも馬鹿な女だね、こんな事に手を染めなきゃ今のままの安泰な生活が続いたのに。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "元々、正義感が強いって訳じゃないだろ。わたしには、あんたはただの悪徳警官と同じに見えるよ。")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "‥‥‥‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "任務を遂行するのに熱心には見えないし、自分の命を危険に晒すなんてまっぴら御免って感じだけどね。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "アンナに恩でもあったのかい、あの女の申し出を断れない弱みが？まさか、アンナを愛していたとか？")
      (wait)
      (text-reset 14)
      (text "「プリス」" 'br)
      (text "どうでもいいでしょう‥‥‥どうせ助かりはしないんだから！")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "図星か！　それじゃ、わたしの事が憎くて仕方なかったろうね。今さら言っても仕方ないけど。")
      (wait)
      (text-reset 14)
      (text "「Kiyomi」" 'br)
      (text "せめて、死ぬ時は一緒に殺してやるよ。あんた達ふたりは軍関係の人間だから、銃殺は免れないだろうしね！")
      (wait)
      (text-reset 14))))
   (nop@)
   (set-reg 139 #t)
   (proc 11))
 (seg (? (= S 6) (= 139 #t))
   (proc 10)
   (branch-reg
    77
    (</>
     (/
      (text "「プリス」" 'br)
      (text "問題は、他の５人が納得するかって事ね‥‥‥‥‥‥")
      (wait)
      (text-reset 14))
     (/ (text "「プリス」" 'br) (text "‥‥‥‥‥‥‥‥‥‥‥‥") (wait) (text-reset 14))))
   (proc 11))
 (seg (? (= S 7) (= 140 #f))
   (proc 10)
   (branch-reg
    77
    (</>
     (/
      (text "わたしは、こいつらに歓迎されていないようだ。あれだけ酷い事をすれば、それももっともな話だが‥‥‥")
      (wait)
      (text-reset 14)
      (text "問題はわたし自身が軍部の計画、全国民をポッドモッドして意識操作をしようって計画に、我慢がならないって事だ。")
      (wait)
      (text-reset 14)
      (text "その計画の全貌を知っているのは、一部の軍関係者と、ここに居る８人だけ。計画を阻止出来るのはわたし達だけなのだ。")
      (wait)
      (text-reset 14)
      (text "今は感情で動いてる時じゃない。アンナ達がわたしのした事を怒ってると言うなら、彼女達の好きなようにさせればいい‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "軍部の計画が成功すれば、今の一部軍人とさらに少数のザイバツによる支配は、さらに揺るぎないものになる。")
      (wait)
      (text-reset 14)
      (text "超兵士とやらが大量生産されれば、戦争に勝つ事も不可能ではないだろう‥‥‥‥‥‥")
      (wait)
      (text-reset 14)
      (text "わたしがどうするべきか、それは火を見るより明らか。今のうちに軍部‥‥‥加藤に恩を売って、然るべき地位に登り詰めるのだ。")
      (wait)
      (text-reset 14)
      (text "キヨミ将軍‥‥‥いや、キヨミ元帥！　悪い気分じゃない。後はこいつらを加藤に引き渡せばいいんだ。")
      (wait)
      (text-reset 14)
      (text "いや‥‥‥")
      (wait)
      (text-reset 14)
      (text "その前に‥‥‥‥‥‥‥‥‥")
      (wait)
      (text-reset 14))))
   (nop@)
   (set-reg 140 #t)
   (proc 11))
 (seg (? (= S 7) (= 140 #t))
   (proc 10)
   (branch-reg
    77
    (</>
     (/
      (text "わたしは、こいつらに歓迎されていないようだ。あれだけ酷い事をすれば、それももっともな話だが‥‥‥")
      (wait)
      (text-reset 14))
     (/
      (text "わたしがどうするべきか、それは火を見るより明らか。今のうちに軍部‥‥‥加藤に恩を売って、然るべき地位に登り詰めるのだ。")
      (wait)
      (text-reset 14))))
   (proc 11)))