(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  ((cmd 209) 0 0)
  (image-file "gpc¥op_04.gpc")
  (image-mem 0 3)
  (text-frame 10 312 70 383)
  ((cmd 209) 1 0)
  (text-delay 10)
  (text "わたしは情報部のオフィスがある")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "赤坂方面へ向かっていた")
  (text-delay 0)
  (text "。")
  (text-delay 10)
  (text "軍服")
  (text-delay 0)
  (text-delay 10)
  (text "野郎は先刻から黙ったままで")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "合皮のシートに体を埋めている")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 10)
  (text "眼下に見える街の全景は")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "まるでシリコンの上に描かれた集積回路")
  (text-delay 0)
  (text-delay 10)
  (text "の配線のよう")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 10)
  (text "何処かのアーティストが暇潰しに造った")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "とびきり質の悪い奴")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 10)
  (text "ここは新帝都と呼ばれている")
  (text-delay 0)
  (text "。")
  (text-delay 10)
  (text "かつて戦争が始まった頃は")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "ただの")
  (text-delay 0)
  (text-delay 10)
  (text "巨大な防空壕だったらしい")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 10)
  (text "それが")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "地上にいる事が賢明でないと判明してから")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "新たな都市と")
  (text-delay 0)
  (text-delay 10)
  (text "して使われるようになった")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 10)
  (text "あまりに無計画な設計と増築のくり返しによって")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "ここは世界に類")
  (text-delay 0)
  (text-delay 10)
  (text "を見ない複雑怪奇な街となった")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「パイロット」" 'br)
  (text-delay 10)
  (text "気流が荒れてます")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "ベルトを締めて下さい")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 10)
  (text "ヘリの機体が発する不快な振動が")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "紫岩で麻痺した平衡器官をさら")
  (text-delay 0)
  (text-delay 10)
  (text "に痛めつける")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 10)
  (text "吐き気がする")
  (text-delay 0)
  (text "‥‥‥")
  (wait)
  (text-reset 14)
  (text-delay 10)
  (text "眠ってしまえればいくらか楽になれるのに")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "わたしの脳は埒もない")
  (text-delay 0)
  (text-delay 10)
  (text "妄想を紡ぎ続ける")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 10)
  (text "電脳空間＝サイバースペースの景色も")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "こんな風なのだろうか")
  (text-delay 0)
  (text "？　")
  (text-delay 10)
  (text "ローテクのわたしには見当もつかない")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 10)
  (text "でも")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "そんな世界を見てみたいとは思わない")
  (text-delay 0)
  (text "。")
  (text-delay 10)
  (text "わたしにとっては目")
  (text-delay 0)
  (text-delay 10)
  (text "に見えるこの光景が全てであり")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "それ以外は蜃気楼と大差ない")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 10)
  (text "それにしても寒い")
  (text-delay 0)
  (text "‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text-delay 10)
  (text "軍が暖房の為に使う電力を")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "他に回してるに違いない")
  (text-delay 0)
  (text "。")
  (text-delay 10)
  (text "もうこの国")
  (text-delay 0)
  (text-delay 10)
  (text "は長くないのかも")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 10)
  (text "身の振り方を考える時期なんだろうか")
  (text-delay 0)
  (text "？")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 5)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (image-file "gpc¥op_05.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (text-frame 10 312 70 383)
  (text "「キヨミ」" 'br)
  (text-delay 10)
  (text "で")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "わたしは何処に行けばいいわけ")
  (text-delay 0)
  (text "？")
  (wait)
  (text-reset 14)
  (text "「軍服の男」" 'br)
  (text-delay 10)
  (text "アンナ大佐のオフィスへ")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「軍服の男」" 'br)
  (text-delay 10)
  (text "急いで下さい")
  (text-delay 0)
  (text "！　")
  (text-delay 10)
  (text "もう随分待たせてしまっている")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text-delay 10)
  (text "なんだ")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "わたしを呼び出した命知らずって")
  (text-delay 0)
  (text "、")
  (text-delay 10)
  (text "アンナだったの")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (image-file "gpc¥op_06.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text-delay 0)
  (text "「キヨミ」" 'br)
  (text "それならそうと早くいいなよ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "アンナか‥‥‥")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "あいつ、ヤバい仕事しか回さないからな‥‥‥")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (image-file "gpc¥op_07u.gpc")
  (image-mem 0 3)
  (exec-mem 256 "I")
  (exec-mem 256 "A 1")
  (text-reset 14)
  (text-frame 10 312 70 383)
  (image-file "gpc¥op_07d.gpc")
  (image-mem 0 3)
  (exec-mem 256 "A 0")
  ((cmd 209) 1 0)
  (load-mem "tcm¥scrh.tcm" 7072)
  (exec-mem 7072 12 16 68 287 0 1 16 17)
  (load-mem "tcm¥palch.tcm" 7072)
  (load-mem "tcm¥gpcpalch.tcm" 7936)
  (load-mem "tcm¥mbuff.tcm" 9504)
  (text "「アンナ」" 'br)
  (text "随分遅かったわね‥‥‥キヨミ。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "休暇中に呼び出したくせに。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "どうせ有意義な休暇とは言えなかったのでしょう？")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "あなた、紫岩臭いわ。私としては部下がジャンキーになってくのを黙って見てる訳にはいかないの。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "商売は商売。遊びは遊び‥‥‥わたしのやってる事に口出しして欲しくはないね。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "いくらアンナでも。わかるだろ？")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "早いとこ任務＝ランの話をしなよ。その為に呼んだんだろ？")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "４人の囚人がある機密を持って脱獄したわ、囚人を捉えて機密を回収しなさい。")
  (wait)
  (text-reset 14)
  (text "酷く疲れているようだ。１０歳も老けこんだように見える。元々快活なんて言葉とは無縁の女だけど‥‥‥")
  (wait)
  (text-reset 14)
  (text "アンナはわたしの上官で現在の良人。いや、情婦と言うべきか。")
  (wait)
  (text-reset 14)
  (text "白ロシア人、元ＫＧＢという噂もきく。開戦まもなく国を逃げ出してきたクチだろうか？")
  (wait)
  (text-reset 14)
  (text "過去について多くを語ろうとはしないが、それが本当なら見た目通りの人間じゃない。少なくとも見掛けより２０年は生きていないと計算が合わない。")
  (wait)
  (text-reset 14)
  (text "もっとも、見掛けと中身が違う人間は、この街では珍しくない。")
  (wait)
  (text-reset 14)
  (text "サイバネ技術で臓器やら皮膚やらを取り替える事は可能だし、それ専門の闇医者は腐る程居るんだから。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "囚人４人のうち、２人は元特殊部隊。本物の殺し屋ね。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "１人は元兵士、もう１人はとある政府高官の秘書。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "‥‥‥それを、私に探せって？")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "一筋縄ではいかない相手よ。プロの手が必要なの。")
  (wait)
  (text-reset 14)
  (exec-mem 256 "E")
  (exec-mem 9504 "I")
  (exec-mem 9504 "M M128")
  (exec-mem 9504 "L gpc¥op_08.gpc,KEEP")
  (exec-mem 9504 "L gpc¥op_09.gpc,KEEP")
  (exec-mem 9504 "L gpc¥op_10.gpc,KEEP")
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_10.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text "「キヨミ」" 'br)
  (text "ちょい待ち、わたしはまだ引き受けた訳じゃない。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "大体、それはわたしの仕事じゃない。わかるだろ？")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "‥‥‥この任務は完全な極秘よ、査問も軍事法廷もなし。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "なるほど、切羽詰まった話って訳。だが、そいつはあんた方の事情で、わたしのじゃない。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "キヨミ、あなたの大好きな拷問の時間て訳よ。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "はん、そんな話には乗れないね！")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥そんな事言わないで。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "部下はわたしだけじゃないでしょう？")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "だけど！　事情が事情なのよ。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "だったらなおさらさ。鼠狩りはわたしの専門じゃない。")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_08.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text "「アンナ」" 'br)
  (text "他に信用出来る人間がいないのよ‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "そもそも、囚人が脱走したってだけでも十分奇異な事でしょう？")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "この世の中、何があっても不思議じゃない。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "私達は、内部の人間の手引きがあったと見てるわ。機密漏洩の穴もまだ塞がってないのよ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "そいつはご愁傷さま。でもわたしの知った事じゃない。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "そんな顔で見るなよ。そこの旦那の部下にいくらでもいるじゃない他人の尻の臭いを嗅ぎ回る専門家がさ！")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "キヨミ！")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "いつまで下らぬ戯言を繰っていれば気が済むのだ？")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_09.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text "「キヨミ」" 'br)
  (text "‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "貴様は特別なエージェントではない、重要な外部協力者でも。ただの情報部員のひとりに過ぎんのだ。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "お前に選択の余地などないと言っているのだ、わかるか？")
  (wait)
  (text-reset 14)
  (text "こいつの名前は加藤。軍の大物で、情報部の内務監査官でもある。つまり、他人の尻の臭いを嗅ぎまわる本物の下衆野郎。")
  (wait)
  (text-reset 14)
  (text "移民であるアンナや、ドロップアウトしてしまったわたしとは違って本物のエリートって訳。")
  (wait)
  (text-reset 14)
  (text "しかし、加藤とわたしに共通点が無い訳ではない。時折帽子の下から覗くサディスティックな眼はわたしのそれとそっくりだ。")
  (wait)
  (text-reset 14)
  (text "それに、加藤も脳に配線するのを拒んだクチ。わたしと同じ理由とは思えないが‥‥‥")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "大体、拷問専門の情報部員など認められるはずがないのだ。軍はお前の欲求を満たす為に、お前に給料を払っているのではない。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "そりゃどうも‥‥‥そっちのテクには定評があるんですけどね。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "キヨミ！　いいから黙って聞きなさい。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "囚人の名前はエイプリル、レイファ、ナナ、ミツコ。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "エイプリルは元特殊部隊、ヨーロッパ系の移民。レイファも同じ部隊に所属していた。中国人だ。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "ナナは元兵士、半分は日本人だ。凄腕のハッカーだったらしい。最後はミツコ‥‥‥純粋な日本人。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "ちょっと待って‥‥‥それだけなの？")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "プロファイルもホロの１枚すら無いの？")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_08.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text "「アンナ」" 'br)
  (text "無いの‥‥‥何者かによって、情報が根こそぎ奪われたのよ。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "そんな馬鹿な事がある？")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "多分ナナの仕事でしょう。軍のネットワークに侵入出来るハッカーなんて、そうはいないから。")
  (wait)
  (text-reset 14)
  (text "これも戦争の弊害のひとつだ。街中に「元なんとか」エキスパートがばら撒かれてしまった。")
  (wait)
  (text-reset 14)
  (text "やり難い事この上ない。しかし、解せないのは、軍のデータベースがひとりのハッカーごときに荒らされてしまったという事だ。")
  (wait)
  (text-reset 14)
  (text "そんな事は、常識では考えられない。いくらローテクのわたしでもそいつがどれ程大事なのかの判断ぐらいは出来る。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "それで、どうやって探せって言うの。経歴どころか、顔さえわからないってのに？")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "またその顔だ、誤魔化されやしないよ。そんな仕事はお断り！")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "大体あんたね、いつも人をヤバい事に巻き込んで良心は痛まない？終いにゃこれかい。そいつは駄目だ、認められないね。")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_09.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text "「加藤」" 'br)
  (text "命令だと言った。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "てめえの部下も信用出来ないくせに、偉そうにするんじゃないよ！")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "冗談じゃないね‥‥‥あんたらのケツを拭いて回る義理はない。そんな借りもないはずだよ。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "その発言は記録しておかねばならない。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "結構！　別に怖かないね。大体、この街にゃそいつらの隠れられそうな場所がごまんとあるんだよ。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "チャイナタウンや、千葉シティにでも隠れられたら、絶対に見つかりっこない。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "見つけるさ、絶対にな。もしもしくじれば、お前だけじゃなく上官であるアンナ大佐もまずい事になる。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "‥‥‥‥‥‥そん時ゃ、あんたも道連れにしてやるよ。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "キヨミ、お願いだから‥‥‥加藤さん、私が何とかしますから。この場は何とか。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "‥‥‥‥‥‥‥‥‥よかろう。")
  (wait)
  (text-reset 14)
  (text "「加藤」" 'br)
  (text "この任務は完全な極秘である、報告は私かアンナ大佐に。早速仕事にかかれ。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_10.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text "冗談じゃない、まるで雲をつかむような話だ。アンナ達はわたしに何をさせようって気なんだ。")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "キヨミ、後で私の部屋に来て。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「アンナ」" 'br)
  (text "キヨミ。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "わかったよ。")
  (wait)
  (text-reset 14)
  (nop@)
  (set-reg 50 #t)
  (exec-mem 9504 "E")
  (exec-mem 256 "E")
  (exec-mem 256 "I")
  ((cmd 209) 0 10)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (image-file "gpc¥98title.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 10)
  (delay 200)
  (sound 'se 1)
  (nop@)
  (set-reg 1000 #t)
  (flag-save 9)
  (delay 20 0)
  (sound '|| 2)
  (delay 50 0)
  (if (</>
       (// (? (= L 1)) (sound '|| 0) (mes-jump "mes¥x_menu.mes"))
       (//
        ((cmd 209) 0 5)
        (image-file "gpc¥waku.gpc")
        (image-mem 0 3)
        ((cmd 209) 1 5)
        (sound '|| 0)
        (mes-jump "mes¥MA_A01.MES"))))))