(mes
 (meta (engine 'ADV) (charset "english") (extraop #t))
 (seg*
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_09.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "..................")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Military Officer」" 'br)
  (text-delay 5)
  (text "You're not a special agent nor an important contractor." 'br)
  (text "You're just another member of the intelligence division," 'br)
  (text "nothing more.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Military Officer」" 'br)
  (text-delay 5)
  (text "You don't have the option to refuse this mission." 'br)
  (text "Is that clear?")
  (wait)
  (text-reset 14)
  (text "This asshole's name is Katou. He's a big shot in the" 'br)
  (text "military and an internal affairs inspector for" 'br)
  (text "the government.")
  (wait)
  (text-reset 14)
  (text "He's a real lowlife... the kind who sniffs other" 'br)
  (text "people's butts.")
  (wait)
  (text-reset 14)
  (text "Unlike Anna, an immigrant, or me, a dropout," 'br)
  (text "he's a proper elite.")
  (wait)
  (text-reset 14)
  (text "However, Katou and I share some qualities. Those sadistic" 'br)
  (text "eyes that sometimes shine out from under his hat remind me" 'br)
  (text "of my own.")
  (wait)
  (text-reset 14)
  (text "Plus, Katou has also avoided getting neuro-mods."'br)
  (text "I don't think his reasons are the same as mine......")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Katou」" 'br)
  (text-delay 5)
  (text "Generally, people aren't allowed to be an intelligence" 'br)
  (text "officer specializing in torture. The military doesn't" 'br)
  (text "pay you to satisfy your own desires.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Well, I happen to have quite the reputation for my technique" 'br)
  (text "in that field, thank you very much.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "Kiyomi! Just shut up and listen.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Katou」" 'br)
  (text-delay 5)
  (text "The prisoners' names are April, Lei Fa, Nana, and Mitsuko.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Katou」" 'br)
  (text-delay 5)
  (text "April was a former Special Forces member and" 'br)
  (text "European immigrant. Lei Fa was also in the same unit," 'br)
  (text "and she's Chinese.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Katou」" 'br)
  (text-delay 5)
  (text "Nana is half-Japanese and used to be a soldier" 'br)
  (text "in cyberwarfare. She was a great hacker.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Katou」" 'br)
  (text-delay 5)
  (text "The last one is Mitsuko...... she's pure Japanese.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Hold on")
  (text-delay 15)
  (text "...")
  (text-delay 5)
  (text " that's all you've got?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Katou」" 'br)
  (text-delay 5)
  (text "..................")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Not even a profile or holopic I can study?")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_08.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "It's all gone...... Someone has erased all" 'br)
  (text "the relevant information.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 15)
  (text "...")
  (text-delay 5)
  (text "you're kidding, right?" 'br)
  (text "How could you allow a breach like that?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "We believe it was Nana's doing. Not many hackers could" 'br)
  (text "break into a secure military server.")
  (wait)
  (text-reset 14)
  (text "This is just another downside of war. Now we have disgraced" 'br)
  (text "\"former experts\" scattered all over the city.")
  (wait)
  (text-reset 14)
  (text "The situation itself is hard enough to deal with, but what I" 'br)
  (text "can't wrap my head around is the fact that our military" 'br)
  (text "database was penetrated by a single hacker." 'br)
  (text "It just doesn't make sense.")
  (wait)
  (text-reset 14)
  (text "That's unbelievable. Even someone low-tech like me" 'br)
  (text "can understand how valuable that woman is.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "So, how do you expect me to hunt them down without" 'br)
  (text "even having a picture of a face?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 10)
  (text "........................")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Don't give me that face, you won't fool me again. I refuse" 'br)
  (text "to accept this mission!")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 10)
  (text "....................................")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Anna, you're always mixing people up in dangerous situations.")
  (text "Don't you feel guilty?" 'br)
  (text "No way am I letting you get me wrapped up in this.")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_09.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text-delay 0)
  (text "「Katou」" 'br)
  (text-delay 5)
  (text "I told you, this is an order.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "You can't even trust your own people, so don't act" 'br)
  (text "all high and mighty!")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "This is ridiculous")
  (text-delay 15)
  (text "... ")
  (text-delay 5)
  (text "I don't owe you anything. There's no" 'br)
  (text "reason I should be here wiping your asses for you.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Katou」" 'br)
  (text-delay 5)
  (text "Your complaints will be recorded and sent to the higher-ups.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Great! I'm not scared of them!" 'br)
  (text "Besides, this city has HUNDREDS of places those prisoners" 'br)
  (text "could be hiding!")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "If they decided to hide out in Chinatown or Chiba City," 'br)
  (text "there's no chance we'd ever find them.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Katou」" 'br)
  (text-delay 5)
  (text "We WILL find and recapture them. If you fail, it won't just" 'br)
  (text "be your ass on the line, but the Colonel's as well.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text ".........If it comes to that, I'll happily take you" 'br)
  (text "down with me.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "Kiyomi, please...... Commander Katou, please let me" 'br)
  (text "handle this. We'll come up with a solution.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Katou」" 'br)
  (text-delay 10)
  (text "............Good.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Katou」" 'br)
  (text-delay 5)
  (text "This mission is completely confidential. You will report" 'br)
  (text "either to me or Colonel Anna. Get to work immediately.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "........................")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_10.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text "This is ridiculous. It's like trying to catch a cloud." 'br)
  (text "What do they expect me to do?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "Kiyomi, come see me in my room later.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "............")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "Kiyomi.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Understood, ma'am.")
  (wait)
  (text-reset 14)
  (nop@)
  (set-reg 50 #t)
  (exec-mem 9504 "E")
  (exec-mem 256 "E")
  (exec-mem 256 "I")
  ((cmd 209) 0 10)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (image-file "gpc¥98title.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 10)
  (delay 200)
  (sound 'se 1)
  (nop@)
  (set-reg 1000 #t)
  (flag-save 9)
  (delay 20 0)
  (sound '|| 2)
  (delay 50 0)
  (if (</>
       (// (? (= L 1)) (sound '|| 0) (mes-jump "mes¥x_menu.mes"))
       (//
        ((cmd 209) 0 5)
        (image-file "gpc¥waku.gpc")
        (image-mem 0 3)
        ((cmd 209) 1 5)
        (sound '|| 0)
        (mes-jump "mes¥MA_A01.MES"))))))