(mes
 (meta (engine 'ADV) (charset "english") (extraop #t))
 (seg*
  (sound '|| 0)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (text-color 15)
  (text-frame 0 150 79 399)
  ((cmd 209) 1 5)
  (text "                          It all started 20 years ago.")
  (delay 50)
  ((cmd 209) 0 5)
  (image-file "gpc¥op_01.gpc")
  (image-mem 0 3)
  (if (</>
       (//
        (? (= O 0))
        (sound '|| 0)
        (sound '|| "uso¥xg_01.uso")
        (sound '|| 1)
        (nop@)
        (set-var P 1))
       (//
        (? (= O 1))
        (sound '|| 0)
        (sound '|| "uso¥xg_01v.uso")
        (sound '|| 1)
        (nop@)
        (set-var P 1))))
  (text-frame 10 312 70 383)
  ((cmd 209) 1 5)
  (text-delay 5)
  (text " At that time, I was still a child")
  (text-delay 0)
  (text ",")
  (text-delay 5)
  (text " and knew nothing about")
  (text-delay 0)
  (text 'br)
  (text "       ")
  (text-delay 5)
  (text "the world-changing events happening around me")
  (text-delay 0)
  (text ".")
  (delay 50)
  (text-reset 14)
  (text "             ")
  (text-delay 5)
  (text "It was the start of a long winter")
  (text-delay 0)
  (text ".")
  (delay 50)
  (text-reset 14)
  (text "            ")
  (text-delay 5)
  (text "And now, it's hard to even remember")
  (text-delay 0)
  (text 'br)
  (text "      ")
  (text-delay 5)
  (text "what it was like to look up and see sunlight...")
  (delay 50)
  (text-reset 14)
  (text "             ")
  (text-delay 5)
  ; ref: 123456789012345678901234567890|234567890123456789012345678901, not centred oops
  (text "I only remember the anxious faces")
  (text-delay 0)
  (text 'br)
  (text "               ")
  (text-delay 5)
  (text "of my mom, dad, and neighbors")
  (text-delay 0)
  (text ".")
  (delay 50)
  (text-reset 14)
  (text "          ")
  (text-delay 5)
  (text "After that, more dead animals and birds" 'br)
  (text-delay 0)
  (text "    ")
  (text-delay 5)
  (text "began appearing on the side of the road each day...")
  (delay 50)
  (text-reset 14)
  (text "      ")
  (text-delay 5)
  (text "I didn't understand how these friendly creatures" 'br)
  (text-delay 0)
  (text "                 ")
  (text-delay 5)
  (text "could all die so suddenly")
  (text-delay 0)
  (text ".")
  (delay 50)
  (text-reset 14)
  (text "               ")
  (text-delay 5)
  (text "When I asked my mom, she said" 'br)
  (text-delay 0)
  (text "     ")
  (text-delay 5)
  (text "it must be caused by the poison from our enemies")
  (text-delay 0)
  (text ".")
  (delay 50)
  (text-reset 14)
  (text "  ")
  (text-delay 5)
  (text "I didn't understand what she meant until 10 years later")
  (text-delay 0)
  (text ".")
  (delay 50)
  (text-reset 14)
  (text "          ")
  (text-delay 5)
  (text "Even now, I'm not sure why it happened")
  (text-delay 0)
  (text ".")
  (delay 50)
  (text-reset 14)
  (text "                   ")
  (text-delay 5)
  (text "But Japan declared war" 'br)
  (text-delay 0)
  (text "        ")
  (text-delay 5)
  (text "on the USA, Britain, and other major powers")
  (text-delay 0)
  (text ".")
  (delay 50)
  (text-reset 14)
  (text "   ")
  (text-delay 5)
  (text "It seems like Japan is doing quite well in maintaining" 'br)
  (text-delay 0)
  (text "           ")
  (text-delay 5)
  (text "a battlefront that spans the world...")
  (text-delay 0)
  (delay 50)
  (text-reset 14)
  (text "          ")
  (text-delay 5)
  (text "However, we've had to pay a steep price")
  (text-delay 0)
  (text ".")
  (delay 50)
  (text-reset 14)
  (text "            ")
  (text-delay 5)
  (text "To avoid the constant air raids and")
  (text-delay 0)
  (text 'br)
  (text "  ")
  (text-delay 5)
  (text "deadly germ warfare, people had to evacuate the surface")
  (text-delay 0)
  (text 'br)
  (text "              ")
  (text-delay 5)
  (text "and flee to underground cities")
  (text-delay 0)
  (text ".")
  (delay 50)
  (text-reset 14)
  (text "          ")
  (text-delay 5)
  (text "People can't leave this \"giant eggshell\"")
  (text-delay 0)
  (text 'br)
  (text "               ")
  (text-delay 5)
  (text "that has been built around us")
  (text-delay 0)
  (text ".")
  (delay 50)
  (text-reset 14)
  (text "     ")
  (text-delay 5)
  (text "Therefore, it's rare to find someone who has seen")
  (text-delay 0)
  (text 'br)
  (text "          ")
  (text-delay 5)
  (text "the outside world, regardless of whether")
  (text-delay 0)
  (text 'br)
  (text "           ")
  (text-delay 5)
  (text "they're immigrants or native Japanese")
  (text-delay 0)
  (text ".")
  (delay 50)
  (text-reset 14)
  (text "        ")
  (text-delay 5)
  (text "We will have to continue gazing at this sky")
  (text-delay 0)
  (text 'br)
  (text "    ")
  (text-delay 5)
  (text "made of concrete and chrome for a long time to come")
  (text-delay 0)
  (text ".")
  (delay 50)
  (text-reset 14)
  (text " ")
  (text-delay 5)
  (text "Vapor from the earth's crust forms a mist that covers the")
  (text-delay 0)
  (text 'br)
  (text " ")
  (text-delay 5)
  (text "area and occasionally rains down on the underground city")
  (text-delay 0)
  (text "." 'br)
  (text "        ")
  (text-delay 5)
  (text "But the rain just smells like mud and metal")
  (text-delay 0)
  (text ".")
  (delay 50)
  (text-reset 14)
  (text "     ")
  (text-delay 5)
  (text "The stagnant air crackles with static electricity")
  (text-delay 0)
  (text "." 'br)
  (text "              ")
  (text-delay 5)
  (text "Is this what thunder felt like")
  (text-delay 0)
  (text "?" 'br)
  (text "                    ")
  (text-delay 5)
  (text "I can only imagine")
  (text-delay 0)
  (text ".")
  (delay 50)
  (text-reset 14)
  (text "          ")
  (text-delay 5)
  (text "How can I explain this craving I have...")
  (text-delay 0)
  (delay 50)
  (text-reset 14)
  (text "                    ")
  (text-delay 5)
  (text "Sometimes, I dream")
  (text-delay 0)
  (text "." 'br)
  (text "           ")
  (delay 50)
  (text-delay 5)
  (text "I dream about the feeling of sunlight")
  (text-delay 0)
  (text 'br)
  (text "              ")
  (text-delay 5)
  (text "locked away in my dim memories")
  (text-delay 0)
  (text ".")
  (delay 50)
  (text-reset 14)
  ((cmd 209) 0 5)
  (text-reset 14)
  (image-file "gpc¥op_06.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (text-frame 10 312 70 393)
  (text-delay 5)
  (text "My name is Kiyomi")
  (text-delay 0)
  (text ",")
  (text-delay 5)
  (text " and I am a military intelligence officer")
  (text-delay 0)
  (text "." 'br)
  (text-delay 5)
  (text "I'm one of the sharpest people in Tokyo")
  (text-delay 0)
  (text "," 'br)
  (text-delay 5)
  (text "a city full of eccentrics")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "Once upon a time, my career and position")
  (text-delay 0)
  (text 'br)
  (text-delay 5)
  (text "in the intelligence sector meant everything to me")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "I had ambition and enthusiasm every day")
  (text-delay 0)
  (text "." 'br)
  (text-delay 5)
  (text "But now, things are different")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "I'm so sick and tired of the military")
  (text-delay 0)
  (text ".")
  (text-delay 5)
  (text " They walk around with" 'br)
  (text "disgustingly fake smiles on their faces and try to flaunt" 'br)
  (text "their power, even though they're just minor officers")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "I was not going to let myself turn into one of those" 'br)
  (text "uniformed bastards")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "When I looked in the mirror and saw that same twisted smile," 'br)
  (text "I made up my mind to leave the army")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "But they wouldn't let someone talented like me go so easily..")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "The society we live in is terribly small")
  (text-delay 0)
  (text ".")
  (text-delay 5)
  (text " The military and a" 'br)
  (text "few large corporations rule this country now")
  (text-delay 0)
  (text ".")
  (text-delay 5)
  (text " You'd have to" 'br)
  (text "be some type of nutcase to go against them")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "The only reason I'm even still allowed to live is" 'br)
  (text "because I'm a pure-blooded Japanese citizen")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "Immigrants, who make up 30\n of this city's population")
  (text-delay 0)
  (text "," 'br)
  (text-delay 5)
  (text "are treated like trash down here")
  (text-delay 0)
  (text "." 'br)
  (text 'br)
  (text-delay 5)
  (text "Above all else, it's important to be born Japanese")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "This stratified society will never change")
  (text-delay 0)
  (text ",")
  (text-delay 5)
  (text " and the lowest" 'br)
  (text "immigrant will never become more than \"just an immigrant\"" 'br)
  (text "in their whole life")
  (text-delay 0)
  (text ". ")
  (text-delay 5)
  (text "Plus, it's impossible to leave the city")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "It's no wonder the city is in ruins...")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "If I were an immigrant, I would have been killed long ago")
  (text-delay 0)
  (text "," 'br)
  (text-delay 5)
  (text "deprived of both my credit and military status")
  (text-delay 0)
  (text "." 'br)
  (text-delay 5)
  (text "Honestly, maybe I would be happier that way")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "I would rather slowly kill my brain cells in a cloud" 'br)
  (text "of purple smoke than face such a painful reality")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (image-file "gpc¥op_02.gpc")
  (image-mem 0 3)
  (text "「Girl」" 'br)
  (text-delay 5)
  (text "Ma'am...")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (text "「Girl」" 'br)
  (text-delay 5)
  (text "Hey, ma'am")
  (text-delay 0)
  (text "!!!")
  (wait)
  (text-reset 14)
  (text "「Girl」" 'br)
  (text-delay 5)
  (text "If you smoke that much at once, you'll die, okay")
  (text-delay 0)
  (text "?")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Leave me alone")
  (text-delay 0)
  (text ".")
  (text-delay 5)
  (text " You're ruining my vibe")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Girl」" 'br)
  (text-delay 5)
  (text "But I...")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Quiet")
  (text-delay 0)
  (text ".")
  (text-delay 5)
  (text " Pillows aren't supposed to talk")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "I was so close to becoming the champion of chemicals, too...")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (text "「???」" 'br)
  (text-delay 5)
  (text "I'm afraid your title match will have" 'br)
  (text "to wait until later")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (image-file "gpc¥op_03.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text "「Uniformed Man」" 'br)
  (text-delay 5)
  (text "We're here to pick you up")
  (text-delay 0)
  (text ",")
  (text-delay 5)
  (text " Major")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Hey")
  (text-delay 0)
  (text ",")
  (text-delay 5)
  (text " public servant")
  (text-delay 0)
  (text ".")
  (text-delay 5)
  (text " Been busy serving the people")
  (text-delay 0)
  (text "?")
  (wait)
  (text-reset 14)
  ;; ALL GOOD ABOVE THIS LINE
  (text-delay 5)
  (text "I recognise this guy")
  (text-delay 0)
  (text ".")
  (text-delay 5)
  (text " He's a leg-breaker who specialises in" 'br)
  (text "underground work (= illegal)")
  (text-delay 0)
  (text ",")
  (text-delay 5)
  (text " and he's one of the best guys" 'br)
  (text "in the department")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "What division was he in, again?......" 'br)
  (text "I know I looked through the profiles, but I can't" 'br)
  (text "remember a thing right now")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "I'm on vacation right now... get lost")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Uniformed Man」" 'br)
  (text-delay 5)
  (text "I regret to inform you that your vacation has been cancelled")
  (text-delay 0)
  (text "." 'br)
  (text-delay 5)
  (text "Your mission will begin shortly")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "You're being so selfish...")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (text "「Uniformed Man」" 'br)
  (text-delay 5)
  (text "Now")
  (text-delay 0)
  (text ",")
  (text-delay 5)
  (text " get rid of that pipe")
  (text-delay 0)
  (text "!")
  (text-delay 5)
  (text " We need a clear" 'br)
  (text "headed agent")
  (text-delay 0)
  (text ",")
  (text-delay 5)
  (text " not some drugged-up idiot")
  (text-delay 0)
  (text "!")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Hm")
  (text-delay 0)
  (text ",")
  (text-delay 5)
  (text " what's the difference between this and your cyber socket")
  (text-delay 0)
  (text "?")
  (text-delay 5)
  (text "Drugs are the only stimulation I'm willing to give" 'br)
  (text "to my bare brain")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Uniformed Man」" 'br)
  (text-delay 5)
  (text "......fine")
  (text-delay 0)
  (text ".")
  (text-delay 5)
  (text " It's your funeral")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Better to fry my brain than yours")
  (text-delay 0)
  (text "!")
  (text-delay 5)
  (text " Even if it kills me")
  (text-delay 0)
  (text "," 'br)
  (text-delay 5)
  (text "at least I get to choose how I go out")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Uniformed Man」" 'br)
  (text-delay 5)
  (text "......It's time to go")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "You're a nasty son of a bitch")
  (text-delay 0)
  (text ".")
  (text-delay 5)
  (text " I told you I'm not going")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Uniformed Man」" 'br)
  (text-delay 5)
  (text "I really hate playing dirty like this, but if you" 'br)
  (text "keep refusing... I'll have to report it as a failure" 'br)
  (text "to obey orders...")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "............")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (text "「Uniformed Man」" 'br)
  (text-delay 5)
  (text "This is your third violation, isn't it? I read your profile")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Are you telling me that I'll be sent to the Siberian front" 'br)
  (text "like you were")
  (text-delay 0)
  (text "?")
  (wait)
  (text-reset 14)
  (text "「Uniformed Man」" 'br)
  (text-delay 5)
  (text "Want me to take off my prosthetic leg and let you see the" 'br)
  (text "stump? Frostbite did this to me")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Cut it out")
  (text-delay 0)
  (text ".")
  (text-delay 5)
  (text " I’m not interested in seeing your little trophy")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Uniformed Man」" 'br)
  (text-delay 5)
  (text "Otherwise...... if you'd prefer something more tropical, I" 'br)
  (text "can drop you in the \"no-man's land\" of the Arabian Desert")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "No way")
  (text-delay 0)
  (text "!")
  (text-delay 5)
  (text " I'd rather not be sun-dried *or* frozen")
  (text-delay 0)
  (text "," 'br)
  (text-delay 5)
  (text "thank you very much")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Uniformed Man」" 'br)
  (text-delay 5)
  (text "Well then")
  (text-delay 0)
  (text ",")
  (text-delay 5)
  (text " let's get going")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "What a miserable world......" 'br)
  (text "I can't even take the time to enjoy myself")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (text "「Uniformed Man」" 'br)
  (text-delay 5)
  (text "I agree")
  (text-delay 0)
  (text ".")
  (wait)
  (text-reset 14)
  (mes-jump "mes¥OP_02.MES")))