(mes
 (meta (engine 'ADV) (charset "english") (extraop #t))
 (seg*
  (sound '|| 0)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (text-color 15)
  (text-frame 0 150 79 399)
  ((cmd 209) 1 5)
  (text "                          It all started 20 years ago.")
  (delay 50)
  ((cmd 209) 0 5)
  (image-file "gpc¥op_01.gpc")
  (image-mem 0 3)
  (if (</>
       (//
        (? (= O 0))
        (sound '|| 0)
        (sound '|| "uso¥xg_01.uso")
        (sound '|| 1)
        (nop@)
        (set-var P 1))
       (//
        (? (= O 1))
        (sound '|| 0)
        (sound '|| "uso¥xg_01v.uso")
        (sound '|| 1)
        (nop@)
        (set-var P 1))))
  (text-frame 10 312 70 383)
  ((cmd 209) 1 5)
  (text-delay 5)
  (text " At that time, I was still a child")
  (text-delay 0)
  (text ",")
  (text-delay 5)
  (text " and knew nothing about")
  (text-delay 0)
  (text 'br)
  (text "       ")
  (text-delay 5)
  (text "the world-changing events happening around me")
  (text-delay 0)
  (text "。")
  (delay 50)
  (text-reset 14)
  (text "          ")
  (text-delay 5)
  (text "It was the start of a long winter")
  (text-delay 0)
  (text "。")
  (delay 50)
  (text-reset 14)
  (text "　　　　   ")
  (text-delay 5)
  (text "And now, it's hard to even remember")
  (text-delay 0)
  (text 'br)
  (text "　　 ")
  (text-delay 5)
  (text "what it was like to look up and see sunlight...")
  (delay 50)
  (text-reset 14)
  (text "             ")
  (text-delay 5)
  ; ref: 123456789012345678901234567890|234567890123456789012345678901, not centred oops
  (text "I only remember the anxious faces")
  (text-delay 0)
  (text 'br)
  (text "               ")
  (text-delay 5)
  (text "of my mom, dad, and neighbors")
  (text-delay 0)
  (text "。")
  (delay 50)
  (text-reset 14)
  (text "          ")
  (text-delay 5)
  (text "After that, more dead animals and birds" 'br)
  (text-delay 0)
  (text "    ")
  (text-delay 5)
  (text "began appearing on the side of the road each day...")
  (delay 50)
  (text-reset 14)
  (text "      ")
  (text-delay 5)
  (text "I didn't understand how these friendly creatures" 'br)
  (text-delay 0)
  (text "                 ")
  (text-delay 5)
  (text "could all die so suddenly")
  (text-delay 0)
  (text "。")
  (delay 50)
  (text-reset 14)
  (text "               ")
  (text-delay 5)
  (text "When I asked my mom, she said" 'br)
  (text-delay 0)
  (text "     ")
  (text-delay 5)
  (text "it must be caused by the poison from our enemies")
  (text-delay 0)
  (text "。")
  (delay 50)
  ;; ALL GOOD ABOVE THIS LINE
  (text-reset 14)
  (text "  ")
  (text-delay 5)
  (text "I didn't understand what she meant until 10 years later")
  (text-delay 0)
  (text "。")
  (delay 50)
  (text-reset 14)
  (text "          ")
  (text-delay 5)
  (text "Even now, I'm not sure why it happened")
  (text-delay 0)
  (text "。")
  (delay 50)
  (text-reset 14)
  (text "                   ")
  (text-delay 5)
  (text "But Japan declared war" 'br)
  (text-delay 0)
  (text "        ")
  (text-delay 5)
  (text "on the USA, Britain, and other major powers")
  (text-delay 0)
  (text "。")
  (delay 50)
  (text-reset 14)
  (text "　")
  (text-delay 5)
  (text "我が国はなかなか健闘しているようで")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "世界中に広がった戦線を" 'br)
  (text-delay 0)
  (text "　　　　　　　　")
  (text-delay 5)
  (text "何とか維持しているという事")
  (text-delay 0)
  (text "‥‥‥")
  (delay 50)
  (text-reset 14)
  (text "　　　　　　")
  (text-delay 5)
  (text "しかし")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "その代償は少なくなかった")
  (text-delay 0)
  (text "。")
  (delay 50)
  (text-reset 14)
  (text "　")
  (text-delay 5)
  (text "絶え間なく続く爆撃の雨と細菌兵器の影響を避けるため")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "人々は")
  (text-delay 0)
  (text 'br)
  (text "　　")
  (text-delay 5)
  (text "地上を追われ地下都市へと移り住まなければならなかった")
  (text-delay 0)
  (text "。")
  (delay 50)
  (text-reset 14)
  (text "　")
  (text-delay 5)
  (text "人々はこの「巨大な卵の殻」から出る事は出来ない")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "だから")
  (text-delay 0)
  (text "、" 'br)
  (text-delay 5)
  (text "外の世界を見た事がある人間は希だ")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "それは日本人も移民も同じ事")
  (text-delay 0)
  (delay 50)
  (text-reset 14)
  (text-delay 5)
  (text "わたし達はこれから先もずっと")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "コンクリートとクロームで出来た")
  (text-delay 0)
  (text 'br)
  (text "　　　　　　　")
  (text-delay 5)
  (text "空を見続けなければならないのだ")
  (text-delay 0)
  (text "。")
  (delay 50)
  (text-reset 14)
  (text-delay 5)
  (text "地殻にこもった水蒸気が霧となって辺りを覆い")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "時折地下の街に雨")
  (text-delay 0)
  (text 'br)
  (text "　　　　　")
  (text-delay 5)
  (text "を降らせる")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "だが")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "雨の匂いは泥水さながら")
  (text-delay 0)
  (text "。")
  (delay 50)
  (text-reset 14)
  (text-delay 5)
  (text "淀んだ大気に空電の光が走る")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "雷とはこんな感じだったろうか")
  (text-delay 0)
  (text "？　" 'br)
  (text "　　　　　　　　　　　")
  (text-delay 5)
  (text "そんな気もする")
  (text-delay 0)
  (text "。")
  (delay 50)
  (text-reset 14)
  (text "　　　　")
  (text-delay 5)
  (text "この渇望をどう説明すればいいのだろうか")
  (text-delay 0)
  (text "‥‥‥")
  (delay 50)
  (text-reset 14)
  (text "　　　　　　　　　")
  (text-delay 5)
  (text "わたしは時々夢を見る")
  (text-delay 0)
  (text "。" 'br)
  (text "　　　")
  (text-delay 5)
  (text "おぼろげな記憶の中の")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "陽光に照らされた世界の事を")
  (text-delay 0)
  (text "。")
  (delay 50)
  (text-reset 14)
  ((cmd 209) 0 5)
  (text-reset 14)
  (image-file "gpc¥op_06.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (text-frame 10 312 70 383)
  (text-delay 5)
  (text "わたしの名前はキヨミ")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "軍人")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "情報部将校")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "変わり者だらけのこの")
  (text-delay 0)
  (text-delay 5)
  (text "東京の中でも")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "とびきりの部類に入る「切れた」人間")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "かつては情報部での地位とキャリアがわたしの全てだった")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "野心と")
  (text-delay 0)
  (text-delay 5)
  (text "熱意を持っていた")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "でも今は違う")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "軍属という奴等には")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "ほとほとうんざりだ")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "あいつらは曖昧な笑み")
  (text-delay 0)
  (text-delay 5)
  (text "を顔に張り付けながら")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "小役人さながらの醜悪さで自らの力を誇示")
  (text-delay 0)
  (text-delay 5)
  (text "しようとする")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "そんな制服野郎になるのは御免だ")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "あいつらと同じ仮面のような笑")
  (text-delay 0)
  (text-delay 5)
  (text "みを鏡の中に見つけた時")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "わたしは軍を去る決心をした")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "もっとも")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "軍がそう簡単に見逃してくれる訳もないのだが")
  (text-delay 0)
  (text "‥‥‥")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "ここはひどく閉鎖的な社会だ")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "今この国を支配しているのは")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "軍と")
  (text-delay 0)
  (text-delay 5)
  (text "一部の大企業")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "だからそれらに逆らうのはかなりの変人といえる")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "わたしが生きている事を許される主な理由は")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "私が純粋な日本人だ")
  (text-delay 0)
  (text-delay 5)
  (text "からに他ならない")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "国の人口の３０\n")
  (text "を占める移民は")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "ここではゴミ同然にしか扱われ")
  (text-delay 0)
  (text-delay 5)
  (text "ない")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "何より日本人である事が重要なのだ")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "この階級社会は決して変わる事はなく")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "一番下の移民は一生ただの")
  (text-delay 0)
  (text-delay 5)
  (text "移民")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "しかも")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "この街から出て行く事は不可能")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "街が荒廃するのも無理からぬ事だ")
  (text-delay 0)
  (text "‥‥‥")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "わたしも移民だったら")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "軍籍もクレジット素子も奪われてとっくに")
  (text-delay 0)
  (text-delay 5)
  (text "殺されているだろう")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "いや")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "その方が幸せなのかも")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "そんな辛い現実を眺めてるぐらいなら")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "紫岩の煙の中で死に行く自")
  (text-delay 0)
  (text-delay 5)
  (text "分の脳細胞に別れを告げてる方が気が晴れる")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (image-file "gpc¥op_02.gpc")
  (image-mem 0 3)
  (text "「女」" 'br)
  (text-delay 5)
  (text "お姉さま")
  (text-delay 0)
  (text "‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「女」" 'br)
  (text-delay 5)
  (text "お姉さまったら")
  (text-delay 0)
  (text "！")
  (wait)
  (text-reset 14)
  (text "「女」" 'br)
  (text-delay 5)
  (text "一度にそんなに吸ったら死んじゃうわよ")
  (text-delay 0)
  (text "？")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text-delay 5)
  (text "放っときな")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "あんたと居ると気分が壊れる")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「女」" 'br)
  (text-delay 5)
  (text "そんな")
  (text-delay 0)
  (text "‥‥‥")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text-delay 5)
  (text "枕は枕らしく黙ってるもんだよ")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text-delay 5)
  (text "もう少しで科学薬品のチャンピオンになれそうだってのにさ")
  (text-delay 0)
  (text "‥‥‥")
  (wait)
  (text-reset 14)
  (text "「軍服の男」" 'br)
  (text-delay 5)
  (text "いや")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "タイトルマッチはまた次の機会にして頂きますよ")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (image-file "gpc¥op_03.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text "「軍服の男」" 'br)
  (text-delay 5)
  (text "少佐")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "お迎えに上がりました")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text-delay 5)
  (text "よう")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "公僕")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "国民に奉仕してるかい")
  (text-delay 0)
  (text "？")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "こいつの顔には見覚えがある")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "潜入工作＝イリーガル専門の叩き上")
  (text-delay 0)
  (text-delay 5)
  (text "げ")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "部内でも特に腕っこきの一人")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "所属は何処だったか")
  (text-delay 0)
  (text "‥‥‥")
  (text-delay 5)
  (text "プロファイルには目を通したはずだけど")
  (text-delay 0)
  (text-delay 5)
  (text "記憶にない")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text-delay 5)
  (text "わたしは今")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "休暇中だよ")
  (text-delay 0)
  (text "‥‥‥")
  (text-delay 5)
  (text "失せな")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「軍服の男」" 'br)
  (text-delay 5)
  (text "休暇は取り消されました")
  (text-delay 0)
  (text "。")
  (text-delay 5)
  (text "まもなく任務＝ランが始まります")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text-delay 5)
  (text "随分勝手な事言ってくれるじゃない")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「軍服の男」" 'br)
  (text-delay 5)
  (text "さあ")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "そのパイプを置いて")
  (text-delay 0)
  (text "！　")
  (text-delay 5)
  (text "ヤク漬けの頭で職務を全う出来ると")
  (text-delay 0)
  (text-delay 5)
  (text "でも思っているのですか")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text-delay 5)
  (text "ふん")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "あんたのその電脳ソケットと何が違うっての")
  (text-delay 0)
  (text "？　")
  (text-delay 5)
  (text "ヤクはわた")
  (text-delay 0)
  (text-delay 5)
  (text "しが")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "この素っぴんの脳にくれてやる唯一の刺激さ")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「軍服の男」" 'br)
  (text-delay 0)
  (text "‥‥‥‥‥‥")
  (text-delay 5)
  (text "結構")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "命を落とすのはあなた自身ですから")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text-delay 5)
  (text "手前の「お脳」とジャムってな")
  (text-delay 0)
  (text "！　")
  (text-delay 5)
  (text "たとえそれが真実だとしても")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "それはわたしの勝手")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「軍服の男」" 'br)
  (text-delay 0)
  (text "‥‥‥‥‥‥‥‥‥‥‥‥")
  (text-delay 5)
  (text "もう時間が")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text-delay 5)
  (text "くどい野郎だね")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "行かないって言ってるだろう")
  (text-delay 0)
  (text "？")
  (wait)
  (text-reset 14)
  (text "「軍服の男」" 'br)
  (text-delay 5)
  (text "こんな汚いやり方は気が進まないが")
  (text-delay 0)
  (text "‥‥‥")
  (text-delay 5)
  (text "命令違反を報告しなけれ")
  (text-delay 0)
  (text-delay 5)
  (text "ばならない")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text "‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「軍服の男」" 'br)
  (text-delay 5)
  (text "これで３度目ですか")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "プロファイルによると")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text-delay 5)
  (text "シベリア戦線行きだって言いたいの")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "あんたみたいに")
  (text-delay 0)
  (text "？")
  (wait)
  (text-reset 14)
  (text "「軍服の男」" 'br)
  (text-delay 5)
  (text "義足を外してご覧にいれますか")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "凍傷でやられた")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text-delay 5)
  (text "よしてよ")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "ご自慢のイチモツだってお断わりよ")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「軍服の男」" 'br)
  (text-delay 5)
  (text "それとも")
  (text-delay 0)
  (text "‥‥‥")
  (text-delay 5)
  (text "熱帯がお望みなら")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "アラビア砂漠の「空白地帯」で")
  (text-delay 0)
  (text-delay 5)
  (text "もご案内しますか")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text-delay 5)
  (text "冗談じゃない")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "日干しも冷凍も御免だね")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「軍服の男」" 'br)
  (text-delay 5)
  (text "では")
  (text-delay 0)
  (text "、")
  (text-delay 5)
  (text "参りましょう")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「キヨミ」" 'br)
  (text-delay 5)
  (text "嫌な世の中だ")
  (text-delay 0)
  (text "‥‥‥")
  (text-delay 5)
  (text "ゆっくり浸ってる事も出来ない")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (text "「軍服の男」" 'br)
  (text-delay 5)
  (text "同感ですな")
  (text-delay 0)
  (text "。")
  (wait)
  (text-reset 14)
  (mes-jump "mes¥OP_02.MES")))