(mes
 (meta (engine 'ADV) (charset "english") (extraop #t))
 (seg*
  ((cmd 209) 0 0)
  (image-file "gpc¥op_04.gpc")
  (image-mem 0 3)
  (text-frame 10 312 70 393)
  ((cmd 209) 1 0)
  (text-delay 5)
  (text "We were headed to the intelligence office in Akasaka. The" 'br)
  (text "uniformed man had been quiet since we got on the AV, his" 'br)
  (text "body buried in the synthetic leather seat.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "From way up here, the streets and neon lights" 'br)
  (text "look just like the wiring on a circuitboard.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "It's so tacky, like a cheap trinket an artist threw" 'br)
  (text "together in his spare time.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "This place is the Japanese Empire's new capital. Apparently," 'br)
  (text "it used to be just a huge bomb shelter when the war started.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "It turned into a major city after it became" 'br)
  (text "too dangerous to stay aboveground.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "The city was built so quickly and recklessly that it ended up")
  (text "becoming a strange, complex place unlike anywhere else" 'br)
  (text "in the world.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Pilot」" 'br)
  (text-delay 5)
  (text "Rough air ahead. ")
  (text "Buckle up.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "The irregular vibration of the helicopter jars my head" 'br)
  (text "and makes me feel sick. It certainly doesn't help that my" 'br)
  (text "balance is already dulled from the purple rock.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "It's nauseating......")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "It would be a lot easier if I could just fall asleep," 'br)
  (text "but my brain keeps buzzing with stupid fantasies.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "Is this what it's like to look out on cyberspace?" 'br)
  (text "I have no idea, as a low-tech person.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "But I don't want to see that world. As far as I'm concerned," 'br)
  (text "the only \"reality\" is the one in front of me." 'br)
  (text "Everything else may as well be a mirage." 'br)
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "Even so, I feel cold......")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "The power that's supposed to be heating this city has been" 'br)
  (text "getting diverted somewhere else by the military." 'br)
  (delay 50)
  (text "Maybe our country is on its last legs after all.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (text "Is it time to start making my exit strategy?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  ((cmd 209) 0 5)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (image-file "gpc¥op_05.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (text-frame 10 312 70 393)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Though, where would I even go from here?")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (text "「Uniformed Man」" 'br)
  (text-delay 5)
  (text "To Colonel Anna's office.")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (text "「Uniformed Man」" 'br)
  (text-delay 5)
  (text "Hurry up! You've already kept her waiting for far too long.")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "What, so you're saying Anna was the fool who called me here?")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (image-file "gpc¥op_06.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "You should've told me earlier......")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Anna, huh......")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "That woman gives out the worst missions......")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (image-file "gpc¥op_07u.gpc")
  (image-mem 0 3)
  (exec-mem 256 "I")
  (exec-mem 256 "A 1")
  (text-reset 14)
  (text-frame 10 312 70 393)
  (image-file "gpc¥op_07d.gpc")
  (image-mem 0 3)
  (exec-mem 256 "A 0")
  ((cmd 209) 1 0)
  (load-mem "tcm¥scrh.tcm" 7072)
  (exec-mem 7072 12 16 68 287 0 1 16 17)
  (load-mem "tcm¥palch.tcm" 7072)
  (load-mem "tcm¥gpcpalch.tcm" 7936)
  (load-mem "tcm¥mbuff.tcm" 9504)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "Kiyomi")
  (text-delay 15)
  (text "... ")
  (text-delay 5)
  (text "You are VERY late.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "For your information, I was on vacation when you called me.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "But you weren't doing anything productive, right?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "You reek of purple rock. Personally, I won't just stand by" 'br)
  (text "and let my agents become junkies.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Work is work. Play is play." 'br)
  (text "Don't interfere with what I do in my free time." 'br)
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "You're not my mother, Anna. So don't act like it.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "..................")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Let's get down to business and discuss the mission. That's" 'br)
  (text "what you called me here for, right?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "Right. 4 high-security prisoners have escaped and stolen" 'br)
  (text "confidential intel. Your mission is to capture" 'br)
  (text "the prisoners and retrieve the intelligence.")
  (wait)
  (text-reset 14)
  (text "It looks like she aged 10 years since the last time" 'br)
  (text "I saw her. She never was very energetic, but this is" 'br)
  (text "a new low...")
  (wait)
  (text-reset 14)
  (text "Anna is my boss and current master." 'br)
  (text "Or mistress, I suppose.")
  (wait)
  (text-reset 14)
  (text "I've heard rumours that she's a White Russian and former" 'br)
  (text "KGB officer. Did she flee her country after the war started?")
  (wait)
  (text-reset 14)
  (text "She never talks about her past, but if those rumours are" 'br)
  (text "true")
  (text-delay 15)
  (text "... ")
  (text-delay 5)
  (text "she'd have to be at least 20 years older" 'br)
  (text "than she looks to make the math add up.")
  (wait)
  (text-reset 14)
  (text "But in this city, appearances are often decieving.")
  (wait)
  (text-reset 14)
  (text "These days, organs and skin can be replaced with" 'br)
  (text "cybernetic substitutes by any backstreet circuit-splicer.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "Of the 4 prisoners, 2 are ex-special forces." 'br)
  (text "Real killers.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "One is a former soldier, and the last was a secretary" 'br)
  (text "to a high-ranking government official.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "...and you want me to find them?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "They aren't a simple target. I'll need your" 'br)
  (text "professional tracking skills.")
  (wait)
  (text-reset 14)
  (exec-mem 256 "E")
  (exec-mem 9504 "I")
  (exec-mem 9504 "M M128")
  (exec-mem 9504 "L gpc¥op_08.gpc,KEEP")
  (exec-mem 9504 "L gpc¥op_09.gpc,KEEP")
  (exec-mem 9504 "L gpc¥op_10.gpc,KEEP")
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_10.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Hold on a minute. I haven't even accepted the mission yet.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Besides, catching criminals is *definitely* not part of" 'br)
  (text "my job. You know that.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "......This mission is completely secret. There cannot be" 'br)
  (text "any official investigation or tribunal.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "I understand, it sounds like a pretty dire situation." 'br)
  (text "But that's your problem, not mine.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "Kiyomi, this is an opportunity to do your favorite torture.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "In your dreams! I won't agree just for that.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 10)
  (text "............")
  (text-delay 5)
  (text "Don't say that.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Wait... Could I be the only agent you have?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "Irrelevant! Circumstances are what they are.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "All the more reason it's not my job. Rat hunting" 'br)
  (text "isn't my specialty.")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_08.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "Kiyomi, I don't know who else I can trust for this")
  (text-delay 10)
  (text "............")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "In the first place, isn't it quite odd that the prisoners" 'br)
  (text "were able to escape?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Crazy things and \"miracles\" that happen in this world" 'br)
  (text "don't surprise me anymore.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "Our experts think there was a mole. The security hole" 'br)
  (text "has not been closed yet.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Sorry to hear that. But it's really not my problem.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 15)
  (text "..................")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Kiyomi」" 'br)
  (text-delay 5)
  (text "Don't look at me like that. There are plenty of other people" 'br)
  (text "working for your boss whose job is to sniff people's butts!")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「Anna」" 'br)
  (text-delay 5)
  (text "Kiyomi!")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (text "「???」" 'br)
  (text-delay 5)
  (text "How much longer will you spout this nonsense?")
  (wait)
  (text-reset 14)
  (mes-jump "mes¥OP_03.MES")))